In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml/HI-Medium_accounts.csv
/kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml/LI-Small_Trans.csv
/kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml/HI-Large_accounts.csv
/kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml/HI-Large_Trans.csv
/kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml/HI-Medium_Trans.csv
/kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml/LI-Medium_accounts.csv
/kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml/HI-Small_Patterns.txt
/kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml/HI-Medium_Patterns.txt
/kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml/HI-Small_accounts.csv
/kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml/LI-Medium_Trans.csv
/kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml/HI-Large_Patterns.txt
/kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml/LI-Medium_Patterns.txt
/kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml/LI-Large_accounts.csv
/kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml/LI-Small_accounts.csv
/kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml/LI-Large_Patterns.txt
/kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml/LI-Large_Trans.csv
/kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml/LI-Small_Patterns.txt
/kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml/HI-Small_Trans.csv

In [2]:
# ============================================================
# CELL 1 — ORIGINAL HI-SMALL DISTRIBUTION DNA AUDIT
#
# SOURCE DATA ONLY:
#   HI-Small_Trans.csv
#   HI-Small_accounts.csv
#   HI-Small_Patterns.txt
#
# IMPORTANT:
#   - Does NOT use augmented data
#   - Does NOT modify any source files
#   - This becomes the baseline for the NEW generator
# ============================================================

from pathlib import Path
from collections import Counter, defaultdict
import pandas as pd
import numpy as np
import json
import re
import gc
import os

# ============================================================
# 0. LOCATE ORIGINAL IBM HI-SMALL FILES
# ============================================================

IBM_ROOT = Path(
    "/kaggle/input/datasets/ealtman2019/"
    "ibm-transactions-for-anti-money-laundering-aml"
)

if not IBM_ROOT.exists():
    raise FileNotFoundError(
        f"IBM dataset root not found:\n{IBM_ROOT}"
    )

TX_PATH = IBM_ROOT / "HI-Small_Trans.csv"
ACCOUNTS_PATH = IBM_ROOT / "HI-Small_accounts.csv"
PATTERNS_PATH = IBM_ROOT / "HI-Small_Patterns.txt"

for p in [TX_PATH, ACCOUNTS_PATH, PATTERNS_PATH]:
    if not p.exists():
        raise FileNotFoundError(
            f"Required file not found:\n{p}"
        )

print("=" * 110)
print("ORIGINAL HI-SMALL DISTRIBUTION DNA AUDIT")
print("=" * 110)

print("Transactions :", TX_PATH)
print("Accounts     :", ACCOUNTS_PATH)
print("Patterns     :", PATTERNS_PATH)
print()

# ============================================================
# 1. BASIC FILE INFORMATION
# ============================================================

print("=" * 110)
print("1. FILE INFORMATION")
print("=" * 110)

print(
    f"Transactions size : "
    f"{TX_PATH.stat().st_size / (1024**3):.3f} GB"
)

print(
    f"Accounts size     : "
    f"{ACCOUNTS_PATH.stat().st_size / (1024**2):.3f} MB"
)

print(
    f"Patterns size     : "
    f"{PATTERNS_PATH.stat().st_size / (1024**2):.3f} MB"
)

# ============================================================
# 2. LOAD HEADER
# ============================================================

header = pd.read_csv(
    TX_PATH,
    nrows=0
)

print()
print("Transaction columns:")
for i, c in enumerate(header.columns, 1):
    print(f"  {i:2d}. {c}")

# ============================================================
# 3. CONFIGURATION
# ============================================================

CHUNK_SIZE = 250_000

TX_COLS = [
    "Timestamp",
    "From Bank",
    "Account",
    "To Bank",
    "Account.1",
    "Amount Received",
    "Receiving Currency",
    "Amount Paid",
    "Payment Currency",
    "Payment Format",
    "Is Laundering"
]

# Reservoir sample size per group for approximate quantiles.
# This avoids storing all 5M amounts in memory.
RESERVOIR_SIZE = 250_000

rng = np.random.default_rng(20260919)

# ============================================================
# 4. COUNTERS / CONTAINERS
# ============================================================

total_rows = 0
legitimate_rows = 0
laundering_rows = 0

timestamp_min = None
timestamp_max = None

# categorical distributions
payment_format_counts = Counter()
receiving_currency_counts = Counter()
payment_currency_counts = Counter()

# time distributions
hour_counts = Counter()
weekday_counts = Counter()
date_counts = Counter()

# bank distributions
from_bank_counts = Counter()
to_bank_counts = Counter()
bank_pair_counts = Counter()

# account distributions
source_account_counts = Counter()
destination_account_counts = Counter()

# account-by-bank combinations
source_node_counts = Counter()
destination_node_counts = Counter()

# account string structure
account_length_counts = Counter()
bank_length_counts = Counter()

account_character_classes = Counter()

# amount diagnostics
amount_received_min = np.inf
amount_received_max = -np.inf
amount_paid_min = np.inf
amount_paid_max = -np.inf

amount_received_nan = 0
amount_paid_nan = 0

amount_ratio_equal = 0
amount_ratio_not_equal = 0

# exact duplicates
duplicate_rows_seen = 0

# ============================================================
# 5. RESERVOIR SAMPLING FUNCTION
# ============================================================

reservoirs = {
    "REAL_LEGITIMATE_received": [],
    "REAL_LAUNDERING_received": [],
    "REAL_LEGITIMATE_paid": [],
    "REAL_LAUNDERING_paid": [],
}

reservoir_seen = {
    k: 0
    for k in reservoirs
}


def reservoir_update(
    reservoir,
    seen_count,
    values,
    max_size=RESERVOIR_SIZE
):
    """
    Reservoir sampling.
    Returns updated reservoir + total seen count.
    """

    values = np.asarray(
        values,
        dtype=np.float64
    )

    values = values[
        np.isfinite(values)
    ]

    for value in values:

        seen_count += 1

        if len(reservoir) < max_size:
            reservoir.append(float(value))

        else:
            j = rng.integers(
                0,
                seen_count
            )

            if j < max_size:
                reservoir[j] = float(value)

    return reservoir, seen_count


# ============================================================
# 6. CHUNKED TRANSACTION AUDIT
# ============================================================

print()
print("=" * 110)
print("2. SCANNING ORIGINAL TRANSACTIONS")
print("=" * 110)

for chunk_no, chunk in enumerate(
    pd.read_csv(
        TX_PATH,
        usecols=TX_COLS,
        dtype=str,
        keep_default_na=False,
        chunksize=CHUNK_SIZE
    ),
    start=1
):

    total_rows += len(chunk)

    # --------------------------------------------------------
    # Normalize flags
    # --------------------------------------------------------

    laundering_mask = (
        chunk["Is Laundering"]
        .astype(str)
        .str.strip()
        == "1"
    )

    legitimate_mask = ~laundering_mask

    n_laundering = int(
        laundering_mask.sum()
    )

    n_legitimate = int(
        legitimate_mask.sum()
    )

    laundering_rows += n_laundering
    legitimate_rows += n_legitimate

    # --------------------------------------------------------
    # Exact-ish duplicate count within chunks
    # Full duplicate validation will be done separately if
    # needed; this captures duplicates occurring inside chunks.
    # --------------------------------------------------------

    duplicate_rows_seen += int(
        chunk.duplicated().sum()
    )

    # --------------------------------------------------------
    # Amounts
    # --------------------------------------------------------

    received = pd.to_numeric(
        chunk["Amount Received"],
        errors="coerce"
    )

    paid = pd.to_numeric(
        chunk["Amount Paid"],
        errors="coerce"
    )

    amount_received_nan += int(
        received.isna().sum()
    )

    amount_paid_nan += int(
        paid.isna().sum()
    )

    valid_received = received[
        received.notna()
    ]

    valid_paid = paid[
        paid.notna()
    ]

    if len(valid_received):

        amount_received_min = min(
            amount_received_min,
            float(valid_received.min())
        )

        amount_received_max = max(
            amount_received_max,
            float(valid_received.max())
        )

    if len(valid_paid):

        amount_paid_min = min(
            amount_paid_min,
            float(valid_paid.min())
        )

        amount_paid_max = max(
            amount_paid_max,
            float(valid_paid.max())
        )

    # Reservoirs
    r, seen = reservoir_update(
        reservoirs["REAL_LEGITIMATE_received"],
        reservoir_seen["REAL_LEGITIMATE_received"],
        received.loc[legitimate_mask].values
    )

    reservoirs["REAL_LEGITIMATE_received"] = r
    reservoir_seen["REAL_LEGITIMATE_received"] = seen

    r, seen = reservoir_update(
        reservoirs["REAL_LAUNDERING_received"],
        reservoir_seen["REAL_LAUNDERING_received"],
        received.loc[laundering_mask].values
    )

    reservoirs["REAL_LAUNDERING_received"] = r
    reservoir_seen["REAL_LAUNDERING_received"] = seen

    r, seen = reservoir_update(
        reservoirs["REAL_LEGITIMATE_paid"],
        reservoir_seen["REAL_LEGITIMATE_paid"],
        paid.loc[legitimate_mask].values
    )

    reservoirs["REAL_LEGITIMATE_paid"] = r
    reservoir_seen["REAL_LEGITIMATE_paid"] = seen

    r, seen = reservoir_update(
        reservoirs["REAL_LAUNDERING_paid"],
        reservoir_seen["REAL_LAUNDERING_paid"],
        paid.loc[laundering_mask].values
    )

    reservoirs["REAL_LAUNDERING_paid"] = r
    reservoir_seen["REAL_LAUNDERING_paid"] = seen

    # Amount relationship
    both_valid = (
        received.notna()
        & paid.notna()
    )

    equal_mask = (
        np.isclose(
            received.loc[both_valid].values,
            paid.loc[both_valid].values,
            rtol=0,
            atol=1e-12
        )
    )

    amount_ratio_equal += int(
        equal_mask.sum()
    )

    amount_ratio_not_equal += int(
        (~equal_mask).sum()
    )

    # --------------------------------------------------------
    # Timestamps
    # --------------------------------------------------------

    ts = pd.to_datetime(
        chunk["Timestamp"],
        errors="coerce"
    )

    valid_ts = ts.notna()

    if valid_ts.any():

        local_min = ts.loc[valid_ts].min()
        local_max = ts.loc[valid_ts].max()

        timestamp_min = (
            local_min
            if timestamp_min is None
            else min(timestamp_min, local_min)
        )

        timestamp_max = (
            local_max
            if timestamp_max is None
            else max(timestamp_max, local_max)
        )

        hour_counts.update(
            ts.loc[valid_ts].dt.hour.tolist()
        )

        weekday_counts.update(
            ts.loc[valid_ts].dt.day_name().tolist()
        )

        date_counts.update(
            ts.loc[valid_ts]
            .dt.strftime("%Y-%m-%d")
            .tolist()
        )

    # --------------------------------------------------------
    # Payment / currency
    # --------------------------------------------------------

    payment_format_counts.update(
        chunk["Payment Format"].tolist()
    )

    receiving_currency_counts.update(
        chunk["Receiving Currency"].tolist()
    )

    payment_currency_counts.update(
        chunk["Payment Currency"].tolist()
    )

    # --------------------------------------------------------
    # Banks
    # --------------------------------------------------------

    from_bank_counts.update(
        chunk["From Bank"].tolist()
    )

    to_bank_counts.update(
        chunk["To Bank"].tolist()
    )

    bank_pair_counts.update(
        zip(
            chunk["From Bank"].tolist(),
            chunk["To Bank"].tolist()
        )
    )

    # --------------------------------------------------------
    # Accounts
    # --------------------------------------------------------

    source_account_counts.update(
        chunk["Account"].tolist()
    )

    destination_account_counts.update(
        chunk["Account.1"].tolist()
    )

    source_node_counts.update(
        zip(
            chunk["From Bank"].tolist(),
            chunk["Account"].tolist()
        )
    )

    destination_node_counts.update(
        zip(
            chunk["To Bank"].tolist(),
            chunk["Account.1"].tolist()
        )
    )

    # --------------------------------------------------------
    # Account / bank ID structure
    # --------------------------------------------------------

    account_lengths = pd.concat([
        chunk["Account"].str.len(),
        chunk["Account.1"].str.len()
    ])

    account_length_counts.update(
        account_lengths.tolist()
    )

    bank_lengths = pd.concat([
        chunk["From Bank"].str.len(),
        chunk["To Bank"].str.len()
    ])

    bank_length_counts.update(
        bank_lengths.tolist()
    )

    # Character classes for accounts
    combined_accounts = pd.concat([
        chunk["Account"],
        chunk["Account.1"]
    ])

    for account in combined_accounts:

        account = str(account)

        if account.isdigit():
            account_character_classes["DIGITS_ONLY"] += 1

        elif account.isalnum() and account.isupper():
            account_character_classes["ALPHANUMERIC_UPPER"] += 1

        elif account.isalnum():
            account_character_classes["ALPHANUMERIC_MIXED"] += 1

        else:
            account_character_classes["OTHER"] += 1

    if chunk_no % 10 == 0:
        print(
            f"Processed {total_rows:,} rows..."
        )

# ============================================================
# 7. BASIC DATASET RESULTS
# ============================================================

print()
print("=" * 110)
print("3. BASIC DATASET RESULTS")
print("=" * 110)

print(
    f"Total rows        : {total_rows:,}"
)

print(
    f"Legitimate rows   : {legitimate_rows:,}"
)

print(
    f"Laundering rows   : {laundering_rows:,}"
)

print(
    f"Laundering rate   : "
    f"{laundering_rows / total_rows * 100:.8f}%"
)

print(
    f"Timestamp minimum : {timestamp_min}"
)

print(
    f"Timestamp maximum : {timestamp_max}"
)

print(
    f"Duplicate rows detected within chunks : "
    f"{duplicate_rows_seen:,}"
)

# ============================================================
# 8. UNIQUE ENTITY COUNTS
# ============================================================

print()
print("=" * 110)
print("4. UNIQUE BANK / ACCOUNT COUNTS")
print("=" * 110)

print(
    f"Unique From Banks          : "
    f"{len(from_bank_counts):,}"
)

print(
    f"Unique To Banks            : "
    f"{len(to_bank_counts):,}"
)

print(
    f"Unique source accounts     : "
    f"{len(source_account_counts):,}"
)

print(
    f"Unique destination accounts: "
    f"{len(destination_account_counts):,}"
)

print(
    f"Unique source bank+account nodes: "
    f"{len(source_node_counts):,}"
)

print(
    f"Unique destination bank+account nodes: "
    f"{len(destination_node_counts):,}"
)

print(
    f"Unique directed bank pairs : "
    f"{len(bank_pair_counts):,}"
)

# ============================================================
# 9. BANK DISTRIBUTIONS
# ============================================================

print()
print("=" * 110)
print("5. TOP SOURCE BANKS")
print("=" * 110)

top_from = (
    pd.Series(
        from_bank_counts,
        dtype="int64"
    )
    .sort_values(
        ascending=False
    )
)

top_from_df = pd.DataFrame({
    "Transactions": top_from,
    "Share_pct": (
        top_from
        / total_rows
        * 100
    )
})

print(
    top_from_df.head(50).to_string()
)

print()
print("=" * 110)
print("6. TOP DESTINATION BANKS")
print("=" * 110)

top_to = (
    pd.Series(
        to_bank_counts,
        dtype="int64"
    )
    .sort_values(
        ascending=False
    )
)

top_to_df = pd.DataFrame({
    "Transactions": top_to,
    "Share_pct": (
        top_to
        / total_rows
        * 100
    )
})

print(
    top_to_df.head(50).to_string()
)

# ============================================================
# 10. TOP BANK PAIRS
# ============================================================

print()
print("=" * 110)
print("7. TOP BANK-TO-BANK PAIRS")
print("=" * 110)

top_pairs = (
    pd.Series(
        bank_pair_counts,
        dtype="int64"
    )
    .sort_values(
        ascending=False
    )
)

top_pairs_df = pd.DataFrame({
    "Transactions": top_pairs,
    "Share_pct": (
        top_pairs
        / total_rows
        * 100
    )
})

print(
    top_pairs_df.head(100).to_string()
)

# ============================================================
# 11. AMOUNT DISTRIBUTIONS
# ============================================================

print()
print("=" * 110)
print("8. AMOUNT DISTRIBUTIONS")
print("=" * 110)

amount_summary = {}

for key, values in reservoirs.items():

    arr = np.asarray(
        values,
        dtype=np.float64
    )

    if len(arr) == 0:
        continue

    qs = np.percentile(
        arr,
        [
            0,
            1,
            5,
            10,
            25,
            50,
            75,
            90,
            95,
            99,
            99.9,
            100
        ]
    )

    amount_summary[key] = {
        "count_seen": int(
            reservoir_seen[key]
        ),
        "sample_size": int(
            len(arr)
        ),
        "min": float(qs[0]),
        "p1": float(qs[1]),
        "p5": float(qs[2]),
        "p10": float(qs[3]),
        "p25": float(qs[4]),
        "median": float(qs[5]),
        "p75": float(qs[6]),
        "p90": float(qs[7]),
        "p95": float(qs[8]),
        "p99": float(qs[9]),
        "p99_9": float(qs[10]),
        "max": float(qs[11]),
    }

    print()
    print(key)

    for k, v in amount_summary[key].items():

        if k in [
            "count_seen",
            "sample_size"
        ]:
            print(
                f"  {k:<12}: {v:,}"
            )
        else:
            print(
                f"  {k:<12}: {v:,.6f}"
            )

print()
print(
    f"Global Amount Received min/max : "
    f"{amount_received_min:,.6f} / "
    f"{amount_received_max:,.6f}"
)

print(
    f"Global Amount Paid min/max     : "
    f"{amount_paid_min:,.6f} / "
    f"{amount_paid_max:,.6f}"
)

print(
    f"Received NaN count             : "
    f"{amount_received_nan:,}"
)

print(
    f"Paid NaN count                 : "
    f"{amount_paid_nan:,}"
)

print(
    f"Paid == Received               : "
    f"{amount_ratio_equal:,}"
)

print(
    f"Paid != Received               : "
    f"{amount_ratio_not_equal:,}"
)

# ============================================================
# 12. PAYMENT FORMAT
# ============================================================

print()
print("=" * 110)
print("9. PAYMENT FORMAT DISTRIBUTION")
print("=" * 110)

payment_df = pd.DataFrame({
    "Count": pd.Series(
        payment_format_counts,
        dtype="int64"
    )
})

payment_df["Share_pct"] = (
    payment_df["Count"]
    / total_rows
    * 100
)

payment_df = payment_df.sort_values(
    "Count",
    ascending=False
)

print(
    payment_df.to_string()
)

# ============================================================
# 13. CURRENCIES
# ============================================================

print()
print("=" * 110)
print("10. RECEIVING CURRENCY DISTRIBUTION")
print("=" * 110)

receiving_currency_df = pd.DataFrame({
    "Count": pd.Series(
        receiving_currency_counts,
        dtype="int64"
    )
})

receiving_currency_df["Share_pct"] = (
    receiving_currency_df["Count"]
    / total_rows
    * 100
)

receiving_currency_df = (
    receiving_currency_df
    .sort_values(
        "Count",
        ascending=False
    )
)

print(
    receiving_currency_df.to_string()
)

print()
print("=" * 110)
print("11. PAYMENT CURRENCY DISTRIBUTION")
print("=" * 110)

payment_currency_df = pd.DataFrame({
    "Count": pd.Series(
        payment_currency_counts,
        dtype="int64"
    )
})

payment_currency_df["Share_pct"] = (
    payment_currency_df["Count"]
    / total_rows
    * 100
)

payment_currency_df = (
    payment_currency_df
    .sort_values(
        "Count",
        ascending=False
    )
)

print(
    payment_currency_df.to_string()
)

# ============================================================
# 14. TIME DISTRIBUTION
# ============================================================

print()
print("=" * 110)
print("12. HOUR-OF-DAY DISTRIBUTION")
print("=" * 110)

hour_df = pd.DataFrame({
    "Count": pd.Series(
        hour_counts,
        dtype="int64"
    )
})

hour_df.index.name = "Hour"

hour_df["Share_pct"] = (
    hour_df["Count"]
    / total_rows
    * 100
)

hour_df = hour_df.sort_index()

print(
    hour_df.to_string()
)

print()
print("=" * 110)
print("13. WEEKDAY DISTRIBUTION")
print("=" * 110)

weekday_df = pd.DataFrame({
    "Count": pd.Series(
        weekday_counts,
        dtype="int64"
    )
})

weekday_df["Share_pct"] = (
    weekday_df["Count"]
    / total_rows
    * 100
)

# chronological weekday order
weekday_order = [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday"
]

weekday_df = weekday_df.reindex(
    [
        d for d in weekday_order
        if d in weekday_df.index
    ]
)

print(
    weekday_df.to_string()
)

print()
print("=" * 110)
print("14. DAILY TRANSACTION COUNTS")
print("=" * 110)

date_df = pd.DataFrame({
    "Count": pd.Series(
        date_counts,
        dtype="int64"
    )
})

date_df["Share_pct"] = (
    date_df["Count"]
    / total_rows
    * 100
)

date_df.index.name = "Date"

date_df = date_df.sort_index()

print(
    date_df.to_string()
)

# ============================================================
# 15. ID STRUCTURE
# ============================================================

print()
print("=" * 110)
print("15. ACCOUNT ID LENGTH DISTRIBUTION")
print("=" * 110)

account_length_df = pd.DataFrame({
    "Count": pd.Series(
        account_length_counts,
        dtype="int64"
    )
})

account_length_df["Share_pct"] = (
    account_length_df["Count"]
    / account_length_df["Count"].sum()
    * 100
)

account_length_df.index.name = "Length"

print(
    account_length_df.sort_index().to_string()
)

print()
print("=" * 110)
print("16. BANK ID LENGTH DISTRIBUTION")
print("=" * 110)

bank_length_df = pd.DataFrame({
    "Count": pd.Series(
        bank_length_counts,
        dtype="int64"
    )
})

bank_length_df["Share_pct"] = (
    bank_length_df["Count"]
    / bank_length_df["Count"].sum()
    * 100
)

bank_length_df.index.name = "Length"

print(
    bank_length_df.sort_index().to_string()
)

print()
print("=" * 110)
print("17. ACCOUNT CHARACTER CLASSES")
print("=" * 110)

account_class_df = pd.DataFrame({
    "Count": pd.Series(
        account_character_classes,
        dtype="int64"
    )
})

account_class_df["Share_pct"] = (
    account_class_df["Count"]
    / account_class_df["Count"].sum()
    * 100
)

print(
    account_class_df.to_string()
)

# ============================================================
# 16. TOP ACCOUNT USAGE
# ============================================================

print()
print("=" * 110)
print("18. TOP SOURCE ACCOUNTS")
print("=" * 110)

top_source_accounts = pd.DataFrame({
    "Transactions": pd.Series(
        source_account_counts,
        dtype="int64"
    )
}).sort_values(
    "Transactions",
    ascending=False
)

top_source_accounts["Share_pct"] = (
    top_source_accounts["Transactions"]
    / total_rows
    * 100
)

print(
    top_source_accounts.head(50).to_string()
)

print()
print("=" * 110)
print("19. TOP DESTINATION ACCOUNTS")
print("=" * 110)

top_destination_accounts = pd.DataFrame({
    "Transactions": pd.Series(
        destination_account_counts,
        dtype="int64"
    )
}).sort_values(
    "Transactions",
    ascending=False
)

top_destination_accounts["Share_pct"] = (
    top_destination_accounts["Transactions"]
    / total_rows
    * 100
)

print(
    top_destination_accounts.head(50).to_string()
)

# ============================================================
# 17. ORIGINAL ACCOUNTS.CSV AUDIT
# ============================================================

print()
print("=" * 110)
print("20. ORIGINAL ACCOUNTS.CSV AUDIT")
print("=" * 110)

accounts = pd.read_csv(
    ACCOUNTS_PATH,
    dtype=str,
    keep_default_na=False
)

print(
    "Shape:",
    accounts.shape
)

print(
    "Columns:",
    list(accounts.columns)
)

for col in accounts.columns:

    unique_count = (
        accounts[col]
        .nunique()
    )

    print(
        f"  {col:<20}: "
        f"{unique_count:,} unique values"
    )

print()
print(
    "Duplicate account rows:",
    f"{accounts.duplicated().sum():,}"
)

# Canonical node count
if {
    "Bank ID",
    "Account Number"
}.issubset(accounts.columns):

    canonical_nodes = (
        accounts["Bank ID"].astype(str)
        + "\x1f"
        + accounts["Account Number"].astype(str)
    )

    print(
        "Unique Bank ID + Account Number:",
        f"{canonical_nodes.nunique():,}"
    )

# ============================================================
# 18. ORIGINAL PATTERNS.TXT AUDIT
# ============================================================

print()
print("=" * 110)
print("21. ORIGINAL PATTERNS.TXT AUDIT")
print("=" * 110)

with open(
    PATTERNS_PATH,
    "r",
    encoding="utf-8"
) as f:

    pattern_lines = [
        line.rstrip("\n")
        for line in f
    ]

print(
    "Total pattern lines:",
    f"{len(pattern_lines):,}"
)

# Exact BEGIN/END parser
episodes = []

current = None

begin_re = re.compile(
    r"BEGIN:\s*(.+)"
)

end_re = re.compile(
    r"END"
)

for line_no, line in enumerate(
    pattern_lines,
    start=1
):

    stripped = line.strip()

    m = begin_re.match(
        stripped
    )

    if m:

        if current is not None:
            raise ValueError(
                f"Nested BEGIN at line {line_no}"
            )

        current = {
            "typology": m.group(1).strip().upper(),
            "begin_line": line_no,
            "transactions": []
        }

        continue

    if end_re.fullmatch(
        stripped
    ):

        if current is None:
            raise ValueError(
                f"END without BEGIN at line {line_no}"
            )

        current["end_line"] = line_no

        episodes.append(
            current
        )

        current = None

        continue

    if current is not None:

        if stripped:
            current["transactions"].append(
                stripped
            )

if current is not None:
    raise ValueError(
        "Patterns file ended before END."
    )

pattern_episode_counts = Counter()

pattern_tx_counts = Counter()

episode_sizes = []

for ep in episodes:

    typology = ep["typology"]
    n = len(
        ep["transactions"]
    )

    pattern_episode_counts[
        typology
    ] += 1

    pattern_tx_counts[
        typology
    ] += n

    episode_sizes.append(
        n
    )

print(
    "Pattern episodes:",
    f"{len(episodes):,}"
)

print(
    "Pattern transaction rows:",
    f"{sum(episode_sizes):,}"
)

print()
print("Typology episode counts:")

for typology, count in sorted(
    pattern_episode_counts.items()
):

    tx_count = pattern_tx_counts[
        typology
    ]

    print(
        f"  {typology:<18} "
        f"episodes={count:>5,} | "
        f"transactions={tx_count:>6,} | "
        f"avg={tx_count / count:.2f}"
    )

if episode_sizes:

    print()
    print("Episode size statistics:")
    print(
        f"  min    : {min(episode_sizes)}"
    )
    print(
        f"  median : {np.median(episode_sizes):.2f}"
    )
    print(
        f"  mean   : {np.mean(episode_sizes):.2f}"
    )
    print(
        f"  p90    : {np.percentile(episode_sizes, 90):.2f}"
    )
    print(
        f"  p99    : {np.percentile(episode_sizes, 99):.2f}"
    )
    print(
        f"  max    : {max(episode_sizes)}"
    )

# ============================================================
# 19. SAVE BASELINE ARTIFACTS
# ============================================================

OUTPUT_DIR = Path(
    "/kaggle/working/AML_GNN_ONLY"
) / "data"

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# Bank distributions
top_from_df.to_csv(
    OUTPUT_DIR /
    "HI-Small_original_from_bank_distribution.csv"
)

top_to_df.to_csv(
    OUTPUT_DIR /
    "HI-Small_original_to_bank_distribution.csv"
)

top_pairs_df.to_csv(
    OUTPUT_DIR /
    "HI-Small_original_bank_pair_distribution.csv"
)

top_source_accounts.to_csv(
    OUTPUT_DIR /
    "HI-Small_original_source_account_distribution.csv"
)

top_destination_accounts.to_csv(
    OUTPUT_DIR /
    "HI-Small_original_destination_account_distribution.csv"
)

payment_df.to_csv(
    OUTPUT_DIR /
    "HI-Small_original_payment_format_distribution.csv"
)

receiving_currency_df.to_csv(
    OUTPUT_DIR /
    "HI-Small_original_receiving_currency_distribution.csv"
)

payment_currency_df.to_csv(
    OUTPUT_DIR /
    "HI-Small_original_payment_currency_distribution.csv"
)

hour_df.to_csv(
    OUTPUT_DIR /
    "HI-Small_original_hour_distribution.csv"
)

weekday_df.to_csv(
    OUTPUT_DIR /
    "HI-Small_original_weekday_distribution.csv"
)

date_df.to_csv(
    OUTPUT_DIR /
    "HI-Small_original_daily_distribution.csv"
)

account_length_df.to_csv(
    OUTPUT_DIR /
    "HI-Small_original_account_length_distribution.csv"
)

bank_length_df.to_csv(
    OUTPUT_DIR /
    "HI-Small_original_bank_length_distribution.csv"
)

account_class_df.to_csv(
    OUTPUT_DIR /
    "HI-Small_original_account_character_classes.csv"
)

# ============================================================
# 20. MASTER JSON
# ============================================================

baseline = {
    "source": {
        "transactions": str(TX_PATH),
        "accounts": str(ACCOUNTS_PATH),
        "patterns": str(PATTERNS_PATH)
    },

    "transactions": {
        "total_rows": int(total_rows),
        "legitimate_rows": int(legitimate_rows),
        "laundering_rows": int(laundering_rows),
        "laundering_rate_pct": float(
            laundering_rows / total_rows * 100
        ),
        "timestamp_min": str(timestamp_min),
        "timestamp_max": str(timestamp_max),
        "duplicate_rows_detected_within_chunks": int(
            duplicate_rows_seen
        )
    },

    "unique_counts": {
        "unique_from_banks": int(
            len(from_bank_counts)
        ),
        "unique_to_banks": int(
            len(to_bank_counts)
        ),
        "unique_source_accounts": int(
            len(source_account_counts)
        ),
        "unique_destination_accounts": int(
            len(destination_account_counts)
        ),
        "unique_source_nodes": int(
            len(source_node_counts)
        ),
        "unique_destination_nodes": int(
            len(destination_node_counts)
        ),
        "unique_bank_pairs": int(
            len(bank_pair_counts)
        )
    },

    "amounts": amount_summary,

    "amount_global": {
        "received_min": float(
            amount_received_min
        ),
        "received_max": float(
            amount_received_max
        ),
        "paid_min": float(
            amount_paid_min
        ),
        "paid_max": float(
            amount_paid_max
        ),
        "received_nan": int(
            amount_received_nan
        ),
        "paid_nan": int(
            amount_paid_nan
        ),
        "equal_received_paid": int(
            amount_ratio_equal
        ),
        "different_received_paid": int(
            amount_ratio_not_equal
        )
    },

    "payment_formats": {
        str(k): int(v)
        for k, v in payment_format_counts.items()
    },

    "receiving_currencies": {
        str(k): int(v)
        for k, v in receiving_currency_counts.items()
    },

    "payment_currencies": {
        str(k): int(v)
        for k, v in payment_currency_counts.items()
    },

    "hours": {
        str(k): int(v)
        for k, v in hour_counts.items()
    },

    "weekdays": {
        str(k): int(v)
        for k, v in weekday_counts.items()
    },

    "daily_counts": {
        str(k): int(v)
        for k, v in date_counts.items()
    },

    "account_id_lengths": {
        str(k): int(v)
        for k, v in account_length_counts.items()
    },

    "bank_id_lengths": {
        str(k): int(v)
        for k, v in bank_length_counts.items()
    },

    "account_character_classes": {
        str(k): int(v)
        for k, v in account_character_classes.items()
    },

    "patterns": {
        "episodes": int(len(episodes)),
        "transactions": int(sum(episode_sizes)),
        "episode_counts": {
            str(k): int(v)
            for k, v in pattern_episode_counts.items()
        },
        "transaction_counts": {
            str(k): int(v)
            for k, v in pattern_tx_counts.items()
        },
        "episode_size": {
            "min": int(min(episode_sizes)),
            "median": float(np.median(episode_sizes)),
            "mean": float(np.mean(episode_sizes)),
            "p90": float(
                np.percentile(
                    episode_sizes,
                    90
                )
            ),
            "p99": float(
                np.percentile(
                    episode_sizes,
                    99
                )
            ),
            "max": int(max(episode_sizes))
        }
    }
}

baseline_path = (
    OUTPUT_DIR /
    "HI-Small_original_distribution_dna.json"
)

with open(
    baseline_path,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        baseline,
        f,
        indent=2
    )

# ============================================================
# 21. FINAL
# ============================================================

print()
print("=" * 110)
print("✅ ORIGINAL HI-SMALL DISTRIBUTION DNA AUDIT COMPLETE")
print("=" * 110)

print(
    "Master baseline:",
    baseline_path
)

print()
print(
    "IMPORTANT:"
)

print(
    "The existing 10M synthetic CSV was NOT used."
)

print(
    "No source dataset was modified."
)

print(
    "This baseline will become the reference distribution "
    "for the NEW pattern-preserving generator."
)

print("=" * 110)

==============================================================================================================
ORIGINAL HI-SMALL DISTRIBUTION DNA AUDIT
==============================================================================================================
Transactions : /kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml/HI-Small_Trans.csv
Accounts     : /kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml/HI-Small_accounts.csv
Patterns     : /kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml/HI-Small_Patterns.txt

==============================================================================================================
1. FILE INFORMATION
==============================================================================================================
Transactions size : 0.443 GB
Accounts size     : 32.476 MB
Patterns size     : 0.309 MB

Transaction columns:
   1. Timestamp
   2. From Bank
   3. Account
   4. To Bank
   5. Account.1
   6. Amount Received
   7. Receiving Currency
   8. Amount Paid
   9. Payment Currency
  10. Payment Format
  11. Is Laundering

==============================================================================================================
2. SCANNING ORIGINAL TRANSACTIONS
==============================================================================================================
Processed 2,500,000 rows...
Processed 5,000,000 rows...

==============================================================================================================
3. BASIC DATASET RESULTS
==============================================================================================================
Total rows        : 5,078,345
Legitimate rows   : 5,073,168
Laundering rows   : 5,177
Laundering rate   : 0.10194266%
Timestamp minimum : 2022-09-01 00:00:00
Timestamp maximum : 2022-09-18 16:18:00
Duplicate rows detected within chunks : 9

==============================================================================================================
4. UNIQUE BANK / ACCOUNT COUNTS
==============================================================================================================
Unique From Banks          : 30,528
Unique To Banks            : 15,850
Unique source accounts     : 496,995
Unique destination accounts: 420,636
Unique source bank+account nodes: 496,999
Unique destination bank+account nodes: 420,640
Unique directed bank pairs : 283,540

==============================================================================================================
5. TOP SOURCE BANKS
==============================================================================================================
         Transactions  Share_pct
070            449859   8.858378
012             71177   1.401579
010             64791   1.275829
001             62211   1.225025
020             41008   0.807507
003             38413   0.756408
007             31086   0.612129
0211            30451   0.599624
0116            30232   0.595312
015             30027   0.591275
011             29676   0.584364
022             28652   0.564200
028             28584   0.562861
00220           28164   0.554590
023             26893   0.529562
01292           26835   0.528420
0118            24988   0.492050
0220            24253   0.477577
01362           23851   0.469661
006             22855   0.450048
0015            22484   0.442743
004             22116   0.435496
01420           21910   0.431440
0214            21727   0.427836
00410           21487   0.423110
01674           19286   0.379769
01467           19252   0.379100
0213            19235   0.378765
0119            19175   0.377584
019             18828   0.370751
01588           18745   0.369116
01665           18613   0.366517
00513           18478   0.363859
02591           17737   0.349267
02843           17450   0.343616
01601           17449   0.343596
01490           17396   0.342553
01729           17336   0.341371
01502           17268   0.340032
01522           16982   0.334400
00701           16851   0.331821
0010            16838   0.331565
01688           16697   0.328788
0117            16493   0.324771
00795           16416   0.323255
01547           16208   0.319159
0112            14794   0.291315
001068          14518   0.285881
02915           14437   0.284286
0137218         14262   0.280840

==============================================================================================================
6. TOP DESTINATION BANKS
==============================================================================================================
         Transactions  Share_pct
012             34732   0.683924
001             30115   0.593008
010             29926   0.589286
003             25627   0.504633
007             23029   0.453475
015             22730   0.447587
020             22048   0.434157
028             21160   0.416671
0211            20576   0.405171
0116            20240   0.398555
0220            16871   0.332215
0118            16448   0.323885
0015            15991   0.314886
006             15821   0.311539
004             15382   0.302894
0213            15223   0.299763
0214            14517   0.285861
01292           14122   0.278083
022             13962   0.274932
019             13870   0.273120
01362           13838   0.272490
00220           13754   0.270836
0119            13449   0.264830
011             13443   0.264712
023             13357   0.263019
0010            12621   0.248526
01588           12092   0.238109
01674           12034   0.236967
01420           12010   0.236494
00410           11742   0.231217
01688           11649   0.229386
01665           11451   0.225487
00795           11393   0.224345
00513           11307   0.222651
01729           11189   0.220328
01467           11181   0.220170
02843           11130   0.219166
01490           11029   0.217177
00701           10708   0.210856
01601           10631   0.209340
02591           10567   0.208080
01522           10551   0.207765
01547           10529   0.207331
01502           10482   0.206406
0137218         10416   0.205106
001068          10277   0.202369
02915           10189   0.200636
0117            10124   0.199356
021387          10051   0.197919
0112             9930   0.195536

==============================================================================================================
7. TOP BANK-TO-BANK PAIRS
==============================================================================================================
                 Transactions  Share_pct
015     015              7901   0.155582
003     003              7173   0.141247
010     010              7164   0.141070
001     001              6556   0.129097
012     012              6457   0.127148
0116    0116             5299   0.104345
0220    0220             4769   0.093909
020     020              4744   0.093416
0015    0015             4438   0.087391
0211    0211             4406   0.086761
028     028              4133   0.081385
007     007              4128   0.081286
0126    0126             3525   0.069412
0118    0118             3367   0.066301
0124    0124             3367   0.066301
070     012              3337   0.065710
0214    0214             3245   0.063899
006     006              3160   0.062225
004     004              3125   0.061536
0225    0225             2979   0.058661
0213    0213             2810   0.055333
019     019              2783   0.054801
0119    0119             2728   0.053718
023     023              2561   0.050430
0010    0010             2538   0.049977
070     010              2491   0.049051
        001              2465   0.048539
010     001              2461   0.048461
022     022              2421   0.047673
011     011              2399   0.047240
001     010              2382   0.046905
070     003              2335   0.045980
00220   00220            2297   0.045231
070     007              2195   0.043223
01292   01292            2179   0.042908
070     015              2081   0.040978
        028              2056   0.040486
0152416 0152416          2045   0.040269
01362   01362            2036   0.040092
0117    0116             1997   0.039324
        0117             1995   0.039284
0118    0116             1933   0.038064
005     005              1921   0.037827
014     014              1890   0.037217
0116    0137218          1873   0.036882
01420   01420            1845   0.036331
0152627 0152627          1842   0.036272
070     0211             1833   0.036094
0210    0210             1815   0.035740
070     0116             1782   0.035090
0116    0118             1782   0.035090
070     020              1774   0.034933
01674   01674            1753   0.034519
00513   00513            1732   0.034106
015     024              1729   0.034047
0112    0116             1717   0.033810
0212    0212             1695   0.033377
012     001              1693   0.033338
0116    0117             1667   0.032826
070     0220             1655   0.032589
024     015              1654   0.032570
0112    0112             1645   0.032392
0214    0213             1641   0.032314
015     009665           1619   0.031880
        021              1608   0.031664
070     022              1598   0.031467
016     016              1586   0.031231
009     009              1583   0.031172
01467   01467            1583   0.031172
00410   00410            1581   0.031132
010     012              1575   0.031014
026     026              1574   0.030994
015     029467           1573   0.030975
01665   01665            1570   0.030916
01588   01588            1568   0.030876
021     021              1567   0.030857
0113    0113             1551   0.030541
02591   02591            1550   0.030522
012     010              1548   0.030482
003     020              1544   0.030404
0071    0071             1533   0.030187
0116    0112             1527   0.030069
021     015              1526   0.030049
01601   01601            1520   0.029931
024     024              1493   0.029399
0137218 0137218          1491   0.029360
01502   01502            1475   0.029045
00701   00701            1473   0.029006
0137218 0116             1473   0.029006
070     004              1469   0.028927
01490   01490            1468   0.028907
01688   01688            1460   0.028750
01547   01547            1457   0.028690
00795   00795            1449   0.028533
027     027              1427   0.028100
070     0015             1423   0.028021
01729   01729            1404   0.027647
070     0213             1402   0.027607
015     009679           1392   0.027411
0012    0012             1390   0.027371

==============================================================================================================
8. AMOUNT DISTRIBUTIONS
==============================================================================================================

REAL_LEGITIMATE_received
  count_seen  : 5,073,168
  sample_size : 250,000
  min         : 0.000001
  p1          : 0.017339
  p5          : 6.660000
  p10         : 24.550000
  p25         : 181.370000
  median      : 1,403.955000
  p75         : 12,245.430000
  p90         : 138,192.170000
  p95         : 629,149.431500
  p99         : 14,194,518.077300
  p99_9       : 477,388,710.650778
  max         : 626,035,501,453.449951

REAL_LAUNDERING_received
  count_seen  : 5,177
  sample_size : 5,177
  min         : 0.003227
  p1          : 1.000002
  p5          : 213.970000
  p10         : 673.148000
  p25         : 2,634.970000
  median      : 8,667.210000
  p75         : 18,832.270000
  p90         : 171,438.292000
  p95         : 943,718.022000
  p99         : 23,420,046.838000
  p99_9       : 1,186,125,953.695763
  max         : 84,853,144,179.580002

REAL_LEGITIMATE_paid
  count_seen  : 5,073,168
  sample_size : 250,000
  min         : 0.000001
  p1          : 0.017456
  p5          : 6.790000
  p10         : 25.570000
  p25         : 186.180000
  median      : 1,420.425000
  p75         : 12,344.002500
  p90         : 135,758.291000
  p95         : 628,105.960000
  p99         : 13,562,985.685600
  p99_9       : 432,548,197.976378
  max         : 140,212,375,027.399994

REAL_LAUNDERING_paid
  count_seen  : 5,177
  sample_size : 5,177
  min         : 0.003227
  p1          : 1.000002
  p5          : 213.970000
  p10         : 673.148000
  p25         : 2,634.970000
  median      : 8,667.210000
  p75         : 18,832.270000
  p90         : 171,438.292000
  p95         : 943,718.022000
  p99         : 23,420,046.838000
  p99_9       : 1,186,125,953.695763
  max         : 84,853,144,179.580002

Global Amount Received min/max : 0.000001 / 1,046,302,363,293.479980
Global Amount Paid min/max     : 0.000001 / 1,046,302,363,293.479980
Received NaN count             : 0
Paid NaN count                 : 0
Paid == Received               : 5,006,187
Paid != Received               : 72,158

==============================================================================================================
9. PAYMENT FORMAT DISTRIBUTION
==============================================================================================================
                Count  Share_pct
Cheque        1864331  36.711389
Credit Card   1323324  26.058174
ACH            600797  11.830567
Cash           490891   9.666358
Reinvestment   481056   9.472692
Wire           171855   3.384075
Bitcoin        146091   2.876744

==============================================================================================================
10. RECEIVING CURRENCY DISTRIBUTION
==============================================================================================================
                     Count  Share_pct
US Dollar          1879341  37.006958
Euro               1172017  23.078720
Swiss Franc         237884   4.684282
Yuan                206551   4.067290
Shekel              194988   3.839597
Rupee               192065   3.782039
UK Pound            181255   3.569175
Ruble               157361   3.098667
Yen                 156319   3.078148
Bitcoin             148151   2.917309
Canadian Dollar     141357   2.783525
Australian Dollar   138511   2.727483
Mexican Peso        111030   2.186342
Saudi Riyal          89971   1.771660
Brazil Real          71544   1.408805

==============================================================================================================
11. PAYMENT CURRENCY DISTRIBUTION
==============================================================================================================
                     Count  Share_pct
US Dollar          1895172  37.318693
Euro               1168297  23.005467
Swiss Franc         234860   4.624735
Yuan                213752   4.209088
Shekel              192184   3.784383
Rupee               190202   3.745354
UK Pound            180738   3.558994
Yen                 155209   3.056291
Ruble               155178   3.055681
Bitcoin             146066   2.876252
Canadian Dollar     140042   2.757631
Australian Dollar   136769   2.693181
Mexican Peso        110159   2.169191
Saudi Riyal          89014   1.752815
Brazil Real          70703   1.392245

==============================================================================================================
12. HOUR-OF-DAY DISTRIBUTION
==============================================================================================================
       Count  Share_pct
Hour
0     634726  12.498678
1     193728   3.814786
2     193143   3.803267
3     193249   3.805354
4     193166   3.803720
5     193900   3.818173
6     194456   3.829121
7     193336   3.807067
8     192921   3.798895
9     192952   3.799506
10    193229   3.804960
11    193500   3.810296
12    192972   3.799899
13    192521   3.791019
14    192787   3.796256
15    194871   3.837293
16    193407   3.808465
17    193154   3.803483
18    193321   3.806772
19    192824   3.796985
20    192809   3.796690
21    192192   3.784540
22    191836   3.777530
23    193345   3.807244

==============================================================================================================
13. WEEKDAY DISTRIBUTION
==============================================================================================================
             Count  Share_pct
Monday      482931   9.509614
Tuesday     482273   9.496657
Wednesday   482872   9.508452
Thursday   1597740  31.461825
Friday     1408962  27.744511
Saturday    415730   8.186328
Sunday      207837   4.092613

==============================================================================================================
14. DAILY TRANSACTION COUNTS
==============================================================================================================
              Count  Share_pct
Date
2022-09-01  1114921  21.954416
2022-09-02   754449  14.856198
2022-09-03   207382   4.083653
2022-09-04   207430   4.084598
2022-09-05   482650   9.504081
2022-09-06   482089   9.493034
2022-09-07   482751   9.506069
2022-09-08   482773   9.506503
2022-09-09   654467  12.887407
2022-09-10   208325   4.102222
2022-09-11      396   0.007798
2022-09-12      281   0.005533
2022-09-13      184   0.003623
2022-09-14      121   0.002383
2022-09-15       46   0.000906
2022-09-16       46   0.000906
2022-09-17       23   0.000453
2022-09-18       11   0.000217

==============================================================================================================
15. ACCOUNT ID LENGTH DISTRIBUTION
==============================================================================================================
           Count  Share_pct
Length
9       10156690      100.0

==============================================================================================================
16. BANK ID LENGTH DISTRIBUTION
==============================================================================================================
          Count  Share_pct
Length
3       1442561  14.203062
4        680833   6.703296
5        746544   7.350269
6       3343316  32.917378
7       3943436  38.825995

==============================================================================================================
17. ACCOUNT CHARACTER CLASSES
==============================================================================================================
                      Count  Share_pct
ALPHANUMERIC_UPPER  9192729  90.509103
DIGITS_ONLY          963961   9.490897

==============================================================================================================
18. TOP SOURCE ACCOUNTS
==============================================================================================================
           Transactions  Share_pct
100428660        168672   3.321397
1004286A8        103018   2.028574
100428978         20497   0.403616
1004286F0         18663   0.367502
100428780         17264   0.339953
1004289C0         16794   0.330698
100428810         16426   0.323452
1004287C8         14174   0.279107
100428738         13756   0.270876
100428A51         13073   0.257426
1004288A0         12330   0.242796
100428858         11000   0.216606
1004288E8          9471   0.186498
100428A08          8290   0.163242
100428930          6431   0.126636
800058B80           351   0.006912
80006FCE0           296   0.005829
800058920           279   0.005494
80005ADE0           276   0.005435
800105F00           274   0.005395
8000C5D00           273   0.005376
800167090           271   0.005336
8001B1C30           268   0.005277
80FD2DBC0           265   0.005218
800102DD0           263   0.005179
8000F7C60           263   0.005179
803037BE0           258   0.005080
80018AE80           255   0.005021
800058470           254   0.005002
8000B8AB0           253   0.004982
8007C51F0           253   0.004982
800061BD0           251   0.004943

ValueError: min() iterable argument is empty

In [3]:
# ============================================================
# CELL 2 — INSPECT EXACT HI-SMALL PATTERNS.TXT FORMAT
#
# Purpose:
#   We need to understand the exact BEGIN / END syntax before
#   building the pattern-aware synthetic generator.
#
# NO files are modified.
# ============================================================

from pathlib import Path
import re

PATTERNS_PATH = Path(
    "/kaggle/input/datasets/ealtman2019/"
    "ibm-transactions-for-anti-money-laundering-aml/"
    "HI-Small_Patterns.txt"
)

if not PATTERNS_PATH.exists():
    raise FileNotFoundError(PATTERNS_PATH)

print("=" * 100)
print("HI-SMALL PATTERNS.TXT FORMAT INSPECTION")
print("=" * 100)

# ------------------------------------------------------------
# 1. READ RAW LINES
# ------------------------------------------------------------

with open(
    PATTERNS_PATH,
    "r",
    encoding="utf-8"
) as f:
    lines = f.readlines()

print("Total lines:", len(lines))

# ------------------------------------------------------------
# 2. PRINT FIRST 100 NON-EMPTY LINES
# ------------------------------------------------------------

print()
print("=" * 100)
print("FIRST 100 NON-EMPTY LINES")
print("=" * 100)

non_empty_counter = 0

for line_no, raw in enumerate(lines, start=1):

    stripped = raw.rstrip("\n\r")

    if not stripped.strip():
        continue

    print(
        f"{line_no:5d}: {repr(stripped)}"
    )

    non_empty_counter += 1

    if non_empty_counter >= 100:
        break

# ------------------------------------------------------------
# 3. FIND ALL LINES CONTAINING BEGIN / END
# ------------------------------------------------------------

print()
print("=" * 100)
print("BEGIN / END MARKER INSPECTION")
print("=" * 100)

begin_matches = []
end_matches = []

for line_no, raw in enumerate(lines, start=1):

    stripped = raw.strip()

    if re.search(
        r"\bBEGIN\b",
        stripped,
        flags=re.IGNORECASE
    ):
        begin_matches.append(
            (line_no, stripped)
        )

    if re.search(
        r"\bEND\b",
        stripped,
        flags=re.IGNORECASE
    ):
        end_matches.append(
            (line_no, stripped)
        )

print(
    "Lines containing BEGIN:",
    len(begin_matches)
)

print(
    "Lines containing END:",
    len(end_matches)
)

print()
print("First 30 BEGIN candidates:")

for line_no, text in begin_matches[:30]:
    print(
        f"{line_no:5d}: {repr(text)}"
    )

print()
print("First 30 END candidates:")

for line_no, text in end_matches[:30]:
    print(
        f"{line_no:5d}: {repr(text)}"
    )

# ------------------------------------------------------------
# 4. SEARCH FOR TYPOLOGY NAMES
# ------------------------------------------------------------

typologies = [
    "FAN-OUT",
    "FAN-IN",
    "CYCLE",
    "BIPARTITE",
    "STACK",
    "RANDOM",
    "SCATTER-GATHER",
    "GATHER-SCATTER",
]

print()
print("=" * 100)
print("TYPOLOGY MARKER INSPECTION")
print("=" * 100)

for typology in typologies:

    occurrences = []

    pattern = re.compile(
        re.escape(typology),
        flags=re.IGNORECASE
    )

    for line_no, raw in enumerate(
        lines,
        start=1
    ):

        if pattern.search(raw):
            occurrences.append(
                (
                    line_no,
                    raw.rstrip("\n\r")
                )
            )

    print()
    print(
        f"{typology:<18}: "
        f"{len(occurrences):,} matching lines"
    )

    for line_no, text in occurrences[:5]:
        print(
            f"    {line_no:5d}: {repr(text)}"
        )

# ------------------------------------------------------------
# 5. SHOW REPRESENTATIVE SECTIONS AROUND TYPOLOGY MARKERS
# ------------------------------------------------------------

print()
print("=" * 100)
print("REPRESENTATIVE PATTERN SECTIONS")
print("=" * 100)

shown_sections = 0
used_lines = set()

for line_no, raw in enumerate(
    lines,
    start=1
):

    upper = raw.upper()

    found_typology = None

    for typology in typologies:
        if typology in upper:
            found_typology = typology
            break

    if found_typology is None:
        continue

    # Avoid dumping overlapping sections
    if any(
        abs(line_no - x) <= 10
        for x in used_lines
    ):
        continue

    start = max(
        1,
        line_no - 3
    )

    end = min(
        len(lines),
        line_no + 12
    )

    print()
    print(
        f"--- around {found_typology} at line {line_no} ---"
    )

    for i in range(
        start,
        end + 1
    ):

        print(
            f"{i:5d}: "
            f"{repr(lines[i-1].rstrip(chr(10)+chr(13)))}"
        )

        used_lines.add(i)

    shown_sections += 1

    if shown_sections >= 8:
        break

# ------------------------------------------------------------
# 6. LOOK FOR OTHER COMMON STRUCTURAL MARKERS
# ------------------------------------------------------------

print()
print("=" * 100)
print("OTHER STRUCTURAL MARKERS")
print("=" * 100)

marker_candidates = [
    "START",
    "BEGIN",
    "END",
    "TYPE",
    "PATTERN",
    "TRANSACTION",
    "Timestamp",
    "From Bank",
    "To Bank",
    "Amount",
]

for marker in marker_candidates:

    count = sum(
        1
        for raw in lines
        if marker.lower() in raw.lower()
    )

    print(
        f"{marker:<15}: {count:,} lines"
    )

print()
print("=" * 100)
print("✅ PATTERNS FORMAT INSPECTION COMPLETE")
print("=" * 100)

print(
    "Nothing was modified."
)

print(
    "We will use the exact format revealed here "
    "for the generator/parser."
)

print("=" * 100)

====================================================================================================
HI-SMALL PATTERNS.TXT FORMAT INSPECTION
====================================================================================================
Total lines: 4319

====================================================================================================
FIRST 100 NON-EMPTY LINES
====================================================================================================
    1: 'BEGIN LAUNDERING ATTEMPT - FAN-OUT:  Max 16-degree Fan-Out'
    2: '2022/09/01 00:06,021174,800737690,012,80011F990,2848.96,Euro,2848.96,Euro,ACH,1'
    3: '2022/09/01 04:33,021174,800737690,020,80020C5B0,8630.40,Euro,8630.40,Euro,ACH,1'
    4: '2022/09/01 09:14,021174,800737690,020,80006A5E0,35642.49,Yuan,35642.49,Yuan,ACH,1'
    5: '2022/09/01 09:56,021174,800737690,00220,8007A5B70,5738987.96,US Dollar,5738987.96,US Dollar,ACH,1'
    6: '2022/09/01 11:28,021174,800737690,001244,80093C0D0,7254.53,US Dollar,7254.53,US Dollar,ACH,1'
    7: '2022/09/01 13:13,021174,800737690,00513,80078E200,6990.87,US Dollar,6990.87,US Dollar,ACH,1'
    8: '2022/09/01 14:11,021174,800737690,020,80066B990,12536.92,Euro,12536.92,Euro,ACH,1'
    9: '2022/09/02 15:40,021174,800737690,00410,8002CC310,3511.82,Euro,3511.82,Euro,ACH,1'
   10: '2022/09/02 21:23,021174,800737690,01292,8004030A0,16135.09,US Dollar,16135.09,US Dollar,ACH,1'
   11: '2022/09/02 23:10,021174,800737690,01601,800578800,12183.28,US Dollar,12183.28,US Dollar,ACH,1'
   12: '2022/09/03 09:29,021174,800737690,001,800AAF0B0,15197.45,US Dollar,15197.45,US Dollar,ACH,1'
   13: '2022/09/03 14:22,021174,800737690,01420,8006FB970,4717.76,US Dollar,4717.76,US Dollar,ACH,1'
   14: '2022/09/04 07:35,021174,800737690,010,800449990,19332.59,US Dollar,19332.59,US Dollar,ACH,1'
   15: '2022/09/04 09:10,021174,800737690,011852,800AEBA90,300.93,Euro,300.93,Euro,ACH,1'
   16: '2022/09/04 12:03,021174,800737690,010,800692550,2724.99,US Dollar,2724.99,US Dollar,ACH,1'
   17: '2022/09/04 15:48,021174,800737690,011056,8007486D0,15224.53,Euro,15224.53,Euro,ACH,1'
   18: 'END LAUNDERING ATTEMPT - FAN-OUT'
   20: 'BEGIN LAUNDERING ATTEMPT - CYCLE:  Max 10 hops'
   21: '2022/09/01 00:03,01467,8013C4030,020,80BC62F10,58702.10,Yuan,58702.10,Yuan,ACH,1'
   22: '2022/09/01 02:52,020,80BC62F10,0240229,80F025640,7332.87,Swiss Franc,7332.87,Swiss Franc,ACH,1'
   23: '2022/09/02 08:44,0240229,80F025640,0217,80FD27570,26443.70,Shekel,26443.70,Shekel,ACH,1'
   24: '2022/09/02 12:29,0217,80FD27570,0024856,8090E8EB0,10621.24,Canadian Dollar,10621.24,Canadian Dollar,ACH,1'
   25: '2022/09/03 10:20,0024856,8090E8EB0,0071,804ABCE90,637140.60,Rupee,637140.60,Rupee,ACH,1'
   26: '2022/09/03 12:08,0071,804ABCE90,0213737,805494C30,621578.18,Rupee,621578.18,Rupee,ACH,1'
   27: '2022/09/03 13:24,0213737,805494C30,014290,801B949C0,7222.58,Euro,7222.58,Euro,ACH,1'
   28: '2022/09/04 03:24,014290,801B949C0,0010057,803DE1580,892031.21,Yen,892031.21,Yen,ACH,1'
   29: '2022/09/04 09:44,0010057,803DE1580,0028628,80ACEE280,11364.12,Australian Dollar,11364.12,Australian Dollar,ACH,1'
   30: '2022/09/04 15:51,0028628,80ACEE280,01467,8013C4030,7945.55,US Dollar,7945.55,US Dollar,ACH,1'
   31: 'END LAUNDERING ATTEMPT - CYCLE'
   33: 'BEGIN LAUNDERING ATTEMPT - GATHER-SCATTER:  Max 3-degree Fan-In'
   34: '2022/09/01 00:04,0119,811C597B0,0048309,811C599A0,34254.65,Saudi Riyal,34254.65,Saudi Riyal,ACH,1'
   35: '2022/09/01 19:27,0150240,812D22980,0048309,811C599A0,5971.98,Saudi Riyal,5971.98,Saudi Riyal,ACH,1'
   36: '2022/09/04 05:06,0222,811B83280,0048309,811C599A0,50445.58,Saudi Riyal,50445.58,Saudi Riyal,ACH,1'
   37: '2022/09/04 05:03,0048309,811C599A0,0048309,811C599A0,48649.42,Saudi Riyal,48649.42,Saudi Riyal,ACH,1'
   38: '2022/09/04 14:59,0048309,811C599A0,0119,811C597B0,64379.45,Saudi Riyal,64379.45,Saudi Riyal,ACH,1'
   39: 'END LAUNDERING ATTEMPT - GATHER-SCATTER'
   41: 'BEGIN LAUNDERING ATTEMPT - STACK'
   42: '2022/09/02 12:36,0223,8000DD890,0040312,80F52D550,14153.46,Swiss Franc,14153.46,Swiss Franc,ACH,1'
   43: '2022/09/03 19:52,0040312,80F52D550,0023370,80BEA98A0,11975.53,UK Pound,11975.53,UK Pound,ACH,1'
   44: '2022/09/01 10:19,018617,8038D3520,024482,801C0F2B0,13712.96,Euro,13712.96,Euro,ACH,1'
   45: '2022/09/03 05:06,024482,801C0F2B0,0214,80C1B9E20,333126.09,Mexican Peso,333126.09,Mexican Peso,ACH,1'
   46: '2022/09/01 09:22,0040836,80F6B88B0,0016606,8064545E0,11800.69,US Dollar,11800.69,US Dollar,ACH,1'
   47: '2022/09/03 08:27,0016606,8064545E0,002454,80662A070,12331.00,US Dollar,12331.00,US Dollar,ACH,1'
   48: '2022/09/02 07:21,021749,8014BDC90,0214050,80537F610,317448.19,Rupee,317448.19,Rupee,ACH,1'
   49: '2022/09/04 19:11,0214050,80537F610,0017554,806C8F2A0,349281.29,Ruble,349281.29,Ruble,ACH,1'
   50: '2022/09/01 15:05,023842,80195DE20,002845,801E2BC20,277.59,US Dollar,277.59,US Dollar,ACH,1'
   51: '2022/09/04 09:31,002845,801E2BC20,0220504,807E97240,230.27,UK Pound,230.27,UK Pound,ACH,1'
   52: '2022/09/01 14:28,010,8009CF210,011318,8011AB110,11964.97,US Dollar,11964.97,US Dollar,ACH,1'
   53: '2022/09/03 09:33,011318,8011AB110,028255,806C7CF80,11521.43,US Dollar,11521.43,US Dollar,ACH,1'
   54: '2022/09/02 19:34,003229,803FF9220,0220271,81114D580,10295.53,US Dollar,10295.53,US Dollar,ACH,1'
   55: '2022/09/04 04:56,0220271,81114D580,013145,809BD8BC0,9743.15,US Dollar,9743.15,US Dollar,ACH,1'
   56: '2022/09/02 07:37,0115700,80B3E96E0,014099,801F8CCB0,17684.19,US Dollar,17684.19,US Dollar,ACH,1'
   57: '2022/09/03 04:39,014099,801F8CCB0,024144,801C92FF0,14819.83,Euro,14819.83,Euro,ACH,1'
   58: '2022/09/01 18:17,022806,807A61380,006179,802D53D80,16345.56,US Dollar,16345.56,US Dollar,ACH,1'
   59: '2022/09/04 01:29,006179,802D53D80,0240229,80EE2B9B0,14199.39,Swiss Franc,14199.39,Swiss Franc,ACH,1'
   60: '2022/09/01 08:40,0214,80B7347A0,00410,802D878C0,6702.62,Euro,6702.62,Euro,ACH,1'
   61: '2022/09/03 01:44,00410,802D878C0,003229,8063F5290,7617.17,US Dollar,7617.17,US Dollar,ACH,1'
   62: '2022/09/01 16:51,02591,80A1C7710,024850,80A09CF50,3724.19,Euro,3724.19,Euro,ACH,1'
   63: '2022/09/02 12:47,024850,80A09CF50,023833,8067AD0A0,4646.02,US Dollar,4646.02,US Dollar,ACH,1'
   64: 'END LAUNDERING ATTEMPT - STACK'
   66: 'BEGIN LAUNDERING ATTEMPT - GATHER-SCATTER:  Max 13-degree Fan-In'
   67: '2022/09/01 00:43,012963,80296CA20,0241869,80F390FC0,12562.68,Swiss Franc,12562.68,Swiss Franc,ACH,1'
   68: '2022/09/01 07:15,01588,801ABC430,0241869,80F390FC0,10475.35,Swiss Franc,10475.35,Swiss Franc,ACH,1'
   69: '2022/09/01 15:25,003051,8012E62B0,0241869,80F390FC0,13315.35,Swiss Franc,13315.35,Swiss Franc,ACH,1'
   70: '2022/09/01 15:32,02843,8043B07C0,0241869,80F390FC0,7999.49,Swiss Franc,7999.49,Swiss Franc,ACH,1'
   71: '2022/09/01 17:25,029788,80399CED0,0241869,80F390FC0,8430.98,Swiss Franc,8430.98,Swiss Franc,ACH,1'
   72: '2022/09/02 07:29,028183,80BF4C160,0241869,80F390FC0,295.90,Swiss Franc,295.90,Swiss Franc,ACH,1'
   73: '2022/09/02 15:44,0131167,80C21E690,0241869,80F390FC0,3354.50,Swiss Franc,3354.50,Swiss Franc,ACH,1'
   74: '2022/09/03 03:54,0129974,80FE25690,0241869,80F390FC0,9547.03,Swiss Franc,9547.03,Swiss Franc,ACH,1'
   75: '2022/09/03 07:12,003051,806A3D750,0241869,80F390FC0,2024.65,Swiss Franc,2024.65,Swiss Franc,ACH,1'
   76: '2022/09/03 11:07,0013157,805CA5A30,0241869,80F390FC0,4513.56,Swiss Franc,4513.56,Swiss Franc,ACH,1'
   77: '2022/09/03 14:28,001047,8031B5390,0241869,80F390FC0,12427.99,Swiss Franc,12427.99,Swiss Franc,ACH,1'
   78: '2022/09/04 14:07,0214050,80543C3C0,0241869,80F390FC0,1514.49,Swiss Franc,1514.49,Swiss Franc,ACH,1'
   79: '2022/09/04 16:21,001501,808C45FE0,0241869,80F390FC0,10058.54,Swiss Franc,10058.54,Swiss Franc,ACH,1'
   80: '2022/09/04 16:37,0241869,80F390FC0,007548,805284730,11674.83,Euro,11674.83,Euro,ACH,1'
   81: '2022/09/04 17:23,0241869,80F390FC0,01467,801D43090,4832.76,US Dollar,4832.76,US Dollar,ACH,1'
   82: '2022/09/06 18:07,0241869,80F390FC0,022736,807DC76A0,6240.05,US Dollar,6240.05,US Dollar,ACH,1'
   83: '2022/09/06 19:16,0241869,80F390FC0,0129974,80E0D4970,7782.25,US Dollar,7782.25,US Dollar,ACH,1'
   84: 'END LAUNDERING ATTEMPT - GATHER-SCATTER'
   86: 'BEGIN LAUNDERING ATTEMPT - RANDOM:  Max 5 hops'
   87: '2022/09/01 01:57,0048309,81239C5C0,0032564,80C50EE70,4986.94,Mexican Peso,4986.94,Mexican Peso,ACH,1'
   88: '2022/09/01 08:59,0032564,80C50EE70,004,806EE41E0,19454.87,Ruble,19454.87,Ruble,ACH,1'
   89: '2022/09/02 19:32,004,806EE41E0,019593,8038A9100,1573.91,Yuan,1573.91,Yuan,ACH,1'
   90: '2022/09/03 14:44,019593,8038A9100,009129,80B4D3030,219.12,US Dollar,219.12,US Dollar,ACH,1'
   91: '2022/09/04 16:35,009129,80B4D3030,01420,8016E2C30,219.12,US Dollar,219.12,US Dollar,ACH,1'
   92: 'END LAUNDERING ATTEMPT - RANDOM'
   94: 'BEGIN LAUNDERING ATTEMPT - CYCLE:  Max 10 hops'
   95: '2022/09/01 01:56,013057,80DED0520,0211,80A451570,26390.87,Australian Dollar,26390.87,Australian Dollar,ACH,1'
   96: '2022/09/01 03:35,0211,80A451570,0017401,80D179410,19934.49,US Dollar,19934.49,US Dollar,ACH,1'
   97: '2022/09/01 16:58,0017401,80D179410,0028663,80A976860,28163.45,Australian Dollar,28163.45,Australian Dollar,ACH,1'
   98: '2022/09/01 17:21,0028663,80A976860,00795,80BAEB330,23674.70,US Dollar,23674.70,US Dollar,ACH,1'
   99: '2022/09/02 00:27,00795,80BAEB330,0017753,806D399E0,23102.65,US Dollar,23102.65,US Dollar,ACH,1'
  100: '2022/09/03 13:44,0017753,806D399E0,027,80BE74FC0,488461.69,Mexican Peso,488461.69,Mexican Peso,ACH,1'
  101: '2022/09/03 18:35,027,80BE74FC0,0239692,80EA93ED0,21138.93,Swiss Franc,21138.93,Swiss Franc,ACH,1'
  102: '2022/09/04 01:34,0239692,80EA93ED0,001124,8079EC940,25434.28,US Dollar,25434.28,US Dollar,ACH,1'
  103: '2022/09/04 13:55,001124,8079EC940,027103,80F93F560,19959.31,Euro,19959.31,Euro,ACH,1'
  104: '2022/09/04 18:29,027103,80F93F560,013057,80DED0520,19959.31,Euro,19959.31,Euro,ACH,1'
  105: 'END LAUNDERING ATTEMPT - CYCLE'
  107: 'BEGIN LAUNDERING ATTEMPT - FAN-OUT:  Max 12-degree Fan-Out'

====================================================================================================
BEGIN / END MARKER INSPECTION
====================================================================================================
Lines containing BEGIN: 370
Lines containing END: 370

First 30 BEGIN candidates:
    1: 'BEGIN LAUNDERING ATTEMPT - FAN-OUT:  Max 16-degree Fan-Out'
   20: 'BEGIN LAUNDERING ATTEMPT - CYCLE:  Max 10 hops'
   33: 'BEGIN LAUNDERING ATTEMPT - GATHER-SCATTER:  Max 3-degree Fan-In'
   41: 'BEGIN LAUNDERING ATTEMPT - STACK'
   66: 'BEGIN LAUNDERING ATTEMPT - GATHER-SCATTER:  Max 13-degree Fan-In'
   86: 'BEGIN LAUNDERING ATTEMPT - RANDOM:  Max 5 hops'
   94: 'BEGIN LAUNDERING ATTEMPT - CYCLE:  Max 10 hops'
  107: 'BEGIN LAUNDERING ATTEMPT - FAN-OUT:  Max 12-degree Fan-Out'
  122: 'BEGIN LAUNDERING ATTEMPT - FAN-OUT:  Max 2-degree Fan-Out'
  127: 'BEGIN LAUNDERING ATTEMPT - BIPARTITE'
  143: 'BEGIN LAUNDERING ATTEMPT - RANDOM:  Max 8 hops'
  154: 'BEGIN LAUNDERING ATTEMPT - GATHER-SCATTER:  Max 2-degree Fan-In'
  161: 'BEGIN LAUNDERING ATTEMPT - FAN-IN:  Max 2-degree Fan-In'
  166: 'BEGIN LAUNDERING ATTEMPT - BIPARTITE'
  181: 'BEGIN LAUNDERING ATTEMPT - FAN-IN:  Max 16-degree Fan-In'
  200: 'BEGIN LAUNDERING ATTEMPT - GATHER-SCATTER:  Max 2-degree Fan-In'
  211: 'BEGIN LAUNDERING ATTEMPT - RANDOM:  Max 3 hops'
  217: 'BEGIN LAUNDERING ATTEMPT - SCATTER-GATHER'
  252: 'BEGIN LAUNDERING ATTEMPT - CYCLE:  Max 10 hops'
  265: 'BEGIN LAUNDERING ATTEMPT - FAN-IN:  Max 10-degree Fan-In'
  278: 'BEGIN LAUNDERING ATTEMPT - FAN-IN:  Max 2-degree Fan-In'
  283: 'BEGIN LAUNDERING ATTEMPT - STACK'
  288: 'BEGIN LAUNDERING ATTEMPT - BIPARTITE'
  292: 'BEGIN LAUNDERING ATTEMPT - CYCLE:  Max 2 hops'
  297: 'BEGIN LAUNDERING ATTEMPT - BIPARTITE'
  301: 'BEGIN LAUNDERING ATTEMPT - BIPARTITE'
  315: 'BEGIN LAUNDERING ATTEMPT - FAN-OUT:  Max 13-degree Fan-Out'
  331: 'BEGIN LAUNDERING ATTEMPT - BIPARTITE'
  339: 'BEGIN LAUNDERING ATTEMPT - GATHER-SCATTER:  Max 12-degree Fan-In'
  367: 'BEGIN LAUNDERING ATTEMPT - CYCLE:  Max 3 hops'

First 30 END candidates:
   18: 'END LAUNDERING ATTEMPT - FAN-OUT'
   31: 'END LAUNDERING ATTEMPT - CYCLE'
   39: 'END LAUNDERING ATTEMPT - GATHER-SCATTER'
   64: 'END LAUNDERING ATTEMPT - STACK'
   84: 'END LAUNDERING ATTEMPT - GATHER-SCATTER'
   92: 'END LAUNDERING ATTEMPT - RANDOM'
  105: 'END LAUNDERING ATTEMPT - CYCLE'
  120: 'END LAUNDERING ATTEMPT - FAN-OUT'
  125: 'END LAUNDERING ATTEMPT - FAN-OUT'
  141: 'END LAUNDERING ATTEMPT - BIPARTITE'
  152: 'END LAUNDERING ATTEMPT - RANDOM'
  159: 'END LAUNDERING ATTEMPT - GATHER-SCATTER'
  164: 'END LAUNDERING ATTEMPT - FAN-IN'
  179: 'END LAUNDERING ATTEMPT - BIPARTITE'
  198: 'END LAUNDERING ATTEMPT - FAN-IN'
  209: 'END LAUNDERING ATTEMPT - GATHER-SCATTER'
  215: 'END LAUNDERING ATTEMPT - RANDOM'
  250: 'END LAUNDERING ATTEMPT - SCATTER-GATHER'
  263: 'END LAUNDERING ATTEMPT - CYCLE'
  276: 'END LAUNDERING ATTEMPT - FAN-IN'
  281: 'END LAUNDERING ATTEMPT - FAN-IN'
  286: 'END LAUNDERING ATTEMPT - STACK'
  290: 'END LAUNDERING ATTEMPT - BIPARTITE'
  295: 'END LAUNDERING ATTEMPT - CYCLE'
  299: 'END LAUNDERING ATTEMPT - BIPARTITE'
  313: 'END LAUNDERING ATTEMPT - BIPARTITE'
  329: 'END LAUNDERING ATTEMPT - FAN-OUT'
  337: 'END LAUNDERING ATTEMPT - BIPARTITE'
  365: 'END LAUNDERING ATTEMPT - GATHER-SCATTER'
  371: 'END LAUNDERING ATTEMPT - CYCLE'

====================================================================================================
TYPOLOGY MARKER INSPECTION
====================================================================================================

FAN-OUT           : 96 matching lines
        1: 'BEGIN LAUNDERING ATTEMPT - FAN-OUT:  Max 16-degree Fan-Out'
       18: 'END LAUNDERING ATTEMPT - FAN-OUT'
      107: 'BEGIN LAUNDERING ATTEMPT - FAN-OUT:  Max 12-degree Fan-Out'
      120: 'END LAUNDERING ATTEMPT - FAN-OUT'
      122: 'BEGIN LAUNDERING ATTEMPT - FAN-OUT:  Max 2-degree Fan-Out'

FAN-IN            : 131 matching lines
       33: 'BEGIN LAUNDERING ATTEMPT - GATHER-SCATTER:  Max 3-degree Fan-In'
       66: 'BEGIN LAUNDERING ATTEMPT - GATHER-SCATTER:  Max 13-degree Fan-In'
      154: 'BEGIN LAUNDERING ATTEMPT - GATHER-SCATTER:  Max 2-degree Fan-In'
      161: 'BEGIN LAUNDERING ATTEMPT - FAN-IN:  Max 2-degree Fan-In'
      164: 'END LAUNDERING ATTEMPT - FAN-IN'

CYCLE             : 108 matching lines
       20: 'BEGIN LAUNDERING ATTEMPT - CYCLE:  Max 10 hops'
       31: 'END LAUNDERING ATTEMPT - CYCLE'
       94: 'BEGIN LAUNDERING ATTEMPT - CYCLE:  Max 10 hops'
      105: 'END LAUNDERING ATTEMPT - CYCLE'
      252: 'BEGIN LAUNDERING ATTEMPT - CYCLE:  Max 10 hops'

BIPARTITE         : 98 matching lines
      127: 'BEGIN LAUNDERING ATTEMPT - BIPARTITE'
      141: 'END LAUNDERING ATTEMPT - BIPARTITE'
      166: 'BEGIN LAUNDERING ATTEMPT - BIPARTITE'
      179: 'END LAUNDERING ATTEMPT - BIPARTITE'
      288: 'BEGIN LAUNDERING ATTEMPT - BIPARTITE'

STACK             : 86 matching lines
       41: 'BEGIN LAUNDERING ATTEMPT - STACK'
       64: 'END LAUNDERING ATTEMPT - STACK'
      283: 'BEGIN LAUNDERING ATTEMPT - STACK'
      286: 'END LAUNDERING ATTEMPT - STACK'
      402: 'BEGIN LAUNDERING ATTEMPT - STACK'

RANDOM            : 82 matching lines
       86: 'BEGIN LAUNDERING ATTEMPT - RANDOM:  Max 5 hops'
       92: 'END LAUNDERING ATTEMPT - RANDOM'
      143: 'BEGIN LAUNDERING ATTEMPT - RANDOM:  Max 8 hops'
      152: 'END LAUNDERING ATTEMPT - RANDOM'
      211: 'BEGIN LAUNDERING ATTEMPT - RANDOM:  Max 3 hops'

SCATTER-GATHER    : 88 matching lines
      217: 'BEGIN LAUNDERING ATTEMPT - SCATTER-GATHER'
      250: 'END LAUNDERING ATTEMPT - SCATTER-GATHER'
      549: 'BEGIN LAUNDERING ATTEMPT - SCATTER-GATHER'
      564: 'END LAUNDERING ATTEMPT - SCATTER-GATHER'
      663: 'BEGIN LAUNDERING ATTEMPT - SCATTER-GATHER'

GATHER-SCATTER    : 102 matching lines
       33: 'BEGIN LAUNDERING ATTEMPT - GATHER-SCATTER:  Max 3-degree Fan-In'
       39: 'END LAUNDERING ATTEMPT - GATHER-SCATTER'
       66: 'BEGIN LAUNDERING ATTEMPT - GATHER-SCATTER:  Max 13-degree Fan-In'
       84: 'END LAUNDERING ATTEMPT - GATHER-SCATTER'
      154: 'BEGIN LAUNDERING ATTEMPT - GATHER-SCATTER:  Max 2-degree Fan-In'

====================================================================================================
REPRESENTATIVE PATTERN SECTIONS
====================================================================================================

--- around FAN-OUT at line 1 ---
    1: 'BEGIN LAUNDERING ATTEMPT - FAN-OUT:  Max 16-degree Fan-Out'
    2: '2022/09/01 00:06,021174,800737690,012,80011F990,2848.96,Euro,2848.96,Euro,ACH,1'
    3: '2022/09/01 04:33,021174,800737690,020,80020C5B0,8630.40,Euro,8630.40,Euro,ACH,1'
    4: '2022/09/01 09:14,021174,800737690,020,80006A5E0,35642.49,Yuan,35642.49,Yuan,ACH,1'
    5: '2022/09/01 09:56,021174,800737690,00220,8007A5B70,5738987.96,US Dollar,5738987.96,US Dollar,ACH,1'
    6: '2022/09/01 11:28,021174,800737690,001244,80093C0D0,7254.53,US Dollar,7254.53,US Dollar,ACH,1'
    7: '2022/09/01 13:13,021174,800737690,00513,80078E200,6990.87,US Dollar,6990.87,US Dollar,ACH,1'
    8: '2022/09/01 14:11,021174,800737690,020,80066B990,12536.92,Euro,12536.92,Euro,ACH,1'
    9: '2022/09/02 15:40,021174,800737690,00410,8002CC310,3511.82,Euro,3511.82,Euro,ACH,1'
   10: '2022/09/02 21:23,021174,800737690,01292,8004030A0,16135.09,US Dollar,16135.09,US Dollar,ACH,1'
   11: '2022/09/02 23:10,021174,800737690,01601,800578800,12183.28,US Dollar,12183.28,US Dollar,ACH,1'
   12: '2022/09/03 09:29,021174,800737690,001,800AAF0B0,15197.45,US Dollar,15197.45,US Dollar,ACH,1'
   13: '2022/09/03 14:22,021174,800737690,01420,8006FB970,4717.76,US Dollar,4717.76,US Dollar,ACH,1'

--- around CYCLE at line 31 ---
   28: '2022/09/04 03:24,014290,801B949C0,0010057,803DE1580,892031.21,Yen,892031.21,Yen,ACH,1'
   29: '2022/09/04 09:44,0010057,803DE1580,0028628,80ACEE280,11364.12,Australian Dollar,11364.12,Australian Dollar,ACH,1'
   30: '2022/09/04 15:51,0028628,80ACEE280,01467,8013C4030,7945.55,US Dollar,7945.55,US Dollar,ACH,1'
   31: 'END LAUNDERING ATTEMPT - CYCLE'
   32: ''
   33: 'BEGIN LAUNDERING ATTEMPT - GATHER-SCATTER:  Max 3-degree Fan-In'
   34: '2022/09/01 00:04,0119,811C597B0,0048309,811C599A0,34254.65,Saudi Riyal,34254.65,Saudi Riyal,ACH,1'
   35: '2022/09/01 19:27,0150240,812D22980,0048309,811C599A0,5971.98,Saudi Riyal,5971.98,Saudi Riyal,ACH,1'
   36: '2022/09/04 05:06,0222,811B83280,0048309,811C599A0,50445.58,Saudi Riyal,50445.58,Saudi Riyal,ACH,1'
   37: '2022/09/04 05:03,0048309,811C599A0,0048309,811C599A0,48649.42,Saudi Riyal,48649.42,Saudi Riyal,ACH,1'
   38: '2022/09/04 14:59,0048309,811C599A0,0119,811C597B0,64379.45,Saudi Riyal,64379.45,Saudi Riyal,ACH,1'
   39: 'END LAUNDERING ATTEMPT - GATHER-SCATTER'
   40: ''
   41: 'BEGIN LAUNDERING ATTEMPT - STACK'
   42: '2022/09/02 12:36,0223,8000DD890,0040312,80F52D550,14153.46,Swiss Franc,14153.46,Swiss Franc,ACH,1'
   43: '2022/09/03 19:52,0040312,80F52D550,0023370,80BEA98A0,11975.53,UK Pound,11975.53,UK Pound,ACH,1'

--- around STACK at line 64 ---
   61: '2022/09/03 01:44,00410,802D878C0,003229,8063F5290,7617.17,US Dollar,7617.17,US Dollar,ACH,1'
   62: '2022/09/01 16:51,02591,80A1C7710,024850,80A09CF50,3724.19,Euro,3724.19,Euro,ACH,1'
   63: '2022/09/02 12:47,024850,80A09CF50,023833,8067AD0A0,4646.02,US Dollar,4646.02,US Dollar,ACH,1'
   64: 'END LAUNDERING ATTEMPT - STACK'
   65: ''
   66: 'BEGIN LAUNDERING ATTEMPT - GATHER-SCATTER:  Max 13-degree Fan-In'
   67: '2022/09/01 00:43,012963,80296CA20,0241869,80F390FC0,12562.68,Swiss Franc,12562.68,Swiss Franc,ACH,1'
   68: '2022/09/01 07:15,01588,801ABC430,0241869,80F390FC0,10475.35,Swiss Franc,10475.35,Swiss Franc,ACH,1'
   69: '2022/09/01 15:25,003051,8012E62B0,0241869,80F390FC0,13315.35,Swiss Franc,13315.35,Swiss Franc,ACH,1'
   70: '2022/09/01 15:32,02843,8043B07C0,0241869,80F390FC0,7999.49,Swiss Franc,7999.49,Swiss Franc,ACH,1'

In [4]:
# ============================================================
# CELL 2 — ORIGINAL HI-SMALL CONDITIONAL / BEHAVIORAL DNA
#
# This cell answers:
#
#   "How does a normal account/bank/entity behave?"
#
# We will later use these empirical distributions to generate:
#   - NEW realistic account IDs
#   - NEW realistic bank assignments
#   - realistic transaction frequency
#   - realistic account reuse
#   - realistic entity/account relationships
#   - realistic timing
#
# SOURCE:
#   Original HI-Small only
#
# NO synthetic data is generated here.
# NO source file is modified.
# ============================================================

from pathlib import Path
from collections import Counter, defaultdict
import pandas as pd
import numpy as np
import json
import re
import gc

# ============================================================
# 0. PATHS
# ============================================================

IBM_ROOT = Path(
    "/kaggle/input/datasets/ealtman2019/"
    "ibm-transactions-for-anti-money-laundering-aml"
)

TX_PATH = IBM_ROOT / "HI-Small_Trans.csv"
ACCOUNTS_PATH = IBM_ROOT / "HI-Small_accounts.csv"

if not TX_PATH.exists():
    raise FileNotFoundError(TX_PATH)

if not ACCOUNTS_PATH.exists():
    raise FileNotFoundError(ACCOUNTS_PATH)

print("=" * 110)
print("ORIGINAL HI-SMALL CONDITIONAL / BEHAVIORAL DNA")
print("=" * 110)
print()
print("Transactions:", TX_PATH)
print("Accounts    :", ACCOUNTS_PATH)

# ============================================================
# 1. LOAD ORIGINAL ACCOUNTS
# ============================================================

accounts = pd.read_csv(
    ACCOUNTS_PATH,
    dtype=str,
    keep_default_na=False
)

accounts["Bank ID"] = (
    accounts["Bank ID"]
    .astype(str)
    .str.strip()
)

accounts["Account Number"] = (
    accounts["Account Number"]
    .astype(str)
    .str.strip()
)

accounts["Entity ID"] = (
    accounts["Entity ID"]
    .astype(str)
    .str.strip()
)

accounts["Bank Name"] = (
    accounts["Bank Name"]
    .astype(str)
    .str.strip()
)

accounts["Entity Name"] = (
    accounts["Entity Name"]
    .astype(str)
    .str.strip()
)

print()
print("=" * 110)
print("1. ORIGINAL ACCOUNT / ENTITY STRUCTURE")
print("=" * 110)

print(
    "Account rows:",
    f"{len(accounts):,}"
)

print(
    "Unique banks:",
    f"{accounts['Bank ID'].nunique():,}"
)

print(
    "Unique entities:",
    f"{accounts['Entity ID'].nunique():,}"
)

# ============================================================
# 2. ACCOUNTS PER ENTITY
# ============================================================

accounts_per_entity = (
    accounts
    .groupby("Entity ID")
    .size()
)

print()
print("Accounts per entity:")

for stat_name, value in {
    "min": accounts_per_entity.min(),
    "p25": accounts_per_entity.quantile(.25),
    "median": accounts_per_entity.median(),
    "mean": accounts_per_entity.mean(),
    "p75": accounts_per_entity.quantile(.75),
    "p90": accounts_per_entity.quantile(.90),
    "p95": accounts_per_entity.quantile(.95),
    "p99": accounts_per_entity.quantile(.99),
    "max": accounts_per_entity.max(),
}.items():

    print(
        f"  {stat_name:<8}: {value:.3f}"
    )

print()
print("Entity account-count frequency:")
print(
    accounts_per_entity
    .value_counts()
    .sort_index()
    .head(30)
    .to_string()
)

# ============================================================
# 3. ENTITIES WITH MULTIPLE BANKS
# ============================================================

banks_per_entity = (
    accounts
    .groupby("Entity ID")["Bank ID"]
    .nunique()
)

multi_bank_entities = (
    banks_per_entity >= 2
)

print()
print(
    "Entities with >=2 bank relationships:",
    f"{multi_bank_entities.sum():,}"
)

print(
    "Percentage of entities with >=2 banks:",
    f"{multi_bank_entities.mean()*100:.4f}%"
)

print(
    "Maximum banks associated with one entity:",
    f"{banks_per_entity.max():,}"
)

# ============================================================
# 4. ACCOUNTS PER BANK
# ============================================================

accounts_per_bank = (
    accounts
    .groupby("Bank ID")
    .size()
    .sort_values(
        ascending=False
    )
)

print()
print("=" * 110)
print("2. ACCOUNTS PER BANK")
print("=" * 110)

for stat_name, value in {
    "min": accounts_per_bank.min(),
    "p25": accounts_per_bank.quantile(.25),
    "median": accounts_per_bank.median(),
    "mean": accounts_per_bank.mean(),
    "p75": accounts_per_bank.quantile(.75),
    "p90": accounts_per_bank.quantile(.90),
    "p95": accounts_per_bank.quantile(.95),
    "p99": accounts_per_bank.quantile(.99),
    "max": accounts_per_bank.max(),
}.items():

    print(
        f"  {stat_name:<8}: {value:.3f}"
    )

print()
print("Top 30 banks by number of accounts:")

bank_account_df = pd.DataFrame({
    "Account_Count": accounts_per_bank
})

bank_account_df["Share_of_Accounts_pct"] = (
    bank_account_df["Account_Count"]
    / len(accounts)
    * 100
)

print(
    bank_account_df
    .head(30)
    .to_string()
)

# ============================================================
# 5. BANK NAME RELATIONSHIP
# ============================================================

bank_name_per_id = (
    accounts
    .groupby("Bank ID")["Bank Name"]
    .nunique()
)

print()
print("=" * 110)
print("3. BANK ID → BANK NAME STRUCTURE")
print("=" * 110)

print(
    "Bank IDs with exactly one Bank Name:",
    f"{(bank_name_per_id == 1).sum():,}"
)

print(
    "Bank IDs with multiple Bank Names:",
    f"{(bank_name_per_id > 1).sum():,}"
)

# ============================================================
# 6. ACCOUNT ID CHARACTER / LENGTH STRUCTURE
# ============================================================

account_lengths = (
    accounts["Account Number"]
    .str.len()
)

print()
print("=" * 110)
print("4. ORIGINAL ACCOUNT ID STRUCTURE")
print("=" * 110)

print(
    "Unique account ID values:",
    f"{accounts['Account Number'].nunique():,}"
)

print()
print("Lengths:")
print(
    account_lengths
    .value_counts()
    .sort_index()
    .to_string()
)

digit_only_accounts = (
    accounts["Account Number"]
    .str.fullmatch(r"\d+")
)

uppercase_alnum_accounts = (
    accounts["Account Number"]
    .str.fullmatch(r"[A-Z0-9]+")
)

print()
print(
    "Digits only:",
    f"{digit_only_accounts.sum():,}",
    f"({digit_only_accounts.mean()*100:.4f}%)"
)

print(
    "Uppercase alphanumeric:",
    f"{uppercase_alnum_accounts.sum():,}",
    f"({uppercase_alnum_accounts.mean()*100:.4f}%)"
)

print()
print("Sample real account IDs:")

for value in (
    accounts["Account Number"]
    .drop_duplicates()
    .sample(
        min(30, accounts["Account Number"].nunique()),
        random_state=20260919
    )
    .tolist()
):
    print(" ", value)

# ============================================================
# 7. ENTITY ID / ENTITY NAME STRUCTURE
# ============================================================

print()
print("=" * 110)
print("5. ENTITY ID STRUCTURE")
print("=" * 110)

print(
    "Unique Entity IDs:",
    f"{accounts['Entity ID'].nunique():,}"
)

print(
    "Unique Entity Names:",
    f"{accounts['Entity Name'].nunique():,}"
)

print(
    "Entity ID == Entity Name unique-count:",
    accounts["Entity ID"].nunique()
    == accounts["Entity Name"].nunique()
)

# ============================================================
# 8. TRANSACTION ACTIVITY COUNTERS
# ============================================================

print()
print("=" * 110)
print("6. SCANNING ORIGINAL TRANSACTION ACTIVITY")
print("=" * 110)

CHUNK_SIZE = 250_000

usecols = [
    "Timestamp",
    "From Bank",
    "Account",
    "To Bank",
    "Account.1",
    "Is Laundering"
]

source_account_counts = Counter()
destination_account_counts = Counter()

source_bank_counts = Counter()
destination_bank_counts = Counter()

source_node_counts = Counter()
destination_node_counts = Counter()

laundering_source_account_counts = Counter()
laundering_destination_account_counts = Counter()

laundering_source_bank_counts = Counter()
laundering_destination_bank_counts = Counter()

legitimate_source_account_counts = Counter()
legitimate_destination_account_counts = Counter()

legitimate_source_bank_counts = Counter()
legitimate_destination_bank_counts = Counter()

# For active account inter-arrival samples
#
# We keep only timestamps for a bounded sample of accounts so
# memory remains safe.
MAX_ACTIVE_ACCOUNTS = 50_000

active_account_timestamps = defaultdict(list)

rng = np.random.default_rng(20260919)

total_rows = 0
legitimate_rows = 0
laundering_rows = 0

for chunk_no, chunk in enumerate(
    pd.read_csv(
        TX_PATH,
        usecols=usecols,
        dtype=str,
        keep_default_na=False,
        chunksize=CHUNK_SIZE
    ),
    start=1
):

    total_rows += len(chunk)

    laundering_mask = (
        chunk["Is Laundering"]
        .astype(str)
        .str.strip()
        == "1"
    )

    legitimate_mask = ~laundering_mask

    legitimate_rows += int(
        legitimate_mask.sum()
    )

    laundering_rows += int(
        laundering_mask.sum()
    )

    # --------------------------------------------------------
    # SOURCE ACCOUNT
    # --------------------------------------------------------

    source_account_counts.update(
        chunk["Account"].tolist()
    )

    destination_account_counts.update(
        chunk["Account.1"].tolist()
    )

    # --------------------------------------------------------
    # SOURCE / DESTINATION BANK
    # --------------------------------------------------------

    source_bank_counts.update(
        chunk["From Bank"].tolist()
    )

    destination_bank_counts.update(
        chunk["To Bank"].tolist()
    )

    # --------------------------------------------------------
    # BANK + ACCOUNT NODE
    # --------------------------------------------------------

    source_node_counts.update(
        zip(
            chunk["From Bank"].tolist(),
            chunk["Account"].tolist()
        )
    )

    destination_node_counts.update(
        zip(
            chunk["To Bank"].tolist(),
            chunk["Account.1"].tolist()
        )
    )

    # --------------------------------------------------------
    # LAUNDERING
    # --------------------------------------------------------

    laundering = chunk.loc[
        laundering_mask
    ]

    legitimate = chunk.loc[
        legitimate_mask
    ]

    laundering_source_account_counts.update(
        laundering["Account"].tolist()
    )

    laundering_destination_account_counts.update(
        laundering["Account.1"].tolist()
    )

    laundering_source_bank_counts.update(
        laundering["From Bank"].tolist()
    )

    laundering_destination_bank_counts.update(
        laundering["To Bank"].tolist()
    )

    # --------------------------------------------------------
    # LEGITIMATE
    # --------------------------------------------------------

    legitimate_source_account_counts.update(
        legitimate["Account"].tolist()
    )

    legitimate_destination_account_counts.update(
        legitimate["Account.1"].tolist()
    )

    legitimate_source_bank_counts.update(
        legitimate["From Bank"].tolist()
    )

    legitimate_destination_bank_counts.update(
        legitimate["To Bank"].tolist()
    )

    # --------------------------------------------------------
    # ACCOUNT TIMESTAMP SAMPLE
    # --------------------------------------------------------

    # Only a bounded set of accounts is tracked.
    #
    # This gives us a representative inter-arrival sample
    # without storing timestamps for every account.
    if len(active_account_timestamps) < MAX_ACTIVE_ACCOUNTS:

        ts = pd.to_datetime(
            chunk["Timestamp"],
            errors="coerce"
        )

        for account, timestamp in zip(
            chunk["Account"],
            ts
        ):

            if pd.isna(timestamp):
                continue

            if account not in active_account_timestamps:

                if len(
                    active_account_timestamps
                ) < MAX_ACTIVE_ACCOUNTS:

                    active_account_timestamps[
                        account
                    ] = [
                        timestamp
                    ]

            else:

                # Store at most 100 timestamps per account.
                if len(
                    active_account_timestamps[account]
                ) < 100:

                    active_account_timestamps[
                        account
                    ].append(
                        timestamp
                    )

    if chunk_no % 10 == 0:
        print(
            f"Processed {total_rows:,} rows..."
        )

# ============================================================
# 9. BASIC ACTIVITY RESULTS
# ============================================================

print()
print("=" * 110)
print("7. TRANSACTION ACTIVITY RESULTS")
print("=" * 110)

print(
    "Total rows:",
    f"{total_rows:,}"
)

print(
    "Legitimate:",
    f"{legitimate_rows:,}"
)

print(
    "Laundering:",
    f"{laundering_rows:,}"
)

# ============================================================
# 10. ACCOUNT TRANSACTION COUNT DISTRIBUTIONS
# ============================================================

def summarize_counter(
    counter,
    name
):

    s = pd.Series(
        counter,
        dtype="int64"
    )

    if len(s) == 0:
        return None

    summary = {
        "count": int(len(s)),
        "min": float(s.min()),
        "p25": float(s.quantile(.25)),
        "median": float(s.median()),
        "mean": float(s.mean()),
        "p75": float(s.quantile(.75)),
        "p90": float(s.quantile(.90)),
        "p95": float(s.quantile(.95)),
        "p99": float(s.quantile(.99)),
        "max": float(s.max())
    }

    print()
    print(name)

    for k, v in summary.items():

        if k == "count":
            print(
                f"  {k:<8}: {int(v):,}"
            )
        else:
            print(
                f"  {k:<8}: {v:.3f}"
            )

    return summary


print()
print("=" * 110)
print("8. SOURCE ACCOUNT ACTIVITY")
print("=" * 110)

source_account_summary = summarize_counter(
    source_account_counts,
    "ALL SOURCE ACCOUNTS"
)

legit_source_account_summary = summarize_counter(
    legitimate_source_account_counts,
    "LEGITIMATE SOURCE ACCOUNTS"
)

launder_source_account_summary = summarize_counter(
    laundering_source_account_counts,
    "LAUNDERING SOURCE ACCOUNTS"
)

print()
print("=" * 110)
print("9. DESTINATION ACCOUNT ACTIVITY")
print("=" * 110)

destination_account_summary = summarize_counter(
    destination_account_counts,
    "ALL DESTINATION ACCOUNTS"
)

legit_destination_account_summary = summarize_counter(
    legitimate_destination_account_counts,
    "LEGITIMATE DESTINATION ACCOUNTS"
)

launder_destination_account_summary = summarize_counter(
    laundering_destination_account_counts,
    "LAUNDERING DESTINATION ACCOUNTS"
)

# ============================================================
# 11. BANK ACTIVITY DISTRIBUTIONS
# ============================================================

print()
print("=" * 110)
print("10. SOURCE BANK ACTIVITY")
print("=" * 110)

source_bank_summary = summarize_counter(
    source_bank_counts,
    "ALL SOURCE BANKS"
)

legit_source_bank_summary = summarize_counter(
    legitimate_source_bank_counts,
    "LEGITIMATE SOURCE BANKS"
)

launder_source_bank_summary = summarize_counter(
    laundering_source_bank_counts,
    "LAUNDERING SOURCE BANKS"
)

print()
print("=" * 110)
print("11. DESTINATION BANK ACTIVITY")
print("=" * 110)

destination_bank_summary = summarize_counter(
    destination_bank_counts,
    "ALL DESTINATION BANKS"
)

legit_destination_bank_summary = summarize_counter(
    legitimate_destination_bank_counts,
    "LEGITIMATE DESTINATION BANKS"
)

launder_destination_bank_summary = summarize_counter(
    laundering_destination_bank_counts,
    "LAUNDERING DESTINATION BANKS"
)

# ============================================================
# 12. TOP ACCOUNT ACTIVITY
# ============================================================

print()
print("=" * 110)
print("12. TOP SOURCE ACCOUNTS BY TRANSACTION COUNT")
print("=" * 110)

top_source_accounts = pd.DataFrame({
    "Transactions": pd.Series(
        source_account_counts,
        dtype="int64"
    )
}).sort_values(
    "Transactions",
    ascending=False
)

top_source_accounts["Share_pct"] = (
    top_source_accounts["Transactions"]
    / total_rows
    * 100
)

print(
    top_source_accounts.head(50).to_string()
)

print()
print("=" * 110)
print("13. TOP SOURCE ACCOUNTS — LEGITIMATE ONLY")
print("=" * 110)

top_legit_source_accounts = pd.DataFrame({
    "Transactions": pd.Series(
        legitimate_source_account_counts,
        dtype="int64"
    )
}).sort_values(
    "Transactions",
    ascending=False
)

top_legit_source_accounts["Share_pct"] = (
    top_legit_source_accounts["Transactions"]
    / legitimate_rows
    * 100
)

print(
    top_legit_source_accounts.head(50).to_string()
)

print()
print("=" * 110)
print("14. TOP SOURCE ACCOUNTS — LAUNDERING")
print("=" * 110)

top_launder_source_accounts = pd.DataFrame({
    "Transactions": pd.Series(
        laundering_source_account_counts,
        dtype="int64"
    )
}).sort_values(
    "Transactions",
    ascending=False
)

top_launder_source_accounts["Share_pct"] = (
    top_launder_source_accounts["Transactions"]
    / laundering_rows
    * 100
)

print(
    top_launder_source_accounts.head(50).to_string()
)

# ============================================================
# 13. INTER-ARRIVAL TIME DISTRIBUTION
# ============================================================

print()
print("=" * 110)
print("15. ACCOUNT INTER-ARRIVAL TIME")
print("=" * 110)

interarrival_minutes = []

for account, timestamps in (
    active_account_timestamps.items()
):

    if len(timestamps) < 2:
        continue

    timestamps = sorted(
        timestamps
    )

    diffs = pd.Series(
        timestamps
    ).diff()

    mins = (
        diffs
        .dropna()
        .dt.total_seconds()
        / 60.0
    )

    interarrival_minutes.extend(
        mins[
            np.isfinite(mins)
        ].tolist()
    )

if interarrival_minutes:

    interarrival = np.asarray(
        interarrival_minutes,
        dtype=np.float64
    )

    print(
        "Sampled inter-arrivals:",
        f"{len(interarrival):,}"
    )

    for q in [
        1,
        5,
        10,
        25,
        50,
        75,
        90,
        95,
        99,
        99.9
    ]:

        print(
            f"  p{q:<4}: "
            f"{np.percentile(interarrival, q):,.4f} minutes"
        )

    print(
        "  max  :",
        f"{np.max(interarrival):,.4f} minutes"
    )

else:

    print(
        "⚠️ No inter-arrival samples available."
    )

# ============================================================
# 14. ACTIVITY BUCKETS
# ============================================================

print()
print("=" * 110)
print("16. ACCOUNT ACTIVITY BUCKETS")
print("=" * 110)

activity = pd.Series(
    source_account_counts,
    dtype="int64"
)

activity_buckets = pd.cut(
    activity,
    bins=[
        0,
        1,
        2,
        5,
        10,
        25,
        50,
        100,
        250,
        500,
        1000,
        np.inf
    ],
    right=True
)

bucket_summary = (
    activity_buckets
    .value_counts()
    .sort_index()
)

bucket_df = pd.DataFrame({
    "Accounts": bucket_summary
})

bucket_df["Share_pct"] = (
    bucket_df["Accounts"]
    / len(activity)
    * 100
)

print(
    bucket_df.to_string()
)

# ============================================================
# 15. BANK ACTIVITY BUCKETS
# ============================================================

print()
print("=" * 110)
print("17. BANK ACTIVITY BUCKETS")
print("=" * 110)

bank_activity = pd.Series(
    source_bank_counts,
    dtype="int64"
)

bank_activity_buckets = pd.cut(
    bank_activity,
    bins=[
        0,
        100,
        500,
        1000,
        5000,
        10000,
        25000,
        50000,
        100000,
        250000,
        np.inf
    ],
    right=True
)

bank_bucket_df = pd.DataFrame({
    "Banks": (
        bank_activity_buckets
        .value_counts()
        .sort_index()
    )
})

bank_bucket_df["Share_pct"] = (
    bank_bucket_df["Banks"]
    / len(bank_activity)
    * 100
)

print(
    bank_bucket_df.to_string()
)

# ============================================================
# 16. SAVE BEHAVIORAL DNA
# ============================================================

OUTPUT_DIR = Path(
    "/kaggle/working/AML_GNN_ONLY/data"
)

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# Save top-account activity tables
top_source_accounts.to_csv(
    OUTPUT_DIR /
    "HI-Small_behavior_top_source_accounts.csv"
)

top_legit_source_accounts.to_csv(
    OUTPUT_DIR /
    "HI-Small_behavior_top_legitimate_source_accounts.csv"
)

top_launder_source_accounts.to_csv(
    OUTPUT_DIR /
    "HI-Small_behavior_top_laundering_source_accounts.csv"
)

bank_account_df.to_csv(
    OUTPUT_DIR /
    "HI-Small_behavior_accounts_per_bank.csv"
)

bucket_df.to_csv(
    OUTPUT_DIR /
    "HI-Small_behavior_account_activity_buckets.csv"
)

bank_bucket_df.to_csv(
    OUTPUT_DIR /
    "HI-Small_behavior_bank_activity_buckets.csv"
)

# ============================================================
# 17. MASTER JSON
# ============================================================

behavioral_dna = {
    "source_transactions": str(TX_PATH),
    "source_accounts": str(ACCOUNTS_PATH),

    "transaction_counts": {
        "total": int(total_rows),
        "legitimate": int(legitimate_rows),
        "laundering": int(laundering_rows)
    },

    "accounts": {
        "rows": int(len(accounts)),
        "unique_accounts": int(
            accounts["Account Number"].nunique()
        ),
        "unique_banks": int(
            accounts["Bank ID"].nunique()
        ),
        "unique_entities": int(
            accounts["Entity ID"].nunique()
        )
    },

    "entity_structure": {
        "accounts_per_entity": {
            "min": float(accounts_per_entity.min()),
            "p25": float(accounts_per_entity.quantile(.25)),
            "median": float(accounts_per_entity.median()),
            "mean": float(accounts_per_entity.mean()),
            "p75": float(accounts_per_entity.quantile(.75)),
            "p90": float(accounts_per_entity.quantile(.90)),
            "p95": float(accounts_per_entity.quantile(.95)),
            "p99": float(accounts_per_entity.quantile(.99)),
            "max": float(accounts_per_entity.max())
        },
        "entities_with_multiple_banks": int(
            multi_bank_entities.sum()
        ),
        "percentage_entities_with_multiple_banks": float(
            multi_bank_entities.mean() * 100
        ),
        "max_banks_per_entity": int(
            banks_per_entity.max()
        )
    },

    "accounts_per_bank": {
        "min": float(accounts_per_bank.min()),
        "p25": float(accounts_per_bank.quantile(.25)),
        "median": float(accounts_per_bank.median()),
        "mean": float(accounts_per_bank.mean()),
        "p75": float(accounts_per_bank.quantile(.75)),
        "p90": float(accounts_per_bank.quantile(.90)),
        "p95": float(accounts_per_bank.quantile(.95)),
        "p99": float(accounts_per_bank.quantile(.99)),
        "max": float(accounts_per_bank.max())
    },

    "account_id_structure": {
        "length_distribution": {
            str(k): int(v)
            for k, v in (
                account_lengths
                .value_counts()
                .sort_index()
                .items()
            )
        },
        "digits_only": int(
            digit_only_accounts.sum()
        ),
        "uppercase_alphanumeric": int(
            uppercase_alnum_accounts.sum()
        )
    },

    "source_account_activity": {
        "all": source_account_summary,
        "legitimate": legit_source_account_summary,
        "laundering": launder_source_account_summary
    },

    "destination_account_activity": {
        "all": destination_account_summary,
        "legitimate": legit_destination_account_summary,
        "laundering": launder_destination_account_summary
    },

    "source_bank_activity": {
        "all": source_bank_summary,
        "legitimate": legit_source_bank_summary,
        "laundering": launder_source_bank_summary
    },

    "destination_bank_activity": {
        "all": destination_bank_summary,
        "legitimate": legit_destination_bank_summary,
        "laundering": launder_destination_bank_summary
    },

    "interarrival_minutes": {
        "sample_size": int(
            len(interarrival_minutes)
        ),
        "p1": float(np.percentile(interarrival, 1))
        if interarrival_minutes else None,
        "p5": float(np.percentile(interarrival, 5))
        if interarrival_minutes else None,
        "p10": float(np.percentile(interarrival, 10))
        if interarrival_minutes else None,
        "p25": float(np.percentile(interarrival, 25))
        if interarrival_minutes else None,
        "median": float(np.percentile(interarrival, 50))
        if interarrival_minutes else None,
        "p75": float(np.percentile(interarrival, 75))
        if interarrival_minutes else None,
        "p90": float(np.percentile(interarrival, 90))
        if interarrival_minutes else None,
        "p95": float(np.percentile(interarrival, 95))
        if interarrival_minutes else None,
        "p99": float(np.percentile(interarrival, 99))
        if interarrival_minutes else None,
        "p99_9": float(np.percentile(interarrival, 99.9))
        if interarrival_minutes else None,
        "max": float(np.max(interarrival))
        if interarrival_minutes else None
    }
}

DNA_PATH = (
    OUTPUT_DIR /
    "HI-Small_original_behavioral_dna.json"
)

with open(
    DNA_PATH,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        behavioral_dna,
        f,
        indent=2
    )

# ============================================================
# 18. CLEANUP
# ============================================================

del accounts
del source_account_counts
del destination_account_counts
del source_bank_counts
del destination_bank_counts
del source_node_counts
del destination_node_counts
del legitimate_source_account_counts
del legitimate_destination_account_counts
del laundering_source_account_counts
del laundering_destination_account_counts
del active_account_timestamps

gc.collect()

# ============================================================
# FINAL
# ============================================================

print()
print("=" * 110)
print("✅ CONDITIONAL / BEHAVIORAL DNA AUDIT COMPLETE")
print("=" * 110)

print(
    "Master behavioral DNA:",
    DNA_PATH
)

print()
print(
    "This is now the empirical reference for the NEW generator."
)

print(
    "No synthetic transactions were generated."
)

print(
    "No original source files were modified."
)

print("=" * 110)

==============================================================================================================
ORIGINAL HI-SMALL CONDITIONAL / BEHAVIORAL DNA
==============================================================================================================

Transactions: /kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml/HI-Small_Trans.csv
Accounts    : /kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml/HI-Small_accounts.csv

==============================================================================================================
1. ORIGINAL ACCOUNT / ENTITY STRUCTURE
==============================================================================================================
Account rows: 518,581
Unique banks: 30,470
Unique entities: 166,207

Accounts per entity:
  min     : 1.000
  p25     : 1.000
  median  : 1.000
  mean    : 3.120
  p75     : 3.000
  p90     : 6.000
  p95     : 7.000
  p99     : 14.000
  max     : 7820.000

Entity account-count frequency:
1     102689
2      15732
3      11443
4       9840
5       8573
6       6173
7       4271
8       2524
9       1420
10       802
11       438
12       299
13       192
14       165
15       112
16       111
17        98
18        78
19        59
20        70
21        61
22        77
23        46
24        60
25        40
26        43
27        40
28        38
29        26
30        18

Entities with >=2 bank relationships: 63,362
Percentage of entities with >=2 banks: 38.1223%
Maximum banks associated with one entity: 1,185

==============================================================================================================
2. ACCOUNTS PER BANK
==============================================================================================================
  min     : 1.000
  p25     : 2.000
  median  : 4.000
  mean    : 17.019
  p75     : 7.000
  p90     : 13.000
  p95     : 31.000
  p99     : 372.620
  max     : 3161.000

Top 30 banks by number of accounts:
         Account_Count  Share_of_Accounts_pct
Bank ID
12                3161               0.609548
10                3108               0.599328
15                3051               0.588336
220               2530               0.487870
1                 2172               0.418835
3                 1777               0.342666
7                 1665               0.321068
20                1625               0.313355
28                1542               0.297350
116               1514               0.291951
211               1507               0.290601
1665              1496               0.288480
118               1218               0.234872
6                 1166               0.224844
213               1128               0.217517
214               1105               0.213081
14                1104               0.212889
4                 1100               0.212117
22                1039               0.200354
1362              1033               0.199197
19                1031               0.198812
23                1023               0.197269
11                1013               0.195341
1292              1000               0.192834
119                977               0.188399
1588               921               0.177600
1420               911               0.175672
126                905               0.174515
1674               897               0.172972
410                879               0.169501

==============================================================================================================
3. BANK ID → BANK NAME STRUCTURE
==============================================================================================================
Bank IDs with exactly one Bank Name: 30,470
Bank IDs with multiple Bank Names: 0

==============================================================================================================
4. ORIGINAL ACCOUNT ID STRUCTURE
==============================================================================================================
Unique account ID values: 518,573

Lengths:
Account Number
9    518581

Digits only: 35,556 (6.8564%)
Uppercase alphanumeric: 518,581 (100.0000%)

Sample real account IDs:
  813643E91
  802E26D10
  80D607B40
  80D9406A0
  80ABCB140
  80C1B6F80
  80AD6D740
  80EF95D30
  811578000
  807441840
  80D8DB790
  80C1625D0
  80413A690
  8019C1840
  8077AE270
  805C58C80
  80B69F980
  80A28EB80
  811725250
  806B9E0A0
  8140B68F1
  803F977F0
  80F67BAC0
  80FDA5E70
  8114D1720
  8024A6F10
  807D08EB0
  80B7A57A0
  8134468A0
  807A2C280

==============================================================================================================
5. ENTITY ID STRUCTURE
==============================================================================================================
Unique Entity IDs: 166,207
Unique Entity Names: 166,207
Entity ID == Entity Name unique-count: True

==============================================================================================================
6. SCANNING ORIGINAL TRANSACTION ACTIVITY
==============================================================================================================
Processed 2,500,000 rows...
Processed 5,000,000 rows...

==============================================================================================================
7. TRANSACTION ACTIVITY RESULTS
==============================================================================================================
Total rows: 5,078,345
Legitimate: 5,073,168
Laundering: 5,177

==============================================================================================================
8. SOURCE ACCOUNT ACTIVITY
==============================================================================================================

ALL SOURCE ACCOUNTS
  count   : 496,995
  min     : 1.000
  p25     : 1.000
  median  : 2.000
  mean    : 10.218
  p75     : 5.000
  p90     : 29.000
  p95     : 46.000
  p99     : 92.000
  max     : 168672.000

LEGITIMATE SOURCE ACCOUNTS
  count   : 496,871
  min     : 1.000
  p25     : 1.000
  median  : 2.000
  mean    : 10.210
  p75     : 5.000
  p90     : 29.000
  p95     : 46.000
  p99     : 92.000
  max     : 168429.000

LAUNDERING SOURCE ACCOUNTS
  count   : 3,376
  min     : 1.000
  p25     : 1.000
  median  : 1.000
  mean    : 1.533
  p75     : 1.000
  p90     : 1.000
  p95     : 2.000
  p99     : 15.000
  max     : 243.000

==============================================================================================================
9. DESTINATION ACCOUNT ACTIVITY
==============================================================================================================

ALL DESTINATION ACCOUNTS
  count   : 420,636
  min     : 1.000
  p25     : 1.000
  median  : 4.000
  mean    : 12.073
  p75     : 22.000
  p90     : 31.000
  p95     : 37.000
  p99     : 51.000
  max     : 1084.000

LEGITIMATE DESTINATION ACCOUNTS
  count   : 420,585
  min     : 1.000
  p25     : 1.000
  median  : 4.000
  mean    : 12.062
  p75     : 22.000
  p90     : 31.000
  p95     : 37.000
  p99     : 51.000
  max     : 1084.000

LAUNDERING DESTINATION ACCOUNTS
  count   : 3,984
  min     : 1.000
  p25     : 1.000
  median  : 1.000
  mean    : 1.299
  p75     : 1.000
  p90     : 1.000
  p95     : 1.850
  p99     : 13.000
  max     : 31.000

==============================================================================================================
10. SOURCE BANK ACTIVITY
==============================================================================================================

ALL SOURCE BANKS
  count   : 30,528
  min     : 1.000
  p25     : 2.000
  median  : 5.000
  mean    : 166.350
  p75     : 12.000
  p90     : 24.000
  p95     : 73.000
  p99     : 3889.140
  max     : 449859.000

LEGITIMATE SOURCE BANKS
  count   : 30,528
  min     : 1.000
  p25     : 2.000
  median  : 5.000
  mean    : 166.181
  p75     : 12.000
  p90     : 24.000
  p95     : 72.000
  p99     : 3886.220
  max     : 449226.000

LAUNDERING SOURCE BANKS
  count   : 1,027
  min     : 1.000
  p25     : 1.000
  median  : 2.000
  mean    : 5.041
  p75     : 5.000
  p90     : 9.000
  p95     : 17.000
  p99     : 34.480
  max     : 633.000

==============================================================================================================
11. DESTINATION BANK ACTIVITY
==============================================================================================================

ALL DESTINATION BANKS
  count   : 15,850
  min     : 1.000
  p25     : 2.000
  median  : 3.000
  mean    : 320.400
  p75     : 6.000
  p90     : 292.400
  p95     : 2280.000
  p99     : 6761.710
  max     : 34732.000

LEGITIMATE DESTINATION BANKS
  count   : 15,850
  min     : 1.000
  p25     : 2.000
  median  : 3.000
  mean    : 320.074
  p75     : 6.000
  p90     : 292.400
  p95     : 2278.550
  p99     : 6752.200
  max     : 34651.000

LAUNDERING DESTINATION BANKS
  count   : 1,111
  min     : 1.000
  p25     : 1.000
  median  : 3.000
  mean    : 4.660
  p75     : 5.000
  p90     : 10.000
  p95     : 16.000
  p99     : 35.600
  max     : 81.000

==============================================================================================================
12. TOP SOURCE ACCOUNTS BY TRANSACTION COUNT
==============================================================================================================
           Transactions  Share_pct
100428660        168672   3.321397
1004286A8        103018   2.028574
100428978         20497   0.403616
1004286F0         18663   0.367502
100428780         17264   0.339953
1004289C0         16794   0.330698
100428810         16426   0.323452
1004287C8         14174   0.279107
100428738         13756   0.270876
100428A51         13073   0.257426
1004288A0         12330   0.242796
100428858         11000   0.216606
1004288E8          9471   0.186498
100428A08          8290   0.163242
100428930          6431   0.126636
800058B80           351   0.006912
80006FCE0           296   0.005829
800058920           279   0.005494
80005ADE0           276   0.005435
800105F00           274   0.005395
8000C5D00           273   0.005376
800167090           271   0.005336
8001B1C30           268   0.005277
80FD2DBC0           265   0.005218
800102DD0           263   0.005179
8000F7C60           263   0.005179
803037BE0           258   0.005080
80018AE80           255   0.005021
800058470           254   0.005002
8000B8AB0           253   0.004982
8007C51F0           253   0.004982
800061BD0           251   0.004943
800055DF0           245   0.004824
800089960           245   0.004824
8000F89F0           245   0.004824
8001C8580           244   0.004805
80010F6E0           241   0.004746
800062960           241   0.004746
8005E5290           239   0.004706
8004203B0           239   0.004706
8000631E0           238   0.004687
8000611E0           238   0.004687
80023D380           237   0.004667
800098200           237   0.004667
807661E30           237   0.004667
800142A60           235   0.004627
80005FB10           234   0.004608
8001B73A0           234   0.004608
800063CE0           232   0.004568
8001580D0           232   0.004568

==============================================================================================================
13. TOP SOURCE ACCOUNTS — LEGITIMATE ONLY
==============================================================================================================
           Transactions  Share_pct
100428660        168429   3.319996
1004286A8        102860   2.027530
100428978         20468   0.403456
1004286F0         18642   0.367463
100428780         17243   0.339886
1004289C0         16781   0.330780
100428810         16400   0.323269
1004287C8         14158   0.279076
100428738         13733   0.270699
100428A51         13055   0.257334
1004288A0         12314   0.242728
100428858         10986   0.216551
1004288E8          9458   0.186432
100428A08          8277   0.163152
100428930          6422   0.126588
800058B80           351   0.006919
80006FCE0           296   0.005835
800058920           279   0.005500
80005ADE0           276   0.005440
800105F00           274   0.005401
8000C5D00           273   0.005381
800167090           271   0.005342
8001B1C30           268   0.005283
80FD2DBC0           265   0.005224
800102DD0           263   0.005184
8000F7C60           263   0.005184
803037BE0           258   0.005086
80018AE80           255   0.005026
800058470           254   0.005007
8007C51F0           253   0.004987
800061BD0           251   0.004948
8000F89F0           245   0.004829
800055DF0           245   0.004829
800089960           245   0.004829
8001C8580           244   0.004810
8000B8AB0           241   0.004750
80010F6E0           241   0.004750
800062960           241   0.004750
8004203B0           239   0.004711
8005E5290           239   0.004711
8000611E0           238   0.004691
8000631E0           237   0.004672
80023D380           237   0.004672
807661E30           237   0.004672
800098200           237   0.004672
800142A60           235   0.004632
8001B73A0           234   0.004613
80005FB10           234   0.004613
8001580D0           232   0.004573
800063CE0           232   0.004573

==============================================================================================================
14. TOP SOURCE ACCOUNTS — LAUNDERING
==============================================================================================================
           Transactions  Share_pct
100428660           243   4.693838
1004286A8           158   3.051961
80266F880            29   0.560170
100428978            29   0.560170
100428810            26   0.502221
812D22980            25   0.482905
100428738            23   0.444273
100428780            21   0.405640
8021353D0            21   0.405640
811C599A0            21   0.405640
811C597B0            21   0.405640
1004286F0            21   0.405640
100428A51            18   0.347692
812A09D40            18   0.347692
811B83280            17   0.328376
811B6E170            17   0.328376
812D0C3C0            17   0.328376
800737690            16   0.309059
1004288A0            16   0.309059
809BFD6B0            16   0.309059
8040AE4F0            16   0.309059
1004287C8            16   0.309059
808338D40            16   0.309059
805DB7F20            16   0.309059
812A09CF0            16   0.309059
80452D470            16   0.309059
8051B3BF0            15   0.289743
80ED002D0            15   0.289743
8051E3B20            15   0.289743
8000E1590            15   0.289743
802E2AD70            15   0.289743
80154AAF0            15   0.289743
8075AC7C0            15   0.289743
803366440            15   0.289743
808839F70            15   0.289743
808D6F2D0            14   0.270427
8043A0FB0            14   0.270427
80F984C70            14   0.270427
80794B6F0            14   0.270427
100428858            14   0.270427
811A4DBD0            14   0.270427
8007C7660            14   0.270427
8095AF170            13   0.251111
80DEE3B40            13   0.251111
8030004E0            13   0.251111
8041A3440            13   0.251111
80CB65920            13   0.251111
1004289C0            13   0.251111
8078765D0            13   0.251111
80C93DF00            13   0.251111

==============================================================================================================
15. ACCOUNT INTER-ARRIVAL TIME
==============================================================================================================
Sampled inter-arrivals: 19,695
  p1   : 0.0000 minutes
  p5   : 0.0000 minutes
  p10  : 1.0000 minutes
  p25  : 2.0000 minutes
  p50  : 5.0000 minutes
  p75  : 11.0000 minutes
  p90  : 17.0000 minutes
  p95  : 20.0000 minutes
  p99  : 25.0000 minutes
  p99.9: 29.0000 minutes
  max  : 29.0000 minutes

==============================================================================================================
16. ACCOUNT ACTIVITY BUCKETS
==============================================================================================================
                 Accounts  Share_pct
(0.0, 1.0]         152750  30.734716
(1.0, 2.0]         158252  31.841769
(2.0, 5.0]          63830  12.843188
(5.0, 10.0]         19044   3.831829
(10.0, 25.0]        48153   9.688830
(25.0, 50.0]        33417   6.723810
(50.0, 100.0]       17805   3.582531
(100.0, 250.0]       3712   0.746889
(250.0, 500.0]         17   0.003421
(500.0, 1000.0]         0   0.000000
(1000.0, inf]          15   0.003018

==============================================================================================================
17. BANK ACTIVITY BUCKETS
==============================================================================================================
                      Banks  Share_pct
(0.0, 100.0]          29059  95.188024
(100.0, 500.0]          417   1.365959
(500.0, 1000.0]         246   0.805818
(1000.0, 5000.0]        560   1.834382
(5000.0, 10000.0]       151   0.494628
(10000.0, 25000.0]       79   0.258779
(25000.0, 50000.0]       12   0.039308
(50000.0, 100000.0]       3   0.009827
(100000.0, 250000.0]      0   0.000000
(250000.0, inf]           1   0.003276

==============================================================================================================
✅ CONDITIONAL / BEHAVIORAL DNA AUDIT COMPLETE
==============================================================================================================
Master behavioral DNA: /kaggle/working/AML_GNN_ONLY/data/HI-Small_original_behavioral_dna.json

This is now the empirical reference for the NEW generator.
No synthetic transactions were generated.
No original source files were modified.
==============================================================================================================

In [6]:
# ============================================================
# CELL 3 — ORIGINAL HI-SMALL PATTERN-WISE DNA AUDIT
# CORRECTED VERSION
#
# Source:
#   HI-Small_Patterns.txt
#
# Purpose:
#   Extract the exact structural + behavioral characteristics
#   of every original IBM laundering typology.
#
# NO files are modified.
# NO synthetic transactions are generated.
# ============================================================

from pathlib import Path
from collections import Counter
import pandas as pd
import numpy as np
import json
import re

# ============================================================
# 1. PATH
# ============================================================

PATTERNS_PATH = Path(
    "/kaggle/input/datasets/ealtman2019/"
    "ibm-transactions-for-anti-money-laundering-aml/"
    "HI-Small_Patterns.txt"
)

if not PATTERNS_PATH.exists():
    raise FileNotFoundError(PATTERNS_PATH)

print("=" * 110)
print("ORIGINAL HI-SMALL PATTERN-WISE DNA AUDIT")
print("=" * 110)
print("Patterns file:")
print(PATTERNS_PATH)

# ============================================================
# 2. EXACT PATTERN PARSER
# ============================================================

BEGIN_RE = re.compile(
    r"^BEGIN LAUNDERING ATTEMPT - (.+?)\s*$",
    re.IGNORECASE
)

END_RE = re.compile(
    r"^END LAUNDERING ATTEMPT - (.+?)\s*$",
    re.IGNORECASE
)

KNOWN_TYPOLOGIES = {
    "FAN-OUT",
    "FAN-IN",
    "CYCLE",
    "BIPARTITE",
    "STACK",
    "RANDOM",
    "SCATTER-GATHER",
    "GATHER-SCATTER",
}

with open(
    PATTERNS_PATH,
    "r",
    encoding="utf-8"
) as f:
    raw_lines = [
        line.rstrip("\r\n")
        for line in f
    ]

episodes = []
current = None

for line_number, raw_line in enumerate(
    raw_lines,
    start=1
):

    line = raw_line.strip()

    if not line:
        continue

    # --------------------------------------------------------
    # BEGIN
    # --------------------------------------------------------

    begin_match = BEGIN_RE.match(line)

    if begin_match:

        if current is not None:
            raise ValueError(
                f"Nested BEGIN at line {line_number}"
            )

        header = begin_match.group(1).strip()

        # Example:
        # FAN-OUT: Max 16-degree Fan-Out
        #
        # We only keep FAN-OUT.
        typology = (
            header
            .split(":", 1)[0]
            .strip()
            .upper()
        )

        if typology not in KNOWN_TYPOLOGIES:
            raise ValueError(
                f"Unknown typology {typology!r} "
                f"at line {line_number}"
            )

        current = {
            "episode_id": len(episodes) + 1,
            "typology": typology,
            "header": line,
            "begin_line": line_number,
            "transaction_lines": [],
        }

        continue

    # --------------------------------------------------------
    # END
    # --------------------------------------------------------

    end_match = END_RE.match(line)

    if end_match:

        if current is None:
            raise ValueError(
                f"END without BEGIN at line {line_number}"
            )

        end_typology = (
            end_match.group(1)
            .strip()
            .upper()
        )

        if end_typology != current["typology"]:
            raise ValueError(
                f"BEGIN/END mismatch at line {line_number}: "
                f"{current['typology']} vs {end_typology}"
            )

        current["end_line"] = line_number

        episodes.append(current)

        current = None

        continue

    # --------------------------------------------------------
    # TRANSACTION LINE
    # --------------------------------------------------------

    if current is None:
        raise ValueError(
            f"Unexpected line outside episode "
            f"at line {line_number}: {line}"
        )

    current["transaction_lines"].append(line)

# ------------------------------------------------------------
# FINAL PARSER CHECK
# ------------------------------------------------------------

if current is not None:
    raise ValueError(
        "Patterns file ended before final END."
    )

print()
print(
    "Parsed episodes:",
    f"{len(episodes):,}"
)

if len(episodes) != 370:
    raise ValueError(
        f"Expected 370 episodes, got {len(episodes)}"
    )

# ============================================================
# 3. PARSE TRANSACTION ROWS
# ============================================================

COLUMNS = [
    "Timestamp",
    "From Bank",
    "Account",
    "To Bank",
    "Account.1",
    "Amount Received",
    "Receiving Currency",
    "Amount Paid",
    "Payment Currency",
    "Payment Format",
    "Is Laundering",
]

transaction_rows = []

for episode in episodes:

    for order, line in enumerate(
        episode["transaction_lines"],
        start=1
    ):

        parts = line.split(",")

        if len(parts) != 11:
            raise ValueError(
                f"Episode {episode['episode_id']} "
                f"contains a row with {len(parts)} fields:\n"
                f"{line}"
            )

        row = {}

        for column, value in zip(
            COLUMNS,
            parts
        ):
            row[column] = value

        row["episode_id"] = (
            episode["episode_id"]
        )

        row["typology"] = (
            episode["typology"]
        )

        row["episode_order"] = order

        transaction_rows.append(row)

patterns_df = pd.DataFrame(
    transaction_rows
)

# ============================================================
# 4. TYPE CONVERSION
# ============================================================

patterns_df["Timestamp"] = pd.to_datetime(
    patterns_df["Timestamp"],
    format="%Y/%m/%d %H:%M",
    errors="raise"
)

patterns_df["Amount Received"] = pd.to_numeric(
    patterns_df["Amount Received"],
    errors="raise"
)

patterns_df["Amount Paid"] = pd.to_numeric(
    patterns_df["Amount Paid"],
    errors="raise"
)

patterns_df["Is Laundering"] = pd.to_numeric(
    patterns_df["Is Laundering"],
    errors="raise"
).astype(int)

# Canonical graph nodes
patterns_df["src_node"] = (
    patterns_df["From Bank"].astype(str)
    + "\x1f"
    + patterns_df["Account"].astype(str)
)

patterns_df["dst_node"] = (
    patterns_df["To Bank"].astype(str)
    + "\x1f"
    + patterns_df["Account.1"].astype(str)
)

print(
    "Pattern transactions:",
    f"{len(patterns_df):,}"
)

if len(patterns_df) != 3209:
    raise ValueError(
        f"Expected 3209 pattern transactions, "
        f"got {len(patterns_df)}"
    )

if not patterns_df["Is Laundering"].eq(1).all():
    raise ValueError(
        "Patterns file contains non-laundering transaction rows."
    )

# ============================================================
# 5. GRAPH METRICS FUNCTION
# ============================================================

def calculate_graph_metrics(group):

    edges = set(
        zip(
            group["src_node"].tolist(),
            group["dst_node"].tolist()
        )
    )

    nodes = set(
        group["src_node"].tolist()
    )

    nodes.update(
        group["dst_node"].tolist()
    )

    indegree = Counter()
    outdegree = Counter()

    for src, dst in edges:

        outdegree[src] += 1
        indegree[dst] += 1

    degree_pairs = []

    for node in nodes:

        incoming = indegree.get(
            node,
            0
        )

        outgoing = outdegree.get(
            node,
            0
        )

        degree_pairs.append(
            (
                int(incoming),
                int(outgoing)
            )
        )

    degree_pairs.sort()

    intermediate_nodes = 0
    source_only_nodes = 0
    destination_only_nodes = 0
    self_loops = 0

    for node in nodes:

        incoming = indegree.get(
            node,
            0
        )

        outgoing = outdegree.get(
            node,
            0
        )

        if incoming > 0 and outgoing > 0:
            intermediate_nodes += 1

        elif incoming == 0 and outgoing > 0:
            source_only_nodes += 1

        elif incoming > 0 and outgoing == 0:
            destination_only_nodes += 1

    for src, dst in edges:

        if src == dst:
            self_loops += 1

    result = {
        "transaction_count": int(
            len(group)
        ),
        "unique_edge_count": int(
            len(edges)
        ),
        "unique_node_count": int(
            len(nodes)
        ),
        "unique_source_accounts": int(
            group["Account"].nunique()
        ),
        "unique_destination_accounts": int(
            group["Account.1"].nunique()
        ),
        "unique_source_banks": int(
            group["From Bank"].nunique()
        ),
        "unique_destination_banks": int(
            group["To Bank"].nunique()
        ),
        "unique_bank_pairs": int(
            group[
                ["From Bank", "To Bank"]
            ]
            .drop_duplicates()
            .shape[0]
        ),
        "max_in_degree": int(
            max(indegree.values())
            if indegree
            else 0
        ),
        "max_out_degree": int(
            max(outdegree.values())
            if outdegree
            else 0
        ),
        "intermediate_nodes": int(
            intermediate_nodes
        ),
        "source_only_nodes": int(
            source_only_nodes
        ),
        "destination_only_nodes": int(
            destination_only_nodes
        ),
        "self_loops": int(
            self_loops
        ),
        "degree_signature": str(
            degree_pairs
        ),
    }

    return result


# ============================================================
# 6. EPISODE-LEVEL DNA
# ============================================================

episode_records = []

for episode_id, group in patterns_df.groupby(
    "episode_id",
    sort=True
):

    group = group.sort_values(
        "episode_order"
    )

    typology = (
        group["typology"]
        .iloc[0]
    )

    graph = calculate_graph_metrics(
        group
    )

    # --------------------------------------------------------
    # Chronological timing
    # --------------------------------------------------------

    chronological = (
        group["Timestamp"]
        .sort_values()
        .reset_index(drop=True)
    )

    total_span = (
        chronological.iloc[-1]
        - chronological.iloc[0]
    )

    total_span_minutes = (
        total_span.total_seconds()
        / 60.0
    )

    if len(chronological) > 1:

        gaps = (
            chronological
            .diff()
            .dropna()
            .dt.total_seconds()
            / 60.0
        )

        gap_min = float(
            gaps.min()
        )

        gap_median = float(
            gaps.median()
        )

        gap_max = float(
            gaps.max()
        )

    else:

        gap_min = 0.0
        gap_median = 0.0
        gap_max = 0.0

    # --------------------------------------------------------
    # Amounts
    # --------------------------------------------------------

    amounts = (
        group["Amount Received"]
        .to_numpy(
            dtype=float
        )
    )

    # --------------------------------------------------------
    # Categorical distributions
    # --------------------------------------------------------

    payment_formats = (
        group["Payment Format"]
        .value_counts()
        .to_dict()
    )

    receiving_currencies = (
        group["Receiving Currency"]
        .value_counts()
        .to_dict()
    )

    payment_currencies = (
        group["Payment Currency"]
        .value_counts()
        .to_dict()
    )

    # --------------------------------------------------------
    # Final record
    # --------------------------------------------------------

    record = {
        "episode_id": int(
            episode_id
        ),
        "typology": typology,

        "transaction_count": graph[
            "transaction_count"
        ],

        "unique_edge_count": graph[
            "unique_edge_count"
        ],

        "unique_node_count": graph[
            "unique_node_count"
        ],

        "unique_source_accounts": graph[
            "unique_source_accounts"
        ],

        "unique_destination_accounts": graph[
            "unique_destination_accounts"
        ],

        "unique_source_banks": graph[
            "unique_source_banks"
        ],

        "unique_destination_banks": graph[
            "unique_destination_banks"
        ],

        "unique_bank_pairs": graph[
            "unique_bank_pairs"
        ],

        "max_in_degree": graph[
            "max_in_degree"
        ],

        "max_out_degree": graph[
            "max_out_degree"
        ],

        "intermediate_nodes": graph[
            "intermediate_nodes"
        ],

        "source_only_nodes": graph[
            "source_only_nodes"
        ],

        "destination_only_nodes": graph[
            "destination_only_nodes"
        ],

        "self_loops": graph[
            "self_loops"
        ],

        "degree_signature": graph[
            "degree_signature"
        ],

        "time_span_minutes": float(
            total_span_minutes
        ),

        "chronological_gap_min": float(
            gap_min
        ),

        "chronological_gap_median": float(
            gap_median
        ),

        "chronological_gap_max": float(
            gap_max
        ),

        "amount_min": float(
            amounts.min()
        ),

        "amount_p25": float(
            np.percentile(
                amounts,
                25
            )
        ),

        "amount_median": float(
            np.median(amounts)
        ),

        "amount_p75": float(
            np.percentile(
                amounts,
                75
            )
        ),

        "amount_max": float(
            amounts.max()
        ),

        "payment_formats": json.dumps(
            payment_formats
        ),

        "receiving_currencies": json.dumps(
            receiving_currencies
        ),

        "payment_currencies": json.dumps(
            payment_currencies
        ),
    }

    episode_records.append(
        record
    )

episode_df = pd.DataFrame(
    episode_records
)

# ============================================================
# 7. VALIDATION
# ============================================================

print()
print("=" * 110)
print("1. PATTERN VALIDATION")
print("=" * 110)

print(
    "Episodes:",
    f"{len(episode_df):,}"
)

print(
    "Transactions:",
    f"{len(patterns_df):,}"
)

print(
    "Typologies:",
    episode_df["typology"].nunique()
)

print(
    "All labels = 1:",
    patterns_df["Is Laundering"].eq(1).all()
)

print()
print("Episode count by typology:")

print(
    episode_df[
        "typology"
    ]
    .value_counts()
    .sort_index()
    .to_string()
)

print()
print("Transaction count by typology:")

print(
    patterns_df[
        "typology"
    ]
    .value_counts()
    .sort_index()
    .to_string()
)

# ============================================================
# 8. TYPOLOGY-WISE DNA
# ============================================================

METRICS = [
    "transaction_count",
    "unique_node_count",
    "unique_source_banks",
    "unique_destination_banks",
    "unique_bank_pairs",
    "max_in_degree",
    "max_out_degree",
    "intermediate_nodes",
    "source_only_nodes",
    "destination_only_nodes",
    "self_loops",
    "time_span_minutes",
    "chronological_gap_median",
    "amount_median",
]

typology_records = []

print()
print("=" * 110)
print("2. TYPOLOGY-WISE DNA")
print("=" * 110)

for typology in sorted(
    episode_df["typology"].unique()
):

    group = episode_df[
        episode_df["typology"] == typology
    ]

    print()
    print("-" * 110)
    print(
        f"{typology} "
        f"({len(group)} episodes)"
    )

    record = {
        "typology": typology,
        "episodes": int(
            len(group)
        ),
    }

    for metric in METRICS:

        values = group[
            metric
        ]

        median = float(
            values.median()
        )

        mean = float(
            values.mean()
        )

        p10 = float(
            values.quantile(
                0.10
            )
        )

        p90 = float(
            values.quantile(
                0.90
            )
        )

        print(
            f"  {metric:<30} "
            f"median={median:>10.3f} "
            f"mean={mean:>10.3f} "
            f"p10={p10:>10.3f} "
            f"p90={p90:>10.3f}"
        )

        record[
            metric + "_median"
        ] = median

        record[
            metric + "_mean"
        ] = mean

        record[
            metric + "_p10"
        ] = p10

        record[
            metric + "_p90"
        ] = p90

    typology_records.append(
        record
    )

typology_summary_df = pd.DataFrame(
    typology_records
)

# ============================================================
# 9. AMOUNT DNA BY TYPOLOGY
# ============================================================

print()
print("=" * 110)
print("3. AMOUNT DNA BY TYPOLOGY")
print("=" * 110)

for typology in sorted(
    patterns_df["typology"].unique()
):

    values = patterns_df.loc[
        patterns_df["typology"] == typology,
        "Amount Received"
    ].to_numpy(
        dtype=float
    )

    print()
    print(typology)

    for percentile in [
        1, 5, 10, 25, 50,
        75, 90, 95, 99
    ]:

        value = np.percentile(
            values,
            percentile
        )

        print(
            f"  p{percentile:<2}: "
            f"{value:,.6f}"
        )

# ============================================================
# 10. PAYMENT FORMAT BY TYPOLOGY
# ============================================================

print()
print("=" * 110)
print("4. PAYMENT FORMAT BY TYPOLOGY")
print("=" * 110)

for typology in sorted(
    patterns_df["typology"].unique()
):

    group = patterns_df[
        patterns_df["typology"] == typology
    ]

    counts = (
        group[
            "Payment Format"
        ]
        .value_counts()
    )

    total = counts.sum()

    output = pd.DataFrame({
        "Count": counts,
        "Share_pct": (
            counts / total * 100.0
        )
    })

    print()
    print(typology)
    print(
        output.to_string()
    )

# ============================================================
# 11. RECEIVING CURRENCY BY TYPOLOGY
# ============================================================

print()
print("=" * 110)
print("5. RECEIVING CURRENCY BY TYPOLOGY")
print("=" * 110)

for typology in sorted(
    patterns_df["typology"].unique()
):

    group = patterns_df[
        patterns_df["typology"] == typology
    ]

    counts = (
        group[
            "Receiving Currency"
        ]
        .value_counts()
    )

    total = counts.sum()

    output = pd.DataFrame({
        "Count": counts,
        "Share_pct": (
            counts / total * 100.0
        )
    })

    print()
    print(typology)
    print(
        output.to_string()
    )

# ============================================================
# 12. TIME DNA
# ============================================================

print()
print("=" * 110)
print("6. TIMING DNA BY TYPOLOGY")
print("=" * 110)

for typology in sorted(
    episode_df["typology"].unique()
):

    group = episode_df[
        episode_df["typology"] == typology
    ]

    print()
    print(typology)

    print(
        "  Episode span median:",
        f"{group['time_span_minutes'].median():.3f} min"
    )

    print(
        "  Gap median:",
        f"{group['chronological_gap_median'].median():.3f} min"
    )

    print(
        "  Gap p90:",
        f"{group['chronological_gap_median'].quantile(.90):.3f} min"
    )

    print(
        "  Maximum episode span:",
        f"{group['time_span_minutes'].max():.3f} min"
    )

# ============================================================
# 13. NODE ROLE DNA
# ============================================================

print()
print("=" * 110)
print("7. NODE ROLE DNA")
print("=" * 110)

role_output = []

for typology in sorted(
    episode_df["typology"].unique()
):

    group = episode_df[
        episode_df["typology"] == typology
    ]

    record = {
        "typology": typology,
        "episodes": int(
            len(group)
        ),
        "median_max_in_degree": float(
            group["max_in_degree"].median()
        ),
        "median_max_out_degree": float(
            group["max_out_degree"].median()
        ),
        "median_intermediate_nodes": float(
            group["intermediate_nodes"].median()
        ),
        "median_source_only_nodes": float(
            group["source_only_nodes"].median()
        ),
        "median_destination_only_nodes": float(
            group["destination_only_nodes"].median()
        ),
        "median_self_loops": float(
            group["self_loops"].median()
        ),
    }

    role_output.append(
        record
    )

role_df = pd.DataFrame(
    role_output
)

print(
    role_df.round(3).to_string(
        index=False
    )
)

# ============================================================
# 14. EPISODE SIZE MATRIX
# ============================================================

print()
print("=" * 110)
print("8. EPISODE SIZE DISTRIBUTION")
print("=" * 110)

size_matrix = (
    episode_df
    .groupby(
        [
            "typology",
            "transaction_count"
        ]
    )
    .size()
    .unstack(
        fill_value=0
    )
)

print(
    size_matrix.to_string()
)

# ============================================================
# 15. GRAPH SIGNATURE FREQUENCY
# ============================================================

print()
print("=" * 110)
print("9. GRAPH SIGNATURE FREQUENCY")
print("=" * 110)

signature_counts = (
    episode_df
    .groupby(
        [
            "typology",
            "degree_signature"
        ]
    )
    .size()
    .reset_index(
        name="episodes"
    )
    .sort_values(
        "episodes",
        ascending=False
    )
)

print(
    signature_counts
    .head(100)
    .to_string(
        index=False
    )
)

# ============================================================
# 16. SAVE OUTPUTS
# ============================================================

OUTPUT_DIR = Path(
    "/kaggle/working/AML_GNN_ONLY/data"
)

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

episode_csv = (
    OUTPUT_DIR /
    "HI-Small_original_pattern_dna_episodes.csv"
)

typology_csv = (
    OUTPUT_DIR /
    "HI-Small_original_pattern_dna_typologies.csv"
)

roles_csv = (
    OUTPUT_DIR /
    "HI-Small_original_pattern_dna_node_roles.csv"
)

sizes_csv = (
    OUTPUT_DIR /
    "HI-Small_original_pattern_dna_episode_sizes.csv"
)

signatures_csv = (
    OUTPUT_DIR /
    "HI-Small_original_pattern_dna_signatures.csv"
)

episode_df.to_csv(
    episode_csv,
    index=False
)

typology_summary_df.to_csv(
    typology_csv,
    index=False
)

role_df.to_csv(
    roles_csv,
    index=False
)

size_matrix.to_csv(
    sizes_csv
)

signature_counts.to_csv(
    signatures_csv,
    index=False
)

# ============================================================
# 17. MASTER JSON
# ============================================================

master = {}

master["source_patterns"] = str(
    PATTERNS_PATH
)

master["episode_count"] = int(
    len(episode_df)
)

master["transaction_count"] = int(
    len(patterns_df)
)

master["typologies"] = {}

for typology in sorted(
    episode_df["typology"].unique()
):

    episode_count = int(
        (
            episode_df["typology"]
            == typology
        ).sum()
    )

    transaction_count = int(
        (
            patterns_df["typology"]
            == typology
        ).sum()
    )

    master["typologies"][typology] = {
        "episodes": episode_count,
        "transactions": transaction_count,
    }

master["episode_size"] = {
    "min": int(
        episode_df[
            "transaction_count"
        ].min()
    ),
    "median": float(
        episode_df[
            "transaction_count"
        ].median()
    ),
    "mean": float(
        episode_df[
            "transaction_count"
        ].mean()
    ),
    "p90": float(
        episode_df[
            "transaction_count"
        ].quantile(.90)
    ),
    "p99": float(
        episode_df[
            "transaction_count"
        ].quantile(.99)
    ),
    "max": int(
        episode_df[
            "transaction_count"
        ].max()
    ),
}

# Store role information
master["node_role_metrics"] = []

for row in role_df.to_dict(
    orient="records"
):

    cleaned = {}

    for key, value in row.items():

        if isinstance(
            value,
            (np.integer, int)
        ):
            cleaned[key] = int(value)

        elif isinstance(
            value,
            (np.floating, float)
        ):
            cleaned[key] = float(value)

        else:
            cleaned[key] = value

    master[
        "node_role_metrics"
    ].append(
        cleaned
    )

master_path = (
    OUTPUT_DIR /
    "HI-Small_original_pattern_dna.json"
)

with open(
    master_path,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        master,
        f,
        indent=2
    )

# ============================================================
# 18. FINAL
# ============================================================

print()
print("=" * 110)
print("✅ PATTERN-WISE DNA AUDIT COMPLETE")
print("=" * 110)

print(
    "Episode DNA CSV:",
    episode_csv
)

print(
    "Typology DNA CSV:",
    typology_csv
)

print(
    "Node-role CSV:",
    roles_csv
)

print(
    "Episode-size CSV:",
    sizes_csv
)

print(
    "Signature CSV:",
    signatures_csv
)

print(
    "Master JSON:",
    master_path
)

print()
print("No transactions generated.")
print("No source files modified.")
print("=" * 110)

==============================================================================================================
ORIGINAL HI-SMALL PATTERN-WISE DNA AUDIT
==============================================================================================================
Patterns file:
/kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml/HI-Small_Patterns.txt

Parsed episodes: 370
Pattern transactions: 3,209

==============================================================================================================
1. PATTERN VALIDATION
==============================================================================================================
Episodes: 370
Transactions: 3,209
Typologies: 8
All labels = 1: True

Episode count by typology:
typology
BIPARTITE         49
CYCLE             54
FAN-IN            40
FAN-OUT           48
GATHER-SCATTER    51
RANDOM            41
SCATTER-GATHER    44
STACK             43

Transaction count by typology:
typology
BIPARTITE         263
CYCLE             287
FAN-IN            318
FAN-OUT           342
GATHER-SCATTER    716
RANDOM            191
SCATTER-GATHER    626
STACK             466

==============================================================================================================
2. TYPOLOGY-WISE DNA
==============================================================================================================

--------------------------------------------------------------------------------------------------------------
BIPARTITE (49 episodes)
  transaction_count              median=     4.000 mean=     5.367 p10=     1.000 p90=    12.200
  unique_node_count              median=     8.000 mean=    10.735 p10=     2.000 p90=    24.400
  unique_source_banks            median=     4.000 mean=     5.143 p10=     1.000 p90=    12.000
  unique_destination_banks       median=     4.000 mean=     5.102 p10=     1.000 p90=    12.200
  unique_bank_pairs              median=     4.000 mean=     5.306 p10=     1.000 p90=    12.200
  max_in_degree                  median=     1.000 mean=     1.000 p10=     1.000 p90=     1.000
  max_out_degree                 median=     1.000 mean=     1.000 p10=     1.000 p90=     1.000
  intermediate_nodes             median=     0.000 mean=     0.000 p10=     0.000 p90=     0.000
  source_only_nodes              median=     4.000 mean=     5.367 p10=     1.000 p90=    12.200
  destination_only_nodes         median=     4.000 mean=     5.367 p10=     1.000 p90=    12.200
  self_loops                     median=     0.000 mean=     0.000 p10=     0.000 p90=     0.000
  time_span_minutes              median=  1460.000 mean=  1286.531 p10=     0.000 p90=  2587.400
  chronological_gap_median       median=   134.000 mean=   206.704 p10=     0.000 p90=   407.200
  amount_median                  median= 14262.230 mean=322050.925 p10=  5200.066 p90= 42561.948

--------------------------------------------------------------------------------------------------------------
CYCLE (54 episodes)
  transaction_count              median=     4.000 mean=     5.315 p10=     2.000 p90=    10.000
  unique_node_count              median=     4.000 mean=     5.315 p10=     2.000 p90=    10.000
  unique_source_banks            median=     4.000 mean=     5.056 p10=     2.000 p90=    10.000
  unique_destination_banks       median=     4.000 mean=     5.056 p10=     2.000 p90=    10.000
  unique_bank_pairs              median=     4.000 mean=     5.259 p10=     2.000 p90=    10.000
  max_in_degree                  median=     1.000 mean=     1.000 p10=     1.000 p90=     1.000
  max_out_degree                 median=     1.000 mean=     1.000 p10=     1.000 p90=     1.000
  intermediate_nodes             median=     4.000 mean=     5.315 p10=     2.000 p90=    10.000
  source_only_nodes              median=     0.000 mean=     0.000 p10=     0.000 p90=     0.000
  destination_only_nodes         median=     0.000 mean=     0.000 p10=     0.000 p90=     0.000
  self_loops                     median=     0.000 mean=     0.000 p10=     0.000 p90=     0.000
  time_span_minutes              median=  4313.000 mean=  3954.185 p10=  1669.400 p90=  5421.000
  chronological_gap_median       median=   849.500 mean=  1346.139 p10=   269.250 p90=  3846.800
  amount_median                  median= 12089.825 mean=241099.478 p10=  1491.880 p90= 42365.718

--------------------------------------------------------------------------------------------------------------
FAN-IN (40 episodes)
  transaction_count              median=     8.000 mean=     7.950 p10=     1.900 p90=    15.100
  unique_node_count              median=     9.000 mean=     8.950 p10=     2.900 p90=    16.100
  unique_source_banks            median=     6.000 mean=     7.375 p10=     1.900 p90=    13.000
  unique_destination_banks       median=     1.000 mean=     1.000 p10=     1.000 p90=     1.000
  unique_bank_pairs              median=     6.000 mean=     7.375 p10=     1.900 p90=    13.000
  max_in_degree                  median=     8.000 mean=     7.950 p10=     1.900 p90=    15.100
  max_out_degree                 median=     1.000 mean=     1.000 p10=     1.000 p90=     1.000
  intermediate_nodes             median=     0.000 mean=     0.000 p10=     0.000 p90=     0.000
  source_only_nodes              median=     8.000 mean=     7.950 p10=     1.900 p90=    15.100
  destination_only_nodes         median=     1.000 mean=     1.000 p10=     1.000 p90=     1.000
  self_loops                     median=     0.000 mean=     0.000 p10=     0.000 p90=     0.000
  time_span_minutes              median=  5096.000 mean=  4189.725 p10=   655.200 p90=  5681.800
  chronological_gap_median       median=   311.750 mean=   842.800 p10=   140.400 p90=  2372.300
  amount_median                  median= 11970.382 mean= 19714.103 p10=  3361.687 p90= 45296.768

--------------------------------------------------------------------------------------------------------------
FAN-OUT (48 episodes)
  transaction_count              median=     7.000 mean=     7.125 p10=     1.000 p90=    14.300
  unique_node_count              median=     8.000 mean=     8.125 p10=     2.000 p90=    15.300
  unique_source_banks            median=     1.000 mean=     1.000 p10=     1.000 p90=     1.000
  unique_destination_banks       median=     6.000 mean=     6.542 p10=     1.000 p90=    13.300
  unique_bank_pairs              median=     6.000 mean=     6.542 p10=     1.000 p90=    13.300
  max_in_degree                  median=     1.000 mean=     1.000 p10=     1.000 p90=     1.000
  max_out_degree                 median=     7.000 mean=     7.125 p10=     1.000 p90=    14.300
  intermediate_nodes             median=     0.000 mean=     0.000 p10=     0.000 p90=     0.000
  source_only_nodes              median=     1.000 mean=     1.000 p10=     1.000 p90=     1.000
  destination_only_nodes         median=     7.000 mean=     7.125 p10=     1.000 p90=    14.300
  self_loops                     median=     0.000 mean=     0.000 p10=     0.000 p90=     0.000
  time_span_minutes              median=  4599.500 mean=  3814.562 p10=     0.000 p90=  5682.500
  chronological_gap_median       median=   387.250 mean=   899.323 p10=     0.000 p90=  2398.900
  amount_median                  median= 13960.323 mean= 42127.909 p10=  8653.413 p90= 47502.466

--------------------------------------------------------------------------------------------------------------
GATHER-SCATTER (51 episodes)
  transaction_count              median=    14.000 mean=    14.039 p10=     2.000 p90=    26.000
  unique_node_count              median=    15.000 mean=    14.333 p10=     2.000 p90=    27.000
  unique_source_banks            median=     7.000 mean=     7.784 p10=     2.000 p90=    14.000
  unique_destination_banks       median=     6.000 mean=     7.392 p10=     2.000 p90=    15.000
  unique_bank_pairs              median=    12.000 mean=    13.471 p10=     2.000 p90=    26.000
  max_in_degree                  median=     7.000 mean=     7.333 p10=     2.000 p90=    14.000
  max_out_degree                 median=     6.000 mean=     6.922 p10=     1.000 p90=    15.000
  intermediate_nodes             median=     1.000 mean=     1.490 p10=     1.000 p90=     3.000
  source_only_nodes              median=     7.000 mean=     6.627 p10=     0.000 p90=    14.000
  destination_only_nodes         median=     5.000 mean=     6.216 p10=     0.000 p90=    15.000
  self_loops                     median=     0.000 mean=     0.216 p10=     0.000 p90=     1.000
  time_span_minutes              median=  9049.000 mean=  7744.863 p10=   394.000 p90= 11030.000
  chronological_gap_median       median=   321.000 mean=   511.422 p10=   201.000 p90=  1121.000
  amount_median                  median= 12576.930 mean= 27202.051 p10=  7787.865 p90= 48649.420

--------------------------------------------------------------------------------------------------------------
RANDOM (41 episodes)
  transaction_count              median=     3.000 mean=     4.659 p10=     1.000 p90=    10.000
  unique_node_count              median=     4.000 mean=     5.659 p10=     2.000 p90=    11.000
  unique_source_banks            median=     3.000 mean=     4.512 p10=     1.000 p90=     9.000
  unique_destination_banks       median=     3.000 mean=     4.463 p10=     1.000 p90=     9.000
  unique_bank_pairs              median=     3.000 mean=     4.659 p10=     1.000 p90=    10.000
  max_in_degree                  median=     1.000 mean=     1.000 p10=     1.000 p90=     1.000
  max_out_degree                 median=     1.000 mean=     1.000 p10=     1.000 p90=     1.000
  intermediate_nodes             median=     2.000 mean=     3.659 p10=     0.000 p90=     9.000
  source_only_nodes              median=     1.000 mean=     1.000 p10=     1.000 p90=     1.000
  destination_only_nodes         median=     1.000 mean=     1.000 p10=     1.000 p90=     1.000
  self_loops                     median=     0.000 mean=     0.000 p10=     0.000 p90=     0.000
  time_span_minutes              median=  2760.000 mean=  2562.829 p10=     0.000 p90=  5198.000
  chronological_gap_median       median=   391.500 mean=   454.476 p10=     0.000 p90=  1257.000
  amount_median                  median= 14252.760 mean=702171.675 p10=  2423.590 p90= 57774.345

--------------------------------------------------------------------------------------------------------------
SCATTER-GATHER (44 episodes)
  transaction_count              median=    14.000 mean=    14.227 p10=     2.000 p90=    26.000
  unique_node_count              median=     9.000 mean=     8.818 p10=     2.000 p90=    15.000
  unique_source_banks            median=     7.500 mean=     7.932 p10=     2.000 p90=    14.000
  unique_destination_banks       median=     8.000 mean=     8.023 p10=     2.000 p90=    14.000
  unique_bank_pairs              median=    14.000 mean=    14.068 p10=     2.000 p90=    26.000
  max_in_degree                  median=     7.000 mean=     7.114 p10=     1.000 p90=    13.000
  max_out_degree                 median=     7.000 mean=     7.114 p10=     1.000 p90=    13.000
  intermediate_nodes             median=     7.000 mean=     7.409 p10=     2.000 p90=    13.000
  source_only_nodes              median=     1.000 mean=     0.705 p10=     0.000 p90=     1.000
  destination_only_nodes         median=     1.000 mean=     0.705 p10=     0.000 p90=     1.000
  self_loops                     median=     0.000 mean=     0.000 p10=     0.000 p90=     0.000
  time_span_minutes              median=  5326.000 mean=  4701.159 p10=  2674.500 p90=  5729.700
  chronological_gap_median       median=   242.500 mean=  1018.386 p10=   109.800 p90=  3631.800
  amount_median                  median= 14131.222 mean=301707.826 p10=  7428.268 p90=218604.898

--------------------------------------------------------------------------------------------------------------
STACK (43 episodes)
  transaction_count              median=    10.000 mean=    10.837 p10=     2.000 p90=    23.600
  unique_node_count              median=    15.000 mean=    15.907 p10=     2.000 p90=    35.400
  unique_source_banks            median=     8.000 mean=     9.953 p10=     2.000 p90=    22.000
  unique_destination_banks       median=     8.000 mean=     9.884 p10=     2.000 p90=    22.000
  unique_bank_pairs              median=    10.000 mean=    10.721 p10=     2.000 p90=    22.000
  max_in_degree                  median=     1.000 mean=     1.000 p10=     1.000 p90=     1.000
  max_out_degree                 median=     1.000 mean=     1.000 p10=     1.000 p90=     1.000
  intermediate_nodes             median=     5.000 mean=     5.767 p10=     2.000 p90=    11.800
  source_only_nodes              median=     5.000 mean=     5.070 p10=     0.000 p90=    11.800
  destination_only_nodes         median=     5.000 mean=     5.070 p10=     0.000 p90=    11.800
  self_loops                     median=     0.000 mean=     0.000 p10=     0.000 p90=     0.000
  time_span_minutes              median=  4399.000 mean=  3843.047 p10=   623.600 p90=  6059.800
  chronological_gap_median       median=   266.000 mean=   792.488 p10=   132.800 p90=  2181.000
  amount_median                  median= 11970.250 mean= 25861.496 p10=  4030.491 p90= 51584.681

==============================================================================================================
3. AMOUNT DNA BY TYPOLOGY
==============================================================================================================

BIPARTITE
  p1 : 189.839000
  p5 : 761.226000
  p10: 1,900.900000
  p25: 5,725.110000
  p50: 12,601.650000
  p75: 26,420.470000
  p90: 483,003.788000
  p95: 1,083,338.449000
  p99: 15,167,938.441800

CYCLE
  p1 : 150.958800
  p5 : 539.713000
  p10: 1,464.396000
  p25: 5,673.570000
  p50: 12,020.120000
  p75: 22,811.480000
  p90: 113,819.136000
  p95: 1,045,212.544000
  p99: 12,670,083.793800

FAN-IN
  p1 : 198.717700
  p5 : 948.204500
  p10: 1,613.380000
  p25: 5,225.650000
  p50: 11,379.330000
  p75: 16,892.440000
  p90: 37,638.058000
  p95: 68,714.341000
  p99: 10,471,136.604100

FAN-OUT
  p1 : 415.898100
  p5 : 1,488.028500
  p10: 2,559.876000
  p25: 6,861.537500
  p50: 12,587.310000
  p75: 26,526.710000
  p90: 231,800.754000
  p95: 826,595.683500
  p99: 4,075,754.125100

GATHER-SCATTER
  p1 : 215.619500
  p5 : 1,015.580000
  p10: 2,033.145000
  p25: 5,903.327500
  p50: 12,454.600000
  p75: 19,535.525000
  p90: 137,009.285000
  p95: 1,033,885.527500
  p99: 38,693,437.717500

RANDOM
  p1 : 730.671000
  p5 : 1,583.605000
  p10: 2,266.170000
  p25: 4,749.230000
  p50: 13,044.810000
  p75: 21,135.700000
  p90: 1,105,578.270000
  p95: 1,596,691.910000
  p99: 45,854,299.828999

SCATTER-GATHER
  p1 : 339.410000
  p5 : 2,034.717500
  p10: 3,189.465000
  p25: 6,875.175000
  p50: 13,836.735000
  p75: 46,661.465000
  p90: 942,955.880000
  p95: 1,658,884.972500
  p99: 85,090,577.877500

STACK
  p1 : 261.028000
  p5 : 1,209.697500
  p10: 1,864.430000
  p25: 5,501.815000
  p50: 11,897.230000
  p75: 18,630.025000
  p90: 422,687.480000
  p95: 1,267,864.745000
  p99: 18,736,802.101000

==============================================================================================================
4. PAYMENT FORMAT BY TYPOLOGY
==============================================================================================================

BIPARTITE
                Count  Share_pct
Payment Format
ACH               263      100.0

CYCLE
                Count  Share_pct
Payment Format
ACH               287      100.0

FAN-IN
                Count  Share_pct
Payment Format
ACH               318      100.0

FAN-OUT
                Count  Share_pct
Payment Format
ACH               342      100.0

GATHER-SCATTER
                Count  Share_pct
Payment Format
ACH               716      100.0

RANDOM
                Count  Share_pct
Payment Format
ACH               191      100.0

SCATTER-GATHER
                Count  Share_pct
Payment Format
ACH               626      100.0

STACK
                Count  Share_pct
Payment Format
ACH               465  99.785408
Bitcoin             1   0.214592

==============================================================================================================
5. RECEIVING CURRENCY BY TYPOLOGY
==============================================================================================================

BIPARTITE
                    Count  Share_pct
Receiving Currency
Euro                   85  32.319392
US Dollar              81  30.798479
Saudi Riyal            32  12.167300
Ruble                  11   4.182510
Rupee                  10   3.802281
Yuan                   10   3.802281
UK Pound                7   2.661597
Yen                     6   2.281369
Canadian Dollar         6   2.281369
Mexican Peso            6   2.281369
Swiss Franc             4   1.520913
Australian Dollar       3   1.140684
Shekel                  2   0.760456

CYCLE
                    Count  Share_pct
Receiving Currency
US Dollar             108  37.630662
Euro                   74  25.783972
Saudi Riyal            42  14.634146
Rupee                  11   3.832753
Yuan                    9   3.135889
Ruble                   8   2.787456
Swiss Franc             7   2.439024
UK Pound                7   2.439024
Australian Dollar       6   2.090592
Yen                     4   1.393728
Mexican Peso            4   1.393728
Shekel                  3   1.045296
Canadian Dollar         2   0.696864
Brazil Real             2   0.696864

FAN-IN
                    Count  Share_pct
Receiving Currency
Euro                  124  38.993711
US Dollar             111  34.905660
Saudi Riyal            36  11.320755
Canadian Dollar        16   5.031447
Swiss Franc            12   3.773585
Australian Dollar      11   3.459119
Yuan                    8   2.515723

FAN-OUT
                    Count  Share_pct
Receiving Currency
US Dollar             107  31.286550
Euro                  102  29.824561
Saudi Riyal            43  12.573099
Yuan                   12   3.508772
Ruble                  12   3.508772
Swiss Franc            11   3.216374
Australian Dollar      10   2.923977
Mexican Peso           10   2.923977
Rupee                   9   2.631579
Yen                     7   2.046784
UK Pound                7   2.046784
Shekel                  5   1.461988
Brazil Real             5   1.461988
Canadian Dollar         2   0.584795

GATHER-SCATTER
                    Count  Share_pct
Receiving Currency
US Dollar             294  41.061453
Euro                  160  22.346369
Saudi Riyal            84  11.731844
Swiss Franc            30   4.189944
Yuan                   29   4.050279
Yen                    24   3.351955
UK Pound               22   3.072626
Canadian Dollar        20   2.793296
Mexican Peso           15   2.094972
Australian Dollar      15   2.094972
Rupee                  11   1.536313
Ruble                   7   0.977654
Shekel                  3   0.418994
Brazil Real             2   0.279330

RANDOM
                    Count  Share_pct
Receiving Currency
US Dollar              60  31.413613
Euro                   56  29.319372
Saudi Riyal            24  12.565445
Rupee                   9   4.712042
Yuan                    9   4.712042
Canadian Dollar         6   3.141361
Mexican Peso            6   3.141361
Swiss Franc             5   2.617801
Ruble                   4   2.094241
Australian Dollar       4   2.094241
Yen                     4   2.094241
UK Pound                3   1.570681
Shekel                  1   0.523560

SCATTER-GATHER
                    Count  Share_pct
Receiving Currency
US Dollar             255  40.734824
Euro                  129  20.607029
Saudi Riyal            51   8.146965
Rupee                  40   6.389776
Swiss Franc            34   5.431310
Yen                    31   4.952077
Ruble                  19   3.035144

In [7]:
# ============================================================
# CELL 4 — ACCOUNT ID / BANK ID GENERATION DNA
#
# PURPOSE:
#   Learn exactly how IBM HI-Small identifiers look.
#
# ACCOUNT:
#   - length
#   - character distribution by position
#   - digit vs letter probability by position
#   - common prefixes
#   - common suffixes
#
# BANK:
#   - length distribution
#   - character distribution
#   - examples
#
# This will be used later to generate NEW realistic IDs.
#
# NO SOURCE FILES MODIFIED.
# ============================================================

from pathlib import Path
from collections import Counter
import pandas as pd
import numpy as np
import json
import string
import re

# ============================================================
# 1. PATH
# ============================================================

ACCOUNTS_PATH = Path(
    "/kaggle/input/datasets/ealtman2019/"
    "ibm-transactions-for-anti-money-laundering-aml/"
    "HI-Small_accounts.csv"
)

TX_PATH = Path(
    "/kaggle/input/datasets/ealtman2019/"
    "ibm-transactions-for-anti-money-laundering-aml/"
    "HI-Small_Trans.csv"
)

if not ACCOUNTS_PATH.exists():
    raise FileNotFoundError(ACCOUNTS_PATH)

if not TX_PATH.exists():
    raise FileNotFoundError(TX_PATH)

# ============================================================
# 2. LOAD ACCOUNTS
# ============================================================

accounts = pd.read_csv(
    ACCOUNTS_PATH,
    dtype=str,
    keep_default_na=False
)

accounts["Account Number"] = (
    accounts["Account Number"]
    .astype(str)
    .str.strip()
)

accounts["Bank ID"] = (
    accounts["Bank ID"]
    .astype(str)
    .str.strip()
)

print("=" * 110)
print("ACCOUNT ID / BANK ID GENERATION DNA")
print("=" * 110)

print(
    "Account rows:",
    f"{len(accounts):,}"
)

# ============================================================
# 3. ACCOUNT ID VALIDATION
# ============================================================

account_series = (
    accounts["Account Number"]
    .drop_duplicates()
)

lengths = account_series.str.len()

print()
print("=" * 110)
print("1. ACCOUNT ID VALIDATION")
print("=" * 110)

print(
    "Unique account IDs:",
    f"{len(account_series):,}"
)

print(
    "Length distribution:"
)

print(
    lengths.value_counts()
    .sort_index()
    .to_string()
)

invalid_format = account_series[
    ~account_series.str.fullmatch(
        r"[A-Z0-9]{9}"
    )
]

print()
print(
    "Invalid 9-character uppercase-alphanumeric IDs:",
    f"{len(invalid_format):,}"
)

if len(invalid_format):
    print(
        invalid_format.head(20).to_string(
            index=False
        )
    )
else:
    print(
        "✅ Every unique account ID matches [A-Z0-9]{9}."
    )

# ============================================================
# 4. CHARACTER DISTRIBUTION BY POSITION
# ============================================================

print()
print("=" * 110)
print("2. CHARACTER DISTRIBUTION BY ACCOUNT POSITION")
print("=" * 110)

position_distributions = {}

for position in range(9):

    chars = (
        account_series
        .str[position]
    )

    counts = (
        chars.value_counts()
        .sort_values(
            ascending=False
        )
    )

    total = counts.sum()

    output = pd.DataFrame({
        "Count": counts,
        "Share_pct": (
            counts / total * 100.0
        )
    })

    position_distributions[
        str(position + 1)
    ] = {
        str(k): int(v)
        for k, v in counts.items()
    }

    print()
    print(
        f"POSITION {position + 1}"
    )

    print(
        output.head(20).to_string()
    )

# ============================================================
# 5. DIGIT / LETTER PROBABILITY BY POSITION
# ============================================================

print()
print("=" * 110)
print("3. DIGIT VS LETTER PROBABILITY BY POSITION")
print("=" * 110)

position_type_rows = []

for position in range(9):

    chars = (
        account_series
        .str[position]
    )

    is_digit = chars.str.isdigit()

    digit_count = int(
        is_digit.sum()
    )

    letter_count = int(
        (~is_digit).sum()
    )

    total = (
        digit_count
        + letter_count
    )

    row = {
        "Position": position + 1,
        "Digit_Count": digit_count,
        "Digit_Pct": (
            digit_count / total * 100.0
        ),
        "Letter_Count": letter_count,
        "Letter_Pct": (
            letter_count / total * 100.0
        )
    }

    position_type_rows.append(
        row
    )

position_type_df = pd.DataFrame(
    position_type_rows
)

print(
    position_type_df.round(4)
    .to_string(index=False)
)

# ============================================================
# 6. FIRST CHARACTER
# ============================================================

print()
print("=" * 110)
print("4. ACCOUNT PREFIX DISTRIBUTION")
print("=" * 110)

for prefix_length in [
    1,
    2,
    3,
    4
]:

    prefixes = (
        account_series
        .str[:prefix_length]
        .value_counts()
        .head(30)
    )

    print()
    print(
        f"TOP {prefix_length}-CHARACTER PREFIXES"
    )

    print(
        prefixes.to_string()
    )

# ============================================================
# 7. SUFFIX DISTRIBUTION
# ============================================================

print()
print("=" * 110)
print("5. ACCOUNT SUFFIX DISTRIBUTION")
print("=" * 110)

for suffix_length in [
    1,
    2,
    3
]:

    suffixes = (
        account_series
        .str[-suffix_length:]
        .value_counts()
        .head(30)
    )

    print()
    print(
        f"TOP {suffix_length}-CHARACTER SUFFIXES"
    )

    print(
        suffixes.to_string()
    )

# ============================================================
# 8. ACCOUNT ID EXAMPLES
# ============================================================

print()
print("=" * 110)
print("6. REAL ACCOUNT ID EXAMPLES")
print("=" * 110)

sample_accounts = (
    account_series
    .sample(
        min(
            100,
            len(account_series)
        ),
        random_state=20260919
    )
)

for account in sample_accounts.tolist():
    print(
        account
    )

# ============================================================
# 9. BANK ID STRUCTURE
# ============================================================

print()
print("=" * 110)
print("7. BANK ID STRUCTURE")
print("=" * 110)

bank_series = (
    accounts["Bank ID"]
    .drop_duplicates()
)

bank_lengths = (
    bank_series
    .str.len()
)

print(
    "Unique bank IDs:",
    f"{len(bank_series):,}"
)

print()
print(
    "Bank ID length distribution:"
)

print(
    bank_lengths
    .value_counts()
    .sort_index()
    .to_string()
)

invalid_bank_ids = bank_series[
    ~bank_series.str.fullmatch(
        r"\d+"
    )
]

print()
print(
    "Non-numeric bank IDs:",
    f"{len(invalid_bank_ids):,}"
)

# ============================================================
# 10. BANK ID CHARACTER DISTRIBUTION BY POSITION
# ============================================================

print()
print("=" * 110)
print("8. BANK ID CHARACTER DISTRIBUTION")
print("=" * 110)

bank_position_distributions = {}

max_bank_length = int(
    bank_lengths.max()
)

for position in range(
    max_bank_length
):

    chars = (
        bank_series
        .str[position]
    )

    chars = chars[
        chars.notna()
    ]

    counts = (
        chars.value_counts()
        .sort_values(
            ascending=False
        )
    )

    if counts.empty:
        continue

    bank_position_distributions[
        str(position + 1)
    ] = {
        str(k): int(v)
        for k, v in counts.items()
    }

    print()
    print(
        f"BANK POSITION {position + 1}"
    )

    print(
        counts.head(15)
        .to_string()
    )

# ============================================================
# 11. BANK EXAMPLES
# ============================================================

print()
print("=" * 110)
print("9. REAL BANK ID EXAMPLES")
print("=" * 110)

for bank in (
    bank_series
    .sample(
        min(
            100,
            len(bank_series)
        ),
        random_state=20260919
    )
    .tolist()
):

    print(
        bank
    )

# ============================================================
# 12. BANK ID → ACCOUNT COUNT
# ============================================================

print()
print("=" * 110)
print("10. BANK → ACCOUNT RELATIONSHIP")
print("=" * 110)

accounts_per_bank = (
    accounts
    .groupby(
        "Bank ID"
    )
    .size()
    .sort_values(
        ascending=False
    )
)

print(
    "Median accounts/bank:",
    f"{accounts_per_bank.median():.3f}"
)

print(
    "Mean accounts/bank:",
    f"{accounts_per_bank.mean():.3f}"
)

print(
    "P90 accounts/bank:",
    f"{accounts_per_bank.quantile(.90):.3f}"
)

print(
    "P95 accounts/bank:",
    f"{accounts_per_bank.quantile(.95):.3f}"
)

print(
    "P99 accounts/bank:",
    f"{accounts_per_bank.quantile(.99):.3f}"
)

print(
    "Max accounts/bank:",
    f"{accounts_per_bank.max():,}"
)

# ============================================================
# 13. BANK-SPECIFIC ACCOUNT ID CHARACTERISTICS
# ============================================================

print()
print("=" * 110)
print("11. BANK-SPECIFIC ACCOUNT PREFIX CHECK")
print("=" * 110)

# We don't want to assume that account ID prefixes encode
# banks. Check statistically.

bank_prefix_records = []

for bank_id, group in (
    accounts
    .groupby("Bank ID")
):

    accs = (
        group["Account Number"]
        .astype(str)
    )

    if len(accs) < 5:
        continue

    prefix3_unique = (
        accs
        .str[:3]
        .nunique()
    )

    prefix3_top_share = (
        accs
        .str[:3]
        .value_counts()
        .iloc[0]
        / len(accs)
    )

    bank_prefix_records.append({
        "Bank ID": bank_id,
        "Account_Count": len(accs),
        "Unique_3char_Prefixes": int(
            prefix3_unique
        ),
        "Top_3char_Prefix_Share_pct": (
            prefix3_top_share * 100.0
        )
    })

bank_prefix_df = pd.DataFrame(
    bank_prefix_records
)

if not bank_prefix_df.empty:

    print(
        bank_prefix_df[
            "Top_3char_Prefix_Share_pct"
        ]
        .describe()
        .round(4)
        .to_string()
    )

    print()
    print(
        "Banks with strongest 3-char account-prefix "
        "concentration:"
    )

    print(
        bank_prefix_df
        .sort_values(
            "Top_3char_Prefix_Share_pct",
            ascending=False
        )
        .head(30)
        .to_string(index=False)
    )

# ============================================================
# 14. SAVE ID DNA
# ============================================================

OUTPUT_DIR = Path(
    "/kaggle/working/AML_GNN_ONLY/data"
)

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

position_type_path = (
    OUTPUT_DIR /
    "HI-Small_account_id_position_types.csv"
)

position_type_df.to_csv(
    position_type_path,
    index=False
)

accounts_per_bank_path = (
    OUTPUT_DIR /
    "HI-Small_accounts_per_bank.csv"
)

accounts_per_bank.to_csv(
    accounts_per_bank_path,
    header=["Account_Count"]
)

if not bank_prefix_df.empty:

    bank_prefix_path = (
        OUTPUT_DIR /
        "HI-Small_bank_account_prefix_behavior.csv"
    )

    bank_prefix_df.to_csv(
        bank_prefix_path,
        index=False
    )

# ============================================================
# 15. MASTER JSON
# ============================================================

id_dna = {
    "account_format": {
        "length": 9,
        "regex": "[A-Z0-9]{9}",
        "unique_account_ids": int(
            len(account_series)
        ),
        "position_character_distribution":
            position_distributions,
        "position_digit_letter":
            position_type_df.to_dict(
                orient="records"
            )
    },

    "bank_format": {
        "unique_bank_ids": int(
            len(bank_series)
        ),
        "length_distribution": {
            str(k): int(v)
            for k, v in (
                bank_lengths
                .value_counts()
                .sort_index()
                .items()
            )
        },
        "all_numeric": bool(
            len(invalid_bank_ids) == 0
        ),
        "position_distribution":
            bank_position_distributions
    },

    "bank_account_relationship": {
        "median_accounts_per_bank": float(
            accounts_per_bank.median()
        ),
        "mean_accounts_per_bank": float(
            accounts_per_bank.mean()
        ),
        "p90_accounts_per_bank": float(
            accounts_per_bank.quantile(.90)
        ),
        "p95_accounts_per_bank": float(
            accounts_per_bank.quantile(.95)
        ),
        "p99_accounts_per_bank": float(
            accounts_per_bank.quantile(.99)
        ),
        "max_accounts_per_bank": int(
            accounts_per_bank.max()
        )
    }
}

id_dna_path = (
    OUTPUT_DIR /
    "HI-Small_original_identifier_dna.json"
)

with open(
    id_dna_path,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        id_dna,
        f,
        indent=2
    )

# ============================================================
# 16. FINAL
# ============================================================

print()
print("=" * 110)
print("✅ IDENTIFIER DNA AUDIT COMPLETE")
print("=" * 110)

print(
    "Identifier DNA:",
    id_dna_path
)

print(
    "Position model:",
    position_type_path
)

print(
    "Accounts/bank:",
    accounts_per_bank_path
)

if not bank_prefix_df.empty:
    print(
        "Bank-prefix behavior:",
        bank_prefix_path
    )

print()
print(
    "NO NEW ACCOUNTS WERE CREATED."
)

print(
    "NO TRANSACTIONS WERE CREATED."
)

print(
    "NO ORIGINAL FILE WAS MODIFIED."
)

print("=" * 110)

==============================================================================================================
ACCOUNT ID / BANK ID GENERATION DNA
==============================================================================================================
Account rows: 518,581

==============================================================================================================
1. ACCOUNT ID VALIDATION
==============================================================================================================
Unique account IDs: 518,573
Length distribution:
Account Number
9    518573

Invalid 9-character uppercase-alphanumeric IDs: 0
✅ Every unique account ID matches [A-Z0-9]{9}.

==============================================================================================================
2. CHARACTER DISTRIBUTION BY ACCOUNT POSITION
==============================================================================================================

POSITION 1
                 Count  Share_pct
Account Number
8               518558  99.997107
1                   15   0.002893

POSITION 2
                 Count  Share_pct
Account Number
0               403414  77.793098
1               115159  22.206902

POSITION 3
                Count  Share_pct
Account Number
3               50670   9.771045
0               50396   9.718207
1               50142   9.669227
2               49749   9.593442
4               40812   7.870059
5               25444   4.906542
6               25268   4.872602
7               25255   4.870095
A               25224   4.864117
E               25191   4.857754
8               25167   4.853126
F               25128   4.845605
9               25118   4.843677
B               25084   4.837120
D               24974   4.815908
C               24951   4.811473

POSITION 4
                Count  Share_pct
Account Number
8               33553   6.470256
4               33408   6.442295
1               33378   6.436509
6               33245   6.410862
3               33122   6.387143
2               33049   6.373066
7               32979   6.359568
5               32687   6.303259
0               32299   6.228438
9               31926   6.156510
C               31904   6.152268
A               31694   6.111772
D               31361   6.047557
F               31332   6.041965
B               31325   6.040615
E               31311   6.037916

POSITION 5
                Count  Share_pct
Account Number
5               33102   6.383286
E               33085   6.380008
1               32918   6.347804
8               32857   6.336041
B               32595   6.285518
D               32537   6.274334
6               32461   6.259678
F               32370   6.242130
A               32286   6.225932
3               32277   6.224196
9               32186   6.206648
4               32136   6.197006
C               32120   6.193921
2               32058   6.181965
7               31878   6.147254
0               31707   6.114279

POSITION 6
                Count  Share_pct
Account Number
F               34050   6.566096
2               32738   6.313094
E               32707   6.307116
C               32654   6.296896
B               32634   6.293039
3               32543   6.275491
D               32453   6.258135
9               32391   6.246179
8               32278   6.224389
4               32257   6.220339
5               32231   6.215326
6               32157   6.201056
A               32144   6.198549
7               32004   6.171552
1               31943   6.159788
0               31389   6.052957

POSITION 7
                Count  Share_pct
Account Number
E               32878   6.340091
9               32792   6.323507
3               32762   6.317722
D               32618   6.289953
A               32537   6.274334
C               32484   6.264113
B               32473   6.261992
7               32381   6.244251
8               32341   6.236538
2               32329   6.234224
F               32302   6.229017
6               32265   6.221882
4               32241   6.217254
1               32155   6.200670
5               32085   6.187171
0               31930   6.157282

POSITION 8
                Count  Share_pct
Account Number
3               32649   6.295931
C               32516   6.270284
8               32485   6.264306
A               32468   6.261028
0               32462   6.259871
6               32441   6.255821
B               32438   6.255243
F               32420   6.251772
1               32409   6.249650
5               32403   6.248493
9               32380   6.244058
E               32356   6.239430
D               32336   6.235573
7               32296   6.227860
2               32279   6.224582
4               32235   6.216097

POSITION 9
                 Count  Share_pct
Account Number
0               504150  97.218714
1                14416   2.779936
8                    7   0.001350

==============================================================================================================
3. DIGIT VS LETTER PROBABILITY BY POSITION
==============================================================================================================
 Position  Digit_Count  Digit_Pct  Letter_Count  Letter_Pct
        1       518573   100.0000             0      0.0000
        2       518573   100.0000             0      0.0000
        3       368021    70.9680        150552     29.0320
        4       329646    63.5679        188927     36.4321
        5       323580    62.3982        194993     37.6018
        6       321931    62.0802        196642     37.9198
        7       323281    62.3405        195292     37.6595
        8       324039    62.4867        194534     37.5133
        9       518573   100.0000             0      0.0000

==============================================================================================================
4. ACCOUNT PREFIX DISTRIBUTION
==============================================================================================================

TOP 1-CHARACTER PREFIXES
Account Number
8    518558
1        15

TOP 2-CHARACTER PREFIXES
Account Number
80    403399
81    115159
10        15

TOP 3-CHARACTER PREFIXES
Account Number
803    25457
801    25448
805    25444
800    25343
802    25307
806    25268
807    25255
80A    25224
813    25213
80E    25191
808    25167
80F    25128
809    25118
80B    25084
804    25040
810    25038
80D    24974
80C    24951
811    24694
812    24442
814    15772
100       15

TOP 4-CHARACTER PREFIXES
Account Number
8146    1796
8148    1760
8054    1739
800C    1734
8088    1709
8140    1706
806C    1703
8142    1703
813D    1695
8003    1691
8051    1687
8147    1685
8107    1685
80AB    1685
8053    1676
80BF    1674
80EA    1672
8086    1672
805C    1669
8029    1669
8143    1668
803C    1668
8004    1661
8044    1661
805A    1656
8063    1651
813E    1649
8006    1647
80EE    1647
801C    1646

==============================================================================================================
5. ACCOUNT SUFFIX DISTRIBUTION
==============================================================================================================

TOP 1-CHARACTER SUFFIXES
Account Number
0    504150
1     14416
8         7

TOP 2-CHARACTER SUFFIXES
Account Number
30    31740
C0    31635
A0    31560
B0    31557
00    31547
60    31546
50    31542
F0    31528
10    31528
90    31504
80    31491
E0    31449
D0    31420
70    31373
40    31371
20    31359
81      994
71      922
21      920
D1      916
01      914
31      908
A1      907
E1      906
61      895
F1      892
11      881
B1      881
C1      880
91      876

TOP 3-CHARACTER SUFFIXES
Account Number
C30    2098
B00    2098
350    2092
330    2089
EE0    2081
930    2077
6A0    2057
A40    2054
9E0    2053
E90    2051
600    2051
EF0    2049
2A0    2046
EA0    2035
ED0    2035
340    2033
280    2030
8A0    2029
860    2028
F20    2028
160    2027
200    2027
700    2026
750    2024
C20    2023
D50    2022
F40    2022
D30    2022
F30    2019
1B0    2018

==============================================================================================================
6. REAL ACCOUNT ID EXAMPLES
==============================================================================================================
813643E91
802E26D10
80D607B40
80D9406A0
80ABCB140
80C1B6F80
80AD6D740
80EF95D30
811578000
807441840
80D8DB790
80C1625D0
80413A690
8019C1840
8077AE270
805C58C80
80B69F980
80A28EB80
811725250
806B9E0A0
8140B68F1
803F977F0
80F67BAC0
80FDA5E70
8114D1720
8024A6F10
807D08EB0
80B7A57A0
8134468A0
807A2C280
802B07470
813B82381
80E203C30
80AE31D20
80B899860
8049EE930
810A40D70
80F12D770
80275CC90
8081D4090
80B7C87F0
8005D0120
8069020F0
806FFAA60
807F80B50
80DE8F480
80F6F1C90
80C8F8910
80CA75380
80745B650
814072451
8046B84F0
803DBA730
80892FFF0
81375DEC1
80BA68450
80A3FAF90
80450CA60
80FC622D0
812BE61B0
804D22DB0
8041E6ED0
8005E5700
80B9D5980
807ACDF60
81061BE40
80F025D40
811F34860
804E726D0
802D94950
802AB01E0
809D30F80
806DE0250
8016AF890
808145E10
8095D1AA0
80BE915C0
812E53610
80B5DDD70
809B4B920
8093AB9F0
80A254A70
809902E80
80215D9F0
802570A20
8026C4070
80367E330
80A6351D0
801A52FA0
8043A0410
810AD3A90
807336B50
80CE2E5F0
80A049F80
8120FAD20
801CE5400
813CB9811
80FF4F070
80913EC70
80373AB80

==============================================================================================================
7. BANK ID STRUCTURE
==============================================================================================================
Unique bank IDs: 30,470

Bank ID length distribution:
Bank ID
1        8
2       18
3       27
4      545
5     5407
6    24465

Non-numeric bank IDs: 0

==============================================================================================================
8. BANK ID CHARACTER DISTRIBUTION
==============================================================================================================

BANK POSITION 1
Bank ID
3    28827
1      721
2      685
4      122
5       67
9       14
8       13
6       11
7       10

BANK POSITION 2
Bank ID
2    6047
1    6040
3    6032
4    5886
5    3792
8     651
9     648
7     648
6     645
0      73

BANK POSITION 3
Bank ID
2    3252
0    3244
4    3228
3    3222
5    3215
1    3173
6    2894
8    2797
7    2760
9    2659

BANK POSITION 4
Bank ID
2    3131
3    3088
1    3079
8    3063
0    3046
6    3037
4    3008
5    3007
9    2983
7    2975

BANK POSITION 5
Bank ID
4    3019
8    3019
1    3002
0    2998
5    2997
9    2994
6    2992
2    2971
3    2946
7    2934

BANK POSITION 6
Bank ID
9    2501
0    2484
3    2468
1    2458
5    2449
2    2446
4    2428
7    2421
6    2418
8    2392

==============================================================================================================
9. REAL BANK ID EXAMPLES
==============================================================================================================
318890
334680
336329
355288
312525
339243
32372
313869
344846
345490
321143
33156
311418
36816
330766
339686
335634
232304
325442
330958
355328
35585
337461
337582
38566
310600
320201
351729
329026
355231
318195
350680
341624
326222
122047
32879
348175
312551
352666
348226
32410
314944
315950
33933
338325
344800
31389
326194
320661
313936
333162
313280
314937
37390
31030
310620
338281
354493
333488
317183
323510
319999
346352
316335
34969
232583
315855
319913
313971
310553
38799
310306
354770
342872
353047
38532
337606
315055
32041
337754
324961
345930
319950
345085
31813
316039
327691
327877
39761
324981
314638
352717
325326
324833
39611
325883
327664
35596
334894
311577

==============================================================================================================
10. BANK → ACCOUNT RELATIONSHIP
==============================================================================================================
Median accounts/bank: 4.000
Mean accounts/bank: 17.019
P90 accounts/bank: 13.000
P95 accounts/bank: 31.000
P99 accounts/bank: 372.620
Max accounts/bank: 3,161

==============================================================================================================
11. BANK-SPECIFIC ACCOUNT PREFIX CHECK
==============================================================================================================
count    12427.0000
mean        46.0801
std         25.6893
min          9.0909
25%         25.0000
50%         40.0000
75%         62.5000
max        100.0000

Banks with strongest 3-char account-prefix concentration:
Bank ID  Account_Count  Unique_3char_Prefixes  Top_3char_Prefix_Share_pct
 322137              6                      1                       100.0
  54240              6                      1                       100.0
     70             15                      1                       100.0
  56045             19                      1                       100.0
  56018             27                      1                       100.0
 317333              9                      1                       100.0
 256550             20                      1                       100.0
 255654            136                      1                       100.0
 328995              7                      1                       100.0
 317263              5                      1                       100.0
 317269              8                      1                       100.0
 317277              7                      1                       100.0
 313863              5                      1                       100.0
 313864              6                      1                       100.0
 313807              7                      1                       100.0
 313815              5                      1                       100.0
 313816              5                      1                       100.0
 313819              6                      1                       100.0
 313822              5                      1                       100.0
 313763              5                      1                       100.0
 312791              5                      1                       100.0
 322175              8                      1                       100.0
  50562             17                      1                       100.0
  51127              7                      1                       100.0
 322184              5                      1                       100.0
 337866              8                      1                       100.0
 312669              9                      1                       100.0
 338550              7                      1                       100.0
 313933              5                      1                       100.0
 313942              7                      1                       100.0

==============================================================================================================
✅ IDENTIFIER DNA AUDIT COMPLETE
==============================================================================================================
Identifier DNA: /kaggle/working/AML_GNN_ONLY/data/HI-Small_original_identifier_dna.json
Position model: /kaggle/working/AML_GNN_ONLY/data/HI-Small_account_id_position_types.csv
Accounts/bank: /kaggle/working/AML_GNN_ONLY/data/HI-Small_accounts_per_bank.csv
Bank-prefix behavior: /kaggle/working/AML_GNN_ONLY/data/HI-Small_bank_account_prefix_behavior.csv

NO NEW ACCOUNTS WERE CREATED.
NO TRANSACTIONS WERE CREATED.
NO ORIGINAL FILE WAS MODIFIED.
==============================================================================================================

In [8]:
# ============================================================
# CELL 5 — REAL TRANSACTION BEHAVIOR SAMPLER / DNA
# ============================================================
# Purpose:
#   Learn the empirical conditional distributions from ORIGINAL
#   HI-Small so the future synthetic laundering generator
#   behaves like the real dataset.
#
# IMPORTANT:
#   - Reads ORIGINAL HI-Small only
#   - Creates NO synthetic transactions
#   - Modifies NO source files
# ============================================================

import os
import json
import numpy as np
import pandas as pd

# ------------------------------------------------------------
# PATHS
# ------------------------------------------------------------
DATA_ROOT = "/kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml"
WORK_DIR  = "/kaggle/working/AML_GNN_ONLY/data"

TRANS_PATH = os.path.join(DATA_ROOT, "HI-Small_Trans.csv")
OUT_JSON   = os.path.join(WORK_DIR, "HI-Small_transaction_behavior_sampler.json")

os.makedirs(WORK_DIR, exist_ok=True)

print("=" * 100)
print("CELL 5 — REAL TRANSACTION BEHAVIOR SAMPLER")
print("=" * 100)

# ------------------------------------------------------------
# LOAD
# ------------------------------------------------------------
usecols = [
    "Timestamp",
    "From Bank",
    "Account",
    "To Bank",
    "Account.1",
    "Amount Received",
    "Receiving Currency",
    "Amount Paid",
    "Payment Currency",
    "Payment Format",
    "Is Laundering"
]

df = pd.read_csv(
    TRANS_PATH,
    usecols=usecols
)

df["Timestamp"] = pd.to_datetime(df["Timestamp"], errors="coerce")

print("\nLoaded rows:", len(df))
print("Columns:", list(df.columns))

# ------------------------------------------------------------
# BASIC CLEANING FOR DNA ESTIMATION ONLY
# ------------------------------------------------------------
df["From Bank"] = df["From Bank"].astype(str)
df["To Bank"] = df["To Bank"].astype(str)
df["Account"] = df["Account"].astype(str)
df["Account.1"] = df["Account.1"].astype(str)

df["Amount Received"] = pd.to_numeric(
    df["Amount Received"], errors="coerce"
)

df["Amount Paid"] = pd.to_numeric(
    df["Amount Paid"], errors="coerce"
)

df["Is Laundering"] = pd.to_numeric(
    df["Is Laundering"], errors="coerce"
).fillna(0).astype(int)

df["Receiving Currency"] = df["Receiving Currency"].astype(str)
df["Payment Currency"] = df["Payment Currency"].astype(str)
df["Payment Format"] = df["Payment Format"].astype(str)

df = df.dropna(subset=[
    "Timestamp",
    "Amount Received",
    "Amount Paid"
]).copy()

# ------------------------------------------------------------
# TIME FEATURES
# ------------------------------------------------------------
df["hour"] = df["Timestamp"].dt.hour
df["minute"] = df["Timestamp"].dt.minute
df["weekday"] = df["Timestamp"].dt.dayofweek
df["date"] = df["Timestamp"].dt.date

# Minute-of-day is useful for realistic timestamp generation
df["minute_of_day"] = (
    df["Timestamp"].dt.hour * 60
    + df["Timestamp"].dt.minute
)

# ------------------------------------------------------------
# AMOUNT FEATURES
# ------------------------------------------------------------
# Log transform is much more useful for this heavy-tailed
# transaction distribution.
df["log_amount_received"] = np.log1p(
    np.clip(df["Amount Received"].values, 0, None)
)

df["log_amount_paid"] = np.log1p(
    np.clip(df["Amount Paid"].values, 0, None)
)

# ------------------------------------------------------------
# HELPER
# ------------------------------------------------------------
def value_counts_pct(series):
    vc = series.value_counts(dropna=False)
    total = vc.sum()

    return {
        str(k): {
            "count": int(v),
            "share_pct": float(v / total * 100)
        }
        for k, v in vc.items()
    }

def quantiles(series):
    s = pd.to_numeric(series, errors="coerce").dropna()

    q = s.quantile(
        [0.001, 0.01, 0.05, 0.10, 0.25,
         0.50, 0.75, 0.90, 0.95, 0.99, 0.999]
    )

    return {
        str(k): float(v)
        for k, v in q.items()
    }

# ============================================================
# 1. GLOBAL TIME DNA
# ============================================================
print("\n" + "=" * 80)
print("1. GLOBAL TIME DNA")
print("=" * 80)

time_dna = {
    "hour_distribution": value_counts_pct(df["hour"]),
    "weekday_distribution": value_counts_pct(df["weekday"]),
    "minute_of_day_distribution": value_counts_pct(df["minute_of_day"])
}

print("\nTop transaction hours:")
print(
    df["hour"]
    .value_counts()
    .sort_index()
    .to_string()
)

# ============================================================
# 2. AMOUNT DNA
# ============================================================
print("\n" + "=" * 80)
print("2. AMOUNT DNA")
print("=" * 80)

amount_dna = {
    "received": {
        "quantiles": quantiles(df["Amount Received"]),
        "log_quantiles": quantiles(df["log_amount_received"])
    },
    "paid": {
        "quantiles": quantiles(df["Amount Paid"]),
        "log_quantiles": quantiles(df["log_amount_paid"])
    }
}

print("\nAmount Received quantiles:")
print(pd.Series(amount_dna["received"]["quantiles"]))

# ============================================================
# 3. CURRENCY DNA
# ============================================================
print("\n" + "=" * 80)
print("3. CURRENCY DNA")
print("=" * 80)

currency_dna = {
    "receiving_currency": value_counts_pct(df["Receiving Currency"]),
    "payment_currency": value_counts_pct(df["Payment Currency"])
}

print("\nReceiving Currency:")
print(
    df["Receiving Currency"]
    .value_counts(normalize=True)
    .mul(100)
    .round(4)
    .to_string()
)

print("\nPayment Currency:")
print(
    df["Payment Currency"]
    .value_counts(normalize=True)
    .mul(100)
    .round(4)
    .to_string()
)

# ============================================================
# 4. PAYMENT FORMAT DNA
# ============================================================
print("\n" + "=" * 80)
print("4. PAYMENT FORMAT DNA")
print("=" * 80)

payment_format_dna = value_counts_pct(df["Payment Format"])

print(
    df["Payment Format"]
    .value_counts(normalize=True)
    .mul(100)
    .round(4)
    .to_string()
)

# ============================================================
# 5. CONDITIONAL PAYMENT FORMAT -> CURRENCY
# ============================================================
print("\n" + "=" * 80)
print("5. CONDITIONAL PAYMENT/CURRENCY DNA")
print("=" * 80)

format_currency = (
    df.groupby(
        ["Payment Format", "Payment Currency"],
        dropna=False
    )
    .size()
    .reset_index(name="count")
)

format_currency["share_pct"] = (
    format_currency["count"]
    /
    format_currency.groupby("Payment Format")["count"]
        .transform("sum")
    * 100
)

format_currency_map = {}

for fmt, g in format_currency.groupby("Payment Format"):
    format_currency_map[str(fmt)] = {
        str(row["Payment Currency"]): {
            "count": int(row["count"]),
            "share_pct": float(row["share_pct"])
        }
        for _, row in g.iterrows()
    }

# ------------------------------------------------------------
# Receiving currency conditioned on payment currency
# ------------------------------------------------------------
recv_pay = (
    df.groupby(
        ["Payment Currency", "Receiving Currency"],
        dropna=False
    )
    .size()
    .reset_index(name="count")
)

recv_pay["share_pct"] = (
    recv_pay["count"]
    /
    recv_pay.groupby("Payment Currency")["count"]
        .transform("sum")
    * 100
)

recv_pay_map = {}

for pay, g in recv_pay.groupby("Payment Currency"):
    recv_pay_map[str(pay)] = {
        str(row["Receiving Currency"]): {
            "count": int(row["count"]),
            "share_pct": float(row["share_pct"])
        }
        for _, row in g.iterrows()
    }

# ============================================================
# 6. PAYMENT FORMAT -> LAUNDERING RATE
# ============================================================
print("\n" + "=" * 80)
print("6. LAUNDERING RATE BY PAYMENT FORMAT")
print("=" * 80)

fmt_laundering = (
    df.groupby("Payment Format")["Is Laundering"]
    .agg(["count", "sum", "mean"])
)

fmt_laundering["rate_pct"] = (
    fmt_laundering["mean"] * 100
)

print(fmt_laundering.to_string())

# ============================================================
# 7. CURRENCY -> LAUNDERING RATE
# ============================================================
print("\n" + "=" * 80)
print("7. LAUNDERING RATE BY CURRENCY")
print("=" * 80)

currency_laundering = (
    df.groupby("Payment Currency")["Is Laundering"]
    .agg(["count", "sum", "mean"])
)

currency_laundering["rate_pct"] = (
    currency_laundering["mean"] * 100
)

print(currency_laundering.to_string())

# ============================================================
# 8. BANK RELATIONSHIP DNA
# ============================================================
print("\n" + "=" * 80)
print("8. BANK RELATIONSHIP DNA")
print("=" * 80)

# Global From-Bank frequency
from_bank_counts = (
    df["From Bank"]
    .value_counts()
)

to_bank_counts = (
    df["To Bank"]
    .value_counts()
)

bank_pair_counts = (
    df.groupby(
        ["From Bank", "To Bank"],
        sort=False
    )
    .size()
    .reset_index(name="count")
)

# Store top empirical pairs only.
# We do NOT need all 283k pairs in the JSON.
top_pairs = (
    bank_pair_counts
    .sort_values("count", ascending=False)
    .head(5000)
)

top_bank_pairs = [
    {
        "from_bank": str(row["From Bank"]),
        "to_bank": str(row["To Bank"]),
        "count": int(row["count"])
    }
    for _, row in top_pairs.iterrows()
]

bank_dna = {
    "unique_from_banks": int(df["From Bank"].nunique()),
    "unique_to_banks": int(df["To Bank"].nunique()),
    "unique_bank_pairs": int(
        bank_pair_counts.shape[0]
    ),
    "from_bank_top": {
        str(k): int(v)
        for k, v in from_bank_counts.head(1000).items()
    },
    "to_bank_top": {
        str(k): int(v)
        for k, v in to_bank_counts.head(1000).items()
    },
    "top_5000_bank_pairs": top_bank_pairs
}

print("Unique From Banks:", bank_dna["unique_from_banks"])
print("Unique To Banks:", bank_dna["unique_to_banks"])
print("Unique Bank Pairs:", bank_dna["unique_bank_pairs"])

# ============================================================
# 9. TRANSACTION AMOUNT BY PAYMENT FORMAT
# ============================================================
print("\n" + "=" * 80)
print("9. AMOUNT DNA BY PAYMENT FORMAT")
print("=" * 80)

amount_by_format = {}

for fmt, g in df.groupby("Payment Format"):
    amount_by_format[str(fmt)] = {
        "count": int(len(g)),
        "received_quantiles": quantiles(g["Amount Received"]),
        "paid_quantiles": quantiles(g["Amount Paid"])
    }

# ============================================================
# 10. AMOUNT DNA BY CURRENCY
# ============================================================
print("\n" + "=" * 80)
print("10. AMOUNT DNA BY PAYMENT CURRENCY")
print("=" * 80)

amount_by_currency = {}

for cur, g in df.groupby("Payment Currency"):
    amount_by_currency[str(cur)] = {
        "count": int(len(g)),
        "received_quantiles": quantiles(g["Amount Received"]),
        "paid_quantiles": quantiles(g["Amount Paid"])
    }

# ============================================================
# 11. LEGITIMATE-ONLY DNA
# ============================================================
print("\n" + "=" * 80)
print("11. LEGITIMATE-ONLY BEHAVIOR DNA")
print("=" * 80)

legit = df[df["Is Laundering"] == 0].copy()

legit_dna = {
    "rows": int(len(legit)),
    "amount_received_quantiles": quantiles(
        legit["Amount Received"]
    ),
    "amount_paid_quantiles": quantiles(
        legit["Amount Paid"]
    ),
    "hour_distribution": value_counts_pct(
        legit["hour"]
    ),
    "payment_format_distribution": value_counts_pct(
        legit["Payment Format"]
    ),
    "receiving_currency_distribution": value_counts_pct(
        legit["Receiving Currency"]
    ),
    "payment_currency_distribution": value_counts_pct(
        legit["Payment Currency"]
    )
}

# ============================================================
# 12. ORIGINAL LAUNDERING-ONLY DNA
# ============================================================
print("\n" + "=" * 80)
print("12. ORIGINAL LAUNDERING-ONLY DNA")
print("=" * 80)

laund = df[df["Is Laundering"] == 1].copy()

laund_dna = {
    "rows": int(len(laund)),
    "amount_received_quantiles": quantiles(
        laund["Amount Received"]
    ),
    "amount_paid_quantiles": quantiles(
        laund["Amount Paid"]
    ),
    "hour_distribution": value_counts_pct(
        laund["hour"]
    ),
    "payment_format_distribution": value_counts_pct(
        laund["Payment Format"]
    ),
    "receiving_currency_distribution": value_counts_pct(
        laund["Receiving Currency"]
    ),
    "payment_currency_distribution": value_counts_pct(
        laund["Payment Currency"]
    )
}

print("Original laundering rows:", len(laund))

# ============================================================
# 13. FINAL DNA MANIFEST
# ============================================================
dna = {
    "dataset": "IBM HI-Small",
    "source": TRANS_PATH,
    "rows_loaded": int(len(df)),
    "legitimate_rows": int((df["Is Laundering"] == 0).sum()),
    "laundering_rows": int((df["Is Laundering"] == 1).sum()),

    "time": time_dna,

    "amount": amount_dna,

    "currency": currency_dna,

    "payment_format": payment_format_dna,

    "payment_format_to_currency": format_currency_map,

    "payment_currency_to_receiving_currency": recv_pay_map,

    "payment_format_laundering_rate": {
        str(idx): {
            "count": int(row["count"]),
            "laundering_count": int(row["sum"]),
            "rate_pct": float(row["rate_pct"])
        }
        for idx, row in fmt_laundering.iterrows()
    },

    "payment_currency_laundering_rate": {
        str(idx): {
            "count": int(row["count"]),
            "laundering_count": int(row["sum"]),
            "rate_pct": float(row["rate_pct"])
        }
        for idx, row in currency_laundering.iterrows()
    },

    "bank": bank_dna,

    "amount_by_payment_format": amount_by_format,

    "amount_by_payment_currency": amount_by_currency,

    "legitimate_dna": legit_dna,

    "original_laundering_dna": laund_dna
}

# ------------------------------------------------------------
# SAVE
# ------------------------------------------------------------
with open(OUT_JSON, "w") as f:
    json.dump(dna, f, indent=2)

print("\n" + "=" * 100)
print("✅ CELL 5 COMPLETE")
print("=" * 100)
print("Saved:", OUT_JSON)
print("Rows used:", len(df))
print("No synthetic transactions created.")
print("No original file modified.")
print("=" * 100)

====================================================================================================
CELL 5 — REAL TRANSACTION BEHAVIOR SAMPLER
====================================================================================================

Loaded rows: 5078345
Columns: ['Timestamp', 'From Bank', 'Account', 'To Bank', 'Account.1', 'Amount Received', 'Receiving Currency', 'Amount Paid', 'Payment Currency', 'Payment Format', 'Is Laundering']

================================================================================
1. GLOBAL TIME DNA
================================================================================

Top transaction hours:
hour
0     634726
1     193728
2     193143
3     193249
4     193166
5     193900
6     194456
7     193336
8     192921
9     192952
10    193229
11    193500
12    192972
13    192521
14    192787
15    194871
16    193407
17    193154
18    193321
19    192824
20    192809
21    192192
22    191836
23    193345

================================================================================
2. AMOUNT DNA
================================================================================

Amount Received quantiles:
0.001    2.463440e-04
0.01     1.680776e-02
0.05     6.850000e+00
0.1      2.501000e+01
0.25     1.833700e+02
0.5      1.411010e+03
0.75     1.234627e+04
0.9      1.407368e+05
0.95     6.499065e+05
0.99     1.475123e+07
0.999    5.226685e+08
dtype: float64

================================================================================
3. CURRENCY DNA
================================================================================

Receiving Currency:
Receiving Currency
US Dollar            37.0070
Euro                 23.0787
Swiss Franc           4.6843
Yuan                  4.0673
Shekel                3.8396
Rupee                 3.7820
UK Pound              3.5692
Ruble                 3.0987
Yen                   3.0781
Bitcoin               2.9173
Canadian Dollar       2.7835
Australian Dollar     2.7275
Mexican Peso          2.1863
Saudi Riyal           1.7717
Brazil Real           1.4088

Payment Currency:
Payment Currency
US Dollar            37.3187
Euro                 23.0055
Swiss Franc           4.6247
Yuan                  4.2091
Shekel                3.7844
Rupee                 3.7454
UK Pound              3.5590
Yen                   3.0563
Ruble                 3.0557
Bitcoin               2.8763
Canadian Dollar       2.7576
Australian Dollar     2.6932
Mexican Peso          2.1692
Saudi Riyal           1.7528
Brazil Real           1.3922

================================================================================
4. PAYMENT FORMAT DNA
================================================================================
Payment Format
Cheque          36.7114
Credit Card     26.0582
ACH             11.8306
Cash             9.6664
Reinvestment     9.4727
Wire             3.3841
Bitcoin          2.8767

================================================================================
5. CONDITIONAL PAYMENT/CURRENCY DNA
================================================================================

================================================================================
6. LAUNDERING RATE BY PAYMENT FORMAT
================================================================================
                  count   sum      mean  rate_pct
Payment Format
ACH              600797  4483  0.007462  0.746175
Bitcoin          146091    56  0.000383  0.038332
Cash             490891   108  0.000220  0.022001
Cheque          1864331   324  0.000174  0.017379
Credit Card     1323324   206  0.000156  0.015567
Reinvestment     481056     0  0.000000  0.000000
Wire             171855     0  0.000000  0.000000

================================================================================
7. LAUNDERING RATE BY CURRENCY
================================================================================
                     count   sum      mean  rate_pct
Payment Currency
Australian Dollar   136769   127  0.000929  0.092857
Bitcoin             146066    56  0.000383  0.038339
Brazil Real          70703    57  0.000806  0.080619
Canadian Dollar     140042   128  0.000914  0.091401
Euro               1168297  1372  0.001174  0.117436
Mexican Peso        110159    92  0.000835  0.083516
Ruble               155178   133  0.000857  0.085708
Rupee               190202   167  0.000878  0.087801
Saudi Riyal          89014   374  0.004202  0.420159
Shekel              192184    95  0.000494  0.049432
Swiss Franc         234860   193  0.000822  0.082177
UK Pound            180738   132  0.000730  0.073034
US Dollar          1895172  1912  0.001009  0.100888
Yen                 155209   155  0.000999  0.099865
Yuan                213752   184  0.000861  0.086081

================================================================================
8. BANK RELATIONSHIP DNA
================================================================================
Unique From Banks: 30470
Unique To Banks: 15811
Unique Bank Pairs: 283353

================================================================================
9. AMOUNT DNA BY PAYMENT FORMAT
================================================================================

================================================================================
10. AMOUNT DNA BY PAYMENT CURRENCY
================================================================================

================================================================================
11. LEGITIMATE-ONLY BEHAVIOR DNA
================================================================================

================================================================================
12. ORIGINAL LAUNDERING-ONLY DNA
================================================================================
Original laundering rows: 5177

====================================================================================================
✅ CELL 5 COMPLETE
====================================================================================================
Saved: /kaggle/working/AML_GNN_ONLY/data/HI-Small_transaction_behavior_sampler.json
Rows used: 5078345
No synthetic transactions created.
No original file modified.
====================================================================================================

In [11]:
# ============================================================
# CELL 6 — EXACT IBM LAUNDERING PATTERN TEMPLATES
# ULTRA-ROBUST IBM BLOCK PARSER
# ============================================================

import os
import re
import json
import numpy as np
import pandas as pd

# ------------------------------------------------------------
# PATHS
# ------------------------------------------------------------
DATA_ROOT = "/kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml"
WORK_DIR = "/kaggle/working/AML_GNN_ONLY/data"

PATTERN_PATH = os.path.join(
    DATA_ROOT,
    "HI-Small_Patterns.txt"
)

OUT_JSON = os.path.join(
    WORK_DIR,
    "HI-Small_pattern_templates.json"
)

OUT_SUMMARY = os.path.join(
    WORK_DIR,
    "HI-Small_pattern_template_summary.csv"
)

os.makedirs(WORK_DIR, exist_ok=True)

print("=" * 100)
print("CELL 6 — EXACT IBM LAUNDERING PATTERN TEMPLATES")
print("ULTRA-ROBUST IBM BLOCK PARSER")
print("=" * 100)

# ============================================================
# 1. READ FILE
# ============================================================
with open(
    PATTERN_PATH,
    "r",
    encoding="utf-8",
    errors="replace"
) as f:
    raw_lines = f.readlines()

print("\nTotal lines:", len(raw_lines))

# Normalize only for parsing.
# Original transaction content is retained separately.
lines = []

for i, raw in enumerate(raw_lines, start=1):

    normalized = (
        raw
        .replace("\ufeff", "")
        .replace("\xa0", " ")
        .replace("\r", "")
        .replace("\n", "")
        .strip()
    )

    lines.append(
        {
            "line_no": i,
            "raw": raw.rstrip("\r\n"),
            "text": normalized
        }
    )

# ============================================================
# 2. HELPERS
# ============================================================
def is_id_line(text):
    """
    Detect:
        id="xxxxxx"
    even if spacing is unusual.
    """
    return (
        text.lower().startswith("id")
        and "=" in text
        and '"' in text
    )


def extract_id(text):

    m = re.search(
        r'id\s*=\s*"([^"]+)"',
        text,
        flags=re.IGNORECASE
    )

    if m:
        return m.group(1)

    return None


def is_begin_line(text):

    upper = text.upper()

    return (
        "BEGIN" in upper
        and "LAUNDERING" in upper
        and "ATTEMPT" in upper
    )


def is_end_line(text):

    upper = text.upper()

    return (
        "END" in upper
        and "LAUNDERING" in upper
        and "ATTEMPT" in upper
    )


def extract_typology(text):

    """
    Handles formats such as:

    BEGIN LAUNDERING ATTEMPT - FAN-OUT: ...
    BEGIN LAUNDERING ATTEMPT-FAN-OUT: ...
    BEGIN LAUNDERING ATTEMPT - FAN-OUT
    """

    upper = text.upper()

    marker = "LAUNDERING ATTEMPT"

    if marker not in upper:
        return None

    tail = text[
        upper.index(marker) + len(marker):
    ].strip()

    # Remove leading separators
    tail = tail.lstrip(" :-=\t")

    # Anything before ':' is the typology
    typology = tail.split(":", 1)[0].strip()

    # Remove accidental trailing separators
    typology = typology.strip(" :-=")

    if not typology:
        return None

    return typology.upper()


def parse_transaction(text):

    """
    IBM pattern rows contain exactly 11 comma-separated fields.
    """

    parts = [
        x.strip()
        for x in text.split(",")
    ]

    if len(parts) != 11:
        return None

    timestamp = parts[0]

    # Timestamp validation
    ts = pd.to_datetime(
        timestamp,
        format="%Y/%m/%d %H:%M",
        errors="coerce"
    )

    if pd.isna(ts):
        return None

    try:

        amount_received = float(
            parts[5]
        )

        amount_paid = float(
            parts[7]
        )

        label = int(
            parts[10]
        )

    except Exception:

        return None

    return {

        "timestamp": timestamp,

        "from_bank": str(
            parts[1]
        ),

        "from_account": str(
            parts[2]
        ),

        "to_bank": str(
            parts[3]
        ),

        "to_account": str(
            parts[4]
        ),

        "amount_received": amount_received,

        "receiving_currency": str(
            parts[6]
        ),

        "amount_paid": amount_paid,

        "payment_currency": str(
            parts[8]
        ),

        "payment_format": str(
            parts[9]
        ),

        "label": label
    }


# ============================================================
# 3. PARSE EPISODE BLOCKS
# ============================================================
#
# KEY CHANGE:
#
# We no longer require the BEGIN line to match an exact regex.
#
# We identify the BEGIN/END markers based on their textual
# content and parse everything between them.
# ============================================================

episodes = []

current = None
pending_id = None

for row in lines:

    line_no = row["line_no"]
    text = row["text"]

    if not text:
        continue

    # --------------------------------------------------------
    # ID
    # --------------------------------------------------------
    if is_id_line(text):

        extracted = extract_id(text)

        if extracted is not None:
            pending_id = extracted

        continue

    # --------------------------------------------------------
    # BEGIN
    # --------------------------------------------------------
    if is_begin_line(text):

        if current is not None:

            raise RuntimeError(
                f"\nNested BEGIN detected.\n"
                f"Line: {line_no}\n"
                f"Content: {text}\n"
                f"Current episode: "
                f"{current['typology']}"
            )

        typology = extract_typology(text)

        if typology is None:

            raise RuntimeError(
                f"\nCould not extract typology "
                f"from BEGIN line.\n"
                f"Line: {line_no}\n"
                f"Content: {text}"
            )

        current = {

            "episode_index": len(
                episodes
            ),

            "episode_id": pending_id,

            "typology": typology,

            "transactions": [],

            "source_begin_line": line_no
        }

        pending_id = None

        continue

    # --------------------------------------------------------
    # END
    # --------------------------------------------------------
    if is_end_line(text):

        if current is None:

            raise RuntimeError(
                f"\nEND marker encountered "
                f"without BEGIN.\n"
                f"Line: {line_no}\n"
                f"Content: {text}"
            )

        end_typology = extract_typology(text)

        if (
            end_typology is not None
            and end_typology != current["typology"]
        ):

            raise RuntimeError(
                f"\nTypology mismatch.\n"
                f"BEGIN: {current['typology']}\n"
                f"END: {end_typology}\n"
                f"Line: {line_no}"
            )

        if len(
            current["transactions"]
        ) == 0:

            raise RuntimeError(
                f"\nEmpty episode.\n"
                f"Episode: "
                f"{current['episode_index']}\n"
                f"Typology: "
                f"{current['typology']}"
            )

        current[
            "source_end_line"
        ] = line_no

        episodes.append(
            current
        )

        current = None

        continue

    # --------------------------------------------------------
    # TRANSACTION
    # --------------------------------------------------------
    tx = parse_transaction(text)

    if tx is not None:

        if current is None:

            raise RuntimeError(
                f"\nTransaction found outside "
                f"laundering episode.\n"
                f"Line: {line_no}\n"
                f"Content: {text}"
            )

        tx[
            "source_order"
        ] = len(
            current["transactions"]
        )

        tx[
            "source_line"
        ] = line_no

        current[
            "transactions"
        ].append(tx)

        continue

# ============================================================
# 4. FINAL STATE VALIDATION
# ============================================================
if current is not None:

    raise RuntimeError(
        "\nFile ended while an episode "
        "was still open.\n"
        f"Episode: "
        f"{current['episode_index']}\n"
        f"Typology: "
        f"{current['typology']}"
    )

print("\nParsed episodes:", len(episodes))

total_transactions = sum(
    len(ep["transactions"])
    for ep in episodes
)

print(
    "Parsed pattern transactions:",
    total_transactions
)

# ============================================================
# 5. EXPECTED IBM VALUES
# ============================================================
print("\n" + "=" * 80)
print("EXPECTED VS ACTUAL")
print("=" * 80)

print(
    "Expected episodes:       370"
)

print(
    "Actual episodes:        ",
    len(episodes)
)

print(
    "Expected transactions:   3209"
)

print(
    "Actual transactions:    ",
    total_transactions
)

# ============================================================
# 6. TYPOLOGY COUNTS
# ============================================================
typology_episode_counts = {}

typology_transaction_counts = {}

for ep in episodes:

    typ = ep["typology"]

    typology_episode_counts[typ] = (
        typology_episode_counts.get(
            typ,
            0
        ) + 1
    )

    typology_transaction_counts[typ] = (
        typology_transaction_counts.get(
            typ,
            0
        )
        +
        len(ep["transactions"])
    )

print("\nEpisode counts:")

for typ in sorted(
    typology_episode_counts
):

    print(
        f"{typ:20s}",
        typology_episode_counts[typ]
    )

print("\nTransaction counts:")

for typ in sorted(
    typology_transaction_counts
):

    print(
        f"{typ:20s}",
        typology_transaction_counts[typ]
    )

# ============================================================
# 7. BUILD GRAPH TEMPLATES
# ============================================================
templates = []
summary_rows = []

for ep in episodes:

    txs = ep["transactions"]

    # --------------------------------------------------------
    # Local node mapping
    # --------------------------------------------------------
    node_map = {}
    nodes = []

    def get_node(
        bank,
        account
    ):

        key = (
            str(bank),
            str(account)
        )

        if key not in node_map:

            node_map[key] = len(
                nodes
            )

            nodes.append(
                {
                    "node_id": len(nodes),
                    "original_bank": str(bank),
                    "original_account": str(account)
                }
            )

        return node_map[key]

    # --------------------------------------------------------
    # Timestamps
    # --------------------------------------------------------
    timestamps = pd.to_datetime(
        [
            tx["timestamp"]
            for tx in txs
        ],
        format="%Y/%m/%d %H:%M",
        errors="coerce"
    )

    if timestamps.isna().any():

        raise RuntimeError(
            f"Timestamp failure in "
            f"episode {ep['episode_index']}"
        )

    min_ts = timestamps.min()
    max_ts = timestamps.max()

    span_minutes = (
        max_ts - min_ts
    ).total_seconds() / 60.0

    # --------------------------------------------------------
    # Amount reference
    # --------------------------------------------------------
    amounts = np.array(
        [
            tx["amount_received"]
            for tx in txs
        ],
        dtype=float
    )

    median_amount = float(
        np.median(amounts)
    )

    if median_amount <= 0:
        median_amount = 1.0

    # --------------------------------------------------------
    # Transactions
    # --------------------------------------------------------
    template_transactions = []

    for order, (
        tx,
        ts
    ) in enumerate(
        zip(txs, timestamps)
    ):

        source_node = get_node(
            tx["from_bank"],
            tx["from_account"]
        )

        destination_node = get_node(
            tx["to_bank"],
            tx["to_account"]
        )

        relative_minutes = (
            ts - min_ts
        ).total_seconds() / 60.0

        amount_ratio = (
            tx["amount_received"]
            /
            median_amount
        )

        template_transactions.append(
            {

                "source_order": int(
                    order
                ),

                "source_node": int(
                    source_node
                ),

                "destination_node": int(
                    destination_node
                ),

                "relative_minutes": float(
                    relative_minutes
                ),

                "amount_received": float(
                    tx["amount_received"]
                ),

                "amount_paid": float(
                    tx["amount_paid"]
                ),

                "amount_ratio_to_episode_median": float(
                    amount_ratio
                ),

                "receiving_currency": (
                    tx["receiving_currency"]
                ),

                "payment_currency": (
                    tx["payment_currency"]
                ),

                "payment_format": (
                    tx["payment_format"]
                ),

                "label": int(
                    tx["label"]
                )
            }
        )

    # ========================================================
    # GRAPH STATISTICS
    # ========================================================
    in_degree = {
        i: 0
        for i in range(len(nodes))
    }

    out_degree = {
        i: 0
        for i in range(len(nodes))
    }

    adjacency = {
        i: []
        for i in range(len(nodes))
    }

    edges = []

    for tx in template_transactions:

        s = tx["source_node"]
        d = tx["destination_node"]

        out_degree[s] += 1
        in_degree[d] += 1

        adjacency[s].append(
            d
        )

        edges.append(
            {
                "source_node": int(s),
                "destination_node": int(d)
            }
        )

    # --------------------------------------------------------
    # Cycle detection
    # --------------------------------------------------------
    def detect_cycle(
        adjacency,
        n
    ):

        WHITE = 0
        GREY = 1
        BLACK = 2

        state = {
            i: WHITE
            for i in range(n)
        }

        def dfs(u):

            state[u] = GREY

            for v in adjacency[u]:

                if state[v] == GREY:
                    return True

                if state[v] == WHITE:

                    if dfs(v):
                        return True

            state[u] = BLACK

            return False

        for i in range(n):

            if state[i] == WHITE:

                if dfs(i):
                    return True

        return False

    cycle_present = detect_cycle(
        adjacency,
        len(nodes)
    )

    # --------------------------------------------------------
    # Bank counts
    # --------------------------------------------------------
    source_banks = set(
        tx["from_bank"]
        for tx in txs
    )

    destination_banks = set(
        tx["to_bank"]
        for tx in txs
    )

    # ========================================================
    # TEMPLATE
    # ========================================================
    template_id = (
        ep["episode_id"]
        if ep["episode_id"]
        else
        f"{ep['typology']}_{ep['episode_index']:04d}"
    )

    template = {

        "template_id": str(
            template_id
        ),

        "episode_index": int(
            ep["episode_index"]
        ),

        "source_episode_id": (
            str(ep["episode_id"])
            if ep["episode_id"]
            else None
        ),

        "typology": ep[
            "typology"
        ],

        "transaction_count": int(
            len(template_transactions)
        ),

        "node_count": int(
            len(nodes)
        ),

        "source_bank_count": int(
            len(source_banks)
        ),

        "destination_bank_count": int(
            len(destination_banks)
        ),

        "max_in_degree": int(
            max(in_degree.values())
        ),

        "max_out_degree": int(
            max(out_degree.values())
        ),

        "cycle_present": bool(
            cycle_present
        ),

        "episode_span_minutes": float(
            span_minutes
        ),

        "median_amount": float(
            median_amount
        ),

        "nodes": [
            {
                "node_id": int(
                    node["node_id"]
                )
            }
            for node in nodes
        ],

        "edges": edges,

        "transactions": template_transactions
    }

    templates.append(
        template
    )

    summary_rows.append(
        {

            "template_id": str(
                template_id
            ),

            "episode_index": int(
                ep["episode_index"]
            ),

            "source_episode_id": (
                str(ep["episode_id"])
                if ep["episode_id"]
                else None
            ),

            "typology": ep[
                "typology"
            ],

            "transaction_count": len(
                template_transactions
            ),

            "node_count": len(
                nodes
            ),

            "source_bank_count": len(
                source_banks
            ),

            "destination_bank_count": len(
                destination_banks
            ),

            "max_in_degree": max(
                in_degree.values()
            ),

            "max_out_degree": max(
                out_degree.values()
            ),

            "cycle_present": cycle_present,

            "episode_span_minutes": span_minutes,

            "median_amount": median_amount
        }
    )

# ============================================================
# 8. SUMMARY DATAFRAME
# ============================================================
summary_df = pd.DataFrame(
    summary_rows
)

# ============================================================
# 9. IBM PATTERN SUMMARY
# ============================================================
print("\n" + "=" * 100)
print("PATTERN TEMPLATE SUMMARY")
print("=" * 100)

typology_summary = (
    summary_df
    .groupby("typology")
    .agg(
        episodes=(
            "template_id",
            "count"
        ),

        transactions=(
            "transaction_count",
            "sum"
        ),

        median_transactions=(
            "transaction_count",
            "median"
        ),

        median_nodes=(
            "node_count",
            "median"
        ),

        median_source_banks=(
            "source_bank_count",
            "median"
        ),

        median_destination_banks=(
            "destination_bank_count",
            "median"
        ),

        median_span_minutes=(
            "episode_span_minutes",
            "median"
        ),

        median_amount=(
            "median_amount",
            "median"
        )
    )
    .sort_index()
)

print(
    typology_summary.to_string()
)

# ============================================================
# 10. EPISODE ID VALIDATION
# ============================================================
episode_ids = [
    ep["episode_id"]
    for ep in episodes
    if ep["episode_id"] is not None
]

print("\n" + "=" * 100)
print("EPISODE ID VALIDATION")
print("=" * 100)

print(
    "Episodes with IDs:",
    len(episode_ids)
)

print(
    "Unique IDs:",
    len(set(episode_ids))
)

# ============================================================
# 11. LABEL VALIDATION
# ============================================================
labels = []

for ep in episodes:

    for tx in ep["transactions"]:

        labels.append(
            tx["label"]
        )

label_counts = (
    pd.Series(labels)
    .value_counts()
    .sort_index()
)

print("\nPattern transaction labels:")
print(
    label_counts.to_string()
)

# ============================================================
# 12. SAVE SUMMARY
# ============================================================
summary_df.to_csv(
    OUT_SUMMARY,
    index=False
)

# ============================================================
# 13. SAVE TEMPLATES
# ============================================================
manifest = {

    "dataset": "IBM HI-Small",

    "source_file": PATTERN_PATH,

    "template_count": int(
        len(templates)
    ),

    "total_template_transactions": int(
        total_transactions
    ),

    "typologies": sorted(
        typology_episode_counts.keys()
    ),

    "templates": templates
}

with open(
    OUT_JSON,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        manifest,
        f,
        indent=2
    )

# ============================================================
# 14. FINAL VALIDATION
# ============================================================
print("\n" + "=" * 100)
print("FINAL VALIDATION")
print("=" * 100)

print(
    "Episodes:",
    len(templates)
)

print(
    "Transactions:",
    total_transactions
)

print(
    "Typologies:",
    sorted(
        typology_episode_counts.keys()
    )
)

print(
    "Episodes with IBM IDs:",
    len(episode_ids)
)

print(
    "Unique IBM IDs:",
    len(set(episode_ids))
)

print(
    "Episodes containing cycles:",
    int(
        summary_df[
            "cycle_present"
        ].sum()
    )
)

print(
    "Zero-transaction templates:",
    int(
        (
            summary_df[
                "transaction_count"
            ] == 0
        ).sum()
    )
)

print("\nSaved:")
print(
    OUT_JSON
)

print(
    OUT_SUMMARY
)

print("\n" + "=" * 100)
print("✅ CELL 6 COMPLETE")
print("=" * 100)
print("NO SYNTHETIC TRANSACTIONS CREATED.")
print("NO ORIGINAL FILE MODIFIED.")
print("=" * 100)

====================================================================================================
CELL 6 — EXACT IBM LAUNDERING PATTERN TEMPLATES
ULTRA-ROBUST IBM BLOCK PARSER
====================================================================================================

Total lines: 4319

Parsed episodes: 370
Parsed pattern transactions: 3209

================================================================================
EXPECTED VS ACTUAL
================================================================================
Expected episodes:       370
Actual episodes:         370
Expected transactions:   3209
Actual transactions:     3209

Episode counts:
BIPARTITE            49
CYCLE                54
FAN-IN               40
FAN-OUT              48
GATHER-SCATTER       51
RANDOM               41
SCATTER-GATHER       44
STACK                43

Transaction counts:
BIPARTITE            263
CYCLE                287
FAN-IN               318
FAN-OUT              342
GATHER-SCATTER       716
RANDOM               191
SCATTER-GATHER       626
STACK                466

====================================================================================================
PATTERN TEMPLATE SUMMARY
====================================================================================================
                episodes  transactions  median_transactions  median_nodes  median_source_banks  median_destination_banks  median_span_minutes  median_amount
typology
BIPARTITE             49           263                  4.0           8.0                  4.0                       4.0               1460.0     14262.2300
CYCLE                 54           287                  4.0           4.0                  4.0                       4.0               4313.0     12089.8250
FAN-IN                40           318                  8.0           9.0                  6.0                       1.0               5096.0     11970.3825
FAN-OUT               48           342                  7.0           8.0                  1.0                       6.0               4599.5     13960.3225
GATHER-SCATTER        51           716                 14.0          15.0                  7.0                       6.0               9049.0     12576.9300
RANDOM                41           191                  3.0           4.0                  3.0                       3.0               2760.0     14252.7600
SCATTER-GATHER        44           626                 14.0           9.0                  7.5                       8.0               5326.0     14131.2225
STACK                 43           466                 10.0          15.0                  8.0                       8.0               4399.0     11970.2500

====================================================================================================
EPISODE ID VALIDATION
====================================================================================================
Episodes with IDs: 0
Unique IDs: 0

Pattern transaction labels:
1    3209

====================================================================================================
FINAL VALIDATION
====================================================================================================
Episodes: 370
Transactions: 3209
Typologies: ['BIPARTITE', 'CYCLE', 'FAN-IN', 'FAN-OUT', 'GATHER-SCATTER', 'RANDOM', 'SCATTER-GATHER', 'STACK']
Episodes with IBM IDs: 0
Unique IBM IDs: 0
Episodes containing cycles: 99
Zero-transaction templates: 0

Saved:
/kaggle/working/AML_GNN_ONLY/data/HI-Small_pattern_templates.json
/kaggle/working/AML_GNN_ONLY/data/HI-Small_pattern_template_summary.csv

====================================================================================================
✅ CELL 6 COMPLETE
====================================================================================================
NO SYNTHETIC TRANSACTIONS CREATED.
NO ORIGINAL FILE MODIFIED.
====================================================================================================

In [12]:
# ============================================================
# CELL 7 — REAL BANK CONNECTIVITY + ACCOUNT REGISTRY
# ============================================================
# Purpose:
#   Build generator-ready registries from ORIGINAL HI-Small.
#
# Creates:
#   1. Real bank registry
#   2. Legitimate bank-pair registry
#   3. Top legitimate neighbors per bank
#   4. Entity/account schema DNA
#
# IMPORTANT:
#   - ORIGINAL DATA ONLY
#   - NO synthetic transactions
#   - NO synthetic accounts
#   - NO original files modified
# ============================================================

import os
import json
import numpy as np
import pandas as pd

# ------------------------------------------------------------
# PATHS
# ------------------------------------------------------------
DATA_ROOT = "/kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml"
WORK_DIR = "/kaggle/working/AML_GNN_ONLY/data"

TRANS_PATH = os.path.join(
    DATA_ROOT,
    "HI-Small_Trans.csv"
)

ACCOUNTS_PATH = os.path.join(
    DATA_ROOT,
    "HI-Small_accounts.csv"
)

BANK_REGISTRY_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_real_bank_registry.csv"
)

BANK_PAIR_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_legitimate_bank_pairs.csv"
)

BANK_NEIGHBOR_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_legitimate_bank_neighbors.json"
)

ENTITY_DNA_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_entity_identifier_dna.json"
)

print("=" * 100)
print("CELL 7 — REAL BANK CONNECTIVITY + ACCOUNT REGISTRY")
print("=" * 100)

# ============================================================
# 1. LOAD ACCOUNTS TABLE
# ============================================================
print("\n" + "=" * 80)
print("1. ACCOUNTS TABLE")
print("=" * 80)

accounts = pd.read_csv(
    ACCOUNTS_PATH,
    dtype=str
)

print("Rows:", len(accounts))
print("Columns:")
for c in accounts.columns:
    print("  ", c)

# ------------------------------------------------------------
# Required fields
# ------------------------------------------------------------
required_columns = [
    "Bank Name",
    "Bank ID",
    "Account Number",
    "Entity ID",
    "Entity Name"
]

missing = [
    c for c in required_columns
    if c not in accounts.columns
]

if missing:
    raise RuntimeError(
        f"Missing required account columns: {missing}"
    )

# ============================================================
# 2. BANK ID -> BANK NAME VALIDATION
# ============================================================
print("\n" + "=" * 80)
print("2. BANK ID / BANK NAME VALIDATION")
print("=" * 80)

bank_name_conflicts = (
    accounts
    .groupby("Bank ID")["Bank Name"]
    .nunique()
)

conflicting_banks = (
    bank_name_conflicts[
        bank_name_conflicts > 1
    ]
)

print(
    "Unique Bank IDs:",
    accounts["Bank ID"].nunique()
)

print(
    "Unique Bank Names:",
    accounts["Bank Name"].nunique()
)

print(
    "Bank IDs with multiple names:",
    len(conflicting_banks)
)

if len(conflicting_banks) > 0:
    raise RuntimeError(
        "Bank ID -> Bank Name conflicts detected."
    )

# One canonical bank name
bank_name_map = (
    accounts[
        ["Bank ID", "Bank Name"]
    ]
    .drop_duplicates("Bank ID")
)

# ============================================================
# 3. ENTITY STRUCTURE DNA
# ============================================================
print("\n" + "=" * 80)
print("3. ENTITY STRUCTURE DNA")
print("=" * 80)

entity_accounts = (
    accounts
    .groupby("Entity ID")
    .size()
)

entity_banks = (
    accounts
    .groupby("Entity ID")["Bank ID"]
    .nunique()
)

print(
    "Unique entities:",
    accounts["Entity ID"].nunique()
)

print(
    "Entities with >=2 accounts:",
    int((entity_accounts >= 2).sum())
)

print(
    "Entities with >=2 banks:",
    int((entity_banks >= 2).sum())
)

print(
    "Maximum accounts/entity:",
    int(entity_accounts.max())
)

print(
    "Maximum banks/entity:",
    int(entity_banks.max())
)

# ------------------------------------------------------------
# Entity ID string DNA
# ------------------------------------------------------------
entity_id_lengths = (
    accounts["Entity ID"]
    .dropna()
    .astype(str)
    .str.len()
    .value_counts()
    .sort_index()
)

entity_name_lengths = (
    accounts["Entity Name"]
    .dropna()
    .astype(str)
    .str.len()
    .value_counts()
    .sort_index()
)

entity_id_digit_pct = (
    accounts["Entity ID"]
    .astype(str)
    .str.fullmatch(r"\d+")
    .mean()
    * 100
)

entity_id_alnum_pct = (
    accounts["Entity ID"]
    .astype(str)
    .str.fullmatch(r"[A-Za-z0-9]+")
    .mean()
    * 100
)

entity_dna = {
    "rows": int(len(accounts)),

    "unique_entities": int(
        accounts["Entity ID"].nunique()
    ),

    "unique_entity_names": int(
        accounts["Entity Name"].nunique()
    ),

    "entity_accounts": {
        "min": int(entity_accounts.min()),
        "median": float(entity_accounts.median()),
        "mean": float(entity_accounts.mean()),
        "p90": float(entity_accounts.quantile(0.90)),
        "p95": float(entity_accounts.quantile(0.95)),
        "p99": float(entity_accounts.quantile(0.99)),
        "max": int(entity_accounts.max())
    },

    "entity_banks": {
        "min": int(entity_banks.min()),
        "median": float(entity_banks.median()),
        "mean": float(entity_banks.mean()),
        "p90": float(entity_banks.quantile(0.90)),
        "p95": float(entity_banks.quantile(0.95)),
        "p99": float(entity_banks.quantile(0.99)),
        "max": int(entity_banks.max())
    },

    "entities_with_multiple_accounts": int(
        (entity_accounts >= 2).sum()
    ),

    "entities_with_multiple_banks": int(
        (entity_banks >= 2).sum()
    ),

    "entity_id_length_distribution": {
        str(k): int(v)
        for k, v in entity_id_lengths.items()
    },

    "entity_name_length_distribution": {
        str(k): int(v)
        for k, v in entity_name_lengths.items()
    },

    "entity_id_digits_only_pct": float(
        entity_id_digit_pct
    ),

    "entity_id_alphanumeric_pct": float(
        entity_id_alnum_pct
    )
}

print(
    "\nEntity ID length distribution:"
)

print(
    entity_id_lengths.to_string()
)

print(
    "\nEntity ID digits-only %:",
    round(entity_id_digit_pct, 4)
)

print(
    "Entity ID alphanumeric %:",
    round(entity_id_alnum_pct, 4)
)

# ============================================================
# 4. BANK ACCOUNT COUNTS
# ============================================================
print("\n" + "=" * 80)
print("4. ACCOUNTS PER BANK")
print("=" * 80)

accounts_per_bank = (
    accounts
    .groupby("Bank ID")
    .size()
    .rename("account_count")
)

print(
    "Median:",
    accounts_per_bank.median()
)

print(
    "Mean:",
    accounts_per_bank.mean()
)

print(
    "P90:",
    accounts_per_bank.quantile(0.90)
)

print(
    "P95:",
    accounts_per_bank.quantile(0.95)
)

print(
    "P99:",
    accounts_per_bank.quantile(0.99)
)

print(
    "Max:",
    accounts_per_bank.max()
)

# ============================================================
# 5. SCAN ORIGINAL TRANSACTIONS FOR BANK CONNECTIVITY
# ============================================================
print("\n" + "=" * 80)
print("5. SCANNING ORIGINAL TRANSACTIONS")
print("=" * 80)

tx_usecols = [
    "From Bank",
    "To Bank",
    "Is Laundering"
]

# ------------------------------------------------------------
# Aggregation containers
# ------------------------------------------------------------
from_counts = {}
to_counts = {}

legit_from_counts = {}
legit_to_counts = {}

pair_total = {}
pair_legit = {}

# ------------------------------------------------------------
# Chunked read
# ------------------------------------------------------------
chunk_size = 500_000

chunk_number = 0
total_rows_seen = 0

for chunk in pd.read_csv(
    TRANS_PATH,
    usecols=tx_usecols,
    chunksize=chunk_size,
    dtype={
        "From Bank": str,
        "To Bank": str
    }
):

    chunk_number += 1
    total_rows_seen += len(chunk)

    chunk["Is Laundering"] = (
        pd.to_numeric(
            chunk["Is Laundering"],
            errors="coerce"
        )
        .fillna(0)
        .astype(int)
    )

    # --------------------------------------------------------
    # All transaction counts
    # --------------------------------------------------------
    fc = chunk["From Bank"].value_counts()

    for bank, count in fc.items():
        from_counts[bank] = (
            from_counts.get(bank, 0)
            + int(count)
        )

    tc = chunk["To Bank"].value_counts()

    for bank, count in tc.items():
        to_counts[bank] = (
            to_counts.get(bank, 0)
            + int(count)
        )

    # --------------------------------------------------------
    # Legitimate only
    # --------------------------------------------------------
    legit_chunk = chunk[
        chunk["Is Laundering"] == 0
    ]

    lfc = legit_chunk[
        "From Bank"
    ].value_counts()

    for bank, count in lfc.items():
        legit_from_counts[bank] = (
            legit_from_counts.get(bank, 0)
            + int(count)
        )

    ltc = legit_chunk[
        "To Bank"
    ].value_counts()

    for bank, count in ltc.items():
        legit_to_counts[bank] = (
            legit_to_counts.get(bank, 0)
            + int(count)
        )

    # --------------------------------------------------------
    # Bank pairs
    # --------------------------------------------------------
    all_pairs = (
        chunk
        .groupby(
            ["From Bank", "To Bank"]
        )
        .size()
    )

    for (
        from_bank,
        to_bank
    ), count in all_pairs.items():

        key = (
            str(from_bank),
            str(to_bank)
        )

        pair_total[key] = (
            pair_total.get(key, 0)
            + int(count)
        )

    legit_pairs = (
        legit_chunk
        .groupby(
            ["From Bank", "To Bank"]
        )
        .size()
    )

    for (
        from_bank,
        to_bank
    ), count in legit_pairs.items():

        key = (
            str(from_bank),
            str(to_bank)
        )

        pair_legit[key] = (
            pair_legit.get(key, 0)
            + int(count)
        )

    print(
        f"  Chunk {chunk_number} "
        f"| rows processed = {total_rows_seen:,}"
    )

print(
    "\nTotal transaction rows scanned:",
    f"{total_rows_seen:,}"
)

# ============================================================
# 6. BUILD BANK REGISTRY
# ============================================================
print("\n" + "=" * 80)
print("6. BUILDING BANK REGISTRY")
print("=" * 80)

all_bank_ids = sorted(
    set(
        accounts["Bank ID"].astype(str)
    )
    |
    set(from_counts.keys())
    |
    set(to_counts.keys())
)

bank_registry_rows = []

for bank_id in all_bank_ids:

    bank_name = bank_name_map.loc[
        bank_name_map["Bank ID"] == bank_id,
        "Bank Name"
    ]

    if len(bank_name) > 0:
        bank_name = str(
            bank_name.iloc[0]
        )
    else:
        bank_name = "UNKNOWN"

    account_count = int(
        accounts_per_bank.get(
            bank_id,
            0
        )
    )

    source_count = int(
        from_counts.get(
            bank_id,
            0
        )
    )

    destination_count = int(
        to_counts.get(
            bank_id,
            0
        )
    )

    legit_source_count = int(
        legit_from_counts.get(
            bank_id,
            0
        )
    )

    legit_destination_count = int(
        legit_to_counts.get(
            bank_id,
            0
        )
    )

    bank_registry_rows.append(
        {
            "Bank ID": bank_id,
            "Bank Name": bank_name,
            "account_count": account_count,
            "source_transactions": source_count,
            "destination_transactions": destination_count,
            "total_transactions": (
                source_count
                +
                destination_count
            ),
            "legitimate_source_transactions":
                legit_source_count,
            "legitimate_destination_transactions":
                legit_destination_count,
            "legitimate_total_transactions":
                (
                    legit_source_count
                    +
                    legit_destination_count
                )
        }
    )

bank_registry = pd.DataFrame(
    bank_registry_rows
)

bank_registry = (
    bank_registry
    .sort_values(
        "legitimate_total_transactions",
        ascending=False
    )
    .reset_index(drop=True)
)

bank_registry.to_csv(
    BANK_REGISTRY_PATH,
    index=False
)

print(
    "Banks in registry:",
    len(bank_registry)
)

print(
    "\nTop 20 banks by legitimate activity:"
)

print(
    bank_registry.head(20).to_string(
        index=False
    )
)

# ============================================================
# 7. BUILD LEGITIMATE BANK-PAIR REGISTRY
# ============================================================
print("\n" + "=" * 80)
print("7. BUILDING LEGITIMATE BANK-PAIR REGISTRY")
print("=" * 80)

pair_rows = []

for (
    from_bank,
    to_bank
), total_count in pair_total.items():

    legit_count = pair_legit.get(
        (
            from_bank,
            to_bank
        ),
        0
    )

    pair_rows.append(
        {
            "From Bank": from_bank,
            "To Bank": to_bank,
            "total_count": int(
                total_count
            ),
            "legitimate_count": int(
                legit_count
            )
        }
    )

bank_pairs = pd.DataFrame(
    pair_rows
)

bank_pairs = (
    bank_pairs
    .sort_values(
        [
            "legitimate_count",
            "total_count"
        ],
        ascending=False
    )
    .reset_index(drop=True)
)

bank_pairs.to_csv(
    BANK_PAIR_PATH,
    index=False
)

print(
    "Unique bank pairs:",
    len(bank_pairs)
)

print(
    "Bank pairs observed in legitimate traffic:",
    int(
        (bank_pairs["legitimate_count"] > 0).sum()
    )
)

# ============================================================
# 8. BUILD TOP LEGITIMATE NEIGHBOR REGISTRY
# ============================================================
print("\n" + "=" * 80)
print("8. TOP LEGITIMATE BANK NEIGHBORS")
print("=" * 80)

neighbors_out = {}

# ------------------------------------------------------------
# Outgoing neighbors
# ------------------------------------------------------------
for bank_id, g in (
    bank_pairs[
        bank_pairs["legitimate_count"] > 0
    ]
    .groupby("From Bank")
):

    g = (
        g
        .sort_values(
            "legitimate_count",
            ascending=False
        )
        .head(50)
    )

    neighbors_out[str(bank_id)] = [
        {
            "to_bank": str(
                row["To Bank"]
            ),
            "count": int(
                row["legitimate_count"]
            )
        }
        for _, row in g.iterrows()
    ]

# ------------------------------------------------------------
# Incoming neighbors
# ------------------------------------------------------------
neighbors_in = {}

for bank_id, g in (
    bank_pairs[
        bank_pairs["legitimate_count"] > 0
    ]
    .groupby("To Bank")
):

    g = (
        g
        .sort_values(
            "legitimate_count",
            ascending=False
        )
        .head(50)
    )

    neighbors_in[str(bank_id)] = [
        {
            "from_bank": str(
                row["From Bank"]
            ),
            "count": int(
                row["legitimate_count"]
            )
        }
        for _, row in g.iterrows()
    ]

neighbor_registry = {
    "outgoing_top50": neighbors_out,
    "incoming_top50": neighbors_in
}

with open(
    BANK_NEIGHBOR_PATH,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        neighbor_registry,
        f,
        indent=2
    )

# ============================================================
# 9. BANK DISTRIBUTION STATISTICS
# ============================================================
print("\n" + "=" * 80)
print("9. BANK DISTRIBUTION CHECK")
print("=" * 80)

source_activity = (
    bank_registry[
        "legitimate_source_transactions"
    ]
)

destination_activity = (
    bank_registry[
        "legitimate_destination_transactions"
    ]
)

print(
    "Legitimate source-bank median:",
    source_activity.median()
)

print(
    "Legitimate source-bank mean:",
    source_activity.mean()
)

print(
    "Legitimate source-bank P90:",
    source_activity.quantile(0.90)
)

print(
    "Legitimate source-bank P95:",
    source_activity.quantile(0.95)
)

print(
    "Legitimate source-bank P99:",
    source_activity.quantile(0.99)
)

print(
    "Legitimate destination-bank median:",
    destination_activity.median()
)

print(
    "Legitimate destination-bank mean:",
    destination_activity.mean()
)

print(
    "Legitimate destination-bank P90:",
    destination_activity.quantile(0.90)
)

print(
    "Legitimate destination-bank P95:",
    destination_activity.quantile(0.95)
)

print(
    "Legitimate destination-bank P99:",
    destination_activity.quantile(0.99)
)

# ============================================================
# 10. SAVE ENTITY DNA
# ============================================================
with open(
    ENTITY_DNA_PATH,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        entity_dna,
        f,
        indent=2
    )

# ============================================================
# 11. FINAL FILE SUMMARY
# ============================================================
print("\n" + "=" * 100)
print("✅ CELL 7 COMPLETE")
print("=" * 100)

print("\nCreated:")
print(
    BANK_REGISTRY_PATH
)
print(
    BANK_PAIR_PATH
)
print(
    BANK_NEIGHBOR_PATH
)
print(
    ENTITY_DNA_PATH
)

print("\nNO SYNTHETIC ACCOUNTS CREATED.")
print("NO SYNTHETIC TRANSACTIONS CREATED.")
print("NO ORIGINAL FILE MODIFIED.")

print("=" * 100)

====================================================================================================
CELL 7 — REAL BANK CONNECTIVITY + ACCOUNT REGISTRY
====================================================================================================

================================================================================
1. ACCOUNTS TABLE
================================================================================
Rows: 518581
Columns:
   Bank Name
   Bank ID
   Account Number
   Entity ID
   Entity Name

================================================================================
2. BANK ID / BANK NAME VALIDATION
================================================================================
Unique Bank IDs: 30470
Unique Bank Names: 20053
Bank IDs with multiple names: 0

================================================================================
3. ENTITY STRUCTURE DNA
================================================================================
Unique entities: 166207
Entities with >=2 accounts: 63518
Entities with >=2 banks: 63362
Maximum accounts/entity: 7820
Maximum banks/entity: 1185

Entity ID length distribution:
Entity ID
9    518581

Entity ID digits-only %: 6.5583
Entity ID alphanumeric %: 100.0

================================================================================
4. ACCOUNTS PER BANK
================================================================================
Median: 4.0
Mean: 17.019396127338364
P90: 13.0
P95: 31.0
P99: 372.6200000000026
Max: 3161

================================================================================
5. SCANNING ORIGINAL TRANSACTIONS
================================================================================
  Chunk 1 | rows processed = 500,000
  Chunk 2 | rows processed = 1,000,000
  Chunk 3 | rows processed = 1,500,000
  Chunk 4 | rows processed = 2,000,000
  Chunk 5 | rows processed = 2,500,000
  Chunk 6 | rows processed = 3,000,000
  Chunk 7 | rows processed = 3,500,000
  Chunk 8 | rows processed = 4,000,000
  Chunk 9 | rows processed = 4,500,000
  Chunk 10 | rows processed = 5,000,000
  Chunk 11 | rows processed = 5,078,345

Total transaction rows scanned: 5,078,345

================================================================================
6. BUILDING BANK REGISTRY
================================================================================
Banks in registry: 60998

Top 20 banks by legitimate activity:
Bank ID Bank Name  account_count  source_transactions  destination_transactions  total_transactions  legitimate_source_transactions  legitimate_destination_transactions  legitimate_total_transactions
    070   UNKNOWN              0               449859                      2892              452751                          449226                                 2892                         452118
    012   UNKNOWN              0                71177                     34732              105909                           71105                                34651                         105756
    010   UNKNOWN              0                64791                     29926               94717                           64747                                29894                          94641
    001   UNKNOWN              0                62211                     30115               92326                           62161                                30062                          92223
    003   UNKNOWN              0                38413                     25627               64040                           38400                                25614                          64014
    020   UNKNOWN              0                41008                     22048               63056                           40941                                21994                          62935
    007   UNKNOWN              0                31086                     23029               54115                           31075                                23015                          54090
    015   UNKNOWN              0                30027                     22730               52757                           29988                                22703                          52691
   0211   UNKNOWN              0                30451                     20576               51027                           30425                                20549                          50974
   0116   UNKNOWN              0                30232                     20240               50472                           30209                                20224                          50433
    028   UNKNOWN              0                28584                     21160               49744                           28558                                21136                          49694
    011   UNKNOWN              0                29676                     13443               43119                           29629                                13375                          43004
    022   UNKNOWN              0                28652                     13962               42614                           28612                                13914                          42526
  00220   UNKNOWN              0                28164                     13754               41918                           28144                                13718                          41862
   0118   UNKNOWN              0                24988                     16448               41436                           24952                                16419                          41371
   0220   UNKNOWN              0                24253                     16871               41124                           24251                                16868                          41119
  01292   UNKNOWN              0                26835                     14122               40957                           26819                                14094                          40913
    023   UNKNOWN              0                26893                     13357               40250                           26861                                13314                          40175
    006   UNKNOWN              0                22855                     15821               38676                           22847                                15814                          38661
   0015   UNKNOWN              0                22484                     15991               38475                           22477                                15976                          38453

================================================================================
7. BUILDING LEGITIMATE BANK-PAIR REGISTRY
================================================================================
Unique bank pairs: 283540
Bank pairs observed in legitimate traffic: 281474

================================================================================
8. TOP LEGITIMATE BANK NEIGHBORS
================================================================================

================================================================================
9. BANK DISTRIBUTION CHECK
================================================================================
Legitimate source-bank median: 1.0
Legitimate source-bank mean: 83.16941539066855
Legitimate source-bank P90: 14.0
Legitimate source-bank P95: 24.0
Legitimate source-bank P99: 1678.0
Legitimate destination-bank median: 0.0
Legitimate destination-bank mean: 83.16941539066855
Legitimate destination-bank P90: 4.0
Legitimate destination-bank P95: 7.0
Legitimate destination-bank P99: 2965.2699999999895

====================================================================================================
✅ CELL 7 COMPLETE
====================================================================================================

Created:
/kaggle/working/AML_GNN_ONLY/data/HI-Small_real_bank_registry.csv
/kaggle/working/AML_GNN_ONLY/data/HI-Small_legitimate_bank_pairs.csv
/kaggle/working/AML_GNN_ONLY/data/HI-Small_legitimate_bank_neighbors.json
/kaggle/working/AML_GNN_ONLY/data/HI-Small_entity_identifier_dna.json

NO SYNTHETIC ACCOUNTS CREATED.
NO SYNTHETIC TRANSACTIONS CREATED.
NO ORIGINAL FILE MODIFIED.
====================================================================================================

In [14]:
# ============================================================
# CELL 8 — BANK ID FORMAT DIAGNOSTIC + CANONICAL MAPPING
# OPTIMIZED VERSION
# ============================================================

import os
import json
import pandas as pd
import numpy as np

# ------------------------------------------------------------
# PATHS
# ------------------------------------------------------------
DATA_ROOT = "/kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml"
WORK_DIR = "/kaggle/working/AML_GNN_ONLY/data"

TRANS_PATH = os.path.join(
    DATA_ROOT,
    "HI-Small_Trans.csv"
)

ACCOUNTS_PATH = os.path.join(
    DATA_ROOT,
    "HI-Small_accounts.csv"
)

OUT_MAPPING = os.path.join(
    WORK_DIR,
    "HI-Small_bank_id_canonical_mapping.csv"
)

OUT_JSON = os.path.join(
    WORK_DIR,
    "HI-Small_bank_id_canonical_dna.json"
)

os.makedirs(WORK_DIR, exist_ok=True)

print("=" * 100)
print("CELL 8 — BANK ID FORMAT DIAGNOSTIC + CANONICAL MAPPING")
print("OPTIMIZED VERSION")
print("=" * 100)

# ============================================================
# 1. LOAD UNIQUE IDS FROM TRANSACTION FILE
# ============================================================
print("\n" + "=" * 80)
print("1. LOADING TRANSACTION BANK IDS")
print("=" * 80)

tx_from = pd.read_csv(
    TRANS_PATH,
    usecols=["From Bank"],
    dtype=str
)

tx_to = pd.read_csv(
    TRANS_PATH,
    usecols=["To Bank"],
    dtype=str
)

tx_bank_series = pd.concat(
    [
        tx_from["From Bank"],
        tx_to["To Bank"]
    ],
    ignore_index=True
).dropna().astype(str)

transaction_bank_ids = set(
    tx_bank_series.unique()
)

print(
    "Unique transaction bank IDs:",
    len(transaction_bank_ids)
)

# ============================================================
# 2. LOAD ACCOUNT BANK IDS
# ============================================================
accounts = pd.read_csv(
    ACCOUNTS_PATH,
    usecols=["Bank ID", "Bank Name"],
    dtype=str
)

account_bank_ids = set(
    accounts["Bank ID"]
    .dropna()
    .astype(str)
    .unique()
)

print(
    "Unique accounts.csv bank IDs:",
    len(account_bank_ids)
)

# ============================================================
# 3. EXACT STRING OVERLAP
# ============================================================
print("\n" + "=" * 80)
print("2. EXACT STRING OVERLAP")
print("=" * 80)

exact_overlap = (
    transaction_bank_ids
    &
    account_bank_ids
)

print(
    "Exact overlapping IDs:",
    len(exact_overlap)
)

print(
    "Exact overlap %:",
    round(
        len(exact_overlap)
        /
        len(transaction_bank_ids)
        * 100,
        4
    )
)

# ============================================================
# 4. NORMALIZATION FUNCTION
# ============================================================
def normalize_bank_id(x):

    x = str(x).strip()

    if x == "":
        return None

    try:
        return str(int(x))
    except Exception:
        return x.lstrip("0") or "0"


# ============================================================
# 5. NORMALIZED ID SETS
# ============================================================
print("\n" + "=" * 80)
print("3. NORMALIZED NUMERIC OVERLAP")
print("=" * 80)

tx_norm_map = {
    x: normalize_bank_id(x)
    for x in transaction_bank_ids
}

acc_norm_map = {
    x: normalize_bank_id(x)
    for x in account_bank_ids
}

tx_normalized = set(
    tx_norm_map.values()
)

acc_normalized = set(
    acc_norm_map.values()
)

normalized_overlap = (
    tx_normalized
    &
    acc_normalized
)

print(
    "Unique normalized transaction IDs:",
    len(tx_normalized)
)

print(
    "Unique normalized account IDs:",
    len(acc_normalized)
)

print(
    "Normalized overlapping IDs:",
    len(normalized_overlap)
)

print(
    "Transaction normalized coverage:",
    round(
        len(normalized_overlap)
        /
        len(tx_normalized)
        * 100,
        4
    ),
    "%"
)

# ============================================================
# 6. OPTIMIZED TRANSACTION ID FREQUENCY
# ============================================================
print("\n" + "=" * 80)
print("4. TRANSACTION BANK-ID FREQUENCY")
print("=" * 80)

tx_id_counts = (
    tx_bank_series
    .value_counts()
    .rename("transaction_rows")
    .reset_index()
)

tx_id_counts.columns = [
    "transaction_bank_id",
    "transaction_rows"
]

tx_id_counts["normalized_bank_id"] = (
    tx_id_counts["transaction_bank_id"]
    .map(normalize_bank_id)
)

print(
    "Transaction bank-ID variants:",
    len(tx_id_counts)
)

# ============================================================
# 7. ACCOUNT-ID VARIANT TABLE
# ============================================================
account_id_variants = pd.DataFrame(
    {
        "account_bank_id": list(
            account_bank_ids
        )
    }
)

account_id_variants[
    "normalized_bank_id"
] = (
    account_id_variants[
        "account_bank_id"
    ]
    .map(normalize_bank_id)
)

# ============================================================
# 8. BUILD TRANSACTION-SIDE CANONICAL REPRESENTATION
# ============================================================
print("\n" + "=" * 80)
print("5. BUILDING CANONICAL TRANSACTION REPRESENTATION")
print("=" * 80)

# Sort by normalized ID and transaction frequency.
# The most frequently observed transaction representation
# becomes canonical.
canonical_candidates = (
    tx_id_counts
    .sort_values(
        [
            "normalized_bank_id",
            "transaction_rows"
        ],
        ascending=[
            True,
            False
        ]
    )
)

canonical = (
    canonical_candidates
    .drop_duplicates(
        "normalized_bank_id",
        keep="first"
    )
    .copy()
)

canonical = canonical.rename(
    columns={
        "transaction_bank_id":
            "canonical_transaction_bank_id"
    }
)

# ============================================================
# 9. LIST ALL TRANSACTION-SIDE VARIANTS
# ============================================================
tx_variants = (
    tx_id_counts
    .groupby(
        "normalized_bank_id"
    )["transaction_bank_id"]
    .agg(
        lambda x: "|".join(
            sorted(
                set(x),
                key=lambda z: (
                    len(str(z)),
                    str(z)
                )
            )
        )
    )
    .rename(
        "transaction_id_variants"
    )
    .reset_index()
)

# ============================================================
# 10. LIST ALL ACCOUNT-SIDE VARIANTS
# ============================================================
acc_variants = (
    account_id_variants
    .groupby(
        "normalized_bank_id"
    )["account_bank_id"]
    .agg(
        lambda x: "|".join(
            sorted(
                set(x),
                key=lambda z: (
                    len(str(z)),
                    str(z)
                )
            )
        )
    )
    .rename(
        "account_table_id_variants"
    )
    .reset_index()
)

# ============================================================
# 11. MERGE CANONICAL MAPPING
# ============================================================
mapping = (
    canonical[
        [
            "normalized_bank_id",
            "canonical_transaction_bank_id",
            "transaction_rows"
        ]
    ]
    .merge(
        tx_variants,
        on="normalized_bank_id",
        how="left"
    )
    .merge(
        acc_variants,
        on="normalized_bank_id",
        how="left"
    )
)

mapping[
    "has_account_record"
] = (
    mapping["normalized_bank_id"]
    .isin(
        acc_normalized
    )
    .astype(int)
)

mapping[
    "transaction_variant_count"
] = (
    mapping[
        "transaction_id_variants"
    ]
    .fillna("")
    .apply(
        lambda x:
        0 if x == ""
        else len(x.split("|"))
    )
)

mapping[
    "account_variant_count"
] = (
    mapping[
        "account_table_id_variants"
    ]
    .fillna("")
    .apply(
        lambda x:
        0 if x == ""
        else len(x.split("|"))
    )
)

# ============================================================
# 12. SHOW FORMAT MISMATCHES
# ============================================================
print("\n" + "=" * 80)
print("6. FORMAT-MISMATCH EXAMPLES")
print("=" * 80)

mismatch = mapping[
    mapping[
        "transaction_id_variants"
    ].fillna("")
    !=
    mapping[
        "account_table_id_variants"
    ].fillna("")
].copy()

print(
    "Normalized IDs with different string representations:",
    len(mismatch)
)

print(
    "\nFirst 30 examples:"
)

for _, row in mismatch.head(30).iterrows():

    print(
        f"Normalized={row['normalized_bank_id']} | "
        f"Transaction={row['transaction_id_variants']} | "
        f"Accounts={row['account_table_id_variants']} | "
        f"Canonical={row['canonical_transaction_bank_id']}"
    )

# ============================================================
# 13. BANK NAME CONSISTENCY AFTER NORMALIZATION
# ============================================================
print("\n" + "=" * 80)
print("7. BANK NAME CONSISTENCY")
print("=" * 80)

accounts["_normalized_bank_id"] = (
    accounts["Bank ID"]
    .map(normalize_bank_id)
)

name_counts = (
    accounts
    .groupby(
        "_normalized_bank_id"
    )["Bank Name"]
    .nunique()
)

name_conflicts = (
    name_counts[
        name_counts > 1
    ]
)

print(
    "Normalized bank IDs with multiple names:",
    len(name_conflicts)
)

# ============================================================
# 14. MATCHING COVERAGE
# ============================================================
print("\n" + "=" * 80)
print("8. MATCHING COVERAGE")
print("=" * 80)

matched_count = int(
    mapping[
        "has_account_record"
    ].sum()
)

unmatched_count = (
    len(tx_normalized)
    -
    matched_count
)

print(
    "Transaction normalized banks:",
    len(tx_normalized)
)

print(
    "Matched to accounts.csv:",
    matched_count
)

print(
    "Unmatched:",
    unmatched_count
)

print(
    "Coverage:",
    round(
        matched_count
        /
        len(tx_normalized)
        * 100,
        4
    ),
    "%"
)

# ============================================================
# 15. BANK-ID LENGTH DISTRIBUTIONS
# ============================================================
print("\n" + "=" * 80)
print("9. BANK-ID LENGTH DISTRIBUTIONS")
print("=" * 80)

tx_lengths = (
    pd.Series(
        [
            len(str(x))
            for x in transaction_bank_ids
        ]
    )
    .value_counts()
    .sort_index()
)

acc_lengths = (
    pd.Series(
        [
            len(str(x))
            for x in account_bank_ids
        ]
    )
    .value_counts()
    .sort_index()
)

print(
    "\nTransaction bank-ID lengths:"
)

print(
    tx_lengths.to_string()
)

print(
    "\nAccounts.csv bank-ID lengths:"
)

print(
    acc_lengths.to_string()
)

# ============================================================
# 16. CANONICAL FORMAT CHECK
# ============================================================
print("\n" + "=" * 80)
print("10. CANONICAL REPRESENTATION")
print("=" * 80)

print(
    "Canonical IDs:",
    len(mapping)
)

print(
    "Canonical IDs missing accounts record:",
    int(
        (
            mapping[
                "has_account_record"
            ] == 0
        ).sum()
    )
)

print(
    "\nTop 20 canonical IDs by transaction activity:"
)

display(
    mapping
    .sort_values(
        "transaction_rows",
        ascending=False
    )
    .head(20)
)

# ============================================================
# 17. SAVE CSV
# ============================================================
mapping.to_csv(
    OUT_MAPPING,
    index=False
)

# ============================================================
# 18. SAVE JSON DNA
# ============================================================
canonical_dna = {

    "transaction_unique_bank_ids": int(
        len(transaction_bank_ids)
    ),

    "accounts_unique_bank_ids": int(
        len(account_bank_ids)
    ),

    "exact_overlap": int(
        len(exact_overlap)
    ),

    "normalized_transaction_ids": int(
        len(tx_normalized)
    ),

    "normalized_account_ids": int(
        len(acc_normalized)
    ),

    "normalized_overlap": int(
        len(normalized_overlap)
    ),

    "normalized_coverage_pct": float(
        len(normalized_overlap)
        /
        len(tx_normalized)
        * 100
    ),

    "unmatched_normalized_ids": [
        str(x)
        for x in sorted(
            tx_normalized
            -
            acc_normalized,
            key=lambda z:
                int(z)
                if str(z).isdigit()
                else str(z)
        )
    ],

    "normalized_ids_with_format_mismatch":
        int(len(mismatch)),

    "normalized_bank_name_conflicts":
        int(len(name_conflicts)),

    "transaction_bank_id_length_distribution":
        {
            str(k): int(v)
            for k, v in tx_lengths.items()
        },

    "account_bank_id_length_distribution":
        {
            str(k): int(v)
            for k, v in acc_lengths.items()
        }
}

with open(
    OUT_JSON,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        canonical_dna,
        f,
        indent=2
    )

# ============================================================
# 19. FINAL
# ============================================================
print("\n" + "=" * 100)
print("✅ CELL 8 COMPLETE")
print("=" * 100)

print(
    "\nCanonical bank registry:",
    OUT_MAPPING
)

print(
    "Canonical bank DNA:",
    OUT_JSON
)

print(
    "\nKey result:"
)

print(
    f"  Transaction bank IDs      : "
    f"{len(transaction_bank_ids):,}"
)

print(
    f"  Accounts bank IDs         : "
    f"{len(account_bank_ids):,}"
)

print(
    f"  Normalized bank IDs       : "
    f"{len(tx_normalized):,}"
)

print(
    f"  Normalized overlap        : "
    f"{len(normalized_overlap):,}"
)

print(
    f"  Coverage                  : "
    f"{len(normalized_overlap) / len(tx_normalized) * 100:.2f}%"
)

print("\nNO SYNTHETIC DATA CREATED.")
print("NO ORIGINAL FILE MODIFIED.")

print("=" * 100)

====================================================================================================
CELL 8 — BANK ID FORMAT DIAGNOSTIC + CANONICAL MAPPING
OPTIMIZED VERSION
====================================================================================================

================================================================================
1. LOADING TRANSACTION BANK IDS
================================================================================
Unique transaction bank IDs: 30528
Unique accounts.csv bank IDs: 30470

================================================================================
2. EXACT STRING OVERLAP
================================================================================
Exact overlapping IDs: 0
Exact overlap %: 0.0

================================================================================
3. NORMALIZED NUMERIC OVERLAP
================================================================================
Unique normalized transaction IDs: 30470
Unique normalized account IDs: 30470
Normalized overlapping IDs: 30470
Transaction normalized coverage: 100.0 %

================================================================================
4. TRANSACTION BANK-ID FREQUENCY
================================================================================
Transaction bank-ID variants: 30528

================================================================================
5. BUILDING CANONICAL TRANSACTION REPRESENTATION
================================================================================

================================================================================
6. FORMAT-MISMATCH EXAMPLES
================================================================================
Normalized IDs with different string representations: 30470

First 30 examples:
Normalized=1 | Transaction=001 | Accounts=1 | Canonical=001
Normalized=10 | Transaction=010|0010 | Accounts=10 | Canonical=010
Normalized=10057 | Transaction=0010057 | Accounts=10057 | Canonical=0010057
Normalized=10060 | Transaction=0010060 | Accounts=10060 | Canonical=0010060
Normalized=10099 | Transaction=0010099 | Accounts=10099 | Canonical=0010099
Normalized=10232 | Transaction=0010232 | Accounts=10232 | Canonical=0010232
Normalized=1024 | Transaction=001024 | Accounts=1024 | Canonical=001024
Normalized=10344 | Transaction=0010344 | Accounts=10344 | Canonical=0010344
Normalized=10404 | Transaction=0010404 | Accounts=10404 | Canonical=0010404
Normalized=10441 | Transaction=0010441 | Accounts=10441 | Canonical=0010441
Normalized=1047 | Transaction=001047 | Accounts=1047 | Canonical=001047
Normalized=10581 | Transaction=0010581 | Accounts=10581 | Canonical=0010581
Normalized=10605 | Transaction=0010605 | Accounts=10605 | Canonical=0010605
Normalized=10614 | Transaction=0010614 | Accounts=10614 | Canonical=0010614
Normalized=10642 | Transaction=0010642 | Accounts=10642 | Canonical=0010642
Normalized=10656 | Transaction=0010656 | Accounts=10656 | Canonical=0010656
Normalized=1068 | Transaction=001068 | Accounts=1068 | Canonical=001068
Normalized=10709 | Transaction=0010709 | Accounts=10709 | Canonical=0010709
Normalized=10813 | Transaction=0010813 | Accounts=10813 | Canonical=0010813
Normalized=11 | Transaction=011 | Accounts=11 | Canonical=011
Normalized=110 | Transaction=0110 | Accounts=110 | Canonical=0110
Normalized=110057 | Transaction=0110057 | Accounts=110057 | Canonical=0110057
Normalized=11030 | Transaction=0011030 | Accounts=11030 | Canonical=0011030
Normalized=11056 | Transaction=011056 | Accounts=11056 | Canonical=011056
Normalized=110603 | Transaction=0110603 | Accounts=110603 | Canonical=0110603
Normalized=110836 | Transaction=0110836 | Accounts=110836 | Canonical=0110836
Normalized=111031 | Transaction=0111031 | Accounts=111031 | Canonical=0111031
Normalized=11107 | Transaction=011107 | Accounts=11107 | Canonical=011107
Normalized=111121 | Transaction=0111121 | Accounts=111121 | Canonical=0111121
Normalized=111141 | Transaction=0111141 | Accounts=111141 | Canonical=0111141

================================================================================
7. BANK NAME CONSISTENCY
================================================================================
Normalized bank IDs with multiple names: 0

================================================================================
8. MATCHING COVERAGE
================================================================================
Transaction normalized banks: 30470
Matched to accounts.csv: 30470
Unmatched: 0
Coverage: 100.0 %

================================================================================
9. BANK-ID LENGTH DISTRIBUTIONS
================================================================================

Transaction bank-ID lengths:
3       25
4       27
5      454
6     5074
7    24948

Accounts.csv bank-ID lengths:
1        8
2       18
3       27
4      545
5     5407
6    24465

================================================================================
10. CANONICAL REPRESENTATION
================================================================================
Canonical IDs: 30470
Canonical IDs missing accounts record: 0

Top 20 canonical IDs by transaction activity:

,normalized_bank_id,canonical_transaction_bank_id,transaction_rows,transaction_id_variants,account_table_id_variants,has_account_record,transaction_variant_count,account_variant_count
30434,70,070,452751,070,70,1,1,1
135,12,012,105909,012|0012,12,1,2,1
1,10,010,94717,010|0010,10,1,2,1
0,1,001,92326,001,1,1,1,1
1406,3,003,64040,003,3,1,1,1
721,20,020,63056,020,20,1,1,1
30433,7,007,54115,007,7,1,1,1
526,15,015,52757,015|0015,15,1,2,1
745,211,0211,51027,0211,211,1,1,1
94,116,0116,50472,0116,116,1,1,1
1342,28,028,49744,028,28,1,1,1
19,11,011,43119,011,11,1,1,1
845,22,022,42614,022,22,1,1,1
846,220,00220,41918,0220|00220,220,1,2,1
117,118,0118,41436,0118,118,1,1,1
254,1292,01292,40957,01292,1292,1,1,1
959,23,023,40250,023,23,1,1,1
30422,6,006,38676,006,6,1,1,1
347,1362,01362,37689,01362,1362,1,1,1
30233,4,004,37498,004,4,1,1,1

====================================================================================================
✅ CELL 8 COMPLETE
====================================================================================================

Canonical bank registry: /kaggle/working/AML_GNN_ONLY/data/HI-Small_bank_id_canonical_mapping.csv
Canonical bank DNA: /kaggle/working/AML_GNN_ONLY/data/HI-Small_bank_id_canonical_dna.json

Key result:
  Transaction bank IDs      : 30,528
  Accounts bank IDs         : 30,470
  Normalized bank IDs       : 30,470
  Normalized overlap        : 30,470
  Coverage                  : 100.00%

NO SYNTHETIC DATA CREATED.
NO ORIGINAL FILE MODIFIED.
====================================================================================================

In [15]:
# ============================================================
# CELL 9 — FINAL GENERATOR BANK POOL + ACCOUNT-ID SAMPLER
# ============================================================
#
# Uses:
#   - Original HI-Small_accounts.csv
#   - Corrected bank-ID mapping from Cell 8
#   - Bank activity registry generated in Cell 7
#
# Creates:
#   1. Final 30,470-bank generator pool
#   2. Bank sampling weights
#   3. Bank-specific account-prefix distributions
#   4. Account-ID positional character distributions
#   5. Compact generator configuration
#
# IMPORTANT:
#   - NO synthetic accounts
#   - NO synthetic transactions
#   - NO original files modified
# ============================================================

import os
import json
import numpy as np
import pandas as pd

# ------------------------------------------------------------
# PATHS
# ------------------------------------------------------------
DATA_ROOT = "/kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml"
WORK_DIR = "/kaggle/working/AML_GNN_ONLY/data"

ACCOUNTS_PATH = os.path.join(
    DATA_ROOT,
    "HI-Small_accounts.csv"
)

BANK_MAPPING_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_bank_id_canonical_mapping.csv"
)

OLD_BANK_REGISTRY_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_real_bank_registry.csv"
)

OUT_BANK_POOL = os.path.join(
    WORK_DIR,
    "HI-Small_final_generator_bank_pool.csv"
)

OUT_PREFIX_JSON = os.path.join(
    WORK_DIR,
    "HI-Small_bank_account_prefix_sampler.json"
)

OUT_ACCOUNT_JSON = os.path.join(
    WORK_DIR,
    "HI-Small_account_id_generator.json"
)

print("=" * 100)
print("CELL 9 — FINAL GENERATOR BANK POOL + ACCOUNT-ID SAMPLER")
print("=" * 100)

# ============================================================
# 1. LOAD SOURCE TABLES
# ============================================================
print("\n" + "=" * 80)
print("1. LOADING SOURCE TABLES")
print("=" * 80)

accounts = pd.read_csv(
    ACCOUNTS_PATH,
    dtype=str
)

mapping = pd.read_csv(
    BANK_MAPPING_PATH,
    dtype=str
)

old_registry = pd.read_csv(
    OLD_BANK_REGISTRY_PATH,
    dtype=str
)

print(
    "Accounts rows:",
    f"{len(accounts):,}"
)

print(
    "Canonical bank IDs:",
    f"{len(mapping):,}"
)

print(
    "Old registry rows:",
    f"{len(old_registry):,}"
)

# ============================================================
# 2. NORMALIZE BANK IDs
# ============================================================
def normalize_bank_id(x):

    x = str(x).strip()

    if x == "":
        return None

    try:
        return str(int(x))
    except Exception:
        return x.lstrip("0") or "0"


accounts[
    "normalized_bank_id"
] = (
    accounts["Bank ID"]
    .map(normalize_bank_id)
)

old_registry[
    "normalized_bank_id"
] = (
    old_registry["Bank ID"]
    .map(normalize_bank_id)
)

mapping[
    "normalized_bank_id"
] = (
    mapping[
        "normalized_bank_id"
    ].astype(str)
)

# ============================================================
# 3. COLLAPSE OLD REGISTRY TO NORMALIZED BANK LEVEL
# ============================================================
print("\n" + "=" * 80)
print("2. COLLAPSING BANK REGISTRY")
print("=" * 80)

# Convert numeric activity fields
activity_cols = [
    "source_transactions",
    "destination_transactions",
    "legitimate_source_transactions",
    "legitimate_destination_transactions"
]

for col in activity_cols:

    old_registry[col] = pd.to_numeric(
        old_registry[col],
        errors="coerce"
    ).fillna(0)

collapsed_activity = (
    old_registry
    .groupby(
        "normalized_bank_id",
        as_index=False
    )[activity_cols]
    .sum()
)

print(
    "Collapsed normalized banks:",
    len(collapsed_activity)
)

# ============================================================
# 4. BANK ACCOUNT COUNTS
# ============================================================
accounts_per_bank = (
    accounts
    .groupby(
        "normalized_bank_id"
    )
    .size()
    .rename("account_count")
    .reset_index()
)

# ============================================================
# 5. CANONICAL BANK REGISTRY
# ============================================================
print("\n" + "=" * 80)
print("3. BUILDING FINAL 30,470-BANK POOL")
print("=" * 80)

# Canonical transaction-side representation
canonical_bank = (
    mapping[
        [
            "normalized_bank_id",
            "canonical_transaction_bank_id"
        ]
    ]
    .drop_duplicates(
        "normalized_bank_id"
    )
)

# Canonical bank name from accounts.csv
bank_names = (
    accounts[
        [
            "normalized_bank_id",
            "Bank Name"
        ]
    ]
    .drop_duplicates(
        "normalized_bank_id"
    )
)

bank_pool = (
    canonical_bank
    .merge(
        bank_names,
        on="normalized_bank_id",
        how="left"
    )
    .merge(
        collapsed_activity,
        on="normalized_bank_id",
        how="left"
    )
    .merge(
        accounts_per_bank,
        on="normalized_bank_id",
        how="left"
    )
)

# Fill missing activity
for col in activity_cols:
    bank_pool[col] = (
        pd.to_numeric(
            bank_pool[col],
            errors="coerce"
        )
        .fillna(0)
        .astype(np.int64)
    )

bank_pool["account_count"] = (
    pd.to_numeric(
        bank_pool["account_count"],
        errors="coerce"
    )
    .fillna(0)
    .astype(np.int64)
)

# ------------------------------------------------------------
# Legitimate transaction weights
# ------------------------------------------------------------
bank_pool[
    "legit_source_weight"
] = (
    bank_pool[
        "legitimate_source_transactions"
    ]
    .astype(float)
)

bank_pool[
    "legit_destination_weight"
] = (
    bank_pool[
        "legitimate_destination_transactions"
    ]
    .astype(float)
)

# Avoid zero-probability banks in generic sampling.
# A tiny floor is used only for banks with no observed
# legitimate activity.
bank_pool[
    "source_sampling_weight"
] = (
    bank_pool[
        "legit_source_weight"
    ]
    .clip(lower=1.0)
)

bank_pool[
    "destination_sampling_weight"
] = (
    bank_pool[
        "legit_destination_weight"
    ]
    .clip(lower=1.0)
)

# ------------------------------------------------------------
# Normalize weights
# ------------------------------------------------------------
source_total = (
    bank_pool[
        "source_sampling_weight"
    ].sum()
)

destination_total = (
    bank_pool[
        "destination_sampling_weight"
    ].sum()
)

bank_pool[
    "source_probability"
] = (
    bank_pool[
        "source_sampling_weight"
    ]
    /
    source_total
)

bank_pool[
    "destination_probability"
] = (
    bank_pool[
        "destination_sampling_weight"
    ]
    /
    destination_total
)

# ------------------------------------------------------------
# Sort by normalized bank ID
# ------------------------------------------------------------
bank_pool = (
    bank_pool
    .sort_values(
        "normalized_bank_id"
    )
    .reset_index(drop=True)
)

print(
    "FINAL BANK POOL:",
    f"{len(bank_pool):,}",
    "banks"
)

# ============================================================
# 6. VALIDATION
# ============================================================
print("\n" + "=" * 80)
print("4. BANK POOL VALIDATION")
print("=" * 80)

print(
    "Expected normalized banks:",
    30470
)

print(
    "Actual normalized banks:",
    len(bank_pool)
)

print(
    "Unique canonical IDs:",
    bank_pool[
        "canonical_transaction_bank_id"
    ].nunique()
)

print(
    "Banks missing Bank Name:",
    int(
        bank_pool["Bank Name"]
        .isna()
        .sum()
    )
)

print(
    "Banks missing account records:",
    int(
        (
            bank_pool["account_count"] == 0
        ).sum()
    )
)

print(
    "Source probability sum:",
    bank_pool[
        "source_probability"
    ].sum()
)

print(
    "Destination probability sum:",
    bank_pool[
        "destination_probability"
    ].sum()
)

# ============================================================
# 7. TOP BANKS
# ============================================================
print("\n" + "=" * 80)
print("5. TOP BANKS BY LEGITIMATE ACTIVITY")
print("=" * 80)

display(
    bank_pool[
        [
            "normalized_bank_id",
            "canonical_transaction_bank_id",
            "Bank Name",
            "account_count",
            "legitimate_source_transactions",
            "legitimate_destination_transactions",
            "source_probability",
            "destination_probability"
        ]
    ]
    .sort_values(
        "legitimate_source_transactions",
        ascending=False
    )
    .head(20)
)

# ============================================================
# 8. BANK-SPECIFIC ACCOUNT PREFIX SAMPLER
# ============================================================
print("\n" + "=" * 80)
print("6. BANK-SPECIFIC ACCOUNT PREFIX SAMPLER")
print("=" * 80)

# Account IDs are known to be 9-character values.
accounts[
    "account_prefix_3"
] = (
    accounts["Account Number"]
    .astype(str)
    .str[:3]
)

accounts[
    "account_prefix_4"
] = (
    accounts["Account Number"]
    .astype(str)
    .str[:4]
)

# ------------------------------------------------------------
# For each normalized bank:
#   top 3-character account prefixes
#   empirical probability
# ------------------------------------------------------------
prefix_sampler = {}

for bank_id, g in (
    accounts
    .groupby(
        "normalized_bank_id"
    )
):

    prefix_counts = (
        g["account_prefix_3"]
        .value_counts()
    )

    total = prefix_counts.sum()

    prefix_sampler[str(bank_id)] = {
        "account_count": int(len(g)),
        "prefixes": [
            {
                "prefix": str(prefix),
                "count": int(count),
                "probability": float(
                    count / total
                )
            }
            for prefix, count in
            prefix_counts.head(100).items()
        ]
    }

print(
    "Banks with prefix models:",
    len(prefix_sampler)
)

# ============================================================
# 9. GLOBAL ACCOUNT-ID POSITION MODEL
# ============================================================
print("\n" + "=" * 80)
print("7. GLOBAL ACCOUNT-ID POSITION MODEL")
print("=" * 80)

account_values = (
    accounts["Account Number"]
    .astype(str)
)

position_models = {}

for pos in range(9):

    vc = (
        account_values
        .str[pos]
        .value_counts()
    )

    total = vc.sum()

    rows = []

    for char, count in vc.items():

        rows.append(
            {
                "char": str(char),
                "count": int(count),
                "probability": float(
                    count / total
                )
            }
        )

    position_models[str(pos + 1)] = rows

    print(
        f"Position {pos + 1}: "
        f"{len(rows)} possible characters"
    )

# ============================================================
# 10. POSITION DIGIT/LETTER DNA
# ============================================================
position_type_model = {}

for pos in range(9):

    chars = (
        account_values
        .str[pos]
    )

    digit_count = int(
        chars.str.isdigit().sum()
    )

    letter_count = int(
        chars.str.isalpha().sum()
    )

    total = len(chars)

    position_type_model[
        str(pos + 1)
    ] = {
        "digit_probability": float(
            digit_count / total
        ),
        "letter_probability": float(
            letter_count / total
        )
    }

# ============================================================
# 11. ACCOUNT ID STRUCTURAL DNA
# ============================================================
account_generator_config = {

    "format": {
        "length": 9,
        "regex": "^[A-Z0-9]{9}$"
    },

    "fixed_position_behavior": {
        "position_1": {
            "values": {
                str(k): int(v)
                for k, v in
                account_values
                .str[0]
                .value_counts()
                .items()
            }
        },

        "position_2": {
            "values": {
                str(k): int(v)
                for k, v in
                account_values
                .str[1]
                .value_counts()
                .items()
            }
        },

        "position_9": {
            "values": {
                str(k): int(v)
                for k, v in
                account_values
                .str[8]
                .value_counts()
                .items()
            }
        }
    },

    "position_models": position_models,

    "position_digit_letter_model":
        position_type_model,

    "bank_specific_prefix_length": 3,

    "bank_specific_prefix_models_available":
        len(prefix_sampler),

    "original_account_rows":
        int(len(accounts)),

    "original_unique_account_ids":
        int(
            account_values.nunique()
        )
}

# ============================================================
# 12. SAVE BANK POOL
# ============================================================
bank_pool.to_csv(
    OUT_BANK_POOL,
    index=False
)

# ============================================================
# 13. SAVE PREFIX SAMPLER
# ============================================================
with open(
    OUT_PREFIX_JSON,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        prefix_sampler,
        f,
        indent=2
    )

# ============================================================
# 14. SAVE ACCOUNT GENERATOR CONFIG
# ============================================================
with open(
    OUT_ACCOUNT_JSON,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        account_generator_config,
        f,
        indent=2
    )

# ============================================================
# 15. FINAL VALIDATION
# ============================================================
print("\n" + "=" * 100)
print("✅ CELL 9 COMPLETE")
print("=" * 100)

print(
    "\nFinal normalized bank pool:",
    f"{len(bank_pool):,}"
)

print(
    "Expected:",
    "30,470"
)

print(
    "Bank-name conflicts:",
    int(
        bank_pool
        .groupby(
            "normalized_bank_id"
        )["Bank Name"]
        .nunique()
        .gt(1)
        .sum()
    )
)

print(
    "Banks with account records:",
    int(
        (
            bank_pool["account_count"] > 0
        ).sum()
    )
)

print(
    "Bank prefix models:",
    len(prefix_sampler)
)

print(
    "Account ID length:",
    9
)

print(
    "Account ID regex:",
    "^[A-Z0-9]{9}$"
)

print("\nSaved:")
print(
    OUT_BANK_POOL
)
print(
    OUT_PREFIX_JSON
)
print(
    OUT_ACCOUNT_JSON
)

print("\nNO SYNTHETIC ACCOUNTS CREATED.")
print("NO SYNTHETIC TRANSACTIONS CREATED.")
print("NO ORIGINAL FILE MODIFIED.")

print("=" * 100)

====================================================================================================
CELL 9 — FINAL GENERATOR BANK POOL + ACCOUNT-ID SAMPLER
====================================================================================================

================================================================================
1. LOADING SOURCE TABLES
================================================================================
Accounts rows: 518,581
Canonical bank IDs: 30,470
Old registry rows: 60,998

================================================================================
2. COLLAPSING BANK REGISTRY
================================================================================
Collapsed normalized banks: 30470

================================================================================
3. BUILDING FINAL 30,470-BANK POOL
================================================================================
FINAL BANK POOL: 30,470 banks

================================================================================
4. BANK POOL VALIDATION
================================================================================
Expected normalized banks: 30470
Actual normalized banks: 30470
Unique canonical IDs: 30470
Banks missing Bank Name: 0
Banks missing account records: 0
Source probability sum: 0.9999999999999999
Destination probability sum: 1.0

================================================================================
5. TOP BANKS BY LEGITIMATE ACTIVITY
================================================================================

,normalized_bank_id,canonical_transaction_bank_id,Bank Name,account_count,legitimate_source_transactions,legitimate_destination_transactions,source_probability,destination_probability
30434,70,070,Oasis Thrift,15,449226,2892,0.088549,0.000568
1,10,010,National Bank of Laramie,3108,81578,42496,0.016080,0.008352
135,12,012,National Bank of the East,3161,79678,41783,0.015706,0.008212
0,1,001,Arbor Savings Bank,2172,62161,30062,0.012253,0.005909
526,15,015,Japan Bank #0,3051,52465,38679,0.010342,0.007602
846,220,00220,National Bank of Pittsburgh,2530,52395,30586,0.010328,0.006012
721,20,020,China Bank #6,1625,40941,21994,0.008070,0.004323
1406,3,003,China Bank #14,1777,38400,25614,0.007569,0.005034
30433,7,007,India Bank #25,1665,31075,23015,0.006125,0.004524
745,211,0211,UK Bank #29,1507,30425,20549,0.005997,0.004039
94,116,0116,Switzerland Bank #9,1514,30209,20224,0.005955,0.003975
19,11,011,Finland Bank #0,1013,29629,13375,0.005840,0.002629
845,22,022,Germany Bank #65,1039,28612,13914,0.005640,0.002735
1342,28,028,Australia Bank #0,1542,28558,21136,0.005629,0.004154
633,1665,01665,Savings Bank of Los Angeles,1496,28289,19520,0.005576,0.003837
959,23,023,Germany Bank #18,1023,26861,13314,0.005295,0.002617
254,1292,01292,Savings Bank of Seattle,1000,26819,14094,0.005286,0.002770
117,118,0118,Switzerland Bank #8,1218,24952,16419,0.004918,0.003227
347,1362,01362,Golden Bancorp,1033,23838,13814,0.004699,0.002715
402,14,014,China Bank #13,1104,23542,15632,0.004640,0.003072

================================================================================
6. BANK-SPECIFIC ACCOUNT PREFIX SAMPLER
================================================================================
Banks with prefix models: 30470

================================================================================
7. GLOBAL ACCOUNT-ID POSITION MODEL
================================================================================
Position 1: 2 possible characters
Position 2: 2 possible characters
Position 3: 16 possible characters
Position 4: 16 possible characters
Position 5: 16 possible characters
Position 6: 16 possible characters
Position 7: 16 possible characters
Position 8: 16 possible characters
Position 9: 3 possible characters

====================================================================================================
✅ CELL 9 COMPLETE
====================================================================================================

Final normalized bank pool: 30,470
Expected: 30,470
Bank-name conflicts: 0
Banks with account records: 30470
Bank prefix models: 30470
Account ID length: 9
Account ID regex: ^[A-Z0-9]{9}$

Saved:
/kaggle/working/AML_GNN_ONLY/data/HI-Small_final_generator_bank_pool.csv
/kaggle/working/AML_GNN_ONLY/data/HI-Small_bank_account_prefix_sampler.json
/kaggle/working/AML_GNN_ONLY/data/HI-Small_account_id_generator.json

NO SYNTHETIC ACCOUNTS CREATED.
NO SYNTHETIC TRANSACTIONS CREATED.
NO ORIGINAL FILE MODIFIED.
====================================================================================================

In [16]:
# ============================================================
# CELL 10 — ACCOUNT REUSE + ENTITY DNA
# ============================================================
#
# Purpose:
#   Learn how frequently real legitimate accounts are reused,
#   and how Entity IDs / Entity Names are structured.
#
# Reads:
#   ORIGINAL HI-Small only
#
# Creates:
#   HI-Small_account_reuse_dna.json
#   HI-Small_entity_name_dna.json
#
# NO synthetic data created.
# NO original data modified.
# ============================================================

import os
import json
import numpy as np
import pandas as pd

# ------------------------------------------------------------
# PATHS
# ------------------------------------------------------------
DATA_ROOT = "/kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml"
WORK_DIR = "/kaggle/working/AML_GNN_ONLY/data"

TRANS_PATH = os.path.join(
    DATA_ROOT,
    "HI-Small_Trans.csv"
)

ACCOUNTS_PATH = os.path.join(
    DATA_ROOT,
    "HI-Small_accounts.csv"
)

OUT_ACCOUNT_DNA = os.path.join(
    WORK_DIR,
    "HI-Small_account_reuse_dna.json"
)

OUT_ENTITY_DNA = os.path.join(
    WORK_DIR,
    "HI-Small_entity_name_dna.json"
)

print("=" * 100)
print("CELL 10 — ACCOUNT REUSE + ENTITY DNA")
print("=" * 100)

# ============================================================
# 1. LOAD ACCOUNTS TABLE
# ============================================================
accounts = pd.read_csv(
    ACCOUNTS_PATH,
    dtype=str
)

required = [
    "Bank ID",
    "Account Number",
    "Entity ID",
    "Entity Name"
]

missing = [
    c for c in required
    if c not in accounts.columns
]

if missing:
    raise RuntimeError(
        f"Missing columns: {missing}"
    )

# ------------------------------------------------------------
# Normalize IDs
# ------------------------------------------------------------
def normalize_bank_id(x):

    x = str(x).strip()

    if x == "":
        return None

    try:
        return str(int(x))
    except Exception:
        return x.lstrip("0") or "0"


accounts[
    "normalized_bank_id"
] = (
    accounts["Bank ID"]
    .map(normalize_bank_id)
)

accounts[
    "Account Number"
] = (
    accounts["Account Number"]
    .astype(str)
)

# ============================================================
# 2. ACCOUNT TABLE STRUCTURE
# ============================================================
print("\n" + "=" * 80)
print("1. ACCOUNT TABLE STRUCTURE")
print("=" * 80)

account_rows = len(accounts)

unique_accounts = (
    accounts["Account Number"]
    .nunique()
)

unique_account_bank_pairs = (
    accounts[
        [
            "normalized_bank_id",
            "Account Number"
        ]
    ]
    .drop_duplicates()
    .shape[0]
)

print(
    "Account rows:",
    f"{account_rows:,}"
)

print(
    "Unique account numbers:",
    f"{unique_accounts:,}"
)

print(
    "Unique bank-account pairs:",
    f"{unique_account_bank_pairs:,}"
)

print(
    "Duplicate account-table rows:",
    f"{account_rows - unique_account_bank_pairs:,}"
)

# ============================================================
# 3. ENTITY ACCOUNT/BANK REUSE
# ============================================================
print("\n" + "=" * 80)
print("2. ENTITY REUSE")
print("=" * 80)

entity_account_count = (
    accounts
    .groupby("Entity ID")
    .size()
)

entity_bank_count = (
    accounts
    .groupby("Entity ID")[
        "normalized_bank_id"
    ]
    .nunique()
)

print(
    "Entities:",
    f"{accounts['Entity ID'].nunique():,}"
)

print(
    "Median accounts/entity:",
    entity_account_count.median()
)

print(
    "Mean accounts/entity:",
    entity_account_count.mean()
)

print(
    "P90 accounts/entity:",
    entity_account_count.quantile(0.90)
)

print(
    "P95 accounts/entity:",
    entity_account_count.quantile(0.95)
)

print(
    "P99 accounts/entity:",
    entity_account_count.quantile(0.99)
)

print(
    "Max accounts/entity:",
    entity_account_count.max()
)

print(
    "Median banks/entity:",
    entity_bank_count.median()
)

print(
    "Mean banks/entity:",
    entity_bank_count.mean()
)

print(
    "Entities with >=2 banks:",
    int(
        (entity_bank_count >= 2).sum()
    )
)

# ============================================================
# 4. SCAN LEGITIMATE TRANSACTIONS
# ============================================================
print("\n" + "=" * 80)
print("3. ACCOUNT TRANSACTION REUSE")
print("=" * 80)

# We count source and destination activity separately.
#
# Key:
#   account number
#
# This is sufficient for the activity-distribution DNA.
# Bank-account uniqueness is handled by the generator.
# ------------------------------------------------------------

source_counts = {}
destination_counts = {}

legit_source_counts = {}
legit_destination_counts = {}

chunk_size = 500_000
rows_seen = 0
chunk_no = 0

for chunk in pd.read_csv(
    TRANS_PATH,
    usecols=[
        "Account",
        "Account.1",
        "Is Laundering"
    ],
    chunksize=chunk_size,
    dtype=str
):

    chunk_no += 1
    rows_seen += len(chunk)

    labels = pd.to_numeric(
        chunk["Is Laundering"],
        errors="coerce"
    ).fillna(0).astype(int)

    # --------------------------------------------------------
    # All source activity
    # --------------------------------------------------------
    src = (
        chunk["Account"]
        .astype(str)
        .value_counts()
    )

    for account, count in src.items():

        source_counts[account] = (
            source_counts.get(
                account,
                0
            )
            +
            int(count)
        )

    # --------------------------------------------------------
    # All destination activity
    # --------------------------------------------------------
    dst = (
        chunk["Account.1"]
        .astype(str)
        .value_counts()
    )

    for account, count in dst.items():

        destination_counts[account] = (
            destination_counts.get(
                account,
                0
            )
            +
            int(count)
        )

    # --------------------------------------------------------
    # Legitimate only
    # --------------------------------------------------------
    legit = chunk[
        labels == 0
    ]

    legit_src = (
        legit["Account"]
        .astype(str)
        .value_counts()
    )

    for account, count in legit_src.items():

        legit_source_counts[account] = (
            legit_source_counts.get(
                account,
                0
            )
            +
            int(count)
        )

    legit_dst = (
        legit["Account.1"]
        .astype(str)
        .value_counts()
    )

    for account, count in legit_dst.items():

        legit_destination_counts[account] = (
            legit_destination_counts.get(
                account,
                0
            )
            +
            int(count)
        )

    print(
        f"  Chunk {chunk_no} "
        f"| rows processed = {rows_seen:,}"
    )

print(
    "\nRows scanned:",
    f"{rows_seen:,}"
)

# ============================================================
# 5. ACCOUNT ACTIVITY DISTRIBUTIONS
# ============================================================
def activity_summary(
    counts_dict
):

    s = pd.Series(
        counts_dict,
        dtype="int64"
    )

    if len(s) == 0:
        return {}

    return {
        "accounts": int(len(s)),
        "min": int(s.min()),
        "median": float(s.median()),
        "mean": float(s.mean()),
        "p75": float(s.quantile(0.75)),
        "p90": float(s.quantile(0.90)),
        "p95": float(s.quantile(0.95)),
        "p99": float(s.quantile(0.99)),
        "max": int(s.max())
    }


source_all_summary = activity_summary(
    source_counts
)

destination_all_summary = activity_summary(
    destination_counts
)

source_legit_summary = activity_summary(
    legit_source_counts
)

destination_legit_summary = activity_summary(
    legit_destination_counts
)

print("\n" + "=" * 80)
print("4. ACTIVITY SUMMARY")
print("=" * 80)

print("\nAll source accounts:")
print(source_all_summary)

print("\nAll destination accounts:")
print(destination_all_summary)

print("\nLegitimate source accounts:")
print(source_legit_summary)

print("\nLegitimate destination accounts:")
print(destination_legit_summary)

# ============================================================
# 6. LEGITIMATE ACTIVITY BUCKETS
# ============================================================
def make_activity_buckets(
    counts_dict
):

    s = pd.Series(
        counts_dict,
        dtype="int64"
    )

    buckets = pd.cut(
        s,
        bins=[
            0,
            1,
            2,
            5,
            10,
            25,
            50,
            100,
            250,
            500,
            1000,
            np.inf
        ],
        labels=[
            "1",
            "2",
            "3-5",
            "6-10",
            "11-25",
            "26-50",
            "51-100",
            "101-250",
            "251-500",
            "501-1000",
            ">1000"
        ]
    )

    counts = (
        buckets
        .value_counts(
            sort=False
        )
    )

    total = counts.sum()

    return {
        str(bucket): {
            "count": int(count),
            "share_pct": float(
                count / total * 100
            )
        }
        for bucket, count
        in counts.items()
    }

legit_source_buckets = make_activity_buckets(
    legit_source_counts
)

legit_destination_buckets = make_activity_buckets(
    legit_destination_counts
)

print("\n" + "=" * 80)
print("5. LEGITIMATE ACCOUNT ACTIVITY BUCKETS")
print("=" * 80)

print("\nSource:")
for k, v in legit_source_buckets.items():
    print(
        f"{k:10s}"
        f"{v['count']:10,d}"
        f"{v['share_pct']:10.4f}%"
    )

print("\nDestination:")
for k, v in legit_destination_buckets.items():
    print(
        f"{k:10s}"
        f"{v['count']:10,d}"
        f"{v['share_pct']:10.4f}%"
    )

# ============================================================
# 7. ENTITY ID DNA
# ============================================================
print("\n" + "=" * 80)
print("6. ENTITY ID DNA")
print("=" * 80)

entity_ids = (
    accounts["Entity ID"]
    .astype(str)
)

entity_id_lengths = (
    entity_ids
    .str.len()
    .value_counts()
    .sort_index()
)

entity_id_position_models = {}

for pos in range(
    int(entity_ids.str.len().max())
):

    vc = (
        entity_ids
        .str[pos]
        .value_counts()
    )

    total = vc.sum()

    entity_id_position_models[
        str(pos + 1)
    ] = {
        str(char): {
            "count": int(count),
            "probability": float(
                count / total
            )
        }
        for char, count
        in vc.items()
    }

print(
    "Entity ID lengths:"
)

print(
    entity_id_lengths.to_string()
)

# ============================================================
# 8. ENTITY NAME DNA
# ============================================================
print("\n" + "=" * 80)
print("7. ENTITY NAME DNA")
print("=" * 80)

entity_names = (
    accounts["Entity Name"]
    .astype(str)
)

name_lengths = (
    entity_names
    .str.len()
    .describe(
        percentiles=[
            0.01,
            0.05,
            0.25,
            0.50,
            0.75,
            0.90,
            0.95,
            0.99
        ]
    )
)

print(
    name_lengths.to_string()
)

# Character composition
name_digit_pct = (
    entity_names
    .str.contains(
        r"\d",
        regex=True
    )
    .mean()
    * 100
)

name_letter_pct = (
    entity_names
    .str.contains(
        r"[A-Za-z]",
        regex=True
    )
    .mean()
    * 100
)

name_space_pct = (
    entity_names
    .str.contains(
        r"\s",
        regex=True
    )
    .mean()
    * 100
)

print(
    "\nNames containing digits:",
    f"{name_digit_pct:.4f}%"
)

print(
    "Names containing letters:",
    f"{name_letter_pct:.4f}%"
)

print(
    "Names containing spaces:",
    f"{name_space_pct:.4f}%"
)

print("\nExample Entity IDs:")

for x in (
    entity_ids
    .drop_duplicates()
    .head(30)
):
    print(x)

print("\nExample Entity Names:")

for x in (
    entity_names
    .drop_duplicates()
    .head(30)
):
    print(x)

# ============================================================
# 9. ENTITY NAME TOP PATTERNS
# ============================================================
#
# We inspect whether names follow simple templates such as:
#   Entity 123
#   Company 45
#   Individual 987
# etc.
#
# No names are copied into the generator yet.
# ============================================================

name_prefixes = (
    entity_names
    .str.extract(
        r"^([A-Za-z]+)",
        expand=False
    )
    .value_counts()
    .head(30)
)

print(
    "\nTop alphabetic name prefixes:"
)

print(
    name_prefixes.to_string()
)

# ============================================================
# 10. SAVE ACCOUNT REUSE DNA
# ============================================================
account_reuse_dna = {

    "source_activity_all":
        source_all_summary,

    "destination_activity_all":
        destination_all_summary,

    "source_activity_legitimate":
        source_legit_summary,

    "destination_activity_legitimate":
        destination_legit_summary,

    "legitimate_source_activity_buckets":
        legit_source_buckets,

    "legitimate_destination_activity_buckets":
        legit_destination_buckets,

    "unique_source_accounts":
        int(len(source_counts)),

    "unique_destination_accounts":
        int(len(destination_counts)),

    "unique_legitimate_source_accounts":
        int(len(legit_source_counts)),

    "unique_legitimate_destination_accounts":
        int(len(legit_destination_counts))
}

with open(
    OUT_ACCOUNT_DNA,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        account_reuse_dna,
        f,
        indent=2
    )

# ============================================================
# 11. SAVE ENTITY DNA
# ============================================================
entity_name_dna = {

    "unique_entity_ids":
        int(entity_ids.nunique()),

    "unique_entity_names":
        int(entity_names.nunique()),

    "entity_id_length_distribution": {
        str(k): int(v)
        for k, v in
        entity_id_lengths.items()
    },

    "entity_id_position_models":
        entity_id_position_models,

    "entity_account_summary": {
        "min": int(entity_account_count.min()),
        "median": float(entity_account_count.median()),
        "mean": float(entity_account_count.mean()),
        "p90": float(entity_account_count.quantile(0.90)),
        "p95": float(entity_account_count.quantile(0.95)),
        "p99": float(entity_account_count.quantile(0.99)),
        "max": int(entity_account_count.max())
    },

    "entity_bank_summary": {
        "min": int(entity_bank_count.min()),
        "median": float(entity_bank_count.median()),
        "mean": float(entity_bank_count.mean()),
        "p90": float(entity_bank_count.quantile(0.90)),
        "p95": float(entity_bank_count.quantile(0.95)),
        "p99": float(entity_bank_count.quantile(0.99)),
        "max": int(entity_bank_count.max())
    },

    "entity_name_length_summary": {
        str(k): float(v)
        for k, v in name_lengths.items()
    },

    "names_with_digits_pct":
        float(name_digit_pct),

    "names_with_letters_pct":
        float(name_letter_pct),

    "names_with_spaces_pct":
        float(name_space_pct),

    "top_name_prefixes": {
        str(k): int(v)
        for k, v in name_prefixes.items()
    }
}

with open(
    OUT_ENTITY_DNA,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        entity_name_dna,
        f,
        indent=2
    )

# ============================================================
# 12. FINAL
# ============================================================
print("\n" + "=" * 100)
print("✅ CELL 10 COMPLETE")
print("=" * 100)

print(
    "Account reuse DNA:",
    OUT_ACCOUNT_DNA
)

print(
    "Entity DNA:",
    OUT_ENTITY_DNA
)

print("\nNO SYNTHETIC ACCOUNTS CREATED.")
print("NO SYNTHETIC TRANSACTIONS CREATED.")
print("NO ORIGINAL FILE MODIFIED.")

print("=" * 100)

====================================================================================================
CELL 10 — ACCOUNT REUSE + ENTITY DNA
====================================================================================================

================================================================================
1. ACCOUNT TABLE STRUCTURE
================================================================================
Account rows: 518,581
Unique account numbers: 518,573
Unique bank-account pairs: 518,581
Duplicate account-table rows: 0

================================================================================
2. ENTITY REUSE
================================================================================
Entities: 166,207
Median accounts/entity: 1.0
Mean accounts/entity: 3.1200912115614865
P90 accounts/entity: 6.0
P95 accounts/entity: 7.0
P99 accounts/entity: 14.0
Max accounts/entity: 7820
Median banks/entity: 1.0
Mean banks/entity: 2.6658624486333307
Entities with >=2 banks: 63362

================================================================================
3. ACCOUNT TRANSACTION REUSE
================================================================================
  Chunk 1 | rows processed = 500,000
  Chunk 2 | rows processed = 1,000,000
  Chunk 3 | rows processed = 1,500,000
  Chunk 4 | rows processed = 2,000,000
  Chunk 5 | rows processed = 2,500,000
  Chunk 6 | rows processed = 3,000,000
  Chunk 7 | rows processed = 3,500,000
  Chunk 8 | rows processed = 4,000,000
  Chunk 9 | rows processed = 4,500,000
  Chunk 10 | rows processed = 5,000,000
  Chunk 11 | rows processed = 5,078,345

Rows scanned: 5,078,345

================================================================================
4. ACTIVITY SUMMARY
================================================================================

All source accounts:
{'accounts': 496995, 'min': 1, 'median': 2.0, 'mean': 10.218100785722191, 'p75': 5.0, 'p90': 29.0, 'p95': 46.0, 'p99': 92.0, 'max': 168672}

All destination accounts:
{'accounts': 420636, 'min': 1, 'median': 4.0, 'mean': 12.073015623959908, 'p75': 22.0, 'p90': 31.0, 'p95': 37.0, 'p99': 51.0, 'max': 1084}

Legitimate source accounts:
{'accounts': 496871, 'min': 1, 'median': 2.0, 'mean': 10.210231629537647, 'p75': 5.0, 'p90': 29.0, 'p95': 46.0, 'p99': 92.0, 'max': 168429}

Legitimate destination accounts:
{'accounts': 420585, 'min': 1, 'median': 4.0, 'mean': 12.062170548165057, 'p75': 22.0, 'p90': 31.0, 'p95': 37.0, 'p99': 51.0, 'max': 1084}

================================================================================
5. LEGITIMATE ACCOUNT ACTIVITY BUCKETS
================================================================================

Source:
1            153,138   30.8205%
2            158,432   31.8859%
3-5           63,278   12.7353%
6-10          18,959    3.8157%
11-25         48,147    9.6900%
26-50         33,378    6.7176%
51-100        17,799    3.5822%
101-250        3,709    0.7465%
251-500           16    0.0032%
501-1000           0    0.0000%
>1000             15    0.0030%

Destination:
1            113,804   27.0585%
2             53,481   12.7159%
3-5           57,272   13.6172%
6-10          21,240    5.0501%
11-25        105,544   25.0946%
26-50         64,655   15.3726%
51-100         4,575    1.0878%
101-250           12    0.0029%
251-500            0    0.0000%
501-1000           1    0.0002%
>1000              1    0.0002%

================================================================================
6. ENTITY ID DNA
================================================================================
Entity ID lengths:
Entity ID
9    518581

================================================================================
7. ENTITY NAME DNA
================================================================================
count    518581.000000
mean         19.962604
std           3.799087
min           9.000000
1%           10.000000
5%           17.000000
25%          18.000000
50%          18.000000
75%          25.000000
90%          26.000000
95%          26.000000
99%          26.000000
max          26.000000

Names containing digits: 100.0000%
Names containing letters: 100.0000%
Names containing spaces: 100.0000%

Example Entity IDs:
80062E240
800C998A0
800C47F50
80096F0B0
800FB8760
80064EB20
800CCEDE0
800D88F10
800D3F760
800B44480
800CE6560
800786C50
8004D60F0
8001B6C60
8001727E0
800A9E740
800720A50
800F0B030
800FBB640
800E84E60
800B49C40
8006D77B0
800DEADE0
8005EC710
80019D860
8000E7320
80094F4F0
800EC1E80
800B3A830
800ABA660

Example Entity Names:
Sole Proprietorship #50438
Corporation #33520
Partnership #35397
Corporation #48813
Corporation #889
Sole Proprietorship #42987
Sole Proprietorship #20855
Partnership #36822
Partnership #36511
Partnership #33830
Partnership #4394
Sole Proprietorship #24627
Sole Proprietorship #17045
Partnership #51470
Sole Proprietorship #4568
Partnership #32508
Corporation #40316
Partnership #15275
Partnership #10650
Corporation #35871
Sole Proprietorship #32941
Sole Proprietorship #23649
Partnership #7246
Partnership #46146
Sole Proprietorship #15491
Partnership #1137
Corporation #26264
Sole Proprietorship #45573
Corporation #31439
Partnership #32618

Top alphabetic name prefixes:
Entity Name
Partnership    189683
Corporation    172351
Sole           149048
Country          6692
Individual        740
Direct             67

====================================================================================================
✅ CELL 10 COMPLETE
====================================================================================================
Account reuse DNA: /kaggle/working/AML_GNN_ONLY/data/HI-Small_account_reuse_dna.json
Entity DNA: /kaggle/working/AML_GNN_ONLY/data/HI-Small_entity_name_dna.json

NO SYNTHETIC ACCOUNTS CREATED.
NO SYNTHETIC TRANSACTIONS CREATED.
NO ORIGINAL FILE MODIFIED.
====================================================================================================

In [17]:
# ============================================================
# CELL 11 — GENERATOR ACCOUNT REGISTRY
# ============================================================
#
# Purpose:
#   Build a generator-ready account registry from ORIGINAL
#   HI-Small only.
#
# This is important because the final synthetic dataset should
# NOT contain millions of one-use synthetic accounts.
#
# We will preferentially REUSE realistic original accounts
# when constructing laundering patterns.
#
# Creates:
#   HI-Small_generator_account_registry.csv
#   HI-Small_generator_account_registry_summary.json
#
# NO synthetic accounts
# NO synthetic transactions
# NO original files modified
# ============================================================

import os
import json
import numpy as np
import pandas as pd

# ------------------------------------------------------------
# PATHS
# ------------------------------------------------------------
DATA_ROOT = "/kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml"
WORK_DIR = "/kaggle/working/AML_GNN_ONLY/data"

ACCOUNTS_PATH = os.path.join(
    DATA_ROOT,
    "HI-Small_accounts.csv"
)

TRANS_PATH = os.path.join(
    DATA_ROOT,
    "HI-Small_Trans.csv"
)

OUT_REGISTRY = os.path.join(
    WORK_DIR,
    "HI-Small_generator_account_registry.csv"
)

OUT_SUMMARY = os.path.join(
    WORK_DIR,
    "HI-Small_generator_account_registry_summary.json"
)

print("=" * 100)
print("CELL 11 — GENERATOR ACCOUNT REGISTRY")
print("=" * 100)

# ============================================================
# 1. LOAD ACCOUNTS TABLE
# ============================================================
print("\n" + "=" * 80)
print("1. LOADING ORIGINAL ACCOUNT TABLE")
print("=" * 80)

accounts = pd.read_csv(
    ACCOUNTS_PATH,
    dtype=str
)

# ------------------------------------------------------------
# Normalize bank IDs
# ------------------------------------------------------------
def normalize_bank_id(x):

    x = str(x).strip()

    if x == "":
        return None

    try:
        return str(int(x))
    except Exception:
        return x.lstrip("0") or "0"


accounts["normalized_bank_id"] = (
    accounts["Bank ID"]
    .map(normalize_bank_id)
)

accounts["Account Number"] = (
    accounts["Account Number"]
    .astype(str)
)

accounts["Entity ID"] = (
    accounts["Entity ID"]
    .astype(str)
)

accounts["Entity Name"] = (
    accounts["Entity Name"]
    .astype(str)
)

# ============================================================
# 2. REMOVE EXACT ACCOUNT-TABLE DUPLICATES
# ============================================================
#
# There are duplicate ACCOUNT NUMBER VALUES in the original
# data, but they are not necessarily duplicate rows.
#
# We retain unique bank-account combinations.
# ============================================================

registry = (
    accounts[
        [
            "normalized_bank_id",
            "Bank ID",
            "Bank Name",
            "Account Number",
            "Entity ID",
            "Entity Name"
        ]
    ]
    .drop_duplicates(
        [
            "normalized_bank_id",
            "Account Number"
        ]
    )
    .copy()
)

print(
    "Original account rows:",
    f"{len(accounts):,}"
)

print(
    "Unique bank-account registry rows:",
    f"{len(registry):,}"
)

# ============================================================
# 3. SCAN ORIGINAL TRANSACTIONS FOR ACCOUNT ACTIVITY
# ============================================================
print("\n" + "=" * 80)
print("2. SCANNING ORIGINAL TRANSACTION ACTIVITY")
print("=" * 80)

src_counts = {}
dst_counts = {}

legit_src_counts = {}
legit_dst_counts = {}

laund_src_counts = {}
laund_dst_counts = {}

chunk_size = 500_000
rows_seen = 0
chunk_no = 0

for chunk in pd.read_csv(
    TRANS_PATH,
    usecols=[
        "Account",
        "Account.1",
        "Is Laundering"
    ],
    dtype=str,
    chunksize=chunk_size
):

    chunk_no += 1
    rows_seen += len(chunk)

    labels = (
        pd.to_numeric(
            chunk["Is Laundering"],
            errors="coerce"
        )
        .fillna(0)
        .astype(int)
    )

    # --------------------------------------------------------
    # All source
    # --------------------------------------------------------
    src = (
        chunk["Account"]
        .astype(str)
        .value_counts()
    )

    for account, count in src.items():

        src_counts[account] = (
            src_counts.get(
                account,
                0
            )
            +
            int(count)
        )

    # --------------------------------------------------------
    # All destination
    # --------------------------------------------------------
    dst = (
        chunk["Account.1"]
        .astype(str)
        .value_counts()
    )

    for account, count in dst.items():

        dst_counts[account] = (
            dst_counts.get(
                account,
                0
            )
            +
            int(count)
        )

    # --------------------------------------------------------
    # Legitimate
    # --------------------------------------------------------
    legit = chunk[
        labels == 0
    ]

    legit_src = (
        legit["Account"]
        .astype(str)
        .value_counts()
    )

    for account, count in legit_src.items():

        legit_src_counts[account] = (
            legit_src_counts.get(
                account,
                0
            )
            +
            int(count)
        )

    legit_dst = (
        legit["Account.1"]
        .astype(str)
        .value_counts()
    )

    for account, count in legit_dst.items():

        legit_dst_counts[account] = (
            legit_dst_counts.get(
                account,
                0
            )
            +
            int(count)
        )

    # --------------------------------------------------------
    # Original laundering
    # --------------------------------------------------------
    laund = chunk[
        labels == 1
    ]

    laund_src = (
        laund["Account"]
        .astype(str)
        .value_counts()
    )

    for account, count in laund_src.items():

        laund_src_counts[account] = (
            laund_src_counts.get(
                account,
                0
            )
            +
            int(count)
        )

    laund_dst = (
        laund["Account.1"]
        .astype(str)
        .value_counts()
    )

    for account, count in laund_dst.items():

        laund_dst_counts[account] = (
            laund_dst_counts.get(
                account,
                0
            )
            +
            int(count)
        )

    print(
        f"  Chunk {chunk_no} "
        f"| rows processed = {rows_seen:,}"
    )

print(
    "\nRows scanned:",
    f"{rows_seen:,}"
)

# ============================================================
# 4. ADD ACTIVITY FEATURES
# ============================================================

registry["source_tx_count"] = (
    registry["Account Number"]
    .map(src_counts)
    .fillna(0)
    .astype(int)
)

registry["destination_tx_count"] = (
    registry["Account Number"]
    .map(dst_counts)
    .fillna(0)
    .astype(int)
)

registry["legitimate_source_tx_count"] = (
    registry["Account Number"]
    .map(legit_src_counts)
    .fillna(0)
    .astype(int)
)

registry["legitimate_destination_tx_count"] = (
    registry["Account Number"]
    .map(legit_dst_counts)
    .fillna(0)
    .astype(int)
)

registry["original_laundering_source_count"] = (
    registry["Account Number"]
    .map(laund_src_counts)
    .fillna(0)
    .astype(int)
)

registry["original_laundering_destination_count"] = (
    registry["Account Number"]
    .map(laund_dst_counts)
    .fillna(0)
    .astype(int)
)

# ============================================================
# 5. ACCOUNT ROLE CLASSIFICATION
# ============================================================
#
# These are generator convenience flags, NOT labels.
#
# source_only
# destination_only
# both
# inactive
# ============================================================

registry["role"] = np.select(
    [
        (
            (registry["legitimate_source_tx_count"] > 0)
            &
            (registry["legitimate_destination_tx_count"] > 0)
        ),

        (
            (registry["legitimate_source_tx_count"] > 0)
            &
            (registry["legitimate_destination_tx_count"] == 0)
        ),

        (
            (registry["legitimate_source_tx_count"] == 0)
            &
            (registry["legitimate_destination_tx_count"] > 0)
        )
    ],
    [
        "both",
        "source_only",
        "destination_only"
    ],
    default="inactive"
)

# ============================================================
# 6. LEGITIMATE ACCOUNT ELIGIBILITY
# ============================================================
#
# Accounts that never appeared in an original laundering
# transaction are our cleanest candidate pool.
#
# This avoids inheriting original laundering labels into
# newly synthesized episodes.
# ============================================================

registry["originally_clean"] = (
    (
        registry[
            "original_laundering_source_count"
        ] == 0
    )
    &
    (
        registry[
            "original_laundering_destination_count"
        ] == 0
    )
)

# Accounts with legitimate activity
registry["has_legitimate_activity"] = (
    (
        registry[
            "legitimate_source_tx_count"
        ]
        +
        registry[
            "legitimate_destination_tx_count"
        ]
    ) > 0
)

# Primary generator pool
registry["generator_eligible"] = (
    registry["originally_clean"]
    &
    registry["has_legitimate_activity"]
)

# ============================================================
# 7. ACCOUNT ACTIVITY TOTAL
# ============================================================
registry["legitimate_total_activity"] = (
    registry[
        "legitimate_source_tx_count"
    ]
    +
    registry[
        "legitimate_destination_tx_count"
    ]
)

# ============================================================
# 8. ACTIVITY BUCKET
# ============================================================
bins = [
    0,
    1,
    2,
    5,
    10,
    25,
    50,
    100,
    250,
    500,
    1000,
    np.inf
]

labels = [
    "1",
    "2",
    "3-5",
    "6-10",
    "11-25",
    "26-50",
    "51-100",
    "101-250",
    "251-500",
    "501-1000",
    ">1000"
]

registry["legitimate_activity_bucket"] = (
    pd.cut(
        registry[
            "legitimate_total_activity"
        ].clip(lower=1),
        bins=bins,
        labels=labels,
        include_lowest=True
    )
    .astype(str)
)

# ============================================================
# 9. ACCOUNT ROLE COUNTS
# ============================================================
print("\n" + "=" * 80)
print("3. ACCOUNT ROLE DISTRIBUTION")
print("=" * 80)

print(
    registry["role"]
    .value_counts()
    .to_string()
)

print("\nGenerator eligible accounts:")
print(
    int(
        registry[
            "generator_eligible"
        ].sum()
    )
)

print("\nOriginally clean accounts:")
print(
    int(
        registry[
            "originally_clean"
        ].sum()
    )
)

# ============================================================
# 10. ACTIVITY DISTRIBUTION
# ============================================================
print("\n" + "=" * 80)
print("4. GENERATOR-ELIGIBLE ACTIVITY DISTRIBUTION")
print("=" * 80)

eligible = registry[
    registry["generator_eligible"]
].copy()

activity = (
    eligible[
        "legitimate_total_activity"
    ]
)

print(
    "Eligible accounts:",
    f"{len(eligible):,}"
)

print(
    "Min:",
    activity.min()
)

print(
    "Median:",
    activity.median()
)

print(
    "Mean:",
    activity.mean()
)

print(
    "P75:",
    activity.quantile(0.75)
)

print(
    "P90:",
    activity.quantile(0.90)
)

print(
    "P95:",
    activity.quantile(0.95)
)

print(
    "P99:",
    activity.quantile(0.99)
)

print(
    "Max:",
    activity.max()
)

# ============================================================
# 11. ROLE × ACTIVITY DISTRIBUTION
# ============================================================
print("\n" + "=" * 80)
print("5. ROLE × ACTIVITY BUCKET")
print("=" * 80)

role_activity = pd.crosstab(
    eligible["role"],
    eligible[
        "legitimate_activity_bucket"
    ],
    normalize="index"
) * 100

print(
    role_activity.round(4).to_string()
)

# ============================================================
# 12. BANK-LEVEL ACCOUNT POOL SIZE
# ============================================================
print("\n" + "=" * 80)
print("6. BANK × ELIGIBLE ACCOUNT COUNTS")
print("=" * 80)

eligible_per_bank = (
    eligible
    .groupby(
        "normalized_bank_id"
    )
    .size()
    .rename(
        "eligible_account_count"
    )
)

print(
    "Banks with eligible accounts:",
    len(eligible_per_bank)
)

print(
    "Median eligible accounts/bank:",
    eligible_per_bank.median()
)

print(
    "Mean eligible accounts/bank:",
    eligible_per_bank.mean()
)

print(
    "P90:",
    eligible_per_bank.quantile(0.90)
)

print(
    "P95:",
    eligible_per_bank.quantile(0.95)
)

print(
    "P99:",
    eligible_per_bank.quantile(0.99)
)

print(
    "Max:",
    eligible_per_bank.max()
)

# ============================================================
# 13. ENTITY STRUCTURE IN ELIGIBLE POOL
# ============================================================
print("\n" + "=" * 80)
print("7. ENTITY STRUCTURE")
print("=" * 80)

eligible_entity_account_counts = (
    eligible
    .groupby("Entity ID")
    .size()
)

eligible_entity_bank_counts = (
    eligible
    .groupby("Entity ID")[
        "normalized_bank_id"
    ]
    .nunique()
)

print(
    "Eligible entities:",
    f"{len(eligible_entity_account_counts):,}"
)

print(
    "Median eligible accounts/entity:",
    eligible_entity_account_counts.median()
)

print(
    "Mean eligible accounts/entity:",
    eligible_entity_account_counts.mean()
)

print(
    "P90:",
    eligible_entity_account_counts.quantile(0.90)
)

print(
    "P95:",
    eligible_entity_account_counts.quantile(0.95)
)

print(
    "P99:",
    eligible_entity_account_counts.quantile(0.99)
)

print(
    "Max:",
    eligible_entity_account_counts.max()
)

print(
    "Eligible entities with >=2 banks:",
    int(
        (
            eligible_entity_bank_counts >= 2
        ).sum()
    )
)

# ============================================================
# 14. SAVE REGISTRY
# ============================================================
registry = registry.sort_values(
    [
        "normalized_bank_id",
        "legitimate_total_activity",
        "Account Number"
    ],
    ascending=[
        True,
        False,
        True
    ]
).reset_index(drop=True)

registry.to_csv(
    OUT_REGISTRY,
    index=False
)

# ============================================================
# 15. SAVE SUMMARY JSON
# ============================================================
summary = {

    "original_account_rows":
        int(len(accounts)),

    "unique_bank_account_rows":
        int(len(registry)),

    "generator_eligible_accounts":
        int(
            registry[
                "generator_eligible"
            ].sum()
        ),

    "originally_clean_accounts":
        int(
            registry[
                "originally_clean"
            ].sum()
        ),

    "accounts_with_legitimate_activity":
        int(
            registry[
                "has_legitimate_activity"
            ].sum()
        ),

    "role_distribution":
        {
            str(k): int(v)
            for k, v in registry[
                "role"
            ].value_counts().items()
        },

    "eligible_activity_summary": {
        "min": int(activity.min()),
        "median": float(activity.median()),
        "mean": float(activity.mean()),
        "p75": float(activity.quantile(0.75)),
        "p90": float(activity.quantile(0.90)),
        "p95": float(activity.quantile(0.95)),
        "p99": float(activity.quantile(0.99)),
        "max": int(activity.max())
    },

    "eligible_entities":
        int(
            len(
                eligible_entity_account_counts
            )
        ),

    "eligible_entities_multiple_banks":
        int(
            (
                eligible_entity_bank_counts >= 2
            ).sum()
        ),

    "banks_with_eligible_accounts":
        int(
            len(eligible_per_bank)
        )
}

with open(
    OUT_SUMMARY,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        summary,
        f,
        indent=2
    )

# ============================================================
# 16. FINAL VALIDATION
# ============================================================
print("\n" + "=" * 100)
print("✅ CELL 11 COMPLETE")
print("=" * 100)

print(
    "Generator account registry:",
    OUT_REGISTRY
)

print(
    "Registry summary:",
    OUT_SUMMARY
)

print(
    "\nTotal registry rows:",
    f"{len(registry):,}"
)

print(
    "Generator-eligible:",
    f"{int(registry['generator_eligible'].sum()):,}"
)

print(
    "Originally clean:",
    f"{int(registry['originally_clean'].sum()):,}"
)

print("\nNO SYNTHETIC ACCOUNTS CREATED.")
print("NO SYNTHETIC TRANSACTIONS CREATED.")
print("NO ORIGINAL FILE MODIFIED.")

print("=" * 100)

====================================================================================================
CELL 11 — GENERATOR ACCOUNT REGISTRY
====================================================================================================

================================================================================
1. LOADING ORIGINAL ACCOUNT TABLE
================================================================================
Original account rows: 518,581
Unique bank-account registry rows: 518,581

================================================================================
2. SCANNING ORIGINAL TRANSACTION ACTIVITY
================================================================================
  Chunk 1 | rows processed = 500,000
  Chunk 2 | rows processed = 1,000,000
  Chunk 3 | rows processed = 1,500,000
  Chunk 4 | rows processed = 2,000,000
  Chunk 5 | rows processed = 2,500,000
  Chunk 6 | rows processed = 3,000,000
  Chunk 7 | rows processed = 3,500,000
  Chunk 8 | rows processed = 4,000,000
  Chunk 9 | rows processed = 4,500,000
  Chunk 10 | rows processed = 5,000,000
  Chunk 11 | rows processed = 5,078,345

Rows scanned: 5,078,345

================================================================================
3. ACCOUNT ROLE DISTRIBUTION
================================================================================
role
both                402449
source_only          94430
destination_only     18140
inactive              3562

Generator eligible accounts:
508731

Originally clean accounts:
512224

================================================================================
4. GENERATOR-ELIGIBLE ACTIVITY DISTRIBUTION
================================================================================
Eligible accounts: 508,731
Min: 1
Median: 6.0
Mean: 18.68091781314683
P75: 27.0
P90: 51.0
P95: 70.0
P99: 118.0
Max: 394

================================================================================
5. ROLE × ACTIVITY BUCKET
================================================================================
legitimate_activity_bucket        1  101-250    11-25        2  251-500    26-50      3-5   51-100     6-10
role
both                         0.0000   2.2727  17.9637  18.6606   0.0149  20.1214  19.5884  10.5692  10.8091
destination_only             8.1227   0.0000  37.9247  15.9833   0.0000  18.2315  10.1255   1.1046   8.5077
source_only                 16.9030   0.0180   1.0290  69.7738   0.0000   0.4557  11.0383   0.1261   0.6560

================================================================================
6. BANK × ELIGIBLE ACCOUNT COUNTS
================================================================================
Banks with eligible accounts: 30469
Median eligible accounts/bank: 4.0
Mean eligible accounts/bank: 16.696675309330796
P90: 13.0
P95: 30.0
P99: 365.3199999999997
Max: 3061

================================================================================
7. ENTITY STRUCTURE
================================================================================
Eligible entities: 164,120
Median eligible accounts/entity: 1.0
Mean eligible accounts/entity: 3.0997501827930782
P90: 6.0
P95: 7.0
P99: 14.0
Max: 7771
Eligible entities with >=2 banks: 62655

====================================================================================================
✅ CELL 11 COMPLETE
====================================================================================================
Generator account registry: /kaggle/working/AML_GNN_ONLY/data/HI-Small_generator_account_registry.csv
Registry summary: /kaggle/working/AML_GNN_ONLY/data/HI-Small_generator_account_registry_summary.json

Total registry rows: 518,581
Generator-eligible: 508,731
Originally clean: 512,224

NO SYNTHETIC ACCOUNTS CREATED.
NO SYNTHETIC TRANSACTIONS CREATED.
NO ORIGINAL FILE MODIFIED.
====================================================================================================

In [18]:
# ============================================================
# CELL 12 — EXACT SYNTHETIC PATTERN ALLOCATION FEASIBILITY
# ============================================================
#
# TARGET:
#   Legitimate rows already in original HI-Small:
#       5,073,168
#
#   Required synthetic laundering rows:
#       5,067,982
#
#   Final total:
#      10,146,150 rows
#
# NOTE:
#   This is based on ORIGINAL HI-Small counts.
#   The previous synthetic dataset is NOT used.
#
# This cell:
#   1. Loads exact IBM templates
#   2. Calculates typology transaction proportions
#   3. Calculates target synthetic transaction count
#   4. Tests exact feasibility per typology
#   5. Checks GCD / reachable transaction counts
#   6. Produces generation targets
#
# NO SYNTHETIC DATA CREATED.
# ============================================================

import os
import json
import math
import numpy as np
import pandas as pd

# ------------------------------------------------------------
# PATHS
# ------------------------------------------------------------
WORK_DIR = "/kaggle/working/AML_GNN_ONLY/data"

TEMPLATE_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_pattern_templates.json"
)

OUT_PLAN = os.path.join(
    WORK_DIR,
    "HI-Small_synthetic_generation_plan.json"
)

# ------------------------------------------------------------
# ORIGINAL DATA COUNTS
# ------------------------------------------------------------
ORIGINAL_LEGITIMATE = 5_073_168
ORIGINAL_LAUNDERING = 5_177

TARGET_SYNTHETIC_LAUNDERING = (
    5_073_168 - ORIGINAL_LAUNDERING
)

FINAL_TOTAL = (
    ORIGINAL_LEGITIMATE
    +
    ORIGINAL_LAUNDERING
    +
    TARGET_SYNTHETIC_LAUNDERING
)

print("=" * 100)
print("CELL 12 — EXACT SYNTHETIC PATTERN ALLOCATION FEASIBILITY")
print("=" * 100)

print("\nOriginal legitimate rows:",
      f"{ORIGINAL_LEGITIMATE:,}")

print("Original laundering rows:",
      f"{ORIGINAL_LAUNDERING:,}")

print("Synthetic laundering required:",
      f"{TARGET_SYNTHETIC_LAUNDERING:,}")

print("Final balanced total:",
      f"{FINAL_TOTAL:,}")

# ============================================================
# 1. LOAD TEMPLATES
# ============================================================
with open(
    TEMPLATE_PATH,
    "r",
    encoding="utf-8"
) as f:

    manifest = json.load(f)

templates = manifest["templates"]

print("\nTemplates loaded:",
      len(templates))

# ============================================================
# 2. BUILD TEMPLATE DATAFRAME
# ============================================================
template_df = pd.DataFrame(
    [
        {
            "template_id":
                t["template_id"],

            "episode_index":
                t["episode_index"],

            "typology":
                t["typology"],

            "transaction_count":
                t["transaction_count"],

            "node_count":
                t["node_count"],

            "span_minutes":
                t["episode_span_minutes"]
        }
        for t in templates
    ]
)

# ============================================================
# 3. ORIGINAL IBM TYPOLOGY DISTRIBUTION
# ============================================================
print("\n" + "=" * 80)
print("1. ORIGINAL IBM TYPOLOGY DISTRIBUTION")
print("=" * 80)

typology_stats = (
    template_df
    .groupby("typology")
    .agg(
        episodes=(
            "template_id",
            "count"
        ),

        transactions=(
            "transaction_count",
            "sum"
        ),

        mean_transactions=(
            "transaction_count",
            "mean"
        ),

        median_transactions=(
            "transaction_count",
            "median"
        ),

        min_transactions=(
            "transaction_count",
            "min"
        ),

        max_transactions=(
            "transaction_count",
            "max"
        )
    )
    .sort_index()
)

total_pattern_transactions = (
    typology_stats[
        "transactions"
    ].sum()
)

typology_stats[
    "transaction_share"
] = (
    typology_stats[
        "transactions"
    ]
    /
    total_pattern_transactions
)

print(
    typology_stats.to_string()
)

print(
    "\nTotal IBM pattern transactions:",
    total_pattern_transactions
)

# ============================================================
# 4. TARGET TRANSACTIONS BY TYPOLOGY
# ============================================================
print("\n" + "=" * 80)
print("2. TARGET SYNTHETIC TRANSACTIONS BY TYPOLOGY")
print("=" * 80)

# Largest-remainder allocation guarantees that the
# integer typology targets sum EXACTLY to the target.
raw_targets = (
    typology_stats[
        "transaction_share"
    ]
    *
    TARGET_SYNTHETIC_LAUNDERING
)

floor_targets = np.floor(
    raw_targets
).astype(int)

remainder = (
    TARGET_SYNTHETIC_LAUNDERING
    -
    int(floor_targets.sum())
)

fractional_parts = (
    raw_targets
    -
    floor_targets
)

largest_fractional = (
    fractional_parts
    .sort_values(
        ascending=False
    )
)

target_transactions = floor_targets.copy()

for typology in (
    largest_fractional
    .head(remainder)
    .index
):

    target_transactions.loc[
        typology
    ] += 1

typology_stats[
    "target_transactions"
] = target_transactions

print(
    typology_stats[
        [
            "episodes",
            "transactions",
            "transaction_share",
            "target_transactions"
        ]
    ].to_string()
)

print(
    "\nTarget sum:",
    f"{typology_stats['target_transactions'].sum():,}"
)

assert (
    typology_stats[
        "target_transactions"
    ].sum()
    ==
    TARGET_SYNTHETIC_LAUNDERING
)

# ============================================================
# 5. TEMPLATE SIZE FEASIBILITY
# ============================================================
print("\n" + "=" * 80)
print("3. TEMPLATE SIZE FEASIBILITY")
print("=" * 80)

feasibility = {}

for typology, g in (
    template_df
    .groupby("typology")
):

    sizes = sorted(
        set(
            g[
                "transaction_count"
            ].astype(int)
        )
    )

    gcd_all = 0

    for size in sizes:
        gcd_all = math.gcd(
            gcd_all,
            int(size)
        )

    feasibility[
        typology
    ] = {

        "unique_transaction_sizes":
            sizes,

        "min_template_transactions":
            int(min(sizes)),

        "max_template_transactions":
            int(max(sizes)),

        "gcd_of_template_sizes":
            int(gcd_all),

        "template_count":
            int(len(g))
    }

    print(
        f"\n{typology}"
    )

    print(
        "  Template count:",
        len(g)
    )

    print(
        "  Transaction sizes:",
        sizes
    )

    print(
        "  Min:",
        min(sizes)
    )

    print(
        "  Max:",
        max(sizes)
    )

    print(
        "  GCD:",
        gcd_all
    )

# ============================================================
# 6. EXACT REACHABILITY CHECK
# ============================================================
print("\n" + "=" * 80)
print("4. EXACT TARGET REACHABILITY")
print("=" * 80)

def reachable_with_unbounded_templates(
    target,
    sizes
):
    """
    Check whether target can be formed using any number
    of template transaction sizes.

    We only search a bounded tail because target is huge.
    With realistic template sizes and gcd=1, every
    sufficiently large value is reachable.

    Returns:
        True / False
    """

    target = int(target)

    sizes = sorted(
        set(
            int(x)
            for x in sizes
            if int(x) > 0
        )
    )

    if not sizes:
        return False

    # GCD necessary condition
    g = 0

    for size in sizes:
        g = math.gcd(g, size)

    if target % g != 0:
        return False

    # For very large targets, inspect a bounded region
    # near the target.
    max_size = max(sizes)

    # Dynamic programming only needs a finite tail.
    limit = min(
        target,
        max_size * 20_000
    )

    reachable = np.zeros(
        limit + 1,
        dtype=np.bool_
    )

    reachable[0] = True

    for value in range(
        1,
        limit + 1
    ):

        for size in sizes:

            if size > value:
                break

            if reachable[
                value - size
            ]:

                reachable[value] = True
                break

    # If target itself is within calculated region
    if target <= limit:
        return bool(
            reachable[target]
        )

    # Otherwise, test a reachable tail.
    # If gcd=1 and the largest target region contains a
    # consecutive reachable stretch of max_size values,
    # then every sufficiently larger target is reachable.
    tail_start = (
        limit
        -
        max_size
        +
        1
    )

    tail = reachable[
        tail_start:
        limit + 1
    ]

    return bool(
        tail.all()
        and
        g == 1
    )

reachability = {}

for typology in typology_stats.index:

    target = int(
        typology_stats.loc[
            typology,
            "target_transactions"
        ]
    )

    sizes = feasibility[
        typology
    ]["unique_transaction_sizes"]

    possible = (
        reachable_with_unbounded_templates(
            target,
            sizes
        )
    )

    reachability[
        typology
    ] = bool(possible)

    print(
        f"{typology:20s}"
        f" target={target:,}"
        f" | reachable={possible}"
    )

# ============================================================
# 7. ESTIMATED EPISODE COUNTS
# ============================================================
print("\n" + "=" * 80)
print("5. ESTIMATED EPISODE COUNTS")
print("=" * 80)

for typology in typology_stats.index:

    target_tx = int(
        typology_stats.loc[
            typology,
            "target_transactions"
        ]
    )

    mean_tx = float(
        typology_stats.loc[
            typology,
            "mean_transactions"
        ]
    )

    estimated_episodes = int(
        round(
            target_tx
            /
            mean_tx
        )
    )

    print(
        f"{typology:20s}"
        f" target_tx={target_tx:,}"
        f" | mean_tx/episode={mean_tx:.3f}"
        f" | estimated episodes={estimated_episodes:,}"
    )

# ============================================================
# 8. GLOBAL ESTIMATED EPISODE COUNT
# ============================================================
estimated_total_episodes = 0

for typology in typology_stats.index:

    target_tx = int(
        typology_stats.loc[
            typology,
            "target_transactions"
        ]
    )

    mean_tx = float(
        typology_stats.loc[
            typology,
            "mean_transactions"
        ]
    )

    estimated_total_episodes += int(
        round(
            target_tx / mean_tx
        )
    )

print(
    "\nEstimated synthetic laundering episodes:",
    f"{estimated_total_episodes:,}"
)

# ============================================================
# 9. SAVE PLAN
# ============================================================
plan = {

    "source_dataset":
        "IBM HI-Small",

    "original_legitimate_rows":
        ORIGINAL_LEGITIMATE,

    "original_laundering_rows":
        ORIGINAL_LAUNDERING,

    "synthetic_laundering_rows_required":
        TARGET_SYNTHETIC_LAUNDERING,

    "final_total_rows":
        FINAL_TOTAL,

    "original_pattern_episodes":
        int(len(templates)),

    "original_pattern_transactions":
        int(total_pattern_transactions),

    "typology_targets": {

        str(typology): {

            "original_episodes":
                int(
                    typology_stats.loc[
                        typology,
                        "episodes"
                    ]
                ),

            "original_transactions":
                int(
                    typology_stats.loc[
                        typology,
                        "transactions"
                    ]
                ),

            "original_transaction_share":
                float(
                    typology_stats.loc[
                        typology,
                        "transaction_share"
                    ]
                ),

            "target_synthetic_transactions":
                int(
                    typology_stats.loc[
                        typology,
                        "target_transactions"
                    ]
                ),

            "template_sizes":
                feasibility[
                    typology
                ][
                    "unique_transaction_sizes"
                ],

            "template_size_gcd":
                feasibility[
                    typology
                ][
                    "gcd_of_template_sizes"
                ],

            "exactly_reachable":
                bool(
                    reachability[
                        typology
                    ]
                )
        }

        for typology
        in typology_stats.index
    }
}

with open(
    OUT_PLAN,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        plan,
        f,
        indent=2
    )

# ============================================================
# 10. FINAL
# ============================================================
print("\n" + "=" * 100)
print("✅ CELL 12 COMPLETE")
print("=" * 100)

print(
    "Synthetic laundering target:",
    f"{TARGET_SYNTHETIC_LAUNDERING:,}"
)

print(
    "Final balanced dataset:",
    f"{FINAL_TOTAL:,}"
)

print(
    "All typology targets sum exactly:",
    int(
        typology_stats[
            "target_transactions"
        ].sum()
    )
    ==
    TARGET_SYNTHETIC_LAUNDERING
)

print(
    "All typologies exactly reachable:",
    all(
        reachability.values()
    )
)

print(
    "\nSaved plan:"
)

print(
    OUT_PLAN
)

print(
    "\nNO SYNTHETIC ACCOUNTS CREATED."
)

print(
    "NO SYNTHETIC TRANSACTIONS CREATED."
)

print(
    "NO ORIGINAL FILE MODIFIED."
)

print("=" * 100)

====================================================================================================
CELL 12 — EXACT SYNTHETIC PATTERN ALLOCATION FEASIBILITY
====================================================================================================

Original legitimate rows: 5,073,168
Original laundering rows: 5,177
Synthetic laundering required: 5,067,991
Final balanced total: 10,146,336

Templates loaded: 370

================================================================================
1. ORIGINAL IBM TYPOLOGY DISTRIBUTION
================================================================================
                episodes  transactions  mean_transactions  median_transactions  min_transactions  max_transactions  transaction_share
typology
BIPARTITE             49           263           5.367347                  4.0                 1                15           0.081957
CYCLE                 54           287           5.314815                  4.0                 2                12           0.089436
FAN-IN                40           318           7.950000                  8.0                 1                16           0.099096
FAN-OUT               48           342           7.125000                  7.0                 1                16           0.106575
GATHER-SCATTER        51           716          14.039216                 14.0                 2                28           0.223122
RANDOM                41           191           4.658537                  3.0                 1                11           0.059520
SCATTER-GATHER        44           626          14.227273                 14.0                 2                32           0.195076
STACK                 43           466          10.837209                 10.0                 2                30           0.145217

Total IBM pattern transactions: 3209

================================================================================
2. TARGET SYNTHETIC TRANSACTIONS BY TYPOLOGY
================================================================================
                episodes  transactions  transaction_share  target_transactions
typology
BIPARTITE             49           263           0.081957               415357
CYCLE                 54           287           0.089436               453261
FAN-IN                40           318           0.099096               502219
FAN-OUT               48           342           0.106575               540123
GATHER-SCATTER        51           716           0.223122              1130783
RANDOM                41           191           0.059520               301647
SCATTER-GATHER        44           626           0.195076               988645
STACK                 43           466           0.145217               735956

Target sum: 5,067,991

================================================================================
3. TEMPLATE SIZE FEASIBILITY
================================================================================

BIPARTITE
  Template count: 49
  Transaction sizes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15]
  Min: 1
  Max: 15
  GCD: 1

CYCLE
  Template count: 54
  Transaction sizes: [2, 3, 4, 5, 6, 7, 8, 10, 11, 12]
  Min: 2
  Max: 12
  GCD: 1

FAN-IN
  Template count: 40
  Transaction sizes: [1, 2, 3, 5, 6, 8, 10, 11, 12, 13, 15, 16]
  Min: 1
  Max: 16
  GCD: 1

FAN-OUT
  Template count: 48
  Transaction sizes: [1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
  Min: 1
  Max: 16
  GCD: 1

GATHER-SCATTER
  Template count: 51
  Transaction sizes: [2, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 17, 19, 20, 21, 22, 24, 25, 26, 27, 28]
  Min: 2
  Max: 28
  GCD: 1

RANDOM
  Template count: 41
  Transaction sizes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
  Min: 1
  Max: 11
  GCD: 1

SCATTER-GATHER
  Template count: 44
  Transaction sizes: [2, 4, 6, 12, 14, 16, 18, 22, 24, 26, 28, 30, 32]
  Min: 2
  Max: 32
  GCD: 2

STACK
  Template count: 43
  Transaction sizes: [2, 4, 6, 8, 10, 12, 14, 16, 20, 22, 24, 26, 28, 30]
  Min: 2
  Max: 30
  GCD: 2

================================================================================
4. EXACT TARGET REACHABILITY
================================================================================
BIPARTITE            target=415,357 | reachable=True
CYCLE                target=453,261 | reachable=True
FAN-IN               target=502,219 | reachable=True
FAN-OUT              target=540,123 | reachable=True
GATHER-SCATTER       target=1,130,783 | reachable=True
RANDOM               target=301,647 | reachable=True
SCATTER-GATHER       target=988,645 | reachable=False
STACK                target=735,956 | reachable=False

================================================================================
5. ESTIMATED EPISODE COUNTS
================================================================================
BIPARTITE            target_tx=415,357 | mean_tx/episode=5.367 | estimated episodes=77,386
CYCLE                target_tx=453,261 | mean_tx/episode=5.315 | estimated episodes=85,283
FAN-IN               target_tx=502,219 | mean_tx/episode=7.950 | estimated episodes=63,172
FAN-OUT              target_tx=540,123 | mean_tx/episode=7.125 | estimated episodes=75,807
GATHER-SCATTER       target_tx=1,130,783 | mean_tx/episode=14.039 | estimated episodes=80,545
RANDOM               target_tx=301,647 | mean_tx/episode=4.659 | estimated episodes=64,751
SCATTER-GATHER       target_tx=988,645 | mean_tx/episode=14.227 | estimated episodes=69,489
STACK                target_tx=735,956 | mean_tx/episode=10.837 | estimated episodes=67,910

Estimated synthetic laundering episodes: 584,343

====================================================================================================
✅ CELL 12 COMPLETE
====================================================================================================
Synthetic laundering target: 5,067,991
Final balanced dataset: 10,146,336
All typology targets sum exactly: True
All typologies exactly reachable: False

Saved plan:
/kaggle/working/AML_GNN_ONLY/data/HI-Small_synthetic_generation_plan.json

NO SYNTHETIC ACCOUNTS CREATED.
NO SYNTHETIC TRANSACTIONS CREATED.
NO ORIGINAL FILE MODIFIED.
====================================================================================================

In [19]:
# ============================================================
# CELL 13 — PARITY-CORRECTED EXACT GENERATION PLAN
# ============================================================
#
# Problem discovered in CELL 12:
#
#   SCATTER-GATHER template sizes are all EVEN
#   STACK template sizes are all EVEN
#
# Therefore their target transaction counts MUST be even.
#
# Current targets:
#   SCATTER-GATHER = 988,645  -> impossible (odd)
#   STACK           = 735,956  -> already possible (even)
#
# Wait:
#   STACK is already even.
#   Therefore only SCATTER-GATHER requires correction.
#
# We will:
#   +1 SCATTER-GATHER
#   -1 from a typology whose templates can produce any large
#      integer count.
#
# The adjustment is selected to minimize proportional distortion.
#
# NO SYNTHETIC DATA CREATED.
# ============================================================

import os
import json
import math
import numpy as np
import pandas as pd

# ------------------------------------------------------------
# PATHS
# ------------------------------------------------------------
WORK_DIR = "/kaggle/working/AML_GNN_ONLY/data"

TEMPLATE_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_pattern_templates.json"
)

OLD_PLAN_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_synthetic_generation_plan.json"
)

OUT_PLAN = os.path.join(
    WORK_DIR,
    "HI-Small_synthetic_generation_plan_v2.json"
)

# ------------------------------------------------------------
# TARGET
# ------------------------------------------------------------
TARGET_SYNTHETIC = 5_067_991

# ============================================================
# 1. LOAD DATA
# ============================================================
with open(
    TEMPLATE_PATH,
    "r",
    encoding="utf-8"
) as f:
    manifest = json.load(f)

templates = manifest["templates"]

template_df = pd.DataFrame(
    [
        {
            "template_id": t["template_id"],
            "typology": t["typology"],
            "transaction_count": int(
                t["transaction_count"]
            )
        }
        for t in templates
    ]
)

# ============================================================
# 2. ORIGINAL IBM TRANSACTION SHARES
# ============================================================
typology_original = (
    template_df
    .groupby("typology")[
        "transaction_count"
    ]
    .sum()
    .sort_index()
)

total_original = (
    typology_original.sum()
)

shares = (
    typology_original
    /
    total_original
)

# ============================================================
# 3. START WITH ORIGINAL CELL-12 TARGETS
# ============================================================
raw_targets = (
    shares
    *
    TARGET_SYNTHETIC
)

targets = np.floor(
    raw_targets
).astype(int)

remaining = (
    TARGET_SYNTHETIC
    -
    int(targets.sum())
)

fractional = (
    raw_targets
    -
    targets
)

for typology in (
    fractional
    .sort_values(
        ascending=False
    )
    .head(remaining)
    .index
):

    targets.loc[
        typology
    ] += 1

targets = targets.astype(int)

# ============================================================
# 4. TEMPLATE-SIZE FEASIBILITY
# ============================================================
size_info = {}

for typology, g in (
    template_df
    .groupby("typology")
):

    sizes = sorted(
        g[
            "transaction_count"
        ]
        .astype(int)
        .unique()
        .tolist()
    )

    gcd_value = 0

    for s in sizes:
        gcd_value = math.gcd(
            gcd_value,
            int(s)
        )

    size_info[
        typology
    ] = {
        "sizes": sizes,
        "gcd": gcd_value,
        "min": min(sizes),
        "max": max(sizes)
    }

# ============================================================
# 5. IDENTIFY PARITY-CONSTRAINED TYPOLOGIES
# ============================================================
print("=" * 100)
print("CELL 13 — PARITY-CORRECTED EXACT GENERATION PLAN")
print("=" * 100)

print("\nInitial targets:")
print(
    targets.to_string()
)

parity_constrained = []

for typology in targets.index:

    sizes = size_info[
        typology
    ]["sizes"]

    # If all template sizes are even, target must be even.
    all_even = all(
        int(s) % 2 == 0
        for s in sizes
    )

    if all_even:

        parity_constrained.append(
            typology
        )

        print(
            f"\n{typology}:"
        )

        print(
            "  Template sizes:",
            sizes
        )

        print(
            "  GCD:",
            size_info[
                typology
            ]["gcd"]
        )

        print(
            "  Target:",
            int(
                targets.loc[
                    typology
                ]
            )
        )

        print(
            "  Target parity:",
            int(
                targets.loc[
                    typology
                ]
            ) % 2
        )

# ============================================================
# 6. FIND INFEASIBLE TARGETS
# ============================================================
infeasible = []

for typology in targets.index:

    target = int(
        targets.loc[
            typology
        ]
    )

    gcd_value = size_info[
        typology
    ]["gcd"]

    if target % gcd_value != 0:

        infeasible.append(
            typology
        )

print("\n" + "=" * 80)
print("1. INFEASIBLE TARGETS")
print("=" * 80)

for typology in infeasible:

    print(
        f"{typology:20s}"
        f" target={targets.loc[typology]:,}"
        f" gcd={size_info[typology]['gcd']}"
    )

# ============================================================
# 7. FIND BEST SOURCE TYPOLOGY FOR REDISTRIBUTION
# ============================================================
#
# We need:
#
#   target[SCATTER-GATHER] += 1
#
# and
#
#   target[source] -= 1
#
# so the total stays unchanged.
#
# Source must NOT be parity-constrained.
# We choose the largest target among eligible types because
# removing one transaction creates the smallest proportional
# disturbance.
# ============================================================

if len(infeasible) == 0:

    print(
        "\n✅ No feasibility correction required."
    )

else:

    source_candidates = []

    for typology in targets.index:

        if typology in infeasible:
            continue

        gcd_value = size_info[
            typology
        ]["gcd"]

        # gcd=1 means no parity restriction at the
        # transaction-count level.
        if gcd_value == 1:

            source_candidates.append(
                typology
            )

    source_candidates = sorted(
        source_candidates,
        key=lambda x:
            int(
                targets.loc[x]
            ),
        reverse=True
    )

    if len(source_candidates) == 0:

        raise RuntimeError(
            "No suitable typology available "
            "for target redistribution."
        )

    print("\nEligible source typologies:")

    for typology in source_candidates:

        print(
            f"  {typology:20s}"
            f" target={targets.loc[typology]:,}"
        )

    # --------------------------------------------------------
    # Determine correction.
    # --------------------------------------------------------
    #
    # In this dataset SCATTER-GATHER has an odd target and
    # requires +1.
    #
    correction_targets = targets.copy()

    for typology in infeasible:

        current = int(
            correction_targets.loc[
                typology
            ]
        )

        # Find nearest higher target satisfying gcd.
        new_target = current

        while (
            new_target % size_info[
                typology
            ]["gcd"] != 0
        ):
            new_target += 1

        delta = (
            new_target
            -
            current
        )

        correction_targets.loc[
            typology
        ] = new_target

        # Remove the same amount from the largest
        # eligible source.
        remaining_correction = delta

        for source in source_candidates:

            available = int(
                correction_targets.loc[
                    source
                ]
            )

            if available <= 0:
                continue

            remove = min(
                remaining_correction,
                available
            )

            correction_targets.loc[
                source
            ] -= remove

            remaining_correction -= remove

            if remaining_correction == 0:
                break

        if remaining_correction != 0:

            raise RuntimeError(
                "Could not redistribute "
                f"{delta} transactions for {typology}."
            )

    targets = correction_targets.astype(int)

# ============================================================
# 8. FINAL TARGET CHECK
# ============================================================
print("\n" + "=" * 80)
print("2. CORRECTED TARGETS")
print("=" * 80)

comparison = pd.DataFrame(
    {
        "original_target": (
            pd.Series(
                raw_targets
            )
            .round()
            .astype(int)
        ),

        "initial_target": (
            pd.Series(
                np.floor(
                    raw_targets
                ).astype(int)
            )
        ),

        "corrected_target": targets
    }
)

# Add actual proportional share
comparison[
    "corrected_share"
] = (
    comparison[
        "corrected_target"
    ]
    /
    TARGET_SYNTHETIC
)

comparison[
    "original_share"
] = shares

comparison[
    "delta"
] = (
    comparison[
        "corrected_target"
    ]
    -
    comparison[
        "initial_target"
    ]
)

print(
    comparison[
        [
            "initial_target",
            "corrected_target",
            "delta",
            "original_share",
            "corrected_share"
        ]
    ].to_string()
)

print(
    "\nCorrected target sum:",
    f"{targets.sum():,}"
)

assert (
    int(targets.sum())
    ==
    TARGET_SYNTHETIC
)

# ============================================================
# 9. EXACT GCD FEASIBILITY CHECK
# ============================================================
print("\n" + "=" * 80)
print("3. GCD FEASIBILITY")
print("=" * 80)

all_feasible = True

for typology in targets.index:

    target = int(
        targets.loc[
            typology
        ]
    )

    gcd_value = size_info[
        typology
    ]["gcd"]

    feasible = (
        target % gcd_value == 0
    )

    print(
        f"{typology:20s}"
        f" target={target:,}"
        f" | gcd={gcd_value}"
        f" | feasible_by_gcd={feasible}"
    )

    if not feasible:
        all_feasible = False

if not all_feasible:

    raise RuntimeError(
        "At least one corrected target "
        "still violates its template-size GCD."
    )

# ============================================================
# 10. ACTUAL TEMPLATE COUNTS NEEDED
# ============================================================
#
# Number of episodes depends on which templates are sampled.
#
# We estimate using original mean transaction count.
# ============================================================

print("\n" + "=" * 80)
print("4. ESTIMATED EPISODE COUNTS")
print("=" * 80)

episode_estimates = {}

for typology in targets.index:

    g = template_df[
        template_df["typology"]
        == typology
    ]

    mean_tx = g[
        "transaction_count"
    ].mean()

    estimate = int(
        round(
            int(
                targets.loc[
                    typology
                ]
            )
            /
            mean_tx
        )
    )

    episode_estimates[
        typology
    ] = estimate

    print(
        f"{typology:20s}"
        f" transactions={targets.loc[typology]:,}"
        f" | mean tx/template={mean_tx:.4f}"
        f" | estimated episodes={estimate:,}"
    )

# ============================================================
# 11. SAVE PLAN
# ============================================================
plan = {

    "dataset":
        "IBM HI-Small",

    "original_legitimate_rows":
        5_073_168,

    "original_laundering_rows":
        5_177,

    "synthetic_laundering_required":
        TARGET_SYNTHETIC,

    "final_balanced_total":
        5_073_168 + 5_177 + TARGET_SYNTHETIC,

    "template_count":
        len(templates),

    "template_transaction_count":
        int(total_original),

    "allocation_method":
        "IBM transaction-share allocation with minimal GCD correction",

    "typology_targets": {

        str(typology): {

            "original_ibm_transactions":
                int(
                    typology_original.loc[
                        typology
                    ]
                ),

            "original_ibm_share":
                float(
                    shares.loc[
                        typology
                    ]
                ),

            "initial_target":
                int(
                    comparison.loc[
                        typology,
                        "initial_target"
                    ]
                ),

            "corrected_target":
                int(
                    targets.loc[
                        typology
                    ]
                ),

            "target_delta":
                int(
                    comparison.loc[
                        typology,
                        "delta"
                    ]
                ),

            "template_sizes":
                size_info[
                    typology
                ]["sizes"],

            "template_gcd":
                int(
                    size_info[
                        typology
                    ]["gcd"]
                ),

            "estimated_episode_count":
                int(
                    episode_estimates[
                        typology
                    ]
                )
        }

        for typology in targets.index
    }
}

with open(
    OUT_PLAN,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        plan,
        f,
        indent=2
    )

# ============================================================
# 12. FINAL
# ============================================================
print("\n" + "=" * 100)
print("✅ CELL 13 COMPLETE")
print("=" * 100)

print(
    "Synthetic laundering target:",
    f"{TARGET_SYNTHETIC:,}"
)

print(
    "Corrected target sum:",
    f"{targets.sum():,}"
)

print(
    "GCD-feasible:",
    all_feasible
)

print(
    "Number of target adjustments:",
    int(
        (
            comparison["delta"]
            != 0
        ).sum()
    )
)

print(
    "Total transaction adjustment:",
    int(
        comparison["delta"].abs().sum()
    )
)

print(
    "\nSaved:"
)

print(
    OUT_PLAN
)

print(
    "\nNO SYNTHETIC DATA CREATED."
)

print(
    "NO ORIGINAL FILE MODIFIED."
)

print("=" * 100)

====================================================================================================
CELL 13 — PARITY-CORRECTED EXACT GENERATION PLAN
====================================================================================================

Initial targets:
typology
BIPARTITE          415357
CYCLE              453261
FAN-IN             502219
FAN-OUT            540123
GATHER-SCATTER    1130783
RANDOM             301647
SCATTER-GATHER     988645
STACK              735956

SCATTER-GATHER:
  Template sizes: [2, 4, 6, 12, 14, 16, 18, 22, 24, 26, 28, 30, 32]
  GCD: 2
  Target: 988645
  Target parity: 1

STACK:
  Template sizes: [2, 4, 6, 8, 10, 12, 14, 16, 20, 22, 24, 26, 28, 30]
  GCD: 2
  Target: 735956
  Target parity: 0

================================================================================
1. INFEASIBLE TARGETS
================================================================================
SCATTER-GATHER       target=988,645 gcd=2

Eligible source typologies:
  GATHER-SCATTER       target=1,130,783
  FAN-OUT              target=540,123
  FAN-IN               target=502,219
  CYCLE                target=453,261
  BIPARTITE            target=415,357
  RANDOM               target=301,647

================================================================================
2. CORRECTED TARGETS
================================================================================
                initial_target  corrected_target  delta  original_share  corrected_share
typology
BIPARTITE               415357            415357      0        0.081957         0.081957
CYCLE                   453260            453261      1        0.089436         0.089436
FAN-IN                  502219            502219      0        0.099096         0.099096
FAN-OUT                 540122            540123      1        0.106575         0.106575
GATHER-SCATTER         1130782           1130782      0        0.223122         0.223122
RANDOM                  301647            301647      0        0.059520         0.059520
SCATTER-GATHER          988645            988646      1        0.195076         0.195077
STACK                   735956            735956      0        0.145217         0.145217

Corrected target sum: 5,067,991

================================================================================
3. GCD FEASIBILITY
================================================================================
BIPARTITE            target=415,357 | gcd=1 | feasible_by_gcd=True
CYCLE                target=453,261 | gcd=1 | feasible_by_gcd=True
FAN-IN               target=502,219 | gcd=1 | feasible_by_gcd=True
FAN-OUT              target=540,123 | gcd=1 | feasible_by_gcd=True
GATHER-SCATTER       target=1,130,782 | gcd=1 | feasible_by_gcd=True
RANDOM               target=301,647 | gcd=1 | feasible_by_gcd=True
SCATTER-GATHER       target=988,646 | gcd=2 | feasible_by_gcd=True
STACK                target=735,956 | gcd=2 | feasible_by_gcd=True

================================================================================
4. ESTIMATED EPISODE COUNTS
================================================================================
BIPARTITE            transactions=415,357 | mean tx/template=5.3673 | estimated episodes=77,386
CYCLE                transactions=453,261 | mean tx/template=5.3148 | estimated episodes=85,283
FAN-IN               transactions=502,219 | mean tx/template=7.9500 | estimated episodes=63,172
FAN-OUT              transactions=540,123 | mean tx/template=7.1250 | estimated episodes=75,807
GATHER-SCATTER       transactions=1,130,782 | mean tx/template=14.0392 | estimated episodes=80,545
RANDOM               transactions=301,647 | mean tx/template=4.6585 | estimated episodes=64,751
SCATTER-GATHER       transactions=988,646 | mean tx/template=14.2273 | estimated episodes=69,489
STACK                transactions=735,956 | mean tx/template=10.8372 | estimated episodes=67,910

====================================================================================================
✅ CELL 13 COMPLETE
====================================================================================================
Synthetic laundering target: 5,067,991
Corrected target sum: 5,067,991
GCD-feasible: True
Number of target adjustments: 3
Total transaction adjustment: 3

Saved:
/kaggle/working/AML_GNN_ONLY/data/HI-Small_synthetic_generation_plan_v2.json

NO SYNTHETIC DATA CREATED.
NO ORIGINAL FILE MODIFIED.
====================================================================================================

In [20]:
# ============================================================
# CELL 14 — EXACT EPISODE-LEVEL TEMPLATE ALLOCATION
# ============================================================
#
# Purpose:
#   Convert exact typology transaction targets into an exact
#   list of synthetic laundering episodes.
#
# Design:
#   - Use ORIGINAL IBM template-size distribution
#   - Preserve typology-specific episode morphology
#   - Sample actual IBM templates with replacement
#   - Exact transaction total per typology
#   - Exact global synthetic transaction total
#
# Creates:
#   HI-Small_synthetic_episode_plan.csv
#   HI-Small_synthetic_episode_plan.json
#
# NO synthetic transactions are generated here.
# NO original files modified.
# ============================================================

import os
import json
import math
import random
import numpy as np
import pandas as pd

# ------------------------------------------------------------
# PATHS
# ------------------------------------------------------------
WORK_DIR = "/kaggle/working/AML_GNN_ONLY/data"

TEMPLATE_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_pattern_templates.json"
)

PLAN_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_synthetic_generation_plan_v2.json"
)

OUT_CSV = os.path.join(
    WORK_DIR,
    "HI-Small_synthetic_episode_plan.csv"
)

OUT_JSON = os.path.join(
    WORK_DIR,
    "HI-Small_synthetic_episode_plan.json"
)

# ------------------------------------------------------------
# REPRODUCIBILITY
# ------------------------------------------------------------
SEED = 20260919

random.seed(SEED)
np.random.seed(SEED)

print("=" * 100)
print("CELL 14 — EXACT EPISODE-LEVEL TEMPLATE ALLOCATION")
print("=" * 100)

# ============================================================
# 1. LOAD IBM TEMPLATES
# ============================================================
with open(
    TEMPLATE_PATH,
    "r",
    encoding="utf-8"
) as f:
    template_manifest = json.load(f)

templates = template_manifest[
    "templates"
]

template_df = pd.DataFrame(
    [
        {
            "template_id":
                str(t["template_id"]),

            "episode_index":
                int(t["episode_index"]),

            "typology":
                str(t["typology"]),

            "transaction_count":
                int(t["transaction_count"])
        }
        for t in templates
    ]
)

print(
    "IBM templates loaded:",
    len(template_df)
)

# ============================================================
# 2. LOAD EXACT TYPOLOGY TARGETS
# ============================================================
with open(
    PLAN_PATH,
    "r",
    encoding="utf-8"
) as f:
    generation_plan = json.load(f)

typology_targets = {
    str(k): int(
        v["corrected_target"]
    )
    for k, v in generation_plan[
        "typology_targets"
    ].items()
}

TARGET_TOTAL = int(
    generation_plan[
        "synthetic_laundering_required"
    ]
)

print(
    "\nSynthetic target:",
    f"{TARGET_TOTAL:,}"
)

# ============================================================
# 3. SMALL EXACT INTEGER COMPOSITION SOLVER
# ============================================================
def exact_size_composition(
    target,
    sizes,
    approximate_counts
):
    """
    Find non-negative counts for transaction sizes such that:

        sum(count[size] * size) == target

    Starting point:
        approximate_counts

    Since approximate_counts are floors of expected counts,
    the residual is generally small.

    Dynamic programming is performed only on the residual.
    """

    sizes = sorted(
        set(
            int(s)
            for s in sizes
            if int(s) > 0
        )
    )

    current_total = sum(
        int(approximate_counts.get(s, 0))
        * int(s)
        for s in sizes
    )

    residual = int(
        target - current_total
    )

    if residual < 0:
        raise RuntimeError(
            "Approximate composition exceeded target."
        )

    if residual == 0:
        return {
            int(s): int(
                approximate_counts.get(
                    s,
                    0
                )
            )
            for s in sizes
        }

    # --------------------------------------------------------
    # Unbounded DP over residual
    # --------------------------------------------------------
    reachable = np.full(
        residual + 1,
        -1,
        dtype=np.int32
    )

    reachable[0] = 0

    parent_size = np.full(
        residual + 1,
        -1,
        dtype=np.int32
    )

    for amount in range(
        1,
        residual + 1
    ):

        for size in sizes:

            if size > amount:
                break

            prev = (
                amount - size
            )

            if reachable[prev] != -1:

                reachable[amount] = (
                    reachable[prev] + 1
                )

                parent_size[
                    amount
                ] = size

                break

    if reachable[residual] == -1:

        # This should only happen if the residual violates
        # the GCD constraint.
        gcd_value = 0

        for s in sizes:
            gcd_value = math.gcd(
                gcd_value,
                int(s)
            )

        raise RuntimeError(
            f"Residual {residual} not reachable. "
            f"Sizes={sizes}, GCD={gcd_value}"
        )

    # --------------------------------------------------------
    # Recover additions
    # --------------------------------------------------------
    additions = {
        int(s): 0
        for s in sizes
    }

    remaining = residual

    while remaining > 0:

        size = int(
            parent_size[remaining]
        )

        if size <= 0:
            raise RuntimeError(
                "Invalid DP parent encountered."
            )

        additions[size] += 1

        remaining -= size

    # --------------------------------------------------------
    # Final composition
    # --------------------------------------------------------
    final_counts = {}

    for size in sizes:

        final_counts[size] = (
            int(
                approximate_counts.get(
                    size,
                    0
                )
            )
            +
            int(
                additions[size]
            )
        )

    # Final validation
    final_total = sum(
        size * count
        for size, count
        in final_counts.items()
    )

    if final_total != target:

        raise RuntimeError(
            f"Composition failed: "
            f"expected={target}, "
            f"actual={final_total}"
        )

    return final_counts

# ============================================================
# 4. CREATE EPISODE PLAN
# ============================================================
episode_plan_rows = []

summary_rows = []

global_episode_counter = 0

for typology in sorted(
    typology_targets.keys()
):

    target_transactions = int(
        typology_targets[
            typology
        ]
    )

    typ_templates = (
        template_df[
            template_df["typology"]
            == typology
        ]
        .copy()
    )

    if typ_templates.empty:
        raise RuntimeError(
            f"No templates found for typology "
            f"{typology}"
        )

    # --------------------------------------------------------
    # Original episode-size distribution
    # --------------------------------------------------------
    size_episode_counts = (
        typ_templates[
            "transaction_count"
        ]
        .value_counts()
        .sort_index()
    )

    total_original_episodes = (
        size_episode_counts.sum()
    )

    size_probs = (
        size_episode_counts
        /
        total_original_episodes
    )

    # --------------------------------------------------------
    # Expected episode count
    # --------------------------------------------------------
    mean_transactions = (
        typ_templates[
            "transaction_count"
        ].mean()
    )

    expected_episode_count = (
        target_transactions
        /
        mean_transactions
    )

    # --------------------------------------------------------
    # Approximate number of episodes
    # --------------------------------------------------------
    episode_count_base = int(
        math.floor(
            expected_episode_count
        )
    )

    # Expected counts per template size
    approximate_counts = {}

    for size, probability in (
        size_probs.items()
    ):

        approximate_counts[
            int(size)
        ] = int(
            math.floor(
                episode_count_base
                *
                float(probability)
            )
        )

    # --------------------------------------------------------
    # If all rounded-down counts somehow produce too few
    # episodes, that is fine; the DP additions will fill the
    # transaction remainder.
    # --------------------------------------------------------
    sizes = sorted(
        approximate_counts.keys()
    )

    final_size_counts = exact_size_composition(
        target_transactions,
        sizes,
        approximate_counts
    )

    # --------------------------------------------------------
    # Validate exact transaction target
    # --------------------------------------------------------
    calculated_transactions = sum(
        size * count
        for size, count
        in final_size_counts.items()
    )

    if (
        calculated_transactions
        != target_transactions
    ):
        raise RuntimeError(
            f"{typology}: exact target failure."
        )

    # --------------------------------------------------------
    # Build template lookup by size
    # --------------------------------------------------------
    templates_by_size = {}

    for size in sizes:

        candidates = (
            typ_templates[
                typ_templates[
                    "transaction_count"
                ] == size
            ]["template_id"]
            .tolist()
        )

        if not candidates:
            raise RuntimeError(
                f"No templates for size {size} "
                f"in {typology}."
            )

        templates_by_size[
            int(size)
        ] = candidates

    # --------------------------------------------------------
    # Create actual episode rows
    # --------------------------------------------------------
    typology_episode_counter = 0
    typology_transaction_counter = 0

    # Shuffle the size groups so the generated episode order
    # is not grouped unnaturally by template size.
    size_jobs = []

    for size, count in (
        final_size_counts.items()
    ):

        for _ in range(
            int(count)
        ):

            size_jobs.append(
                int(size)
            )

    random.shuffle(
        size_jobs
    )

    # --------------------------------------------------------
    # For every required size, choose an IBM template with
    # uniform probability among original episodes of that size.
    # --------------------------------------------------------
    for size in size_jobs:

        template_id = random.choice(
            templates_by_size[
                int(size)
            ]
        )

        synthetic_episode_id = (
            f"SYN_{typology}_{global_episode_counter:07d}"
        )

        episode_row = {

            "synthetic_episode_id":
                synthetic_episode_id,

            "global_episode_index":
                int(global_episode_counter),

            "typology":
                typology,

            "source_template_id":
                str(template_id),

            "transaction_count":
                int(size)
        }

        episode_plan_rows.append(
            episode_row
        )

        global_episode_counter += 1

        typology_episode_counter += 1

        typology_transaction_counter += (
            int(size)
        )

    # --------------------------------------------------------
    # Summary
    # --------------------------------------------------------
    generated_sizes = (
        pd.Series(
            [
                r["transaction_count"]
                for r in episode_plan_rows[
                    -typology_episode_counter:
                ]
            ]
        )
    )

    summary_rows.append(
        {
            "typology":
                typology,

            "target_transactions":
                target_transactions,

            "generated_transactions":
                typology_transaction_counter,

            "episode_count":
                typology_episode_counter,

            "mean_transactions_per_episode":
                float(
                    generated_sizes.mean()
                ),

            "median_transactions_per_episode":
                float(
                    generated_sizes.median()
                ),

            "min_transactions_per_episode":
                int(
                    generated_sizes.min()
                ),

            "max_transactions_per_episode":
                int(
                    generated_sizes.max()
                ),

            "original_mean_transactions":
                float(mean_transactions),

            "original_episode_count":
                int(
                    total_original_episodes
                )
        }
    )

# ============================================================
# 5. DATAFRAME
# ============================================================
episode_plan = pd.DataFrame(
    episode_plan_rows
)

summary_df = pd.DataFrame(
    summary_rows
)

# ============================================================
# 6. GLOBAL VALIDATION
# ============================================================
print("\n" + "=" * 80)
print("1. TYPOLOGY GENERATION SUMMARY")
print("=" * 80)

print(
    summary_df.to_string(
        index=False
    )
)

global_generated_transactions = int(
    episode_plan[
        "transaction_count"
    ].sum()
)

print("\n" + "=" * 80)
print("2. GLOBAL VALIDATION")
print("=" * 80)

print(
    "Generated episodes:",
    f"{len(episode_plan):,}"
)

print(
    "Generated transactions:",
    f"{global_generated_transactions:,}"
)

print(
    "Required transactions:",
    f"{TARGET_TOTAL:,}"
)

print(
    "Exact transaction match:",
    global_generated_transactions
    ==
    TARGET_TOTAL
)

# ============================================================
# 7. TYPOLOGY EXACTNESS
# ============================================================
typology_check = (
    episode_plan
    .groupby("typology")
    .agg(
        generated_episodes=(
            "synthetic_episode_id",
            "count"
        ),
        generated_transactions=(
            "transaction_count",
            "sum"
        )
    )
    .reset_index()
)

target_df = pd.DataFrame(
    [
        {
            "typology": typology,
            "target_transactions":
                target_transactions
        }
        for typology, target_transactions
        in typology_targets.items()
    ]
)

typology_check = (
    target_df
    .merge(
        typology_check,
        on="typology",
        how="left"
    )
)

typology_check[
    "exact_match"
] = (
    typology_check[
        "target_transactions"
    ]
    ==
    typology_check[
        "generated_transactions"
    ]
)

print(
    "\nTypology exactness:"
)

print(
    typology_check.to_string(
        index=False
    )
)

if not bool(
    typology_check[
        "exact_match"
    ].all()
):

    raise RuntimeError(
        "At least one typology does not "
        "match its exact target."
    )

# ============================================================
# 8. SOURCE TEMPLATE COVERAGE
# ============================================================
print("\n" + "=" * 80)
print("3. SOURCE TEMPLATE COVERAGE")
print("=" * 80)

template_usage = (
    episode_plan[
        "source_template_id"
    ]
    .value_counts()
)

print(
    "IBM templates used:",
    len(template_usage),
    "/",
    len(template_df)
)

print(
    "Template coverage:",
    round(
        len(template_usage)
        /
        len(template_df)
        *
        100,
        4
    ),
    "%"
)

# ============================================================
# 9. TEMPLATE USAGE BY TYPOLOGY
# ============================================================
usage_by_type = []

for typology, g in (
    episode_plan
    .groupby("typology")
):

    source_templates = (
        g[
            "source_template_id"
        ]
        .nunique()
    )

    total_templates = (
        template_df[
            template_df["typology"]
            == typology
        ]
        ["template_id"]
        .nunique()
    )

    usage_by_type.append(
        {
            "typology":
                typology,

            "templates_used":
                int(source_templates),

            "templates_available":
                int(total_templates),

            "coverage_pct":
                float(
                    source_templates
                    /
                    total_templates
                    * 100
                )
        }
    )

usage_by_type_df = pd.DataFrame(
    usage_by_type
)

print(
    usage_by_type_df.to_string(
        index=False
    )
)

# ============================================================
# 10. SAVE CSV
# ============================================================
episode_plan.to_csv(
    OUT_CSV,
    index=False
)

# ============================================================
# 11. SAVE JSON
# ============================================================
plan_manifest = {

    "dataset":
        "IBM HI-Small",

    "seed":
        SEED,

    "synthetic_transaction_target":
        TARGET_TOTAL,

    "generated_transaction_count":
        global_generated_transactions,

    "generated_episode_count":
        int(len(episode_plan)),

    "typology_targets":
        typology_targets,

    "typology_summary":
        summary_df.to_dict(
            orient="records"
        ),

    "template_usage":
        {
            str(k): int(v)
            for k, v
            in template_usage.items()
        },

    "episodes":
        episode_plan.to_dict(
            orient="records"
        )
}

with open(
    OUT_JSON,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        plan_manifest,
        f,
        indent=2
    )

# ============================================================
# 12. FINAL
# ============================================================
print("\n" + "=" * 100)
print("✅ CELL 14 COMPLETE")
print("=" * 100)

print(
    "Episode plan:",
    OUT_CSV
)

print(
    "Episode plan manifest:",
    OUT_JSON
)

print(
    "\nSynthetic episodes planned:",
    f"{len(episode_plan):,}"
)

print(
    "Synthetic transactions planned:",
    f"{global_generated_transactions:,}"
)

print(
    "Exact target achieved:",
    global_generated_transactions
    ==
    TARGET_TOTAL
)

print(
    "\nNO SYNTHETIC TRANSACTIONS CREATED."
)

print(
    "NO SYNTHETIC ACCOUNTS CREATED."
)

print(
    "NO ORIGINAL FILE MODIFIED."
)

print("=" * 100)

====================================================================================================
CELL 14 — EXACT EPISODE-LEVEL TEMPLATE ALLOCATION
====================================================================================================
IBM templates loaded: 370

Synthetic target: 5,067,991

================================================================================
1. TYPOLOGY GENERATION SUMMARY
================================================================================
      typology  target_transactions  generated_transactions  episode_count  mean_transactions_per_episode  median_transactions_per_episode  min_transactions_per_episode  max_transactions_per_episode  original_mean_transactions  original_episode_count
     BIPARTITE               415357                  415357          77451                       5.362836                              4.0                             1                            15                    5.367347                      49
         CYCLE               453261                  453261          85293                       5.314164                              4.0                             2                            12                    5.314815                      54
        FAN-IN               502219                  502219          63218                       7.944241                              8.0                             1                            16                    7.950000                      40
       FAN-OUT               540123                  540123          75862                       7.119810                              7.0                             1                            16                    7.125000                      48
GATHER-SCATTER              1130782                 1130782          80605                      14.028683                             14.0                             2                            28                   14.039216                      51
        RANDOM               301647                  301647          64782                       4.656340                              3.0                             1                            11                    4.658537                      41
SCATTER-GATHER               988646                  988646          69540                      14.216940                             14.0                             2                            32                   14.227273                      44
         STACK               735956                  735956          67955                      10.830049                             10.0                             2                            30                   10.837209                      43

================================================================================
2. GLOBAL VALIDATION
================================================================================
Generated episodes: 584,706
Generated transactions: 5,067,991
Required transactions: 5,067,991
Exact transaction match: True

Typology exactness:
      typology  target_transactions  generated_episodes  generated_transactions  exact_match
     BIPARTITE               415357               77451                  415357         True
         CYCLE               453261               85293                  453261         True
        FAN-IN               502219               63218                  502219         True
       FAN-OUT               540123               75862                  540123         True
GATHER-SCATTER              1130782               80605                 1130782         True
        RANDOM               301647               64782                  301647         True
SCATTER-GATHER               988646               69540                  988646         True
         STACK               735956               67955                  735956         True

================================================================================
3. SOURCE TEMPLATE COVERAGE
================================================================================
IBM templates used: 370 / 370
Template coverage: 100.0 %
      typology  templates_used  templates_available  coverage_pct
     BIPARTITE              49                   49         100.0
         CYCLE              54                   54         100.0
        FAN-IN              40                   40         100.0
       FAN-OUT              48                   48         100.0
GATHER-SCATTER              51                   51         100.0
        RANDOM              41                   41         100.0
SCATTER-GATHER              44                   44         100.0
         STACK              43                   43         100.0

====================================================================================================
✅ CELL 14 COMPLETE
====================================================================================================
Episode plan: /kaggle/working/AML_GNN_ONLY/data/HI-Small_synthetic_episode_plan.csv
Episode plan manifest: /kaggle/working/AML_GNN_ONLY/data/HI-Small_synthetic_episode_plan.json

Synthetic episodes planned: 584,706
Synthetic transactions planned: 5,067,991
Exact target achieved: True

NO SYNTHETIC TRANSACTIONS CREATED.
NO SYNTHETIC ACCOUNTS CREATED.
NO ORIGINAL FILE MODIFIED.
====================================================================================================

In [21]:
# ============================================================
# CELL 15 — 5,000-EPISODE SYNTHETIC GENERATOR PILOT
# ============================================================
#
# PURPOSE
# -------
# Validate the complete synthetic-generation mechanism before
# scaling to the full 5,067,991 laundering transactions.
#
# PILOT:
#   5,000 laundering episodes
#
# Uses:
#   - Original IBM pattern templates
#   - Original HI-Small legitimate transaction DNA
#   - Real bank vocabulary
#   - Real clean account ecosystem
#   - Fresh structurally realistic accounts for a small
#     fraction of nodes
#
# Creates:
#   1. Pilot synthetic transactions CSV
#   2. Pilot new accounts CSV
#   3. Pilot Patterns.txt
#   4. Pilot manifest JSON
#
# IMPORTANT
# ---------
# Original HI-Small files are NEVER modified.
# ============================================================

import os
import re
import json
import random
import string
from collections import defaultdict

import numpy as np
import pandas as pd

# ============================================================
# CONFIGURATION
# ============================================================

SEED = 20260919

random.seed(SEED)
np.random.seed(SEED)

PILOT_EPISODES = 5000

# Fraction of template nodes that will receive a brand-new
# synthetic account.
#
# Most nodes use the original clean account ecosystem so that
# "new account" itself does not become the dominant synthetic
# signal.
NEW_ACCOUNT_RATE = 0.05

DATA_ROOT = (
    "/kaggle/input/datasets/"
    "ealtman2019/ibm-transactions-for-anti-money-laundering-aml"
)

WORK_DIR = (
    "/kaggle/working/"
    "AML_GNN_ONLY/data"
)

TRANS_PATH = os.path.join(
    DATA_ROOT,
    "HI-Small_Trans.csv"
)

ACCOUNTS_PATH = os.path.join(
    DATA_ROOT,
    "HI-Small_accounts.csv"
)

TEMPLATE_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_pattern_templates.json"
)

EPISODE_PLAN_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_synthetic_episode_plan.csv"
)

BANK_POOL_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_final_generator_bank_pool.csv"
)

ACCOUNT_REGISTRY_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_generator_account_registry.csv"
)

ACCOUNT_PREFIX_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_bank_account_prefix_sampler.json"
)

ACCOUNT_GENERATOR_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_account_id_generator.json"
)

ENTITY_DNA_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_entity_name_dna.json"
)

# ------------------------------------------------------------
# PILOT OUTPUTS
# ------------------------------------------------------------

PILOT_TRANS_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_SYNTH_PILOT_transactions.csv"
)

PILOT_ACCOUNTS_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_SYNTH_PILOT_new_accounts.csv"
)

PILOT_PATTERNS_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_SYNTH_PILOT_Patterns.txt"
)

PILOT_MANIFEST_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_SYNTH_PILOT_manifest.json"
)

print("=" * 100)
print("CELL 15 — 5,000-EPISODE SYNTHETIC GENERATOR PILOT")
print("=" * 100)

# ============================================================
# 1. LOAD IBM TEMPLATES
# ============================================================

print("\n" + "=" * 80)
print("1. LOADING IBM TEMPLATES")
print("=" * 80)

with open(
    TEMPLATE_PATH,
    "r",
    encoding="utf-8"
) as f:

    template_manifest = json.load(f)

templates = template_manifest[
    "templates"
]

template_lookup = {
    str(t["template_id"]): t
    for t in templates
}

print(
    "Templates:",
    len(templates)
)

# ============================================================
# 2. LOAD COMPLETE EPISODE PLAN
# ============================================================

episode_plan = pd.read_csv(
    EPISODE_PLAN_PATH,
    dtype=str
)

episode_plan[
    "transaction_count"
] = pd.to_numeric(
    episode_plan[
        "transaction_count"
    ],
    errors="raise"
)

print(
    "Full planned episodes:",
    f"{len(episode_plan):,}"
)

# ============================================================
# 3. STRATIFIED PILOT EPISODE SAMPLE
# ============================================================
#
# Preserve approximate typology composition in the pilot.
# ============================================================

typology_counts = (
    episode_plan["typology"]
    .value_counts()
    .sort_index()
)

target_pilot_counts = (
    typology_counts
    /
    typology_counts.sum()
    *
    PILOT_EPISODES
)

pilot_counts = np.floor(
    target_pilot_counts
).astype(int)

remainder = (
    PILOT_EPISODES
    -
    int(pilot_counts.sum())
)

fractions = (
    target_pilot_counts
    -
    pilot_counts
)

for typology in (
    fractions
    .sort_values(
        ascending=False
    )
    .head(remainder)
    .index
):

    pilot_counts.loc[
        typology
    ] += 1

pilot_parts = []

for typology, count in (
    pilot_counts.items()
):

    available = episode_plan[
        episode_plan["typology"]
        ==
        typology
    ]

    sampled = available.sample(
        n=int(count),
        random_state=SEED
        +
        sum(
            ord(c)
            for c in typology
        )
    )

    pilot_parts.append(
        sampled
    )

pilot_plan = (
    pd.concat(
        pilot_parts,
        ignore_index=True
    )
    .sample(
        frac=1,
        random_state=SEED
    )
    .reset_index(drop=True)
)

# Re-number pilot episode IDs
pilot_plan[
    "pilot_episode_index"
] = np.arange(
    len(pilot_plan)
)

pilot_plan[
    "synthetic_episode_id"
] = [
    f"SYN_{i:07d}"
    for i in range(
        len(pilot_plan)
    )
]

print(
    "Pilot episodes:",
    len(pilot_plan)
)

print(
    "\nPilot typology distribution:"
)

print(
    pilot_plan[
        "typology"
    ]
    .value_counts()
    .sort_index()
    .to_string()
)

# ============================================================
# 4. LOAD BANK POOL
# ============================================================

print("\n" + "=" * 80)
print("2. LOADING BANK POOL")
print("=" * 80)

bank_pool = pd.read_csv(
    BANK_POOL_PATH,
    dtype=str
)

numeric_bank_cols = [
    "legitimate_source_transactions",
    "legitimate_destination_transactions",
    "account_count",
    "source_probability",
    "destination_probability"
]

for col in numeric_bank_cols:

    bank_pool[col] = pd.to_numeric(
        bank_pool[col],
        errors="coerce"
    ).fillna(0)

print(
    "Banks:",
    len(bank_pool)
)

# ------------------------------------------------------------
# Bank dictionaries
# ------------------------------------------------------------

bank_ids = (
    bank_pool[
        "normalized_bank_id"
    ]
    .astype(str)
    .tolist()
)

bank_tx_id_map = {
    str(row["normalized_bank_id"]):
        str(row["canonical_transaction_bank_id"])
    for _, row in bank_pool.iterrows()
}

bank_account_id_map = {}

# Original accounts.csv representation
accounts_source_for_bank = pd.read_csv(
    ACCOUNTS_PATH,
    usecols=[
        "Bank ID",
        "Account Number"
    ],
    dtype=str
)

def normalize_bank_id(x):

    x = str(x).strip()

    if x == "":
        return None

    try:
        return str(
            int(x)
        )
    except Exception:
        return x.lstrip("0") or "0"

accounts_source_for_bank[
    "normalized_bank_id"
] = (
    accounts_source_for_bank[
        "Bank ID"
    ].map(normalize_bank_id)
)

for bank_id, g in (
    accounts_source_for_bank
    .groupby("normalized_bank_id")
):

    bank_account_id_map[
        str(bank_id)
    ] = str(
        g["Bank ID"].iloc[0]
    )

# ------------------------------------------------------------
# Weighted bank sampling
# ------------------------------------------------------------

source_bank_weights = (
    bank_pool[
        "source_probability"
    ]
    .to_numpy(
        dtype=float
    )
)

destination_bank_weights = (
    bank_pool[
        "destination_probability"
    ]
    .to_numpy(
        dtype=float
    )
)

# ============================================================
# 5. LOAD CLEAN ACCOUNT REGISTRY
# ============================================================

print("\n" + "=" * 80)
print("3. LOADING CLEAN ACCOUNT REGISTRY")
print("=" * 80)

registry = pd.read_csv(
    ACCOUNT_REGISTRY_PATH,
    dtype=str
)

registry[
    "normalized_bank_id"
] = registry[
    "normalized_bank_id"
].astype(str)

for col in [
    "legitimate_source_tx_count",
    "legitimate_destination_tx_count",
    "legitimate_total_activity"
]:

    registry[col] = pd.to_numeric(
        registry[col],
        errors="coerce"
    ).fillna(0).astype(int)

registry[
    "generator_eligible"
] = (
    registry[
        "generator_eligible"
    ].astype(str).str.lower()
    .eq("true")
)

eligible = registry[
    registry[
        "generator_eligible"
    ]
].copy()

print(
    "Eligible accounts:",
    f"{len(eligible):,}"
)

# ------------------------------------------------------------
# Create role-compatible pools
# ------------------------------------------------------------

def compatible_role(row_role, needed_role):

    if needed_role == "source":
        return row_role in {
            "source_only",
            "both"
        }

    if needed_role == "destination":
        return row_role in {
            "destination_only",
            "both"
        }

    if needed_role == "both":
        return row_role == "both"

    return True


account_pool = defaultdict(list)

for _, row in eligible.iterrows():

    role = str(
        row["role"]
    )

    bank = str(
        row["normalized_bank_id"]
    )

    if compatible_role(
        role,
        "source"
    ):

        account_pool[
            (bank, "source")
        ].append(
            str(row["Account Number"])
        )

    if compatible_role(
        role,
        "destination"
    ):

        account_pool[
            (bank, "destination")
        ].append(
            str(row["Account Number"])
        )

    if compatible_role(
        role,
        "both"
    ):

        account_pool[
            (bank, "both")
        ].append(
            str(row["Account Number"])
        )

# ------------------------------------------------------------
# Shuffle each account pool
# ------------------------------------------------------------

for key in account_pool:

    random.shuffle(
        account_pool[key]
    )

account_pool_pointer = defaultdict(int)

# Existing accounts already present in original dataset
existing_account_keys = set(
    (
        str(row["normalized_bank_id"]),
        str(row["Account Number"])
    )
    for _, row in registry.iterrows()
)

# ============================================================
# 6. ACCOUNT / ENTITY GENERATION DNA
# ============================================================

print("\n" + "=" * 80)
print("4. LOADING ACCOUNT / ENTITY GENERATION DNA")
print("=" * 80)

with open(
    ACCOUNT_PREFIX_PATH,
    "r",
    encoding="utf-8"
) as f:

    bank_prefix_sampler = json.load(f)

with open(
    ACCOUNT_GENERATOR_PATH,
    "r",
    encoding="utf-8"
) as f:

    account_generator_dna = json.load(f)

with open(
    ENTITY_DNA_PATH,
    "r",
    encoding="utf-8"
) as f:

    entity_dna = json.load(f)

position_models = (
    account_generator_dna[
        "position_models"
    ]
)

entity_position_models = (
    entity_dna[
        "entity_id_position_models"
    ]
)

name_prefixes = (
    entity_dna[
        "top_name_prefixes"
    ]
)

# ------------------------------------------------------------
# Convert JSON probabilities into arrays
# ------------------------------------------------------------

account_position_arrays = {}

for pos, values in (
    position_models.items()
):

    chars = [
        item["char"]
        for item in values
    ]

    probs = np.array(
        [
            item["probability"]
            for item in values
        ],
        dtype=float
    )

    probs = (
        probs
        /
        probs.sum()
    )

    account_position_arrays[
        int(pos)
    ] = (
        chars,
        probs
    )

# Entity ID arrays
entity_position_arrays = {}

for pos, values in (
    entity_position_models.items()
):

    chars = list(
        values.keys()
    )

    probs = np.array(
        [
            values[c]["probability"]
            for c in chars
        ],
        dtype=float
    )

    probs = (
        probs
        /
        probs.sum()
    )

    entity_position_arrays[
        int(pos)
    ] = (
        chars,
        probs
    )

# Name prefix probabilities
name_prefix_keys = list(
    name_prefixes.keys()
)

name_prefix_probs = np.array(
    [
        name_prefixes[k]
        for k in name_prefix_keys
    ],
    dtype=float
)

name_prefix_probs /= (
    name_prefix_probs.sum()
)

# ------------------------------------------------------------
# Fresh-account generators
# ------------------------------------------------------------

used_new_accounts = set()

used_new_entity_ids = set()

new_accounts_rows = []

def generate_entity_id():

    for _ in range(10000):

        chars = []

        for pos in range(
            1,
            10
        ):

            char_list, probs = (
                entity_position_arrays[
                    pos
                ]
            )

            chars.append(
                np.random.choice(
                    char_list,
                    p=probs
                )
            )

        value = "".join(chars)

        if value not in (
            used_new_entity_ids
        ):

            used_new_entity_ids.add(
                value
            )

            return value

    raise RuntimeError(
        "Unable to generate unique Entity ID."
    )


def generate_entity_name():

    prefix = np.random.choice(
        name_prefix_keys,
        p=name_prefix_probs
    )

    number = np.random.randint(
        1,
        100000
    )

    return (
        f"{prefix} #{number}"
    )


def generate_new_account(
    normalized_bank_id
):

    normalized_bank_id = str(
        normalized_bank_id
    )

    # Get bank-specific 3-char prefixes.
    prefix_info = (
        bank_prefix_sampler
        .get(
            normalized_bank_id
        )
    )

    for _ in range(10000):

        # ----------------------------------------------------
        # Prefix
        # ----------------------------------------------------
        if (
            prefix_info
            and
            prefix_info["prefixes"]
        ):

            prefixes = [
                x["prefix"]
                for x in
                prefix_info["prefixes"]
            ]

            probs = np.array(
                [
                    x["probability"]
                    for x in
                    prefix_info["prefixes"]
                ],
                dtype=float
            )

            probs /= probs.sum()

            prefix = np.random.choice(
                prefixes,
                p=probs
            )

        else:

            # Fallback: sample first 3 positions
            prefix_chars = []

            for pos in [1, 2, 3]:

                chars, probs = (
                    account_position_arrays[
                        pos
                    ]
                )

                prefix_chars.append(
                    np.random.choice(
                        chars,
                        p=probs
                    )
                )

            prefix = "".join(
                prefix_chars
            )

        # ----------------------------------------------------
        # Remaining positions 4-9
        # ----------------------------------------------------
        chars = list(
            prefix
        )

        for pos in range(
            4,
            10
        ):

            char_list, probs = (
                account_position_arrays[
                    pos
                ]
            )

            chars.append(
                np.random.choice(
                    char_list,
                    p=probs
                )
            )

        account_number = "".join(
            chars
        )

        key = (
            normalized_bank_id,
            account_number
        )

        if (
            key not in
            existing_account_keys
            and
            key not in
            used_new_accounts
        ):

            used_new_accounts.add(
                key
            )

            entity_id = (
                generate_entity_id()
            )

            entity_name = (
                generate_entity_name()
            )

            bank_account_id = (
                bank_account_id_map.get(
                    normalized_bank_id,
                    normalized_bank_id
                )
            )

            new_accounts_rows.append(
                {
                    "Bank Name":
                        str(
                            bank_pool.loc[
                                bank_pool[
                                    "normalized_bank_id"
                                ].astype(str)
                                ==
                                normalized_bank_id,
                                "Bank Name"
                            ].iloc[0]
                        ),

                    "Bank ID":
                        bank_account_id,

                    "Account Number":
                        account_number,

                    "Entity ID":
                        entity_id,

                    "Entity Name":
                        entity_name
                }
            )

            return account_number

    raise RuntimeError(
        "Unable to generate unique account."
    )

# ============================================================
# 7. LOAD LEGITIMATE BEHAVIOR SAMPLE
# ============================================================

print("\n" + "=" * 80)
print("5. BUILDING LEGITIMATE BEHAVIOR SAMPLE")
print("=" * 80)

sample_rows = []

chunk_size = 500_000
chunk_no = 0

for chunk in pd.read_csv(
    TRANS_PATH,
    usecols=[
        "Timestamp",
        "Amount Received",
        "Amount Paid",
        "Payment Currency",
        "Receiving Currency",
        "Payment Format",
        "Is Laundering"
    ],
    chunksize=chunk_size,
    dtype=str
):

    chunk_no += 1

    chunk[
        "Is Laundering"
    ] = pd.to_numeric(
        chunk[
            "Is Laundering"
        ],
        errors="coerce"
    ).fillna(0).astype(int)

    legit_chunk = chunk[
        chunk[
            "Is Laundering"
        ] == 0
    ].copy()

    if len(legit_chunk) == 0:
        continue

    # Take up to 10k random legitimate rows/chunk.
    n = min(
        10000,
        len(legit_chunk)
    )

    sampled = (
        legit_chunk
        .sample(
            n=n,
            random_state=SEED + chunk_no
        )
    )

    sample_rows.append(
        sampled
    )

    print(
        f"  Chunk {chunk_no} "
        f"| sampled legitimate rows = "
        f"{sum(len(x) for x in sample_rows):,}"
    )

behavior_sample = (
    pd.concat(
        sample_rows,
        ignore_index=True
    )
)

behavior_sample[
    "Timestamp"
] = pd.to_datetime(
    behavior_sample[
        "Timestamp"
    ],
    errors="coerce"
)

behavior_sample[
    "Amount Received"
] = pd.to_numeric(
    behavior_sample[
        "Amount Received"
    ],
    errors="coerce"
)

behavior_sample[
    "Amount Paid"
] = pd.to_numeric(
    behavior_sample[
        "Amount Paid"
    ],
    errors="coerce"
)

behavior_sample = (
    behavior_sample
    .dropna(
        subset=[
            "Timestamp",
            "Amount Received",
            "Amount Paid"
        ]
    )
    .copy()
)

print(
    "\nLegitimate behavior sample:",
    f"{len(behavior_sample):,}"
)

# ------------------------------------------------------------
# Global empirical samplers
# ------------------------------------------------------------

time_values = (
    behavior_sample[
        "Timestamp"
    ]
    .tolist()
)

received_amount_values = (
    behavior_sample[
        "Amount Received"
    ]
    .clip(
        lower=1e-6
    )
    .to_numpy(
        dtype=float
    )
)

payment_format_values = (
    behavior_sample[
        "Payment Format"
    ]
    .astype(str)
    .tolist()
)

payment_currency_values = (
    behavior_sample[
        "Payment Currency"
    ]
    .astype(str)
    .tolist()
)

# payment currency -> receiving currency
recv_by_pay = defaultdict(list)

for pay, recv in zip(
    behavior_sample[
        "Payment Currency"
    ].astype(str),
    behavior_sample[
        "Receiving Currency"
    ].astype(str)
):

    recv_by_pay[pay].append(
        recv
    )

# Dataset min/max
dataset_min_ts = (
    behavior_sample[
        "Timestamp"
    ].min()
)

dataset_max_ts = (
    behavior_sample[
        "Timestamp"
    ].max()
)

dataset_max_received = float(
    received_amount_values.max()
)

# ============================================================
# 8. PREPARE NODE ROLE FUNCTION
# ============================================================

def get_template_node_roles(
    template
):

    in_degree = defaultdict(int)
    out_degree = defaultdict(int)

    for edge in template["edges"]:

        s = int(
            edge["source_node"]
        )

        d = int(
            edge["destination_node"]
        )

        out_degree[s] += 1
        in_degree[d] += 1

    roles = {}

    for node in template["nodes"]:

        node_id = int(
            node["node_id"]
        )

        indeg = in_degree[
            node_id
        ]

        outdeg = out_degree[
            node_id
        ]

        if (
            indeg > 0
            and
            outdeg > 0
        ):

            role = "both"

        elif outdeg > 0:

            role = "source"

        elif indeg > 0:

            role = "destination"

        else:

            role = "both"

        roles[node_id] = role

    return roles

# ============================================================
# 9. BANK MAPPING
# ============================================================

def sample_distinct_bank(
    used_banks,
    role
):

    if role == "source":
        probs = source_bank_weights

    elif role == "destination":
        probs = destination_bank_weights

    else:
        probs = (
            source_bank_weights
            +
            destination_bank_weights
        )

        probs = (
            probs
            /
            probs.sum()
        )

    # Try weighted candidates.
    for _ in range(200):

        idx = np.random.choice(
            len(bank_pool),
            p=probs
        )

        bank = str(
            bank_pool.iloc[
                idx
            ][
                "normalized_bank_id"
            ]
        )

        if bank not in used_banks:
            return bank

    # Fallback
    candidates = [
        x for x in bank_ids
        if x not in used_banks
    ]

    if not candidates:

        raise RuntimeError(
            "Ran out of distinct banks."
        )

    return random.choice(
        candidates
    )

def map_template_banks(
    template
):

    # Determine the original bank of every node.
    node_original_bank = {}

    for tx in template[
        "transactions"
    ]:

        s = int(
            tx["source_node"]
        )

        d = int(
            tx["destination_node"]
        )

        node_original_bank.setdefault(
            s,
            str(
                template["nodes"][
                    s
                ].get(
                    "original_bank",
                    "0"
                )
            )
        )

        node_original_bank.setdefault(
            d,
            str(
                template["nodes"][
                    d
                ].get(
                    "original_bank",
                    "0"
                )
            )
        )

    # --------------------------------------------------------
    # Templates created by Cell 6 intentionally stripped
    # original node bank values from "nodes". Therefore derive
    # role-level grouping from transaction rows.
    # --------------------------------------------------------
    original_bank_by_node = {}

    for tx in template[
        "_raw_transactions_for_mapping"
    ]:
        original_bank_by_node[
            int(tx["source_node"])
        ] = str(
            tx["from_bank"]
        )

        original_bank_by_node[
            int(tx["destination_node"])
        ] = str(
            tx["to_bank"]
        )

    # --------------------------------------------------------
    # Determine source/destination presence per bank
    # --------------------------------------------------------
    bank_roles = defaultdict(set)

    for tx in template[
        "_raw_transactions_for_mapping"
    ]:

        bank_roles[
            str(tx["from_bank"])
        ].add(
            "source"
        )

        bank_roles[
            str(tx["to_bank"])
        ].add(
            "destination"
        )

    unique_original_banks = list(
        bank_roles.keys()
    )

    # Sort so role-bearing banks are deterministic.
    unique_original_banks.sort()

    mapping = {}
    used_real_banks = set()

    for original_bank in (
        unique_original_banks
    ):

        roles = bank_roles[
            original_bank
        ]

        if (
            "source" in roles
            and
            "destination" in roles
        ):
            role = "both"

        elif "source" in roles:
            role = "source"

        else:
            role = "destination"

        real_bank = sample_distinct_bank(
            used_real_banks,
            role
        )

        mapping[
            original_bank
        ] = real_bank

        used_real_banks.add(
            real_bank
        )

    # Node -> real bank
    node_bank_mapping = {}

    for node_id, original_bank in (
        original_bank_by_node.items()
    ):

        node_bank_mapping[
            int(node_id)
        ] = mapping[
            str(original_bank)
        ]

    return (
        node_bank_mapping,
        mapping
    )

# ============================================================
# 10. ACCOUNT ASSIGNMENT
# ============================================================

def get_account_from_pool(
    bank,
    role,
    used_accounts_this_episode
):

    # --------------------------------------------------------
    # Candidate role order
    # --------------------------------------------------------
    if role == "both":

        role_order = [
            "both"
        ]

    elif role == "source":

        role_order = [
            "source",
            "both"
        ]

    else:

        role_order = [
            "destination",
            "both"
        ]

    for candidate_role in role_order:

        pool = account_pool.get(
            (
                str(bank),
                candidate_role
            ),
            []
        )

        if not pool:
            continue

        start = (
            account_pool_pointer[
                (
                    str(bank),
                    candidate_role
                )
            ]
        )

        for offset in range(
            len(pool)
        ):

            idx = (
                start
                +
                offset
            ) % len(pool)

            account = pool[idx]

            if account not in (
                used_accounts_this_episode
            ):

                account_pool_pointer[
                    (
                        str(bank),
                        candidate_role
                    )
                ] = (
                    idx + 1
                ) % len(pool)

                return account, False

    # No clean original account available.
    # Create a fresh structurally realistic one.
    account = generate_new_account(
        str(bank)
    )

    return account, True

# ============================================================
# 11. TRANSACTION ID GENERATOR
# ============================================================

used_transaction_ids = set()

alphabet = (
    string.ascii_uppercase
    +
    string.digits
)

def generate_transaction_id():

    for _ in range(1000):

        value = "".join(
            random.choices(
                alphabet,
                k=16
            )
        )

        if value not in (
            used_transaction_ids
        ):

            used_transaction_ids.add(
                value
            )

            return value

    raise RuntimeError(
        "Unable to generate unique transaction ID."
    )

# ============================================================
# 12. OUTPUT BUFFERS
# ============================================================

transaction_rows = []

pattern_file = open(
    PILOT_PATTERNS_PATH,
    "w",
    encoding="utf-8"
)

used_edges = set()

episode_audit_rows = []

global_transaction_counter = 0

# ============================================================
# 13. GENERATE PILOT
# ============================================================

print("\n" + "=" * 80)
print("6. GENERATING PILOT")
print("=" * 80)

for pilot_idx, episode_row in (
    pilot_plan.iterrows()
):

    template_id = str(
        episode_row[
            "source_template_id"
        ]
    )

    template = template_lookup[
        template_id
    ]

    typology = str(
        episode_row[
            "typology"
        ]
    )

    synthetic_episode_id = str(
        episode_row[
            "synthetic_episode_id"
        ]
    )

    # --------------------------------------------------------
    # Build raw transaction structure.
    #
    # Since Cell 6 compressed node metadata, the original
    # bank/account information from the template transactions
    # is reconstructed here.
    # --------------------------------------------------------
    raw_template_transactions = []

    for tx in template[
        "transactions"
    ]:

        raw_template_transactions.append(
            {
                "source_node":
                    int(tx["source_node"]),

                "destination_node":
                    int(tx["destination_node"]),

                "from_bank":
                    str(
                        template[
                            "transactions"
                        ][
                            tx["source_order"]
                        ].get(
                            "from_bank",
                            ""
                        )
                    ),

                "to_bank":
                    str(
                        template[
                            "transactions"
                        ][
                            tx["source_order"]
                        ].get(
                            "to_bank",
                            ""
                        )
                    ),

                "source_order":
                    int(
                        tx["source_order"]
                    ),

                "relative_minutes":
                    float(
                        tx["relative_minutes"]
                    ),

                "amount_received":
                    float(
                        tx["amount_received"]
                    ),

                "amount_paid":
                    float(
                        tx["amount_paid"]
                    ),

                "payment_format":
                    str(
                        tx["payment_format"]
                    ),

                "payment_currency":
                    str(
                        tx["payment_currency"]
                    ),

                "receiving_currency":
                    str(
                        tx["receiving_currency"]
                    )
            }
        )

    # --------------------------------------------------------
    # IMPORTANT:
    # Cell 6 JSON does not retain original bank IDs inside
    # each transaction because the reusable structural template
    # intentionally stripped them.
    #
    # Instead we use the source template node IDs and create
    # a fresh bank assignment based on transaction structure.
    #
    # For the pilot, each unique template node receives a real
    # bank according to its source/destination role.
    # --------------------------------------------------------

    # Node degree
    in_degree = defaultdict(int)
    out_degree = defaultdict(int)

    for tx in template[
        "transactions"
    ]:

        s = int(
            tx["source_node"]
        )

        d = int(
            tx["destination_node"]
        )

        out_degree[s] += 1
        in_degree[d] += 1

    node_roles = {}

    for node in template[
        "nodes"
    ]:

        node_id = int(
            node["node_id"]
        )

        if (
            in_degree[node_id] > 0
            and
            out_degree[node_id] > 0
        ):

            node_roles[
                node_id
            ] = "both"

        elif out_degree[node_id] > 0:

            node_roles[
                node_id
            ] = "source"

        else:

            node_roles[
                node_id
            ] = "destination"

    # --------------------------------------------------------
    # Sample one real bank per template node.
    #
    # Distinct node banks are preserved where possible.
    # --------------------------------------------------------
    node_bank_mapping = {}

    used_banks = set()

    for node_id in sorted(
        node_roles.keys()
    ):

        real_bank = (
            sample_distinct_bank(
                used_banks,
                node_roles[node_id]
            )
        )

        node_bank_mapping[
            node_id
        ] = real_bank

        used_banks.add(
            real_bank
        )

    # --------------------------------------------------------
    # Account assignment
    # --------------------------------------------------------
    node_account_mapping = {}

    used_accounts_episode = set()

    fresh_accounts_episode = 0

    for node_id in sorted(
        node_roles.keys()
    ):

        bank = node_bank_mapping[
            node_id
        ]

        role = node_roles[
            node_id
        ]

        # Mostly reuse real eligible accounts.
        use_new = (
            np.random.random()
            <
            NEW_ACCOUNT_RATE
        )

        if use_new:

            account = (
                generate_new_account(
                    bank
                )
            )

            was_new = True

        else:

            account, was_new = (
                get_account_from_pool(
                    bank,
                    role,
                    used_accounts_episode
                )
            )

        node_account_mapping[
            node_id
        ] = account

        used_accounts_episode.add(
            account
        )

        if was_new:
            fresh_accounts_episode += 1

    # --------------------------------------------------------
    # Episode timing anchor
    # --------------------------------------------------------
    template_span = float(
        template[
            "episode_span_minutes"
        ]
    )

    anchor = random.choice(
        time_values
    )

    latest_allowed = (
        dataset_max_ts
        -
        pd.to_timedelta(
            template_span,
            unit="m"
        )
    )

    if anchor > latest_allowed:
        anchor = latest_allowed

    if anchor < dataset_min_ts:
        anchor = dataset_min_ts

    # --------------------------------------------------------
    # Target episode median amount from legitimate DNA
    # --------------------------------------------------------
    target_median_amount = float(
        np.random.choice(
            received_amount_values
        )
    )

    # Keep amount realistic.
    target_median_amount = max(
        1e-6,
        min(
            target_median_amount,
            dataset_max_received
        )
    )

    template_median = float(
        template[
            "median_amount"
        ]
    )

    if template_median <= 0:
        template_median = 1.0

    scale = (
        target_median_amount
        /
        template_median
    )

    # --------------------------------------------------------
    # Build transaction rows
    # --------------------------------------------------------
    episode_pattern_lines = []

    episode_transaction_count = 0

    episode_edge_set = set()

    episode_amounts = []

    for tx in template[
        "transactions"
    ]:

        source_node = int(
            tx["source_node"]
        )

        destination_node = int(
            tx["destination_node"]
        )

        source_bank_norm = (
            node_bank_mapping[
                source_node
            ]
        )

        dest_bank_norm = (
            node_bank_mapping[
                destination_node
            ]
        )

        source_account = (
            node_account_mapping[
                source_node
            ]
        )

        dest_account = (
            node_account_mapping[
                destination_node
            ]
        )

        # ----------------------------------------------------
        # Edge uniqueness
        # ----------------------------------------------------
        edge = (
            source_bank_norm,
            source_account,
            dest_bank_norm,
            dest_account
        )

        episode_edge_set.add(
            edge
        )

        # ----------------------------------------------------
        # Amount
        # ----------------------------------------------------
        amount_received = max(
            1e-6,
            float(
                tx[
                    "amount_received"
                ]
            )
            *
            scale
        )

        amount_paid_ratio = (
            float(
                tx["amount_paid"]
            )
            /
            max(
                float(
                    tx[
                        "amount_received"
                    ]
                ),
                1e-12
            )
        )

        amount_paid = max(
            1e-6,
            amount_received
            *
            amount_paid_ratio
        )

        # Prevent extreme overflow.
        if amount_received > dataset_max_received:

            local_scale = (
                dataset_max_received
                /
                amount_received
            )

            amount_received *= (
                local_scale
            )

            amount_paid *= (
                local_scale
            )

        # ----------------------------------------------------
        # Time
        # ----------------------------------------------------
        timestamp = (
            anchor
            +
            pd.to_timedelta(
                float(
                    tx[
                        "relative_minutes"
                    ]
                ),
                unit="m"
            )
        )

        # ----------------------------------------------------
        # Payment format from NORMAL HI-Small distribution
        # ----------------------------------------------------
        payment_format = random.choice(
            payment_format_values
        )

        payment_currency = random.choice(
            payment_currency_values
        )

        receiving_candidates = (
            recv_by_pay.get(
                payment_currency
            )
        )

        if (
            receiving_candidates
            and
            len(receiving_candidates) > 0
        ):

            receiving_currency = (
                random.choice(
                    receiving_candidates
                )
            )

        else:

            receiving_currency = (
                payment_currency
            )

        # ----------------------------------------------------
        # Bank representation in transactions
        # ----------------------------------------------------
        source_bank_tx = (
            bank_tx_id_map[
                source_bank_norm
            ]
        )

        dest_bank_tx = (
            bank_tx_id_map[
                dest_bank_norm
            ]
        )

        # ----------------------------------------------------
        # Internal synthetic transaction ID
        # ----------------------------------------------------
        transaction_id = (
            generate_transaction_id()
        )

        # ----------------------------------------------------
        # Transaction CSV row
        # ----------------------------------------------------
        transaction_rows.append(
            {
                "transaction_id":
                    transaction_id,

                "Timestamp":
                    timestamp.strftime(
                        "%Y-%m-%d %H:%M:%S"
                    ),

                "From Bank":
                    source_bank_tx,

                "Account":
                    source_account,

                "To Bank":
                    dest_bank_tx,

                "Account.1":
                    dest_account,

                "Amount Received":
                    float(
                        amount_received
                    ),

                "Receiving Currency":
                    receiving_currency,

                "Amount Paid":
                    float(
                        amount_paid
                    ),

                "Payment Currency":
                    payment_currency,

                "Payment Format":
                    payment_format,

                "Is Laundering":
                    1,

                "is_synthetic":
                    1,

                "synthetic_episode_id":
                    synthetic_episode_id,

                "typology":
                    typology,

                "source_template_id":
                    template_id,

                "template_source_order":
                    int(
                        tx[
                            "source_order"
                        ]
                    )
            }
        )

        # ----------------------------------------------------
        # Exact IBM-style Patterns.txt line
        # ----------------------------------------------------
        episode_pattern_lines.append(
            ",".join(
                [
                    timestamp.strftime(
                        "%Y/%m/%d %H:%M"
                    ),

                    source_bank_tx,

                    source_account,

                    dest_bank_tx,

                    dest_account,

                    f"{amount_received:.6f}",

                    receiving_currency,

                    f"{amount_paid:.6f}",

                    payment_currency,

                    payment_format,

                    "1"
                ]
            )
        )

        episode_transaction_count += 1
        episode_amounts.append(
            amount_received
        )

    # --------------------------------------------------------
    # Patterns.txt episode
    # --------------------------------------------------------
    pattern_file.write(
        f'id="{synthetic_episode_id}"\n'
    )

    pattern_file.write(
        f"BEGIN LAUNDERING ATTEMPT - "
        f"{typology}: "
        f"Synthetic instance based on "
        f"IBM {typology} template\n"
    )

    for line in episode_pattern_lines:

        pattern_file.write(
            line + "\n"
        )

    pattern_file.write(
        f"END LAUNDERING ATTEMPT - "
        f"{typology}\n"
    )

    # --------------------------------------------------------
    # Audit
    # --------------------------------------------------------
    episode_audit_rows.append(
        {
            "synthetic_episode_id":
                synthetic_episode_id,

            "typology":
                typology,

            "source_template_id":
                template_id,

            "transaction_count":
                episode_transaction_count,

            "node_count":
                len(
                    node_account_mapping
                ),

            "bank_count":
                len(
                    set(
                        node_bank_mapping.values()
                    )
                ),

            "fresh_account_count":
                fresh_accounts_episode,

            "unique_edges":
                len(
                    episode_edge_set
                ),

            "duplicate_edges":
                episode_transaction_count
                -
                len(
                    episode_edge_set
                ),

            "episode_span_minutes":
                template_span,

            "generated_median_amount":
                float(
                    np.median(
                        episode_amounts
                    )
                )
        }
    )

    global_transaction_counter += (
        episode_transaction_count
    )

    if (
        (pilot_idx + 1) % 500
        == 0
    ):

        print(
            f"  Episodes generated: "
            f"{pilot_idx + 1:,}"
            f" | Transactions: "
            f"{global_transaction_counter:,}"
            f" | New accounts: "
            f"{len(new_accounts_rows):,}"
        )

pattern_file.close()

# ============================================================
# 14. WRITE TRANSACTIONS
# ============================================================

print("\n" + "=" * 80)
print("7. WRITING PILOT FILES")
print("=" * 80)

pilot_transactions = pd.DataFrame(
    transaction_rows
)

pilot_audit = pd.DataFrame(
    episode_audit_rows
)

pilot_new_accounts = pd.DataFrame(
    new_accounts_rows
)

pilot_transactions.to_csv(
    PILOT_TRANS_PATH,
    index=False
)

pilot_new_accounts.to_csv(
    PILOT_ACCOUNTS_PATH,
    index=False
)

# ============================================================
# 15. GLOBAL AUDIT
# ============================================================

print("\n" + "=" * 80)
print("8. PILOT AUDIT")
print("=" * 80)

print(
    "Episodes:",
    len(pilot_audit)
)

print(
    "Transactions:",
    len(pilot_transactions)
)

print(
    "New accounts:",
    len(pilot_new_accounts)
)

print(
    "Unique transaction IDs:",
    pilot_transactions[
        "transaction_id"
    ].nunique()
)

print(
    "Transaction ID duplicates:",
    (
        len(pilot_transactions)
        -
        pilot_transactions[
            "transaction_id"
        ].nunique()
    )
)

print(
    "\nTypology transaction counts:"
)

print(
    pilot_transactions[
        "typology"
    ]
    .value_counts()
    .sort_index()
    .to_string()
)

print(
    "\nTypology episode counts:"
)

print(
    pilot_audit[
        "typology"
    ]
    .value_counts()
    .sort_index()
    .to_string()
)

# ============================================================
# 16. EDGE VALIDATION
# ============================================================

print("\n" + "=" * 80)
print("9. EDGE VALIDATION")
print("=" * 80)

print(
    "Episodes with duplicate edges:",
    int(
        (
            pilot_audit[
                "duplicate_edges"
            ]
            > 0
        ).sum()
    )
)

print(
    "Total duplicate edges inside episodes:",
    int(
        pilot_audit[
            "duplicate_edges"
        ].sum()
    )
)

global_edges = (
    pilot_transactions[
        [
            "From Bank",
            "Account",
            "To Bank",
            "Account.1"
        ]
    ]
    .astype(str)
)

global_edge_keys = (
    global_edges
    .astype(str)
    .agg(
        "|".join,
        axis=1
    )
)

print(
    "Global unique directed edges:",
    global_edge_keys.nunique()
)

print(
    "Global duplicate directed edges:",
    len(global_edge_keys)
    -
    global_edge_keys.nunique()
)

# ============================================================
# 17. ACCOUNT FORMAT VALIDATION
# ============================================================

print("\n" + "=" * 80)
print("10. ACCOUNT FORMAT VALIDATION")
print("=" * 80)

new_ids = (
    pilot_new_accounts[
        "Account Number"
    ]
    .astype(str)
)

print(
    "New account format violations:",
    int(
        ~new_ids.str.fullmatch(
            r"[A-Z0-9]{9}"
        ).sum()
    )
)

if len(new_ids) > 0:

    print(
        "New account length distribution:"
    )

    print(
        new_ids.str.len()
        .value_counts()
        .sort_index()
        .to_string()
    )

# ============================================================
# 18. BANK VALIDATION
# ============================================================

print("\n" + "=" * 80)
print("11. BANK VALIDATION")
print("=" * 80)

valid_transaction_banks = set(
    bank_pool[
        "canonical_transaction_bank_id"
    ].astype(str)
)

generated_from_banks = set(
    pilot_transactions[
        "From Bank"
    ].astype(str)
)

generated_to_banks = set(
    pilot_transactions[
        "To Bank"
    ].astype(str)
)

unknown_banks = (
    (
        generated_from_banks
        |
        generated_to_banks
    )
    -
    valid_transaction_banks
)

print(
    "Unique generated transaction banks:",
    len(
        generated_from_banks
        |
        generated_to_banks
    )
)

print(
    "Unknown generated banks:",
    len(unknown_banks)
)

# ============================================================
# 19. BEHAVIOR DISTRIBUTION
# ============================================================

print("\n" + "=" * 80)
print("12. SYNTHETIC BEHAVIOR DISTRIBUTION")
print("=" * 80)

print(
    "\nPayment Format:"
)

print(
    pilot_transactions[
        "Payment Format"
    ]
    .value_counts(
        normalize=True
    )
    .mul(100)
    .round(3)
    .to_string()
)

print(
    "\nPayment Currency:"
)

print(
    pilot_transactions[
        "Payment Currency"
    ]
    .value_counts(
        normalize=True
    )
    .mul(100)
    .round(3)
    .to_string()
)

amounts = (
    pilot_transactions[
        "Amount Received"
    ]
)

print(
    "\nGenerated Amount Received quantiles:"
)

print(
    amounts.quantile(
        [
            0.01,
            0.05,
            0.25,
            0.50,
            0.75,
            0.90,
            0.95,
            0.99
        ]
    ).to_string()
)

# ============================================================
# 20. TIMESTAMP DISTRIBUTION
# ============================================================

pilot_transactions[
    "_timestamp"
] = pd.to_datetime(
    pilot_transactions[
        "Timestamp"
    ]
)

print(
    "\nGenerated transaction hours:"
)

print(
    pilot_transactions[
        "_timestamp"
    ]
    .dt.hour
    .value_counts()
    .sort_index()
    .to_string()
)

# ============================================================
# 21. PATTERN FILE VALIDATION
# ============================================================

print("\n" + "=" * 80)
print("13. PATTERNS.TXT VALIDATION")
print("=" * 80)

with open(
    PILOT_PATTERNS_PATH,
    "r",
    encoding="utf-8"
) as f:

    pattern_lines = [
        line.rstrip("\n")
        for line in f
    ]

begin_lines = [
    x for x in pattern_lines
    if x.startswith(
        "BEGIN LAUNDERING ATTEMPT"
    )
]

end_lines = [
    x for x in pattern_lines
    if x.startswith(
        "END LAUNDERING ATTEMPT"
    )
]

id_lines = [
    x for x in pattern_lines
    if x.startswith(
        'id="'
    )
]

print(
    "Patterns file lines:",
    len(pattern_lines)
)

print(
    "ID lines:",
    len(id_lines)
)

print(
    "BEGIN lines:",
    len(begin_lines)
)

print(
    "END lines:",
    len(end_lines)
)

print(
    "Expected episodes:",
    PILOT_EPISODES
)

print(
    "Episode marker count correct:",
    (
        len(id_lines)
        ==
        PILOT_EPISODES
        and
        len(begin_lines)
        ==
        PILOT_EPISODES
        and
        len(end_lines)
        ==
        PILOT_EPISODES
    )
)

# ============================================================
# 22. SAVE MANIFEST
# ============================================================

manifest = {

    "dataset":
        "IBM HI-Small",

    "pilot_seed":
        SEED,

    "pilot_episodes":
        int(PILOT_EPISODES),

    "generated_transactions":
        int(len(pilot_transactions)),

    "new_accounts_created":
        int(len(pilot_new_accounts)),

    "new_account_rate":
        float(NEW_ACCOUNT_RATE),

    "templates_available":
        int(len(templates)),

    "templates_used":
        int(
            pilot_plan[
                "source_template_id"
            ].nunique()
        ),

    "typology_episode_counts":
        {
            str(k): int(v)
            for k, v in
            pilot_audit[
                "typology"
            ].value_counts().items()
        },

    "typology_transaction_counts":
        {
            str(k): int(v)
            for k, v in
            pilot_transactions[
                "typology"
            ].value_counts().items()
        },

    "duplicate_episode_edges":
        int(
            pilot_audit[
                "duplicate_edges"
            ].sum()
        ),

    "duplicate_global_edges":
        int(
            len(global_edge_keys)
            -
            global_edge_keys.nunique()
        ),

    "unknown_banks":
        int(len(unknown_banks)),

    "duplicate_transaction_ids":
        int(
            len(pilot_transactions)
            -
            pilot_transactions[
                "transaction_id"
            ].nunique()
        ),

    "pattern_id_lines":
        int(len(id_lines)),

    "pattern_begin_lines":
        int(len(begin_lines)),

    "pattern_end_lines":
        int(len(end_lines)),

    "outputs": {
        "transactions":
            PILOT_TRANS_PATH,

        "new_accounts":
            PILOT_ACCOUNTS_PATH,

        "patterns":
            PILOT_PATTERNS_PATH
    }
}

with open(
    PILOT_MANIFEST_PATH,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        manifest,
        f,
        indent=2
    )

# ============================================================
# 23. CLEAN HELPER COLUMN
# ============================================================

pilot_transactions.drop(
    columns=["_timestamp"],
    inplace=True
)

pilot_transactions.to_csv(
    PILOT_TRANS_PATH,
    index=False
)

# ============================================================
# 24. FINAL
# ============================================================

print("\n" + "=" * 100)
print("✅ CELL 15 COMPLETE — PILOT GENERATED")
print("=" * 100)

print(
    "\nTransactions:",
    f"{len(pilot_transactions):,}"
)

print(
    "Episodes:",
    f"{len(pilot_audit):,}"
)

print(
    "New accounts:",
    f"{len(pilot_new_accounts):,}"
)

print(
    "Templates used:",
    f"{pilot_plan['source_template_id'].nunique():,}"
)

print(
    "Duplicate transaction IDs:",
    int(
        len(pilot_transactions)
        -
        pilot_transactions[
            "transaction_id"
        ].nunique()
    )
)

print(
    "Unknown banks:",
    len(unknown_banks)
)

print(
    "Duplicate global edges:",
    int(
        len(global_edge_keys)
        -
        global_edge_keys.nunique()
    )
)

print(
    "Patterns ID/BEGIN/END correct:",
    (
        len(id_lines)
        ==
        PILOT_EPISODES
        and
        len(begin_lines)
        ==
        PILOT_EPISODES
        and
        len(end_lines)
        ==
        PILOT_EPISODES
    )
)

print("\nSaved:")
print(
    PILOT_TRANS_PATH
)
print(
    PILOT_ACCOUNTS_PATH
)
print(
    PILOT_PATTERNS_PATH
)
print(
    PILOT_MANIFEST_PATH
)

print("\nORIGINAL HI-SMALL FILES WERE NOT MODIFIED.")

print("=" * 100)

====================================================================================================
CELL 15 — 5,000-EPISODE SYNTHETIC GENERATOR PILOT
====================================================================================================

================================================================================
1. LOADING IBM TEMPLATES
================================================================================
Templates: 370
Full planned episodes: 584,706
Pilot episodes: 5000

Pilot typology distribution:
typology
BIPARTITE         662
CYCLE             729
FAN-IN            541
FAN-OUT           649
GATHER-SCATTER    689
RANDOM            554
SCATTER-GATHER    595
STACK             581

================================================================================
2. LOADING BANK POOL
================================================================================
Banks: 30470

================================================================================
3. LOADING CLEAN ACCOUNT REGISTRY
================================================================================
Eligible accounts: 508,731

================================================================================
4. LOADING ACCOUNT / ENTITY GENERATION DNA
================================================================================

================================================================================
5. BUILDING LEGITIMATE BEHAVIOR SAMPLE
================================================================================
  Chunk 1 | sampled legitimate rows = 10,000
  Chunk 2 | sampled legitimate rows = 20,000
  Chunk 3 | sampled legitimate rows = 30,000
  Chunk 4 | sampled legitimate rows = 40,000
  Chunk 5 | sampled legitimate rows = 50,000
  Chunk 6 | sampled legitimate rows = 60,000
  Chunk 7 | sampled legitimate rows = 70,000
  Chunk 8 | sampled legitimate rows = 80,000
  Chunk 9 | sampled legitimate rows = 90,000
  Chunk 10 | sampled legitimate rows = 100,000
  Chunk 11 | sampled legitimate rows = 110,000

Legitimate behavior sample: 110,000

================================================================================
6. GENERATING PILOT
================================================================================
  Episodes generated: 500 | Transactions: 4,167 | New accounts: 413
  Episodes generated: 1,000 | Transactions: 8,626 | New accounts: 819
  Episodes generated: 1,500 | Transactions: 12,878 | New accounts: 1,233
  Episodes generated: 2,000 | Transactions: 17,241 | New accounts: 1,631
  Episodes generated: 2,500 | Transactions: 21,692 | New accounts: 2,048
  Episodes generated: 3,000 | Transactions: 26,123 | New accounts: 2,471
  Episodes generated: 3,500 | Transactions: 30,275 | New accounts: 2,882
  Episodes generated: 4,000 | Transactions: 34,377 | New accounts: 3,305
  Episodes generated: 4,500 | Transactions: 38,743 | New accounts: 3,745
  Episodes generated: 5,000 | Transactions: 43,310 | New accounts: 4,185

================================================================================
7. WRITING PILOT FILES
================================================================================

================================================================================
8. PILOT AUDIT
================================================================================
Episodes: 5000
Transactions: 43310
New accounts: 4185
Unique transaction IDs: 43310
Transaction ID duplicates: 0

Typology transaction counts:
typology
BIPARTITE         3543
CYCLE             3903
FAN-IN            4212
FAN-OUT           4631
GATHER-SCATTER    9535
RANDOM            2610
SCATTER-GATHER    8470
STACK             6406

Typology episode counts:
typology
BIPARTITE         662
CYCLE             729
FAN-IN            541
FAN-OUT           649
GATHER-SCATTER    689
RANDOM            554
SCATTER-GATHER    595
STACK             581

================================================================================
9. EDGE VALIDATION
================================================================================
Episodes with duplicate edges: 0
Total duplicate edges inside episodes: 0
Global unique directed edges: 43310
Global duplicate directed edges: 0

================================================================================
10. ACCOUNT FORMAT VALIDATION
================================================================================
New account format violations: -4186
New account length distribution:
Account Number
9    4185

================================================================================
11. BANK VALIDATION
================================================================================
Unique generated transaction banks: 2973
Unknown generated banks: 0

================================================================================
12. SYNTHETIC BEHAVIOR DISTRIBUTION
================================================================================

Payment Format:
Payment Format
Cheque          36.987
Credit Card     26.036
ACH             12.193
Cash             9.838
Reinvestment     8.675
Wire             3.399
Bitcoin          2.872

Payment Currency:
Payment Currency
US Dollar            36.594
Euro                 23.009
Swiss Franc           4.950
Yuan                  4.255
Shekel                3.960
UK Pound              3.704
Rupee                 3.526
Ruble                 3.177
Yen                   3.029
Bitcoin               2.888
Canadian Dollar       2.888
Australian Dollar     2.669
Mexican Peso          2.187
Saudi Riyal           1.813
Brazil Real           1.351

Generated Amount Received quantiles:
0.01    2.795842e-02
0.05    5.112477e+00
0.25    1.612523e+02
0.50    1.704950e+03
0.75    1.957913e+04
0.90    2.674255e+05
0.95    1.291785e+06
0.99    5.727930e+07

Generated transaction hours:
_timestamp
0     2143
1     1646
2     1752
3     1796
4     1796
5     1811
6     1731
7     1926
8     1808
9     1809
10    1762
11    1805
12    1802
13    1783
14    1870
15    1846
16    1828
17    1713
18    1801
19    1949
20    1760
21    1766
22    1733
23    1674

================================================================================
13. PATTERNS.TXT VALIDATION
================================================================================
Patterns file lines: 58310
ID lines: 5000
BEGIN lines: 5000
END lines: 5000
Expected episodes: 5000
Episode marker count correct: True

====================================================================================================
✅ CELL 15 COMPLETE — PILOT GENERATED
====================================================================================================

Transactions: 43,310
Episodes: 5,000
New accounts: 4,185
Templates used: 370
Duplicate transaction IDs: 0
Unknown banks: 0
Duplicate global edges: 0
Patterns ID/BEGIN/END correct: True

Saved:
/kaggle/working/AML_GNN_ONLY/data/HI-Small_SYNTH_PILOT_transactions.csv
/kaggle/working/AML_GNN_ONLY/data/HI-Small_SYNTH_PILOT_new_accounts.csv
/kaggle/working/AML_GNN_ONLY/data/HI-Small_SYNTH_PILOT_Patterns.txt
/kaggle/working/AML_GNN_ONLY/data/HI-Small_SYNTH_PILOT_manifest.json

ORIGINAL HI-SMALL FILES WERE NOT MODIFIED.
====================================================================================================

In [22]:
# ============================================================
# CELL 16 — PILOT BANK RELATIONSHIP AUDIT
# ============================================================
#
# Purpose:
#   Audit whether synthetic From Bank -> To Bank relationships
#   are grounded in legitimate HI-Small connectivity.
#
# IMPORTANT:
#   This cell does NOT generate anything.
# ============================================================

import os
import pandas as pd
import numpy as np

WORK_DIR = "/kaggle/working/AML_GNN_ONLY/data"

PILOT_TRANS_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_SYNTH_PILOT_transactions.csv"
)

LEGIT_PAIR_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_legitimate_bank_pairs.csv"
)

BANK_POOL_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_final_generator_bank_pool.csv"
)

print("=" * 100)
print("CELL 16 — PILOT BANK RELATIONSHIP AUDIT")
print("=" * 100)

# ============================================================
# 1. LOAD PILOT
# ============================================================
pilot = pd.read_csv(
    PILOT_TRANS_PATH,
    usecols=[
        "From Bank",
        "To Bank",
        "Account",
        "Account.1",
        "typology",
        "synthetic_episode_id"
    ],
    dtype=str
)

print(
    "\nPilot transactions:",
    f"{len(pilot):,}"
)

# ============================================================
# 2. LOAD LEGITIMATE BANK PAIRS
# ============================================================
legit_pairs = pd.read_csv(
    LEGIT_PAIR_PATH,
    usecols=[
        "From Bank",
        "To Bank",
        "legitimate_count"
    ],
    dtype=str
)

legit_pairs[
    "legitimate_count"
] = pd.to_numeric(
    legit_pairs[
        "legitimate_count"
    ],
    errors="coerce"
).fillna(0).astype(int)

# Normalize representations
def normalize_bank_id(x):

    x = str(x).strip()

    try:
        return str(int(x))
    except Exception:
        return x.lstrip("0") or "0"

pilot[
    "from_norm"
] = pilot[
    "From Bank"
].map(normalize_bank_id)

pilot[
    "to_norm"
] = pilot[
    "To Bank"
].map(normalize_bank_id)

legit_pairs[
    "from_norm"
] = legit_pairs[
    "From Bank"
].map(normalize_bank_id)

legit_pairs[
    "to_norm"
] = legit_pairs[
    "To Bank"
].map(normalize_bank_id)

# ============================================================
# 3. BUILD LEGITIMATE PAIR SET
# ============================================================
legit_pair_set = set(
    zip(
        legit_pairs[
            "from_norm"
        ],
        legit_pairs[
            "to_norm"
        ]
    )
)

print(
    "\nLegitimate bank pairs:",
    f"{len(legit_pair_set):,}"
)

# ============================================================
# 4. AUDIT GENERATED PAIRS
# ============================================================
pilot_pairs = (
    pilot[
        [
            "from_norm",
            "to_norm"
        ]
    ]
    .drop_duplicates()
)

pilot_pairs[
    "legitimate_pair"
] = [
    (
        (src, dst)
        in legit_pair_set
    )
    for src, dst in zip(
        pilot_pairs[
            "from_norm"
        ],
        pilot_pairs[
            "to_norm"
        ]
    )
]

print("\n" + "=" * 80)
print("1. GLOBAL BANK-PAIR REALISM")
print("=" * 80)

print(
    "Unique generated bank pairs:",
    f"{len(pilot_pairs):,}"
)

print(
    "Generated pairs observed in legitimate HI-Small:",
    int(
        pilot_pairs[
            "legitimate_pair"
        ].sum()
    )
)

print(
    "Generated pairs NOT observed legitimately:",
    int(
        (~pilot_pairs["legitimate_pair"]).sum()
    )
)

print(
    "Pair-level legitimate coverage:",
    f"{pilot_pairs['legitimate_pair'].mean() * 100:.4f}%"
)

# Transaction-weighted coverage
transaction_pair_flags = [
    (
        (src, dst)
        in legit_pair_set
    )
    for src, dst in zip(
        pilot["from_norm"],
        pilot["to_norm"]
    )
]

print(
    "Transaction-weighted legitimate coverage:",
    f"{np.mean(transaction_pair_flags) * 100:.4f}%"
)

# ============================================================
# 5. SHOW ARTIFICIAL PAIR EXAMPLES
# ============================================================
print("\n" + "=" * 80)
print("2. ARTIFICIAL BANK-PAIR EXAMPLES")
print("=" * 80)

artificial_pairs = (
    pilot_pairs[
        ~pilot_pairs[
            "legitimate_pair"
        ]
    ]
    .head(50)
)

if len(artificial_pairs) == 0:

    print(
        "✅ No artificial bank pairs found."
    )

else:

    print(
        artificial_pairs[
            [
                "from_norm",
                "to_norm"
            ]
        ]
        .to_string(
            index=False
        )
    )

# ============================================================
# 6. BANK-PAIR COVERAGE BY TYPOLOGY
# ============================================================
print("\n" + "=" * 80)
print("3. BANK-PAIR REALISM BY TYPOLOGY")
print("=" * 80)

typology_rows = []

for typology, g in (
    pilot
    .groupby("typology")
):

    flags = [
        (
            (src, dst)
            in legit_pair_set
        )
        for src, dst in zip(
            g["from_norm"],
            g["to_norm"]
        )
    ]

    unique_g = (
        g[
            [
                "from_norm",
                "to_norm"
            ]
        ]
        .drop_duplicates()
    )

    unique_flags = [
        (
            (src, dst)
            in legit_pair_set
        )
        for src, dst in zip(
            unique_g["from_norm"],
            unique_g["to_norm"]
        )
    ]

    typology_rows.append(
        {
            "typology":
                typology,

            "transactions":
                len(g),

            "unique_bank_pairs":
                len(unique_g),

            "transaction_weighted_legit_pct":
                np.mean(flags) * 100,

            "pair_level_legit_pct":
                np.mean(unique_flags) * 100
        }
    )

typology_audit = pd.DataFrame(
    typology_rows
).sort_values(
    "typology"
)

print(
    typology_audit.to_string(
        index=False
    )
)

# ============================================================
# 7. ACCOUNT/BANK CONSISTENCY
# ============================================================
print("\n" + "=" * 80)
print("4. ACCOUNT / BANK CONSISTENCY")
print("=" * 80)

# New pilot accounts
pilot_accounts = pd.read_csv(
    os.path.join(
        WORK_DIR,
        "HI-Small_SYNTH_PILOT_new_accounts.csv"
    ),
    dtype=str
)

# Each new account should belong to the bank recorded
# in the new account registry.
#
# Build normalized account->bank map.
pilot_accounts[
    "bank_norm"
] = (
    pilot_accounts[
        "Bank ID"
    ]
    .map(normalize_bank_id)
)

account_bank_map = {
    str(row["Account Number"]):
    str(row["bank_norm"])
    for _, row in pilot_accounts.iterrows()
}

source_check = []

for _, row in pilot.iterrows():

    account = str(
        row["Account"]
    )

    if account in account_bank_map:

        source_check.append(
            account_bank_map[account]
            ==
            row["from_norm"]
        )

    else:

        source_check.append(
            True
        )

destination_check = []

for _, row in pilot.iterrows():

    account = str(
        row["Account.1"]
    )

    if account in account_bank_map:

        destination_check.append(
            account_bank_map[account]
            ==
            row["to_norm"]
        )

    else:

        destination_check.append(
            True
        )

print(
    "New-account source-bank mismatches:",
    int(
        (~np.array(source_check)).sum()
    )
)

print(
    "New-account destination-bank mismatches:",
    int(
        (~np.array(destination_check)).sum()
    )
)

# ============================================================
# 8. ACCOUNT FORMAT CORRECTED AUDIT
# ============================================================
print("\n" + "=" * 80)
print("5. ACCOUNT FORMAT AUDIT")
print("=" * 80)

if len(pilot_accounts) > 0:

    valid_mask = (
        pilot_accounts[
            "Account Number"
        ]
        .astype(str)
        .str.fullmatch(
            r"[A-Z0-9]{9}"
        )
    )

    print(
        "New accounts:",
        len(pilot_accounts)
    )

    print(
        "Valid 9-char uppercase-alphanumeric:",
        int(valid_mask.sum())
    )

    print(
        "Actual format violations:",
        int((~valid_mask).sum())
    )

# ============================================================
# 9. GLOBAL NODE / EDGE CHARACTERISTICS
# ============================================================
print("\n" + "=" * 80)
print("6. GLOBAL PILOT CHARACTERISTICS")
print("=" * 80)

print(
    "Unique source accounts:",
    pilot["Account"].nunique()
)

print(
    "Unique destination accounts:",
    pilot["Account.1"].nunique()
)

print(
    "Unique source banks:",
    pilot["from_norm"].nunique()
)

print(
    "Unique destination banks:",
    pilot["to_norm"].nunique()
)

# ============================================================
# 10. FINAL VERDICT
# ============================================================
coverage = (
    np.mean(transaction_pair_flags)
    *
    100
)

print("\n" + "=" * 100)
print("✅ CELL 16 COMPLETE")
print("=" * 100)

print(
    f"Transaction-weighted legitimate bank-pair coverage: "
    f"{coverage:.4f}%"
)

if coverage >= 99:

    print(
        "✅ Bank relationship structure is strongly grounded."
    )

elif coverage >= 90:

    print(
        "⚠️ Bank relationship structure needs improvement."
    )

else:

    print(
        "❌ Bank relationship structure is NOT suitable "
        "for final-scale generation."
    )

print(
    "\nNo synthetic data generated by this cell."
)

print(
    "No original files modified."
)

print("=" * 100)

====================================================================================================
CELL 16 — PILOT BANK RELATIONSHIP AUDIT
====================================================================================================

Pilot transactions: 43,310

Legitimate bank pairs: 283,353

================================================================================
1. GLOBAL BANK-PAIR REALISM
================================================================================
Unique generated bank pairs: 39,258
Generated pairs observed in legitimate HI-Small: 8076
Generated pairs NOT observed legitimately: 31182
Pair-level legitimate coverage: 20.5716%
Transaction-weighted legitimate coverage: 23.9806%

================================================================================
2. ARTIFICIAL BANK-PAIR EXAMPLES
================================================================================
from_norm to_norm
     1467   14838
    14838    1068
   232583   36056
    36056   30380
    30380  127977
   224449   21258
        1     210
    23833     410
    23833  232880
     1674    1655
   214621      12
       20  212789
   212789   50016
    50016  142501
   142501      12
       12      14
       14   29317
    29317   11056
   226925  240229
   240229  226925
    21611    3514
     3514     126
      126   16163
    16163    3236
     3236   22736
    22736   23525
    23525     701
    16354   19723
       16   19723
   239692   19723
   122055   19723
     1547   19723
   325787   19723
    14099   19723
    21611   19723
    28771   19723
   132499   19723
   122086   19723
       11   19723
    22828   19723
    22205  229620
   229620   27103
     1198   28317
    28317    6803
       19   23885
    23885   29467
    17769  232555
     5140  210185
   210185   28611
   210292  245064

================================================================================
3. BANK-PAIR REALISM BY TYPOLOGY
================================================================================
      typology  transactions  unique_bank_pairs  transaction_weighted_legit_pct  pair_level_legit_pct
     BIPARTITE          3543               3504                       24.809483             24.457763
         CYCLE          3903               3846                       21.701255             21.112845
        FAN-IN          4212               4154                       24.382716             23.736158
       FAN-OUT          4631               4545                       25.804362             24.818482
GATHER-SCATTER          9535               9203                       24.478238             23.166359
        RANDOM          2610               2575                       24.980843             24.349515
SCATTER-GATHER          8470               8226                       23.754427             22.623389
         STACK          6406               6305                       22.478926             21.887391

================================================================================
4. ACCOUNT / BANK CONSISTENCY
================================================================================
New-account source-bank mismatches: 2
New-account destination-bank mismatches: 3

================================================================================
5. ACCOUNT FORMAT AUDIT
================================================================================
New accounts: 4185
Valid 9-char uppercase-alphanumeric: 4185
Actual format violations: 0

================================================================================
6. GLOBAL PILOT CHARACTERISTICS
================================================================================
Unique source accounts: 31175
Unique destination accounts: 31030
Unique source banks: 2651
Unique destination banks: 2229

====================================================================================================
✅ CELL 16 COMPLETE
====================================================================================================
Transaction-weighted legitimate bank-pair coverage: 23.9806%
❌ Bank relationship structure is NOT suitable for final-scale generation.

No synthetic data generated by this cell.
No original files modified.
====================================================================================================

In [23]:
# ============================================================
# CELL 17 — LEGITIMATE-CONNECTIVITY BANK MAPPING LIBRARY
# ============================================================
#
# PURPOSE
# -------
# Fix the issue discovered in CELL 16.
#
# For every IBM pattern template:
#
#     template node A -> template node B
#
# must map to:
#
#     real bank X -> real bank Y
#
# where X -> Y EXISTS in legitimate HI-Small traffic.
#
# The graph topology of the IBM laundering template is
# preserved exactly.
#
# We create several valid mappings per template so the final
# generator can randomly select among them.
#
# NO synthetic transactions generated.
# NO synthetic accounts generated.
# ============================================================

import os
import json
import random
from collections import defaultdict, deque

import numpy as np
import pandas as pd

# ============================================================
# CONFIG
# ============================================================

SEED = 20260919

random.seed(SEED)
np.random.seed(SEED)

MAPPINGS_PER_TEMPLATE = 5

MAX_ROOT_CANDIDATES = 300

MAX_BACKTRACK_STEPS = 3000

MAX_ATTEMPTS_PER_MAPPING = 100

# ------------------------------------------------------------
# PATHS
# ------------------------------------------------------------

WORK_DIR = (
    "/kaggle/working/"
    "AML_GNN_ONLY/data"
)

TEMPLATE_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_pattern_templates.json"
)

LEGIT_PAIR_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_legitimate_bank_pairs.csv"
)

BANK_POOL_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_final_generator_bank_pool.csv"
)

OUT_JSON = os.path.join(
    WORK_DIR,
    "HI-Small_legitimate_bank_mapping_library.json"
)

OUT_SUMMARY = os.path.join(
    WORK_DIR,
    "HI-Small_legitimate_bank_mapping_summary.csv"
)

print("=" * 100)
print("CELL 17 — LEGITIMATE-CONNECTIVITY BANK MAPPING LIBRARY")
print("=" * 100)

# ============================================================
# 1. LOAD TEMPLATES
# ============================================================

with open(
    TEMPLATE_PATH,
    "r",
    encoding="utf-8"
) as f:

    template_manifest = json.load(f)

templates = template_manifest[
    "templates"
]

print(
    "\nIBM templates:",
    len(templates)
)

# ============================================================
# 2. LOAD LEGITIMATE BANK PAIRS
# ============================================================

print("\n" + "=" * 80)
print("1. LOADING LEGITIMATE BANK GRAPH")
print("=" * 80)

pairs = pd.read_csv(
    LEGIT_PAIR_PATH,
    dtype=str
)

pairs["legitimate_count"] = pd.to_numeric(
    pairs["legitimate_count"],
    errors="coerce"
).fillna(0).astype(int)

# ------------------------------------------------------------
# Normalize IDs
# ------------------------------------------------------------

def normalize_bank_id(x):

    x = str(x).strip()

    if x == "":
        return None

    try:
        return str(int(x))
    except Exception:
        return x.lstrip("0") or "0"

pairs[
    "src_norm"
] = pairs[
    "From Bank"
].map(normalize_bank_id)

pairs[
    "dst_norm"
] = pairs[
    "To Bank"
].map(normalize_bank_id)

pairs = pairs[
    pairs[
        "legitimate_count"
    ] > 0
].copy()

print(
    "Legitimate bank pairs:",
    f"{len(pairs):,}"
)

# ============================================================
# 3. BUILD ADJACENCY STRUCTURES
# ============================================================

print("\n" + "=" * 80)
print("2. BUILDING LEGITIMATE BANK GRAPH")
print("=" * 80)

out_neighbors = defaultdict(dict)
in_neighbors = defaultdict(dict)

for _, row in pairs.iterrows():

    src = str(
        row["src_norm"]
    )

    dst = str(
        row["dst_norm"]
    )

    weight = int(
        row["legitimate_count"]
    )

    out_neighbors[src][dst] = weight

    in_neighbors[dst][src] = weight

# ------------------------------------------------------------
# Sets for fast constraint checks
# ------------------------------------------------------------

out_neighbor_sets = {
    src: set(
        neighbors.keys()
    )
    for src, neighbors
    in out_neighbors.items()
}

in_neighbor_sets = {
    dst: set(
        neighbors.keys()
    )
    for dst, neighbors
    in in_neighbors.items()
}

all_banks = sorted(
    set(
        out_neighbors.keys()
    )
    |
    set(
        in_neighbors.keys()
    )
)

print(
    "Banks in legitimate graph:",
    len(all_banks)
)

print(
    "Banks with outgoing legitimate edges:",
    len(out_neighbors)
)

print(
    "Banks with incoming legitimate edges:",
    len(in_neighbors)
)

# ============================================================
# 4. LOAD BANK ACTIVITY WEIGHTS
# ============================================================

bank_pool = pd.read_csv(
    BANK_POOL_PATH,
    dtype=str
)

for col in [
    "legitimate_source_transactions",
    "legitimate_destination_transactions"
]:

    bank_pool[col] = pd.to_numeric(
        bank_pool[col],
        errors="coerce"
    ).fillna(0)

bank_activity = {}

for _, row in bank_pool.iterrows():

    bank = str(
        row["normalized_bank_id"]
    )

    bank_activity[
        bank
    ] = {

        "source_activity":
            float(
                row[
                    "legitimate_source_transactions"
                ]
            ),

        "destination_activity":
            float(
                row[
                    "legitimate_destination_transactions"
                ]
            )
    }

# ============================================================
# 5. BANK DEGREE DATA
# ============================================================

bank_out_degree = {
    bank: len(
        out_neighbor_sets.get(
            bank,
            set()
        )
    )
    for bank in all_banks
}

bank_in_degree = {
    bank: len(
        in_neighbor_sets.get(
            bank,
            set()
        )
    )
    for bank in all_banks
}

# ============================================================
# 6. TEMPLATE GRAPH HELPERS
# ============================================================

def build_template_graph(
    template
):

    nodes = set()

    adjacency = defaultdict(set)

    reverse = defaultdict(set)

    edge_list = []

    for edge in template[
        "edges"
    ]:

        s = int(
            edge["source_node"]
        )

        d = int(
            edge["destination_node"]
        )

        nodes.add(s)
        nodes.add(d)

        adjacency[s].add(d)

        reverse[d].add(s)

        edge_list.append(
            (
                s,
                d
            )
        )

    # Preserve isolated nodes if any
    for node in template[
        "nodes"
    ]:

        nodes.add(
            int(
                node["node_id"]
            )
        )

    return (
        sorted(nodes),
        adjacency,
        reverse,
        edge_list
    )


def node_degrees(
    node,
    adjacency,
    reverse
):

    return (
        len(
            adjacency.get(
                node,
                set()
            )
        ),
        len(
            reverse.get(
                node,
                set()
            )
        )
    )


def connected_components(
    nodes,
    adjacency,
    reverse
):

    seen = set()
    components = []

    for start in nodes:

        if start in seen:
            continue

        q = deque(
            [start]
        )

        seen.add(start)

        component = []

        while q:

            u = q.popleft()

            component.append(u)

            neighbors = (
                adjacency.get(
                    u,
                    set()
                )
                |
                reverse.get(
                    u,
                    set()
                )
            )

            for v in neighbors:

                if v not in seen:

                    seen.add(v)
                    q.append(v)

        components.append(
            sorted(component)
        )

    return components

# ============================================================
# 7. CANDIDATE BANK FUNCTIONS
# ============================================================

def base_bank_score(
    bank,
    role,
    required_out=0,
    required_in=0
):

    bank = str(bank)

    out_deg = bank_out_degree.get(
        bank,
        0
    )

    in_deg = bank_in_degree.get(
        bank,
        0
    )

    if (
        out_deg < required_out
        or
        in_deg < required_in
    ):
        return 0.0

    activity = bank_activity.get(
        bank,
        {}
    )

    if role == "source":

        score = (
            activity.get(
                "source_activity",
                0.0
            )
            +
            1.0
        )

    elif role == "destination":

        score = (
            activity.get(
                "destination_activity",
                0.0
            )
            +
            1.0
        )

    else:

        score = (
            activity.get(
                "source_activity",
                0.0
            )
            +
            activity.get(
                "destination_activity",
                0.0
            )
            +
            1.0
        )

    # Mild degree boost.
    score *= (
        1.0
        +
        0.02
        *
        (
            out_deg
            +
            in_deg
        )
    )

    return float(
        score
    )


def weighted_sample_one(
    candidates,
    role,
    required_out=0,
    required_in=0
):

    if not candidates:
        return None

    scored = []

    for bank in candidates:

        score = base_bank_score(
            bank,
            role,
            required_out,
            required_in
        )

        if score > 0:

            scored.append(
                (
                    str(bank),
                    score
                )
            )

    if not scored:
        return None

    banks = [
        x[0]
        for x in scored
    ]

    scores = np.array(
        [
            x[1]
            for x in scored
        ],
        dtype=float
    )

    # Compress enormous bank-activity differences.
    scores = np.sqrt(
        scores
    )

    scores /= scores.sum()

    return str(
        np.random.choice(
            banks,
            p=scores
        )
    )

# ============================================================
# 8. NODE ROLE
# ============================================================

def get_node_role(
    node,
    adjacency,
    reverse
):

    out_deg = len(
        adjacency.get(
            node,
            set()
        )
    )

    in_deg = len(
        reverse.get(
            node,
            set()
        )
    )

    if (
        in_deg > 0
        and
        out_deg > 0
    ):
        return "both"

    if out_deg > 0:
        return "source"

    if in_deg > 0:
        return "destination"

    return "both"

# ============================================================
# 9. GENERATE ONE VALID BANK MAPPING
# ============================================================

def generate_mapping(
    template,
    mapping_index
):

    (
        nodes,
        adjacency,
        reverse,
        edge_list
    ) = build_template_graph(
        template
    )

    # --------------------------------------------------------
    # Handle empty graph
    # --------------------------------------------------------
    if not nodes:

        return {}

    # --------------------------------------------------------
    # Components
    # --------------------------------------------------------
    components = connected_components(
        nodes,
        adjacency,
        reverse
    )

    mapping = {}

    used_banks = set()

    # --------------------------------------------------------
    # Process each component independently.
    # --------------------------------------------------------
    for component in components:

        if len(component) == 1:

            node = component[0]

            role = get_node_role(
                node,
                adjacency,
                reverse
            )

            candidates = [
                bank
                for bank in all_banks
                if (
                    base_bank_score(
                        bank,
                        role
                    ) > 0
                )
            ]

            selected = weighted_sample_one(
                candidates,
                role
            )

            if selected is None:
                return None

            mapping[node] = selected
            used_banks.add(selected)

            continue

        # ----------------------------------------------------
        # Node ordering:
        # high degree first.
        # ----------------------------------------------------
        component_order = sorted(
            component,
            key=lambda n: (
                -(
                    len(
                        adjacency.get(
                            n,
                            set()
                        )
                    )
                    +
                    len(
                        reverse.get(
                            n,
                            set()
                        )
                    )
                ),
                -len(
                    adjacency.get(
                        n,
                        set()
                    )
                ),
                n
            )
        )

        # ----------------------------------------------------
        # Root selection
        # ----------------------------------------------------
        root = component_order[0]

        root_role = get_node_role(
            root,
            adjacency,
            reverse
        )

        required_out = len(
            adjacency.get(
                root,
                set()
            )
        )

        required_in = len(
            reverse.get(
                root,
                set()
            )
        )

        # Candidate banks that have enough observed
        # neighbors for the root's branching structure.
        root_candidates = []

        for bank in all_banks:

            if bank_out_degree.get(
                bank,
                0
            ) < required_out:
                continue

            if bank_in_degree.get(
                bank,
                0
            ) < required_in:
                continue

            score = base_bank_score(
                bank,
                root_role,
                required_out,
                required_in
            )

            if score > 0:
                root_candidates.append(
                    (
                        bank,
                        score
                    )
                )

        if not root_candidates:
            return None

        root_candidates = sorted(
            root_candidates,
            key=lambda x: x[1],
            reverse=True
        )

        # Keep a diverse but manageable root candidate set.
        if len(root_candidates) > MAX_ROOT_CANDIDATES:

            # Probabilistic selection later.
            root_candidates = root_candidates[
                :MAX_ROOT_CANDIDATES
            ]

        # Shuffle root order weighted by activity.
        root_banks = [
            x[0]
            for x in root_candidates
        ]

        root_scores = np.array(
            [
                x[1]
                for x in root_candidates
            ],
            dtype=float
        )

        root_scores = np.sqrt(
            root_scores
        )

        root_scores /= (
            root_scores.sum()
        )

        root_order = list(
            np.random.choice(
                root_banks,
                size=min(
                    30,
                    len(root_banks)
                ),
                replace=False,
                p=root_scores
            )
        )

        found_component = False

        # ----------------------------------------------------
        # Try multiple roots
        # ----------------------------------------------------
        for root_bank in root_order:

            local_mapping = {
                root: str(
                    root_bank
                )
            }

            local_used = {
                str(root_bank)
            }

            # ------------------------------------------------
            # Backtracking search
            # ------------------------------------------------
            backtrack_counter = [0]

            def choose_next_node():

                unassigned = [
                    n for n in component
                    if n not in local_mapping
                ]

                if not unassigned:
                    return None

                # MRV:
                # choose node with most constraints first.
                best_node = None
                best_key = None

                for n in unassigned:

                    assigned_neighbors = (
                        (
                            adjacency.get(
                                n,
                                set()
                            )
                            |
                            reverse.get(
                                n,
                                set()
                            )
                        )
                        &
                        set(
                            local_mapping.keys()
                        )
                    )

                    key = (
                        len(
                            assigned_neighbors
                        ),
                        len(
                            adjacency.get(
                                n,
                                set()
                            )
                        )
                        +
                        len(
                            reverse.get(
                                n,
                                set()
                            )
                        )
                    )

                    if (
                        best_key is None
                        or
                        key > best_key
                    ):

                        best_key = key
                        best_node = n

                return best_node

            def candidate_banks(
                node
            ):

                role = get_node_role(
                    node,
                    adjacency,
                    reverse
                )

                candidates = None

                # --------------------------------------------
                # Incoming constraints:
                #
                # assigned predecessor P
                # requires:
                #
                #   P_bank -> candidate_bank
                # --------------------------------------------
                for predecessor in (
                    reverse.get(
                        node,
                        set()
                    )
                ):

                    if predecessor not in (
                        local_mapping
                    ):
                        continue

                    pred_bank = local_mapping[
                        predecessor
                    ]

                    valid = (
                        out_neighbor_sets
                        .get(
                            pred_bank,
                            set()
                        )
                    )

                    if candidates is None:
                        candidates = set(valid)
                    else:
                        candidates &= valid

                    if not candidates:
                        return []

                # --------------------------------------------
                # Outgoing constraints:
                #
                # candidate_bank -> assigned successor
                # --------------------------------------------
                for successor in (
                    adjacency.get(
                        node,
                        set()
                    )
                ):

                    if successor not in (
                        local_mapping
                    ):
                        continue

                    succ_bank = local_mapping[
                        successor
                    ]

                    valid = (
                        in_neighbor_sets
                        .get(
                            succ_bank,
                            set()
                        )
                    )

                    if candidates is None:
                        candidates = set(valid)
                    else:
                        candidates &= valid

                    if not candidates:
                        return []

                # --------------------------------------------
                # If no assigned neighbor constraint exists,
                # use global banks.
                # --------------------------------------------
                if candidates is None:

                    required_out_local = len(
                        adjacency.get(
                            node,
                            set()
                        )
                    )

                    required_in_local = len(
                        reverse.get(
                            node,
                            set()
                        )
                    )

                    candidates = {
                        bank
                        for bank in all_banks
                        if (
                            bank_out_degree.get(
                                bank,
                                0
                            )
                            >=
                            required_out_local
                            and
                            bank_in_degree.get(
                                bank,
                                0
                            )
                            >=
                            required_in_local
                        )
                    }

                # --------------------------------------------
                # Prefer unused banks where possible.
                # But DO NOT force uniqueness if that would
                # make the graph impossible.
                # --------------------------------------------
                unused_candidates = (
                    candidates
                    -
                    local_used
                )

                if unused_candidates:
                    candidates = (
                        unused_candidates
                    )

                # --------------------------------------------
                # Ensure node's role has activity support.
                # --------------------------------------------
                scored = []

                required_out_local = len(
                    adjacency.get(
                        node,
                        set()
                    )
                )

                required_in_local = len(
                    reverse.get(
                        node,
                        set()
                    )
                )

                for bank in candidates:

                    score = base_bank_score(
                        bank,
                        role,
                        required_out_local,
                        required_in_local
                    )

                    if score <= 0:
                        continue

                    # Add local connectivity score.
                    local_score = 1.0

                    for predecessor in (
                        reverse.get(
                            node,
                            set()
                        )
                    ):

                        if predecessor in local_mapping:

                            pred_bank = local_mapping[
                                predecessor
                            ]

                            local_score *= max(
                                1.0,
                                float(
                                    out_neighbors[
                                        pred_bank
                                    ].get(
                                        bank,
                                        0
                                    )
                                )
                            )

                    for successor in (
                        adjacency.get(
                            node,
                            set()
                        )
                    ):

                        if successor in local_mapping:

                            succ_bank = local_mapping[
                                successor
                            ]

                            local_score *= max(
                                1.0,
                                float(
                                    in_neighbors[
                                        succ_bank
                                    ].get(
                                        bank,
                                        0
                                    )
                                )
                            )

                    score *= (
                        np.sqrt(
                            local_score
                        )
                    )

                    scored.append(
                        (
                            str(bank),
                            score
                        )
                    )

                if not scored:
                    return []

                # Weighted random ordering.
                banks = [
                    x[0]
                    for x in scored
                ]

                scores = np.array(
                    [
                        x[1]
                        for x in scored
                    ],
                    dtype=float
                )

                scores = np.sqrt(
                    scores
                )

                scores /= (
                    scores.sum()
                )

                order_count = min(
                    40,
                    len(banks)
                )

                return list(
                    np.random.choice(
                        banks,
                        size=order_count,
                        replace=False,
                        p=scores
                    )
                )

            def search():

                if (
                    len(local_mapping)
                    ==
                    len(component)
                ):
                    return True

                backtrack_counter[0] += 1

                if (
                    backtrack_counter[0]
                    >
                    MAX_BACKTRACK_STEPS
                ):
                    return False

                node = choose_next_node()

                if node is None:
                    return True

                candidates = candidate_banks(
                    node
                )

                if not candidates:
                    return False

                for bank in candidates:

                    # Check every currently satisfied edge
                    # explicitly before committing.
                    valid = True

                    for predecessor in (
                        reverse.get(
                            node,
                            set()
                        )
                    ):

                        if predecessor in local_mapping:

                            pred_bank = local_mapping[
                                predecessor
                            ]

                            if bank not in (
                                out_neighbor_sets
                                .get(
                                    pred_bank,
                                    set()
                                )
                            ):

                                valid = False
                                break

                    if not valid:
                        continue

                    for successor in (
                        adjacency.get(
                            node,
                            set()
                        )
                    ):

                        if successor in local_mapping:

                            succ_bank = local_mapping[
                                successor
                            ]

                            if bank not in (
                                in_neighbor_sets
                                .get(
                                    succ_bank,
                                    set()
                                )
                            ):

                                valid = False
                                break

                    if not valid:
                        continue

                    local_mapping[
                        node
                    ] = bank

                    local_used.add(
                        bank
                    )

                    if search():
                        return True

                    local_used.discard(
                        bank
                    )

                    del local_mapping[
                        node
                    ]

                return False

            if search():

                mapping.update(
                    local_mapping
                )

                used_banks.update(
                    local_mapping.values()
                )

                found_component = True
                break

        if not found_component:
            return None

    # ========================================================
    # FINAL EDGE CHECK
    # ========================================================
    for source_node, dest_node in edge_list:

        source_bank = mapping[
            source_node
        ]

        dest_bank = mapping[
            dest_node
        ]

        if dest_bank not in (
            out_neighbor_sets.get(
                source_bank,
                set()
            )
        ):

            return None

    return mapping

# ============================================================
# 10. BUILD MAPPING LIBRARY
# ============================================================

print("\n" + "=" * 80)
print("3. GENERATING VALID BANK MAPPINGS")
print("=" * 80)

mapping_library = {}
summary_rows = []

total_successful = 0

for template_idx, template in enumerate(
    templates,
    start=1
):

    template_id = str(
        template["template_id"]
    )

    typology = str(
        template["typology"]
    )

    target_mappings = []

    attempted = 0

    while (
        len(target_mappings)
        <
        MAPPINGS_PER_TEMPLATE
        and
        attempted
        <
        (
            MAPPINGS_PER_TEMPLATE
            *
            MAX_ATTEMPTS_PER_MAPPING
        )
    ):

        attempted += 1

        mapping = generate_mapping(
            template,
            len(target_mappings)
        )

        if mapping is None:
            continue

        # ----------------------------------------------------
        # Canonical mapping representation
        # ----------------------------------------------------
        mapping_tuple = tuple(
            (
                int(node),
                str(bank)
            )
            for node, bank
            in sorted(
                mapping.items()
            )
        )

        # Avoid duplicate mappings.
        existing = {
            tuple(
                (
                    int(n),
                    str(b)
                )
                for n, b
                in sorted(
                    m.items()
                )
            )
            for m in target_mappings
        }

        if mapping_tuple in existing:
            continue

        target_mappings.append(
            mapping
        )

    mapping_library[
        template_id
    ] = target_mappings

    success = len(
        target_mappings
    )

    total_successful += success

    summary_rows.append(
        {
            "template_id":
                template_id,

            "typology":
                typology,

            "template_nodes":
                int(
                    template["node_count"]
                ),

            "template_edges":
                int(
                    len(
                        template["edges"]
                    )
                ),

            "mappings_required":
                int(
                    MAPPINGS_PER_TEMPLATE
                ),

            "mappings_generated":
                int(
                    success
                ),

            "complete":
                bool(
                    success
                    >=
                    MAPPINGS_PER_TEMPLATE
                ),

            "unique_banks_example":
                int(
                    len(
                        set(
                            target_mappings[0].values()
                        )
                    )
                )
                if target_mappings
                else 0
        }
    )

    if (
        template_idx % 25
        == 0
    ):

        print(
            f"Templates processed: "
            f"{template_idx:,}/{len(templates):,}"
            f" | "
            f"valid mappings stored: "
            f"{total_successful:,}"
        )

# ============================================================
# 11. SUMMARY
# ============================================================

summary_df = pd.DataFrame(
    summary_rows
)

print("\n" + "=" * 80)
print("4. MAPPING LIBRARY SUMMARY")
print("=" * 80)

print(
    summary_df[
        [
            "typology",
            "mappings_generated",
            "complete"
        ]
    ]
    .groupby("typology")
    .agg(
        templates=(
            "mappings_generated",
            "count"
        ),

        min_mappings=(
            "mappings_generated",
            "min"
        ),

        median_mappings=(
            "mappings_generated",
            "median"
        ),

        complete_templates=(
            "complete",
            "sum"
        )
    )
    .to_string()
)

print(
    "\nTemplates with 5 valid mappings:",
    int(
        summary_df[
            "complete"
        ].sum()
    ),
        "/",
    len(summary_df)
)

print(
    "Total valid mappings:",
    total_successful
)

# ============================================================
# 12. CHECK ALL EDGES IN ALL MAPPINGS
# ============================================================

print("\n" + "=" * 80)
print("5. FINAL EDGE VALIDATION")
print("=" * 80)

total_checked_edges = 0
invalid_edges = 0

for template in templates:

    template_id = str(
        template["template_id"]
    )

    mappings = mapping_library[
        template_id
    ]

    for mapping in mappings:

        for edge in template[
            "edges"
        ]:

            source_bank = mapping[
                int(
                    edge["source_node"]
                )
            ]

            dest_bank = mapping[
                int(
                    edge["destination_node"]
                )
            ]

            total_checked_edges += 1

            if dest_bank not in (
                out_neighbor_sets.get(
                    source_bank,
                    set()
                )
            ):

                invalid_edges += 1

print(
    "Edges checked:",
    f"{total_checked_edges:,}"
)

print(
    "Invalid edges:",
    invalid_edges
)

print(
    "Legitimate edge coverage:",
    (
        100.0
        if total_checked_edges == 0
        else
        (
            1
            -
            invalid_edges
            /
            total_checked_edges
        )
        *
        100
    )
)

# ============================================================
# 13. BANK-COUNT DISTRIBUTION
# ============================================================

print("\n" + "=" * 80)
print("6. UNIQUE BANK COUNT OF GENERATED MAPPINGS")
print("=" * 80)

bank_count_rows = []

for template in templates:

    template_id = str(
        template["template_id"]
    )

    typology = str(
        template["typology"]
    )

    for mapping in mapping_library[
        template_id
    ]:

        bank_count_rows.append(
            {
                "template_id":
                    template_id,

                "typology":
                    typology,

                "nodes":
                    len(mapping),

                "unique_banks":
                    len(
                        set(
                            mapping.values()
                        )
                    )
            }
        )

bank_count_df = pd.DataFrame(
    bank_count_rows
)

print(
    bank_count_df
    .groupby("typology")[
        "unique_banks"
    ]
    .describe()
    .round(3)
    .to_string()
)

# ============================================================
# 14. SAVE SUMMARY
# ============================================================

summary_df.to_csv(
    OUT_SUMMARY,
    index=False
)

# ============================================================
# 15. SAVE JSON
# ============================================================

serializable_library = {}

for template_id, mappings in (
    mapping_library.items()
):

    serializable_library[
        str(template_id)
    ] = [

        {
            str(node):
                str(bank)

            for node, bank
            in mapping.items()
        }

        for mapping in mappings
    ]

manifest = {

    "dataset":
        "IBM HI-Small",

    "purpose":
        "Reusable bank-node mappings constrained to "
        "legitimate HI-Small bank connectivity",

    "seed":
        SEED,

    "mappings_per_template_requested":
        MAPPINGS_PER_TEMPLATE,

    "template_count":
        len(templates),

    "templates_with_complete_mapping_library":
        int(
            summary_df[
                "complete"
            ].sum()
        ),

    "total_valid_mappings":
        int(total_successful),

    "legitimate_edge_coverage_pct":
        (
            100.0
            if total_checked_edges == 0
            else
            (
                1
                -
                invalid_edges
                /
                total_checked_edges
            )
            *
            100
        ),

    "mappings":
        serializable_library
}

with open(
    OUT_JSON,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        manifest,
        f,
        indent=2
    )

# ============================================================
# 16. FINAL
# ============================================================

print("\n" + "=" * 100)
print("✅ CELL 17 COMPLETE")
print("=" * 100)

print(
    "Templates:",
    len(templates)
)

print(
    "Templates with complete mapping sets:",
    int(
        summary_df[
            "complete"
        ].sum()
    )
)

print(
    "Required mappings/template:",
    MAPPINGS_PER_TEMPLATE
)

print(
    "Total valid mappings:",
    total_successful
)

print(
    "Invalid mapped edges:",
    invalid_edges
)

print(
    "Legitimate edge coverage:",
    (
        100.0
        if total_checked_edges == 0
        else
        (
            1
            -
            invalid_edges
            /
            total_checked_edges
        )
        *
        100
    ),
    "%"
)

print("\nSaved:")
print(
    OUT_JSON
)

print(
    OUT_SUMMARY
)

print("\nNO SYNTHETIC TRANSACTIONS CREATED.")
print("NO SYNTHETIC ACCOUNTS CREATED.")
print("NO ORIGINAL FILE MODIFIED.")

print("=" * 100)

====================================================================================================
CELL 17 — LEGITIMATE-CONNECTIVITY BANK MAPPING LIBRARY
====================================================================================================

IBM templates: 370

================================================================================
1. LOADING LEGITIMATE BANK GRAPH
================================================================================
Legitimate bank pairs: 281,474

================================================================================
2. BUILDING LEGITIMATE BANK GRAPH
================================================================================
Banks in legitimate graph: 30470
Banks with outgoing legitimate edges: 30470
Banks with incoming legitimate edges: 15811

================================================================================
3. GENERATING VALID BANK MAPPINGS
================================================================================
Templates processed: 25/370 | valid mappings stored: 125
Templates processed: 50/370 | valid mappings stored: 250
Templates processed: 75/370 | valid mappings stored: 375
Templates processed: 100/370 | valid mappings stored: 500
Templates processed: 125/370 | valid mappings stored: 625
Templates processed: 150/370 | valid mappings stored: 750
Templates processed: 175/370 | valid mappings stored: 875
Templates processed: 200/370 | valid mappings stored: 1,000
Templates processed: 225/370 | valid mappings stored: 1,125
Templates processed: 250/370 | valid mappings stored: 1,250
Templates processed: 275/370 | valid mappings stored: 1,375
Templates processed: 300/370 | valid mappings stored: 1,500
Templates processed: 325/370 | valid mappings stored: 1,625
Templates processed: 350/370 | valid mappings stored: 1,750

================================================================================
4. MAPPING LIBRARY SUMMARY
================================================================================
                templates  min_mappings  median_mappings  complete_templates
typology
BIPARTITE              49             5              5.0                  49
CYCLE                  54             5              5.0                  54
FAN-IN                 40             5              5.0                  40
FAN-OUT                48             5              5.0                  48
GATHER-SCATTER         51             5              5.0                  51
RANDOM                 41             5              5.0                  41
SCATTER-GATHER         44             5              5.0                  44
STACK                  43             5              5.0                  43

Templates with 5 valid mappings: 370 / 370
Total valid mappings: 1850

================================================================================
5. FINAL EDGE VALIDATION
================================================================================
Edges checked: 16,045
Invalid edges: 0
Legitimate edge coverage: 100.0

================================================================================
6. UNIQUE BANK COUNT OF GENERATED MAPPINGS
================================================================================
                count    mean     std  min   25%   50%   75%   max
typology
BIPARTITE       245.0  10.396   8.546  2.0  2.00   8.0  17.0  29.0
CYCLE           270.0   5.307   3.237  2.0  2.00   4.0   8.0  12.0
FAN-IN          200.0   8.950   5.131  2.0  4.00   9.0  14.0  17.0
FAN-OUT         240.0   8.125   5.149  2.0  3.00   8.0  13.0  17.0
GATHER-SCATTER  255.0  14.333   9.511  2.0  4.00  15.0  23.0  29.0
RANDOM          205.0   5.659   3.533  2.0  2.00   4.0   9.0  12.0
SCATTER-GATHER  220.0   8.564   5.531  2.0  2.75   8.0  15.0  18.0
STACK           215.0  14.656  12.373  2.0  2.00  15.0  22.0  44.0

====================================================================================================
✅ CELL 17 COMPLETE
====================================================================================================
Templates: 370
Templates with complete mapping sets: 370
Required mappings/template: 5
Total valid mappings: 1850
Invalid mapped edges: 0
Legitimate edge coverage: 100.0 %

Saved:
/kaggle/working/AML_GNN_ONLY/data/HI-Small_legitimate_bank_mapping_library.json
/kaggle/working/AML_GNN_ONLY/data/HI-Small_legitimate_bank_mapping_summary.csv

NO SYNTHETIC TRANSACTIONS CREATED.
NO SYNTHETIC ACCOUNTS CREATED.
NO ORIGINAL FILE MODIFIED.
====================================================================================================

In [24]:
# ============================================================
# CELL 18 — CONNECTIVITY-CONSTRAINED SYNTHETIC PILOT V2
# ============================================================
#
# Rebuild the 5,000-episode pilot using CELL 17 mappings.
#
# CRITICAL DIFFERENCE FROM CELL 15:
#
#   Cell 15:
#       template node -> independently sampled bank
#
#   Cell 18:
#       template node -> bank from CELL 17
#       where EVERY template edge maps to a legitimate
#       HI-Small bank relationship.
#
# ============================================================

import os
import json
import random
import string
from collections import defaultdict

import numpy as np
import pandas as pd

# ============================================================
# CONFIG
# ============================================================

SEED = 20260919

random.seed(SEED)
np.random.seed(SEED)

PILOT_EPISODES = 5000

# New accounts are generated only for a small fraction of
# template nodes.
NEW_ACCOUNT_RATE = 0.05

# ============================================================
# PATHS
# ============================================================

DATA_ROOT = (
    "/kaggle/input/datasets/"
    "ealtman2019/ibm-transactions-for-anti-money-laundering-aml"
)

WORK_DIR = (
    "/kaggle/working/"
    "AML_GNN_ONLY/data"
)

TRANS_PATH = os.path.join(
    DATA_ROOT,
    "HI-Small_Trans.csv"
)

ACCOUNTS_PATH = os.path.join(
    DATA_ROOT,
    "HI-Small_accounts.csv"
)

TEMPLATE_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_pattern_templates.json"
)

EPISODE_PLAN_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_synthetic_episode_plan.csv"
)

BANK_POOL_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_final_generator_bank_pool.csv"
)

ACCOUNT_REGISTRY_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_generator_account_registry.csv"
)

ACCOUNT_PREFIX_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_bank_account_prefix_sampler.json"
)

ACCOUNT_GENERATOR_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_account_id_generator.json"
)

ENTITY_DNA_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_entity_name_dna.json"
)

MAPPING_LIBRARY_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_legitimate_bank_mapping_library.json"
)

# ------------------------------------------------------------
# OUTPUTS — V2
# ------------------------------------------------------------

OUT_TRANS = os.path.join(
    WORK_DIR,
    "HI-Small_SYNTH_PILOT_V2_transactions.csv"
)

OUT_ACCOUNTS = os.path.join(
    WORK_DIR,
    "HI-Small_SYNTH_PILOT_V2_new_accounts.csv"
)

OUT_PATTERNS = os.path.join(
    WORK_DIR,
    "HI-Small_SYNTH_PILOT_V2_Patterns.txt"
)

OUT_MANIFEST = os.path.join(
    WORK_DIR,
    "HI-Small_SYNTH_PILOT_V2_manifest.json"
)

OUT_AUDIT = os.path.join(
    WORK_DIR,
    "HI-Small_SYNTH_PILOT_V2_episode_audit.csv"
)

print("=" * 100)
print("CELL 18 — CONNECTIVITY-CONSTRAINED SYNTHETIC PILOT V2")
print("=" * 100)

# ============================================================
# 1. LOAD TEMPLATES
# ============================================================

print("\n" + "=" * 80)
print("1. LOADING TEMPLATES")
print("=" * 80)

with open(
    TEMPLATE_PATH,
    "r",
    encoding="utf-8"
) as f:

    template_manifest = json.load(f)

templates = template_manifest[
    "templates"
]

template_lookup = {
    str(t["template_id"]): t
    for t in templates
}

print(
    "IBM templates:",
    len(templates)
)

# ============================================================
# 2. LOAD EPISODE PLAN
# ============================================================

episode_plan = pd.read_csv(
    EPISODE_PLAN_PATH,
    dtype=str
)

episode_plan[
    "transaction_count"
] = pd.to_numeric(
    episode_plan[
        "transaction_count"
    ],
    errors="raise"
)

# ------------------------------------------------------------
# Stratified pilot
# ------------------------------------------------------------

type_counts = (
    episode_plan[
        "typology"
    ]
    .value_counts()
    .sort_index()
)

pilot_raw = (
    type_counts
    /
    type_counts.sum()
    *
    PILOT_EPISODES
)

pilot_counts = np.floor(
    pilot_raw
).astype(int)

remaining = (
    PILOT_EPISODES
    -
    int(pilot_counts.sum())
)

fractions = (
    pilot_raw
    -
    pilot_counts
)

for typology in (
    fractions
    .sort_values(
        ascending=False
    )
    .head(remaining)
    .index
):

    pilot_counts.loc[
        typology
    ] += 1

pilot_parts = []

for typology, count in (
    pilot_counts.items()
):

    subset = episode_plan[
        episode_plan[
            "typology"
        ]
        ==
        typology
    ]

    pilot_parts.append(
        subset.sample(
            n=int(count),
            random_state=(
                SEED
                +
                sum(
                    ord(c)
                    for c in typology
                )
            )
        )
    )

pilot_plan = (
    pd.concat(
        pilot_parts,
        ignore_index=True
    )
    .sample(
        frac=1,
        random_state=SEED
    )
    .reset_index(drop=True)
)

pilot_plan[
    "pilot_episode_index"
] = np.arange(
    len(pilot_plan)
)

pilot_plan[
    "synthetic_episode_id"
] = [
    f"SYN_{i:07d}"
    for i in range(
        len(pilot_plan)
    )
]

print(
    "Pilot episodes:",
    len(pilot_plan)
)

print(
    "\nPilot typology distribution:"
)

print(
    pilot_plan[
        "typology"
    ]
    .value_counts()
    .sort_index()
    .to_string()
)

# ============================================================
# 3. LOAD BANK MAPPING LIBRARY
# ============================================================

print("\n" + "=" * 80)
print("2. LOADING LEGITIMATE BANK MAPPINGS")
print("=" * 80)

with open(
    MAPPING_LIBRARY_PATH,
    "r",
    encoding="utf-8"
) as f:

    mapping_manifest = json.load(f)

mapping_library = (
    mapping_manifest[
        "mappings"
    ]
)

print(
    "Templates with mappings:",
    len(mapping_library)
)

print(
    "Mappings per template:",
    mapping_manifest[
        "mappings_per_template_requested"
    ]
)

print(
    "Validated legitimate edge coverage:",
    mapping_manifest[
        "legitimate_edge_coverage_pct"
    ]
)

# Convert node keys from JSON strings back to ints
normalized_mapping_library = {}

for template_id, maps in (
    mapping_library.items()
):

    normalized_mapping_library[
        str(template_id)
    ] = [

        {
            int(node):
                str(bank)

            for node, bank
            in mapping.items()
        }

        for mapping in maps
    ]

# ============================================================
# 4. LOAD BANK POOL
# ============================================================

print("\n" + "=" * 80)
print("3. LOADING BANK POOL")
print("=" * 80)

bank_pool = pd.read_csv(
    BANK_POOL_PATH,
    dtype=str
)

for col in [
    "legitimate_source_transactions",
    "legitimate_destination_transactions",
    "account_count",
    "source_probability",
    "destination_probability"
]:

    bank_pool[col] = pd.to_numeric(
        bank_pool[col],
        errors="coerce"
    ).fillna(0)

bank_tx_id_map = {
    str(row["normalized_bank_id"]):
        str(row["canonical_transaction_bank_id"])
    for _, row in bank_pool.iterrows()
}

bank_name_map = {
    str(row["normalized_bank_id"]):
        str(row["Bank Name"])
    for _, row in bank_pool.iterrows()
}

print(
    "Banks:",
    len(bank_pool)
)

# ============================================================
# 5. LOAD ACCOUNT REGISTRY
# ============================================================

print("\n" + "=" * 80)
print("4. LOADING ACCOUNT REGISTRY")
print("=" * 80)

registry = pd.read_csv(
    ACCOUNT_REGISTRY_PATH,
    dtype=str
)

registry[
    "normalized_bank_id"
] = registry[
    "normalized_bank_id"
].astype(str)

for col in [
    "legitimate_source_tx_count",
    "legitimate_destination_tx_count",
    "legitimate_total_activity"
]:

    registry[col] = pd.to_numeric(
        registry[col],
        errors="coerce"
    ).fillna(0).astype(int)

registry[
    "generator_eligible"
] = (
    registry[
        "generator_eligible"
    ]
    .astype(str)
    .str.lower()
    .eq("true")
)

eligible = registry[
    registry[
        "generator_eligible"
    ]
].copy()

print(
    "Eligible accounts:",
    f"{len(eligible):,}"
)

# ------------------------------------------------------------
# Role-specific pools
# ------------------------------------------------------------

account_pool = defaultdict(list)

for _, row in eligible.iterrows():

    bank = str(
        row["normalized_bank_id"]
    )

    account = str(
        row["Account Number"]
    )

    role = str(
        row["role"]
    )

    # Source-compatible
    if role in {
        "source_only",
        "both"
    }:

        account_pool[
            (bank, "source")
        ].append(account)

    # Destination-compatible
    if role in {
        "destination_only",
        "both"
    }:

        account_pool[
            (bank, "destination")
        ].append(account)

    # Both-side accounts
    if role == "both":

        account_pool[
            (bank, "both")
        ].append(account)

    # Universal bank pool
    account_pool[
        (bank, "any")
    ].append(account)

for key in account_pool:

    random.shuffle(
        account_pool[key]
    )

pool_pointer = defaultdict(int)

# ============================================================
# 6. LOAD ACCOUNT GENERATION DNA
# ============================================================

print("\n" + "=" * 80)
print("5. LOADING ACCOUNT GENERATION DNA")
print("=" * 80)

with open(
    ACCOUNT_PREFIX_PATH,
    "r",
    encoding="utf-8"
) as f:

    bank_prefix_sampler = json.load(f)

with open(
    ACCOUNT_GENERATOR_PATH,
    "r",
    encoding="utf-8"
) as f:

    account_generator_dna = json.load(f)

with open(
    ENTITY_DNA_PATH,
    "r",
    encoding="utf-8"
) as f:

    entity_dna = json.load(f)

position_models = (
    account_generator_dna[
        "position_models"
    ]
)

entity_position_models = (
    entity_dna[
        "entity_id_position_models"
    ]

)

name_prefixes = (
    entity_dna[
        "top_name_prefixes"
    ]
)

# ------------------------------------------------------------
# Position sampler
# ------------------------------------------------------------

account_position_arrays = {}

for pos, entries in (
    position_models.items()
):

    chars = [
        x["char"]
        for x in entries
    ]

    probs = np.array(
        [
            x["probability"]
            for x in entries
        ],
        dtype=float
    )

    probs /= probs.sum()

    account_position_arrays[
        int(pos)
    ] = (
        chars,
        probs
    )

# ------------------------------------------------------------
# Entity sampler
# ------------------------------------------------------------

entity_position_arrays = {}

for pos, values in (
    entity_position_models.items()
):

    chars = list(
        values.keys()
    )

    probs = np.array(
        [
            values[c]["probability"]
            for c in chars
        ],
        dtype=float
    )

    probs /= probs.sum()

    entity_position_arrays[
        int(pos)
    ] = (
        chars,
        probs
    )

name_keys = list(
    name_prefixes.keys()
)

name_probs = np.array(
    [
        name_prefixes[k]
        for k in name_keys
    ],
    dtype=float
)

name_probs /= name_probs.sum()

# ------------------------------------------------------------
# Existing IDs
# ------------------------------------------------------------

existing_bank_account_keys = set(
    (
        str(row["normalized_bank_id"]),
        str(row["Account Number"])
    )
    for _, row
    in registry.iterrows()
)

used_new_accounts = set()
used_new_entities = set()

new_account_rows = []

# ============================================================
# 7. FRESH ACCOUNT GENERATORS
# ============================================================

def generate_entity_id():

    for _ in range(10000):

        chars = []

        for pos in range(1, 10):

            char_list, probs = (
                entity_position_arrays[
                    pos
                ]
            )

            chars.append(
                np.random.choice(
                    char_list,
                    p=probs
                )
            )

        value = "".join(
            chars
        )

        if value not in (
            used_new_entities
        ):

            used_new_entities.add(
                value
            )

            return value

    raise RuntimeError(
        "Could not generate unique Entity ID."
    )


def generate_entity_name():

    prefix = np.random.choice(
        name_keys,
        p=name_probs
    )

    number = np.random.randint(
        1,
        100000
    )

    return (
        f"{prefix} #{number}"
    )


def generate_new_account(
    bank
):

    bank = str(bank)

    prefix_data = (
        bank_prefix_sampler.get(
            bank
        )
    )

    for _ in range(10000):

        # ----------------------------------------------------
        # Bank-specific 3-character prefix
        # ----------------------------------------------------
        if (
            prefix_data
            and
            prefix_data["prefixes"]
        ):

            prefixes = [
                x["prefix"]
                for x
                in prefix_data["prefixes"]
            ]

            probs = np.array(
                [
                    x["probability"]
                    for x
                    in prefix_data["prefixes"]
                ],
                dtype=float
            )

            probs /= probs.sum()

            prefix = np.random.choice(
                prefixes,
                p=probs
            )

        else:

            prefix = ""

            for pos in [1, 2, 3]:

                chars, probs = (
                    account_position_arrays[
                        pos
                    ]
                )

                prefix += (
                    np.random.choice(
                        chars,
                        p=probs
                    )
                )

        account_chars = list(
            prefix
        )

        for pos in range(
            4,
            10
        ):

            chars, probs = (
                account_position_arrays[
                    pos
                ]
            )

            account_chars.append(
                np.random.choice(
                    chars,
                    p=probs
                )
            )

        account = "".join(
            account_chars
        )

        key = (
            bank,
            account
        )

        if (
            key not in
            existing_bank_account_keys
            and
            key not in
            used_new_accounts
        ):

            used_new_accounts.add(
                key
            )

            entity_id = (
                generate_entity_id()
            )

            entity_name = (
                generate_entity_name()
            )

            new_account_rows.append(
                {
                    "Bank Name":
                        bank_name_map[
                            bank
                        ],

                    "Bank ID":
                        str(
                            bank_pool.loc[
                                bank_pool[
                                    "normalized_bank_id"
                                ].astype(str)
                                ==
                                bank,
                                "canonical_transaction_bank_id"
                            ].iloc[0]
                        ),

                    "Account Number":
                        account,

                    "Entity ID":
                        entity_id,

                    "Entity Name":
                        entity_name,

                    "normalized_bank_id":
                        bank
                }
            )

            return account

    raise RuntimeError(
        f"Unable to generate account for bank {bank}"
    )

# ============================================================
# 8. ACCOUNT ASSIGNMENT
# ============================================================

def get_account(
    bank,
    role,
    used_accounts
):

    bank = str(bank)

    role_order = []

    if role == "source":

        role_order = [
            "source",
            "both",
            "any"
        ]

    elif role == "destination":

        role_order = [
            "destination",
            "both",
            "any"
        ]

    else:

        role_order = [
            "both",
            "any"
        ]

    for pool_role in role_order:

        candidates = account_pool.get(
            (
                bank,
                pool_role
            ),
            []
        )

        if not candidates:
            continue

        start = pool_pointer[
            (
                bank,
                pool_role
            )
        ]

        for offset in range(
            len(candidates)
        ):

            idx = (
                start
                +
                offset
            ) % len(candidates)

            account = candidates[
                idx
            ]

            if account in used_accounts:
                continue

            pool_pointer[
                (
                    bank,
                    pool_role
                )
            ] = (
                idx + 1
            ) % len(candidates)

            return (
                account,
                False
            )

    # No original eligible account available.
    return (
        generate_new_account(bank),
        True
    )

# ============================================================
# 9. BEHAVIOR DNA SAMPLE
# ============================================================

print("\n" + "=" * 80)
print("6. LOADING LEGITIMATE BEHAVIOR DNA SAMPLE")
print("=" * 80)

# We only need a representative sample to reproduce the
# normal transaction-level behavior distribution.

behavior_parts = []

chunk_no = 0
rows_seen = 0

for chunk in pd.read_csv(
    TRANS_PATH,
    usecols=[
        "Timestamp",
        "Amount Received",
        "Amount Paid",
        "Payment Currency",
        "Receiving Currency",
        "Payment Format",
        "Is Laundering"
    ],
    dtype=str,
    chunksize=500_000
):

    chunk_no += 1
    rows_seen += len(chunk)

    chunk[
        "Is Laundering"
    ] = pd.to_numeric(
        chunk[
            "Is Laundering"
        ],
        errors="coerce"
    ).fillna(0).astype(int)

    legit = chunk[
        chunk[
            "Is Laundering"
        ] == 0
    ].copy()

    if len(legit) == 0:
        continue

    sample_n = min(
        10000,
        len(legit)
    )

    behavior_parts.append(
        legit.sample(
            n=sample_n,
            random_state=(
                SEED
                +
                chunk_no
            )
        )
    )

behavior = pd.concat(
    behavior_parts,
    ignore_index=True
)

behavior[
    "Timestamp"
] = pd.to_datetime(
    behavior[
        "Timestamp"
    ],
    errors="coerce"
)

behavior[
    "Amount Received"
] = pd.to_numeric(
    behavior[
        "Amount Received"
    ],
    errors="coerce"
)

behavior[
    "Amount Paid"
] = pd.to_numeric(
    behavior[
        "Amount Paid"
    ],
    errors="coerce"
)

behavior = behavior.dropna(
    subset=[
        "Timestamp",
        "Amount Received",
        "Amount Paid"
    ]
)

print(
    "Behavior sample:",
    f"{len(behavior):,}"
)

# ------------------------------------------------------------
# Sampling arrays
# ------------------------------------------------------------

time_values = (
    behavior[
        "Timestamp"
    ].tolist()
)

amount_values = (
    behavior[
        "Amount Received"
    ]
    .clip(
        lower=1e-6
    )
    .to_numpy(
        dtype=float
    )
)

payment_formats = (
    behavior[
        "Payment Format"
    ]
    .astype(str)
    .tolist()
)

payment_currencies = (
    behavior[
        "Payment Currency"
    ]
    .astype(str)
    .tolist()
)

receiving_by_payment = defaultdict(list)

for pay, recv in zip(
    behavior[
        "Payment Currency"
    ].astype(str),
    behavior[
        "Receiving Currency"
    ].astype(str)
):

    receiving_by_payment[
        pay
    ].append(
        recv
    )

dataset_min_ts = (
    behavior[
        "Timestamp"
    ].min()
)

dataset_max_ts = (
    behavior[
        "Timestamp"
    ].max()
)

dataset_max_amount = float(
    amount_values.max()
)

# ============================================================
# 10. TRANSACTION ID GENERATOR
# ============================================================

used_transaction_ids = set()

tx_alphabet = (
    string.ascii_uppercase
    +
    string.digits
)

def generate_transaction_id():

    for _ in range(1000):

        value = "".join(
            random.choices(
                tx_alphabet,
                k=16
            )
        )

        if value not in (
            used_transaction_ids
        ):

            used_transaction_ids.add(
                value
            )

            return value

    raise RuntimeError(
        "Unable to create unique transaction ID."
    )

# ============================================================
# 11. GENERATE PILOT
# ============================================================

print("\n" + "=" * 80)
print("7. GENERATING CONNECTIVITY-CONSTRAINED PILOT")
print("=" * 80)

transaction_rows = []
episode_audit = []

pattern_file = open(
    OUT_PATTERNS,
    "w",
    encoding="utf-8"
)

total_transactions = 0

for idx, episode in (
    pilot_plan.iterrows()
):

    template_id = str(
        episode[
            "source_template_id"
        ]
    )

    typology = str(
        episode[
            "typology"
        ]
    )

    synthetic_episode_id = str(
        episode[
            "synthetic_episode_id"
        ]
    )

    template = template_lookup[
        template_id
    ]

    valid_mappings = (
        normalized_mapping_library[
            template_id
        ]
    )

    if not valid_mappings:

        raise RuntimeError(
            f"No valid bank mappings for "
            f"template {template_id}"
        )

    # --------------------------------------------------------
    # Choose one validated bank mapping.
    # --------------------------------------------------------
    node_bank_mapping = random.choice(
        valid_mappings
    )

    # --------------------------------------------------------
    # Node degree / role
    # --------------------------------------------------------
    in_degree = defaultdict(int)
    out_degree = defaultdict(int)

    for edge in template[
        "edges"
    ]:

        source = int(
            edge["source_node"]
        )

        destination = int(
            edge["destination_node"]
        )

        out_degree[source] += 1
        in_degree[destination] += 1

    node_roles = {}

    for node in template[
        "nodes"
    ]:

        node_id = int(
            node["node_id"]
        )

        if (
            in_degree[node_id] > 0
            and
            out_degree[node_id] > 0
        ):

            role = "both"

        elif out_degree[node_id] > 0:

            role = "source"

        else:

            role = "destination"

        node_roles[
            node_id
        ] = role

    # --------------------------------------------------------
    # Account mapping
    # --------------------------------------------------------
    node_account_mapping = {}

    used_accounts_episode = set()

    fresh_accounts_episode = 0

    for node_id in sorted(
        node_roles
    ):

        bank = str(
            node_bank_mapping[
                node_id
            ]
        )

        role = node_roles[
            node_id
        ]

        force_new = (
            np.random.random()
            <
            NEW_ACCOUNT_RATE
        )

        if force_new:

            account = (
                generate_new_account(
                    bank
                )
            )

            was_new = True

        else:

            account, was_new = (
                get_account(
                    bank,
                    role,
                    used_accounts_episode
                )
            )

        if account in (
            used_accounts_episode
        ):

            raise RuntimeError(
                "Duplicate account inside episode."
            )

        node_account_mapping[
            node_id
        ] = account

        used_accounts_episode.add(
            account
        )

        if was_new:

            fresh_accounts_episode += 1

    # --------------------------------------------------------
    # Anchor time
    # --------------------------------------------------------
    template_span = float(
        template[
            "episode_span_minutes"
        ]
    )

    anchor = random.choice(
        time_values
    )

    latest_anchor = (
        dataset_max_ts
        -
        pd.to_timedelta(
            template_span,
            unit="m"
        )
    )

    if anchor > latest_anchor:

        anchor = latest_anchor

    if anchor < dataset_min_ts:

        anchor = dataset_min_ts

    # --------------------------------------------------------
    # Episode amount scaling
    #
    # Target median follows REAL legitimate transaction
    # distribution.
    # --------------------------------------------------------
    target_median = float(
        random.choice(
            amount_values
        )
    )

    template_median = max(
        1e-9,
        float(
            template[
                "median_amount"
            ]
        )
    )

    amount_scale = (
        target_median
        /
        template_median
    )

    episode_edges = set()
    episode_amounts = []

    pattern_lines = []

    # --------------------------------------------------------
    # Transactions
    # --------------------------------------------------------
    for tx in template[
        "transactions"
    ]:

        source_node = int(
            tx["source_node"]
        )

        destination_node = int(
            tx["destination_node"]
        )

        source_bank_norm = str(
            node_bank_mapping[
                source_node
            ]
        )

        destination_bank_norm = str(
            node_bank_mapping[
                destination_node
            ]
        )

        source_account = (
            node_account_mapping[
                source_node
            ]
        )

        destination_account = (
            node_account_mapping[
                destination_node
            ]
        )

        # ----------------------------------------------------
        # Validated mapped bank edge
        # ----------------------------------------------------
        edge = (
            source_bank_norm,
            destination_bank_norm
        )

        episode_edges_check = (
            source_bank_norm,
            source_account,
            destination_bank_norm,
            destination_account
        )

        episode_edges_check = (
            source_bank_norm,
            source_account,
            destination_bank_norm,
            destination_account
        )

        episode_edges_check = tuple(
            episode_edges_check
        )

        episode_edges_check

        episode_edges_key = (
            source_bank_norm,
            source_account,
            destination_bank_norm,
            destination_account
        )

        episode_edges_set_key = (
            source_bank_norm,
            source_account,
            destination_bank_norm,
            destination_account
        )

        episode_edges_key = (
            source_bank_norm,
            source_account,
            destination_bank_norm,
            destination_account
        )

        # Use full account-level directed edge for audit.
        episode_edges = episode_edges_set_key

        episode_edges

        episode_edge_set = (
            episode_audit
        )

        # Actually store it in local set:
        # ----------------------------------------------------
        episode_edges_unique = (
            episode_edges_set_key
        )

        # We keep a dedicated local set below.
        # ----------------------------------------------------

        # ----------------------------------------------------
        # Amount
        # ----------------------------------------------------
        template_amount = float(
            tx[
                "amount_received"
            ]
        )

        amount_received = max(
            1e-6,
            template_amount
            *
            amount_scale
        )

        original_received = max(
            1e-12,
            template_amount
        )

        original_paid = float(
            tx[
                "amount_paid"
            ]
        )

        paid_ratio = (
            original_paid
            /
            original_received
        )

        amount_paid = max(
            1e-6,
            amount_received
            *
            paid_ratio
        )

        if (
            amount_received
            >
            dataset_max_amount
        ):

            correction = (
                dataset_max_amount
                /
                amount_received
            )

            amount_received *= correction
            amount_paid *= correction

        # ----------------------------------------------------
        # Timestamp
        # ----------------------------------------------------
        timestamp = (
            anchor
            +
            pd.to_timedelta(
                float(
                    tx[
                        "relative_minutes"
                    ]
                ),
                unit="m"
            )
        )

        # ----------------------------------------------------
        # Real legitimate transaction behavior
        # ----------------------------------------------------
        payment_format = random.choice(
            payment_formats
        )

        payment_currency = random.choice(
            payment_currencies
        )

        recv_candidates = (
            receiving_by_payment.get(
                payment_currency
            )
        )

        if (
            recv_candidates
            and
            len(recv_candidates) > 0
        ):

            receiving_currency = (
                random.choice(
                    recv_candidates
                )
            )

        else:

            receiving_currency = (
                payment_currency
            )

        # ----------------------------------------------------
        # Canonical transaction bank IDs
        # ----------------------------------------------------
        source_bank_tx = (
            bank_tx_id_map[
                source_bank_norm
            ]
        )

        destination_bank_tx = (
            bank_tx_id_map[
                destination_bank_norm
            ]
        )

        # ----------------------------------------------------
        # Transaction ID
        # ----------------------------------------------------
        transaction_id = (
            generate_transaction_id()
        )

        transaction_rows.append(
            {
                "transaction_id":
                    transaction_id,

                "Timestamp":
                    timestamp.strftime(
                        "%Y-%m-%d %H:%M:%S"
                    ),

                "From Bank":
                    source_bank_tx,

                "Account":
                    source_account,

                "To Bank":
                    destination_bank_tx,

                "Account.1":
                    destination_account,

                "Amount Received":
                    float(
                        amount_received
                    ),

                "Receiving Currency":
                    receiving_currency,

                "Amount Paid":
                    float(
                        amount_paid
                    ),

                "Payment Currency":
                    payment_currency,

                "Payment Format":
                    payment_format,

                "Is Laundering":
                    1,

                "is_synthetic":
                    1,

                "synthetic_episode_id":
                    synthetic_episode_id,

                "typology":
                    typology,

                "source_template_id":
                    template_id,

                "template_source_order":
                    int(
                        tx[
                            "source_order"
                        ]
                    )
            }
        )

        # ----------------------------------------------------
        # IBM-style pattern transaction line
        # ----------------------------------------------------
        pattern_lines.append(
            ",".join(
                [
                    timestamp.strftime(
                        "%Y/%m/%d %H:%M"
                    ),

                    source_bank_tx,

                    source_account,

                    destination_bank_tx,

                    destination_account,

                    f"{amount_received:.6f}",

                    receiving_currency,

                    f"{amount_paid:.6f}",

                    payment_currency,

                    payment_format,

                    "1"
                ]
            )
        )

        episode_amounts.append(
            amount_received
        )

    # --------------------------------------------------------
    # Write Patterns.txt block
    # --------------------------------------------------------
    pattern_file.write(
        f'id="{synthetic_episode_id}"\n'
    )

    pattern_file.write(
        f"BEGIN LAUNDERING ATTEMPT - "
        f"{typology}: "
        f"Synthetic instance based on "
        f"IBM {typology} template\n"
    )

    for pattern_line in pattern_lines:

        pattern_file.write(
            pattern_line + "\n"
        )

    pattern_file.write(
        f"END LAUNDERING ATTEMPT - "
        f"{typology}\n"
    )

    # --------------------------------------------------------
    # Episode audit
    # --------------------------------------------------------
    #
    # Reconstruct all account-level edges directly from the
    # generated transaction records for this episode.
    # --------------------------------------------------------
    episode_transaction_rows = transaction_rows[
        -len(
            template[
                "transactions"
            ]
        ):
    ]

    full_edges = {
        (
            row["From Bank"],
            row["Account"],
            row["To Bank"],
            row["Account.1"]
        )
        for row
        in episode_transaction_rows
    }

    episode_audit.append(
        {
            "synthetic_episode_id":
                synthetic_episode_id,

            "typology":
                typology,

            "source_template_id":
                template_id,

            "transaction_count":
                len(
                    episode_transaction_rows
                ),

            "template_node_count":
                int(
                    len(
                        template[
                            "nodes"
                        ]
                    )
                ),

            "generated_unique_banks":
                len(
                    set(
                        node_bank_mapping.values()
                    )
                ),

            "fresh_accounts":
                fresh_accounts_episode,

            "unique_accounts":
                len(
                    node_account_mapping
                ),

            "unique_directed_edges":
                len(
                    full_edges
                ),

            "duplicate_directed_edges":
                len(
                    episode_transaction_rows
                )
                -
                len(
                    full_edges
                ),

            "template_span_minutes":
                template_span,

            "generated_median_amount":
                float(
                    np.median(
                        episode_amounts
                    )
                )
        }
    )

    total_transactions += (
        len(
            template[
                "transactions"
            ]
        )
    )

    if (
        (idx + 1) % 500
        == 0
    ):

        print(
            f"Episodes: {idx + 1:,}"
            f" | Transactions: "
            f"{total_transactions:,}"
            f" | New accounts: "
            f"{len(new_account_rows):,}"
        )

pattern_file.close()

# ============================================================
# 12. DATAFRAMES
# ============================================================

synthetic_df = pd.DataFrame(
    transaction_rows
)

new_accounts_df = pd.DataFrame(
    new_account_rows
)

audit_df = pd.DataFrame(
    episode_audit
)

# ============================================================
# 13. SAVE FILES
# ============================================================

print("\n" + "=" * 80)
print("8. SAVING PILOT V2")
print("=" * 80)

synthetic_df.to_csv(
    OUT_TRANS,
    index=False
)

new_accounts_df.to_csv(
    OUT_ACCOUNTS,
    index=False
)

audit_df.to_csv(
    OUT_AUDIT,
    index=False
)

# ============================================================
# 14. GLOBAL EDGE CHECK
# ============================================================

global_edges = (
    synthetic_df[
        [
            "From Bank",
            "Account",
            "To Bank",
            "Account.1"
        ]
    ]
    .astype(str)
    .agg(
        "|".join,
        axis=1
    )
)

# ============================================================
# 15. LEGITIMATE BANK PAIR SET
# ============================================================

legit_pair_path = os.path.join(
    WORK_DIR,
    "HI-Small_legitimate_bank_pairs.csv"
)

legit_pairs = pd.read_csv(
    legit_pair_path,
    dtype=str
)

legit_pairs[
    "src_norm"
] = (
    legit_pairs[
        "From Bank"
    ]
    .map(
        lambda x: str(
            int(str(x))
        )
    )
)

legit_pairs[
    "dst_norm"
] = (
    legit_pairs[
        "To Bank"
    ]
    .map(
        lambda x: str(
            int(str(x))
        )
    )
)

legit_pairs = legit_pairs[
    pd.to_numeric(
        legit_pairs[
            "legitimate_count"
        ],
        errors="coerce"
    ).fillna(0)
    > 0
]

legit_pair_set = set(
    zip(
        legit_pairs[
            "src_norm"
        ],
        legit_pairs[
            "dst_norm"
        ]
    )
)

synthetic_df[
    "from_norm"
] = synthetic_df[
    "From Bank"
].map(
    lambda x: str(
        int(str(x))
    )
)

synthetic_df[
    "to_norm"
] = synthetic_df[
    "To Bank"
].map(
    lambda x: str(
        int(str(x))
    )
)

pair_flags = [
    (
        (src, dst)
        in legit_pair_set
    )
    for src, dst in zip(
        synthetic_df[
            "from_norm"
        ],
        synthetic_df[
            "to_norm"
        ]
    )
]

# ============================================================
# 16. ACCOUNT-BANK VALIDATION
# ============================================================

# Original registry account -> normalized bank
account_bank_map = {
    str(row["Account Number"]):
        str(row["normalized_bank_id"])
    for _, row
    in registry.iterrows()
}

# New account -> normalized bank
for _, row in new_accounts_df.iterrows():

    account_bank_map[
        str(row[
            "Account Number"
        ])
    ] = str(
        row[
            "normalized_bank_id"
        ]
    )

source_consistency = []
destination_consistency = []

for _, row in synthetic_df.iterrows():

    account = str(
        row["Account"]
    )

    account2 = str(
        row["Account.1"]
    )

    source_bank = str(
        row["from_norm"]
    )

    destination_bank = str(
        row["to_norm"]
    )

    if account in account_bank_map:

        source_consistency.append(
            account_bank_map[
                account
            ]
            ==
            source_bank
        )

    else:

        source_consistency.append(
            False
        )

    if account2 in account_bank_map:

        destination_consistency.append(
            account_bank_map[
                account2
            ]
            ==
            destination_bank
        )

    else:

        destination_consistency.append(
            False
        )

# ============================================================
# 17. ACCOUNT FORMAT VALIDATION
# ============================================================

new_account_format_ok = (
    new_accounts_df[
        "Account Number"
    ]
    .astype(str)
    .str.fullmatch(
        r"[A-Z0-9]{9}"
    )
)

# ============================================================
# 18. PATTERN FILE VALIDATION
# ============================================================

with open(
    OUT_PATTERNS,
    "r",
    encoding="utf-8"
) as f:

    pattern_lines = [
        x.rstrip("\n")
        for x in f
    ]

pattern_ids = [
    x for x in pattern_lines
    if x.startswith(
        'id="'
    )
]

pattern_begins = [
    x for x in pattern_lines
    if x.startswith(
        "BEGIN LAUNDERING ATTEMPT"
    )
]

pattern_ends = [
    x for x in pattern_lines
    if x.startswith(
        "END LAUNDERING ATTEMPT"
    )
]

# ============================================================
# 19. TYPOLOGY AUDIT
# ============================================================

typology_transactions = (
    synthetic_df[
        "typology"
    ]
    .value_counts()
    .sort_index()
)

typology_episodes = (
    audit_df[
        "typology"
    ]
    .value_counts()
    .sort_index()
)

# ============================================================
# 20. SAVE MANIFEST
# ============================================================

manifest = {

    "dataset":
        "IBM HI-Small",

    "generator_version":
        "connectivity_constrained_v2",

    "seed":
        SEED,

    "pilot_episodes":
        int(PILOT_EPISODES),

    "generated_transactions":
        int(len(synthetic_df)),

    "new_accounts":
        int(len(new_accounts_df)),

    "new_account_rate":
        float(NEW_ACCOUNT_RATE),

    "ibm_templates_available":
        int(len(templates)),

    "ibm_templates_used":
        int(
            pilot_plan[
                "source_template_id"
            ].nunique()
        ),

    "valid_bank_mappings_available":
        int(
            mapping_manifest[
                "total_valid_mappings"
            ]
        ),

    "typology_episode_counts":
        {
            str(k): int(v)
            for k, v
            in typology_episodes.items()
        },

    "typology_transaction_counts":
        {
            str(k): int(v)
            for k, v
            in typology_transactions.items()
        },

    "transaction_weighted_legitimate_bank_pair_pct":
        float(
            np.mean(
                pair_flags
            )
            *
            100
        ),

    "global_unique_directed_edges":
        int(
            global_edges.nunique()
        ),

    "global_duplicate_directed_edges":
        int(
            len(global_edges)
            -
            global_edges.nunique()
        ),

    "source_account_bank_consistency_pct":
        float(
            np.mean(
                source_consistency
            )
            *
            100
        ),

    "destination_account_bank_consistency_pct":
        float(
            np.mean(
                destination_consistency
            )
            *
            100
        ),

    "new_account_format_violations":
        int(
            (~new_account_format_ok).sum()
        ),

    "pattern_id_lines":
        int(
            len(pattern_ids)
        ),

    "pattern_begin_lines":
        int(
            len(pattern_begins)
        ),

    "pattern_end_lines":
        int(
            len(pattern_ends)
        ),

    "outputs": {
        "transactions":
            OUT_TRANS,

        "new_accounts":
            OUT_ACCOUNTS,

        "patterns":
            OUT_PATTERNS,

        "episode_audit":
            OUT_AUDIT
    }
}

with open(
    OUT_MANIFEST,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        manifest,
        f,
        indent=2
    )

# ============================================================
# 21. FINAL VALIDATION OUTPUT
# ============================================================

print("\n" + "=" * 100)
print("✅ CELL 18 COMPLETE — PILOT V2")
print("=" * 100)

print(
    "\nTransactions:",
    f"{len(synthetic_df):,}"
)

print(
    "Episodes:",
    f"{len(audit_df):,}"
)

print(
    "New accounts:",
    f"{len(new_accounts_df):,}"
)

print(
    "Unique transaction IDs:",
    synthetic_df[
        "transaction_id"
    ].nunique()
)

print(
    "Transaction ID duplicates:",
    len(synthetic_df)
    -
    synthetic_df[
        "transaction_id"
    ].nunique()
)

print(
    "\nTransaction-weighted legitimate bank-pair coverage:",
    f"{np.mean(pair_flags) * 100:.4f}%"
)

print(
    "Global duplicate directed edges:",
    int(
        len(global_edges)
        -
        global_edges.nunique()
    )
)

print(
    "Source account-bank consistency:",
    f"{np.mean(source_consistency) * 100:.4f}%"
)

print(
    "Destination account-bank consistency:",
    f"{np.mean(destination_consistency) * 100:.4f}%"
)

print(
    "New-account format violations:",
    int(
        (~new_account_format_ok).sum()
    )
)

print(
    "\nPatterns.txt IDs:",
    len(pattern_ids)
)

print(
    "Patterns.txt BEGIN:",
    len(pattern_begins)
)

print(
    "Patterns.txt END:",
    len(pattern_ends)
)

print(
    "Pattern marker counts correct:",
    (
        len(pattern_ids)
        ==
        PILOT_EPISODES
        and
        len(pattern_begins)
        ==
        PILOT_EPISODES
        and
        len(pattern_ends)
        ==
        PILOT_EPISODES
    )
)

print("\nTypology transactions:")

print(
    typology_transactions.to_string()
)

print("\nSaved:")

print(
    OUT_TRANS
)

print(
    OUT_ACCOUNTS
)

print(
    OUT_PATTERNS
)

print(
    OUT_AUDIT
)

print(
    OUT_MANIFEST
)

print("\nORIGINAL HI-SMALL FILES WERE NOT MODIFIED.")

print("=" * 100)

====================================================================================================
CELL 18 — CONNECTIVITY-CONSTRAINED SYNTHETIC PILOT V2
====================================================================================================

================================================================================
1. LOADING TEMPLATES
================================================================================
IBM templates: 370
Pilot episodes: 5000

Pilot typology distribution:
typology
BIPARTITE         662
CYCLE             729
FAN-IN            541
FAN-OUT           649
GATHER-SCATTER    689
RANDOM            554
SCATTER-GATHER    595
STACK             581

================================================================================
2. LOADING LEGITIMATE BANK MAPPINGS
================================================================================
Templates with mappings: 370
Mappings per template: 5
Validated legitimate edge coverage: 100.0

================================================================================
3. LOADING BANK POOL
================================================================================
Banks: 30470

================================================================================
4. LOADING ACCOUNT REGISTRY
================================================================================
Eligible accounts: 508,731

================================================================================
5. LOADING ACCOUNT GENERATION DNA
================================================================================

================================================================================
6. LOADING LEGITIMATE BEHAVIOR DNA SAMPLE
================================================================================
Behavior sample: 110,000

================================================================================
7. GENERATING CONNECTIVITY-CONSTRAINED PILOT
================================================================================
Episodes: 500 | Transactions: 4,167 | New accounts: 369
Episodes: 1,000 | Transactions: 8,626 | New accounts: 781
Episodes: 1,500 | Transactions: 12,878 | New accounts: 1,175
Episodes: 2,000 | Transactions: 17,241 | New accounts: 1,639
Episodes: 2,500 | Transactions: 21,692 | New accounts: 2,039
Episodes: 3,000 | Transactions: 26,123 | New accounts: 2,439
Episodes: 3,500 | Transactions: 30,275 | New accounts: 2,806
Episodes: 4,000 | Transactions: 34,377 | New accounts: 3,195
Episodes: 4,500 | Transactions: 38,743 | New accounts: 3,645
Episodes: 5,000 | Transactions: 43,310 | New accounts: 4,081

================================================================================
8. SAVING PILOT V2
================================================================================

====================================================================================================
✅ CELL 18 COMPLETE — PILOT V2
====================================================================================================

Transactions: 43,310
Episodes: 5,000
New accounts: 4,081
Unique transaction IDs: 43310
Transaction ID duplicates: 0

Transaction-weighted legitimate bank-pair coverage: 100.0000%
Global duplicate directed edges: 0
Source account-bank consistency: 99.9815%
Destination account-bank consistency: 99.9885%
New-account format violations: 0

Patterns.txt IDs: 5000
Patterns.txt BEGIN: 5000
Patterns.txt END: 5000
Pattern marker counts correct: True

Typology transactions:
typology
BIPARTITE         3543
CYCLE             3903
FAN-IN            4212
FAN-OUT           4631
GATHER-SCATTER    9535
RANDOM            2610
SCATTER-GATHER    8470
STACK             6406

Saved:
/kaggle/working/AML_GNN_ONLY/data/HI-Small_SYNTH_PILOT_V2_transactions.csv
/kaggle/working/AML_GNN_ONLY/data/HI-Small_SYNTH_PILOT_V2_new_accounts.csv
/kaggle/working/AML_GNN_ONLY/data/HI-Small_SYNTH_PILOT_V2_Patterns.txt
/kaggle/working/AML_GNN_ONLY/data/HI-Small_SYNTH_PILOT_V2_episode_audit.csv
/kaggle/working/AML_GNN_ONLY/data/HI-Small_SYNTH_PILOT_V2_manifest.json

ORIGINAL HI-SMALL FILES WERE NOT MODIFIED.
====================================================================================================

In [25]:
# ============================================================
# CELL 19 — FULL PILOT INTEGRITY + PATTERN FIDELITY AUDIT
# ============================================================
#
# PURPOSE
# -------
# Validate the complete V2 pilot before scaling to ~5.07M
# synthetic laundering transactions.
#
# Checks:
#   1. Exact episode/template transaction counts
#   2. Exact node/edge morphology
#   3. Exact timestamp-relative structure
#   4. Bank-pair legitimacy
#   5. Correct BANK + ACCOUNT identity mapping
#   6. New-account uniqueness/format
#   7. Entity uniqueness
#   8. Pattern.txt integrity
#   9. Amount integrity
#  10. Currency/payment-format integrity
#
# NO DATA IS GENERATED.
# ============================================================

import os
import json
from collections import defaultdict

import numpy as np
import pandas as pd

# ============================================================
# PATHS
# ============================================================

WORK_DIR = (
    "/kaggle/working/"
    "AML_GNN_ONLY/data"
)

PILOT_TRANS_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_SYNTH_PILOT_V2_transactions.csv"
)

PILOT_ACCOUNTS_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_SYNTH_PILOT_V2_new_accounts.csv"
)

PILOT_PATTERNS_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_SYNTH_PILOT_V2_Patterns.txt"
)

PILOT_AUDIT_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_SYNTH_PILOT_V2_episode_audit.csv"
)

TEMPLATE_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_pattern_templates.json"
)

BANK_PAIR_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_legitimate_bank_pairs.csv"
)

ACCOUNT_REGISTRY_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_generator_account_registry.csv"
)

# ============================================================
# 1. LOAD
# ============================================================

print("=" * 100)
print("CELL 19 — FULL PILOT INTEGRITY + PATTERN FIDELITY AUDIT")
print("=" * 100)

pilot = pd.read_csv(
    PILOT_TRANS_PATH,
    dtype=str
)

new_accounts = pd.read_csv(
    PILOT_ACCOUNTS_PATH,
    dtype=str
)

episode_audit = pd.read_csv(
    PILOT_AUDIT_PATH,
    dtype=str
)

with open(
    TEMPLATE_PATH,
    "r",
    encoding="utf-8"
) as f:
    template_manifest = json.load(f)

templates = template_manifest[
    "templates"
]

template_lookup = {
    str(t["template_id"]): t
    for t in templates
}

print(
    "\nPilot transactions:",
    f"{len(pilot):,}"
)

print(
    "Pilot episodes:",
    f"{pilot['synthetic_episode_id'].nunique():,}"
)

print(
    "New accounts:",
    f"{len(new_accounts):,}"
)

print(
    "Templates:",
    len(templates)
)

# ============================================================
# 2. BASIC INTEGRITY
# ============================================================

print("\n" + "=" * 80)
print("1. BASIC TRANSACTION INTEGRITY")
print("=" * 80)

print(
    "Null values:",
    int(pilot.isna().sum().sum())
)

numeric_amount_received = pd.to_numeric(
    pilot["Amount Received"],
    errors="coerce"
)

numeric_amount_paid = pd.to_numeric(
    pilot["Amount Paid"],
    errors="coerce"
)

print(
    "Invalid Amount Received:",
    int(
        numeric_amount_received.isna().sum()
    )
)

print(
    "Invalid Amount Paid:",
    int(
        numeric_amount_paid.isna().sum()
    )
)

print(
    "Non-positive Amount Received:",
    int(
        (numeric_amount_received <= 0).sum()
    )
)

print(
    "Non-positive Amount Paid:",
    int(
        (numeric_amount_paid <= 0).sum()
    )
)

print(
    "Non-laundering rows:",
    int(
        (
            pd.to_numeric(
                pilot["Is Laundering"],
                errors="coerce"
            )
            != 1
        ).sum()
    )
)

# ============================================================
# 3. TRANSACTION ID INTEGRITY
# ============================================================

print("\n" + "=" * 80)
print("2. TRANSACTION ID INTEGRITY")
print("=" * 80)

unique_tx_ids = (
    pilot["transaction_id"]
    .nunique()
)

print(
    "Unique transaction IDs:",
    unique_tx_ids
)

print(
    "Duplicate transaction IDs:",
    len(pilot)
    -
    unique_tx_ids
)

# ============================================================
# 4. LOAD LEGITIMATE BANK PAIRS
# ============================================================

legit_pairs = pd.read_csv(
    BANK_PAIR_PATH,
    dtype=str
)

def norm_bank(x):

    x = str(x).strip()

    try:
        return str(int(x))
    except Exception:
        return x.lstrip("0") or "0"

legit_pairs[
    "src_norm"
] = legit_pairs[
    "From Bank"
].map(norm_bank)

legit_pairs[
    "dst_norm"
] = legit_pairs[
    "To Bank"
].map(norm_bank)

legit_pairs[
    "legitimate_count"
] = pd.to_numeric(
    legit_pairs[
        "legitimate_count"
    ],
    errors="coerce"
).fillna(0).astype(int)

legit_pair_set = set(
    zip(
        legit_pairs[
            legit_pairs[
                "legitimate_count"
            ] > 0
        ]["src_norm"],

        legit_pairs[
            legit_pairs[
                "legitimate_count"
            ] > 0
        ]["dst_norm"]
    )
)

pilot[
    "from_norm"
] = pilot[
    "From Bank"
].map(norm_bank)

pilot[
    "to_norm"
] = pilot[
    "To Bank"
].map(norm_bank)

# ============================================================
# 5. BANK-PAIR INTEGRITY
# ============================================================

print("\n" + "=" * 80)
print("3. LEGITIMATE BANK-PAIR INTEGRITY")
print("=" * 80)

pair_flags = [
    (
        (src, dst)
        in legit_pair_set
    )
    for src, dst in zip(
        pilot["from_norm"],
        pilot["to_norm"]
    )
]

print(
    "Transaction rows checked:",
    f"{len(pair_flags):,}"
)

print(
    "Legitimate bank-pair rows:",
    sum(pair_flags)
)

print(
    "Invalid bank-pair rows:",
    len(pair_flags) - sum(pair_flags)
)

print(
    "Bank-pair legitimate coverage:",
    f"{np.mean(pair_flags) * 100:.6f}%"
)

# ============================================================
# 6. ACCOUNT REGISTRY
# ============================================================

print("\n" + "=" * 80)
print("4. BANK + ACCOUNT INTEGRITY")
print("=" * 80)

registry = pd.read_csv(
    ACCOUNT_REGISTRY_PATH,
    dtype=str
)

registry[
    "normalized_bank_id"
] = registry[
    "normalized_bank_id"
].map(norm_bank)

# Exact key:
#     normalized_bank_id + Account Number
original_account_keys = set(
    (
        str(row["normalized_bank_id"]),
        str(row["Account Number"])
    )
    for _, row in registry.iterrows()
)

# Add new accounts
new_accounts[
    "normalized_bank_id"
] = new_accounts[
    "normalized_bank_id"
].map(norm_bank)

new_account_keys = set(
    (
        str(row["normalized_bank_id"]),
        str(row["Account Number"])
    )
    for _, row
    in new_accounts.iterrows()
)

all_valid_account_keys = (
    original_account_keys
    |
    new_account_keys
)

# ------------------------------------------------------------
# Source account checks
# ------------------------------------------------------------

source_keys = [
    (
        str(row["from_norm"]),
        str(row["Account"])
    )
    for _, row
    in pilot.iterrows()
]

destination_keys = [
    (
        str(row["to_norm"]),
        str(row["Account.1"])
    )
    for _, row
    in pilot.iterrows()
]

source_valid = [
    x in all_valid_account_keys
    for x in source_keys
]

destination_valid = [
    x in all_valid_account_keys
    for x in destination_keys
]

print(
    "Source bank+account valid rows:",
    sum(source_valid)
)

print(
    "Source bank+account invalid rows:",
    len(source_valid) - sum(source_valid)
)

print(
    "Source bank+account coverage:",
    f"{np.mean(source_valid) * 100:.6f}%"
)

print(
    "\nDestination bank+account valid rows:",
    sum(destination_valid)
)

print(
    "Destination bank+account invalid rows:",
    len(destination_valid) - sum(destination_valid)
)

print(
    "Destination bank+account coverage:",
    f"{np.mean(destination_valid) * 100:.6f}%"
)

# ============================================================
# 7. INVESTIGATE RAW ACCOUNT-NUMBER COLLISIONS
# ============================================================

print("\n" + "=" * 80)
print("5. GLOBAL ACCOUNT-NUMBER COLLISION CHECK")
print("=" * 80)

account_to_banks = defaultdict(set)

for bank, account in original_account_keys:

    account_to_banks[
        account
    ].add(bank)

collision_accounts = {
    account: banks
    for account, banks
    in account_to_banks.items()
    if len(banks) > 1
}

print(
    "Account numbers used by >1 bank in original data:",
    len(collision_accounts)
)

if collision_accounts:

    print(
        "\nExamples:"
    )

    for account, banks in list(
        collision_accounts.items()
    )[:20]:

        print(
            account,
            "->",
            sorted(banks)
        )

# ============================================================
# 8. NEW ACCOUNT FORMAT
# ============================================================

print("\n" + "=" * 80)
print("6. NEW ACCOUNT INTEGRITY")
print("=" * 80)

new_account_series = (
    new_accounts[
        "Account Number"
    ].astype(str)
)

valid_format = (
    new_account_series
    .str.fullmatch(
        r"[A-Z0-9]{9}"
    )
)

print(
    "New accounts:",
    len(new_accounts)
)

print(
    "Format-valid:",
    int(valid_format.sum())
)

print(
    "Format violations:",
    int((~valid_format).sum())
)

# Unique within bank
new_bank_account_keys = [
    (
        str(row["normalized_bank_id"]),
        str(row["Account Number"])
    )
    for _, row
    in new_accounts.iterrows()
]

print(
    "Unique bank+account new IDs:",
    len(set(new_bank_account_keys))
)

print(
    "Duplicate new bank+account IDs:",
    len(new_bank_account_keys)
    -
    len(set(new_bank_account_keys))
)

# Global collision with originals
new_vs_original = (
    set(new_bank_account_keys)
    &
    original_account_keys
)

print(
    "New accounts colliding with original bank+account:",
    len(new_vs_original)
)

# ============================================================
# 9. NEW ACCOUNT ENTITY INTEGRITY
# ============================================================

print("\n" + "=" * 80)
print("7. NEW ENTITY INTEGRITY")
print("=" * 80)

entity_ids = (
    new_accounts[
        "Entity ID"
    ].astype(str)
)

entity_names = (
    new_accounts[
        "Entity Name"
    ].astype(str)
)

print(
    "New Entity IDs:",
    entity_ids.nunique()
)

print(
    "Duplicate Entity IDs:",
    len(entity_ids)
    -
    entity_ids.nunique()
)

print(
    "Valid 9-char Entity IDs:",
    int(
        entity_ids
        .str.fullmatch(
            r"[A-Z0-9]{9}"
        )
        .sum()
    )
)

print(
    "Entity name examples:"
)

print(
    entity_names.head(10).to_string(
        index=False
    )
)

# ============================================================
# 10. LOAD EPISODE AUDIT
# ============================================================

episode_audit[
    "transaction_count"
] = pd.to_numeric(
    episode_audit[
        "transaction_count"
    ],
    errors="coerce"
).astype(int)

# ============================================================
# 11. EPISODE ↔ TEMPLATE FIDELITY
# ============================================================

print("\n" + "=" * 80)
print("8. EPISODE / TEMPLATE FIDELITY")
print("=" * 80)

template_count_mismatch = 0
template_node_mismatch = 0
template_edge_mismatch = 0
template_degree_mismatch = 0
timestamp_mismatch = 0

# Make generated transactions accessible by episode
grouped = {
    str(ep_id): g.reset_index(drop=True)
    for ep_id, g
    in pilot.groupby(
        "synthetic_episode_id",
        sort=False
    )
}

for ep_id, g in (
    pilot.groupby(
        "synthetic_episode_id",
        sort=False
    )
):

    ep_id = str(ep_id)

    # Template ID
    template_id = str(
        g["source_template_id"]
        .iloc[0]
    )

    template = template_lookup[
        template_id
    ]

    generated_n = len(g)

    expected_n = int(
        template[
            "transaction_count"
        ]
    )

    if generated_n != expected_n:

        template_count_mismatch += 1

    # --------------------------------------------------------
    # Generated node graph
    # --------------------------------------------------------
    account_nodes = set(
        g[
            "Account"
        ].astype(str)
    ) | set(
        g[
            "Account.1"
        ].astype(str)
    )

    expected_nodes = int(
        template[
            "node_count"
        ]
    )

    if len(account_nodes) != expected_nodes:

        template_node_mismatch += 1

    # --------------------------------------------------------
    # Generated edges
    # --------------------------------------------------------
    generated_edges = {
        (
            str(row["Account"]),
            str(row["Account.1"])
        )
        for _, row
        in g.iterrows()
    }

    expected_edges = len(
        template[
            "edges"
        ]
    )

    if len(generated_edges) != expected_edges:

        template_edge_mismatch += 1

    # --------------------------------------------------------
    # Degree sequence
    # --------------------------------------------------------
    generated_in = defaultdict(int)
    generated_out = defaultdict(int)

    for _, row in g.iterrows():

        s = str(
            row["Account"]
        )

        d = str(
            row["Account.1"]
        )

        generated_out[s] += 1
        generated_in[d] += 1

    generated_degree_signature = sorted(
        [
            (
                generated_in[n],
                generated_out[n]
            )
            for n in account_nodes
        ]
    )

    # Template degree signature
    expected_in = defaultdict(int)
    expected_out = defaultdict(int)

    for edge in template[
        "edges"
    ]:

        s = int(
            edge["source_node"]
        )

        d = int(
            edge["destination_node"]
        )

        expected_out[s] += 1
        expected_in[d] += 1

    template_nodes = [
        int(n["node_id"])
        for n in template[
            "nodes"
        ]
    ]

    expected_degree_signature = sorted(
        [
            (
                expected_in[n],
                expected_out[n]
            )
            for n in template_nodes
        ]
    )

    if (
        generated_degree_signature
        !=
        expected_degree_signature
    ):

        template_degree_mismatch += 1

    # --------------------------------------------------------
    # Timestamp fidelity
    # --------------------------------------------------------
    generated_ts = pd.to_datetime(
        g["Timestamp"],
        errors="coerce"
    )

    if generated_ts.isna().any():

        timestamp_mismatch += 1

        continue

    anchor = generated_ts.min()

    generated_relative = (
        (
            generated_ts
            -
            anchor
        )
        .dt.total_seconds()
        /
        60.0
    )

    expected_relative = np.array(
        [
            float(
                tx[
                    "relative_minutes"
                ]
            )
            for tx in sorted(
                template[
                    "transactions"
                ],
                key=lambda x:
                    int(
                        x["source_order"]
                    )
            )
        ]
    )

    # Generated row order is source order
    generated_relative_array = (
        generated_relative
        .to_numpy()
    )

    if len(
        generated_relative_array
    ) != len(
        expected_relative
    ):

        timestamp_mismatch += 1

    else:

        max_error = np.max(
            np.abs(
                generated_relative_array
                -
                expected_relative
            )
        )

        if max_error > 1e-9:

            timestamp_mismatch += 1

print(
    "Episode transaction-count mismatches:",
    template_count_mismatch
)

print(
    "Episode node-count mismatches:",
    template_node_mismatch
)

print(
    "Episode edge-count mismatches:",
    template_edge_mismatch
)

print(
    "Episode degree-signature mismatches:",
    template_degree_mismatch
)

print(
    "Episode timestamp mismatches:",
    timestamp_mismatch
)

# ============================================================
# 12. DUPLICATE DIRECTED EDGES
# ============================================================

print("\n" + "=" * 80)
print("9. DIRECTED EDGE UNIQUENESS")
print("=" * 80)

edge_strings = (
    pilot[
        [
            "from_norm",
            "Account",
            "to_norm",
            "Account.1"
        ]
    ]
    .astype(str)
    .agg(
        "|".join,
        axis=1
    )
)

print(
    "Total edges:",
    len(edge_strings)
)

print(
    "Unique edges:",
    edge_strings.nunique()
)

print(
    "Duplicate edges:",
    len(edge_strings)
    -
    edge_strings.nunique()
)

# ============================================================
# 13. AMOUNT INTEGRITY
# ============================================================

print("\n" + "=" * 80)
print("10. AMOUNT INTEGRITY")
print("=" * 80)

print(
    "Amount Received quantiles:"
)

print(
    numeric_amount_received
    .quantile(
        [
            0.001,
            0.01,
            0.05,
            0.25,
            0.50,
            0.75,
            0.90,
            0.95,
            0.99,
            0.999
        ]
    )
    .to_string()
)

print(
    "\nAmount Paid quantiles:"
)

print(
    numeric_amount_paid
    .quantile(
        [
            0.001,
            0.01,
            0.05,
            0.25,
            0.50,
            0.75,
            0.90,
            0.95,
            0.99,
            0.999
        ]
    )
    .to_string()
)

print(
    "\nAmount Received > 1e12:",
    int(
        (numeric_amount_received > 1e12).sum()
    )
)

print(
    "Amount Received < 1e-6:",
    int(
        (numeric_amount_received < 1e-6).sum()
    )
)

# ============================================================
# 14. PAYMENT BEHAVIOR
# ============================================================

print("\n" + "=" * 80)
print("11. PAYMENT BEHAVIOR")
print("=" * 80)

print(
    "\nPayment Format:"
)

print(
    pilot[
        "Payment Format"
    ]
    .value_counts(
        normalize=True
    )
    .mul(100)
    .round(4)
    .to_string()
)

print(
    "\nPayment Currency:"
)

print(
    pilot[
        "Payment Currency"
    ]
    .value_counts(
        normalize=True
    )
    .mul(100)
    .round(4)
    .to_string()
)

print(
    "\nReceiving Currency:"
)

print(
    pilot[
        "Receiving Currency"
    ]
    .value_counts(
        normalize=True
    )
    .mul(100)
    .round(4)
    .to_string()
)

# ============================================================
# 15. PATTERNS.TXT INTEGRITY
# ============================================================

print("\n" + "=" * 80)
print("12. PATTERNS.TXT INTEGRITY")
print("=" * 80)

with open(
    PILOT_PATTERNS_PATH,
    "r",
    encoding="utf-8"
) as f:

    pattern_lines = [
        x.rstrip("\n")
        for x in f
    ]

id_lines = [
    x for x in pattern_lines
    if x.startswith('id="')
]

begin_lines = [
    x for x in pattern_lines
    if x.startswith(
        "BEGIN LAUNDERING ATTEMPT"
    )
]

end_lines = [
    x for x in pattern_lines
    if x.startswith(
        "END LAUNDERING ATTEMPT"
    )
]

pattern_tx_lines = []

for x in pattern_lines:

    parts = x.split(",")

    if len(parts) == 11:

        parsed_date = pd.to_datetime(
            parts[0],
            format="%Y/%m/%d %H:%M",
            errors="coerce"
        )

        if not pd.isna(parsed_date):

            pattern_tx_lines.append(
                x
            )

print(
    "Pattern IDs:",
    len(id_lines)
)

print(
    "BEGIN markers:",
    len(begin_lines)
)

print(
    "END markers:",
    len(end_lines)
)

print(
    "Pattern transaction rows:",
    len(pattern_tx_lines)
)

print(
    "Expected pattern transaction rows:",
    len(pilot)
)

# ============================================================
# 16. PATTERN TRANSACTION LABELS
# ============================================================

pattern_labels = []

for line in pattern_tx_lines:

    parts = [
        x.strip()
        for x in line.split(",")
    ]

    try:

        pattern_labels.append(
            int(parts[10])
        )

    except Exception:

        pass

print(
    "Pattern labels other than 1:",
    sum(
        x != 1
        for x in pattern_labels
    )
)

# ============================================================
# 17. FINAL DECISION GATES
# ============================================================

print("\n" + "=" * 100)
print("13. FINAL PILOT SCALE-UP GATES")
print("=" * 100)

gates = {

    "transaction_count_nonzero":
        len(pilot) > 0,

    "unique_transaction_ids":
        (
            pilot["transaction_id"].nunique()
            ==
            len(pilot)
        ),

    "bank_pair_coverage_100":
        (
            np.mean(pair_flags)
            >=
            0.999999
        ),

    "source_bank_account_coverage_100":
        (
            np.mean(source_valid)
            >=
            0.999999
        ),

    "destination_bank_account_coverage_100":
        (
            np.mean(destination_valid)
            >=
            0.999999
        ),

    "new_account_format_100":
        (
            int((~valid_format).sum())
            ==
            0
        ),

    "new_account_bank_collision_0":
        (
            len(new_vs_original)
            ==
            0
        ),

    "new_entity_id_unique":
        (
            entity_ids.nunique()
            ==
            len(entity_ids)
        ),

    "episode_transaction_counts_exact":
        (
            template_count_mismatch
            ==
            0
        ),

    "episode_node_counts_exact":
        (
            template_node_mismatch
            ==
            0
        ),

    "episode_edge_counts_exact":
        (
            template_edge_mismatch
            ==
            0
        ),

    "episode_degree_signatures_exact":
        (
            template_degree_mismatch
            ==
            0
        ),

    "episode_timestamps_exact":
        (
            timestamp_mismatch
            ==
            0
        ),

    "duplicate_directed_edges_0":
        (
            len(edge_strings)
            ==
            edge_strings.nunique()
        ),

    "patterns_ids_exact":
        (
            len(id_lines)
            ==
            pilot["synthetic_episode_id"].nunique()
        ),

    "patterns_begin_exact":
        (
            len(begin_lines)
            ==
            pilot["synthetic_episode_id"].nunique()
        ),

    "patterns_end_exact":
        (
            len(end_lines)
            ==
            pilot["synthetic_episode_id"].nunique()
        ),

    "patterns_transaction_count_exact":
        (
            len(pattern_tx_lines)
            ==
            len(pilot)
        ),

    "patterns_all_labeled_1":
        (
            all(
                x == 1
                for x in pattern_labels
            )
        )
}

for name, passed in gates.items():

    print(
        f"{'✅' if passed else '❌'} "
        f"{name}: {passed}"
    )

all_passed = all(
    gates.values()
)

# ============================================================
# 18. FINAL RESULT
# ============================================================

print("\n" + "=" * 100)

if all_passed:

    print(
        "✅ PILOT PASSED ALL SCALE-UP INTEGRITY GATES"
    )

else:

    print(
        "❌ PILOT FAILED ONE OR MORE SCALE-UP GATES"
    )

print("=" * 100)

print(
    "\nNO SYNTHETIC DATA GENERATED BY THIS CELL."
)

print(
    "NO ORIGINAL FILES MODIFIED."
)

print("=" * 100)

====================================================================================================
CELL 19 — FULL PILOT INTEGRITY + PATTERN FIDELITY AUDIT
====================================================================================================

Pilot transactions: 43,310
Pilot episodes: 5,000
New accounts: 4,081
Templates: 370

================================================================================
1. BASIC TRANSACTION INTEGRITY
================================================================================
Null values: 0
Invalid Amount Received: 0
Invalid Amount Paid: 0
Non-positive Amount Received: 0
Non-positive Amount Paid: 0
Non-laundering rows: 0

================================================================================
2. TRANSACTION ID INTEGRITY
================================================================================
Unique transaction IDs: 43310
Duplicate transaction IDs: 0

================================================================================
3. LEGITIMATE BANK-PAIR INTEGRITY
================================================================================
Transaction rows checked: 43,310
Legitimate bank-pair rows: 43310
Invalid bank-pair rows: 0
Bank-pair legitimate coverage: 100.000000%

================================================================================
4. BANK + ACCOUNT INTEGRITY
================================================================================
Source bank+account valid rows: 43310
Source bank+account invalid rows: 0
Source bank+account coverage: 100.000000%

Destination bank+account valid rows: 43310
Destination bank+account invalid rows: 0
Destination bank+account coverage: 100.000000%

================================================================================
5. GLOBAL ACCOUNT-NUMBER COLLISION CHECK
================================================================================
Account numbers used by >1 bank in original data: 8

Examples:
8135B8200 -> ['221731', '27444']
8135B8250 -> ['221731', '27444']
81211BA20 -> ['142574', '1490']
81211BC00 -> ['142574', '1490']
80FA56340 -> ['13858', '138832']
80A7FDE00 -> ['27755', '28248']
80A7FD400 -> ['27755', '28248']
80FA55EF0 -> ['13858', '138832']

================================================================================
6. NEW ACCOUNT INTEGRITY
================================================================================
New accounts: 4081
Format-valid: 4081
Format violations: 0
Unique bank+account new IDs: 4081
Duplicate new bank+account IDs: 0
New accounts colliding with original bank+account: 0

================================================================================
7. NEW ENTITY INTEGRITY
================================================================================
New Entity IDs: 4081
Duplicate Entity IDs: 0
Valid 9-char Entity IDs: 4081
Entity name examples:
Partnership #29149
Corporation #62779
Corporation #36823
Partnership #53285
Partnership #24643
Corporation #77136
       Sole #39617
       Sole #75621
Corporation #13960
 Partnership #7132

================================================================================
8. EPISODE / TEMPLATE FIDELITY
================================================================================

/tmp/ipykernel_58/3382689211.py:799: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  generated_ts = pd.to_datetime(
/tmp/ipykernel_58/3382689211.py:799: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  generated_ts = pd.to_datetime(

Episode transaction-count mismatches: 0
Episode node-count mismatches: 0
Episode edge-count mismatches: 0
Episode degree-signature mismatches: 0
Episode timestamp mismatches: 0

================================================================================
9. DIRECTED EDGE UNIQUENESS
================================================================================
Total edges: 43310
Unique edges: 43310
Duplicate edges: 0

================================================================================
10. AMOUNT INTEGRITY
================================================================================
Amount Received quantiles:
0.001    7.053857e-05
0.010    8.546211e-03
0.050    2.670620e+00
0.250    1.431546e+02
0.500    1.363441e+03
0.750    1.544714e+04
0.900    2.319521e+05
0.950    1.246118e+06
0.990    3.388815e+07
0.999    3.704223e+09

Amount Paid quantiles:
0.001    7.053857e-05
0.010    8.546211e-03
0.050    2.670620e+00
0.250    1.431546e+02
0.500    1.363441e+03
0.750    1.544714e+04
0.900    2.319521e+05
0.950    1.246118e+06
0.990    3.388815e+07
0.999    3.704223e+09

Amount Received > 1e12: 0
Amount Received < 1e-6: 0

================================================================================
11. PAYMENT BEHAVIOR
================================================================================

Payment Format:
Payment Format
Cheque          37.6380
Credit Card     25.5992
ACH             11.9487
Cash             9.6998
Reinvestment     8.5962
Wire             3.6435
Bitcoin          2.8746

Payment Currency:
Payment Currency
US Dollar            36.7398
Euro                 23.0409
Swiss Franc           4.6640
Yuan                  4.1538
Shekel                3.8259
UK Pound              3.7613
Rupee                 3.6181
Ruble                 3.2417
Bitcoin               2.9485
Yen                   2.9485
Canadian Dollar       2.9185
Australian Dollar     2.6460
Mexican Peso          2.1819
Saudi Riyal           1.8910
Brazil Real           1.4200

Receiving Currency:
Receiving Currency
US Dollar            36.4350
Euro                 23.1586
Swiss Franc           4.7449
Yuan                  3.9737
Shekel                3.8652
UK Pound              3.7497
Rupee                 3.6481
Ruble                 3.2810
Bitcoin               2.9924
Yen                   2.9554
Canadian Dollar       2.9508
Australian Dollar     2.6807
Mexican Peso          2.2050
Saudi Riyal           1.9118
Brazil Real           1.4477

================================================================================
12. PATTERNS.TXT INTEGRITY
================================================================================
Pattern IDs: 5000
BEGIN markers: 5000
END markers: 5000
Pattern transaction rows: 43310
Expected pattern transaction rows: 43310
Pattern labels other than 1: 0

====================================================================================================
13. FINAL PILOT SCALE-UP GATES
====================================================================================================
✅ transaction_count_nonzero: True
✅ unique_transaction_ids: True
✅ bank_pair_coverage_100: True
✅ source_bank_account_coverage_100: True
✅ destination_bank_account_coverage_100: True
✅ new_account_format_100: True
✅ new_account_bank_collision_0: True
✅ new_entity_id_unique: True
✅ episode_transaction_counts_exact: True
✅ episode_node_counts_exact: True
✅ episode_edge_counts_exact: True
✅ episode_degree_signatures_exact: True
✅ episode_timestamps_exact: True
✅ duplicate_directed_edges_0: True
✅ patterns_ids_exact: True
✅ patterns_begin_exact: True
✅ patterns_end_exact: True
✅ patterns_transaction_count_exact: True
✅ patterns_all_labeled_1: True

====================================================================================================
✅ PILOT PASSED ALL SCALE-UP INTEGRITY GATES
====================================================================================================

NO SYNTHETIC DATA GENERATED BY THIS CELL.
NO ORIGINAL FILES MODIFIED.
====================================================================================================

In [26]:
# ============================================================
# CELL 20 — FULL-SCALE STREAMING SYNTHETIC GENERATOR
# ============================================================
#
# TARGET:
#   5,067,991 synthetic laundering transactions
#   584,706 synthetic laundering episodes
#
# IMPORTANT:
#   - Original HI-Small files remain untouched.
#   - Writes incrementally to disk.
#   - Does NOT hold 5M transaction dictionaries in RAM.
#
# OUTPUT:
#   HI-Small_SYNTH_FULL_transactions.csv
#   HI-Small_SYNTH_FULL_new_accounts.csv
#   HI-Small_SYNTH_FULL_Patterns.txt
#   HI-Small_SYNTH_FULL_episode_audit.csv
#   HI-Small_SYNTH_FULL_manifest.json
#
# ============================================================

import os
import json
import random
import string
from collections import defaultdict

import numpy as np
import pandas as pd

# ============================================================
# CONFIG
# ============================================================

SEED = 20260919

random.seed(SEED)
np.random.seed(SEED)

NEW_ACCOUNT_RATE = 0.05

FLUSH_EVERY_EPISODES = 500

# ============================================================
# PATHS
# ============================================================

DATA_ROOT = (
    "/kaggle/input/datasets/"
    "ealtman2019/ibm-transactions-for-anti-money-laundering-aml"
)

WORK_DIR = (
    "/kaggle/working/"
    "AML_GNN_ONLY/data"
)

TRANS_PATH = os.path.join(
    DATA_ROOT,
    "HI-Small_Trans.csv"
)

ACCOUNTS_PATH = os.path.join(
    DATA_ROOT,
    "HI-Small_accounts.csv"
)

TEMPLATE_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_pattern_templates.json"
)

EPISODE_PLAN_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_synthetic_episode_plan.csv"
)

BANK_POOL_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_final_generator_bank_pool.csv"
)

ACCOUNT_REGISTRY_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_generator_account_registry.csv"
)

ACCOUNT_PREFIX_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_bank_account_prefix_sampler.json"
)

ACCOUNT_GENERATOR_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_account_id_generator.json"
)

ENTITY_DNA_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_entity_name_dna.json"
)

MAPPING_LIBRARY_PATH = os.path.join(
    WORK_DIR,
    "HI-Small_legitimate_bank_mapping_library.json"
)

# ------------------------------------------------------------
# FINAL OUTPUTS
# ------------------------------------------------------------

OUT_TRANS = os.path.join(
    WORK_DIR,
    "HI-Small_SYNTH_FULL_transactions.csv"
)

OUT_ACCOUNTS = os.path.join(
    WORK_DIR,
    "HI-Small_SYNTH_FULL_new_accounts.csv"
)

OUT_PATTERNS = os.path.join(
    WORK_DIR,
    "HI-Small_SYNTH_FULL_Patterns.txt"
)

OUT_AUDIT = os.path.join(
    WORK_DIR,
    "HI-Small_SYNTH_FULL_episode_audit.csv"
)

OUT_MANIFEST = os.path.join(
    WORK_DIR,
    "HI-Small_SYNTH_FULL_manifest.json"
)

# ============================================================
# 1. LOAD STATIC DATA
# ============================================================

print("=" * 100)
print("CELL 20 — FULL-SCALE STREAMING SYNTHETIC GENERATOR")
print("=" * 100)

# ------------------------------------------------------------
# Templates
# ------------------------------------------------------------

with open(
    TEMPLATE_PATH,
    "r",
    encoding="utf-8"
) as f:

    template_manifest = json.load(f)

templates = template_manifest[
    "templates"
]

template_lookup = {
    str(t["template_id"]): t
    for t in templates
}

print(
    "\nIBM templates:",
    len(templates)
)

# ------------------------------------------------------------
# Episode plan
# ------------------------------------------------------------

episode_plan = pd.read_csv(
    EPISODE_PLAN_PATH,
    dtype=str
)

episode_plan[
    "transaction_count"
] = pd.to_numeric(
    episode_plan[
        "transaction_count"
    ],
    errors="raise"
).astype(int)

print(
    "Planned episodes:",
    f"{len(episode_plan):,}"
)

planned_target = int(
    episode_plan[
        "transaction_count"
    ].sum()
)

print(
    "Planned synthetic transactions:",
    f"{planned_target:,}"
)

EXPECTED_TARGET = 5_067_991

if planned_target != EXPECTED_TARGET:

    raise RuntimeError(
        f"Episode plan target mismatch: "
        f"{planned_target:,} != {EXPECTED_TARGET:,}"
    )

# ============================================================
# 2. LOAD BANK MAPPING LIBRARY
# ============================================================

print("\n" + "=" * 80)
print("1. LOADING CONNECTIVITY MAPPINGS")
print("=" * 80)

with open(
    MAPPING_LIBRARY_PATH,
    "r",
    encoding="utf-8"
) as f:

    mapping_manifest = json.load(f)

mapping_library = {}

for template_id, mappings in (
    mapping_manifest[
        "mappings"
    ].items()
):

    mapping_library[
        str(template_id)
    ] = [

        {
            int(node):
                str(bank)

            for node, bank
            in mapping.items()
        }

        for mapping in mappings
    ]

print(
    "Templates with mapping libraries:",
    len(mapping_library)
)

# ============================================================
# 3. BANK POOL
# ============================================================

print("\n" + "=" * 80)
print("2. LOADING BANK POOL")
print("=" * 80)

bank_pool = pd.read_csv(
    BANK_POOL_PATH,
    dtype=str
)

bank_pool[
    "normalized_bank_id"
] = bank_pool[
    "normalized_bank_id"
].astype(str)

bank_tx_id_map = {
    str(row["normalized_bank_id"]):
        str(row["canonical_transaction_bank_id"])
    for _, row in bank_pool.iterrows()
}

bank_name_map = {
    str(row["normalized_bank_id"]):
        str(row["Bank Name"])
    for _, row in bank_pool.iterrows()
}

print(
    "Banks:",
    len(bank_pool)
)

# ============================================================
# 4. ACCOUNT REGISTRY
# ============================================================

print("\n" + "=" * 80)
print("3. LOADING ACCOUNT REGISTRY")
print("=" * 80)

registry = pd.read_csv(
    ACCOUNT_REGISTRY_PATH,
    dtype=str
)

registry[
    "normalized_bank_id"
] = registry[
    "normalized_bank_id"
].astype(str)

for col in [
    "legitimate_source_tx_count",
    "legitimate_destination_tx_count",
    "legitimate_total_activity"
]:

    registry[col] = pd.to_numeric(
        registry[col],
        errors="coerce"
    ).fillna(0).astype(int)

registry[
    "generator_eligible"
] = (
    registry[
        "generator_eligible"
    ]
    .astype(str)
    .str.lower()
    .eq("true")
)

eligible = registry[
    registry[
        "generator_eligible"
    ]
].copy()

print(
    "Eligible accounts:",
    f"{len(eligible):,}"
)

# ------------------------------------------------------------
# Account pools
# ------------------------------------------------------------

account_pool = defaultdict(list)

for _, row in eligible.iterrows():

    bank = str(
        row["normalized_bank_id"]
    )

    account = str(
        row["Account Number"]
    )

    role = str(
        row["role"]
    )

    if role in {
        "source_only",
        "both"
    }:

        account_pool[
            (bank, "source")
        ].append(account)

    if role in {
        "destination_only",
        "both"
    }:

        account_pool[
            (bank, "destination")
        ].append(account)

    if role == "both":

        account_pool[
            (bank, "both")
        ].append(account)

    account_pool[
        (bank, "any")
    ].append(account)

for key in account_pool:

    random.shuffle(
        account_pool[key]
    )

pool_pointer = defaultdict(int)

# ============================================================
# 5. ACCOUNT DNA
# ============================================================

print("\n" + "=" * 80)
print("4. LOADING ACCOUNT GENERATION DNA")
print("=" * 80)

with open(
    ACCOUNT_PREFIX_PATH,
    "r",
    encoding="utf-8"
) as f:

    bank_prefix_sampler = json.load(f)

with open(
    ACCOUNT_GENERATOR_PATH,
    "r",
    encoding="utf-8"
) as f:

    account_generator_dna = json.load(f)

with open(
    ENTITY_DNA_PATH,
    "r",
    encoding="utf-8"
) as f:

    entity_dna = json.load(f)

position_models = (
    account_generator_dna[
        "position_models"
    ]
)

entity_position_models = (
    entity_dna[
        "entity_id_position_models"
    ]

)

name_prefixes = (
    entity_dna[
        "top_name_prefixes"
    ]
)

account_position_arrays = {}

for pos, entries in (
    position_models.items()
):

    chars = [
        x["char"]
        for x in entries
    ]

    probs = np.array(
        [
            x["probability"]
            for x in entries
        ],
        dtype=float
    )

    probs /= probs.sum()

    account_position_arrays[
        int(pos)
    ] = (
        chars,
        probs
    )

entity_position_arrays = {}

for pos, values in (
    entity_position_models.items()
):

    chars = list(
        values.keys()
    )

    probs = np.array(
        [
            values[c]["probability"]
            for c in chars
        ],
        dtype=float
    )

    probs /= probs.sum()

    entity_position_arrays[
        int(pos)
    ] = (
        chars,
        probs
    )

name_keys = list(
    name_prefixes.keys()
)

name_probs = np.array(
    [
        name_prefixes[k]
        for k in name_keys
    ],
    dtype=float
)

name_probs /= name_probs.sum()

# ------------------------------------------------------------
# Existing bank+account combinations
# ------------------------------------------------------------

existing_account_keys = set(
    (
        str(row["normalized_bank_id"]),
        str(row["Account Number"])
    )
    for _, row in registry.iterrows()
)

used_new_accounts = set()
used_new_entities = set()

# ============================================================
# 6. BEHAVIOR DNA SAMPLE
# ============================================================

print("\n" + "=" * 80)
print("5. LOADING LEGITIMATE TRANSACTION BEHAVIOR")
print("=" * 80)

behavior_parts = []

chunk_number = 0

for chunk in pd.read_csv(
    TRANS_PATH,
    usecols=[
        "Timestamp",
        "Amount Received",
        "Amount Paid",
        "Payment Currency",
        "Receiving Currency",
        "Payment Format",
        "Is Laundering"
    ],
    dtype=str,
    chunksize=500_000
):

    chunk_number += 1

    labels = pd.to_numeric(
        chunk[
            "Is Laundering"
        ],
        errors="coerce"
    ).fillna(0).astype(int)

    legit = chunk[
        labels == 0
    ].copy()

    if len(legit) == 0:
        continue

    n = min(
        10_000,
        len(legit)
    )

    behavior_parts.append(
        legit.sample(
            n=n,
            random_state=(
                SEED
                +
                chunk_number
            )
        )
    )

behavior = pd.concat(
    behavior_parts,
    ignore_index=True
)

behavior[
    "Timestamp"
] = pd.to_datetime(
    behavior[
        "Timestamp"
    ],
    errors="coerce"
)

behavior[
    "Amount Received"
] = pd.to_numeric(
    behavior[
        "Amount Received"
    ],
    errors="coerce"
)

behavior[
    "Amount Paid"
] = pd.to_numeric(
    behavior[
        "Amount Paid"
    ],
    errors="coerce"
)

behavior = behavior.dropna(
    subset=[
        "Timestamp",
        "Amount Received",
        "Amount Paid"
    ]
).reset_index(
    drop=True
)

print(
    "Behavior sample:",
    f"{len(behavior):,}"
)

time_values = (
    behavior[
        "Timestamp"
    ].tolist()
)

amount_values = (
    behavior[
        "Amount Received"
    ]
    .clip(
        lower=1e-6
    )
    .to_numpy(
        dtype=float
    )
)

payment_formats = (
    behavior[
        "Payment Format"
    ]
    .astype(str)
    .tolist()
)

payment_currencies = (
    behavior[
        "Payment Currency"
    ]
    .astype(str)
    .tolist()
)

receiving_by_payment = defaultdict(list)

for pay, recv in zip(
    behavior[
        "Payment Currency"
    ].astype(str),
    behavior[
        "Receiving Currency"
    ].astype(str)
):

    receiving_by_payment[
        pay
    ].append(
        recv
    )

dataset_min_ts = (
    behavior["Timestamp"].min()
)

dataset_max_ts = (
    behavior["Timestamp"].max()
)

dataset_max_amount = float(
    amount_values.max()
)

# ============================================================
# 7. GENERATORS
# ============================================================

def generate_entity_id():

    for _ in range(10000):

        chars = []

        for pos in range(
            1,
            10
        ):

            char_list, probs = (
                entity_position_arrays[
                    pos
                ]
            )

            chars.append(
                np.random.choice(
                    char_list,
                    p=probs
                )
            )

        value = "".join(chars)

        if value not in (
            used_new_entities
        ):

            used_new_entities.add(
                value
            )

            return value

    raise RuntimeError(
        "Could not generate Entity ID."
    )


def generate_entity_name():

    prefix = np.random.choice(
        name_keys,
        p=name_probs
    )

    number = np.random.randint(
        1,
        100000
    )

    return (
        f"{prefix} #{number}"
    )


def generate_new_account(
    bank
):

    bank = str(bank)

    prefix_data = (
        bank_prefix_sampler.get(
            bank
        )
    )

    for _ in range(10000):

        if (
            prefix_data
            and
            prefix_data["prefixes"]
        ):

            prefixes = [
                x["prefix"]
                for x
                in prefix_data[
                    "prefixes"
                ]
            ]

            probs = np.array(
                [
                    x["probability"]
                    for x
                    in prefix_data[
                        "prefixes"
                    ]
                ],
                dtype=float
            )

            probs /= probs.sum()

            prefix = np.random.choice(
                prefixes,
                p=probs
            )

        else:

            prefix = ""

            for pos in [
                1,
                2,
                3
            ]:

                chars, probs = (
                    account_position_arrays[
                        pos
                    ]
                )

                prefix += (
                    np.random.choice(
                        chars,
                        p=probs
                    )
                )

        chars = list(
            prefix
        )

        for pos in range(
            4,
            10
        ):

            char_list, probs = (
                account_position_arrays[
                    pos
                ]
            )

            chars.append(
                np.random.choice(
                    char_list,
                    p=probs
                )
            )

        account = "".join(
            chars
        )

        key = (
            bank,
            account
        )

        if (
            key not in
            existing_account_keys
            and
            key not in
            used_new_accounts
        ):

            used_new_accounts.add(
                key
            )

            new_accounts_file.writerow(
                [
                    bank_name_map[
                        bank
                    ],

                    bank_tx_id_map[
                        bank
                    ],

                    account,

                    generate_entity_id(),

                    generate_entity_name()
                ]
            )

            return account

    raise RuntimeError(
        f"Unable to generate account for bank {bank}"
    )


def get_account(
    bank,
    role,
    used_accounts
):

    bank = str(bank)

    if role == "source":

        role_order = [
            "source",
            "both",
            "any"
        ]

    elif role == "destination":

        role_order = [
            "destination",
            "both",
            "any"
        ]

    else:

        role_order = [
            "both",
            "any"
        ]

    for pool_role in role_order:

        pool = account_pool.get(
            (
                bank,
                pool_role
            ),
            []
        )

        if not pool:
            continue

        start = pool_pointer[
            (
                bank,
                pool_role
            )
        ]

        for offset in range(
            len(pool)
        ):

            idx = (
                start
                +
                offset
            ) % len(pool)

            account = pool[
                idx
            ]

            if account in used_accounts:
                continue

            pool_pointer[
                (
                    bank,
                    pool_role
                )
            ] = (
                idx + 1
            ) % len(pool)

            return (
                account,
                False
            )

    return (
        generate_new_account(bank),
        True
    )


def generate_transaction_id():

    for _ in range(1000):

        value = "".join(
            random.choices(
                string.ascii_uppercase
                +
                string.digits,
                k=16
            )
        )

        if value not in (
            used_transaction_ids
        ):

            used_transaction_ids.add(
                value
            )

            return value

    raise RuntimeError(
        "Unable to generate transaction ID."
    )

# ============================================================
# 8. PREPARE OUTPUT FILES
# ============================================================

print("\n" + "=" * 80)
print("6. OPENING STREAM OUTPUTS")
print("=" * 80)

# ------------------------------------------------------------
# Transaction CSV
# ------------------------------------------------------------

transaction_columns = [
    "transaction_id",
    "Timestamp",
    "From Bank",
    "Account",
    "To Bank",
    "Account.1",
    "Amount Received",
    "Receiving Currency",
    "Amount Paid",
    "Payment Currency",
    "Payment Format",
    "Is Laundering",
    "is_synthetic",
    "synthetic_episode_id",
    "typology",
    "source_template_id",
    "template_source_order"
]

trans_file = open(
    OUT_TRANS,
    "w",
    encoding="utf-8",
    buffering=1024 * 1024
)

transactions_csv = (
    __import__("csv").writer(
        trans_file
    )
)

transactions_csv.writerow(
    transaction_columns
)

# ------------------------------------------------------------
# New accounts CSV
# ------------------------------------------------------------

accounts_file = open(
    OUT_ACCOUNTS,
    "w",
    encoding="utf-8",
    buffering=1024 * 1024
)

new_accounts_file = (
    __import__("csv").writer(
        accounts_file
    )
)

new_accounts_file.writerow(
    [
        "Bank Name",
        "Bank ID",
        "Account Number",
        "Entity ID",
        "Entity Name"
    ]
)

# ------------------------------------------------------------
# Patterns
# ------------------------------------------------------------

patterns_file = open(
    OUT_PATTERNS,
    "w",
    encoding="utf-8",
    buffering=1024 * 1024
)

# ============================================================
# 9. GENERATION STATE
# ============================================================

used_transaction_ids = set()

total_transactions = 0
total_episodes = 0

typology_transactions = defaultdict(int)
typology_episodes = defaultdict(int)

new_accounts_total = 0

audit_buffer = []

# ============================================================
# 10. GENERATE ALL EPISODES
# ============================================================

print("\n" + "=" * 80)
print("7. FULL-SCALE GENERATION")
print("=" * 80)

for idx, episode in (
    episode_plan.iterrows()
):

    template_id = str(
        episode[
            "source_template_id"
        ]
    )

    typology = str(
        episode[
            "typology"
        ]
    )

    synthetic_episode_id = str(
        episode[
            "synthetic_episode_id"
        ]
    )

    template = template_lookup[
        template_id
    ]

    mappings = mapping_library[
        template_id
    ]

    if not mappings:
        raise RuntimeError(
            f"No mapping for {template_id}"
        )

    node_bank_mapping = random.choice(
        mappings
    )

    # --------------------------------------------------------
    # Node degree
    # --------------------------------------------------------
    in_degree = defaultdict(int)
    out_degree = defaultdict(int)

    for edge in template[
        "edges"
    ]:

        source = int(
            edge["source_node"]
        )

        destination = int(
            edge["destination_node"]
        )

        out_degree[
            source
        ] += 1

        in_degree[
            destination
        ] += 1

    node_roles = {}

    for node in template[
        "nodes"
    ]:

        node_id = int(
            node["node_id"]
        )

        if (
            in_degree[node_id] > 0
            and
            out_degree[node_id] > 0
        ):

            role = "both"

        elif out_degree[node_id] > 0:

            role = "source"

        else:

            role = "destination"

        node_roles[
            node_id
        ] = role

    # --------------------------------------------------------
    # Account mapping
    # --------------------------------------------------------
    node_account_mapping = {}

    used_accounts_episode = set()

    episode_new_accounts = 0

    for node_id in sorted(
        node_roles
    ):

        bank = str(
            node_bank_mapping[
                node_id
            ]
        )

        role = node_roles[
            node_id
        ]

        force_new = (
            np.random.random()
            <
            NEW_ACCOUNT_RATE
        )

        if force_new:

            account = (
                generate_new_account(
                    bank
                )
            )

            was_new = True

        else:

            account, was_new = (
                get_account(
                    bank,
                    role,
                    used_accounts_episode
                )
            )

        node_account_mapping[
            node_id
        ] = account

        used_accounts_episode.add(
            account
        )

        if was_new:
            episode_new_accounts += 1

    new_accounts_total += (
        episode_new_accounts
    )

    # --------------------------------------------------------
    # Time anchor
    # --------------------------------------------------------
    template_span = float(
        template[
            "episode_span_minutes"
        ]
    )

    anchor = random.choice(
        time_values
    )

    latest_anchor = (
        dataset_max_ts
        -
        pd.to_timedelta(
            template_span,
            unit="m"
        )
    )

    if anchor > latest_anchor:
        anchor = latest_anchor

    if anchor < dataset_min_ts:
        anchor = dataset_min_ts

    # --------------------------------------------------------
    # Amount scaling
    # --------------------------------------------------------
    target_median = float(
        random.choice(
            amount_values
        )
    )

    template_median = max(
        1e-9,
        float(
            template[
                "median_amount"
            ]
        )
    )

    amount_scale = (
        target_median
        /
        template_median
    )

    episode_amounts = []

    episode_edges = set()

    # --------------------------------------------------------
    # Patterns block begin
    # --------------------------------------------------------
    patterns_file.write(
        f'id="{synthetic_episode_id}"\n'
    )

    patterns_file.write(
        f"BEGIN LAUNDERING ATTEMPT - "
        f"{typology}: "
        f"Synthetic instance based on "
        f"IBM {typology} template\n"
    )

    # --------------------------------------------------------
    # Generate transactions in exact template order
    # --------------------------------------------------------
    for tx in template[
        "transactions"
    ]:

        source_node = int(
            tx["source_node"]
        )

        destination_node = int(
            tx["destination_node"]
        )

        source_bank_norm = str(
            node_bank_mapping[
                source_node
            ]
        )

        destination_bank_norm = str(
            node_bank_mapping[
                destination_node
            ]
        )

        source_account = (
            node_account_mapping[
                source_node
            ]
        )

        destination_account = (
            node_account_mapping[
                destination_node
            ]
        )

        # ----------------------------------------------------
        # Amount
        # ----------------------------------------------------
        template_amount = float(
            tx[
                "amount_received"
            ]
        )

        amount_received = max(
            1e-6,
            template_amount
            *
            amount_scale
        )

        original_received = max(
            1e-12,
            template_amount
        )

        original_paid = float(
            tx[
                "amount_paid"
            ]
        )

        paid_ratio = (
            original_paid
            /
            original_received
        )

        amount_paid = max(
            1e-6,
            amount_received
            *
            paid_ratio
        )

        if amount_received > dataset_max_amount:

            correction = (
                dataset_max_amount
                /
                amount_received
            )

            amount_received *= correction
            amount_paid *= correction

        # ----------------------------------------------------
        # Timestamp
        # ----------------------------------------------------
        timestamp = (
            anchor
            +
            pd.to_timedelta(
                float(
                    tx[
                        "relative_minutes"
                    ]
                ),
                unit="m"
            )
        )

        # ----------------------------------------------------
        # Behavior attributes
        # ----------------------------------------------------
        payment_format = random.choice(
            payment_formats
        )

        payment_currency = random.choice(
            payment_currencies
        )

        recv_candidates = (
            receiving_by_payment.get(
                payment_currency
            )
        )

        if recv_candidates:

            receiving_currency = (
                random.choice(
                    recv_candidates
                )
            )

        else:

            receiving_currency = (
                payment_currency
            )

        # ----------------------------------------------------
        # Canonical transaction bank IDs
        # ----------------------------------------------------
        source_bank_tx = (
            bank_tx_id_map[
                source_bank_norm
            ]
        )

        destination_bank_tx = (
            bank_tx_id_map[
                destination_bank_norm
            ]
        )

        # ----------------------------------------------------
        # Full directed edge
        # ----------------------------------------------------
        edge = (
            source_bank_tx,
            source_account,
            destination_bank_tx,
            destination_account
        )

        episode_edges.add(
            edge
        )

        # ----------------------------------------------------
        # Transaction ID
        # ----------------------------------------------------
        transaction_id = (
            generate_transaction_id()
        )

        # ----------------------------------------------------
        # Write transaction
        # ----------------------------------------------------
        transactions_csv.writerow(
            [
                transaction_id,

                timestamp.strftime(
                    "%Y-%m-%d %H:%M:%S"
                ),

                source_bank_tx,

                source_account,

                destination_bank_tx,

                destination_account,

                f"{amount_received:.6f}",

                receiving_currency,

                f"{amount_paid:.6f}",

                payment_currency,

                payment_format,

                1,

                1,

                synthetic_episode_id,

                typology,

                template_id,

                int(
                    tx[
                        "source_order"
                    ]
                )
            ]
        )

        # ----------------------------------------------------
        # Write Patterns transaction
        # ----------------------------------------------------
        patterns_file.write(
            ",".join(
                [
                    timestamp.strftime(
                        "%Y/%m/%d %H:%M"
                    ),

                    source_bank_tx,

                    source_account,

                    destination_bank_tx,

                    destination_account,

                    f"{amount_received:.6f}",

                    receiving_currency,

                    f"{amount_paid:.6f}",

                    payment_currency,

                    payment_format,

                    "1"
                ]
            )
            +
            "\n"
        )

        episode_amounts.append(
            amount_received
        )

        total_transactions += 1
        typology_transactions[
            typology
        ] += 1

    # --------------------------------------------------------
    # Patterns end
    # --------------------------------------------------------
    patterns_file.write(
        f"END LAUNDERING ATTEMPT - "
        f"{typology}\n"
    )

    # --------------------------------------------------------
    # Episode counters
    # --------------------------------------------------------
    total_episodes += 1

    typology_episodes[
        typology
    ] += 1

    audit_buffer.append(
        {
            "synthetic_episode_id":
                synthetic_episode_id,

            "typology":
                typology,

            "source_template_id":
                template_id,

            "transaction_count":
                len(
                    template[
                        "transactions"
                    ]
                ),

            "template_nodes":
                len(
                    template[
                        "nodes"
                    ]
                ),

            "generated_unique_accounts":
                len(
                    node_account_mapping
                ),

            "generated_unique_banks":
                len(
                    set(
                        node_bank_mapping.values()
                    )
                ),

            "new_accounts":
                episode_new_accounts,

            "unique_directed_edges":
                len(
                    episode_edges
                ),

            "duplicate_directed_edges":
                len(
                    template[
                        "transactions"
                    ]
                )
                -
                len(
                    episode_edges
                ),

            "template_span_minutes":
                template_span,

            "generated_median_amount":
                float(
                    np.median(
                        episode_amounts
                    )
                )
        }
    )

    # --------------------------------------------------------
    # Flush audit periodically
    # --------------------------------------------------------
    if (
        total_episodes
        %
        FLUSH_EVERY_EPISODES
        ==
        0
    ):

        print(
            f"Episodes: "
            f"{total_episodes:,}/"
            f"{len(episode_plan):,}"
            f" | Transactions: "
            f"{total_transactions:,}"
            f" | New accounts: "
            f"{new_accounts_total:,}"
        )

# ============================================================
# 11. CLOSE FILES
# ============================================================

trans_file.close()
accounts_file.close()
patterns_file.close()

# ============================================================
# 12. FINAL EXACTNESS
# ============================================================

print("\n" + "=" * 80)
print("8. FINAL GENERATION COUNTS")
print("=" * 80)

print(
    "Episodes generated:",
    f"{total_episodes:,}"
)

print(
    "Episodes planned:",
    f"{len(episode_plan):,}"
)

print(
    "Transactions generated:",
    f"{total_transactions:,}"
)

print(
    "Transactions planned:",
    f"{planned_target:,}"
)

print(
    "New accounts generated:",
    f"{new_accounts_total:,}"
)

if (
    total_episodes
    !=
    len(episode_plan)
):

    raise RuntimeError(
        "Episode count mismatch."
    )

if (
    total_transactions
    !=
    planned_target
):

    raise RuntimeError(
        "Transaction count mismatch."
    )

# ============================================================
# 13. AUDIT DATAFRAME
# ============================================================

audit_df = pd.DataFrame(
    audit_buffer
)

audit_df.to_csv(
    OUT_AUDIT,
    index=False
)

# ============================================================
# 14. PATTERN FILE COUNTS
# ============================================================

print("\n" + "=" * 80)
print("9. PATTERNS FILE VALIDATION")
print("=" * 80)

with open(
    OUT_PATTERNS,
    "r",
    encoding="utf-8"
) as f:

    pattern_lines = [
        x.rstrip("\n")
        for x in f
    ]

pattern_ids = [
    x for x in pattern_lines
    if x.startswith(
        'id="'
    )
]

pattern_begins = [
    x for x in pattern_lines
    if x.startswith(
        "BEGIN LAUNDERING ATTEMPT"
    )
]

pattern_ends = [
    x for x in pattern_lines
    if x.startswith(
        "END LAUNDERING ATTEMPT"
    )
]

pattern_transaction_count = 0

for line in pattern_lines:

    parts = line.split(",")

    if len(parts) != 11:
        continue

    parsed = pd.to_datetime(
        parts[0],
        format="%Y/%m/%d %H:%M",
        errors="coerce"
    )

    if not pd.isna(parsed):
        pattern_transaction_count += 1

print(
    "Pattern IDs:",
    len(pattern_ids)
)

print(
    "BEGIN markers:",
    len(pattern_begins)
)

print(
    "END markers:",
    len(pattern_ends)
)

print(
    "Pattern transaction rows:",
    pattern_transaction_count
)

# ============================================================
# 15. BUILD MANIFEST
# ============================================================

manifest = {

    "dataset":
        "IBM HI-Small",

    "generator_version":
        "streaming_connectivity_constrained_v3",

    "seed":
        SEED,

    "target_synthetic_transactions":
        EXPECTED_TARGET,

    "generated_synthetic_transactions":
        int(total_transactions),

    "target_episodes":
        int(len(episode_plan)),

    "generated_episodes":
        int(total_episodes),

    "new_accounts_generated":
        int(new_accounts_total),

    "new_account_rate":
        float(NEW_ACCOUNT_RATE),

    "templates_available":
        int(len(templates)),

    "templates_used":
        int(
            episode_plan[
                "source_template_id"
            ].nunique()
        ),

    "validated_legitimate_bank_mappings":
        int(
            mapping_manifest[
                "total_valid_mappings"
            ]
        ),

    "typology_transactions":
        {
            str(k): int(v)
            for k, v
            in typology_transactions.items()
        },

    "typology_episodes":
        {
            str(k): int(v)
            for k, v
            in typology_episodes.items()
        },

    "pattern_file_ids":
        int(len(pattern_ids)),

    "pattern_file_begin_markers":
        int(len(pattern_begins)),

    "pattern_file_end_markers":
        int(len(pattern_ends)),

    "pattern_file_transaction_rows":
        int(pattern_transaction_count),

    "outputs": {

        "transactions":
            OUT_TRANS,

        "new_accounts":
            OUT_ACCOUNTS,

        "patterns":
            OUT_PATTERNS,

        "episode_audit":
            OUT_AUDIT
    }
}

with open(
    OUT_MANIFEST,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        manifest,
        f,
        indent=2
    )

# ============================================================
# 16. FINAL
# ============================================================

print("\n" + "=" * 100)
print("✅ CELL 20 COMPLETE — FULL SYNTHETIC GENERATION")
print("=" * 100)

print(
    "\nSynthetic laundering transactions:",
    f"{total_transactions:,}"
)

print(
    "Required:",
    f"{EXPECTED_TARGET:,}"
)

print(
    "Exact transaction target:",
    total_transactions
    ==
    EXPECTED_TARGET
)

print(
    "Synthetic laundering episodes:",
    f"{total_episodes:,}"
)

print(
    "New accounts:",
    f"{new_accounts_total:,}"
)

print(
    "Templates used:",
    f"{episode_plan['source_template_id'].nunique():,}"
)

print(
    "\nPatterns IDs:",
    len(pattern_ids)
)

print(
    "Patterns BEGIN:",
    len(pattern_begins)
)

print(
    "Patterns END:",
    len(pattern_ends)
)

print(
    "Patterns transaction rows:",
    pattern_transaction_count
)

print(
    "Patterns exact:",
    (
        len(pattern_ids)
        ==
        total_episodes
        and
        len(pattern_begins)
        ==
        total_episodes
        and
        len(pattern_ends)
        ==
        total_episodes
        and
        pattern_transaction_count
        ==
        total_transactions
    )
)

print("\nSaved:")
print(
    OUT_TRANS
)
print(
    OUT_ACCOUNTS
)
print(
    OUT_PATTERNS
)
print(
    OUT_AUDIT
)
print(
    OUT_MANIFEST
)

print(
    "\nORIGINAL HI-SMALL FILES WERE NOT MODIFIED."
)

print("=" * 100)

====================================================================================================
CELL 20 — FULL-SCALE STREAMING SYNTHETIC GENERATOR
====================================================================================================

IBM templates: 370
Planned episodes: 584,706
Planned synthetic transactions: 5,067,991

================================================================================
1. LOADING CONNECTIVITY MAPPINGS
================================================================================
Templates with mapping libraries: 370

================================================================================
2. LOADING BANK POOL
================================================================================
Banks: 30470

================================================================================
3. LOADING ACCOUNT REGISTRY
================================================================================
Eligible accounts: 508,731

================================================================================
4. LOADING ACCOUNT GENERATION DNA
================================================================================

================================================================================
5. LOADING LEGITIMATE TRANSACTION BEHAVIOR
================================================================================
Behavior sample: 110,000

================================================================================
6. OPENING STREAM OUTPUTS
================================================================================

================================================================================
7. FULL-SCALE GENERATION
================================================================================
Episodes: 500/584,706 | Transactions: 2,611 | New accounts: 397
Episodes: 1,000/584,706 | Transactions: 5,356 | New accounts: 803
Episodes: 1,500/584,706 | Transactions: 8,227 | New accounts: 1,203
Episodes: 2,000/584,706 | Transactions: 11,081 | New accounts: 1,653
Episodes: 2,500/584,706 | Transactions: 13,595 | New accounts: 2,008
Episodes: 3,000/584,706 | Transactions: 16,279 | New accounts: 2,400
Episodes: 3,500/584,706 | Transactions: 19,015 | New accounts: 2,794
Episodes: 4,000/584,706 | Transactions: 21,628 | New accounts: 3,171
Episodes: 4,500/584,706 | Transactions: 24,339 | New accounts: 3,565
Episodes: 5,000/584,706 | Transactions: 27,018 | New accounts: 3,968
Episodes: 5,500/584,706 | Transactions: 29,684 | New accounts: 4,348
Episodes: 6,000/584,706 | Transactions: 32,420 | New accounts: 4,764
Episodes: 6,500/584,706 | Transactions: 34,987 | New accounts: 5,144
Episodes: 7,000/584,706 | Transactions: 37,539 | New accounts: 5,519
Episodes: 7,500/584,706 | Transactions: 40,294 | New accounts: 5,911
Episodes: 8,000/584,706 | Transactions: 42,804 | New accounts: 6,300
Episodes: 8,500/584,706 | Transactions: 45,605 | New accounts: 6,703
Episodes: 9,000/584,706 | Transactions: 48,354 | New accounts: 7,124
Episodes: 9,500/584,706 | Transactions: 50,989 | New accounts: 7,494
Episodes: 12,500/584,706 | Transactions: 66,596 | New accounts: 9,812
Episodes: 13,000/584,706 | Transactions: 69,325 | New accounts: 10,206
Episodes: 13,500/584,706 | Transactions: 71,986 | New accounts: 10,558
Episodes: 14,000/584,706 | Transactions: 74,636 | New accounts: 10,918
Episodes: 14,500/584,706 | Transactions: 77,299 | New accounts: 11,325
Episodes: 15,000/584,706 | Transactions: 79,929 | New accounts: 11,717
Episodes: 15,500/584,706 | Transactions: 82,758 | New accounts: 12,119
Episodes: 16,000/584,706 | Transactions: 85,499 | New accounts: 12,519
Episodes: 16,500/584,706 | Transactions: 88,227 | New accounts: 12,954
Episodes: 17,000/584,706 | Transactions: 90,836 | New accounts: 13,341
Episodes: 17,500/584,706 | Transactions: 93,484 | New accounts: 13,717
Episodes: 18,000/584,706 | Transactions: 96,168 | New accounts: 14,109
Episodes: 18,500/584,706 | Transactions: 98,794 | New accounts: 14,499
Episodes: 19,000/584,706 | Transactions: 101,512 | New accounts: 14,887
Episodes: 19,500/584,706 | Transactions: 104,018 | New accounts: 15,271
Episodes: 20,000/584,706 | Transactions: 106,733 | New accounts: 15,695
Episodes: 20,500/584,706 | Transactions: 109,308 | New accounts: 16,103
Episodes: 21,000/584,706 | Transactions: 112,083 | New accounts: 16,494
Episodes: 21,500/584,706 | Transactions: 114,778 | New accounts: 16,875
Episodes: 22,000/584,706 | Transactions: 117,582 | New accounts: 17,297
Episodes: 22,500/584,706 | Transactions: 120,163 | New accounts: 17,694
Episodes: 23,000/584,706 | Transactions: 122,811 | New accounts: 18,057
Episodes: 23,500/584,706 | Transactions: 125,397 | New accounts: 18,458
Episodes: 24,000/584,706 | Transactions: 128,109 | New accounts: 18,856
Episodes: 24,500/584,706 | Transactions: 130,772 | New accounts: 19,263
Episodes: 25,000/584,706 | Transactions: 133,510 | New accounts: 19,650
Episodes: 25,500/584,706 | Transactions: 136,229 | New accounts: 20,045
Episodes: 26,000/584,706 | Transactions: 138,879 | New accounts: 20,435
Episodes: 26,500/584,706 | Transactions: 141,658 | New accounts: 20,840
Episodes: 27,000/584,706 | Transactions: 144,321 | New accounts: 21,227
Episodes: 27,500/584,706 | Transactions: 146,908 | New accounts: 21,631
Episodes: 28,000/584,706 | Transactions: 149,623 | New accounts: 22,030
Episodes: 28,500/584,706 | Transactions: 152,209 | New accounts: 22,407
Episodes: 29,000/584,706 | Transactions: 154,887 | New accounts: 22,788
Episodes: 29,500/584,706 | Transactions: 157,257 | New accounts: 23,135
Episodes: 30,000/584,706 | Transactions: 159,890 | New accounts: 23,534
Episodes: 30,500/584,706 | Transactions: 162,895 | New accounts: 23,983
Episodes: 31,000/584,706 | Transactions: 165,636 | New accounts: 24,346
Episodes: 31,500/584,706 | Transactions: 168,427 | New accounts: 24,754
Episodes: 32,000/584,706 | Transactions: 171,027 | New accounts: 25,105
Episodes: 32,500/584,706 | Transactions: 173,425 | New accounts: 25,450
Episodes: 33,000/584,706 | Transactions: 176,308 | New accounts: 25,866
Episodes: 33,500/584,706 | Transactions: 178,865 | New accounts: 26,257
Episodes: 34,000/584,706 | Transactions: 181,298 | New accounts: 26,609
Episodes: 34,500/584,706 | Transactions: 183,916 | New accounts: 27,019
Episodes: 35,000/584,706 | Transactions: 186,613 | New accounts: 27,427
Episodes: 35,500/584,706 | Transactions: 189,334 | New accounts: 27,794
Episodes: 36,000/584,706 | Transactions: 191,830 | New accounts: 28,130
Episodes: 36,500/584,706 | Transactions: 194,576 | New accounts: 28,544
Episodes: 37,000/584,706 | Transactions: 197,371 | New accounts: 28,970
Episodes: 37,500/584,706 | Transactions: 200,255 | New accounts: 29,360
Episodes: 38,000/584,706 | Transactions: 202,720 | New accounts: 29,736
Episodes: 38,500/584,706 | Transactions: 205,521 | New accounts: 30,151
Episodes: 39,000/584,706 | Transactions: 208,481 | New accounts: 30,589
Episodes: 39,500/584,706 | Transactions: 211,082 | New accounts: 30,970
Episodes: 40,000/584,706 | Transactions: 213,650 | New accounts: 31,358
Episodes: 40,500/584,706 | Transactions: 216,203 | New accounts: 31,725
Episodes: 41,000/584,706 | Transactions: 219,022 | New accounts: 32,133
Episodes: 41,500/584,706 | Transactions: 221,545 | New accounts: 32,513
Episodes: 42,000/584,706 | Transactions: 224,235 | New accounts: 32,891
Episodes: 42,500/584,706 | Transactions: 227,250 | New accounts: 33,343
Episodes: 43,000/584,706 | Transactions: 229,881 | New accounts: 33,709
Episodes: 43,500/584,706 | Transactions: 232,485 | New accounts: 34,081
Episodes: 44,000/584,706 | Transactions: 235,190 | New accounts: 34,460
Episodes: 44,500/584,706 | Transactions: 237,910 | New accounts: 34,812
Episodes: 45,000/584,706 | Transactions: 240,563 | New accounts: 35,223
Episodes: 45,500/584,706 | Transactions: 243,313 | New accounts: 35,610
Episodes: 46,000/584,706 | Transactions: 246,023 | New accounts: 35,999
Episodes: 46,500/584,706 | Transactions: 248,741 | New accounts: 36,430
Episodes: 47,000/584,706 | Transactions: 251,470 | New accounts: 36,833
Episodes: 47,500/584,706 | Transactions: 254,126 | New accounts: 37,226
Episodes: 48,000/584,706 | Transactions: 256,931 | New accounts: 37,600
Episodes: 48,500/584,706 | Transactions: 259,596 | New accounts: 38,002
Episodes: 49,000/584,706 | Transactions: 262,221 | New accounts: 38,413
Episodes: 49,500/584,706 | Transactions: 264,944 | New accounts: 38,802
Episodes: 50,000/584,706 | Transactions: 267,694 | New accounts: 39,220
Episodes: 50,500/584,706 | Transactions: 270,377 | New accounts: 39,605
Episodes: 51,000/584,706 | Transactions: 273,323 | New accounts: 40,042
Episodes: 51,500/584,706 | Transactions: 276,023 | New accounts: 40,450
Episodes: 52,000/584,706 | Transactions: 278,721 | New accounts: 40,836
Episodes: 52,500/584,706 | Transactions: 281,456 | New accounts: 41,250
Episodes: 53,000/584,706 | Transactions: 284,020 | New accounts: 41,603
Episodes: 53,500/584,706 | Transactions: 286,575 | New accounts: 41,985
Episodes: 54,000/584,706 | Transactions: 289,358 | New accounts: 42,361
Episodes: 54,500/584,706 | Transactions: 291,988 | New accounts: 42,752
Episodes: 55,000/584,706 | Transactions: 294,680 | New accounts: 43,145
Episodes: 55,500/584,706 | Transactions: 297,433 | New accounts: 43,545
Episodes: 56,000/584,706 | Transactions: 300,133 | New accounts: 43,945
Episodes: 56,500/584,706 | Transactions: 302,704 | New accounts: 44,294
Episodes: 57,000/584,706 | Transactions: 305,383 | New accounts: 44,677
Episodes: 57,500/584,706 | Transactions: 308,115 | New accounts: 45,055
Episodes: 58,000/584,706 | Transactions: 310,711 | New accounts: 45,458
Episodes: 58,500/584,706 | Transactions: 313,447 | New accounts: 45,848
Episodes: 59,000/584,706 | Transactions: 316,162 | New accounts: 46,253
Episodes: 59,500/584,706 | Transactions: 318,802 | New accounts: 46,624
Episodes: 60,000/584,706 | Transactions: 321,476 | New accounts: 46,972
Episodes: 60,500/584,706 | Transactions: 324,121 | New accounts: 47,345
Episodes: 61,000/584,706 | Transactions: 326,740 | New accounts: 47,712
Episodes: 61,500/584,706 | Transactions: 329,341 | New accounts: 48,145
Episodes: 62,000/584,706 | Transactions: 331,876 | New accounts: 48,533
Episodes: 62,500/584,706 | Transactions: 334,648 | New accounts: 48,932
Episodes: 63,000/584,706 | Transactions: 337,276 | New accounts: 49,347
Episodes: 63,500/584,706 | Transactions: 340,171 | New accounts: 49,776
Episodes: 64,000/584,706 | Transactions: 342,898 | New accounts: 50,158
Episodes: 64,500/584,706 | Transactions: 345,605 | New accounts: 50,559
Episodes: 65,000/584,706 | Transactions: 348,337 | New accounts: 50,964
Episodes: 65,500/584,706 | Transactions: 351,058 | New accounts: 51,366
Episodes: 66,000/584,706 | Transactions: 353,754 | New accounts: 51,765
Episodes: 66,500/584,706 | Transactions: 356,443 | New accounts: 52,139
Episodes: 67,000/584,706 | Transactions: 359,103 | New accounts: 52,506
Episodes: 67,500/584,706 | Transactions: 361,709 | New accounts: 52,893
Episodes: 68,000/584,706 | Transactions: 364,457 | New accounts: 53,273
Episodes: 68,500/584,706 | Transactions: 367,073 | New accounts: 53,666
Episodes: 69,000/584,706 | Transactions: 369,862 | New accounts: 54,035
Episodes: 69,500/584,706 | Transactions: 372,564 | New accounts: 54,415
Episodes: 70,000/584,706 | Transactions: 375,259 | New accounts: 54,810
Episodes: 70,500/584,706 | Transactions: 377,772 | New accounts: 55,152
Episodes: 71,000/584,706 | Transactions: 380,623 | New accounts: 55,587
Episodes: 71,500/584,706 | Transactions: 383,274 | New accounts: 55,963
Episodes: 72,000/584,706 | Transactions: 386,018 | New accounts: 56,389
Episodes: 72,500/584,706 | Transactions: 388,692 | New accounts: 56,818
Episodes: 73,000/584,706 | Transactions: 391,415 | New accounts: 57,221
Episodes: 73,500/584,706 | Transactions: 394,036 | New accounts: 57,622
Episodes: 74,000/584,706 | Transactions: 396,755 | New accounts: 58,038
Episodes: 74,500/584,706 | Transactions: 399,467 | New accounts: 58,422
Episodes: 75,000/584,706 | Transactions: 402,249 | New accounts: 58,796
Episodes: 75,500/584,706 | Transactions: 404,939 | New accounts: 59,184
Episodes: 76,000/584,706 | Transactions: 407,778 | New accounts: 59,614
Episodes: 76,500/584,706 | Transactions: 410,244 | New accounts: 59,960
Episodes: 77,000/584,706 | Transactions: 412,985 | New accounts: 60,341
Episodes: 77,500/584,706 | Transactions: 415,560 | New accounts: 60,701
Episodes: 78,000/584,706 | Transactions: 418,150 | New accounts: 60,840
Episodes: 78,500/584,706 | Transactions: 420,690 | New accounts: 60,986
Episodes: 79,000/584,706 | Transactions: 423,254 | New accounts: 61,145
Episodes: 79,500/584,706 | Transactions: 426,014 | New accounts: 61,321
Episodes: 80,000/584,706 | Transactions: 428,586 | New accounts: 61,469
Episodes: 80,500/584,706 | Transactions: 431,240 | New accounts: 61,619
Episodes: 81,000/584,706 | Transactions: 433,853 | New accounts: 61,782
Episodes: 81,500/584,706 | Transactions: 436,502 | New accounts: 61,970
Episodes: 82,000/584,706 | Transactions: 439,139 | New accounts: 62,129
Episodes: 82,500/584,706 | Transactions: 441,767 | New accounts: 62,286
Episodes: 83,000/584,706 | Transactions: 444,442 | New accounts: 62,427
Episodes: 83,500/584,706 | Transactions: 446,998 | New accounts: 62,569
Episodes: 84,000/584,706 | Transactions: 449,785 | New accounts: 62,725
Episodes: 84,500/584,706 | Transactions: 452,355 | New accounts: 62,878
Episodes: 85,000/584,706 | Transactions: 454,966 | New accounts: 63,032
Episodes: 85,500/584,706 | Transactions: 457,604 | New accounts: 63,173
Episodes: 86,000/584,706 | Transactions: 460,316 | New accounts: 63,330
Episodes: 86,500/584,706 | Transactions: 463,159 | New accounts: 63,487
Episodes: 87,000/584,706 | Transactions: 465,922 | New accounts: 63,675
Episodes: 87,500/584,706 | Transactions: 468,582 | New accounts: 63,830
Episodes: 88,000/584,706 | Transactions: 471,274 | New accounts: 63,983
Episodes: 88,500/584,706 | Transactions: 473,973 | New accounts: 64,145
Episodes: 89,000/584,706 | Transactions: 476,565 | New accounts: 64,291
Episodes: 89,500/584,706 | Transactions: 479,213 | New accounts: 64,434
Episodes: 90,000/584,706 | Transactions: 481,819 | New accounts: 64,580
Episodes: 90,500/584,706 | Transactions: 484,510 | New accounts: 64,725
Episodes: 91,000/584,706 | Transactions: 487,126 | New accounts: 64,874
Episodes: 91,500/584,706 | Transactions: 489,751 | New accounts: 65,028
Episodes: 92,000/584,706 | Transactions: 492,445 | New accounts: 65,200
Episodes: 92,500/584,706 | Transactions: 495,116 | New accounts: 65,363
Episodes: 93,000/584,706 | Transactions: 497,746 | New accounts: 65,513
Episodes: 93,500/584,706 | Transactions: 500,369 | New accounts: 65,658
Episodes: 94,000/584,706 | Transactions: 502,982 | New accounts: 65,806
Episodes: 94,500/584,706 | Transactions: 505,672 | New accounts: 65,974
Episodes: 95,000/584,706 | Transactions: 508,399 | New accounts: 66,129
Episodes: 95,500/584,706 | Transactions: 511,007 | New accounts: 66,275
Episodes: 96,000/584,706 | Transactions: 513,648 | New accounts: 66,437
Episodes: 96,500/584,706 | Transactions: 516,181 | New accounts: 66,595
Episodes: 97,000/584,706 | Transactions: 518,806 | New accounts: 66,728
Episodes: 97,500/584,706 | Transactions: 521,472 | New accounts: 66,856
Episodes: 98,000/584,706 | Transactions: 524,176 | New accounts: 67,015
Episodes: 98,500/584,706 | Transactions: 526,858 | New accounts: 67,163
Episodes: 99,000/584,706 | Transactions: 529,489 | New accounts: 67,321
Episodes: 99,500/584,706 | Transactions: 532,107 | New accounts: 67,477
Episodes: 100,000/584,706 | Transactions: 534,693 | New accounts: 67,626
Episodes: 100,500/584,706 | Transactions: 537,402 | New accounts: 67,780
Episodes: 101,000/584,706 | Transactions: 540,132 | New accounts: 67,941
Episodes: 101,500/584,706 | Transactions: 542,711 | New accounts: 68,081
Episodes: 102,000/584,706 | Transactions: 545,394 | New accounts: 68,239
Episodes: 102,500/584,706 | Transactions: 548,155 | New accounts: 68,385
Episodes: 103,000/584,706 | Transactions: 550,882 | New accounts: 68,533
Episodes: 103,500/584,706 | Transactions: 553,572 | New accounts: 68,674
Episodes: 104,000/584,706 | Transactions: 556,208 | New accounts: 68,831
Episodes: 104,500/584,706 | Transactions: 559,016 | New accounts: 69,005
Episodes: 105,000/584,706 | Transactions: 561,663 | New accounts: 69,152
Episodes: 105,500/584,706 | Transactions: 564,381 | New accounts: 69,309
Episodes: 106,000/584,706 | Transactions: 566,938 | New accounts: 69,471
Episodes: 106,500/584,706 | Transactions: 569,628 | New accounts: 69,617
Episodes: 107,000/584,706 | Transactions: 572,274 | New accounts: 69,787
Episodes: 107,500/584,706 | Transactions: 574,933 | New accounts: 69,923
Episodes: 108,000/584,706 | Transactions: 577,592 | New accounts: 70,075
Episodes: 108,500/584,706 | Transactions: 580,106 | New accounts: 70,221
Episodes: 109,000/584,706 | Transactions: 582,739 | New accounts: 70,369
Episodes: 109,500/584,706 | Transactions: 585,412 | New accounts: 70,513
Episodes: 110,000/584,706 | Transactions: 588,107 | New accounts: 70,658
Episodes: 110,500/584,706 | Transactions: 590,743 | New accounts: 70,801
Episodes: 111,000/584,706 | Transactions: 593,404 | New accounts: 70,947
Episodes: 111,500/584,706 | Transactions: 596,037 | New accounts: 71,092
Episodes: 112,000/584,706 | Transactions: 598,648 | New accounts: 71,237
Episodes: 112,500/584,706 | Transactions: 601,347 | New accounts: 71,390
Episodes: 113,000/584,706 | Transactions: 603,827 | New accounts: 71,542
Episodes: 113,500/584,706 | Transactions: 606,502 | New accounts: 71,684
Episodes: 114,000/584,706 | Transactions: 609,192 | New accounts: 71,856
Episodes: 114,500/584,706 | Transactions: 611,821 | New accounts: 72,009
Episodes: 115,000/584,706 | Transactions: 614,659 | New accounts: 72,164
Episodes: 115,500/584,706 | Transactions: 617,354 | New accounts: 72,321
Episodes: 116,000/584,706 | Transactions: 620,044 | New accounts: 72,458
Episodes: 116,500/584,706 | Transactions: 622,840 | New accounts: 72,596
Episodes: 117,000/584,706 | Transactions: 625,452 | New accounts: 72,749
Episodes: 117,500/584,706 | Transactions: 628,090 | New accounts: 72,918
Episodes: 118,000/584,706 | Transactions: 630,788 | New accounts: 73,056
Episodes: 118,500/584,706 | Transactions: 633,403 | New accounts: 73,202
Episodes: 119,000/584,706 | Transactions: 636,058 | New accounts: 73,350
Episodes: 119,500/584,706 | Transactions: 638,755 | New accounts: 73,517
Episodes: 120,000/584,706 | Transactions: 641,455 | New accounts: 73,653
Episodes: 120,500/584,706 | Transactions: 644,206 | New accounts: 73,819
Episodes: 121,000/584,706 | Transactions: 646,795 | New accounts: 73,988
Episodes: 121,500/584,706 | Transactions: 649,519 | New accounts: 74,147
Episodes: 122,000/584,706 | Transactions: 652,176 | New accounts: 74,306
Episodes: 122,500/584,706 | Transactions: 654,630 | New accounts: 74,445
Episodes: 123,000/584,706 | Transactions: 657,299 | New accounts: 74,589
Episodes: 123,500/584,706 | Transactions: 660,059 | New accounts: 74,751
Episodes: 124,000/584,706 | Transactions: 662,632 | New accounts: 74,892
Episodes: 124,500/584,706 | Transactions: 665,351 | New accounts: 75,061
Episodes: 125,000/584,706 | Transactions: 667,931 | New accounts: 75,215
Episodes: 125,500/584,706 | Transactions: 670,580 | New accounts: 75,367
Episodes: 126,000/584,706 | Transactions: 673,348 | New accounts: 75,548
Episodes: 126,500/584,706 | Transactions: 676,085 | New accounts: 75,702
Episodes: 127,000/584,706 | Transactions: 678,820 | New accounts: 75,843
Episodes: 127,500/584,706 | Transactions: 681,549 | New accounts: 76,005
Episodes: 128,000/584,706 | Transactions: 684,238 | New accounts: 76,153
Episodes: 128,500/584,706 | Transactions: 687,007 | New accounts: 76,306
Episodes: 129,000/584,706 | Transactions: 689,658 | New accounts: 76,480

KeyboardInterrupt:

In [31]:
# ==================================================================================================
# CELL 21 — STREAMING FINAL SYNTHETIC DATA AUDIT
# FULL REPLACEMENT — AUTO-DISCOVERS ORIGINAL ACCOUNTS FILE
#
# IMPORTANT:
#   - DO NOT regenerate anything
#   - Uses the already-generated full synthetic dataset
#   - Automatically searches Kaggle input/workspace for HI-Small_accounts.csv
#   - Creates the missing manifest
# ==================================================================================================

import os
import csv
import json
import re
import math
import glob
import subprocess
from collections import Counter
from datetime import datetime


# --------------------------------------------------------------------------------------------------
# PATHS
# --------------------------------------------------------------------------------------------------

BASE = "/kaggle/working/AML_GNN_ONLY/data"

TRANSACTIONS_FILE = os.path.join(
    BASE,
    "HI-Small_SYNTH_FULL_transactions.csv"
)

NEW_ACCOUNTS_FILE = os.path.join(
    BASE,
    "HI-Small_SYNTH_FULL_new_accounts.csv"
)

PATTERNS_FILE = os.path.join(
    BASE,
    "HI-Small_SYNTH_FULL_Patterns.txt"
)

EPISODE_AUDIT_FILE = os.path.join(
    BASE,
    "HI-Small_SYNTH_FULL_episode_audit.csv"
)

MANIFEST_FILE = os.path.join(
    BASE,
    "HI-Small_SYNTH_FULL_manifest.json"
)

LEGIT_PAIRS_FILE = os.path.join(
    BASE,
    "HI-Small_legitimate_bank_pairs.csv"
)

EXPECTED_TX = 5_067_991
EXPECTED_EPISODES = 584_706

EXPECTED_TYPOLOGY_TX = {
    "BIPARTITE":        415_357,
    "CYCLE":            453_261,
    "FAN-IN":           502_219,
    "FAN-OUT":          540_123,
    "GATHER-SCATTER": 1_130_782,
    "RANDOM":           301_647,
    "SCATTER-GATHER":   988_646,
    "STACK":            735_956,
}


# --------------------------------------------------------------------------------------------------
# HELPERS
# --------------------------------------------------------------------------------------------------

def canonical_bank(x):
    if x is None:
        return None

    s = str(x).strip()

    if not s:
        return None

    if s.isdigit():
        return str(int(s))

    return s.upper()


def file_size_mb(path):
    return os.path.getsize(path) / (1024 * 1024)


def safe_float(x):
    try:
        return float(x)
    except Exception:
        return None


def safe_int(x):
    try:
        return int(x)
    except Exception:
        return None


def find_column(header, candidates):

    if header is None:
        return None

    lower_map = {
        str(h).strip().lower(): h
        for h in header
    }

    # Exact normalized match
    for c in candidates:

        key = c.strip().lower()

        if key in lower_map:
            return lower_map[key]

    # Substring fallback
    for h in header:

        h_low = str(h).strip().lower()

        for c in candidates:

            if c.strip().lower() in h_low:
                return h

    return None


def require_file(path, label):

    if not os.path.exists(path):

        raise FileNotFoundError(
            f"Missing required {label}: {path}"
        )


# --------------------------------------------------------------------------------------------------
# ORIGINAL HI-SMALL ACCOUNTS FILE AUTO-DISCOVERY
# --------------------------------------------------------------------------------------------------

def discover_original_accounts():

    candidates = []

    search_roots = [
        "/kaggle/input",
        "/kaggle/working",
    ]

    for root in search_roots:

        if not os.path.exists(root):
            continue

        pattern = os.path.join(
            root,
            "**",
            "HI-Small_accounts.csv"
        )

        try:

            matches = glob.glob(
                pattern,
                recursive=True
            )

            candidates.extend(matches)

        except Exception:
            pass


    # Remove duplicates
    candidates = sorted(
        set(
            os.path.abspath(x)
            for x in candidates
            if os.path.isfile(x)
        )
    )


    # Prefer exact file in BASE if ever present
    base_exact = os.path.join(
        BASE,
        "HI-Small_accounts.csv"
    )

    if os.path.isfile(base_exact):
        return base_exact, candidates


    if len(candidates) == 0:
        return None, candidates


    # Prefer files under Kaggle input
    input_candidates = [
        x for x in candidates
        if x.startswith("/kaggle/input/")
    ]

    if len(input_candidates) == 1:
        return input_candidates[0], candidates

    if len(input_candidates) > 1:

        # Exact filename already guaranteed.
        # Pick the smallest path depth / deterministic first.
        input_candidates = sorted(
            input_candidates,
            key=lambda x: (
                x.count(os.sep),
                x
            )
        )

        return input_candidates[0], candidates


    return candidates[0], candidates


# --------------------------------------------------------------------------------------------------
# START
# --------------------------------------------------------------------------------------------------

print("=" * 100)
print("CELL 21 — STREAMING FINAL SYNTHETIC DATA AUDIT")
print("=" * 100)


# --------------------------------------------------------------------------------------------------
# 1. OUTPUT FILE CHECK
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("1. OUTPUT FILE CHECK")
print("=" * 80)

required_outputs = {
    "transactions": TRANSACTIONS_FILE,
    "new_accounts": NEW_ACCOUNTS_FILE,
    "patterns": PATTERNS_FILE,
    "episode_audit": EPISODE_AUDIT_FILE,
    "legitimate_pairs": LEGIT_PAIRS_FILE,
}

for label, path in required_outputs.items():

    exists = os.path.exists(path)

    if exists:

        print(
            f"{label:18s} | exists=True  | "
            f"size={file_size_mb(path):,.2f} MB | "
            f"{os.path.basename(path)}"
        )

    else:

        print(
            f"{label:18s} | exists=False | "
            f"{os.path.basename(path)}"
        )


for label, path in required_outputs.items():

    require_file(
        path,
        label
    )


print(
    f"manifest           | exists={os.path.exists(MANIFEST_FILE)} | "
    f"{os.path.basename(MANIFEST_FILE)}"
)


# --------------------------------------------------------------------------------------------------
# 2. TRANSACTION CSV STRUCTURE
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("2. TRANSACTION CSV STRUCTURE")
print("=" * 80)


with open(
    TRANSACTIONS_FILE,
    "r",
    newline="",
    encoding="utf-8"
) as f:

    reader = csv.reader(f)
    tx_header = next(reader)


print("Columns:")

for i, col in enumerate(tx_header):

    print(
        f"  [{i}] {col}"
    )


tx_id_col = find_column(
    tx_header,
    [
        "transaction_id",
        "Transaction ID",
        "transaction id"
    ]
)

timestamp_col = find_column(
    tx_header,
    ["Timestamp"]
)

from_bank_col = find_column(
    tx_header,
    ["From Bank", "from_bank"]
)

account_col = find_column(
    tx_header,
    ["Account"]
)

to_bank_col = find_column(
    tx_header,
    ["To Bank", "to_bank"]
)

account1_col = find_column(
    tx_header,
    [
        "Account.1",
        "Account1",
        "To Account",
        "to_account"
    ]
)

amount_received_col = find_column(
    tx_header,
    [
        "Amount Received",
        "amount_received"
    ]
)

amount_paid_col = find_column(
    tx_header,
    [
        "Amount Paid",
        "amount_paid"
    ]
)

recv_currency_col = find_column(
    tx_header,
    [
        "Receiving Currency",
        "receiving_currency"
    ]
)

pay_currency_col = find_column(
    tx_header,
    [
        "Payment Currency",
        "payment_currency"
    ]
)

payment_format_col = find_column(
    tx_header,
    [
        "Payment Format",
        "payment_format"
    ]
)

label_col = find_column(
    tx_header,
    [
        "Is Laundering",
        "is_laundering"
    ]
)

synthetic_col = find_column(
    tx_header,
    [
        "is_synthetic",
        "Is Synthetic"
    ]
)

synthetic_episode_col = find_column(
    tx_header,
    [
        "synthetic_episode_id",
        "Synthetic Episode ID"
    ]
)

typology_col = find_column(
    tx_header,
    [
        "typology",
        "Typology"
    ]
)

template_col = find_column(
    tx_header,
    [
        "source_template_id",
        "Source Template ID"
    ]
)

template_order_col = find_column(
    tx_header,
    [
        "template_source_order",
        "Template Source Order"
    ]
)


required_columns = {
    "transaction_id": tx_id_col,
    "Timestamp": timestamp_col,
    "From Bank": from_bank_col,
    "Account": account_col,
    "To Bank": to_bank_col,
    "Account.1": account1_col,
    "Amount Received": amount_received_col,
    "Amount Paid": amount_paid_col,
    "Receiving Currency": recv_currency_col,
    "Payment Currency": pay_currency_col,
    "Payment Format": payment_format_col,
    "Is Laundering": label_col,
}


missing_cols = [
    name
    for name, value in required_columns.items()
    if value is None
]


if missing_cols:

    raise RuntimeError(
        "Missing required transaction columns: "
        + ", ".join(missing_cols)
    )


print("\n✅ All required transaction columns found.")


# --------------------------------------------------------------------------------------------------
# 3. FULL TRANSACTION CSV STREAMING AUDIT
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("3. FULL TRANSACTION CSV STREAMING AUDIT")
print("=" * 80)


header_idx = {
    name: i
    for i, name in enumerate(tx_header)
}


idx_id = header_idx[tx_id_col]
idx_ts = header_idx[timestamp_col]
idx_fb = header_idx[from_bank_col]
idx_acc = header_idx[account_col]
idx_tb = header_idx[to_bank_col]
idx_acc1 = header_idx[account1_col]
idx_ar = header_idx[amount_received_col]
idx_ap = header_idx[amount_paid_col]
idx_rc = header_idx[recv_currency_col]
idx_pc = header_idx[pay_currency_col]
idx_pf = header_idx[payment_format_col]
idx_label = header_idx[label_col]

idx_synth = (
    header_idx[synthetic_col]
    if synthetic_col
    else None
)

idx_episode = (
    header_idx[synthetic_episode_col]
    if synthetic_episode_col
    else None
)

idx_typology = (
    header_idx[typology_col]
    if typology_col
    else None
)

idx_template = (
    header_idx[template_col]
    if template_col
    else None
)


tx_count = 0
malformed_rows = 0
blank_ids = 0
invalid_labels = 0
invalid_synthetic_flags = 0
invalid_episode_ids = 0
blank_typology = 0
blank_template_ids = 0

min_amount_received = math.inf
max_amount_received = -math.inf

min_amount_paid = math.inf
max_amount_paid = -math.inf

min_timestamp = None
max_timestamp = None

format_counts = Counter()
payment_currency_counts = Counter()
receiving_currency_counts = Counter()
typology_counts = Counter()
template_counts = Counter()

unique_episode_ids = set()

source_banks = set()
destination_banks = set()
bank_pairs = set()


id_temp = os.path.join(
    BASE,
    "_HI-Small_SYNTH_FULL_tx_ids.tmp"
)

id_sorted = os.path.join(
    BASE,
    "_HI-Small_SYNTH_FULL_tx_ids_sorted.tmp"
)


with open(
    TRANSACTIONS_FILE,
    "r",
    newline="",
    encoding="utf-8"
) as f, open(
    id_temp,
    "w",
    encoding="utf-8"
) as id_out:

    reader = csv.reader(f)

    next(reader)

    for row in reader:

        tx_count += 1


        if len(row) != len(tx_header):

            malformed_rows += 1
            continue


        tx_id = row[idx_id].strip()

        if not tx_id:

            blank_ids += 1

        else:

            id_out.write(
                tx_id + "\n"
            )


        ts = row[idx_ts].strip()

        if ts:

            if (
                min_timestamp is None
                or ts < min_timestamp
            ):
                min_timestamp = ts

            if (
                max_timestamp is None
                or ts > max_timestamp
            ):
                max_timestamp = ts


        ar = safe_float(
            row[idx_ar]
        )

        ap = safe_float(
            row[idx_ap]
        )


        if (
            ar is None
            or not math.isfinite(ar)
            or ar <= 0
        ):

            invalid_labels += 1

        else:

            min_amount_received = min(
                min_amount_received,
                ar
            )

            max_amount_received = max(
                max_amount_received,
                ar
            )


        if (
            ap is None
            or not math.isfinite(ap)
            or ap <= 0
        ):

            invalid_labels += 1

        else:

            min_amount_paid = min(
                min_amount_paid,
                ap
            )

            max_amount_paid = max(
                max_amount_paid,
                ap
            )


        label = row[idx_label].strip()

        if label not in {
            "1",
            "1.0"
        }:

            invalid_labels += 1


        if idx_synth is not None:

            syn = row[idx_synth].strip()

            if syn not in {
                "1",
                "1.0",
                "True",
                "true"
            }:

                invalid_synthetic_flags += 1


        if idx_episode is not None:

            episode_id = row[idx_episode].strip()

            if not episode_id:

                invalid_episode_ids += 1

            else:

                unique_episode_ids.add(
                    episode_id
                )


        if idx_typology is not None:

            typ = row[idx_typology].strip().upper()

            if not typ:

                blank_typology += 1

            else:

                typology_counts[
                    typ
                ] += 1


        if idx_template is not None:

            template_id = row[
                idx_template
            ].strip()

            if not template_id:

                blank_template_ids += 1

            else:

                template_counts[
                    template_id
                ] += 1


        format_counts[
            row[idx_pf].strip()
        ] += 1

        payment_currency_counts[
            row[idx_pc].strip()
        ] += 1

        receiving_currency_counts[
            row[idx_rc].strip()
        ] += 1


        src_bank = canonical_bank(
            row[idx_fb]
        )

        dst_bank = canonical_bank(
            row[idx_tb]
        )


        source_banks.add(
            src_bank
        )

        destination_banks.add(
            dst_bank
        )

        bank_pairs.add(
            (
                src_bank,
                dst_bank
            )
        )


print(
    f"Transaction rows                : {tx_count:,}"
)

print(
    f"Expected                         : {EXPECTED_TX:,}"
)

print(
    f"Malformed rows                  : {malformed_rows:,}"
)

print(
    f"Blank transaction IDs           : {blank_ids:,}"
)

print(
    f"Invalid laundering labels       : {invalid_labels:,}"
)

print(
    f"Invalid synthetic flags         : {invalid_synthetic_flags:,}"
)

print(
    f"Invalid episode IDs             : {invalid_episode_ids:,}"
)

print(
    f"Blank typology values           : {blank_typology:,}"
)

print(
    f"Blank source-template IDs       : {blank_template_ids:,}"
)

print(
    f"Unique synthetic episode IDs    : "
    f"{len(unique_episode_ids):,}"
)

print(
    f"Expected synthetic episodes     : "
    f"{EXPECTED_EPISODES:,}"
)

print(
    f"Unique source templates         : "
    f"{len(template_counts):,}"
)

print(
    f"Min Timestamp                   : "
    f"{min_timestamp}"
)

print(
    f"Max Timestamp                   : "
    f"{max_timestamp}"
)

print(
    f"Min Amount Received             : "
    f"{min_amount_received}"
)

print(
    f"Max Amount Received             : "
    f"{max_amount_received}"
)

print(
    f"Min Amount Paid                 : "
    f"{min_amount_paid}"
)

print(
    f"Max Amount Paid                 : "
    f"{max_amount_paid}"
)

print(
    f"Unique source banks             : "
    f"{len(source_banks):,}"
)

print(
    f"Unique destination banks        : "
    f"{len(destination_banks):,}"
)

print(
    f"Unique generated bank pairs     : "
    f"{len(bank_pairs):,}"
)


print("\nPayment Format:")

for k, v in format_counts.most_common():

    print(
        f"  {k:20s} "
        f"{v:12,} "
        f"({100*v/tx_count:8.4f}%)"
    )


print("\nPayment Currency:")

for k, v in payment_currency_counts.most_common():

    print(
        f"  {k:20s} "
        f"{v:12,} "
        f"({100*v/tx_count:8.4f}%)"
    )


print("\nReceiving Currency:")

for k, v in receiving_currency_counts.most_common():

    print(
        f"  {k:20s} "
        f"{v:12,} "
        f"({100*v/tx_count:8.4f}%)"
    )


print("\nTypology counts in transaction CSV:")

for typ in sorted(
    typology_counts
):

    expected = EXPECTED_TYPOLOGY_TX.get(
        typ,
        "N/A"
    )

    print(
        f"  {typ:18s} "
        f"{typology_counts[typ]:10,} "
        f"| expected={expected}"
    )


# --------------------------------------------------------------------------------------------------
# 4. GLOBAL TRANSACTION ID UNIQUENESS
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("4. GLOBAL TRANSACTION ID UNIQUENESS")
print("=" * 80)


print(
    "Running external unique sort on transaction IDs..."
)


result = subprocess.run(
    [
        "sort",
        "-u",
        id_temp,
        "-o",
        id_sorted
    ],
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE,
    text=True
)


if result.returncode != 0:

    raise RuntimeError(
        "External transaction-ID sort failed:\n"
        + result.stderr
    )


with open(
    id_sorted,
    "r",
    encoding="utf-8"
) as f:

    unique_tx_ids = sum(
        1 for _ in f
    )


duplicate_tx_ids = (
    tx_count - unique_tx_ids
)


print(
    f"Total transaction rows : "
    f"{tx_count:,}"
)

print(
    f"Unique transaction IDs  : "
    f"{unique_tx_ids:,}"
)

print(
    f"Duplicate transaction IDs: "
    f"{duplicate_tx_ids:,}"
)


os.remove(id_temp)
os.remove(id_sorted)


tx_id_gate = (
    tx_count == EXPECTED_TX
    and unique_tx_ids == EXPECTED_TX
    and blank_ids == 0
)


print(
    "✅ PASS"
    if tx_id_gate
    else "❌ FAIL"
)


# --------------------------------------------------------------------------------------------------
# 5. LEGITIMATE BANK-PAIR COVERAGE
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("5. LEGITIMATE BANK-PAIR COVERAGE")
print("=" * 80)


legitimate_pairs = set()


with open(
    LEGIT_PAIRS_FILE,
    "r",
    newline="",
    encoding="utf-8"
) as f:

    reader = csv.DictReader(f)

    pair_header = reader.fieldnames

    fb_col = find_column(
        pair_header,
        [
            "From Bank",
            "from_bank",
            "source_bank",
            "Source Bank"
        ]
    )

    tb_col = find_column(
        pair_header,
        [
            "To Bank",
            "to_bank",
            "destination_bank",
            "Destination Bank"
        ]
    )


    if (
        fb_col is None
        or tb_col is None
    ):

        raise RuntimeError(
            "Could not identify bank columns "
            "in legitimate bank-pair file."
        )


    for row in reader:

        src = canonical_bank(
            row[fb_col]
        )

        dst = canonical_bank(
            row[tb_col]
        )

        if (
            src is not None
            and dst is not None
        ):

            legitimate_pairs.add(
                (src, dst)
            )


print(
    f"Legitimate bank pairs available : "
    f"{len(legitimate_pairs):,}"
)

print(
    f"Generated unique bank pairs      : "
    f"{len(bank_pairs):,}"
)


covered_pairs = sum(
    1
    for pair in bank_pairs
    if pair in legitimate_pairs
)


missing_pairs = (
    bank_pairs - legitimate_pairs
)


coverage_pct = (
    100.0 * covered_pairs / len(bank_pairs)
    if bank_pairs
    else 0.0
)


print(
    f"Observed in legitimate network  : "
    f"{covered_pairs:,}"
)

print(
    f"Unseen generated bank pairs      : "
    f"{len(missing_pairs):,}"
)

print(
    f"Coverage                         : "
    f"{coverage_pct:.6f}%"
)


if missing_pairs:

    print(
        "\nFirst 20 missing generated "
        "bank pairs:"
    )

    for pair in list(
        missing_pairs
    )[:20]:

        print(
            "  ",
            pair
        )


bank_pair_gate = (
    len(missing_pairs) == 0
)


print(
    "\n✅ PASS"
    if bank_pair_gate
    else "\n❌ FAIL"
)


# --------------------------------------------------------------------------------------------------
# 6. NEW ACCOUNT FILE AUDIT
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("6. NEW ACCOUNT FILE AUDIT")
print("=" * 80)


account_count = 0

account_format_errors = 0
account_bank_missing = 0
account_entity_missing = 0
duplicate_account_keys = 0
duplicate_entity_ids = 0

account_key_seen = set()
entity_id_seen = set()


account_id_pattern = re.compile(
    r"^[A-Z0-9]{9}$"
)

entity_id_pattern = re.compile(
    r"^[A-Z0-9]{9}$"
)


with open(
    NEW_ACCOUNTS_FILE,
    "r",
    newline="",
    encoding="utf-8"
) as f:

    reader = csv.DictReader(f)

    account_header = reader.fieldnames


    bank_id_col = find_column(
        account_header,
        [
            "Bank ID",
            "Bank_ID",
            "bank_id",
            "bank"
        ]
    )

    account_num_col = find_column(
        account_header,
        [
            "Account Number",
            "Account",
            "account_number"
        ]
    )

    entity_id_col = find_column(
        account_header,
        [
            "Entity ID",
            "Entity_ID",
            "entity_id"
        ]
    )

    entity_name_col = find_column(
        account_header,
        [
            "Entity Name",
            "Entity_Name",
            "entity_name"
        ]
    )


    if (
        bank_id_col is None
        or account_num_col is None
        or entity_id_col is None
        or entity_name_col is None
    ):

        raise RuntimeError(
            "Could not identify all required "
            "new-account columns.\n"
            + str(account_header)
        )


    for row in reader:

        account_count += 1


        bank_id = canonical_bank(
            row[bank_id_col]
        )

        account_num = str(
            row[account_num_col]
        ).strip()

        entity_id = str(
            row[entity_id_col]
        ).strip()

        entity_name = str(
            row[entity_name_col]
        ).strip()


        if bank_id is None:
            account_bank_missing += 1


        if not account_id_pattern.match(
            account_num
        ):

            account_format_errors += 1


        if not entity_id_pattern.match(
            entity_id
        ):

            account_format_errors += 1


        if not entity_name:

            account_entity_missing += 1


        key = (
            bank_id,
            account_num
        )


        if key in account_key_seen:

            duplicate_account_keys += 1

        else:

            account_key_seen.add(
                key
            )


        if entity_id in entity_id_seen:

            duplicate_entity_ids += 1

        else:

            entity_id_seen.add(
                entity_id
            )


print(
    f"New account rows                 : "
    f"{account_count:,}"
)

print(
    f"Unique bank+account keys         : "
    f"{len(account_key_seen):,}"
)

print(
    f"Unique entity IDs                : "
    f"{len(entity_id_seen):,}"
)

print(
    f"Account format errors            : "
    f"{account_format_errors:,}"
)

print(
    f"Duplicate bank+account keys      : "
    f"{duplicate_account_keys:,}"
)

print(
    f"Duplicate entity IDs             : "
    f"{duplicate_entity_ids:,}"
)

print(
    f"Missing bank IDs                 : "
    f"{account_bank_missing:,}"
)

print(
    f"Missing entity names             : "
    f"{account_entity_missing:,}"
)


new_account_gate = (
    account_format_errors == 0
    and duplicate_account_keys == 0
    and account_bank_missing == 0
    and account_entity_missing == 0
)


print(
    "\n✅ PASS"
    if new_account_gate
    else "\n❌ FAIL"
)


# --------------------------------------------------------------------------------------------------
# 7. DISCOVER ORIGINAL HI-SMALL ACCOUNTS FILE
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("7. ORIGINAL HI-SMALL ACCOUNTS FILE DISCOVERY")
print("=" * 80)


ORIGINAL_ACCOUNTS_FILE, accounts_candidates = (
    discover_original_accounts()
)


print(
    f"Candidates found: "
    f"{len(accounts_candidates)}"
)


for candidate in accounts_candidates:

    print(
        "  ",
        candidate
    )


if ORIGINAL_ACCOUNTS_FILE is None:

    print(
        "\n⚠️ ORIGINAL HI-SMALL ACCOUNTS FILE "
        "COULD NOT BE FOUND."
    )

    print(
        "The rest of the audit will continue, "
        "but the original-collision gate will "
        "be marked FAIL."
    )

    collision_gate = False

    original_collisions = None

    original_keys_count = None

else:

    print(
        "\nUsing original accounts file:"
    )

    print(
        ORIGINAL_ACCOUNTS_FILE
    )


    original_keys = set()


    with open(
        ORIGINAL_ACCOUNTS_FILE,
        "r",
        newline="",
        encoding="utf-8"
    ) as f:

        reader = csv.DictReader(f)

        original_header = reader.fieldnames


        original_bank_col = find_column(
            original_header,
            [
                "Bank ID",
                "Bank_ID",
                "bank_id",
                "bank"
            ]
        )

        original_account_col = find_column(
            original_header,
            [
                "Account Number",
                "Account",
                "account_number"
            ]
        )


        if (
            original_bank_col is None
            or original_account_col is None
        ):

            raise RuntimeError(
                "Could not identify original "
                "account columns:\n"
                + str(original_header)
            )


        for row in reader:

            original_keys.add(
                (
                    canonical_bank(
                        row[original_bank_col]
                    ),
                    str(
                        row[original_account_col]
                    ).strip()
                )
            )


    original_keys_count = (
        len(original_keys)
    )


    original_collisions = len(
        account_key_seen.intersection(
            original_keys
        )
    )


    print(
        f"Original bank+account keys      : "
        f"{original_keys_count:,}"
    )

    print(
        f"New/original collisions          : "
        f"{original_collisions:,}"
    )


    collision_gate = (
        original_collisions == 0
    )


    print(
        "\n✅ PASS"
        if collision_gate
        else "\n❌ FAIL"
    )


# --------------------------------------------------------------------------------------------------
# 8. PATTERNS FILE STREAMING AUDIT
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("8. PATTERNS FILE VALIDATION")
print("=" * 80)


pattern_episode_ids = 0
pattern_begin = 0
pattern_end = 0
pattern_tx = 0

pattern_malformed_tx = 0
pattern_label_errors = 0

pattern_typology_episodes = Counter()
pattern_typology_tx = Counter()

current_typology = None
current_episode_tx = 0

pattern_id_values = set()


with open(
    PATTERNS_FILE,
    "r",
    encoding="utf-8"
) as f:

    for raw in f:

        line = raw.strip()


        if not line:
            continue


        if line.startswith(
            'id="'
        ):

            pattern_episode_ids += 1

            pattern_id_values.add(
                line
            )

            continue


        if line.startswith(
            "BEGIN LAUNDERING ATTEMPT"
        ):

            pattern_begin += 1


            m = re.search(
                r"BEGIN LAUNDERING ATTEMPT\s*-\s*([A-Z-]+)",
                line
            )


            current_typology = (
                m.group(1)
                if m
                else "UNKNOWN"
            )


            pattern_typology_episodes[
                current_typology
            ] += 1


            current_episode_tx = 0

            continue


        if line.startswith(
            "END LAUNDERING ATTEMPT"
        ):

            pattern_end += 1


            if current_typology is not None:

                pattern_typology_tx[
                    current_typology
                ] += current_episode_tx


            current_typology = None

            current_episode_tx = 0

            continue


        if current_typology is not None:

            parts = line.split(",")


            if len(parts) != 11:

                pattern_malformed_tx += 1

            else:

                try:

                    datetime.strptime(
                        parts[0].strip(),
                        "%Y/%m/%d %H:%M"
                    )

                except Exception:

                    pattern_malformed_tx += 1


                if parts[-1].strip() != "1":

                    pattern_label_errors += 1


            current_episode_tx += 1

            pattern_tx += 1


print(
    f"Pattern episode ID lines        : "
    f"{pattern_episode_ids:,}"
)

print(
    f"Unique pattern ID lines         : "
    f"{len(pattern_id_values):,}"
)

print(
    f"BEGIN episode markers           : "
    f"{pattern_begin:,}"
)

print(
    f"END episode markers             : "
    f"{pattern_end:,}"
)

print(
    f"Pattern transaction lines       : "
    f"{pattern_tx:,}"
)

print(
    f"Malformed pattern tx rows       : "
    f"{pattern_malformed_tx:,}"
)

print(
    f"Pattern label != 1              : "
    f"{pattern_label_errors:,}"
)


print("\nPattern transactions by typology:")


for typ in sorted(
    pattern_typology_tx
):

    actual = pattern_typology_tx[
        typ
    ]

    expected = EXPECTED_TYPOLOGY_TX.get(
        typ,
        "N/A"
    )

    print(
        f"  {typ:18s} "
        f"episodes="
        f"{pattern_typology_episodes[typ]:7,} "
        f"transactions="
        f"{actual:9,} "
        f"expected="
        f"{expected}"
    )


pattern_gate = (
    pattern_episode_ids == EXPECTED_EPISODES
    and len(pattern_id_values) == EXPECTED_EPISODES
    and pattern_begin == EXPECTED_EPISODES
    and pattern_end == EXPECTED_EPISODES
    and pattern_tx == EXPECTED_TX
    and pattern_malformed_tx == 0
    and pattern_label_errors == 0
    and all(
        pattern_typology_tx.get(
            typ,
            -1
        ) == expected
        for typ, expected
        in EXPECTED_TYPOLOGY_TX.items()
    )
)


print(
    "\n✅ PASS"
    if pattern_gate
    else "\n❌ FAIL"
)


# --------------------------------------------------------------------------------------------------
# 9. CSV ↔ PATTERNS TYPOLOGY CONSISTENCY
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("9. CSV ↔ PATTERNS TYPOLOGY CONSISTENCY")
print("=" * 80)


csv_typology_gate = True


for typ, expected in EXPECTED_TYPOLOGY_TX.items():

    csv_count = typology_counts.get(
        typ,
        0
    )

    pattern_count = pattern_typology_tx.get(
        typ,
        0
    )


    passed = (
        csv_count == expected
        and pattern_count == expected
    )


    print(
        f"{'✅ PASS' if passed else '❌ FAIL'} "
        f"| {typ:18s} "
        f"| CSV={csv_count:,} "
        f"| Patterns={pattern_count:,} "
        f"| Expected={expected:,}"
    )


    csv_typology_gate &= passed


print(
    "\n✅ PASS"
    if csv_typology_gate
    else "\n❌ FAIL"
)


# --------------------------------------------------------------------------------------------------
# 10. EPISODE AUDIT FILE
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("10. EPISODE AUDIT FILE")
print("=" * 80)


episode_rows = 0
episode_tx_sum = 0

episode_typology_tx = Counter()
episode_typology_ep = Counter()


with open(
    EPISODE_AUDIT_FILE,
    "r",
    newline="",
    encoding="utf-8"
) as f:

    reader = csv.DictReader(f)

    eh = reader.fieldnames


    etyp = find_column(
        eh,
        [
            "typology",
            "Typology",
            "pattern_type",
            "pattern"
        ]
    )


    etx = find_column(
        eh,
        [
            "transaction_count",
            "tx_count",
            "transactions",
            "n_transactions"
        ]
    )


    if etx is None:

        raise RuntimeError(
            "Could not find transaction-count "
            "column in episode audit."
        )


    for row in reader:

        episode_rows += 1


        n = safe_int(
            row[etx]
        )


        if n is not None:

            episode_tx_sum += n


            if etyp is not None:

                typ = row[
                    etyp
                ].strip().upper()


                episode_typology_tx[
                    typ
                ] += n


                episode_typology_ep[
                    typ
                ] += 1


print(
    f"Episode-audit rows               : "
    f"{episode_rows:,}"
)

print(
    f"Expected episodes                : "
    f"{EXPECTED_EPISODES:,}"
)

print(
    f"Episode-audit transaction sum    : "
    f"{episode_tx_sum:,}"
)

print(
    f"Expected transactions            : "
    f"{EXPECTED_TX:,}"
)


if etyp is not None:

    print(
        "\nEpisode-audit typology totals:"
    )


    for typ in sorted(
        episode_typology_tx
    ):

        print(
            f"  {typ:18s} "
            f"episodes="
            f"{episode_typology_ep[typ]:7,} "
            f"transactions="
            f"{episode_typology_tx[typ]:9,}"
        )


episode_gate = (
    episode_rows == EXPECTED_EPISODES
    and episode_tx_sum == EXPECTED_TX
)


print(
    "\n✅ PASS"
    if episode_gate
    else "\n❌ FAIL"
)


# --------------------------------------------------------------------------------------------------
# 11. FINAL GLOBAL GATES
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("11. FINAL GLOBAL GATES")
print("=" * 80)


amount_gate = (
    min_amount_received > 0
    and math.isfinite(
        max_amount_received
    )
    and min_amount_paid > 0
    and math.isfinite(
        max_amount_paid
    )
)


episode_csv_gate = (
    idx_episode is not None
    and invalid_episode_ids == 0
    and len(unique_episode_ids) == EXPECTED_EPISODES
)


typology_gate = (
    idx_typology is not None
    and blank_typology == 0
    and csv_typology_gate
)


template_gate = (
    idx_template is not None
    and blank_template_ids == 0
)


gates = {

    "Exact transaction row count":
        tx_count == EXPECTED_TX,

    "Global transaction IDs unique":
        tx_id_gate,

    "No malformed transaction rows":
        malformed_rows == 0,

    "All laundering labels = 1":
        invalid_labels == 0,

    "All synthetic flags valid":
        (
            invalid_synthetic_flags == 0
            if synthetic_col is not None
            else True
        ),

    "Positive finite amounts":
        amount_gate,

    "Exact synthetic episode count":
        episode_csv_gate,

    "Typology integrity":
        typology_gate,

    "Template IDs present":
        template_gate,

    "Legitimate bank-pair coverage":
        bank_pair_gate,

    "New account integrity":
        new_account_gate,

    "No new/original account collisions":
        collision_gate,

    "Patterns file exact":
        pattern_gate,

    "CSV ↔ Patterns typology match":
        csv_typology_gate,

    "Episode audit exact":
        episode_gate,
}


all_pass = True


for name, passed in gates.items():

    print(
        f"{'✅ PASS' if passed else '❌ FAIL'} "
        f"| {name}"
    )

    all_pass &= passed


# --------------------------------------------------------------------------------------------------
# 12. CREATE MANIFEST
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("12. CREATING MANIFEST")
print("=" * 80)


manifest = {

    "dataset":
        "IBM HI-Small",

    "generation_status":
        "COMPLETED",

    "audit_status":
        "PASS" if all_pass else "FAIL",


    "generation": {

        "synthetic_episodes":
            EXPECTED_EPISODES,

        "synthetic_transactions":
            EXPECTED_TX,

        "new_accounts_generated":
            account_count,
    },


    "expected_typology_transactions":
        EXPECTED_TYPOLOGY_TX,


    "resolved_source_files": {

        "original_accounts_file":
            ORIGINAL_ACCOUNTS_FILE,

        "legitimate_bank_pairs_file":
            LEGIT_PAIRS_FILE,
    },


    "outputs": {

        "transactions":
            os.path.basename(
                TRANSACTIONS_FILE
            ),

        "new_accounts":
            os.path.basename(
                NEW_ACCOUNTS_FILE
            ),

        "patterns":
            os.path.basename(
                PATTERNS_FILE
            ),

        "episode_audit":
            os.path.basename(
                EPISODE_AUDIT_FILE
            ),

        "manifest":
            os.path.basename(
                MANIFEST_FILE
            ),
    },


    "file_sizes_mb": {

        "transactions":
            round(
                file_size_mb(
                    TRANSACTIONS_FILE
                ),
                2
            ),

        "new_accounts":
            round(
                file_size_mb(
                    NEW_ACCOUNTS_FILE
                ),
                2
            ),

        "patterns":
            round(
                file_size_mb(
                    PATTERNS_FILE
                ),
                2
            ),

        "episode_audit":
            round(
                file_size_mb(
                    EPISODE_AUDIT_FILE
                ),
                2
            ),
    },


    "transaction_audit": {

        "rows":
            tx_count,

        "expected_rows":
            EXPECTED_TX,

        "unique_transaction_ids":
            unique_tx_ids,

        "duplicate_transaction_ids":
            duplicate_tx_ids,

        "malformed_rows":
            malformed_rows,

        "blank_transaction_ids":
            blank_ids,

        "invalid_laundering_labels":
            invalid_labels,

        "invalid_synthetic_flags":
            invalid_synthetic_flags,

        "unique_synthetic_episode_ids":
            len(unique_episode_ids),

        "unique_templates":
            len(template_counts),

        "min_timestamp":
            min_timestamp,

        "max_timestamp":
            max_timestamp,

        "min_amount_received":
            min_amount_received,

        "max_amount_received":
            max_amount_received,

        "min_amount_paid":
            min_amount_paid,

        "max_amount_paid":
            max_amount_paid,

        "unique_source_banks":
            len(source_banks),

        "unique_destination_banks":
            len(destination_banks),

        "unique_generated_bank_pairs":
            len(bank_pairs),

        "payment_format_counts":
            dict(format_counts),

        "payment_currency_counts":
            dict(payment_currency_counts),

        "receiving_currency_counts":
            dict(receiving_currency_counts),

        "typology_counts":
            dict(typology_counts),

        "template_counts":
            dict(template_counts),
    },


    "bank_network_audit": {

        "legitimate_pairs":
            len(legitimate_pairs),

        "generated_unique_pairs":
            len(bank_pairs),

        "covered_pairs":
            covered_pairs,

        "missing_pairs":
            len(missing_pairs),

        "coverage_percent":
            coverage_pct,
    },


    "new_account_audit": {

        "rows":
            account_count,

        "unique_bank_account_keys":
            len(account_key_seen),

        "unique_entity_ids":
            len(entity_id_seen),

        "format_errors":
            account_format_errors,

        "duplicate_bank_account_keys":
            duplicate_account_keys,

        "duplicate_entity_ids":
            duplicate_entity_ids,

        "missing_bank_ids":
            account_bank_missing,

        "missing_entity_names":
            account_entity_missing,

        "original_collisions":
            original_collisions,

        "original_account_keys":
            original_keys_count,
    },


    "patterns_audit": {

        "episode_id_lines":
            pattern_episode_ids,

        "unique_episode_id_lines":
            len(pattern_id_values),

        "begin_markers":
            pattern_begin,

        "end_markers":
            pattern_end,

        "transaction_lines":
            pattern_tx,

        "malformed_transaction_lines":
            pattern_malformed_tx,

        "label_errors":
            pattern_label_errors,

        "typology_episodes":
            dict(
                pattern_typology_episodes
            ),

        "typology_transactions":
            dict(
                pattern_typology_tx
            ),
    },


    "episode_audit": {

        "rows":
            episode_rows,

        "transaction_sum":
            episode_tx_sum,

        "typology_transactions":
            dict(
                episode_typology_tx
            ),

        "typology_episodes":
            dict(
                episode_typology_ep
            ),
    },


    "gates":
        gates,
}


with open(
    MANIFEST_FILE,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        manifest,
        f,
        indent=2
    )


print(
    "Manifest written to:"
)

print(
    MANIFEST_FILE
)

print(
    f"Manifest size: "
    f"{file_size_mb(MANIFEST_FILE):.4f} MB"
)


# --------------------------------------------------------------------------------------------------
# 13. FINAL RESULT
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 100)


if all_pass:

    print(
        "✅✅✅ FINAL SYNTHETIC DATASET AUDIT PASSED ✅✅✅"
    )

    print(
        "=" * 100
    )

    print(
        f"Synthetic transactions : "
        f"{tx_count:,}"
    )

    print(
        f"Synthetic episodes     : "
        f"{len(unique_episode_ids):,}"
    )

    print(
        f"New accounts           : "
        f"{account_count:,}"
    )

    print(
        f"Patterns transactions  : "
        f"{pattern_tx:,}"
    )

    print(
        f"Generated bank pairs   : "
        f"{len(bank_pairs):,}"
    )

    print(
        f"Bank-pair coverage     : "
        f"{coverage_pct:.6f}%"
    )

    print(
        "Manifest               : CREATED"
    )

    print(
        "\n✅ Structural generation integrity is complete."
    )

else:

    print(
        "❌ FINAL SYNTHETIC DATASET AUDIT HAS FAILURES"
    )

    print(
        "=" * 100
    )

    print(
        "Do NOT proceed to GNN training yet."
    )

    print(
        "Inspect the failed gate(s) above."
    )


print("=" * 100)

====================================================================================================
CELL 21 — STREAMING FINAL SYNTHETIC DATA AUDIT
====================================================================================================

================================================================================
1. OUTPUT FILE CHECK
================================================================================
transactions       | exists=True  | size=844.22 MB | HI-Small_SYNTH_FULL_transactions.csv
new_accounts       | exists=True  | size=27.85 MB | HI-Small_SYNTH_FULL_new_accounts.csv
patterns           | exists=True  | size=570.76 MB | HI-Small_SYNTH_FULL_Patterns.txt
episode_audit      | exists=True  | size=43.50 MB | HI-Small_SYNTH_FULL_episode_audit.csv
legitimate_pairs   | exists=True  | size=5.26 MB | HI-Small_legitimate_bank_pairs.csv
manifest           | exists=False | HI-Small_SYNTH_FULL_manifest.json

================================================================================
2. TRANSACTION CSV STRUCTURE
================================================================================
Columns:
  [0] transaction_id
  [1] Timestamp
  [2] From Bank
  [3] Account
  [4] To Bank
  [5] Account.1
  [6] Amount Received
  [7] Receiving Currency
  [8] Amount Paid
  [9] Payment Currency
  [10] Payment Format
  [11] Is Laundering
  [12] is_synthetic
  [13] synthetic_episode_id
  [14] typology
  [15] source_template_id
  [16] template_source_order

✅ All required transaction columns found.

================================================================================
3. FULL TRANSACTION CSV STREAMING AUDIT
================================================================================
Transaction rows                : 5,067,991
Expected                         : 5,067,991
Malformed rows                  : 0
Blank transaction IDs           : 0
Invalid laundering labels       : 0
Invalid synthetic flags         : 0
Invalid episode IDs             : 0
Blank typology values           : 0
Blank source-template IDs       : 0
Unique synthetic episode IDs    : 584,706
Expected synthetic episodes     : 584,706
Unique source templates         : 370
Min Timestamp                   : 2022-09-01 00:00:00
Max Timestamp                   : 2022-09-14 19:51:00
Min Amount Received             : 1e-06
Max Amount Received             : 25747762666.420002
Min Amount Paid                 : 1e-06
Max Amount Paid                 : 25747762666.420002
Unique source banks             : 1,064
Unique destination banks        : 1,223
Unique generated bank pairs     : 12,768

Payment Format:
  Cheque                  1,892,688 ( 37.3459%)
  Credit Card             1,310,992 ( 25.8681%)
  ACH                       616,125 ( 12.1572%)
  Cash                      489,452 (  9.6577%)
  Reinvestment              438,420 (  8.6508%)
  Wire                      173,787 (  3.4291%)
  Bitcoin                   146,527 (  2.8912%)

Payment Currency:
  US Dollar               1,877,273 ( 37.0418%)
  Euro                    1,157,845 ( 22.8462%)
  Swiss Franc               238,278 (  4.7016%)
  Yuan                      212,164 (  4.1864%)
  Shekel                    196,048 (  3.8684%)
  Rupee                     185,467 (  3.6596%)
  UK Pound                  185,108 (  3.6525%)
  Ruble                     157,851 (  3.1147%)
  Yen                       157,476 (  3.1073%)
  Bitcoin                   146,192 (  2.8846%)
  Canadian Dollar           144,823 (  2.8576%)
  Australian Dollar         135,347 (  2.6706%)
  Mexican Peso              112,305 (  2.2160%)
  Saudi Riyal                90,557 (  1.7868%)
  Brazil Real                71,257 (  1.4060%)

Receiving Currency:
  US Dollar               1,863,380 ( 36.7676%)
  Euro                    1,161,712 ( 22.9225%)
  Swiss Franc               241,788 (  4.7709%)
  Yuan                      204,300 (  4.0312%)
  Shekel                    198,279 (  3.9124%)
  Rupee                     187,889 (  3.7074%)
  UK Pound                  184,662 (  3.6437%)
  Ruble                     159,642 (  3.1500%)
  Yen                       158,074 (  3.1191%)
  Bitcoin                   147,951 (  2.9193%)
  Canadian Dollar           145,588 (  2.8727%)
  Australian Dollar         137,361 (  2.7104%)
  Mexican Peso              113,581 (  2.2411%)
  Saudi Riyal                91,806 (  1.8115%)
  Brazil Real                71,978 (  1.4202%)

Typology counts in transaction CSV:
  BIPARTITE             415,357 | expected=415357
  CYCLE                 453,261 | expected=453261
  FAN-IN                502,219 | expected=502219
  FAN-OUT               540,123 | expected=540123
  GATHER-SCATTER      1,130,782 | expected=1130782
  RANDOM                301,647 | expected=301647
  SCATTER-GATHER        988,646 | expected=988646
  STACK                 735,956 | expected=735956

================================================================================
4. GLOBAL TRANSACTION ID UNIQUENESS
================================================================================
Running external unique sort on transaction IDs...
Total transaction rows : 5,067,991
Unique transaction IDs  : 5,067,991
Duplicate transaction IDs: 0
✅ PASS

================================================================================
5. LEGITIMATE BANK-PAIR COVERAGE
================================================================================
Legitimate bank pairs available : 283,353
Generated unique bank pairs      : 12,768
Observed in legitimate network  : 12,768
Unseen generated bank pairs      : 0
Coverage                         : 100.000000%

✅ PASS

================================================================================
6. NEW ACCOUNT FILE AUDIT
================================================================================
New account rows                 : 486,372
Unique bank+account keys         : 486,372
Unique entity IDs                : 486,372
Account format errors            : 0
Duplicate bank+account keys      : 0
Duplicate entity IDs             : 0
Missing bank IDs                 : 0
Missing entity names             : 0

✅ PASS

================================================================================
7. ORIGINAL HI-SMALL ACCOUNTS FILE DISCOVERY
================================================================================
Candidates found: 1
   /kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml/HI-Small_accounts.csv

Using original accounts file:
/kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml/HI-Small_accounts.csv
Original bank+account keys      : 518,581
New/original collisions          : 0

✅ PASS

================================================================================
8. PATTERNS FILE VALIDATION
================================================================================
Pattern episode ID lines        : 584,706
Unique pattern ID lines         : 584,706
BEGIN episode markers           : 584,706
END episode markers             : 584,706
Pattern transaction lines       : 5,067,991
Malformed pattern tx rows       : 0
Pattern label != 1              : 0

Pattern transactions by typology:
  BIPARTITE          episodes= 77,451 transactions=  415,357 expected=415357
  CYCLE              episodes= 85,293 transactions=  453,261 expected=453261
  FAN-IN             episodes= 63,218 transactions=  502,219 expected=502219
  FAN-OUT            episodes= 75,862 transactions=  540,123 expected=540123
  GATHER-SCATTER     episodes= 80,605 transactions=1,130,782 expected=1130782
  RANDOM             episodes= 64,782 transactions=  301,647 expected=301647
  SCATTER-GATHER     episodes= 69,540 transactions=  988,646 expected=988646
  STACK              episodes= 67,955 transactions=  735,956 expected=735956

✅ PASS

================================================================================
9. CSV ↔ PATTERNS TYPOLOGY CONSISTENCY
================================================================================
✅ PASS | BIPARTITE          | CSV=415,357 | Patterns=415,357 | Expected=415,357
✅ PASS | CYCLE              | CSV=453,261 | Patterns=453,261 | Expected=453,261
✅ PASS | FAN-IN             | CSV=502,219 | Patterns=502,219 | Expected=502,219
✅ PASS | FAN-OUT            | CSV=540,123 | Patterns=540,123 | Expected=540,123
✅ PASS | GATHER-SCATTER     | CSV=1,130,782 | Patterns=1,130,782 | Expected=1,130,782
✅ PASS | RANDOM             | CSV=301,647 | Patterns=301,647 | Expected=301,647
✅ PASS | SCATTER-GATHER     | CSV=988,646 | Patterns=988,646 | Expected=988,646
✅ PASS | STACK              | CSV=735,956 | Patterns=735,956 | Expected=735,956

✅ PASS

================================================================================
10. EPISODE AUDIT FILE
================================================================================
Episode-audit rows               : 584,706
Expected episodes                : 584,706
Episode-audit transaction sum    : 5,067,991
Expected transactions            : 5,067,991

Episode-audit typology totals:
  BIPARTITE          episodes= 77,451 transactions=  415,357
  CYCLE              episodes= 85,293 transactions=  453,261
  FAN-IN             episodes= 63,218 transactions=  502,219
  FAN-OUT            episodes= 75,862 transactions=  540,123
  GATHER-SCATTER     episodes= 80,605 transactions=1,130,782
  RANDOM             episodes= 64,782 transactions=  301,647
  SCATTER-GATHER     episodes= 69,540 transactions=  988,646
  STACK              episodes= 67,955 transactions=  735,956

✅ PASS

================================================================================
11. FINAL GLOBAL GATES
================================================================================
✅ PASS | Exact transaction row count
✅ PASS | Global transaction IDs unique
✅ PASS | No malformed transaction rows
✅ PASS | All laundering labels = 1
✅ PASS | All synthetic flags valid
✅ PASS | Positive finite amounts
✅ PASS | Exact synthetic episode count
✅ PASS | Typology integrity
✅ PASS | Template IDs present
✅ PASS | Legitimate bank-pair coverage
✅ PASS | New account integrity
✅ PASS | No new/original account collisions
✅ PASS | Patterns file exact
✅ PASS | CSV ↔ Patterns typology match
✅ PASS | Episode audit exact

================================================================================
12. CREATING MANIFEST
================================================================================
Manifest written to:
/kaggle/working/AML_GNN_ONLY/data/HI-Small_SYNTH_FULL_manifest.json
Manifest size: 0.0159 MB

====================================================================================================
✅✅✅ FINAL SYNTHETIC DATASET AUDIT PASSED ✅✅✅
====================================================================================================
Synthetic transactions : 5,067,991
Synthetic episodes     : 584,706
New accounts           : 486,372
Patterns transactions  : 5,067,991
Generated bank pairs   : 12,768
Bank-pair coverage     : 100.000000%
Manifest               : CREATED

✅ Structural generation integrity is complete.
====================================================================================================

In [32]:
# ==================================================================================================
# CELL 22 — SYNTHETIC vs ORIGINAL HI-SMALL BEHAVIORAL DNA AUDIT
#
# PURPOSE:
#   Compare the generated synthetic laundering data against ORIGINAL HI-Small behavior.
#
#   This cell:
#       - DOES NOT regenerate anything
#       - DOES NOT modify generated files
#       - DOES NOT train a model
#       - Creates an audit report only
#
# Main checks:
#   1. Timestamp/date coverage
#   2. Hour distribution
#   3. Day-of-week distribution
#   4. Amount distribution
#   5. Payment Format
#   6. Payment Currency
#   7. Receiving Currency
#   8. Source-bank concentration
#   9. Destination-bank concentration
#  10. Account activity/reuse
#  11. Cross-bank activity
# ==================================================================================================

import os
import csv
import json
import math
import glob
import random
from collections import Counter, defaultdict
from datetime import datetime


# --------------------------------------------------------------------------------------------------
# PATHS
# --------------------------------------------------------------------------------------------------

BASE = "/kaggle/working/AML_GNN_ONLY/data"

SYN_FILE = os.path.join(
    BASE,
    "HI-Small_SYNTH_FULL_transactions.csv"
)

OUT_JSON = os.path.join(
    BASE,
    "HI-Small_SYNTH_vs_ORIGINAL_behavioral_dna_audit.json"
)

OUT_CSV = os.path.join(
    BASE,
    "HI-Small_SYNTH_vs_ORIGINAL_behavioral_dna_summary.csv"
)


# --------------------------------------------------------------------------------------------------
# AUTO-DISCOVER ORIGINAL HI-SMALL TRANSACTION FILE
# --------------------------------------------------------------------------------------------------

def discover_original_transactions():

    candidates = []

    roots = [
        "/kaggle/input",
        "/kaggle/working"
    ]

    for root in roots:

        if not os.path.exists(root):
            continue

        pattern = os.path.join(
            root,
            "**",
            "HI-Small_Trans.csv"
        )

        candidates.extend(
            glob.glob(
                pattern,
                recursive=True
            )
        )

    candidates = sorted(
        set(
            os.path.abspath(x)
            for x in candidates
            if os.path.isfile(x)
        )
    )

    if len(candidates) == 0:
        return None

    # Prefer input dataset
    input_candidates = [
        x for x in candidates
        if x.startswith("/kaggle/input/")
    ]

    if input_candidates:
        return input_candidates[0]

    return candidates[0]


# --------------------------------------------------------------------------------------------------
# HELPERS
# --------------------------------------------------------------------------------------------------

def canonical_bank(x):

    if x is None:
        return None

    s = str(x).strip()

    if not s:
        return None

    if s.isdigit():
        return str(int(s))

    return s.upper()


def find_column(header, candidates):

    low = {
        str(x).strip().lower(): x
        for x in header
    }

    for c in candidates:

        if c.strip().lower() in low:
            return low[c.strip().lower()]

    for h in header:

        hl = str(h).strip().lower()

        for c in candidates:

            if c.strip().lower() in hl:
                return h

    return None


def pct(count, total):

    if total == 0:
        return 0.0

    return 100.0 * count / total


def quantiles_from_sample(values):

    if not values:
        return {}

    values = sorted(values)

    def q(p):

        idx = int(
            p * (len(values) - 1)
        )

        return values[idx]

    return {
        "p01": q(0.01),
        "p05": q(0.05),
        "p10": q(0.10),
        "p25": q(0.25),
        "p50": q(0.50),
        "p75": q(0.75),
        "p90": q(0.90),
        "p95": q(0.95),
        "p99": q(0.99),
        "min_sample": min(values),
        "max_sample": max(values),
    }


def distribution_pct(counter, total):

    return {
        k: {
            "count": v,
            "pct": pct(v, total)
        }
        for k, v in counter.items()
    }


# --------------------------------------------------------------------------------------------------
# START
# --------------------------------------------------------------------------------------------------

print("=" * 100)
print("CELL 22 — SYNTHETIC vs ORIGINAL HI-SMALL BEHAVIORAL DNA AUDIT")
print("=" * 100)


# --------------------------------------------------------------------------------------------------
# FILE DISCOVERY
# --------------------------------------------------------------------------------------------------

if not os.path.exists(SYN_FILE):

    raise FileNotFoundError(
        f"Missing synthetic transaction file:\n{SYN_FILE}"
    )


ORIGINAL_FILE = discover_original_transactions()


if ORIGINAL_FILE is None:

    raise FileNotFoundError(
        "Could not find original HI-Small_Trans.csv "
        "under /kaggle/input or /kaggle/working."
    )


print("\nSynthetic file:")
print(SYN_FILE)

print("\nOriginal file:")
print(ORIGINAL_FILE)


# --------------------------------------------------------------------------------------------------
# SAMPLE SETTINGS
# --------------------------------------------------------------------------------------------------

SAMPLE_SIZE = 200_000

random.seed(42)


# --------------------------------------------------------------------------------------------------
# GENERIC STATS CONTAINER
# --------------------------------------------------------------------------------------------------

def new_stats():

    return {
        "rows": 0,

        "min_timestamp": None,
        "max_timestamp": None,

        "hour": Counter(),
        "day_of_week": Counter(),
        "date": Counter(),

        "payment_format": Counter(),
        "payment_currency": Counter(),
        "receiving_currency": Counter(),

        "source_bank": Counter(),
        "destination_bank": Counter(),

        "source_account": Counter(),
        "destination_account": Counter(),

        "source_bank_account": Counter(),
        "destination_bank_account": Counter(),

        "amount_sample": [],
    }


# --------------------------------------------------------------------------------------------------
# STREAM FILE
# --------------------------------------------------------------------------------------------------

def stream_stats(
    path,
    stats_name,
    expected_columns=None
):

    stats = new_stats()

    with open(
        path,
        "r",
        newline="",
        encoding="utf-8"
    ) as f:

        reader = csv.DictReader(f)

        header = reader.fieldnames

        if header is None:
            raise RuntimeError(
                f"No header found in {path}"
            )

        timestamp_col = find_column(
            header,
            ["Timestamp"]
        )

        from_bank_col = find_column(
            header,
            ["From Bank", "from_bank"]
        )

        account_col = find_column(
            header,
            ["Account"]
        )

        to_bank_col = find_column(
            header,
            ["To Bank", "to_bank"]
        )

        account1_col = find_column(
            header,
            [
                "Account.1",
                "Account1",
                "To Account",
                "to_account"
            ]
        )

        amount_col = find_column(
            header,
            [
                "Amount Received",
                "amount_received"
            ]
        )

        pay_curr_col = find_column(
            header,
            [
                "Payment Currency",
                "payment_currency"
            ]
        )

        recv_curr_col = find_column(
            header,
            [
                "Receiving Currency",
                "receiving_currency"
            ]
        )

        format_col = find_column(
            header,
            [
                "Payment Format",
                "payment_format"
            ]
        )

        required = {
            "Timestamp": timestamp_col,
            "From Bank": from_bank_col,
            "Account": account_col,
            "To Bank": to_bank_col,
            "Account.1": account1_col,
            "Amount Received": amount_col,
            "Payment Currency": pay_curr_col,
            "Receiving Currency": recv_curr_col,
            "Payment Format": format_col,
        }

        missing = [
            k
            for k, v in required.items()
            if v is None
        ]

        if missing:

            raise RuntimeError(
                f"{stats_name}: missing columns: {missing}"
            )


        for row in reader:

            stats["rows"] += 1


            # --------------------------------------------------------------------------------------
            # TIMESTAMP
            # --------------------------------------------------------------------------------------

            ts = row[timestamp_col].strip()

            try:

                dt = datetime.strptime(
                    ts,
                    "%Y-%m-%d %H:%M:%S"
                )

            except Exception:

                try:

                    dt = datetime.strptime(
                        ts,
                        "%Y/%m/%d %H:%M"
                    )

                except Exception:

                    dt = None


            if dt is not None:

                if (
                    stats["min_timestamp"] is None
                    or dt < stats["min_timestamp"]
                ):
                    stats["min_timestamp"] = dt

                if (
                    stats["max_timestamp"] is None
                    or dt > stats["max_timestamp"]
                ):
                    stats["max_timestamp"] = dt

                stats["hour"][dt.hour] += 1

                stats["day_of_week"][
                    dt.strftime("%A")
                ] += 1

                stats["date"][
                    dt.strftime("%Y-%m-%d")
                ] += 1


            # --------------------------------------------------------------------------------------
            # CATEGORICAL
            # --------------------------------------------------------------------------------------

            stats["payment_format"][
                row[format_col].strip()
            ] += 1

            stats["payment_currency"][
                row[pay_curr_col].strip()
            ] += 1

            stats["receiving_currency"][
                row[recv_curr_col].strip()
            ] += 1


            # --------------------------------------------------------------------------------------
            # BANKS
            # --------------------------------------------------------------------------------------

            src = canonical_bank(
                row[from_bank_col]
            )

            dst = canonical_bank(
                row[to_bank_col]
            )

            acc_src = row[
                account_col
            ].strip()

            acc_dst = row[
                account1_col
            ].strip()


            stats["source_bank"][
                src
            ] += 1

            stats["destination_bank"][
                dst
            ] += 1


            stats["source_account"][
                acc_src
            ] += 1

            stats["destination_account"][
                acc_dst
            ] += 1


            stats["source_bank_account"][
                (src, acc_src)
            ] += 1

            stats["destination_bank_account"][
                (dst, acc_dst)
            ] += 1


            # --------------------------------------------------------------------------------------
            # AMOUNT RESERVOIR SAMPLE
            # --------------------------------------------------------------------------------------

            try:

                amount = float(
                    row[amount_col]
                )

                if (
                    math.isfinite(amount)
                    and amount > 0
                ):

                    n = len(
                        stats["amount_sample"]
                    )

                    if n < SAMPLE_SIZE:

                        stats["amount_sample"].append(
                            amount
                        )

                    else:

                        # Reservoir sampling
                        j = random.randint(
                            0,
                            stats["rows"] - 1
                        )

                        if j < SAMPLE_SIZE:

                            stats[
                                "amount_sample"
                            ][j] = amount

            except Exception:
                pass


    return stats


# --------------------------------------------------------------------------------------------------
# STREAM ORIGINAL
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("1. STREAMING ORIGINAL HI-SMALL")
print("=" * 80)

original = stream_stats(
    ORIGINAL_FILE,
    "ORIGINAL"
)

print(
    f"Original rows: "
    f"{original['rows']:,}"
)

print(
    f"Original min timestamp: "
    f"{original['min_timestamp']}"
)

print(
    f"Original max timestamp: "
    f"{original['max_timestamp']}"
)


# --------------------------------------------------------------------------------------------------
# STREAM SYNTHETIC
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("2. STREAMING SYNTHETIC LAUNDERING DATA")
print("=" * 80)

synthetic = stream_stats(
    SYN_FILE,
    "SYNTHETIC"
)

print(
    f"Synthetic rows: "
    f"{synthetic['rows']:,}"
)

print(
    f"Synthetic min timestamp: "
    f"{synthetic['min_timestamp']}"
)

print(
    f"Synthetic max timestamp: "
    f"{synthetic['max_timestamp']}"
)


# --------------------------------------------------------------------------------------------------
# 3. TIMESTAMP COVERAGE
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("3. TIMESTAMP COVERAGE")
print("=" * 80)

print(
    f"Original : "
    f"{original['min_timestamp']} "
    f"→ "
    f"{original['max_timestamp']}"
)

print(
    f"Synthetic: "
    f"{synthetic['min_timestamp']} "
    f"→ "
    f"{synthetic['max_timestamp']}"
)


original_days = set(
    original["date"].keys()
)

synthetic_days = set(
    synthetic["date"].keys()
)

missing_synthetic_days = (
    original_days - synthetic_days
)


print(
    f"Original active dates : "
    f"{len(original_days)}"
)

print(
    f"Synthetic active dates: "
    f"{len(synthetic_days)}"
)

print(
    f"Dates missing in synthetic: "
    f"{len(missing_synthetic_days)}"
)


if missing_synthetic_days:

    print(
        "\n⚠️ Missing synthetic dates:"
    )

    for d in sorted(
        missing_synthetic_days
    ):

        print(
            "  ",
            d
        )


# --------------------------------------------------------------------------------------------------
# 4. HOUR DISTRIBUTION
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("4. HOUR DISTRIBUTION")
print("=" * 80)

print(
    f"{'Hour':>6} "
    f"{'Original %':>14} "
    f"{'Synthetic %':>14} "
    f"{'Abs Diff':>14}"
)

hour_abs_diffs = []

for hour in range(24):

    op = pct(
        original["hour"].get(hour, 0),
        original["rows"]
    )

    sp = pct(
        synthetic["hour"].get(hour, 0),
        synthetic["rows"]
    )

    diff = abs(
        op - sp
    )

    hour_abs_diffs.append(
        diff
    )

    print(
        f"{hour:6d} "
        f"{op:14.4f} "
        f"{sp:14.4f} "
        f"{diff:14.4f}"
    )

hour_mae = (
    sum(hour_abs_diffs)
    / len(hour_abs_diffs)
)


print(
    f"\nHour-distribution MAE: "
    f"{hour_mae:.6f} percentage points"
)


# --------------------------------------------------------------------------------------------------
# 5. DAY OF WEEK
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("5. DAY OF WEEK DISTRIBUTION")
print("=" * 80)

days = [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday"
]

dow_abs_diffs = []

for d in days:

    op = pct(
        original["day_of_week"].get(d, 0),
        original["rows"]
    )

    sp = pct(
        synthetic["day_of_week"].get(d, 0),
        synthetic["rows"]
    )

    diff = abs(
        op - sp
    )

    dow_abs_diffs.append(
        diff
    )

    print(
        f"{d:12s} "
        f"| Original={op:8.4f}% "
        f"| Synthetic={sp:8.4f}% "
        f"| AbsDiff={diff:8.4f}"
    )


dow_mae = (
    sum(dow_abs_diffs)
    / len(dow_abs_diffs)
)


print(
    f"\nDay-of-week MAE: "
    f"{dow_mae:.6f} percentage points"
)


# --------------------------------------------------------------------------------------------------
# 6. PAYMENT FORMAT
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("6. PAYMENT FORMAT")
print("=" * 80)

all_formats = sorted(
    set(
        original["payment_format"]
    )
    | set(
        synthetic["payment_format"]
    )
)

format_abs_diffs = []

for fmt in all_formats:

    op = pct(
        original["payment_format"].get(fmt, 0),
        original["rows"]
    )

    sp = pct(
        synthetic["payment_format"].get(fmt, 0),
        synthetic["rows"]
    )

    diff = abs(
        op - sp
    )

    format_abs_diffs.append(
        diff
    )

    print(
        f"{fmt:20s} "
        f"| Original={op:8.4f}% "
        f"| Synthetic={sp:8.4f}% "
        f"| AbsDiff={diff:8.4f}"
    )


format_mae = (
    sum(format_abs_diffs)
    / len(format_abs_diffs)
)


# --------------------------------------------------------------------------------------------------
# 7. PAYMENT CURRENCY
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("7. PAYMENT CURRENCY")
print("=" * 80)

all_pc = sorted(
    set(
        original["payment_currency"]
    )
    | set(
        synthetic["payment_currency"]
    )
)

currency_abs_diffs = []

for curr in all_pc:

    op = pct(
        original["payment_currency"].get(curr, 0),
        original["rows"]
    )

    sp = pct(
        synthetic["payment_currency"].get(curr, 0),
        synthetic["rows"]
    )

    diff = abs(
        op - sp
    )

    currency_abs_diffs.append(
        diff
    )

    print(
        f"{curr:20s} "
        f"| Original={op:8.4f}% "
        f"| Synthetic={sp:8.4f}% "
        f"| AbsDiff={diff:8.4f}"
    )


currency_mae = (
    sum(currency_abs_diffs)
    / len(currency_abs_diffs)
)


# --------------------------------------------------------------------------------------------------
# 8. RECEIVING CURRENCY
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("8. RECEIVING CURRENCY")
print("=" * 80)

all_rc = sorted(
    set(
        original["receiving_currency"]
    )
    | set(
        synthetic["receiving_currency"]
    )
)

recv_abs_diffs = []

for curr in all_rc:

    op = pct(
        original["receiving_currency"].get(curr, 0),
        original["rows"]
    )

    sp = pct(
        synthetic["receiving_currency"].get(curr, 0),
        synthetic["rows"]
    )

    diff = abs(
        op - sp
    )

    recv_abs_diffs.append(
        diff
    )

    print(
        f"{curr:20s} "
        f"| Original={op:8.4f}% "
        f"| Synthetic={sp:8.4f}% "
        f"| AbsDiff={diff:8.4f}"
    )


recv_currency_mae = (
    sum(recv_abs_diffs)
    / len(recv_abs_diffs)
)


# --------------------------------------------------------------------------------------------------
# 9. AMOUNT DISTRIBUTION
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("9. AMOUNT DISTRIBUTION")
print("=" * 80)

original_amount_q = quantiles_from_sample(
    original["amount_sample"]
)

synthetic_amount_q = quantiles_from_sample(
    synthetic["amount_sample"]
)


print(
    f"{'Quantile':>12} "
    f"{'Original':>20} "
    f"{'Synthetic':>20} "
    f"{'Ratio':>12}"
)


for key in [
    "p01",
    "p05",
    "p10",
    "p25",
    "p50",
    "p75",
    "p90",
    "p95",
    "p99"
]:

    ov = original_amount_q[key]
    sv = synthetic_amount_q[key]

    ratio = (
        sv / ov
        if ov != 0
        else None
    )

    print(
        f"{key:>12} "
        f"{ov:20.6f} "
        f"{sv:20.6f} "
        f"{ratio:12.4f}"
    )


# --------------------------------------------------------------------------------------------------
# 10. BANK COVERAGE + CONCENTRATION
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("10. BANK COVERAGE + CONCENTRATION")
print("=" * 80)


def top_share(counter, total, k):

    top = counter.most_common(k)

    return (
        sum(v for _, v in top) / total * 100
        if total
        else 0.0
    )


metrics = {

    "source_bank_unique": (
        len(original["source_bank"]),
        len(synthetic["source_bank"])
    ),

    "destination_bank_unique": (
        len(original["destination_bank"]),
        len(synthetic["destination_bank"])
    ),

    "source_account_unique": (
        len(original["source_account"]),
        len(synthetic["source_account"])
    ),

    "destination_account_unique": (
        len(original["destination_account"]),
        len(synthetic["destination_account"])
    ),

    "source_bank_account_unique": (
        len(original["source_bank_account"]),
        len(synthetic["source_bank_account"])
    ),

    "destination_bank_account_unique": (
        len(original["destination_bank_account"]),
        len(synthetic["destination_bank_account"])
    ),
}


for name, (ov, sv) in metrics.items():

    print(
        f"{name:30s} "
        f"| Original={ov:,} "
        f"| Synthetic={sv:,}"
    )


print("\nTop-bank transaction concentration:")


for k in [1, 5, 10, 25, 50, 100]:

    obs = top_share(
        original["source_bank"],
        original["rows"],
        k
    )

    syn = top_share(
        synthetic["source_bank"],
        synthetic["rows"],
        k
    )

    print(
        f"Top {k:3d} source banks "
        f"| Original={obs:9.4f}% "
        f"| Synthetic={syn:9.4f}%"
    )


print("\nTop destination-bank concentration:")


for k in [1, 5, 10, 25, 50, 100]:

    obs = top_share(
        original["destination_bank"],
        original["rows"],
        k
    )

    syn = top_share(
        synthetic["destination_bank"],
        synthetic["rows"],
        k
    )

    print(
        f"Top {k:3d} destination banks "
        f"| Original={obs:9.4f}% "
        f"| Synthetic={syn:9.4f}%"
    )


# --------------------------------------------------------------------------------------------------
# 11. ACCOUNT REUSE DISTRIBUTION
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("11. ACCOUNT REUSE DISTRIBUTION")
print("=" * 80)


def activity_distribution(
    counter,
    total_accounts
):

    buckets = Counter()

    for _, n in counter.items():

        if n == 1:
            buckets["1"] += 1

        elif n == 2:
            buckets["2"] += 1

        elif 3 <= n <= 5:
            buckets["3-5"] += 1

        elif 6 <= n <= 10:
            buckets["6-10"] += 1

        elif 11 <= n <= 25:
            buckets["11-25"] += 1

        elif 26 <= n <= 50:
            buckets["26-50"] += 1

        elif 51 <= n <= 100:
            buckets["51-100"] += 1

        elif 101 <= n <= 250:
            buckets["101-250"] += 1

        elif 251 <= n <= 500:
            buckets["251-500"] += 1

        elif 501 <= n <= 1000:
            buckets["501-1000"] += 1

        else:
            buckets[">1000"] += 1


    return {
        k: {
            "count": v,
            "pct": pct(
                v,
                total_accounts
            )
        }
        for k, v in buckets.items()
    }


orig_src_activity = activity_distribution(
    original["source_account"],
    len(original["source_account"])
)

syn_src_activity = activity_distribution(
    synthetic["source_account"],
    len(synthetic["source_account"])
)

orig_dst_activity = activity_distribution(
    original["destination_account"],
    len(original["destination_account"])
)

syn_dst_activity = activity_distribution(
    synthetic["destination_account"],
    len(synthetic["destination_account"])
)


bucket_order = [
    "1",
    "2",
    "3-5",
    "6-10",
    "11-25",
    "26-50",
    "51-100",
    "101-250",
    "251-500",
    "501-1000",
    ">1000"
]


print("\nSOURCE ACCOUNT ACTIVITY")

for b in bucket_order:

    o = orig_src_activity.get(
        b,
        {"pct": 0.0}
    )["pct"]

    s = syn_src_activity.get(
        b,
        {"pct": 0.0}
    )["pct"]

    print(
        f"{b:10s} "
        f"| Original={o:9.4f}% "
        f"| Synthetic={s:9.4f}% "
        f"| AbsDiff={abs(o-s):8.4f}"
    )


print("\nDESTINATION ACCOUNT ACTIVITY")

for b in bucket_order:

    o = orig_dst_activity.get(
        b,
        {"pct": 0.0}
    )["pct"]

    s = syn_dst_activity.get(
        b,
        {"pct": 0.0}
    )["pct"]

    print(
        f"{b:10s} "
        f"| Original={o:9.4f}% "
        f"| Synthetic={s:9.4f}% "
        f"| AbsDiff={abs(o-s):8.4f}"
    )


# --------------------------------------------------------------------------------------------------
# 12. SUMMARY
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("12. BEHAVIORAL DNA SUMMARY")
print("=" * 80)


summary_rows = [

    (
        "Row count",
        original["rows"],
        synthetic["rows"],
        (
            synthetic["rows"]
            / original["rows"]
            if original["rows"]
            else None
        )
    ),

    (
        "Unique source banks",
        len(original["source_bank"]),
        len(synthetic["source_bank"]),
        None
    ),

    (
        "Unique destination banks",
        len(original["destination_bank"]),
        len(synthetic["destination_bank"]),
        None
    ),

    (
        "Unique source accounts",
        len(original["source_account"]),
        len(synthetic["source_account"]),
        None
    ),

    (
        "Unique destination accounts",
        len(original["destination_account"]),
        len(synthetic["destination_account"]),
        None
    ),

    (
        "Hour MAE (percentage points)",
        None,
        None,
        hour_mae
    ),

    (
        "Day-of-week MAE (percentage points)",
        None,
        None,
        dow_mae
    ),

    (
        "Payment-format MAE (percentage points)",
        None,
        None,
        format_mae
    ),

    (
        "Payment-currency MAE (percentage points)",
        None,
        None,
        currency_mae
    ),

    (
        "Receiving-currency MAE (percentage points)",
        None,
        None,
        recv_currency_mae
    ),

]


for name, ov, sv, metric in summary_rows:

    if (
        ov is not None
        and sv is not None
    ):

        print(
            f"{name:40s} "
            f"| Original={ov:,} "
            f"| Synthetic={sv:,}"
        )

    else:

        print(
            f"{name:40s} "
            f"| Metric={metric:.6f}"
        )


# --------------------------------------------------------------------------------------------------
# 13. SAVE AUDIT JSON
# --------------------------------------------------------------------------------------------------

audit = {

    "synthetic_file":
        SYN_FILE,

    "original_file":
        ORIGINAL_FILE,

    "row_counts": {
        "original":
            original["rows"],
        "synthetic":
            synthetic["rows"],
    },

    "timestamps": {

        "original_min":
            str(
                original["min_timestamp"]
            ),

        "original_max":
            str(
                original["max_timestamp"]
            ),

        "synthetic_min":
            str(
                synthetic["min_timestamp"]
            ),

        "synthetic_max":
            str(
                synthetic["max_timestamp"]
            ),

        "original_active_dates":
            sorted(original_days),

        "synthetic_active_dates":
            sorted(synthetic_days),

        "missing_synthetic_dates":
            sorted(
                missing_synthetic_days
            ),
    },

    "distribution_metrics": {

        "hour_mae_percentage_points":
            hour_mae,

        "day_of_week_mae_percentage_points":
            dow_mae,

        "payment_format_mae_percentage_points":
            format_mae,

        "payment_currency_mae_percentage_points":
            currency_mae,

        "receiving_currency_mae_percentage_points":
            recv_currency_mae,
    },

    "amount_quantiles_sample":
        {
            "original":
                original_amount_q,

            "synthetic":
                synthetic_amount_q,
        },

    "bank_coverage": {

        "original_unique_source_banks":
            len(
                original["source_bank"]
            ),

        "synthetic_unique_source_banks":
            len(
                synthetic["source_bank"]
            ),

        "original_unique_destination_banks":
            len(
                original["destination_bank"]
            ),

        "synthetic_unique_destination_banks":
            len(
                synthetic["destination_bank"]
            ),

        "original_top_source_bank_shares": {
            str(k):
                top_share(
                    original["source_bank"],
                    original["rows"],
                    k
                )
            for k in [1, 5, 10, 25, 50, 100]
        },

        "synthetic_top_source_bank_shares": {
            str(k):
                top_share(
                    synthetic["source_bank"],
                    synthetic["rows"],
                    k
                )
            for k in [1, 5, 10, 25, 50, 100]
        },

        "original_top_destination_bank_shares": {
            str(k):
                top_share(
                    original["destination_bank"],
                    original["rows"],
                    k
                )
            for k in [1, 5, 10, 25, 50, 100]
        },

        "synthetic_top_destination_bank_shares": {
            str(k):
                top_share(
                    synthetic["destination_bank"],
                    synthetic["rows"],
                    k
                )
            for k in [1, 5, 10, 25, 50, 100]
        },
    },

    "account_coverage": {

        "original_unique_source_accounts":
            len(
                original["source_account"]
            ),

        "synthetic_unique_source_accounts":
            len(
                synthetic["source_account"]
            ),

        "original_unique_destination_accounts":
            len(
                original["destination_account"]
            ),

        "synthetic_unique_destination_accounts":
            len(
                synthetic["destination_account"]
            ),
    },

    "payment_format": {

        "original":
            distribution_pct(
                original["payment_format"],
                original["rows"]
            ),

        "synthetic":
            distribution_pct(
                synthetic["payment_format"],
                synthetic["rows"]
            ),
    },

    "payment_currency": {

        "original":
            distribution_pct(
                original["payment_currency"],
                original["rows"]
            ),

        "synthetic":
            distribution_pct(
                synthetic["payment_currency"],
                synthetic["rows"]
            ),
    },

    "receiving_currency": {

        "original":
            distribution_pct(
                original["receiving_currency"],
                original["rows"]
            ),

        "synthetic":
            distribution_pct(
                synthetic["receiving_currency"],
                synthetic["rows"]
            ),
    },

    "hour_distribution": {

        "original":
            distribution_pct(
                original["hour"],
                original["rows"]
            ),

        "synthetic":
            distribution_pct(
                synthetic["hour"],
                synthetic["rows"]
            ),
    },

    "day_of_week_distribution": {

        "original":
            distribution_pct(
                original["day_of_week"],
                original["rows"]
            ),

        "synthetic":
            distribution_pct(
                synthetic["day_of_week"],
                synthetic["rows"]
            ),
    },
}


with open(
    OUT_JSON,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        audit,
        f,
        indent=2
    )


# --------------------------------------------------------------------------------------------------
# SAVE COMPACT CSV
# --------------------------------------------------------------------------------------------------

with open(
    OUT_CSV,
    "w",
    newline="",
    encoding="utf-8"
) as f:

    writer = csv.writer(f)

    writer.writerow([
        "metric",
        "original",
        "synthetic",
        "metric_value"
    ])

    writer.writerow([
        "row_count",
        original["rows"],
        synthetic["rows"],
        ""
    ])

    writer.writerow([
        "unique_source_banks",
        len(original["source_bank"]),
        len(synthetic["source_bank"]),
        ""
    ])

    writer.writerow([
        "unique_destination_banks",
        len(original["destination_bank"]),
        len(synthetic["destination_bank"]),
        ""
    ])

    writer.writerow([
        "unique_source_accounts",
        len(original["source_account"]),
        len(synthetic["source_account"]),
        ""
    ])

    writer.writerow([
        "unique_destination_accounts",
        len(original["destination_account"]),
        len(synthetic["destination_account"]),
        ""
    ])

    writer.writerow([
        "hour_mae_percentage_points",
        "",
        "",
        hour_mae
    ])

    writer.writerow([
        "day_of_week_mae_percentage_points",
        "",
        "",
        dow_mae
    ])

    writer.writerow([
        "payment_format_mae_percentage_points",
        "",
        "",
        format_mae
    ])

    writer.writerow([
        "payment_currency_mae_percentage_points",
        "",
        "",
        currency_mae
    ])

    writer.writerow([
        "receiving_currency_mae_percentage_points",
        "",
        "",
        recv_currency_mae
    ])


# --------------------------------------------------------------------------------------------------
# FINAL
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("✅ CELL 22 COMPLETE")
print("=" * 100)

print(
    "Audit JSON:"
)

print(
    OUT_JSON
)

print(
    "\nAudit CSV:"
)

print(
    OUT_CSV
)

print(
    "\nIMPORTANT:"
)

print(
    "This is a behavioral comparison only."
)

print(
    "No synthetic data was regenerated or modified."
)

print("=" * 100)

====================================================================================================
CELL 22 — SYNTHETIC vs ORIGINAL HI-SMALL BEHAVIORAL DNA AUDIT
====================================================================================================

Synthetic file:
/kaggle/working/AML_GNN_ONLY/data/HI-Small_SYNTH_FULL_transactions.csv

Original file:
/kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml/HI-Small_Trans.csv

================================================================================
1. STREAMING ORIGINAL HI-SMALL
================================================================================

RuntimeError: ORIGINAL: missing columns: ['Account.1']

In [34]:
# ==================================================================================================
# FINAL MERGE CELL — CORRECTED FOR IBM DUPLICATE "Account" COLUMNS
#
# Creates:
#   1) HI-Small_FINAL_transactions_10146336.csv
#   2) HI-Small_FINAL_accounts_1004953.csv
#   3) HI-Small_FINAL_Patterns.txt
#
# IMPORTANT:
#   - DOES NOT regenerate synthetic data
#   - Uses the already-completed synthetic files
#   - Original HI-Small transaction file is read POSITIONALLY because
#     it contains two columns named "Account"
# ==================================================================================================

import os
import csv
import shutil
from IPython.display import FileLink, display


# --------------------------------------------------------------------------------------------------
# PATHS
# --------------------------------------------------------------------------------------------------

BASE = "/kaggle/working/AML_GNN_ONLY/data"

ORIGINAL_TRANS = (
    "/kaggle/input/datasets/"
    "ealtman2019/ibm-transactions-for-anti-money-laundering-aml/"
    "HI-Small_Trans.csv"
)

ORIGINAL_ACCOUNTS = (
    "/kaggle/input/datasets/"
    "ealtman2019/ibm-transactions-for-anti-money-laundering-aml/"
    "HI-Small_accounts.csv"
)

ORIGINAL_PATTERNS = (
    "/kaggle/input/datasets/"
    "ealtman2019/ibm-transactions-for-anti-money-laundering-aml/"
    "HI-Small_Patterns.txt"
)

SYNTH_TRANS = os.path.join(
    BASE,
    "HI-Small_SYNTH_FULL_transactions.csv"
)

SYNTH_ACCOUNTS = os.path.join(
    BASE,
    "HI-Small_SYNTH_FULL_new_accounts.csv"
)

SYNTH_PATTERNS = os.path.join(
    BASE,
    "HI-Small_SYNTH_FULL_Patterns.txt"
)


# --------------------------------------------------------------------------------------------------
# FINAL OUTPUT FILES
# --------------------------------------------------------------------------------------------------

FINAL_TRANS = os.path.join(
    BASE,
    "HI-Small_FINAL_transactions_10146336.csv"
)

FINAL_ACCOUNTS = os.path.join(
    BASE,
    "HI-Small_FINAL_accounts_1004953.csv"
)

FINAL_PATTERNS = os.path.join(
    BASE,
    "HI-Small_FINAL_Patterns.txt"
)


# --------------------------------------------------------------------------------------------------
# EXPECTED COUNTS
# --------------------------------------------------------------------------------------------------

EXPECTED_ORIGINAL_TRANS = 5_078_345
EXPECTED_SYNTH_TRANS = 5_067_991
EXPECTED_FINAL_TRANS = 10_146_336

EXPECTED_ORIGINAL_ACCOUNTS = 518_581
EXPECTED_SYNTH_ACCOUNTS = 486_372
EXPECTED_FINAL_ACCOUNTS = 1_004_953

EXPECTED_ORIGINAL_PATTERN_EPISODES = 370
EXPECTED_SYNTH_PATTERN_EPISODES = 584_706
EXPECTED_FINAL_PATTERN_EPISODES = 585_076

EXPECTED_ORIGINAL_PATTERN_TX = 3_209
EXPECTED_SYNTH_PATTERN_TX = 5_067_991
EXPECTED_FINAL_PATTERN_TX = 5_071_200


# --------------------------------------------------------------------------------------------------
# HELPERS
# --------------------------------------------------------------------------------------------------

def norm_col(x):
    return (
        str(x)
        .strip()
        .lower()
        .replace(" ", "")
        .replace("_", "")
        .replace(".", "")
    )


def find_column(header, names):

    normalized = {
        norm_col(h): h
        for h in header
    }

    for name in names:

        key = norm_col(name)

        if key in normalized:
            return normalized[key]

    for h in header:

        hl = norm_col(h)

        for name in names:

            if norm_col(name) in hl:
                return h

    return None


def file_mb(path):
    return os.path.getsize(path) / (1024 * 1024)


# --------------------------------------------------------------------------------------------------
# START
# --------------------------------------------------------------------------------------------------

print("=" * 100)
print("FINAL HI-SMALL MERGE — CORRECTED")
print("=" * 100)


# --------------------------------------------------------------------------------------------------
# 1. INPUT FILE CHECK
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("1. INPUT FILE CHECK")
print("=" * 80)

inputs = {
    "Original transactions": ORIGINAL_TRANS,
    "Original accounts": ORIGINAL_ACCOUNTS,
    "Original patterns": ORIGINAL_PATTERNS,
    "Synthetic transactions": SYNTH_TRANS,
    "Synthetic accounts": SYNTH_ACCOUNTS,
    "Synthetic patterns": SYNTH_PATTERNS,
}

for name, path in inputs.items():

    if not os.path.exists(path):
        raise FileNotFoundError(
            f"Missing {name}:\n{path}"
        )

    print(
        f"✅ {name:25s} | "
        f"{file_mb(path):,.2f} MB"
    )


# --------------------------------------------------------------------------------------------------
# 2. FINAL TRANSACTION SCHEMA
# --------------------------------------------------------------------------------------------------

FINAL_TRANSACTION_COLUMNS = [
    "transaction_id",
    "Timestamp",
    "From Bank",
    "Account",
    "To Bank",
    "Account.1",
    "Amount Received",
    "Receiving Currency",
    "Amount Paid",
    "Payment Currency",
    "Payment Format",
    "Is Laundering",
    "is_synthetic",
    "synthetic_episode_id",
    "typology",
    "source_template_id",
    "template_source_order",
]


# --------------------------------------------------------------------------------------------------
# 3. INSPECT ORIGINAL TRANSACTION HEADER POSITIONALLY
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("2. ORIGINAL TRANSACTION HEADER")
print("=" * 80)


with open(
    ORIGINAL_TRANS,
    "r",
    newline="",
    encoding="utf-8-sig"
) as f:

    reader = csv.reader(f)

    original_header = next(reader)


print(
    "Original header:"
)

for i, col in enumerate(original_header):

    print(
        f"  [{i}] {col}"
    )


# Expected IBM structure:
#
# 0 Timestamp
# 1 From Bank
# 2 Account            <- SOURCE ACCOUNT
# 3 To Bank
# 4 Account            <- DESTINATION ACCOUNT
# 5 Amount Received
# 6 Receiving Currency
# 7 Amount Paid
# 8 Payment Currency
# 9 Payment Format
# 10 Is Laundering


if len(original_header) != 11:

    raise RuntimeError(
        "Unexpected original HI-Small transaction "
        f"column count: {len(original_header)}"
    )


# Positional mapping — IMPORTANT
ORIG_TS = 0
ORIG_FROM_BANK = 1
ORIG_SOURCE_ACCOUNT = 2
ORIG_TO_BANK = 3
ORIG_DEST_ACCOUNT = 4
ORIG_AMOUNT_RECEIVED = 5
ORIG_RECEIVING_CURRENCY = 6
ORIG_AMOUNT_PAID = 7
ORIG_PAYMENT_CURRENCY = 8
ORIG_PAYMENT_FORMAT = 9
ORIG_IS_LAUNDERING = 10


# Verify expected names in the expected positions
expected_names = [
    "Timestamp",
    "From Bank",
    "Account",
    "To Bank",
    "Account",
    "Amount Received",
    "Receiving Currency",
    "Amount Paid",
    "Payment Currency",
    "Payment Format",
    "Is Laundering",
]

if original_header != expected_names:

    raise RuntimeError(
        "Original HI-Small header differs from expected positional schema.\n"
        f"Actual  : {original_header}\n"
        f"Expected: {expected_names}"
    )


print(
    "\n✅ Original duplicate Account columns resolved positionally:"
)

print(
    "   original column [2] Account -> final 'Account'"
)

print(
    "   original column [4] Account -> final 'Account.1'"
)


# --------------------------------------------------------------------------------------------------
# 4. INSPECT SYNTHETIC TRANSACTION FILE
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("3. SYNTHETIC TRANSACTION SCHEMA")
print("=" * 80)


with open(
    SYNTH_TRANS,
    "r",
    newline="",
    encoding="utf-8"
) as f:

    reader = csv.reader(f)

    synth_header = next(reader)


for i, col in enumerate(synth_header):

    print(
        f"  [{i}] {col}"
    )


missing_synthetic_columns = [
    col
    for col in FINAL_TRANSACTION_COLUMNS
    if col not in synth_header
]


if missing_synthetic_columns:

    raise RuntimeError(
        "Synthetic transaction file missing columns:\n"
        + str(missing_synthetic_columns)
    )


print(
    "\n✅ Synthetic transaction schema validated."
)


# --------------------------------------------------------------------------------------------------
# 5. MERGE TRANSACTIONS
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("4. MERGING TRANSACTIONS")
print("=" * 80)


# Remove any partial output
if os.path.exists(FINAL_TRANS):

    os.remove(FINAL_TRANS)

    print(
        "Removed previous partial final transaction file."
    )


original_count = 0
synthetic_count = 0


with open(
    FINAL_TRANS,
    "w",
    newline="",
    encoding="utf-8"
) as out_f:

    writer = csv.DictWriter(
        out_f,
        fieldnames=FINAL_TRANSACTION_COLUMNS
    )

    writer.writeheader()


    # ==============================================================================================
    # ORIGINAL TRANSACTIONS — POSITIONAL READ
    # ==============================================================================================

    print(
        "\nWriting original transactions..."
    )

    with open(
        ORIGINAL_TRANS,
        "r",
        newline="",
        encoding="utf-8-sig"
    ) as f:

        reader = csv.reader(f)

        next(reader)


        for row in reader:

            if len(row) != 11:

                raise RuntimeError(
                    "Unexpected original transaction row length "
                    f"at row {original_count + 2}: "
                    f"{len(row)}"
                )


            original_count += 1


            writer.writerow({

                "transaction_id":
                    f"ORIG_{original_count:010d}",

                "Timestamp":
                    row[ORIG_TS],

                "From Bank":
                    row[ORIG_FROM_BANK],

                # SOURCE ACCOUNT
                "Account":
                    row[ORIG_SOURCE_ACCOUNT],

                "To Bank":
                    row[ORIG_TO_BANK],

                # DESTINATION ACCOUNT
                "Account.1":
                    row[ORIG_DEST_ACCOUNT],

                "Amount Received":
                    row[ORIG_AMOUNT_RECEIVED],

                "Receiving Currency":
                    row[ORIG_RECEIVING_CURRENCY],

                "Amount Paid":
                    row[ORIG_AMOUNT_PAID],

                "Payment Currency":
                    row[ORIG_PAYMENT_CURRENCY],

                "Payment Format":
                    row[ORIG_PAYMENT_FORMAT],

                "Is Laundering":
                    row[ORIG_IS_LAUNDERING],

                "is_synthetic":
                    0,

                "synthetic_episode_id":
                    "",

                "typology":
                    "",

                "source_template_id":
                    "",

                "template_source_order":
                    "",
            })


            if (
                original_count % 1_000_000 == 0
            ):

                print(
                    f"  Original written: "
                    f"{original_count:,}"
                )


    print(
        f"✅ Original transactions written: "
        f"{original_count:,}"
    )


    # ==============================================================================================
    # SYNTHETIC TRANSACTIONS
    # ==============================================================================================

    print(
        "\nWriting synthetic transactions..."
    )

    with open(
        SYNTH_TRANS,
        "r",
        newline="",
        encoding="utf-8"
    ) as f:

        reader = csv.DictReader(f)


        for row in reader:

            synthetic_count += 1


            writer.writerow({

                col:
                    row[col]
                for col in FINAL_TRANSACTION_COLUMNS

            })


            if (
                synthetic_count % 1_000_000 == 0
            ):

                print(
                    f"  Synthetic written: "
                    f"{synthetic_count:,}"
                )


    print(
        f"✅ Synthetic transactions written: "
        f"{synthetic_count:,}"
    )


final_transaction_count = (
    original_count
    + synthetic_count
)


print(
    "\nTransaction merge result:"
)

print(
    f"  Original  : {original_count:,}"
)

print(
    f"  Synthetic : {synthetic_count:,}"
)

print(
    f"  FINAL     : {final_transaction_count:,}"
)

print(
    f"  EXPECTED  : {EXPECTED_FINAL_TRANS:,}"
)


if (
    original_count != EXPECTED_ORIGINAL_TRANS
    or synthetic_count != EXPECTED_SYNTH_TRANS
    or final_transaction_count != EXPECTED_FINAL_TRANS
):

    raise RuntimeError(
        "❌ FINAL TRANSACTION COUNT VALIDATION FAILED."
    )


print(
    "✅ Transaction merge PASSED."
)


# --------------------------------------------------------------------------------------------------
# 6. MERGE ACCOUNTS
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("5. MERGING ACCOUNTS")
print("=" * 80)


FINAL_ACCOUNT_COLUMNS = [
    "Bank Name",
    "Bank ID",
    "Account Number",
    "Entity ID",
    "Entity Name",
]


def resolve_account_columns(header):

    return {

        "Bank Name":
            find_column(
                header,
                [
                    "Bank Name",
                    "BankName"
                ]
            ),

        "Bank ID":
            find_column(
                header,
                [
                    "Bank ID",
                    "BankID",
                    "bank_id"
                ]
            ),

        "Account Number":
            find_column(
                header,
                [
                    "Account Number",
                    "AccountNumber",
                    "Account"
                ]
            ),

        "Entity ID":
            find_column(
                header,
                [
                    "Entity ID",
                    "EntityID",
                    "entity_id"
                ]
            ),

        "Entity Name":
            find_column(
                header,
                [
                    "Entity Name",
                    "EntityName",
                    "entity_name"
                ]
            ),
    }


# Read original account header
with open(
    ORIGINAL_ACCOUNTS,
    "r",
    newline="",
    encoding="utf-8-sig"
) as f:

    reader = csv.DictReader(f)

    original_account_header = (
        reader.fieldnames
    )


# Read synthetic account header
with open(
    SYNTH_ACCOUNTS,
    "r",
    newline="",
    encoding="utf-8-sig"
) as f:

    reader = csv.DictReader(f)

    synthetic_account_header = (
        reader.fieldnames
    )


print(
    "Original accounts:"
)

print(
    original_account_header
)


print(
    "\nSynthetic accounts:"
)

print(
    synthetic_account_header
)


original_account_cols = (
    resolve_account_columns(
        original_account_header
    )
)

synthetic_account_cols = (
    resolve_account_columns(
        synthetic_account_header
    )
)


missing_original_accounts = [
    k
    for k, v in original_account_cols.items()
    if v is None
]

missing_synthetic_accounts = [
    k
    for k, v in synthetic_account_cols.items()
    if v is None
]


if missing_original_accounts:

    raise RuntimeError(
        "Original accounts missing:\n"
        + str(missing_original_accounts)
    )


if missing_synthetic_accounts:

    raise RuntimeError(
        "Synthetic accounts missing:\n"
        + str(missing_synthetic_accounts)
    )


if os.path.exists(FINAL_ACCOUNTS):

    os.remove(FINAL_ACCOUNTS)


account_original_count = 0
account_synthetic_count = 0


with open(
    FINAL_ACCOUNTS,
    "w",
    newline="",
    encoding="utf-8"
) as out_f:

    writer = csv.DictWriter(
        out_f,
        fieldnames=FINAL_ACCOUNT_COLUMNS
    )

    writer.writeheader()


    # ==============================================================================================
    # ORIGINAL ACCOUNTS
    # ==============================================================================================

    with open(
        ORIGINAL_ACCOUNTS,
        "r",
        newline="",
        encoding="utf-8-sig"
    ) as f:

        reader = csv.DictReader(f)

        for row in reader:

            account_original_count += 1

            writer.writerow({

                col:
                    row[
                        original_account_cols[col]
                    ]

                for col
                in FINAL_ACCOUNT_COLUMNS

            })


    # ==============================================================================================
    # SYNTHETIC ACCOUNTS
    # ==============================================================================================

    with open(
        SYNTH_ACCOUNTS,
        "r",
        newline="",
        encoding="utf-8-sig"
    ) as f:

        reader = csv.DictReader(f)

        for row in reader:

            account_synthetic_count += 1

            writer.writerow({

                col:
                    row[
                        synthetic_account_cols[col]
                    ]

                for col
                in FINAL_ACCOUNT_COLUMNS

            })


final_account_count = (
    account_original_count
    + account_synthetic_count
)


print(
    f"Original accounts : "
    f"{account_original_count:,}"
)

print(
    f"Synthetic accounts: "
    f"{account_synthetic_count:,}"
)

print(
    f"FINAL accounts    : "
    f"{final_account_count:,}"
)

print(
    f"EXPECTED accounts : "
    f"{EXPECTED_FINAL_ACCOUNTS:,}"
)


if (
    account_original_count != EXPECTED_ORIGINAL_ACCOUNTS
    or account_synthetic_count != EXPECTED_SYNTH_ACCOUNTS
    or final_account_count != EXPECTED_FINAL_ACCOUNTS
):

    raise RuntimeError(
        "❌ FINAL ACCOUNT COUNT VALIDATION FAILED."
    )


print(
    "✅ Account merge PASSED."
)


# --------------------------------------------------------------------------------------------------
# 7. MERGE PATTERNS
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("6. MERGING PATTERNS.TXT")
print("=" * 80)


if os.path.exists(FINAL_PATTERNS):

    os.remove(FINAL_PATTERNS)


# Copy original
with open(
    FINAL_PATTERNS,
    "wb"
) as out_f:

    with open(
        ORIGINAL_PATTERNS,
        "rb"
    ) as f:

        shutil.copyfileobj(
            f,
            out_f,
            length=8 * 1024 * 1024
        )


# Ensure newline between original and synthetic pattern files
with open(
    ORIGINAL_PATTERNS,
    "rb"
) as f:

    if os.path.getsize(ORIGINAL_PATTERNS) > 0:

        f.seek(-1, os.SEEK_END)

        last_byte = f.read(1)

        if last_byte != b"\n":

            with open(
                FINAL_PATTERNS,
                "ab"
            ) as out_f:

                out_f.write(
                    b"\n"
                )


# Append synthetic
with open(
    FINAL_PATTERNS,
    "ab"
) as out_f:

    with open(
        SYNTH_PATTERNS,
        "rb"
    ) as f:

        shutil.copyfileobj(
            f,
            out_f,
            length=8 * 1024 * 1024
        )


print(
    f"Original Patterns : "
    f"{file_mb(ORIGINAL_PATTERNS):,.2f} MB"
)

print(
    f"Synthetic Patterns: "
    f"{file_mb(SYNTH_PATTERNS):,.2f} MB"
)

print(
    f"FINAL Patterns    : "
    f"{file_mb(FINAL_PATTERNS):,.2f} MB"
)

print(
    "✅ Pattern merge completed."
)


# --------------------------------------------------------------------------------------------------
# 8. FINAL VALIDATION
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("7. FINAL MERGED FILE VALIDATION")
print("=" * 80)


# --------------------------------------------------------------------------------
# Transactions
# --------------------------------------------------------------------------------

with open(
    FINAL_TRANS,
    "r",
    encoding="utf-8"
) as f:

    final_tx_lines = sum(
        1
        for _ in f
    ) - 1


# --------------------------------------------------------------------------------
# Accounts
# --------------------------------------------------------------------------------

with open(
    FINAL_ACCOUNTS,
    "r",
    encoding="utf-8"
) as f:

    final_account_lines = sum(
        1
        for _ in f
    ) - 1


# --------------------------------------------------------------------------------
# Patterns
# --------------------------------------------------------------------------------

final_pattern_ids = 0
final_pattern_begin = 0
final_pattern_end = 0
final_pattern_tx = 0

inside_episode = False


with open(
    FINAL_PATTERNS,
    "r",
    encoding="utf-8"
) as f:

    for raw in f:

        line = raw.strip()

        if not line:
            continue


        if line.startswith(
            'id="'
        ):

            final_pattern_ids += 1
            continue


        if line.startswith(
            "BEGIN LAUNDERING ATTEMPT"
        ):

            final_pattern_begin += 1
            inside_episode = True
            continue


        if line.startswith(
            "END LAUNDERING ATTEMPT"
        ):

            final_pattern_end += 1
            inside_episode = False
            continue


        if inside_episode:

            final_pattern_tx += 1


print(
    f"Final transactions    : "
    f"{final_tx_lines:,}"
)

print(
    f"Expected transactions : "
    f"{EXPECTED_FINAL_TRANS:,}"
)

print(
    f"Final accounts        : "
    f"{final_account_lines:,}"
)

print(
    f"Expected accounts     : "
    f"{EXPECTED_FINAL_ACCOUNTS:,}"
)

print(
    f"Final pattern IDs     : "
    f"{final_pattern_ids:,}"
)

print(
    f"Expected pattern IDs  : "
    f"{EXPECTED_FINAL_PATTERN_EPISODES:,}"
)

print(
    f"Final BEGIN markers   : "
    f"{final_pattern_begin:,}"
)

print(
    f"Final END markers     : "
    f"{final_pattern_end:,}"
)

print(
    f"Final pattern TX      : "
    f"{final_pattern_tx:,}"
)

print(
    f"Expected pattern TX   : "
    f"{EXPECTED_FINAL_PATTERN_TX:,}"
)


final_validation = {

    "transactions":
        final_tx_lines == EXPECTED_FINAL_TRANS,

    "accounts":
        final_account_lines == EXPECTED_FINAL_ACCOUNTS,

    "pattern_ids":
        final_pattern_ids == EXPECTED_FINAL_PATTERN_EPISODES,

    "pattern_begin":
        final_pattern_begin == EXPECTED_FINAL_PATTERN_EPISODES,

    "pattern_end":
        final_pattern_end == EXPECTED_FINAL_PATTERN_EPISODES,

    "pattern_transactions":
        final_pattern_tx == EXPECTED_FINAL_PATTERN_TX,
}


# --------------------------------------------------------------------------------
# Print gates
# --------------------------------------------------------------------------------

print("\nFinal validation gates:")

all_pass = True

for name, passed in final_validation.items():

    print(
        f"{'✅ PASS' if passed else '❌ FAIL'} | {name}"
    )

    all_pass &= passed


if not all_pass:

    raise RuntimeError(
        "\n❌ FINAL MERGED DATASET VALIDATION FAILED."
    )


# --------------------------------------------------------------------------------------------------
# 9. FINAL FILE INFORMATION
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("8. FINAL FILES")
print("=" * 80)


for path in [
    FINAL_TRANS,
    FINAL_ACCOUNTS,
    FINAL_PATTERNS,
]:

    print(
        f"{os.path.basename(path):50s} "
        f"{file_mb(path):12,.2f} MB"
    )


# --------------------------------------------------------------------------------------------------
# 10. KAGGLE DOWNLOAD LINKS
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("9. DOWNLOAD LINKS")
print("=" * 80)


print(
    "\n⬇️ FINAL TRANSACTIONS — 10,146,336 rows"
)

display(
    FileLink(FINAL_TRANS)
)


print(
    "\n⬇️ FINAL ACCOUNTS — 1,004,953 rows"
)

display(
    FileLink(FINAL_ACCOUNTS)
)


print(
    "\n⬇️ FINAL PATTERNS.TXT — 585,076 episodes"
)

display(
    FileLink(FINAL_PATTERNS)
)


# --------------------------------------------------------------------------------------------------
# DONE
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 100)
print(
    "✅✅✅ ALL THREE FINAL MERGED FILES ARE READY ✅✅✅"
)
print("=" * 100)

print(
    f"Transactions : {FINAL_TRANS}"
)

print(
    f"Accounts     : {FINAL_ACCOUNTS}"
)

print(
    f"Patterns     : {FINAL_PATTERNS}"
)

print("=" * 100)

====================================================================================================
FINAL HI-SMALL MERGE — CORRECTED
====================================================================================================

================================================================================
1. INPUT FILE CHECK
================================================================================
✅ Original transactions     | 453.63 MB
✅ Original accounts         | 32.48 MB
✅ Original patterns         | 0.31 MB
✅ Synthetic transactions    | 844.22 MB
✅ Synthetic accounts        | 27.85 MB
✅ Synthetic patterns        | 570.76 MB

================================================================================
2. ORIGINAL TRANSACTION HEADER
================================================================================
Original header:
  [0] Timestamp
  [1] From Bank
  [2] Account
  [3] To Bank
  [4] Account
  [5] Amount Received
  [6] Receiving Currency
  [7] Amount Paid
  [8] Payment Currency
  [9] Payment Format
  [10] Is Laundering

✅ Original duplicate Account columns resolved positionally:
   original column [2] Account -> final 'Account'
   original column [4] Account -> final 'Account.1'

================================================================================
3. SYNTHETIC TRANSACTION SCHEMA
================================================================================
  [0] transaction_id
  [1] Timestamp
  [2] From Bank
  [3] Account
  [4] To Bank
  [5] Account.1
  [6] Amount Received
  [7] Receiving Currency
  [8] Amount Paid
  [9] Payment Currency
  [10] Payment Format
  [11] Is Laundering
  [12] is_synthetic
  [13] synthetic_episode_id
  [14] typology
  [15] source_template_id
  [16] template_source_order

✅ Synthetic transaction schema validated.

================================================================================
4. MERGING TRANSACTIONS
================================================================================

Writing original transactions...
  Original written: 1,000,000
  Original written: 2,000,000
  Original written: 3,000,000
  Original written: 4,000,000
  Original written: 5,000,000
✅ Original transactions written: 5,078,345

Writing synthetic transactions...
  Synthetic written: 1,000,000
  Synthetic written: 2,000,000
  Synthetic written: 3,000,000
  Synthetic written: 4,000,000
  Synthetic written: 5,000,000
✅ Synthetic transactions written: 5,067,991

Transaction merge result:
  Original  : 5,078,345
  Synthetic : 5,067,991
  FINAL     : 10,146,336
  EXPECTED  : 10,146,336
✅ Transaction merge PASSED.

================================================================================
5. MERGING ACCOUNTS
================================================================================
Original accounts:
['Bank Name', 'Bank ID', 'Account Number', 'Entity ID', 'Entity Name']

Synthetic accounts:
['Bank Name', 'Bank ID', 'Account Number', 'Entity ID', 'Entity Name']
Original accounts : 518,581
Synthetic accounts: 486,372
FINAL accounts    : 1,004,953
EXPECTED accounts : 1,004,953
✅ Account merge PASSED.

================================================================================
6. MERGING PATTERNS.TXT
================================================================================
Original Patterns : 0.31 MB
Synthetic Patterns: 570.76 MB
FINAL Patterns    : 571.07 MB
✅ Pattern merge completed.

================================================================================
7. FINAL MERGED FILE VALIDATION
================================================================================
Final transactions    : 10,146,336
Expected transactions : 10,146,336
Final accounts        : 1,004,953
Expected accounts     : 1,004,953
Final pattern IDs     : 584,706
Expected pattern IDs  : 585,076
Final BEGIN markers   : 585,076
Final END markers     : 585,076
Final pattern TX      : 5,071,200
Expected pattern TX   : 5,071,200

Final validation gates:
✅ PASS | transactions
✅ PASS | accounts
❌ FAIL | pattern_ids
✅ PASS | pattern_begin
✅ PASS | pattern_end
✅ PASS | pattern_transactions

RuntimeError:
❌ FINAL MERGED DATASET VALIDATION FAILED.

In [35]:
# ==================================================================================================
# FINAL VALIDATION + DOWNLOAD
#
# IMPORTANT:
#   The previous merge is ALREADY CORRECT.
#
#   The failure happened because:
#       - Original IBM Patterns file has 370 episodes
#       - Original IBM Patterns file has 0 id="..." lines
#       - Synthetic Patterns file has 584,706 id="..." lines
#       - Final file therefore correctly has 584,706 ID lines
#       - BUT it has 585,076 BEGIN and END markers
#
#   This cell:
#       1. Validates the already-created final files
#       2. Confirms original Patterns ID count
#       3. Creates the final manifest
#       4. Shows download links
#
#   NO DATA REGENERATION.
# ==================================================================================================

import os
import csv
import json
from IPython.display import FileLink, display


# --------------------------------------------------------------------------------------------------
# PATHS
# --------------------------------------------------------------------------------------------------

BASE = "/kaggle/working/AML_GNN_ONLY/data"

ORIGINAL_TRANS = (
    "/kaggle/input/datasets/"
    "ealtman2019/ibm-transactions-for-anti-money-laundering-aml/"
    "HI-Small_Trans.csv"
)

ORIGINAL_ACCOUNTS = (
    "/kaggle/input/datasets/"
    "ealtman2019/ibm-transactions-for-anti-money-laundering-aml/"
    "HI-Small_accounts.csv"
)

ORIGINAL_PATTERNS = (
    "/kaggle/input/datasets/"
    "ealtman2019/ibm-transactions-for-anti-money-laundering-aml/"
    "HI-Small_Patterns.txt"
)

FINAL_TRANS = os.path.join(
    BASE,
    "HI-Small_FINAL_transactions_10146336.csv"
)

FINAL_ACCOUNTS = os.path.join(
    BASE,
    "HI-Small_FINAL_accounts_1004953.csv"
)

FINAL_PATTERNS = os.path.join(
    BASE,
    "HI-Small_FINAL_Patterns.txt"
)

MANIFEST = os.path.join(
    BASE,
    "HI-Small_FINAL_manifest.json"
)


# --------------------------------------------------------------------------------------------------
# EXPECTED VALUES
# --------------------------------------------------------------------------------------------------

EXPECTED_FINAL_TRANS = 10_146_336
EXPECTED_FINAL_ACCOUNTS = 1_004_953

ORIGINAL_PATTERN_EPISODES = 370
SYNTH_PATTERN_EPISODES = 584_706
EXPECTED_FINAL_PATTERN_EPISODES = (
    ORIGINAL_PATTERN_EPISODES
    + SYNTH_PATTERN_EPISODES
)

ORIGINAL_PATTERN_TX = 3_209
SYNTH_PATTERN_TX = 5_067_991
EXPECTED_FINAL_PATTERN_TX = (
    ORIGINAL_PATTERN_TX
    + SYNTH_PATTERN_TX
)


# --------------------------------------------------------------------------------------------------
# HELPERS
# --------------------------------------------------------------------------------------------------

def mb(path):
    return os.path.getsize(path) / (1024 * 1024)


def require(path):
    if not os.path.exists(path):
        raise FileNotFoundError(path)


# --------------------------------------------------------------------------------------------------
# START
# --------------------------------------------------------------------------------------------------

print("=" * 100)
print("FINAL HI-SMALL MERGED DATASET VALIDATION")
print("=" * 100)


# --------------------------------------------------------------------------------------------------
# 1. FILE EXISTENCE
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("1. FINAL FILE EXISTENCE")
print("=" * 80)

for name, path in {
    "FINAL TRANSACTIONS": FINAL_TRANS,
    "FINAL ACCOUNTS": FINAL_ACCOUNTS,
    "FINAL PATTERNS": FINAL_PATTERNS,
}.items():

    require(path)

    print(
        f"✅ {name:20s} | "
        f"{mb(path):,.2f} MB | "
        f"{os.path.basename(path)}"
    )


# --------------------------------------------------------------------------------------------------
# 2. COUNT ID LINES IN ORIGINAL PATTERNS
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("2. ORIGINAL IBM PATTERNS STRUCTURE")
print("=" * 80)

original_pattern_ids = 0
original_begin = 0
original_end = 0
original_tx = 0

inside = False


with open(
    ORIGINAL_PATTERNS,
    "r",
    encoding="utf-8"
) as f:

    for raw in f:

        line = raw.strip()

        if not line:
            continue

        if line.startswith('id="'):

            original_pattern_ids += 1

        elif line.startswith(
            "BEGIN LAUNDERING ATTEMPT"
        ):

            original_begin += 1
            inside = True

        elif line.startswith(
            "END LAUNDERING ATTEMPT"
        ):

            original_end += 1
            inside = False

        elif inside:

            original_tx += 1


print(
    f"Original ID lines       : "
    f"{original_pattern_ids:,}"
)

print(
    f"Original BEGIN markers  : "
    f"{original_begin:,}"
)

print(
    f"Original END markers    : "
    f"{original_end:,}"
)

print(
    f"Original TX lines       : "
    f"{original_tx:,}"
)


# The observed original file structure is:
#   0 ID lines
#   370 BEGIN
#   370 END
#   3,209 TX

original_pattern_gate = (
    original_pattern_ids == 0
    and original_begin == ORIGINAL_PATTERN_EPISODES
    and original_end == ORIGINAL_PATTERN_EPISODES
    and original_tx == ORIGINAL_PATTERN_TX
)


print(
    "\n✅ Original IBM pattern structure PASS"
    if original_pattern_gate
    else "\n❌ Original IBM pattern structure FAIL"
)


# --------------------------------------------------------------------------------------------------
# 3. FINAL TRANSACTION COUNT
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("3. FINAL TRANSACTION FILE")
print("=" * 80)


with open(
    FINAL_TRANS,
    "r",
    encoding="utf-8"
) as f:

    final_transaction_rows = (
        sum(1 for _ in f) - 1
    )


print(
    f"Final transaction rows : "
    f"{final_transaction_rows:,}"
)

print(
    f"Expected                : "
    f"{EXPECTED_FINAL_TRANS:,}"
)


transaction_gate = (
    final_transaction_rows
    == EXPECTED_FINAL_TRANS
)


print(
    "✅ PASS"
    if transaction_gate
    else "❌ FAIL"
)


# --------------------------------------------------------------------------------------------------
# 4. FINAL ACCOUNT COUNT
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("4. FINAL ACCOUNT FILE")
print("=" * 80)


with open(
    FINAL_ACCOUNTS,
    "r",
    encoding="utf-8"
) as f:

    final_account_rows = (
        sum(1 for _ in f) - 1
    )


print(
    f"Final account rows : "
    f"{final_account_rows:,}"
)

print(
    f"Expected           : "
    f"{EXPECTED_FINAL_ACCOUNTS:,}"
)


account_gate = (
    final_account_rows
    == EXPECTED_FINAL_ACCOUNTS
)


print(
    "✅ PASS"
    if account_gate
    else "❌ FAIL"
)


# --------------------------------------------------------------------------------------------------
# 5. FINAL PATTERNS VALIDATION
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("5. FINAL PATTERNS FILE")
print("=" * 80)


final_pattern_ids = 0
final_pattern_begin = 0
final_pattern_end = 0
final_pattern_tx = 0

inside = False


with open(
    FINAL_PATTERNS,
    "r",
    encoding="utf-8"
) as f:

    for raw in f:

        line = raw.strip()

        if not line:
            continue


        if line.startswith('id="'):

            final_pattern_ids += 1


        elif line.startswith(
            "BEGIN LAUNDERING ATTEMPT"
        ):

            final_pattern_begin += 1
            inside = True


        elif line.startswith(
            "END LAUNDERING ATTEMPT"
        ):

            final_pattern_end += 1
            inside = False


        elif inside:

            final_pattern_tx += 1


print(
    f"Final ID lines       : "
    f"{final_pattern_ids:,}"
)

print(
    f"Final BEGIN markers  : "
    f"{final_pattern_begin:,}"
)

print(
    f"Final END markers    : "
    f"{final_pattern_end:,}"
)

print(
    f"Final TX lines       : "
    f"{final_pattern_tx:,}"
)


# IMPORTANT:
# ID lines are NOT expected to equal the number of episodes because
# the original IBM Patterns.txt contributes 0 id="..." lines.

pattern_id_expected = (
    original_pattern_ids
    + SYNTH_PATTERN_EPISODES
)


print(
    f"\nExpected ID lines    : "
    f"{pattern_id_expected:,}"
)

print(
    f"Expected BEGIN/END   : "
    f"{EXPECTED_FINAL_PATTERN_EPISODES:,}"
)

print(
    f"Expected TX lines    : "
    f"{EXPECTED_FINAL_PATTERN_TX:,}"
)


pattern_id_gate = (
    final_pattern_ids
    == pattern_id_expected
)

pattern_begin_gate = (
    final_pattern_begin
    == EXPECTED_FINAL_PATTERN_EPISODES
)

pattern_end_gate = (
    final_pattern_end
    == EXPECTED_FINAL_PATTERN_EPISODES
)

pattern_tx_gate = (
    final_pattern_tx
    == EXPECTED_FINAL_PATTERN_TX
)


print(
    f"\n{'✅ PASS' if pattern_id_gate else '❌ FAIL'} "
    "| Pattern ID lines"
)

print(
    f"{'✅ PASS' if pattern_begin_gate else '❌ FAIL'} "
    "| Pattern BEGIN markers"
)

print(
    f"{'✅ PASS' if pattern_end_gate else '❌ FAIL'} "
    "| Pattern END markers"
)

print(
    f"{'✅ PASS' if pattern_tx_gate else '❌ FAIL'} "
    "| Pattern transaction lines"
)


# --------------------------------------------------------------------------------------------------
# 6. FINAL GLOBAL RESULT
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("6. FINAL GLOBAL VALIDATION")
print("=" * 80)


gates = {

    "Final transactions exact":
        transaction_gate,

    "Final accounts exact":
        account_gate,

    "Original IBM Patterns structure":
        original_pattern_gate,

    "Final Pattern ID lines":
        pattern_id_gate,

    "Final Pattern BEGIN markers":
        pattern_begin_gate,

    "Final Pattern END markers":
        pattern_end_gate,

    "Final Pattern transaction lines":
        pattern_tx_gate,
}


all_pass = True


for name, passed in gates.items():

    print(
        f"{'✅ PASS' if passed else '❌ FAIL'} "
        f"| {name}"
    )

    all_pass &= passed


# --------------------------------------------------------------------------------------------------
# 7. CREATE FINAL MANIFEST
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("7. FINAL MANIFEST")
print("=" * 80)


manifest_data = {

    "dataset":
        "IBM HI-Small + pattern-aware synthetic laundering data",

    "status":
        "VALIDATED" if all_pass else "VALIDATION_FAILED",

    "transactions": {

        "original":
            5_078_345,

        "synthetic":
            5_067_991,

        "final":
            final_transaction_rows,
    },

    "accounts": {

        "original":
            518_581,

        "synthetic":
            486_372,

        "final":
            final_account_rows,
    },

    "patterns": {

        "original": {

            "episodes":
                original_begin,

            "id_lines":
                original_pattern_ids,

            "transaction_lines":
                original_tx,
        },

        "synthetic": {

            "episodes":
                SYNTH_PATTERN_EPISODES,

            "id_lines":
                SYNTH_PATTERN_EPISODES,

            "transaction_lines":
                SYNTH_PATTERN_TX,
        },

        "final": {

            "episodes":
                final_pattern_begin,

            "id_lines":
                final_pattern_ids,

            "begin_markers":
                final_pattern_begin,

            "end_markers":
                final_pattern_end,

            "transaction_lines":
                final_pattern_tx,
        },
    },

    "important_note":
        (
            "The original IBM HI-Small Patterns.txt contains "
            "370 BEGIN/END laundering episodes but 0 id=\"...\" "
            "lines. Therefore final ID-line count is 584,706, "
            "while final episode count is 585,076."
        ),

    "files": {

        "transactions":
            FINAL_TRANS,

        "accounts":
            FINAL_ACCOUNTS,

        "patterns":
            FINAL_PATTERNS,
    },

    "file_sizes_mb": {

        "transactions":
            round(mb(FINAL_TRANS), 2),

        "accounts":
            round(mb(FINAL_ACCOUNTS), 2),

        "patterns":
            round(mb(FINAL_PATTERNS), 2),
    },

    "validation_gates":
        gates,
}


with open(
    MANIFEST,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        manifest_data,
        f,
        indent=2
    )


print(
    f"Manifest created:\n{MANIFEST}"
)


# --------------------------------------------------------------------------------------------------
# 8. DOWNLOAD LINKS
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("8. DOWNLOAD FINAL FILES")
print("=" * 80)


print(
    "\n⬇️ 1. FINAL TRANSACTIONS — 10,146,336 rows"
)

display(
    FileLink(FINAL_TRANS)
)


print(
    "\n⬇️ 2. FINAL ACCOUNTS — 1,004,953 rows"
)

display(
    FileLink(FINAL_ACCOUNTS)
)


print(
    "\n⬇️ 3. FINAL PATTERNS — 585,076 episodes"
)

display(
    FileLink(FINAL_PATTERNS)
)


print("\n" + "=" * 100)


if all_pass:

    print(
        "✅✅✅ FINAL DATASET PACKAGE VALIDATED ✅✅✅"
    )

    print("=" * 100)

    print(
        "Transactions : 10,146,336"
    )

    print(
        "Accounts     : 1,004,953"
    )

    print(
        "Pattern eps. : 585,076"
    )

    print(
        "Pattern IDs  : 584,706"
    )

    print(
        "Pattern TX   : 5,071,200"
    )

    print(
        "\nAll three final files are ready for download."
    )

else:

    print(
        "❌ FINAL VALIDATION FAILED"
    )

print("=" * 100)

====================================================================================================
FINAL HI-SMALL MERGED DATASET VALIDATION
====================================================================================================

================================================================================
1. FINAL FILE EXISTENCE
================================================================================
✅ FINAL TRANSACTIONS   | 1,409.24 MB | HI-Small_FINAL_transactions_10146336.csv
✅ FINAL ACCOUNTS       | 60.82 MB | HI-Small_FINAL_accounts_1004953.csv
✅ FINAL PATTERNS       | 571.07 MB | HI-Small_FINAL_Patterns.txt

================================================================================
2. ORIGINAL IBM PATTERNS STRUCTURE
================================================================================
Original ID lines       : 0
Original BEGIN markers  : 370
Original END markers    : 370
Original TX lines       : 3,209

✅ Original IBM pattern structure PASS

================================================================================
3. FINAL TRANSACTION FILE
================================================================================
Final transaction rows : 10,146,336
Expected                : 10,146,336
✅ PASS

================================================================================
4. FINAL ACCOUNT FILE
================================================================================
Final account rows : 1,004,953
Expected           : 1,004,953
✅ PASS

================================================================================
5. FINAL PATTERNS FILE
================================================================================
Final ID lines       : 584,706
Final BEGIN markers  : 585,076
Final END markers    : 585,076
Final TX lines       : 5,071,200

Expected ID lines    : 584,706
Expected BEGIN/END   : 585,076
Expected TX lines    : 5,071,200

✅ PASS | Pattern ID lines
✅ PASS | Pattern BEGIN markers
✅ PASS | Pattern END markers
✅ PASS | Pattern transaction lines

================================================================================
6. FINAL GLOBAL VALIDATION
================================================================================
✅ PASS | Final transactions exact
✅ PASS | Final accounts exact
✅ PASS | Original IBM Patterns structure
✅ PASS | Final Pattern ID lines
✅ PASS | Final Pattern BEGIN markers
✅ PASS | Final Pattern END markers
✅ PASS | Final Pattern transaction lines

================================================================================
7. FINAL MANIFEST
================================================================================
Manifest created:
/kaggle/working/AML_GNN_ONLY/data/HI-Small_FINAL_manifest.json

================================================================================
8. DOWNLOAD FINAL FILES
================================================================================

⬇️ 1. FINAL TRANSACTIONS — 10,146,336 rows

/kaggle/working/AML_GNN_ONLY/data/HI-Small_FINAL_transactions_10146336.csv

⬇️ 2. FINAL ACCOUNTS — 1,004,953 rows

/kaggle/working/AML_GNN_ONLY/data/HI-Small_FINAL_accounts_1004953.csv

⬇️ 3. FINAL PATTERNS — 585,076 episodes

/kaggle/working/AML_GNN_ONLY/data/HI-Small_FINAL_Patterns.txt

====================================================================================================
✅✅✅ FINAL DATASET PACKAGE VALIDATED ✅✅✅
====================================================================================================
Transactions : 10,146,336
Accounts     : 1,004,953
Pattern eps. : 585,076
Pattern IDs  : 584,706
Pattern TX   : 5,071,200

All three final files are ready for download.
====================================================================================================

In [37]:
# ==================================================================================================
# CELL 22 — CORRECTED BEHAVIORAL DNA AUDIT
# Synthetic laundering vs ORIGINAL HI-Small behavior
#
# DOES NOT modify or regenerate any dataset.
# ==================================================================================================

import os
import csv
import json
import math
import random
from collections import Counter
from datetime import datetime


# --------------------------------------------------------------------------------------------------
# PATHS
# --------------------------------------------------------------------------------------------------

BASE = "/kaggle/working/AML_GNN_ONLY/data"

SYN_FILE = os.path.join(
    BASE,
    "HI-Small_SYNTH_FULL_transactions.csv"
)

ORIGINAL_FILE = (
    "/kaggle/input/datasets/"
    "ealtman2019/ibm-transactions-for-anti-money-laundering-aml/"
    "HI-Small_Trans.csv"
)

OUT_JSON = os.path.join(
    BASE,
    "HI-Small_SYNTH_vs_ORIGINAL_behavioral_dna_audit.json"
)

OUT_CSV = os.path.join(
    BASE,
    "HI-Small_SYNTH_vs_ORIGINAL_behavioral_dna_summary.csv"
)

SAMPLE_SIZE = 200_000
random.seed(42)


# --------------------------------------------------------------------------------------------------
# HELPERS
# --------------------------------------------------------------------------------------------------

def canonical_bank(x):
    s = str(x).strip()
    if not s:
        return None
    if s.isdigit():
        return str(int(s))
    return s.upper()


def pct(x, total):
    return 100.0 * x / total if total else 0.0


def quantile(values, q):
    if not values:
        return None
    values = sorted(values)
    idx = int(q * (len(values) - 1))
    return values[idx]


def distribution(counter, total):
    return {
        str(k): {
            "count": int(v),
            "pct": pct(v, total)
        }
        for k, v in counter.items()
    }


def new_stats():
    return {
        "rows": 0,
        "min_timestamp": None,
        "max_timestamp": None,
        "hour": Counter(),
        "day_of_week": Counter(),
        "date": Counter(),
        "payment_format": Counter(),
        "payment_currency": Counter(),
        "receiving_currency": Counter(),
        "source_bank": Counter(),
        "destination_bank": Counter(),
        "source_account": Counter(),
        "destination_account": Counter(),
        "amount_sample": [],
    }


# --------------------------------------------------------------------------------------------------
# STREAM ORIGINAL — POSITIONAL BECAUSE IBM HAS TWO "Account" COLUMNS
# --------------------------------------------------------------------------------------------------

def stream_original(path):

    stats = new_stats()

    with open(
        path,
        "r",
        newline="",
        encoding="utf-8-sig"
    ) as f:

        reader = csv.reader(f)
        header = next(reader)

        expected_header = [
            "Timestamp",
            "From Bank",
            "Account",
            "To Bank",
            "Account",
            "Amount Received",
            "Receiving Currency",
            "Amount Paid",
            "Payment Currency",
            "Payment Format",
            "Is Laundering"
        ]

        if header != expected_header:
            raise RuntimeError(
                "Unexpected original HI-Small header:\n"
                f"{header}"
            )

        for row in reader:

            if len(row) != 11:
                continue

            stats["rows"] += 1

            ts = row[0].strip()

            try:
                dt = datetime.strptime(
                    ts,
                    "%Y-%m-%d %H:%M:%S"
                )
            except Exception:
                try:
                    dt = datetime.strptime(
                        ts,
                        "%Y/%m/%d %H:%M"
                    )
                except Exception:
                    dt = None

            if dt is not None:

                if stats["min_timestamp"] is None or dt < stats["min_timestamp"]:
                    stats["min_timestamp"] = dt

                if stats["max_timestamp"] is None or dt > stats["max_timestamp"]:
                    stats["max_timestamp"] = dt

                stats["hour"][dt.hour] += 1
                stats["day_of_week"][dt.strftime("%A")] += 1
                stats["date"][dt.strftime("%Y-%m-%d")] += 1

            stats["payment_format"][row[9].strip()] += 1
            stats["payment_currency"][row[8].strip()] += 1
            stats["receiving_currency"][row[6].strip()] += 1

            src_bank = canonical_bank(row[1])
            dst_bank = canonical_bank(row[3])

            src_account = row[2].strip()
            dst_account = row[4].strip()

            stats["source_bank"][src_bank] += 1
            stats["destination_bank"][dst_bank] += 1

            stats["source_account"][src_account] += 1
            stats["destination_account"][dst_account] += 1

            try:
                amount = float(row[5])

                if math.isfinite(amount) and amount > 0:

                    n = len(stats["amount_sample"])

                    if n < SAMPLE_SIZE:

                        stats["amount_sample"].append(amount)

                    else:

                        j = random.randint(
                            0,
                            stats["rows"] - 1
                        )

                        if j < SAMPLE_SIZE:
                            stats["amount_sample"][j] = amount

            except Exception:
                pass

    return stats


# --------------------------------------------------------------------------------------------------
# STREAM SYNTHETIC
# --------------------------------------------------------------------------------------------------

def stream_synthetic(path):

    stats = new_stats()

    with open(
        path,
        "r",
        newline="",
        encoding="utf-8"
    ) as f:

        reader = csv.DictReader(f)

        required = [
            "Timestamp",
            "From Bank",
            "Account",
            "To Bank",
            "Account.1",
            "Amount Received",
            "Receiving Currency",
            "Payment Currency",
            "Payment Format",
        ]

        missing = [
            c for c in required
            if c not in reader.fieldnames
        ]

        if missing:
            raise RuntimeError(
                "Synthetic file missing columns:\n"
                + str(missing)
            )

        for row in reader:

            stats["rows"] += 1

            ts = row["Timestamp"].strip()

            try:
                dt = datetime.strptime(
                    ts,
                    "%Y-%m-%d %H:%M:%S"
                )
            except Exception:
                try:
                    dt = datetime.strptime(
                        ts,
                        "%Y/%m/%d %H:%M"
                    )
                except Exception:
                    dt = None

            if dt is not None:

                if stats["min_timestamp"] is None or dt < stats["min_timestamp"]:
                    stats["min_timestamp"] = dt

                if stats["max_timestamp"] is None or dt > stats["max_timestamp"]:
                    stats["max_timestamp"] = dt

                stats["hour"][dt.hour] += 1
                stats["day_of_week"][dt.strftime("%A")] += 1
                stats["date"][dt.strftime("%Y-%m-%d")] += 1

            stats["payment_format"][
                row["Payment Format"].strip()
            ] += 1

            stats["payment_currency"][
                row["Payment Currency"].strip()
            ] += 1

            stats["receiving_currency"][
                row["Receiving Currency"].strip()
            ] += 1

            src_bank = canonical_bank(
                row["From Bank"]
            )

            dst_bank = canonical_bank(
                row["To Bank"]
            )

            stats["source_bank"][src_bank] += 1
            stats["destination_bank"][dst_bank] += 1

            stats["source_account"][
                row["Account"].strip()
            ] += 1

            stats["destination_account"][
                row["Account.1"].strip()
            ] += 1

            try:
                amount = float(
                    row["Amount Received"]
                )

                if math.isfinite(amount) and amount > 0:

                    n = len(
                        stats["amount_sample"]
                    )

                    if n < SAMPLE_SIZE:

                        stats["amount_sample"].append(
                            amount
                        )

                    else:

                        j = random.randint(
                            0,
                            stats["rows"] - 1
                        )

                        if j < SAMPLE_SIZE:
                            stats["amount_sample"][j] = amount

            except Exception:
                pass

    return stats


# --------------------------------------------------------------------------------------------------
# RUN
# --------------------------------------------------------------------------------------------------

print("=" * 100)
print("CELL 22 — CORRECTED BEHAVIORAL DNA AUDIT")
print("=" * 100)

print("\n1. Streaming ORIGINAL HI-Small...")
original = stream_original(ORIGINAL_FILE)

print(
    f"Original rows     : {original['rows']:,}"
)

print(
    f"Original range    : "
    f"{original['min_timestamp']} -> "
    f"{original['max_timestamp']}"
)

print("\n2. Streaming SYNTHETIC laundering data...")
synthetic = stream_synthetic(SYN_FILE)

print(
    f"Synthetic rows    : {synthetic['rows']:,}"
)

print(
    f"Synthetic range   : "
    f"{synthetic['min_timestamp']} -> "
    f"{synthetic['max_timestamp']}"
)


# --------------------------------------------------------------------------------------------------
# TIMESTAMP
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("3. TIMESTAMP COVERAGE")
print("=" * 80)

original_dates = set(original["date"])
synthetic_dates = set(synthetic["date"])

missing_dates = original_dates - synthetic_dates

print(
    f"Original active dates : {len(original_dates)}"
)

print(
    f"Synthetic active dates: {len(synthetic_dates)}"
)

print(
    f"Missing synthetic dates: {len(missing_dates)}"
)

if missing_dates:
    print("\nMissing dates:")
    for d in sorted(missing_dates):
        print(" ", d)


# --------------------------------------------------------------------------------------------------
# HOUR
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("4. HOUR DISTRIBUTION")
print("=" * 80)

hour_diffs = []

for h in range(24):

    op = pct(
        original["hour"].get(h, 0),
        original["rows"]
    )

    sp = pct(
        synthetic["hour"].get(h, 0),
        synthetic["rows"]
    )

    diff = abs(op - sp)
    hour_diffs.append(diff)

    print(
        f"{h:02d}:00 "
        f"| Original={op:8.4f}% "
        f"| Synthetic={sp:8.4f}% "
        f"| AbsDiff={diff:8.4f}"
    )

hour_mae = sum(hour_diffs) / len(hour_diffs)

print(
    f"\nHour MAE = {hour_mae:.6f} percentage points"
)


# --------------------------------------------------------------------------------------------------
# DAY OF WEEK
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("5. DAY-OF-WEEK DISTRIBUTION")
print("=" * 80)

days = [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday"
]

dow_diffs = []

for d in days:

    op = pct(
        original["day_of_week"].get(d, 0),
        original["rows"]
    )

    sp = pct(
        synthetic["day_of_week"].get(d, 0),
        synthetic["rows"]
    )

    diff = abs(op - sp)
    dow_diffs.append(diff)

    print(
        f"{d:10s} "
        f"| Original={op:8.4f}% "
        f"| Synthetic={sp:8.4f}% "
        f"| AbsDiff={diff:8.4f}"
    )

dow_mae = sum(dow_diffs) / len(dow_diffs)

print(
    f"\nDay-of-week MAE = "
    f"{dow_mae:.6f} percentage points"
)


# --------------------------------------------------------------------------------------------------
# PAYMENT FORMAT
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("6. PAYMENT FORMAT")
print("=" * 80)

formats = sorted(
    set(original["payment_format"])
    | set(synthetic["payment_format"])
)

format_diffs = []

for fmt in formats:

    op = pct(
        original["payment_format"].get(fmt, 0),
        original["rows"]
    )

    sp = pct(
        synthetic["payment_format"].get(fmt, 0),
        synthetic["rows"]
    )

    diff = abs(op - sp)
    format_diffs.append(diff)

    print(
        f"{fmt:18s} "
        f"| Original={op:8.4f}% "
        f"| Synthetic={sp:8.4f}% "
        f"| AbsDiff={diff:8.4f}"
    )

format_mae = sum(format_diffs) / len(format_diffs)

print(
    f"\nPayment-format MAE = "
    f"{format_mae:.6f} percentage points"
)


# --------------------------------------------------------------------------------------------------
# PAYMENT CURRENCY
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("7. PAYMENT CURRENCY")
print("=" * 80)

payment_currencies = sorted(
    set(original["payment_currency"])
    | set(synthetic["payment_currency"])
)

payment_currency_diffs = []

for curr in payment_currencies:

    op = pct(
        original["payment_currency"].get(curr, 0),
        original["rows"]
    )

    sp = pct(
        synthetic["payment_currency"].get(curr, 0),
        synthetic["rows"]
    )

    diff = abs(op - sp)
    payment_currency_diffs.append(diff)

    print(
        f"{curr:20s} "
        f"| Original={op:8.4f}% "
        f"| Synthetic={sp:8.4f}% "
        f"| AbsDiff={diff:8.4f}"
    )

payment_currency_mae = (
    sum(payment_currency_diffs)
    / len(payment_currency_diffs)
)

print(
    f"\nPayment-currency MAE = "
    f"{payment_currency_mae:.6f} percentage points"
)


# --------------------------------------------------------------------------------------------------
# RECEIVING CURRENCY
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("8. RECEIVING CURRENCY")
print("=" * 80)

receiving_currencies = sorted(
    set(original["receiving_currency"])
    | set(synthetic["receiving_currency"])
)

receiving_currency_diffs = []

for curr in receiving_currencies:

    op = pct(
        original["receiving_currency"].get(curr, 0),
        original["rows"]
    )

    sp = pct(
        synthetic["receiving_currency"].get(curr, 0),
        synthetic["rows"]
    )

    diff = abs(op - sp)
    receiving_currency_diffs.append(diff)

    print(
        f"{curr:20s} "
        f"| Original={op:8.4f}% "
        f"| Synthetic={sp:8.4f}% "
        f"| AbsDiff={diff:8.4f}"
    )

receiving_currency_mae = (
    sum(receiving_currency_diffs)
    / len(receiving_currency_diffs)
)

print(
    f"\nReceiving-currency MAE = "
    f"{receiving_currency_mae:.6f} percentage points"
)


# --------------------------------------------------------------------------------------------------
# AMOUNTS
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("9. AMOUNT DISTRIBUTION")
print("=" * 80)

quantile_points = [
    0.01,
    0.05,
    0.10,
    0.25,
    0.50,
    0.75,
    0.90,
    0.95,
    0.99,
]

print(
    f"{'Quantile':>10} "
    f"{'Original':>20} "
    f"{'Synthetic':>20} "
    f"{'Ratio':>12}"
)

amount_ratios = []

for q in quantile_points:

    ov = quantile(
        original["amount_sample"],
        q
    )

    sv = quantile(
        synthetic["amount_sample"],
        q
    )

    ratio = (
        sv / ov
        if ov is not None
        and ov != 0
        else None
    )

    if ratio is not None:
        amount_ratios.append(ratio)

    print(
        f"p{int(q*100):02d} "
        f"{ov:20.6f} "
        f"{sv:20.6f} "
        f"{ratio:12.4f}"
    )


# --------------------------------------------------------------------------------------------------
# BANK COVERAGE
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("10. BANK / ACCOUNT COVERAGE")
print("=" * 80)

original_source_banks = set(
    original["source_bank"]
)

synthetic_source_banks = set(
    synthetic["source_bank"]
)

original_dest_banks = set(
    original["destination_bank"]
)

synthetic_dest_banks = set(
    synthetic["destination_bank"]
)

print(
    f"Unique source banks:"
)

print(
    f"  Original : {len(original_source_banks):,}"
)

print(
    f"  Synthetic: {len(synthetic_source_banks):,}"
)

print(
    f"  Synthetic covers "
    f"{pct(len(synthetic_source_banks.intersection(original_source_banks)), len(original_source_banks)):.4f}% "
    f"of original source banks"
)


print(
    f"\nUnique destination banks:"
)

print(
    f"  Original : {len(original_dest_banks):,}"
)

print(
    f"  Synthetic: {len(synthetic_dest_banks):,}"
)

print(
    f"  Synthetic covers "
    f"{pct(len(synthetic_dest_banks.intersection(original_dest_banks)), len(original_dest_banks)):.4f}% "
    f"of original destination banks"
)


print(
    f"\nUnique source accounts:"
)

print(
    f"  Original : {len(original['source_account']):,}"
)

print(
    f"  Synthetic: {len(synthetic['source_account']):,}"
)


print(
    f"\nUnique destination accounts:"
)

print(
    f"  Original : {len(original['destination_account']):,}"
)

print(
    f"  Synthetic: {len(synthetic['destination_account']):,}"
)


# --------------------------------------------------------------------------------------------------
# BANK CONCENTRATION
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("11. BANK CONCENTRATION")
print("=" * 80)


def top_share(counter, total, k):
    return (
        100.0 * sum(
            v
            for _, v in counter.most_common(k)
        ) / total
        if total
        else 0.0
    )


print("\nSource-bank concentration:")

for k in [1, 5, 10, 25, 50, 100]:

    o = top_share(
        original["source_bank"],
        original["rows"],
        k
    )

    s = top_share(
        synthetic["source_bank"],
        synthetic["rows"],
        k
    )

    print(
        f"Top {k:3d} "
        f"| Original={o:10.4f}% "
        f"| Synthetic={s:10.4f}%"
    )


print("\nDestination-bank concentration:")

for k in [1, 5, 10, 25, 50, 100]:

    o = top_share(
        original["destination_bank"],
        original["rows"],
        k
    )

    s = top_share(
        synthetic["destination_bank"],
        synthetic["rows"],
        k
    )

    print(
        f"Top {k:3d} "
        f"| Original={o:10.4f}% "
        f"| Synthetic={s:10.4f}%"
    )


# --------------------------------------------------------------------------------------------------
# ACCOUNT REUSE
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("12. ACCOUNT REUSE")
print("=" * 80)


def activity_stats(counter):

    values = list(
        counter.values()
    )

    if not values:
        return {}

    values.sort()

    n = len(values)

    def q(p):
        return values[
            int(
                p * (n - 1)
            )
        ]

    buckets = Counter()

    for v in values:

        if v == 1:
            buckets["1"] += 1

        elif v == 2:
            buckets["2"] += 1

        elif 3 <= v <= 5:
            buckets["3-5"] += 1

        elif 6 <= v <= 10:
            buckets["6-10"] += 1

        elif 11 <= v <= 25:
            buckets["11-25"] += 1

        elif 26 <= v <= 50:
            buckets["26-50"] += 1

        elif 51 <= v <= 100:
            buckets["51-100"] += 1

        elif 101 <= v <= 250:
            buckets["101-250"] += 1

        elif 251 <= v <= 500:
            buckets["251-500"] += 1

        elif 501 <= v <= 1000:
            buckets["501-1000"] += 1

        else:
            buckets[">1000"] += 1

    return {
        "min": min(values),
        "p25": q(0.25),
        "median": q(0.50),
        "p75": q(0.75),
        "p90": q(0.90),
        "p95": q(0.95),
        "p99": q(0.99),
        "max": max(values),
        "buckets": buckets,
    }


orig_src_activity = activity_stats(
    original["source_account"]
)

syn_src_activity = activity_stats(
    synthetic["source_account"]
)

orig_dst_activity = activity_stats(
    original["destination_account"]
)

syn_dst_activity = activity_stats(
    synthetic["destination_account"]
)


print("\nSOURCE ACCOUNT ACTIVITY")

for key in [
    "min",
    "p25",
    "median",
    "p75",
    "p90",
    "p95",
    "p99",
    "max"
]:

    print(
        f"{key:8s} "
        f"| Original={orig_src_activity[key]:12} "
        f"| Synthetic={syn_src_activity[key]:12}"
    )


print("\nDESTINATION ACCOUNT ACTIVITY")

for key in [
    "min",
    "p25",
    "median",
    "p75",
    "p90",
    "p95",
    "p99",
    "max"
]:

    print(
        f"{key:8s} "
        f"| Original={orig_dst_activity[key]:12} "
        f"| Synthetic={syn_dst_activity[key]:12}"
    )


# --------------------------------------------------------------------------------------------------
# SAVE AUDIT
# --------------------------------------------------------------------------------------------------

audit = {

    "original_rows":
        original["rows"],

    "synthetic_rows":
        synthetic["rows"],

    "timestamp": {

        "original_min":
            str(original["min_timestamp"]),

        "original_max":
            str(original["max_timestamp"]),

        "synthetic_min":
            str(synthetic["min_timestamp"]),

        "synthetic_max":
            str(synthetic["max_timestamp"]),

        "original_active_dates":
            sorted(original_dates),

        "synthetic_active_dates":
            sorted(synthetic_dates),

        "missing_synthetic_dates":
            sorted(missing_dates),
    },

    "distribution_mae": {

        "hour":
            hour_mae,

        "day_of_week":
            dow_mae,

        "payment_format":
            format_mae,

        "payment_currency":
            payment_currency_mae,

        "receiving_currency":
            receiving_currency_mae,
    },

    "amount_quantiles": {

        "original": {
            f"p{int(q*100):02d}":
                quantile(
                    original["amount_sample"],
                    q
                )
            for q in quantile_points
        },

        "synthetic": {
            f"p{int(q*100):02d}":
                quantile(
                    synthetic["amount_sample"],
                    q
                )
            for q in quantile_points
        },
    },

    "bank_coverage": {

        "original_source_banks":
            len(original_source_banks),

        "synthetic_source_banks":
            len(synthetic_source_banks),

        "original_destination_banks":
            len(original_dest_banks),

        "synthetic_destination_banks":
            len(synthetic_dest_banks),
    },

    "payment_format":

        {
            "original":
                distribution(
                    original["payment_format"],
                    original["rows"]
                ),

            "synthetic":
                distribution(
                    synthetic["payment_format"],
                    synthetic["rows"]
                ),
        },

    "payment_currency":

        {
            "original":
                distribution(
                    original["payment_currency"],
                    original["rows"]
                ),

            "synthetic":
                distribution(
                    synthetic["payment_currency"],
                    synthetic["rows"]
                ),
        },

    "receiving_currency":

        {
            "original":
                distribution(
                    original["receiving_currency"],
                    original["rows"]
                ),

            "synthetic":
                distribution(
                    synthetic["receiving_currency"],
                    synthetic["rows"]
                ),
        },

    "hour_distribution":

        {
            "original":
                distribution(
                    original["hour"],
                    original["rows"]
                ),

            "synthetic":
                distribution(
                    synthetic["hour"],
                    synthetic["rows"]
                ),
        },
}


with open(
    OUT_JSON,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        audit,
        f,
        indent=2
    )


with open(
    OUT_CSV,
    "w",
    newline="",
    encoding="utf-8"
) as f:

    writer = csv.writer(f)

    writer.writerow([
        "metric",
        "value"
    ])

    writer.writerow([
        "original_rows",
        original["rows"]
    ])

    writer.writerow([
        "synthetic_rows",
        synthetic["rows"]
    ])

    writer.writerow([
        "hour_mae_percentage_points",
        hour_mae
    ])

    writer.writerow([
        "day_of_week_mae_percentage_points",
        dow_mae
    ])

    writer.writerow([
        "payment_format_mae_percentage_points",
        format_mae
    ])

    writer.writerow([
        "payment_currency_mae_percentage_points",
        payment_currency_mae
    ])

    writer.writerow([
        "receiving_currency_mae_percentage_points",
        receiving_currency_mae
    ])

    writer.writerow([
        "original_source_banks",
        len(original_source_banks)
    ])

    writer.writerow([
        "synthetic_source_banks",
        len(synthetic_source_banks)
    ])

    writer.writerow([
        "original_destination_banks",
        len(original_dest_banks)
    ])

    writer.writerow([
        "synthetic_destination_banks",
        len(synthetic_dest_banks)
    ])


# --------------------------------------------------------------------------------------------------
# DONE
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("✅ CELL 22 COMPLETE")
print("=" * 100)

print(
    f"Audit JSON: {OUT_JSON}"
)

print(
    f"Audit CSV : {OUT_CSV}"
)

print("=" * 100)

====================================================================================================
CELL 22 — CORRECTED BEHAVIORAL DNA AUDIT
====================================================================================================

1. Streaming ORIGINAL HI-Small...
Original rows     : 5,078,345
Original range    : 2022-09-01 00:00:00 -> 2022-09-18 16:18:00

2. Streaming SYNTHETIC laundering data...
Synthetic rows    : 5,067,991
Synthetic range   : 2022-09-01 00:00:00 -> 2022-09-14 19:51:00

================================================================================
3. TIMESTAMP COVERAGE
================================================================================
Original active dates : 18
Synthetic active dates: 14
Missing synthetic dates: 4

Missing dates:
  2022-09-15
  2022-09-16
  2022-09-17
  2022-09-18

================================================================================
4. HOUR DISTRIBUTION
================================================================================
00:00 | Original= 12.4987% | Synthetic=  4.9561% | AbsDiff=  7.5426
01:00 | Original=  3.8148% | Synthetic=  4.0008% | AbsDiff=  0.1860
02:00 | Original=  3.8033% | Synthetic=  4.0594% | AbsDiff=  0.2562
03:00 | Original=  3.8054% | Synthetic=  4.0574% | AbsDiff=  0.2521
04:00 | Original=  3.8037% | Synthetic=  4.0374% | AbsDiff=  0.2337
05:00 | Original=  3.8182% | Synthetic=  4.0783% | AbsDiff=  0.2602
06:00 | Original=  3.8291% | Synthetic=  4.0222% | AbsDiff=  0.1931
07:00 | Original=  3.8071% | Synthetic=  4.2672% | AbsDiff=  0.4602
08:00 | Original=  3.7989% | Synthetic=  4.0347% | AbsDiff=  0.2358
09:00 | Original=  3.7995% | Synthetic=  4.0461% | AbsDiff=  0.2466
10:00 | Original=  3.8050% | Synthetic=  4.0885% | AbsDiff=  0.2836
11:00 | Original=  3.8103% | Synthetic=  4.1589% | AbsDiff=  0.3486
12:00 | Original=  3.7999% | Synthetic=  4.0524% | AbsDiff=  0.2525
13:00 | Original=  3.7910% | Synthetic=  4.1596% | AbsDiff=  0.3686
14:00 | Original=  3.7963% | Synthetic=  4.2050% | AbsDiff=  0.4087
15:00 | Original=  3.8373% | Synthetic=  4.1896% | AbsDiff=  0.3523
16:00 | Original=  3.8085% | Synthetic=  4.2872% | AbsDiff=  0.4787
17:00 | Original=  3.8035% | Synthetic=  4.0781% | AbsDiff=  0.2746
18:00 | Original=  3.8068% | Synthetic=  4.1034% | AbsDiff=  0.2966
19:00 | Original=  3.7970% | Synthetic=  4.5755% | AbsDiff=  0.7785
20:00 | Original=  3.7967% | Synthetic=  4.1136% | AbsDiff=  0.3169
21:00 | Original=  3.7845% | Synthetic=  4.1465% | AbsDiff=  0.3619
22:00 | Original=  3.7775% | Synthetic=  4.1696% | AbsDiff=  0.3921
23:00 | Original=  3.8072% | Synthetic=  4.1124% | AbsDiff=  0.3051

Hour MAE = 0.628549 percentage points

================================================================================
5. DAY-OF-WEEK DISTRIBUTION
================================================================================
Monday     | Original=  9.5096% | Synthetic= 13.4611% | AbsDiff=  3.9515
Tuesday    | Original=  9.4967% | Synthetic= 10.8091% | AbsDiff=  1.3124
Wednesday  | Original=  9.5085% | Synthetic= 10.1134% | AbsDiff=  0.6050
Thursday   | Original= 31.4618% | Synthetic= 14.1341% | AbsDiff= 17.3278
Friday     | Original= 27.7445% | Synthetic= 17.5878% | AbsDiff= 10.1567
Saturday   | Original=  8.1863% | Synthetic= 17.5648% | AbsDiff=  9.3785
Sunday     | Original=  4.0926% | Synthetic= 16.3297% | AbsDiff= 12.2371

Day-of-week MAE = 7.852707 percentage points

================================================================================
6. PAYMENT FORMAT
================================================================================
ACH                | Original= 11.8306% | Synthetic= 12.1572% | AbsDiff=  0.3266
Bitcoin            | Original=  2.8767% | Synthetic=  2.8912% | AbsDiff=  0.0145
Cash               | Original=  9.6664% | Synthetic=  9.6577% | AbsDiff=  0.0086
Cheque             | Original= 36.7114% | Synthetic= 37.3459% | AbsDiff=  0.6345
Credit Card        | Original= 26.0582% | Synthetic= 25.8681% | AbsDiff=  0.1901
Reinvestment       | Original=  9.4727% | Synthetic=  8.6508% | AbsDiff=  0.8219
Wire               | Original=  3.3841% | Synthetic=  3.4291% | AbsDiff=  0.0450

Payment-format MAE = 0.291619 percentage points

================================================================================
7. PAYMENT CURRENCY
================================================================================
Australian Dollar    | Original=  2.6932% | Synthetic=  2.6706% | AbsDiff=  0.0226
Bitcoin              | Original=  2.8763% | Synthetic=  2.8846% | AbsDiff=  0.0084
Brazil Real          | Original=  1.3922% | Synthetic=  1.4060% | AbsDiff=  0.0138
Canadian Dollar      | Original=  2.7576% | Synthetic=  2.8576% | AbsDiff=  0.1000
Euro                 | Original= 23.0055% | Synthetic= 22.8462% | AbsDiff=  0.1592
Mexican Peso         | Original=  2.1692% | Synthetic=  2.2160% | AbsDiff=  0.0468
Ruble                | Original=  3.0557% | Synthetic=  3.1147% | AbsDiff=  0.0590
Rupee                | Original=  3.7454% | Synthetic=  3.6596% | AbsDiff=  0.0858
Saudi Riyal          | Original=  1.7528% | Synthetic=  1.7868% | AbsDiff=  0.0340
Shekel               | Original=  3.7844% | Synthetic=  3.8684% | AbsDiff=  0.0840
Swiss Franc          | Original=  4.6247% | Synthetic=  4.7016% | AbsDiff=  0.0769
UK Pound             | Original=  3.5590% | Synthetic=  3.6525% | AbsDiff=  0.0935
US Dollar            | Original= 37.3187% | Synthetic= 37.0418% | AbsDiff=  0.2769
Yen                  | Original=  3.0563% | Synthetic=  3.1073% | AbsDiff=  0.0510
Yuan                 | Original=  4.2091% | Synthetic=  4.1864% | AbsDiff=  0.0227

Payment-currency MAE = 0.075632 percentage points

================================================================================
8. RECEIVING CURRENCY
================================================================================
Australian Dollar    | Original=  2.7275% | Synthetic=  2.7104% | AbsDiff=  0.0171
Bitcoin              | Original=  2.9173% | Synthetic=  2.9193% | AbsDiff=  0.0020
Brazil Real          | Original=  1.4088% | Synthetic=  1.4202% | AbsDiff=  0.0114
Canadian Dollar      | Original=  2.7835% | Synthetic=  2.8727% | AbsDiff=  0.0892
Euro                 | Original= 23.0787% | Synthetic= 22.9225% | AbsDiff=  0.1562
Mexican Peso         | Original=  2.1863% | Synthetic=  2.2411% | AbsDiff=  0.0548
Ruble                | Original=  3.0987% | Synthetic=  3.1500% | AbsDiff=  0.0513
Rupee                | Original=  3.7820% | Synthetic=  3.7074% | AbsDiff=  0.0747
Saudi Riyal          | Original=  1.7717% | Synthetic=  1.8115% | AbsDiff=  0.0398
Shekel               | Original=  3.8396% | Synthetic=  3.9124% | AbsDiff=  0.0728
Swiss Franc          | Original=  4.6843% | Synthetic=  4.7709% | AbsDiff=  0.0866
UK Pound             | Original=  3.5692% | Synthetic=  3.6437% | AbsDiff=  0.0745
US Dollar            | Original= 37.0070% | Synthetic= 36.7676% | AbsDiff=  0.2393
Yen                  | Original=  3.0781% | Synthetic=  3.1191% | AbsDiff=  0.0409
Yuan                 | Original=  4.0673% | Synthetic=  4.0312% | AbsDiff=  0.0361

Receiving-currency MAE = 0.069789 percentage points

================================================================================
9. AMOUNT DISTRIBUTION
================================================================================
  Quantile             Original            Synthetic        Ratio
p01             0.019137             0.014478       0.7565
p05             7.110000             3.338515       0.4696
p10            25.460000            17.176505       0.6746
p25           181.160000           152.347208       0.8410
p50          1398.250000          1500.304346       1.0730
p75         12256.830000         17889.113952       1.4595
p90        139040.770000        274804.698703       1.9764
p95        637351.360000       1539643.676274       2.4157
p99      13958058.200000      61425026.907555       4.4007

================================================================================
10. BANK / ACCOUNT COVERAGE
================================================================================
Unique source banks:
  Original : 30,470
  Synthetic: 1,064
  Synthetic covers 3.4920% of original source banks

Unique destination banks:
  Original : 15,811
  Synthetic: 1,223
  Synthetic covers 7.7351% of original destination banks

Unique source accounts:
  Original : 496,995
  Synthetic: 682,923

Unique destination accounts:
  Original : 420,636
  Synthetic: 542,095

================================================================================
11. BANK CONCENTRATION
================================================================================

Source-bank concentration:
Top   1 | Original=    8.8584% | Synthetic=    5.4621%
Top   5 | Original=   14.2953% | Synthetic=   12.8769%
Top  10 | Original=   18.1031% | Synthetic=   16.9372%
Top  25 | Original=   25.6187% | Synthetic=   26.1294%
Top  50 | Original=   33.9523% | Synthetic=   38.3516%
Top 100 | Original=   45.0857% | Synthetic=   56.0272%

Destination-bank concentration:
Top   1 | Original=    0.8378% | Synthetic=    2.4429%
Top   5 | Original=    3.6209% | Synthetic=    7.3716%
Top  10 | Original=    5.8350% | Synthetic=   10.6323%
Top  25 | Original=   10.3415% | Synthetic=   18.2232%
Top  50 | Original=   15.6705% | Synthetic=   28.6861%
Top 100 | Original=   24.0707% | Synthetic=   44.9651%

================================================================================
12. ACCOUNT REUSE
================================================================================

SOURCE ACCOUNT ACTIVITY
min      | Original=           1 | Synthetic=           1
p25      | Original=           1 | Synthetic=           1
median   | Original=           2 | Synthetic=           1
p75      | Original=           5 | Synthetic=           8
p90      | Original=          29 | Synthetic=          26
p95      | Original=          46 | Synthetic=          34
p99      | Original=          92 | Synthetic=          48
max      | Original=      168672 | Synthetic=         330

DESTINATION ACCOUNT ACTIVITY
min      | Original=           1 | Synthetic=           1
p25      | Original=           1 | Synthetic=           1
median   | Original=           4 | Synthetic=           4
p75      | Original=          22 | Synthetic=          15
p90      | Original=          31 | Synthetic=          26
p95      | Original=          37 | Synthetic=          33
p99      | Original=          51 | Synthetic=          46
max      | Original=        1084 | Synthetic=         104

====================================================================================================
✅ CELL 22 COMPLETE
====================================================================================================
Audit JSON: /kaggle/working/AML_GNN_ONLY/data/HI-Small_SYNTH_vs_ORIGINAL_behavioral_dna_audit.json
Audit CSV : /kaggle/working/AML_GNN_ONLY/data/HI-Small_SYNTH_vs_ORIGINAL_behavioral_dna_summary.csv
====================================================================================================

In [39]:
# ==================================================================================================
# CELL 23 — FULL-SCALE PATTERN MORPHOLOGY AUDIT
#
# PURPOSE:
#   Verify that every synthetic laundering episode preserves the structural morphology
#   of its assigned IBM template.
#
# Checks:
#   1. Episode continuity
#   2. Typology consistency
#   3. Source-template consistency
#   4. Transaction count consistency
#   5. Unique node count
#   6. Unique edge count
#   7. Max in-degree / out-degree
#   8. Exact node degree signature
#   9. Template source-order preservation
#  10. Relative timestamp structure preservation
#
# IMPORTANT:
#   - DOES NOT modify any file
#   - DOES NOT regenerate data
#   - DOES NOT train the GNN
# ==================================================================================================

import os
import csv
import json
from collections import defaultdict, Counter


# --------------------------------------------------------------------------------------------------
# PATHS
# --------------------------------------------------------------------------------------------------

BASE = "/kaggle/working/AML_GNN_ONLY/data"

SYN_FILE = os.path.join(
    BASE,
    "HI-Small_SYNTH_FULL_transactions.csv"
)

EPISODE_AUDIT_FILE = os.path.join(
    BASE,
    "HI-Small_SYNTH_FULL_episode_audit.csv"
)

TEMPLATE_FILE = os.path.join(
    BASE,
    "HI-Small_pattern_templates.json"
)

OUT_JSON = os.path.join(
    BASE,
    "HI-Small_SYNTH_full_morphology_audit.json"
)

OUT_CSV = os.path.join(
    BASE,
    "HI-Small_SYNTH_full_morphology_summary.csv"
)

EXPECTED_EPISODES = 584_706
EXPECTED_TX = 5_067_991


# --------------------------------------------------------------------------------------------------
# HELPERS
# --------------------------------------------------------------------------------------------------

def parse_timestamp(ts):
    ts = str(ts).strip()

    try:
        from datetime import datetime

        return datetime.strptime(
            ts,
            "%Y-%m-%d %H:%M:%S"
        )

    except Exception:

        from datetime import datetime

        return datetime.strptime(
            ts,
            "%Y/%m/%d %H:%M"
        )


def canonical_node(bank, account):
    return (
        str(bank).strip()
        + "|"
        + str(account).strip()
    )


def freeze_degree_signature(in_deg, out_deg):
    """
    Exact unlabeled directed degree signature.

    Each node represented as:
        (in_degree, out_degree)

    Sorted so node IDs do not affect the signature.
    """

    return tuple(
        sorted(
            (
                int(in_deg.get(node, 0)),
                int(out_deg.get(node, 0))
            )
            for node in set(in_deg) | set(out_deg)
        )
    )


def finish_episode(
    state,
    template_reference,
    results
):
    """
    Finalize one episode and compare with its template reference.
    """

    if state is None:
        return

    episode_id = state["episode_id"]
    template_id = state["template_id"]
    typology = state["typology"]

    tx_count = state["tx_count"]

    nodes = state["nodes"]

    unique_edges = state["edges"]

    in_deg = state["in_deg"]
    out_deg = state["out_deg"]

    degree_signature = freeze_degree_signature(
        in_deg,
        out_deg
    )

    max_in = (
        max(in_deg.values())
        if in_deg
        else 0
    )

    max_out = (
        max(out_deg.values())
        if out_deg
        else 0
    )

    source_nodes = sum(
        1
        for node in nodes
        if (
            in_deg.get(node, 0) == 0
            and out_deg.get(node, 0) > 0
        )
    )

    destination_nodes = sum(
        1
        for node in nodes
        if (
            out_deg.get(node, 0) == 0
            and in_deg.get(node, 0) > 0
        )
    )

    intermediate_nodes = sum(
        1
        for node in nodes
        if (
            in_deg.get(node, 0) > 0
            and out_deg.get(node, 0) > 0
        )
    )

    # ----------------------------------------------------------------------------------------------
    # Relative timestamp sequence
    # ----------------------------------------------------------------------------------------------

    timestamps = state["timestamps"]

    if timestamps:

        t0 = min(timestamps)

        relative_minutes = tuple(
            int(
                (t - t0).total_seconds() // 60
            )
            for t in timestamps
        )

        relative_minutes_sorted = tuple(
            sorted(relative_minutes)
        )

    else:

        relative_minutes = tuple()
        relative_minutes_sorted = tuple()


    current_signature = {
        "typology": typology,
        "tx_count": tx_count,
        "node_count": len(nodes),
        "edge_count": len(unique_edges),
        "max_in_degree": max_in,
        "max_out_degree": max_out,
        "source_nodes": source_nodes,
        "destination_nodes": destination_nodes,
        "intermediate_nodes": intermediate_nodes,
        "degree_signature": degree_signature,
        "relative_minutes_sorted":
            relative_minutes_sorted,
    }


    results["episodes"] += 1
    results["transactions"] += tx_count

    results["typology_episodes"][
        typology
    ] += 1

    results["typology_transactions"][
        typology
    ] += tx_count


    # ----------------------------------------------------------------------------------------------
    # Reference template comparison
    # ----------------------------------------------------------------------------------------------

    if template_id not in template_reference:

        template_reference[
            template_id
        ] = {

            **current_signature,

            "_first_episode":
                episode_id
        }

        results[
            "new_template_ids"
        ].add(
            template_id
        )

        results[
            "template_typology"
        ][template_id] = typology

        results[
            "template_counts"
        ][template_id] += 1

        return


    ref = template_reference[
        template_id
    ]

    results[
        "template_counts"
    ][template_id] += 1


    # ----------------------------------------------------------------------------------------------
    # Typology consistency
    # ----------------------------------------------------------------------------------------------

    if typology != ref["typology"]:

        results[
            "typology_mismatches"
        ] += 1


    # ----------------------------------------------------------------------------------------------
    # Transaction count
    # ----------------------------------------------------------------------------------------------

    if tx_count != ref["tx_count"]:

        results[
            "transaction_count_mismatches"
        ] += 1


    # ----------------------------------------------------------------------------------------------
    # Node count
    # ----------------------------------------------------------------------------------------------

    if (
        len(nodes)
        != ref["node_count"]
    ):

        results[
            "node_count_mismatches"
        ] += 1


    # ----------------------------------------------------------------------------------------------
    # Edge count
    # ----------------------------------------------------------------------------------------------

    if (
        len(unique_edges)
        != ref["edge_count"]
    ):

        results[
            "edge_count_mismatches"
        ] += 1


    # ----------------------------------------------------------------------------------------------
    # Degree structure
    # ----------------------------------------------------------------------------------------------

    if (
        degree_signature
        != ref["degree_signature"]
    ):

        results[
            "degree_signature_mismatches"
        ] += 1


    # ----------------------------------------------------------------------------------------------
    # Max in/out degree
    # ----------------------------------------------------------------------------------------------

    if (
        max_in
        != ref["max_in_degree"]
    ):

        results[
            "max_in_degree_mismatches"
        ] += 1


    if (
        max_out
        != ref["max_out_degree"]
    ):

        results[
            "max_out_degree_mismatches"
        ] += 1


    # ----------------------------------------------------------------------------------------------
    # Role counts
    # ----------------------------------------------------------------------------------------------

    if (
        source_nodes
        != ref["source_nodes"]
    ):

        results[
            "source_node_mismatches"
        ] += 1


    if (
        destination_nodes
        != ref["destination_nodes"]
    ):

        results[
            "destination_node_mismatches"
        ] += 1


    if (
        intermediate_nodes
        != ref["intermediate_nodes"]
    ):

        results[
            "intermediate_node_mismatches"
        ] += 1


    # ----------------------------------------------------------------------------------------------
    # Relative timestamp structure
    # ----------------------------------------------------------------------------------------------

    if (
        relative_minutes_sorted
        != ref["relative_minutes_sorted"]
    ):

        results[
            "timestamp_structure_mismatches"
        ] += 1


    # ----------------------------------------------------------------------------------------------
    # Source-order consistency
    # ----------------------------------------------------------------------------------------------

    source_order = state[
        "source_orders"
    ]

    if source_order:

        expected_order = tuple(
            range(
                len(source_order)
            )
        )

        if source_order != expected_order:

            results[
                "source_order_mismatches"
            ] += 1


# --------------------------------------------------------------------------------------------------
# INITIALIZE
# --------------------------------------------------------------------------------------------------

print("=" * 100)
print("CELL 23 — FULL-SCALE PATTERN MORPHOLOGY AUDIT")
print("=" * 100)

if not os.path.exists(SYN_FILE):

    raise FileNotFoundError(
        SYN_FILE
    )


results = {

    "episodes": 0,

    "transactions": 0,

    "typology_episodes": Counter(),

    "typology_transactions": Counter(),

    "template_counts": Counter(),

    "template_typology": {},

    "new_template_ids": set(),

    "typology_mismatches": 0,

    "transaction_count_mismatches": 0,

    "node_count_mismatches": 0,

    "edge_count_mismatches": 0,

    "degree_signature_mismatches": 0,

    "max_in_degree_mismatches": 0,

    "max_out_degree_mismatches": 0,

    "source_node_mismatches": 0,

    "destination_node_mismatches": 0,

    "intermediate_node_mismatches": 0,

    "timestamp_structure_mismatches": 0,

    "source_order_mismatches": 0,
}


template_reference = {}


# Current episode
current_episode = None
closed_episode_ids = set()

rows_seen = 0


# --------------------------------------------------------------------------------------------------
# STREAM TRANSACTIONS
# --------------------------------------------------------------------------------------------------

print("\nStreaming synthetic transactions...")

with open(
    SYN_FILE,
    "r",
    newline="",
    encoding="utf-8"
) as f:

    reader = csv.DictReader(f)

    required = [
        "synthetic_episode_id",
        "typology",
        "source_template_id",
        "template_source_order",
        "Timestamp",
        "From Bank",
        "Account",
        "To Bank",
        "Account.1",
    ]

    missing = [
        c
        for c in required
        if c not in reader.fieldnames
    ]

    if missing:

        raise RuntimeError(
            "Missing required columns:\n"
            + str(missing)
        )


    for row in reader:

        rows_seen += 1

        episode_id = row[
            "synthetic_episode_id"
        ].strip()

        typology = row[
            "typology"
        ].strip().upper()

        template_id = row[
            "source_template_id"
        ].strip()

        template_order = int(
            row[
                "template_source_order"
            ]
        )

        # ------------------------------------------------------------------------------------------
        # New episode
        # ------------------------------------------------------------------------------------------

        if (
            current_episode is None
            or episode_id
            != current_episode["episode_id"]
        ):

            # Close previous
            if current_episode is not None:

                finish_episode(
                    current_episode,
                    template_reference,
                    results
                )

                closed_episode_ids.add(
                    current_episode[
                        "episode_id"
                    ]
                )


            # Detect a reappearing episode
            if episode_id in closed_episode_ids:

                raise RuntimeError(
                    "Episode IDs are not contiguous. "
                    f"Episode {episode_id} reappeared."
                )


            current_episode = {

                "episode_id":
                    episode_id,

                "typology":
                    typology,

                "template_id":
                    template_id,

                "tx_count":
                    0,

                "nodes":
                    set(),

                "edges":
                    set(),

                "in_deg":
                    defaultdict(int),

                "out_deg":
                    defaultdict(int),

                "timestamps":
                    [],

                "source_orders":
                    [],
            }


        # ------------------------------------------------------------------------------------------
        # Consistency within episode
        # ------------------------------------------------------------------------------------------

        if typology != current_episode["typology"]:

            results[
                "typology_mismatches"
            ] += 1


        if template_id != current_episode["template_id"]:

            results[
                "transaction_count_mismatches"
            ] += 1


        # ------------------------------------------------------------------------------------------
        # Graph nodes / edges
        # ------------------------------------------------------------------------------------------

        src = canonical_node(
            row["From Bank"],
            row["Account"]
        )

        dst = canonical_node(
            row["To Bank"],
            row["Account.1"]
        )

        edge = (
            src,
            dst
        )

        current_episode["nodes"].add(
            src
        )

        current_episode["nodes"].add(
            dst
        )

        current_episode["edges"].add(
            edge
        )

        current_episode["out_deg"][src] += 1
        current_episode["in_deg"][dst] += 1


        # ------------------------------------------------------------------------------------------
        # Time structure
        # ------------------------------------------------------------------------------------------

        try:

            current_episode[
                "timestamps"
            ].append(
                parse_timestamp(
                    row["Timestamp"]
                )
            )

        except Exception:

            pass


        # ------------------------------------------------------------------------------------------
        # Template source order
        # ------------------------------------------------------------------------------------------

        current_episode[
            "source_orders"
        ].append(
            template_order
        )

        current_episode[
            "tx_count"
        ] += 1


        # ------------------------------------------------------------------------------------------
        # Progress
        # ------------------------------------------------------------------------------------------

        if rows_seen % 1_000_000 == 0:

            print(
                f"  Rows processed: "
                f"{rows_seen:,}"
            )


# Finish final episode
if current_episode is not None:

    finish_episode(
        current_episode,
        template_reference,
        results
    )

    closed_episode_ids.add(
        current_episode[
            "episode_id"
        ]
    )


# --------------------------------------------------------------------------------------------------
# BASIC COUNTS
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("1. BASIC MORPHOLOGY COUNTS")
print("=" * 80)

print(
    f"Transactions processed : "
    f"{rows_seen:,}"
)

print(
    f"Expected transactions   : "
    f"{EXPECTED_TX:,}"
)

print(
    f"Episodes processed      : "
    f"{results['episodes']:,}"
)

print(
    f"Expected episodes       : "
    f"{EXPECTED_EPISODES:,}"
)

print(
    f"Unique templates seen   : "
    f"{len(template_reference):,}"
)


# --------------------------------------------------------------------------------------------------
# TYPOLOGY SUMMARY
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("2. TYPOLOGY MORPHOLOGY")
print("=" * 80)

for typ in sorted(
    results["typology_episodes"]
):

    print(
        f"{typ:18s} "
        f"| Episodes="
        f"{results['typology_episodes'][typ]:8,} "
        f"| Transactions="
        f"{results['typology_transactions'][typ]:10,}"
    )


# --------------------------------------------------------------------------------------------------
# MISMATCH SUMMARY
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("3. MORPHOLOGY MISMATCH SUMMARY")
print("=" * 80)

mismatch_metrics = {

    "Typology mismatches":
        results["typology_mismatches"],

    "Transaction-count mismatches":
        results["transaction_count_mismatches"],

    "Node-count mismatches":
        results["node_count_mismatches"],

    "Edge-count mismatches":
        results["edge_count_mismatches"],

    "Degree-signature mismatches":
        results["degree_signature_mismatches"],

    "Max in-degree mismatches":
        results["max_in_degree_mismatches"],

    "Max out-degree mismatches":
        results["max_out_degree_mismatches"],

    "Source-node mismatches":
        results["source_node_mismatches"],

    "Destination-node mismatches":
        results["destination_node_mismatches"],

    "Intermediate-node mismatches":
        results["intermediate_node_mismatches"],

    "Timestamp-structure mismatches":
        results["timestamp_structure_mismatches"],

    "Source-order mismatches":
        results["source_order_mismatches"],
}


all_morphology_zero = True

for name, value in mismatch_metrics.items():

    passed = (
        value == 0
    )

    print(
        f"{'✅ PASS' if passed else '❌ FAIL'} "
        f"| {name:35s} | {value:,}"
    )

    all_morphology_zero &= passed


# --------------------------------------------------------------------------------------------------
# TEMPLATE USAGE
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("4. TEMPLATE USAGE")
print("=" * 80)

template_usage_values = list(
    results["template_counts"].values()
)

if template_usage_values:

    print(
        f"Templates used : "
        f"{len(template_usage_values):,}"
    )

    print(
        f"Minimum episodes/template : "
        f"{min(template_usage_values):,}"
    )

    print(
        f"Maximum episodes/template : "
        f"{max(template_usage_values):,}"
    )

    print(
        f"Median episodes/template  : "
        f"{sorted(template_usage_values)[
            len(template_usage_values)//2
        ]:,}"
    )


# --------------------------------------------------------------------------------------------------
# SAVE JSON
# --------------------------------------------------------------------------------------------------

audit_json = {

    "transactions_processed":
        rows_seen,

    "expected_transactions":
        EXPECTED_TX,

    "episodes_processed":
        results["episodes"],

    "expected_episodes":
        EXPECTED_EPISODES,

    "unique_templates":
        len(template_reference),

    "typology_episodes":
        dict(
            results["typology_episodes"]
        ),

    "typology_transactions":
        dict(
            results["typology_transactions"]
        ),

    "template_counts":
        {
            str(k): int(v)
            for k, v
            in results["template_counts"].items()
        },

    "mismatch_metrics":
        mismatch_metrics,

    "morphology_pass":
        (
            rows_seen == EXPECTED_TX
            and results["episodes"]
                == EXPECTED_EPISODES
            and len(template_reference)
                == 370
            and all_morphology_zero
        ),
}


with open(
    OUT_JSON,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        audit_json,
        f,
        indent=2
    )


# --------------------------------------------------------------------------------------------------
# SAVE SUMMARY CSV
# --------------------------------------------------------------------------------------------------

with open(
    OUT_CSV,
    "w",
    newline="",
    encoding="utf-8"
) as f:

    writer = csv.writer(f)

    writer.writerow([
        "metric",
        "value"
    ])

    writer.writerow([
        "transactions_processed",
        rows_seen
    ])

    writer.writerow([
        "expected_transactions",
        EXPECTED_TX
    ])

    writer.writerow([
        "episodes_processed",
        results["episodes"]
    ])

    writer.writerow([
        "expected_episodes",
        EXPECTED_EPISODES
    ])

    writer.writerow([
        "unique_templates",
        len(template_reference)
    ])

    for name, value in mismatch_metrics.items():

        writer.writerow([
            name,
            value
        ])


# --------------------------------------------------------------------------------------------------
# FINAL GATE
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 100)

if audit_json["morphology_pass"]:

    print(
        "✅✅✅ FULL-SCALE PATTERN MORPHOLOGY PASSED ✅✅✅"
    )

else:

    print(
        "❌ FULL-SCALE PATTERN MORPHOLOGY HAS MISMATCHES"
    )

print("=" * 100)

print(
    f"Audit JSON: {OUT_JSON}"
)

print(
    f"Audit CSV : {OUT_CSV}"
)

print("=" * 100)

====================================================================================================
CELL 23 — FULL-SCALE PATTERN MORPHOLOGY AUDIT
====================================================================================================

Streaming synthetic transactions...
  Rows processed: 1,000,000
  Rows processed: 2,000,000
  Rows processed: 3,000,000
  Rows processed: 4,000,000
  Rows processed: 5,000,000

================================================================================
1. BASIC MORPHOLOGY COUNTS
================================================================================
Transactions processed : 5,067,991
Expected transactions   : 5,067,991
Episodes processed      : 584,706
Expected episodes       : 584,706
Unique templates seen   : 370

================================================================================
2. TYPOLOGY MORPHOLOGY
================================================================================
BIPARTITE          | Episodes=  77,451 | Transactions=   415,357
CYCLE              | Episodes=  85,293 | Transactions=   453,261
FAN-IN             | Episodes=  63,218 | Transactions=   502,219
FAN-OUT            | Episodes=  75,862 | Transactions=   540,123
GATHER-SCATTER     | Episodes=  80,605 | Transactions= 1,130,782
RANDOM             | Episodes=  64,782 | Transactions=   301,647
SCATTER-GATHER     | Episodes=  69,540 | Transactions=   988,646
STACK              | Episodes=  67,955 | Transactions=   735,956

================================================================================
3. MORPHOLOGY MISMATCH SUMMARY
================================================================================
✅ PASS | Typology mismatches                 | 0
✅ PASS | Transaction-count mismatches        | 0
✅ PASS | Node-count mismatches               | 0
✅ PASS | Edge-count mismatches               | 0
✅ PASS | Degree-signature mismatches         | 0
✅ PASS | Max in-degree mismatches            | 0
✅ PASS | Max out-degree mismatches           | 0
✅ PASS | Source-node mismatches              | 0
✅ PASS | Destination-node mismatches         | 0
✅ PASS | Intermediate-node mismatches        | 0
✅ PASS | Timestamp-structure mismatches      | 0
❌ FAIL | Source-order mismatches             | 584,336

================================================================================
4. TEMPLATE USAGE
================================================================================
Templates used : 370
Minimum episodes/template : 1,480
Maximum episodes/template : 1,678
Median episodes/template  : 1,579

====================================================================================================
❌ FULL-SCALE PATTERN MORPHOLOGY HAS MISMATCHES
====================================================================================================
Audit JSON: /kaggle/working/AML_GNN_ONLY/data/HI-Small_SYNTH_full_morphology_audit.json
Audit CSV : /kaggle/working/AML_GNN_ONLY/data/HI-Small_SYNTH_full_morphology_summary.csv
====================================================================================================

In [40]:
# ==================================================================================================
# CELL 24 — ORIGINAL LAUNDERING vs SYNTHETIC LAUNDERING AUDIT
#
# IMPORTANT:
#   Compare ONLY:
#       Original laundering  = 5,177
#       Synthetic laundering = 5,067,991
#
#   DO NOT compare legitimate transactions against synthetic laundering here.
#
# Checks:
#   1. Amount mean / median / quantiles
#   2. Payment Format
#   3. Payment Currency
#   4. Receiving Currency
#   5. Hour distribution
#   6. Day-of-week distribution
#   7. Source-account activity
#   8. Destination-account activity
#   9. Source-bank concentration
#  10. Destination-bank concentration
#  11. Bank/account diversity
#
# This cell DOES NOT modify or regenerate any data.
# ==================================================================================================

import os
import csv
import math
import random
from collections import Counter
from datetime import datetime


# --------------------------------------------------------------------------------------------------
# PATHS
# --------------------------------------------------------------------------------------------------

BASE = "/kaggle/working/AML_GNN_ONLY/data"

ORIGINAL_FILE = (
    "/kaggle/input/datasets/"
    "ealtman2019/ibm-transactions-for-anti-money-laundering-aml/"
    "HI-Small_Trans.csv"
)

SYNTHETIC_FILE = os.path.join(
    BASE,
    "HI-Small_SYNTH_FULL_transactions.csv"
)

OUT_JSON = os.path.join(
    BASE,
    "HI-Small_original_laundering_vs_synthetic_laundering.json"
)


# --------------------------------------------------------------------------------------------------
# EXPECTED
# --------------------------------------------------------------------------------------------------

EXPECTED_ORIGINAL_LAUNDERING = 5_177
EXPECTED_SYNTHETIC_LAUNDERING = 5_067_991


# --------------------------------------------------------------------------------------------------
# HELPERS
# --------------------------------------------------------------------------------------------------

def canonical_bank(x):

    s = str(x).strip()

    if not s:
        return None

    if s.isdigit():
        return str(int(s))

    return s.upper()


def pct(x, total):

    return (
        100.0 * x / total
        if total
        else 0.0
    )


def qvalue(values, q):

    if not values:
        return None

    values = sorted(values)

    idx = int(
        q * (len(values) - 1)
    )

    return values[idx]


def distribution_pct(counter, total):

    return {
        str(k): {
            "count": int(v),
            "pct": pct(v, total)
        }
        for k, v in counter.items()
    }


def new_stats():

    return {

        "rows": 0,

        "amounts": [],

        "payment_format": Counter(),

        "payment_currency": Counter(),

        "receiving_currency": Counter(),

        "hour": Counter(),

        "day_of_week": Counter(),

        "date": Counter(),

        "source_account": Counter(),

        "destination_account": Counter(),

        "source_bank": Counter(),

        "destination_bank": Counter(),
    }


# --------------------------------------------------------------------------------------------------
# STREAM ORIGINAL LAUNDERING
# --------------------------------------------------------------------------------------------------

def stream_original_laundering(path):

    stats = new_stats()

    with open(
        path,
        "r",
        newline="",
        encoding="utf-8-sig"
    ) as f:

        reader = csv.reader(f)

        header = next(reader)

        expected_header = [
            "Timestamp",
            "From Bank",
            "Account",
            "To Bank",
            "Account",
            "Amount Received",
            "Receiving Currency",
            "Amount Paid",
            "Payment Currency",
            "Payment Format",
            "Is Laundering"
        ]

        if header != expected_header:

            raise RuntimeError(
                "Unexpected original HI-Small header:\n"
                + str(header)
            )


        for row in reader:

            if len(row) != 11:
                continue


            # ONLY LAUNDERING
            label = row[10].strip()

            if label not in {"1", "1.0"}:
                continue


            stats["rows"] += 1


            # ------------------------------------------------------------------
            # AMOUNT
            # ------------------------------------------------------------------

            try:

                amount = float(
                    row[5]
                )

                if (
                    math.isfinite(amount)
                    and amount > 0
                ):

                    stats["amounts"].append(
                        amount
                    )

            except Exception:
                pass


            # ------------------------------------------------------------------
            # CATEGORICAL
            # ------------------------------------------------------------------

            stats["payment_format"][
                row[9].strip()
            ] += 1

            stats["payment_currency"][
                row[8].strip()
            ] += 1

            stats["receiving_currency"][
                row[6].strip()
            ] += 1


            # ------------------------------------------------------------------
            # TIME
            # ------------------------------------------------------------------

            try:

                dt = datetime.strptime(
                    row[0].strip(),
                    "%Y-%m-%d %H:%M:%S"
                )

            except Exception:

                try:

                    dt = datetime.strptime(
                        row[0].strip(),
                        "%Y/%m/%d %H:%M"
                    )

                except Exception:

                    dt = None


            if dt is not None:

                stats["hour"][
                    dt.hour
                ] += 1

                stats["day_of_week"][
                    dt.strftime("%A")
                ] += 1

                stats["date"][
                    dt.strftime("%Y-%m-%d")
                ] += 1


            # ------------------------------------------------------------------
            # BANKS / ACCOUNTS
            # ------------------------------------------------------------------

            src_bank = canonical_bank(
                row[1]
            )

            dst_bank = canonical_bank(
                row[3]
            )

            src_account = row[2].strip()
            dst_account = row[4].strip()


            stats["source_bank"][
                src_bank
            ] += 1

            stats["destination_bank"][
                dst_bank
            ] += 1

            stats["source_account"][
                src_account
            ] += 1

            stats["destination_account"][
                dst_account
            ] += 1


    return stats


# --------------------------------------------------------------------------------------------------
# STREAM SYNTHETIC LAUNDERING
# --------------------------------------------------------------------------------------------------

def stream_synthetic_laundering(path):

    stats = new_stats()

    with open(
        path,
        "r",
        newline="",
        encoding="utf-8"
    ) as f:

        reader = csv.DictReader(f)


        for row in reader:

            # Synthetic file contains only laundering rows,
            # but explicitly verify it.
            label = row[
                "Is Laundering"
            ].strip()

            if label not in {
                "1",
                "1.0"
            }:

                continue


            stats["rows"] += 1


            # ------------------------------------------------------------------
            # AMOUNT
            # ------------------------------------------------------------------

            try:

                amount = float(
                    row[
                        "Amount Received"
                    ]
                )

                if (
                    math.isfinite(amount)
                    and amount > 0
                ):

                    stats["amounts"].append(
                        amount
                    )

            except Exception:
                pass


            # ------------------------------------------------------------------
            # CATEGORICAL
            # ------------------------------------------------------------------

            stats["payment_format"][
                row[
                    "Payment Format"
                ].strip()
            ] += 1

            stats["payment_currency"][
                row[
                    "Payment Currency"
                ].strip()
            ] += 1

            stats["receiving_currency"][
                row[
                    "Receiving Currency"
                ].strip()
            ] += 1


            # ------------------------------------------------------------------
            # TIME
            # ------------------------------------------------------------------

            try:

                dt = datetime.strptime(
                    row["Timestamp"].strip(),
                    "%Y-%m-%d %H:%M:%S"
                )

            except Exception:

                try:

                    dt = datetime.strptime(
                        row["Timestamp"].strip(),
                        "%Y/%m/%d %H:%M"
                    )

                except Exception:

                    dt = None


            if dt is not None:

                stats["hour"][
                    dt.hour
                ] += 1

                stats["day_of_week"][
                    dt.strftime("%A")
                ] += 1

                stats["date"][
                    dt.strftime("%Y-%m-%d")
                ] += 1


            # ------------------------------------------------------------------
            # BANKS / ACCOUNTS
            # ------------------------------------------------------------------

            src_bank = canonical_bank(
                row["From Bank"]
            )

            dst_bank = canonical_bank(
                row["To Bank"]
            )

            src_account = row[
                "Account"
            ].strip()

            dst_account = row[
                "Account.1"
            ].strip()


            stats["source_bank"][
                src_bank
            ] += 1

            stats["destination_bank"][
                dst_bank
            ] += 1

            stats["source_account"][
                src_account
            ] += 1

            stats["destination_account"][
                dst_account
            ] += 1


    return stats


# --------------------------------------------------------------------------------------------------
# START
# --------------------------------------------------------------------------------------------------

print("=" * 100)
print("CELL 24 — ORIGINAL LAUNDERING vs SYNTHETIC LAUNDERING")
print("=" * 100)


print("\nStreaming ORIGINAL LAUNDERING...")

original = stream_original_laundering(
    ORIGINAL_FILE
)

print(
    f"Original laundering rows: "
    f"{original['rows']:,}"
)


print("\nStreaming SYNTHETIC LAUNDERING...")

synthetic = stream_synthetic_laundering(
    SYNTHETIC_FILE
)

print(
    f"Synthetic laundering rows: "
    f"{synthetic['rows']:,}"
)


# --------------------------------------------------------------------------------------------------
# COUNT CHECK
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("1. COUNT CHECK")
print("=" * 80)

print(
    f"Original laundering : "
    f"{original['rows']:,}"
)

print(
    f"Expected             : "
    f"{EXPECTED_ORIGINAL_LAUNDERING:,}"
)

print(
    f"Synthetic laundering: "
    f"{synthetic['rows']:,}"
)

print(
    f"Expected             : "
    f"{EXPECTED_SYNTHETIC_LAUNDERING:,}"
)


count_gate = (
    original["rows"]
    == EXPECTED_ORIGINAL_LAUNDERING
    and
    synthetic["rows"]
    == EXPECTED_SYNTHETIC_LAUNDERING
)


print(
    "\n✅ PASS"
    if count_gate
    else "\n❌ FAIL"
)


# --------------------------------------------------------------------------------------------------
# AMOUNT STATISTICS
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("2. AMOUNT DISTRIBUTION")
print("=" * 80)


amount_quantiles = [
    0.01,
    0.05,
    0.10,
    0.25,
    0.50,
    0.75,
    0.90,
    0.95,
    0.99,
]


def amount_stats(values):

    if not values:
        return {}

    return {

        "mean":
            sum(values) / len(values),

        "median":
            qvalue(values, 0.50),

        "p01":
            qvalue(values, 0.01),

        "p05":
            qvalue(values, 0.05),

        "p10":
            qvalue(values, 0.10),

        "p25":
            qvalue(values, 0.25),

        "p75":
            qvalue(values, 0.75),

        "p90":
            qvalue(values, 0.90),

        "p95":
            qvalue(values, 0.95),

        "p99":
            qvalue(values, 0.99),

        "min":
            min(values),

        "max":
            max(values),
    }


orig_amount = amount_stats(
    original["amounts"]
)

syn_amount = amount_stats(
    synthetic["amounts"]
)


print(
    f"{'Metric':12s} "
    f"{'Original laundering':>24s} "
    f"{'Synthetic laundering':>24s} "
    f"{'Ratio':>12s}"
)


for key in [
    "mean",
    "median",
    "p01",
    "p05",
    "p10",
    "p25",
    "p75",
    "p90",
    "p95",
    "p99",
    "min",
    "max",
]:

    ov = orig_amount[key]
    sv = syn_amount[key]

    ratio = (
        sv / ov
        if ov != 0
        else None
    )

    print(
        f"{key:12s} "
        f"{ov:24.6f} "
        f"{sv:24.6f} "
        f"{ratio:12.4f}"
    )


# --------------------------------------------------------------------------------------------------
# PAYMENT FORMAT
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("3. PAYMENT FORMAT")
print("=" * 80)


formats = sorted(
    set(original["payment_format"])
    | set(synthetic["payment_format"])
)


for fmt in formats:

    op = pct(
        original["payment_format"].get(
            fmt,
            0
        ),
        original["rows"]
    )

    sp = pct(
        synthetic["payment_format"].get(
            fmt,
            0
        ),
        synthetic["rows"]
    )

    print(
        f"{fmt:18s} "
        f"| Original={op:9.4f}% "
        f"| Synthetic={sp:9.4f}% "
        f"| AbsDiff={abs(op-sp):9.4f}"
    )


# --------------------------------------------------------------------------------------------------
# PAYMENT CURRENCY
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("4. PAYMENT CURRENCY")
print("=" * 80)


currencies = sorted(
    set(original["payment_currency"])
    | set(synthetic["payment_currency"])
)


for curr in currencies:

    op = pct(
        original["payment_currency"].get(
            curr,
            0
        ),
        original["rows"]
    )

    sp = pct(
        synthetic["payment_currency"].get(
            curr,
            0
        ),
        synthetic["rows"]
    )

    print(
        f"{curr:20s} "
        f"| Original={op:9.4f}% "
        f"| Synthetic={sp:9.4f}% "
        f"| AbsDiff={abs(op-sp):9.4f}"
    )


# --------------------------------------------------------------------------------------------------
# RECEIVING CURRENCY
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("5. RECEIVING CURRENCY")
print("=" * 80)


currencies = sorted(
    set(original["receiving_currency"])
    | set(synthetic["receiving_currency"])
)


for curr in currencies:

    op = pct(
        original["receiving_currency"].get(
            curr,
            0
        ),
        original["rows"]
    )

    sp = pct(
        synthetic["receiving_currency"].get(
            curr,
            0
        ),
        synthetic["rows"]
    )

    print(
        f"{curr:20s} "
        f"| Original={op:9.4f}% "
        f"| Synthetic={sp:9.4f}% "
        f"| AbsDiff={abs(op-sp):9.4f}"
    )


# --------------------------------------------------------------------------------------------------
# HOUR DISTRIBUTION
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("6. HOUR DISTRIBUTION")
print("=" * 80)


hour_diffs = []


for h in range(24):

    op = pct(
        original["hour"].get(
            h,
            0
        ),
        original["rows"]
    )

    sp = pct(
        synthetic["hour"].get(
            h,
            0
        ),
        synthetic["rows"]
    )

    diff = abs(
        op - sp
    )

    hour_diffs.append(
        diff
    )

    print(
        f"{h:02d}:00 "
        f"| Original={op:9.4f}% "
        f"| Synthetic={sp:9.4f}% "
        f"| AbsDiff={diff:9.4f}"
    )


hour_mae = (
    sum(hour_diffs)
    / len(hour_diffs)
)


print(
    f"\nHour MAE: "
    f"{hour_mae:.6f} percentage points"
)


# --------------------------------------------------------------------------------------------------
# DAY-OF-WEEK
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("7. DAY-OF-WEEK DISTRIBUTION")
print("=" * 80)


days = [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday"
]


dow_diffs = []


for day in days:

    op = pct(
        original["day_of_week"].get(
            day,
            0
        ),
        original["rows"]
    )

    sp = pct(
        synthetic["day_of_week"].get(
            day,
            0
        ),
        synthetic["rows"]
    )

    diff = abs(
        op - sp
    )

    dow_diffs.append(
        diff
    )

    print(
        f"{day:10s} "
        f"| Original={op:9.4f}% "
        f"| Synthetic={sp:9.4f}% "
        f"| AbsDiff={diff:9.4f}"
    )


dow_mae = (
    sum(dow_diffs)
    / len(dow_diffs)
)


print(
    f"\nDay-of-week MAE: "
    f"{dow_mae:.6f} percentage points"
)


# --------------------------------------------------------------------------------------------------
# BANK / ACCOUNT DIVERSITY
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("8. BANK / ACCOUNT DIVERSITY")
print("=" * 80)


print(
    f"{'Metric':30s} "
    f"{'Original':>15s} "
    f"{'Synthetic':>15s}"
)


metrics = [

    (
        "Unique source banks",
        len(original["source_bank"]),
        len(synthetic["source_bank"])
    ),

    (
        "Unique destination banks",
        len(original["destination_bank"]),
        len(synthetic["destination_bank"])
    ),

    (
        "Unique source accounts",
        len(original["source_account"]),
        len(synthetic["source_account"])
    ),

    (
        "Unique destination accounts",
        len(original["destination_account"]),
        len(synthetic["destination_account"])
    ),
]


for name, ov, sv in metrics:

    print(
        f"{name:30s} "
        f"{ov:15,} "
        f"{sv:15,}"
    )


# --------------------------------------------------------------------------------------------------
# ACCOUNT REUSE
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("9. ACCOUNT REUSE")
print("=" * 80)


def reuse_stats(counter):

    values = sorted(
        counter.values()
    )

    if not values:
        return {}

    n = len(values)

    def q(p):

        return values[
            int(
                p * (n - 1)
            )
        ]

    return {

        "min":
            values[0],

        "p25":
            q(0.25),

        "median":
            q(0.50),

        "p75":
            q(0.75),

        "p90":
            q(0.90),

        "p95":
            q(0.95),

        "p99":
            q(0.99),

        "max":
            values[-1],
    }


orig_src_reuse = reuse_stats(
    original["source_account"]
)

syn_src_reuse = reuse_stats(
    synthetic["source_account"]
)

orig_dst_reuse = reuse_stats(
    original["destination_account"]
)

syn_dst_reuse = reuse_stats(
    synthetic["destination_account"]
)


print("\nSOURCE ACCOUNT REUSE")

for key in [
    "min",
    "p25",
    "median",
    "p75",
    "p90",
    "p95",
    "p99",
    "max"
]:

    print(
        f"{key:8s} "
        f"| Original={orig_src_reuse[key]:12,} "
        f"| Synthetic={syn_src_reuse[key]:12,}"
    )


print("\nDESTINATION ACCOUNT REUSE")

for key in [
    "min",
    "p25",
    "median",
    "p75",
    "p90",
    "p95",
    "p99",
    "max"
]:

    print(
        f"{key:8s} "
        f"| Original={orig_dst_reuse[key]:12,} "
        f"| Synthetic={syn_dst_reuse[key]:12,}"
    )


# --------------------------------------------------------------------------------------------------
# BANK CONCENTRATION
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("10. BANK CONCENTRATION")
print("=" * 80)


def top_share(counter, total, k):

    return (
        100.0
        * sum(
            v
            for _, v
            in counter.most_common(k)
        )
        / total
        if total
        else 0.0
    )


print("\nSOURCE BANKS")

for k in [
    1,
    5,
    10,
    25,
    50,
]:

    op = top_share(
        original["source_bank"],
        original["rows"],
        k
    )

    sp = top_share(
        synthetic["source_bank"],
        synthetic["rows"],
        k
    )

    print(
        f"Top {k:2d} "
        f"| Original={op:9.4f}% "
        f"| Synthetic={sp:9.4f}% "
        f"| AbsDiff={abs(op-sp):9.4f}"
    )


print("\nDESTINATION BANKS")

for k in [
    1,
    5,
    10,
    25,
    50,
]:

    op = top_share(
        original["destination_bank"],
        original["rows"],
        k
    )

    sp = top_share(
        synthetic["destination_bank"],
        synthetic["rows"],
        k
    )

    print(
        f"Top {k:2d} "
        f"| Original={op:9.4f}% "
        f"| Synthetic={sp:9.4f}% "
        f"| AbsDiff={abs(op-sp):9.4f}"
    )


# --------------------------------------------------------------------------------------------------
# SUMMARY
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("11. SUMMARY")
print("=" * 80)


print(
    f"Original laundering rows : "
    f"{original['rows']:,}"
)

print(
    f"Synthetic laundering rows: "
    f"{synthetic['rows']:,}"
)

print(
    f"Original median amount   : "
    f"{orig_amount['median']:,.6f}"
)

print(
    f"Synthetic median amount  : "
    f"{syn_amount['median']:,.6f}"
)

print(
    f"Original mean amount     : "
    f"{orig_amount['mean']:,.6f}"
)

print(
    f"Synthetic mean amount    : "
    f"{syn_amount['mean']:,.6f}"
)

print(
    f"Hour MAE                 : "
    f"{hour_mae:.6f} pp"
)

print(
    f"Day-of-week MAE          : "
    f"{dow_mae:.6f} pp"
)


# --------------------------------------------------------------------------------------------------
# SAVE JSON
# --------------------------------------------------------------------------------------------------

audit = {

    "comparison":
        "Original laundering vs Synthetic laundering",

    "rows": {

        "original_laundering":
            original["rows"],

        "synthetic_laundering":
            synthetic["rows"],
    },

    "amount": {

        "original":
            orig_amount,

        "synthetic":
            syn_amount,
    },

    "payment_format": {

        "original":
            distribution_pct(
                original["payment_format"],
                original["rows"]
            ),

        "synthetic":
            distribution_pct(
                synthetic["payment_format"],
                synthetic["rows"]
            ),
    },

    "payment_currency": {

        "original":
            distribution_pct(
                original["payment_currency"],
                original["rows"]
            ),

        "synthetic":
            distribution_pct(
                synthetic["payment_currency"],
                synthetic["rows"]
            ),
    },

    "receiving_currency": {

        "original":
            distribution_pct(
                original["receiving_currency"],
                original["rows"]
            ),

        "synthetic":
            distribution_pct(
                synthetic["receiving_currency"],
                synthetic["rows"]
            ),
    },

    "hour_mae_percentage_points":
        hour_mae,

    "day_of_week_mae_percentage_points":
        dow_mae,

    "original_unique_source_banks":
        len(original["source_bank"]),

    "synthetic_unique_source_banks":
        len(synthetic["source_bank"]),

    "original_unique_destination_banks":
        len(original["destination_bank"]),

    "synthetic_unique_destination_banks":
        len(synthetic["destination_bank"]),

    "original_unique_source_accounts":
        len(original["source_account"]),

    "synthetic_unique_source_accounts":
        len(synthetic["source_account"]),

    "original_unique_destination_accounts":
        len(original["destination_account"]),

    "synthetic_unique_destination_accounts":
        len(synthetic["destination_account"]),
}


with open(
    OUT_JSON,
    "w",
    encoding="utf-8"
) as f:

    import json

    json.dump(
        audit,
        f,
        indent=2
    )


# --------------------------------------------------------------------------------------------------
# FINAL
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("✅ CELL 24 COMPLETE")
print("=" * 100)

print(
    f"Audit saved to:\n{OUT_JSON}"
)

print("=" * 100)

====================================================================================================
CELL 24 — ORIGINAL LAUNDERING vs SYNTHETIC LAUNDERING
====================================================================================================

Streaming ORIGINAL LAUNDERING...
Original laundering rows: 5,177

Streaming SYNTHETIC LAUNDERING...
Synthetic laundering rows: 5,067,991

================================================================================
1. COUNT CHECK
================================================================================
Original laundering : 5,177
Expected             : 5,177
Synthetic laundering: 5,067,991
Expected             : 5,067,991

✅ PASS

================================================================================
2. AMOUNT DISTRIBUTION
================================================================================
Metric            Original laundering     Synthetic laundering        Ratio
mean                  36135310.412813          21383007.836351       0.5917
median                    8667.210000              1465.920000       0.1691
p01                          0.995281                 0.014792       0.0149
p05                        213.850000                 3.413636       0.0160
p10                        672.380000                17.142333       0.0255
p25                       2634.970000               150.797968       0.0572
p75                      18832.270000             17584.697184       0.9338
p90                     170985.240000            276577.693457       1.6176
p95                     939548.060000           1575621.745114       1.6770
p99                   23199483.550000          59921433.366666       2.5829
min                          0.003227                 0.000001       0.0003
max                84853144179.580002       25747762666.420002       0.3034

================================================================================
3. PAYMENT FORMAT
================================================================================
ACH                | Original=  86.5946% | Synthetic=  12.1572% | AbsDiff=  74.4374
Bitcoin            | Original=   1.0817% | Synthetic=   2.8912% | AbsDiff=   1.8095
Cash               | Original=   2.0862% | Synthetic=   9.6577% | AbsDiff=   7.5716
Cheque             | Original=   6.2585% | Synthetic=  37.3459% | AbsDiff=  31.0875
Credit Card        | Original=   3.9791% | Synthetic=  25.8681% | AbsDiff=  21.8889
Reinvestment       | Original=   0.0000% | Synthetic=   8.6508% | AbsDiff=   8.6508
Wire               | Original=   0.0000% | Synthetic=   3.4291% | AbsDiff=   3.4291

================================================================================
4. PAYMENT CURRENCY
================================================================================
Australian Dollar    | Original=   2.4532% | Synthetic=   2.6706% | AbsDiff=   0.2175
Bitcoin              | Original=   1.0817% | Synthetic=   2.8846% | AbsDiff=   1.8029
Brazil Real          | Original=   1.1010% | Synthetic=   1.4060% | AbsDiff=   0.3050
Canadian Dollar      | Original=   2.4725% | Synthetic=   2.8576% | AbsDiff=   0.3851
Euro                 | Original=  26.5018% | Synthetic=  22.8462% | AbsDiff=   3.6556
Mexican Peso         | Original=   1.7771% | Synthetic=   2.2160% | AbsDiff=   0.4389
Ruble                | Original=   2.5691% | Synthetic=   3.1147% | AbsDiff=   0.5456
Rupee                | Original=   3.2258% | Synthetic=   3.6596% | AbsDiff=   0.4338
Saudi Riyal          | Original=   7.2243% | Synthetic=   1.7868% | AbsDiff=   5.4374
Shekel               | Original=   1.8350% | Synthetic=   3.8684% | AbsDiff=   2.0333
Swiss Franc          | Original=   3.7280% | Synthetic=   4.7016% | AbsDiff=   0.9736
UK Pound             | Original=   2.5497% | Synthetic=   3.6525% | AbsDiff=   1.1028
US Dollar            | Original=  36.9326% | Synthetic=  37.0418% | AbsDiff=   0.1092
Yen                  | Original=   2.9940% | Synthetic=   3.1073% | AbsDiff=   0.1133
Yuan                 | Original=   3.5542% | Synthetic=   4.1864% | AbsDiff=   0.6322

================================================================================
5. RECEIVING CURRENCY
================================================================================
Australian Dollar    | Original=   2.4532% | Synthetic=   2.7104% | AbsDiff=   0.2572
Bitcoin              | Original=   1.0817% | Synthetic=   2.9193% | AbsDiff=   1.8376
Brazil Real          | Original=   1.1010% | Synthetic=   1.4202% | AbsDiff=   0.3192
Canadian Dollar      | Original=   2.4725% | Synthetic=   2.8727% | AbsDiff=   0.4002
Euro                 | Original=  26.5018% | Synthetic=  22.9225% | AbsDiff=   3.5793
Mexican Peso         | Original=   1.7771% | Synthetic=   2.2411% | AbsDiff=   0.4641
Ruble                | Original=   2.5691% | Synthetic=   3.1500% | AbsDiff=   0.5810
Rupee                | Original=   3.2258% | Synthetic=   3.7074% | AbsDiff=   0.4816
Saudi Riyal          | Original=   7.2243% | Synthetic=   1.8115% | AbsDiff=   5.4128
Shekel               | Original=   1.8350% | Synthetic=   3.9124% | AbsDiff=   2.0773
Swiss Franc          | Original=   3.7280% | Synthetic=   4.7709% | AbsDiff=   1.0429
UK Pound             | Original=   2.5497% | Synthetic=   3.6437% | AbsDiff=   1.0940
US Dollar            | Original=  36.9326% | Synthetic=  36.7676% | AbsDiff=   0.1650
Yen                  | Original=   2.9940% | Synthetic=   3.1191% | AbsDiff=   0.1251
Yuan                 | Original=   3.5542% | Synthetic=   4.0312% | AbsDiff=   0.4770

================================================================================
6. HOUR DISTRIBUTION
================================================================================
00:00 | Original=   3.3997% | Synthetic=   4.9561% | AbsDiff=   1.5564
01:00 | Original=   2.9361% | Synthetic=   4.0008% | AbsDiff=   1.0647
02:00 | Original=   3.1872% | Synthetic=   4.0594% | AbsDiff=   0.8723
03:00 | Original=   2.8202% | Synthetic=   4.0574% | AbsDiff=   1.2372
04:00 | Original=   2.9747% | Synthetic=   4.0374% | AbsDiff=   1.0627
05:00 | Original=   3.6314% | Synthetic=   4.0783% | AbsDiff=   0.4469
06:00 | Original=   3.9985% | Synthetic=   4.0222% | AbsDiff=   0.0238
07:00 | Original=   3.7667% | Synthetic=   4.2672% | AbsDiff=   0.5006
08:00 | Original=   4.9836% | Synthetic=   4.0347% | AbsDiff=   0.9488
09:00 | Original=   4.1916% | Synthetic=   4.0461% | AbsDiff=   0.1455
10:00 | Original=   4.5200% | Synthetic=   4.0885% | AbsDiff=   0.4314
11:00 | Original=   5.6983% | Synthetic=   4.1589% | AbsDiff=   1.5394
12:00 | Original=   6.4902% | Synthetic=   4.0524% | AbsDiff=   2.4379
13:00 | Original=   5.6403% | Synthetic=   4.1596% | AbsDiff=   1.4807
14:00 | Original=   5.3892% | Synthetic=   4.2050% | AbsDiff=   1.1842
15:00 | Original=   5.0802% | Synthetic=   4.1896% | AbsDiff=   0.8906
16:00 | Original=   6.0073% | Synthetic=   4.2872% | AbsDiff=   1.7202
17:00 | Original=   4.9643% | Synthetic=   4.0781% | AbsDiff=   0.8862
18:00 | Original=   4.9256% | Synthetic=   4.1034% | AbsDiff=   0.8223
19:00 | Original=   4.4620% | Synthetic=   4.5755% | AbsDiff=   0.1135
20:00 | Original=   2.5884% | Synthetic=   4.1136% | AbsDiff=   1.5252
21:00 | Original=   2.9747% | Synthetic=   4.1465% | AbsDiff=   1.1718
22:00 | Original=   2.4725% | Synthetic=   4.1696% | AbsDiff=   1.6971
23:00 | Original=   2.8974% | Synthetic=   4.1124% | AbsDiff=   1.2149

Hour MAE: 1.040598 percentage points

================================================================================
7. DAY-OF-WEEK DISTRIBUTION
================================================================================
Monday     | Original=  12.3817% | Synthetic=  13.4611% | AbsDiff=   1.0794
Tuesday    | Original=  12.3044% | Synthetic=  10.8091% | AbsDiff=   1.4954
Wednesday  | Original=  10.9523% | Synthetic=  10.1134% | AbsDiff=   0.8389
Thursday   | Original=  17.1721% | Synthetic=  14.1341% | AbsDiff=   3.0380
Friday     | Original=  18.3118% | Synthetic=  17.5878% | AbsDiff=   0.7240
Saturday   | Original=  16.3801% | Synthetic=  17.5648% | AbsDiff=   1.1847
Sunday     | Original=  12.4976% | Synthetic=  16.3297% | AbsDiff=   3.8321

Day-of-week MAE: 1.741786 percentage points

================================================================================
8. BANK / ACCOUNT DIVERSITY
================================================================================
Metric                                Original       Synthetic
Unique source banks                      1,021           1,064
Unique destination banks                 1,105           1,223
Unique source accounts                   3,376         682,923
Unique destination accounts              3,984         542,095

================================================================================
9. ACCOUNT REUSE
================================================================================

SOURCE ACCOUNT REUSE
min      | Original=           1 | Synthetic=           1
p25      | Original=           1 | Synthetic=           1
median   | Original=           1 | Synthetic=           1
p75      | Original=           1 | Synthetic=           8
p90      | Original=           1 | Synthetic=          26
p95      | Original=           2 | Synthetic=          34
p99      | Original=          15 | Synthetic=          48
max      | Original=         243 | Synthetic=         330

DESTINATION ACCOUNT REUSE
min      | Original=           1 | Synthetic=           1
p25      | Original=           1 | Synthetic=           1
median   | Original=           1 | Synthetic=           4
p75      | Original=           1 | Synthetic=          15
p90      | Original=           1 | Synthetic=          26
p95      | Original=           1 | Synthetic=          33
p99      | Original=          13 | Synthetic=          46
max      | Original=          31 | Synthetic=         104

================================================================================
10. BANK CONCENTRATION
================================================================================

SOURCE BANKS
Top  1 | Original=  12.2272% | Synthetic=   5.4621% | AbsDiff=   6.7651
Top  5 | Original=  17.1142% | Synthetic=  12.8769% | AbsDiff=   4.2373
Top 10 | Original=  21.3444% | Synthetic=  16.9372% | AbsDiff=   4.4072
Top 25 | Original=  30.0367% | Synthetic=  26.1294% | AbsDiff=   3.9073
Top 50 | Original=  39.4437% | Synthetic=  38.3516% | AbsDiff=   1.0920

DESTINATION BANKS
Top  1 | Original=   1.7191% | Synthetic=   2.4429% | AbsDiff=   0.7237
Top  5 | Original=   6.5096% | Synthetic=   7.3716% | AbsDiff=   0.8620
Top 10 | Original=  10.9716% | Synthetic=  10.6323% | AbsDiff=   0.3393
Top 25 | Original=  19.4707% | Synthetic=  18.2232% | AbsDiff=   1.2475
Top 50 | Original=  29.0129% | Synthetic=  28.6861% | AbsDiff=   0.3268

================================================================================
11. SUMMARY
================================================================================
Original laundering rows : 5,177
Synthetic laundering rows: 5,067,991
Original median amount   : 8,667.210000
Synthetic median amount  : 1,465.920000
Original mean amount     : 36,135,310.412813
Synthetic mean amount    : 21,383,007.836351
Hour MAE                 : 1.040598 pp
Day-of-week MAE          : 1.741786 pp

====================================================================================================
✅ CELL 24 COMPLETE
====================================================================================================
Audit saved to:
/kaggle/working/AML_GNN_ONLY/data/HI-Small_original_laundering_vs_synthetic_laundering.json
====================================================================================================

In [41]:
# ==================================================================================================
# CELL 25 — TYPOLOGY-WISE LAUNDERING DNA AUDIT
#
# Compare:
#   ORIGINAL IBM PATTERN TRANSACTIONS
#          vs
#   SYNTHETIC TRANSACTIONS
#
# Broken down by:
#   BIPARTITE
#   CYCLE
#   FAN-IN
#   FAN-OUT
#   GATHER-SCATTER
#   RANDOM
#   SCATTER-GATHER
#   STACK
#
# This tells us exactly how the generator differs from the ORIGINAL laundering patterns.
#
# DOES NOT modify or regenerate data.
# ==================================================================================================

import os
import csv
import json
import math
from collections import Counter, defaultdict
from datetime import datetime


# --------------------------------------------------------------------------------------------------
# PATHS
# --------------------------------------------------------------------------------------------------

BASE = "/kaggle/working/AML_GNN_ONLY/data"

ORIGINAL_PATTERNS = (
    "/kaggle/input/datasets/"
    "ealtman2019/ibm-transactions-for-anti-money-laundering-aml/"
    "HI-Small_Patterns.txt"
)

SYNTHETIC_FILE = os.path.join(
    BASE,
    "HI-Small_SYNTH_FULL_transactions.csv"
)

OUT_JSON = os.path.join(
    BASE,
    "HI-Small_typology_wise_laundering_dna_audit.json"
)


TYPOLOGIES = [
    "BIPARTITE",
    "CYCLE",
    "FAN-IN",
    "FAN-OUT",
    "GATHER-SCATTER",
    "RANDOM",
    "SCATTER-GATHER",
    "STACK",
]


# --------------------------------------------------------------------------------------------------
# HELPERS
# --------------------------------------------------------------------------------------------------

def pct(x, total):

    return (
        100.0 * x / total
        if total
        else 0.0
    )


def parse_timestamp(x):

    x = x.strip()

    try:

        return datetime.strptime(
            x,
            "%Y/%m/%d %H:%M"
        )

    except Exception:

        return datetime.strptime(
            x,
            "%Y-%m-%d %H:%M:%S"
        )


def quantile(values, q):

    if not values:
        return None

    values = sorted(values)

    idx = int(
        q * (len(values) - 1)
    )

    return values[idx]


def new_typology_stats():

    return {
        "rows": 0,
        "amounts": [],
        "payment_format": Counter(),
        "payment_currency": Counter(),
        "receiving_currency": Counter(),
        "hour": Counter(),
        "day_of_week": Counter(),
        "source_banks": Counter(),
        "destination_banks": Counter(),
        "source_accounts": Counter(),
        "destination_accounts": Counter(),
    }


# --------------------------------------------------------------------------------------------------
# ORIGINAL IBM PATTERNS
# --------------------------------------------------------------------------------------------------

print("=" * 100)
print("CELL 25 — TYPOLOGY-WISE LAUNDERING DNA AUDIT")
print("=" * 100)

print("\n1. Reading ORIGINAL IBM Patterns.txt ...")


original = {
    typ: new_typology_stats()
    for typ in TYPOLOGIES
}


current_typology = None


with open(
    ORIGINAL_PATTERNS,
    "r",
    encoding="utf-8"
) as f:

    for raw in f:

        line = raw.strip()

        if not line:
            continue


        if line.startswith(
            "BEGIN LAUNDERING ATTEMPT"
        ):

            parts = line.split("-")

            # Robust extraction from:
            # BEGIN LAUNDERING ATTEMPT - FAN-OUT: ...
            typology_part = line.split(
                " - ",
                1
            )[1]

            current_typology = (
                typology_part
                .split(":")[0]
                .strip()
            )

            if current_typology not in original:

                current_typology = None

            continue


        if line.startswith(
            "END LAUNDERING ATTEMPT"
        ):

            current_typology = None
            continue


        # Ignore ID lines
        if line.startswith(
            'id="'
        ):

            continue


        if current_typology is None:
            continue


        parts = line.split(",")

        if len(parts) != 11:
            continue


        stats = original[
            current_typology
        ]


        stats["rows"] += 1


        # ----------------------------------------------------------------------
        # amount
        # ----------------------------------------------------------------------

        try:

            amount = float(
                parts[5]
            )

            if (
                math.isfinite(amount)
                and amount > 0
            ):

                stats[
                    "amounts"
                ].append(amount)

        except Exception:
            pass


        # ----------------------------------------------------------------------
        # categorical
        # ----------------------------------------------------------------------

        stats["payment_format"][
            parts[9].strip()
        ] += 1

        stats["payment_currency"][
            parts[8].strip()
        ] += 1

        stats["receiving_currency"][
            parts[6].strip()
        ] += 1


        # ----------------------------------------------------------------------
        # timestamp
        # ----------------------------------------------------------------------

        try:

            dt = parse_timestamp(
                parts[0]
            )

            stats["hour"][
                dt.hour
            ] += 1

            stats["day_of_week"][
                dt.strftime("%A")
            ] += 1

        except Exception:
            pass


        # ----------------------------------------------------------------------
        # bank/account
        # ----------------------------------------------------------------------

        src_bank = parts[1].strip()
        dst_bank = parts[3].strip()

        src_account = parts[2].strip()
        dst_account = parts[4].strip()


        stats["source_banks"][
            src_bank
        ] += 1

        stats["destination_banks"][
            dst_bank
        ] += 1

        stats["source_accounts"][
            src_account
        ] += 1

        stats["destination_accounts"][
            dst_account
        ] += 1


print("\nOriginal IBM pattern transaction counts:")

for typ in TYPOLOGIES:

    print(
        f"  {typ:18s} "
        f"{original[typ]['rows']:8,}"
    )


# --------------------------------------------------------------------------------------------------
# SYNTHETIC
# --------------------------------------------------------------------------------------------------

print("\n2. Streaming SYNTHETIC transactions ...")


synthetic = {
    typ: new_typology_stats()
    for typ in TYPOLOGIES
}


with open(
    SYNTHETIC_FILE,
    "r",
    newline="",
    encoding="utf-8"
) as f:

    reader = csv.DictReader(f)


    for row in reader:

        typology = row[
            "typology"
        ].strip().upper()


        if typology not in synthetic:
            continue


        stats = synthetic[
            typology
        ]


        stats["rows"] += 1


        # ----------------------------------------------------------------------
        # amount
        # ----------------------------------------------------------------------

        try:

            amount = float(
                row["Amount Received"]
            )

            if (
                math.isfinite(amount)
                and amount > 0
            ):

                stats[
                    "amounts"
                ].append(amount)

        except Exception:
            pass


        # ----------------------------------------------------------------------
        # categorical
        # ----------------------------------------------------------------------

        stats["payment_format"][
            row[
                "Payment Format"
            ].strip()
        ] += 1

        stats["payment_currency"][
            row[
                "Payment Currency"
            ].strip()
        ] += 1

        stats["receiving_currency"][
            row[
                "Receiving Currency"
            ].strip()
        ] += 1


        # ----------------------------------------------------------------------
        # timestamp
        # ----------------------------------------------------------------------

        try:

            dt = parse_timestamp(
                row["Timestamp"]
            )

            stats["hour"][
                dt.hour
            ] += 1

            stats["day_of_week"][
                dt.strftime("%A")
            ] += 1

        except Exception:
            pass


        # ----------------------------------------------------------------------
        # banks/accounts
        # ----------------------------------------------------------------------

        src_bank = row[
            "From Bank"
        ].strip()

        dst_bank = row[
            "To Bank"
        ].strip()

        src_account = row[
            "Account"
        ].strip()

        dst_account = row[
            "Account.1"
        ].strip()


        stats["source_banks"][
            src_bank
        ] += 1

        stats["destination_banks"][
            dst_bank
        ] += 1

        stats["source_accounts"][
            src_account
        ] += 1

        stats["destination_accounts"][
            dst_account
        ] += 1


# --------------------------------------------------------------------------------------------------
# BASIC COUNTS
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("3. TYPOLOGY COUNTS")
print("=" * 80)

for typ in TYPOLOGIES:

    print(
        f"{typ:18s} "
        f"| Original={original[typ]['rows']:9,} "
        f"| Synthetic={synthetic[typ]['rows']:10,}"
    )


# --------------------------------------------------------------------------------------------------
# AMOUNT COMPARISON
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("4. AMOUNT DISTRIBUTION BY TYPOLOGY")
print("=" * 80)


amount_quantiles = [
    0.10,
    0.25,
    0.50,
    0.75,
    0.90,
    0.95,
    0.99,
]


for typ in TYPOLOGIES:

    oa = original[typ]["amounts"]
    sa = synthetic[typ]["amounts"]


    if not oa or not sa:

        continue


    print(
        "\n"
        + typ
    )

    print(
        f"  {'Metric':10s} "
        f"{'Original':>18s} "
        f"{'Synthetic':>18s} "
        f"{'Ratio':>12s}"
    )


    for q in amount_quantiles:

        ov = quantile(
            oa,
            q
        )

        sv = quantile(
            sa,
            q
        )

        ratio = (
            sv / ov
            if ov != 0
            else None
        )


        print(
            f"  p{int(q*100):02d} "
            f"{ov:18.4f} "
            f"{sv:18.4f} "
            f"{ratio:12.4f}"
        )


# --------------------------------------------------------------------------------------------------
# PAYMENT FORMAT BY TYPOLOGY
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("5. PAYMENT FORMAT BY TYPOLOGY")
print("=" * 80)


for typ in TYPOLOGIES:

    print(
        f"\n[{typ}]"
    )


    all_formats = sorted(
        set(
            original[typ]["payment_format"]
        )
        |
        set(
            synthetic[typ]["payment_format"]
        )
    )


    for fmt in all_formats:

        op = pct(
            original[typ]["payment_format"].get(
                fmt,
                0
            ),
            original[typ]["rows"]
        )

        sp = pct(
            synthetic[typ]["payment_format"].get(
                fmt,
                0
            ),
            synthetic[typ]["rows"]
        )


        print(
            f"  {fmt:18s} "
            f"| Original={op:9.3f}% "
            f"| Synthetic={sp:9.3f}% "
            f"| AbsDiff={abs(op-sp):9.3f}"
        )


# --------------------------------------------------------------------------------------------------
# PAYMENT CURRENCY BY TYPOLOGY
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("6. PAYMENT CURRENCY BY TYPOLOGY")
print("=" * 80)


for typ in TYPOLOGIES:

    print(
        f"\n[{typ}]"
    )


    all_curr = sorted(
        set(
            original[typ]["payment_currency"]
        )
        |
        set(
            synthetic[typ]["payment_currency"]
        )
    )


    for curr in all_curr:

        op = pct(
            original[typ]["payment_currency"].get(
                curr,
                0
            ),
            original[typ]["rows"]
        )

        sp = pct(
            synthetic[typ]["payment_currency"].get(
                curr,
                0
            ),
            synthetic[typ]["rows"]
        )


        print(
            f"  {curr:20s} "
            f"| Original={op:9.3f}% "
            f"| Synthetic={sp:9.3f}% "
            f"| AbsDiff={abs(op-sp):9.3f}"
        )


# --------------------------------------------------------------------------------------------------
# RECEIVING CURRENCY BY TYPOLOGY
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("7. RECEIVING CURRENCY BY TYPOLOGY")
print("=" * 80)


for typ in TYPOLOGIES:

    print(
        f"\n[{typ}]"
    )


    all_curr = sorted(
        set(
            original[typ]["receiving_currency"]
        )
        |
        set(
            synthetic[typ]["receiving_currency"]
        )
    )


    for curr in all_curr:

        op = pct(
            original[typ]["receiving_currency"].get(
                curr,
                0
            ),
            original[typ]["rows"]
        )

        sp = pct(
            synthetic[typ]["receiving_currency"].get(
                curr,
                0
            ),
            synthetic[typ]["rows"]
        )


        print(
            f"  {curr:20s} "
            f"| Original={op:9.3f}% "
            f"| Synthetic={sp:9.3f}% "
            f"| AbsDiff={abs(op-sp):9.3f}"
        )


# --------------------------------------------------------------------------------------------------
# BANK / ACCOUNT DIVERSITY BY TYPOLOGY
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("8. BANK / ACCOUNT DIVERSITY BY TYPOLOGY")
print("=" * 80)


for typ in TYPOLOGIES:

    print(
        f"\n[{typ}]"
    )

    print(
        f"  Source banks      : "
        f"{len(original[typ]['source_banks']):8,} "
        f"-> "
        f"{len(synthetic[typ]['source_banks']):8,}"
    )

    print(
        f"  Destination banks : "
        f"{len(original[typ]['destination_banks']):8,} "
        f"-> "
        f"{len(synthetic[typ]['destination_banks']):8,}"
    )

    print(
        f"  Source accounts   : "
        f"{len(original[typ]['source_accounts']):8,} "
        f"-> "
        f"{len(synthetic[typ]['source_accounts']):8,}"
    )

    print(
        f"  Destination accounts:"
        f"{len(original[typ]['destination_accounts']):8,} "
        f"-> "
        f"{len(synthetic[typ]['destination_accounts']):8,}"
    )


# --------------------------------------------------------------------------------------------------
# DAY / HOUR BY TYPOLOGY
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 80)
print("9. TEMPORAL DNA BY TYPOLOGY")
print("=" * 80)


for typ in TYPOLOGIES:

    print(
        f"\n[{typ}]"
    )


    print(
        "  Hours:"
    )


    for h in range(24):

        ov = pct(
            original[typ]["hour"].get(
                h,
                0
            ),
            original[typ]["rows"]
        )

        sv = pct(
            synthetic[typ]["hour"].get(
                h,
                0
            ),
            synthetic[typ]["rows"]
        )


        if ov > 0 or sv > 0:

            print(
                f"    {h:02d}: "
                f"O={ov:7.3f}% "
                f"S={sv:7.3f}%"
            )


# --------------------------------------------------------------------------------------------------
# SAVE COMPACT JSON
# --------------------------------------------------------------------------------------------------

def compact_stats(stats):

    return {

        "rows":
            stats["rows"],

        "amount": {

            "mean":
                (
                    sum(stats["amounts"])
                    / len(stats["amounts"])
                    if stats["amounts"]
                    else None
                ),

            "median":
                quantile(
                    stats["amounts"],
                    0.50
                ),

            "p90":
                quantile(
                    stats["amounts"],
                    0.90
                ),

            "p95":
                quantile(
                    stats["amounts"],
                    0.95
                ),

            "p99":
                quantile(
                    stats["amounts"],
                    0.99
                ),
        },

        "payment_format":
            dict(
                stats["payment_format"]
            ),

        "payment_currency":
            dict(
                stats["payment_currency"]
            ),

        "receiving_currency":
            dict(
                stats["receiving_currency"]
            ),

        "unique_source_banks":
            len(stats["source_banks"]),

        "unique_destination_banks":
            len(stats["destination_banks"]),

        "unique_source_accounts":
            len(stats["source_accounts"]),

        "unique_destination_accounts":
            len(stats["destination_accounts"]),
    }


audit = {

    "original": {
        typ:
            compact_stats(
                original[typ]
            )
        for typ in TYPOLOGIES
    },

    "synthetic": {
        typ:
            compact_stats(
                synthetic[typ]
            )
        for typ in TYPOLOGIES
    },
}


with open(
    OUT_JSON,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        audit,
        f,
        indent=2
    )


# --------------------------------------------------------------------------------------------------
# FINAL
# --------------------------------------------------------------------------------------------------

print("\n" + "=" * 100)
print("✅ CELL 25 COMPLETE")
print("=" * 100)

print(
    f"Saved audit:\n{OUT_JSON}"
)

print("=" * 100)

====================================================================================================
CELL 25 — TYPOLOGY-WISE LAUNDERING DNA AUDIT
====================================================================================================

1. Reading ORIGINAL IBM Patterns.txt ...

Original IBM pattern transaction counts:
  BIPARTITE               263
  CYCLE                   287
  FAN-IN                  318
  FAN-OUT                 342
  GATHER-SCATTER          716
  RANDOM                  191
  SCATTER-GATHER          626
  STACK                   466

2. Streaming SYNTHETIC transactions ...

================================================================================
3. TYPOLOGY COUNTS
================================================================================
BIPARTITE          | Original=      263 | Synthetic=   415,357
CYCLE              | Original=      287 | Synthetic=   453,261
FAN-IN             | Original=      318 | Synthetic=   502,219
FAN-OUT            | Original=      342 | Synthetic=   540,123
GATHER-SCATTER     | Original=      716 | Synthetic= 1,130,782
RANDOM             | Original=      191 | Synthetic=   301,647
SCATTER-GATHER     | Original=      626 | Synthetic=   988,646
STACK              | Original=      466 | Synthetic=   735,956

================================================================================
4. AMOUNT DISTRIBUTION BY TYPOLOGY
================================================================================

BIPARTITE
  Metric               Original          Synthetic        Ratio
  p10          1848.7500            16.2600       0.0088
  p25          5710.1900           156.8916       0.0275
  p50         12601.6500          1656.0944       0.1314
  p75         26259.5300         22049.7314       0.8397
  p90        470886.9000        358515.2642       0.7614
  p95       1059468.1000       2028917.5766       1.9150
  p99      12248835.4000      78297254.8310       6.3922

CYCLE
  Metric               Original          Synthetic        Ratio
  p10          1461.8700            28.0720       0.0192
  p25          5606.5500           210.1012       0.0375
  p50         12020.1200          1868.8735       0.1555
  p75         22520.3100         19087.1900       0.8476
  p90         99938.5000        260194.2500       2.6035
  p95        986045.1000       1278308.1578       1.2964
  p99      12650338.1700      37143684.7365       2.9362

FAN-IN
  Metric               Original          Synthetic        Ratio
  p10          1549.1900            17.2531       0.0111
  p25          5223.3800           135.3466       0.0259
  p50         11316.1700          1155.1898       0.1021
  p75         16862.5600         11893.8081       0.7053
  p90         37493.0200        162175.1386       4.3255
  p95         68416.7200        878740.7234      12.8439
  p99       3510590.3800      28448761.7548       8.1037

FAN-OUT
  Metric               Original          Synthetic        Ratio
  p10          2541.5300            17.9868       0.0071
  p25          6845.6400           155.9242       0.0228
  p50         12582.3300          1547.1536       0.1230
  p75         24975.9500         18698.6941       0.7487
  p90        208413.7500        278032.5222       1.3340
  p95        823911.2400       1534494.2930       1.8625
  p99       1682320.0700      68900047.4615      40.9554

GATHER-SCATTER
  Metric               Original          Synthetic        Ratio
  p10          2024.6500            15.7202       0.0078
  p25          5897.0200           137.1606       0.0233
  p50         12427.9900          1308.3439       0.1053
  p75         19530.3600         15470.4522       0.7921
  p90        129476.4200        246974.0390       1.9075
  p95       1025648.8900       1551928.3939       1.5131
  p99      37215591.3800      63845228.3704       1.7156

RANDOM
  Metric               Original          Synthetic        Ratio
  p10          2266.1700            23.4626       0.0104
  p25          4511.5200           190.7519       0.0423
  p50         13044.8100          1677.3700       0.1286
  p75         20674.4100         17200.7229       0.8320
  p90       1105578.2700        228208.2065       0.2064
  p95       1539523.0200       1133823.3600       0.7365
  p99      29211025.7800      29513220.2593       1.0103

SCATTER-GATHER
  Metric               Original          Synthetic        Ratio
  p10          3176.7200            13.5764       0.0043
  p25          6870.0500           131.0679       0.0191
  p50         13811.5500          1370.9124       0.0993
  p75         46443.8000         17617.7572       0.3793
  p90        918374.4200        306419.4959       0.3337
  p95       1641584.8800       1892702.2052       1.1530
  p99      77189806.6700      73832540.5704       0.9565

STACK
  Metric               Original          Synthetic        Ratio
  p10          1831.3300            17.7930       0.0097
  p25          5478.9700           156.7457       0.0286
  p50         11866.5600          1636.2921       0.1379
  p75         18595.0300         22433.5977       1.2064
  p90        392562.5800        379759.9736       0.9674
  p95       1265627.0600       2120158.7230       1.6752
  p99      16706462.7200      83874756.7208       5.0205

================================================================================
5. PAYMENT FORMAT BY TYPOLOGY
================================================================================

[BIPARTITE]
  ACH                | Original=  100.000% | Synthetic=   12.178% | AbsDiff=   87.822
  Bitcoin            | Original=    0.000% | Synthetic=    2.901% | AbsDiff=    2.901
  Cash               | Original=    0.000% | Synthetic=    9.706% | AbsDiff=    9.706
  Cheque             | Original=    0.000% | Synthetic=   37.229% | AbsDiff=   37.229
  Credit Card        | Original=    0.000% | Synthetic=   25.876% | AbsDiff=   25.876
  Reinvestment       | Original=    0.000% | Synthetic=    8.685% | AbsDiff=    8.685
  Wire               | Original=    0.000% | Synthetic=    3.425% | AbsDiff=    3.425

[CYCLE]
  ACH                | Original=  100.000% | Synthetic=   12.117% | AbsDiff=   87.883
  Bitcoin            | Original=    0.000% | Synthetic=    2.896% | AbsDiff=    2.896
  Cash               | Original=    0.000% | Synthetic=    9.719% | AbsDiff=    9.719
  Cheque             | Original=    0.000% | Synthetic=   37.401% | AbsDiff=   37.401
  Credit Card        | Original=    0.000% | Synthetic=   25.813% | AbsDiff=   25.813
  Reinvestment       | Original=    0.000% | Synthetic=    8.642% | AbsDiff=    8.642
  Wire               | Original=    0.000% | Synthetic=    3.412% | AbsDiff=    3.412

[FAN-IN]
  ACH                | Original=  100.000% | Synthetic=   12.124% | AbsDiff=   87.876
  Bitcoin            | Original=    0.000% | Synthetic=    2.863% | AbsDiff=    2.863
  Cash               | Original=    0.000% | Synthetic=    9.625% | AbsDiff=    9.625
  Cheque             | Original=    0.000% | Synthetic=   37.395% | AbsDiff=   37.395
  Credit Card        | Original=    0.000% | Synthetic=   25.866% | AbsDiff=   25.866
  Reinvestment       | Original=    0.000% | Synthetic=    8.685% | AbsDiff=    8.685
  Wire               | Original=    0.000% | Synthetic=    3.441% | AbsDiff=    3.441

[FAN-OUT]
  ACH                | Original=  100.000% | Synthetic=   12.156% | AbsDiff=   87.844
  Bitcoin            | Original=    0.000% | Synthetic=    2.888% | AbsDiff=    2.888
  Cash               | Original=    0.000% | Synthetic=    9.600% | AbsDiff=    9.600
  Cheque             | Original=    0.000% | Synthetic=   37.410% | AbsDiff=   37.410
  Credit Card        | Original=    0.000% | Synthetic=   25.880% | AbsDiff=   25.880
  Reinvestment       | Original=    0.000% | Synthetic=    8.633% | AbsDiff=    8.633
  Wire               | Original=    0.000% | Synthetic=    3.433% | AbsDiff=    3.433

[GATHER-SCATTER]
  ACH                | Original=  100.000% | Synthetic=   12.114% | AbsDiff=   87.886
  Bitcoin            | Original=    0.000% | Synthetic=    2.902% | AbsDiff=    2.902
  Cash               | Original=    0.000% | Synthetic=    9.661% | AbsDiff=    9.661
  Cheque             | Original=    0.000% | Synthetic=   37.339% | AbsDiff=   37.339
  Credit Card        | Original=    0.000% | Synthetic=   25.872% | AbsDiff=   25.872
  Reinvestment       | Original=    0.000% | Synthetic=    8.676% | AbsDiff=    8.676
  Wire               | Original=    0.000% | Synthetic=    3.437% | AbsDiff=    3.437

[RANDOM]
  ACH                | Original=  100.000% | Synthetic=   12.238% | AbsDiff=   87.762
  Bitcoin            | Original=    0.000% | Synthetic=    2.942% | AbsDiff=    2.942
  Cash               | Original=    0.000% | Synthetic=    9.640% | AbsDiff=    9.640
  Cheque             | Original=    0.000% | Synthetic=   37.130% | AbsDiff=   37.130
  Credit Card        | Original=    0.000% | Synthetic=   25.954% | AbsDiff=   25.954
  Reinvestment       | Original=    0.000% | Synthetic=    8.665% | AbsDiff=    8.665
  Wire               | Original=    0.000% | Synthetic=    3.430% | AbsDiff=    3.430

[SCATTER-GATHER]
  ACH                | Original=  100.000% | Synthetic=   12.202% | AbsDiff=   87.798
  Bitcoin            | Original=    0.000% | Synthetic=    2.884% | AbsDiff=    2.884
  Cash               | Original=    0.000% | Synthetic=    9.655% | AbsDiff=    9.655
  Cheque             | Original=    0.000% | Synthetic=   37.421% | AbsDiff=   37.421
  Credit Card        | Original=    0.000% | Synthetic=   25.821% | AbsDiff=   25.821
  Reinvestment       | Original=    0.000% | Synthetic=    8.601% | AbsDiff=    8.601
  Wire               | Original=    0.000% | Synthetic=    3.416% | AbsDiff=    3.416

[STACK]
  ACH                | Original=   99.785% | Synthetic=   12.167% | AbsDiff=   87.618
  Bitcoin            | Original=    0.215% | Synthetic=    2.877% | AbsDiff=    2.663
  Cash               | Original=    0.000% | Synthetic=    9.663% | AbsDiff=    9.663
  Cheque             | Original=    0.000% | Synthetic=   37.295% | AbsDiff=   37.295
  Credit Card        | Original=    0.000% | Synthetic=   25.913% | AbsDiff=   25.913
  Reinvestment       | Original=    0.000% | Synthetic=    8.649% | AbsDiff=    8.649
  Wire               | Original=    0.000% | Synthetic=    3.435% | AbsDiff=    3.435

================================================================================
6. PAYMENT CURRENCY BY TYPOLOGY
================================================================================

[BIPARTITE]
  Australian Dollar    | Original=    1.141% | Synthetic=    2.686% | AbsDiff=    1.546
  Bitcoin              | Original=    0.000% | Synthetic=    2.907% | AbsDiff=    2.907
  Brazil Real          | Original=    0.000% | Synthetic=    1.390% | AbsDiff=    1.390
  Canadian Dollar      | Original=    2.281% | Synthetic=    2.880% | AbsDiff=    0.598
  Euro                 | Original=   32.319% | Synthetic=   22.865% | AbsDiff=    9.454
  Mexican Peso         | Original=    2.281% | Synthetic=    2.214% | AbsDiff=    0.067
  Ruble                | Original=    4.183% | Synthetic=    3.110% | AbsDiff=    1.073
  Rupee                | Original=    3.802% | Synthetic=    3.638% | AbsDiff=    0.165
  Saudi Riyal          | Original=   12.167% | Synthetic=    1.780% | AbsDiff=   10.387
  Shekel               | Original=    0.760% | Synthetic=    3.876% | AbsDiff=    3.116
  Swiss Franc          | Original=    1.521% | Synthetic=    4.714% | AbsDiff=    3.193
  UK Pound             | Original=    2.662% | Synthetic=    3.693% | AbsDiff=    1.031
  US Dollar            | Original=   30.798% | Synthetic=   36.942% | AbsDiff=    6.143
  Yen                  | Original=    2.281% | Synthetic=    3.100% | AbsDiff=    0.818
  Yuan                 | Original=    3.802% | Synthetic=    4.206% | AbsDiff=    0.403

[CYCLE]
  Australian Dollar    | Original=    2.091% | Synthetic=    2.694% | AbsDiff=    0.603
  Bitcoin              | Original=    0.000% | Synthetic=    2.873% | AbsDiff=    2.873
  Brazil Real          | Original=    0.697% | Synthetic=    1.424% | AbsDiff=    0.727
  Canadian Dollar      | Original=    0.697% | Synthetic=    2.855% | AbsDiff=    2.158
  Euro                 | Original=   25.784% | Synthetic=   22.770% | AbsDiff=    3.014
  Mexican Peso         | Original=    1.394% | Synthetic=    2.203% | AbsDiff=    0.809
  Ruble                | Original=    2.787% | Synthetic=    3.110% | AbsDiff=    0.323
  Rupee                | Original=    3.833% | Synthetic=    3.661% | AbsDiff=    0.172
  Saudi Riyal          | Original=   14.634% | Synthetic=    1.750% | AbsDiff=   12.885
  Shekel               | Original=    1.045% | Synthetic=    3.864% | AbsDiff=    2.819
  Swiss Franc          | Original=    2.439% | Synthetic=    4.724% | AbsDiff=    2.285
  UK Pound             | Original=    2.439% | Synthetic=    3.715% | AbsDiff=    1.276
  US Dollar            | Original=   37.631% | Synthetic=   37.061% | AbsDiff=    0.570
  Yen                  | Original=    1.394% | Synthetic=    3.134% | AbsDiff=    1.740
  Yuan                 | Original=    3.136% | Synthetic=    4.163% | AbsDiff=    1.027

[FAN-IN]
  Australian Dollar    | Original=    3.459% | Synthetic=    2.660% | AbsDiff=    0.799
  Bitcoin              | Original=    0.000% | Synthetic=    2.916% | AbsDiff=    2.916
  Brazil Real          | Original=    0.000% | Synthetic=    1.389% | AbsDiff=    1.389
  Canadian Dollar      | Original=    5.031% | Synthetic=    2.829% | AbsDiff=    2.203
  Euro                 | Original=   38.994% | Synthetic=   22.798% | AbsDiff=   16.195
  Mexican Peso         | Original=    0.000% | Synthetic=    2.222% | AbsDiff=    2.222
  Ruble                | Original=    0.000% | Synthetic=    3.113% | AbsDiff=    3.113
  Rupee                | Original=    0.000% | Synthetic=    3.647% | AbsDiff=    3.647
  Saudi Riyal          | Original=   11.321% | Synthetic=    1.789% | AbsDiff=    9.532
  Shekel               | Original=    0.000% | Synthetic=    3.891% | AbsDiff=    3.891
  Swiss Franc          | Original=    3.774% | Synthetic=    4.751% | AbsDiff=    0.977
  UK Pound             | Original=    0.000% | Synthetic=    3.621% | AbsDiff=    3.621
  US Dollar            | Original=   34.906% | Synthetic=   37.061% | AbsDiff=    2.155
  Yen                  | Original=    0.000% | Synthetic=    3.101% | AbsDiff=    3.101
  Yuan                 | Original=    2.516% | Synthetic=    4.213% | AbsDiff=    1.697

[FAN-OUT]
  Australian Dollar    | Original=    2.924% | Synthetic=    2.655% | AbsDiff=    0.269
  Bitcoin              | Original=    0.000% | Synthetic=    2.865% | AbsDiff=    2.865
  Brazil Real          | Original=    1.462% | Synthetic=    1.428% | AbsDiff=    0.034
  Canadian Dollar      | Original=    0.585% | Synthetic=    2.839% | AbsDiff=    2.254
  Euro                 | Original=   29.825% | Synthetic=   22.999% | AbsDiff=    6.826
  Mexican Peso         | Original=    2.924% | Synthetic=    2.212% | AbsDiff=    0.712
  Ruble                | Original=    3.509% | Synthetic=    3.092% | AbsDiff=    0.417
  Rupee                | Original=    2.632% | Synthetic=    3.660% | AbsDiff=    1.028
  Saudi Riyal          | Original=   12.573% | Synthetic=    1.791% | AbsDiff=   10.783
  Shekel               | Original=    1.462% | Synthetic=    3.858% | AbsDiff=    2.396
  Swiss Franc          | Original=    3.216% | Synthetic=    4.725% | AbsDiff=    1.509
  UK Pound             | Original=    2.047% | Synthetic=    3.685% | AbsDiff=    1.638
  US Dollar            | Original=   31.287% | Synthetic=   36.933% | AbsDiff=    5.646
  Yen                  | Original=    2.047% | Synthetic=    3.087% | AbsDiff=    1.040
  Yuan                 | Original=    3.509% | Synthetic=    4.173% | AbsDiff=    0.664

[GATHER-SCATTER]
  Australian Dollar    | Original=    2.095% | Synthetic=    2.678% | AbsDiff=    0.583
  Bitcoin              | Original=    0.000% | Synthetic=    2.883% | AbsDiff=    2.883
  Brazil Real          | Original=    0.279% | Synthetic=    1.414% | AbsDiff=    1.135
  Canadian Dollar      | Original=    2.793% | Synthetic=    2.860% | AbsDiff=    0.067
  Euro                 | Original=   22.346% | Synthetic=   22.848% | AbsDiff=    0.502
  Mexican Peso         | Original=    2.095% | Synthetic=    2.223% | AbsDiff=    0.128
  Ruble                | Original=    0.978% | Synthetic=    3.125% | AbsDiff=    2.147
  Rupee                | Original=    1.536% | Synthetic=    3.675% | AbsDiff=    2.139
  Saudi Riyal          | Original=   11.732% | Synthetic=    1.799% | AbsDiff=    9.933
  Shekel               | Original=    0.419% | Synthetic=    3.840% | AbsDiff=    3.421
  Swiss Franc          | Original=    4.190% | Synthetic=    4.703% | AbsDiff=    0.513
  UK Pound             | Original=    3.073% | Synthetic=    3.629% | AbsDiff=    0.557
  US Dollar            | Original=   41.061% | Synthetic=   37.069% | AbsDiff=    3.992
  Yen                  | Original=    3.352% | Synthetic=    3.102% | AbsDiff=    0.250
  Yuan                 | Original=    4.050% | Synthetic=    4.152% | AbsDiff=    0.101

[RANDOM]
  Australian Dollar    | Original=    2.094% | Synthetic=    2.669% | AbsDiff=    0.574
  Bitcoin              | Original=    0.000% | Synthetic=    2.859% | AbsDiff=    2.859
  Brazil Real          | Original=    0.000% | Synthetic=    1.384% | AbsDiff=    1.384
  Canadian Dollar      | Original=    3.141% | Synthetic=    2.855% | AbsDiff=    0.286
  Euro                 | Original=   29.319% | Synthetic=   22.895% | AbsDiff=    6.424
  Mexican Peso         | Original=    3.141% | Synthetic=    2.199% | AbsDiff=    0.942
  Ruble                | Original=    2.094% | Synthetic=    3.067% | AbsDiff=    0.973
  Rupee                | Original=    4.712% | Synthetic=    3.629% | AbsDiff=    1.083
  Saudi Riyal          | Original=   12.565% | Synthetic=    1.781% | AbsDiff=   10.785
  Shekel               | Original=    0.524% | Synthetic=    3.857% | AbsDiff=    3.334
  Swiss Franc          | Original=    2.618% | Synthetic=    4.642% | AbsDiff=    2.024
  UK Pound             | Original=    1.571% | Synthetic=    3.594% | AbsDiff=    2.024
  US Dollar            | Original=   31.414% | Synthetic=   37.201% | AbsDiff=    5.788
  Yen                  | Original=    2.094% | Synthetic=    3.138% | AbsDiff=    1.044
  Yuan                 | Original=    4.712% | Synthetic=    4.228% | AbsDiff=    0.484

[SCATTER-GATHER]
  Australian Dollar    | Original=    2.236% | Synthetic=    2.676% | AbsDiff=    0.439
  Bitcoin              | Original=    0.000% | Synthetic=    2.876% | AbsDiff=    2.876
  Brazil Real          | Original=    1.597% | Synthetic=    1.401% | AbsDiff=    0.196
  Canadian Dollar      | Original=    1.917% | Synthetic=    2.855% | AbsDiff=    0.938
  Euro                 | Original=   20.607% | Synthetic=   22.816% | AbsDiff=    2.209
  Mexican Peso         | Original=    0.799% | Synthetic=    2.218% | AbsDiff=    1.419
  Ruble                | Original=    3.035% | Synthetic=    3.143% | AbsDiff=    0.108
  Rupee                | Original=    6.390% | Synthetic=    3.660% | AbsDiff=    2.729
  Saudi Riyal          | Original=    8.147% | Synthetic=    1.796% | AbsDiff=    6.351
  Shekel               | Original=    0.479% | Synthetic=    3.886% | AbsDiff=    3.406
  Swiss Franc          | Original=    5.431% | Synthetic=    4.680% | AbsDiff=    0.751
  UK Pound             | Original=    0.958% | Synthetic=    3.653% | AbsDiff=    2.695
  US Dollar            | Original=   40.735% | Synthetic=   37.033% | AbsDiff=    3.702
  Yen                  | Original=    4.952% | Synthetic=    3.112% | AbsDiff=    1.840
  Yuan                 | Original=    2.716% | Synthetic=    4.194% | AbsDiff=    1.479

[STACK]

In [43]:
# ============================================================
# CELL 26A — LOCATE FINAL ORIGINAL + FINAL BALANCED FILE
# ============================================================

import os

# ------------------------------------------------------------
# SEARCH ALL CSV FILES
# ------------------------------------------------------------

SEARCH_DIRS = [
    "/kaggle/working",
    "/kaggle/input"
]

matches = []

for base_dir in SEARCH_DIRS:
    for root, dirs, files in os.walk(base_dir):
        for fname in files:
            if fname.lower().endswith(".csv"):
                path = os.path.join(root, fname)

                if (
                    "hi-small" in fname.lower()
                    or "final" in fname.lower()
                    or "transactions" in fname.lower()
                ):
                    matches.append(path)

print("=" * 80)
print("POSSIBLE HI-SMALL / FINAL CSV FILES")
print("=" * 80)

for p in sorted(matches):
    size_mb = os.path.getsize(p) / (1024 ** 2)
    print(f"{size_mb:10.2f} MB | {p}")

# ------------------------------------------------------------
# IDENTIFY FILES
# ------------------------------------------------------------

ORIG_PATH = None
FINAL_TX_PATH = None

for p in matches:

    fname = os.path.basename(p).lower()

    # Original IBM HI-Small transactions
    if fname == "hi-small_trans.csv":
        ORIG_PATH = p

    # Our final 50:50 merged transactions
    if (
        "hi-small_final_transactions_10146336" in fname
        or (
            "hi-small_final" in fname
            and "transactions" in fname
        )
    ):
        FINAL_TX_PATH = p

print("\n" + "=" * 80)
print("SELECTED FILES")
print("=" * 80)

print("ORIGINAL:")
print(ORIG_PATH)

print("\nFINAL BALANCED:")
print(FINAL_TX_PATH)

# ------------------------------------------------------------
# VALIDATE PATHS
# ------------------------------------------------------------

if ORIG_PATH is None:
    raise FileNotFoundError(
        "Original HI-Small_Trans.csv was not found."
    )

if FINAL_TX_PATH is None:
    raise FileNotFoundError(
        "HI-Small_FINAL_transactions_10146336.csv was not found. "
        "Check whether the final merged file is attached to this Kaggle session."
    )

# ------------------------------------------------------------
# BASIC FILE INFO
# ------------------------------------------------------------

orig_size = os.path.getsize(ORIG_PATH) / (1024 ** 2)
final_size = os.path.getsize(FINAL_TX_PATH) / (1024 ** 2)

print("\n" + "=" * 80)
print("FILE VALIDATION")
print("=" * 80)

print(f"Original file size : {orig_size:,.2f} MB")
print(f"Final file size    : {final_size:,.2f} MB")

print("\n✅ Original file located")
print("✅ Final balanced transaction file located")
print("\nNow we can run the sample-size-adjusted amount audit.")

================================================================================
POSSIBLE HI-SMALL / FINAL CSV FILES
================================================================================
    453.63 MB | /kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml/HI-Small_Trans.csv
     32.48 MB | /kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml/HI-Small_accounts.csv
     60.82 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_FINAL_accounts_1004953.csv
   1409.24 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_FINAL_transactions_10146336.csv
     43.50 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_SYNTH_FULL_episode_audit.csv
     27.85 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_SYNTH_FULL_new_accounts.csv
    844.22 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_SYNTH_FULL_transactions.csv
      0.33 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_SYNTH_PILOT_V2_episode_audit.csv
      0.25 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_SYNTH_PILOT_V2_new_accounts.csv
      7.25 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_SYNTH_PILOT_V2_transactions.csv
      0.23 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_SYNTH_PILOT_new_accounts.csv
      7.27 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_SYNTH_PILOT_transactions.csv
      0.00 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_SYNTH_full_morphology_summary.csv
      0.00 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_SYNTH_vs_ORIGINAL_behavioral_dna_summary.csv
      0.00 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_account_id_position_types.csv
      0.26 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_accounts_per_bank.csv
      0.28 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_bank_account_prefix_behavior.csv
      1.09 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_bank_id_canonical_mapping.csv
      0.00 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_behavior_account_activity_buckets.csv
      0.90 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_behavior_accounts_per_bank.csv
      0.00 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_behavior_bank_activity_buckets.csv
      0.11 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_behavior_top_laundering_source_accounts.csv
     16.44 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_behavior_top_legitimate_source_accounts.csv
     16.23 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_behavior_top_source_accounts.csv
      3.12 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_final_generator_bank_pool.csv
     56.08 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_generator_account_registry.csv
      0.01 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_legitimate_bank_mapping_summary.csv
      5.26 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_legitimate_bank_pairs.csv
      0.00 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_original_account_character_classes.csv
      0.00 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_original_account_length_distribution.csv
      0.00 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_original_bank_length_distribution.csv
     10.58 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_original_bank_pair_distribution.csv
      0.00 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_original_daily_distribution.csv
     13.83 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_original_destination_account_distribution.csv
      0.94 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_original_from_bank_distribution.csv
      0.00 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_original_hour_distribution.csv
      0.00 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_original_pattern_dna_episode_sizes.csv
      0.11 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_original_pattern_dna_episodes.csv
      0.00 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_original_pattern_dna_node_roles.csv
      0.02 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_original_pattern_dna_signatures.csv
      0.00 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_original_pattern_dna_typologies.csv
      0.00 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_original_payment_currency_distribution.csv
      0.00 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_original_payment_format_distribution.csv
      0.00 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_original_receiving_currency_distribution.csv
     16.23 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_original_source_account_distribution.csv
      0.48 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_original_to_bank_distribution.csv
      0.00 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_original_weekday_distribution.csv
      0.02 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_pattern_template_summary.csv
      2.09 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_real_bank_registry.csv
     30.19 MB | /kaggle/working/AML_GNN_ONLY/data/HI-Small_synthetic_episode_plan.csv

================================================================================
SELECTED FILES
================================================================================
ORIGINAL:
/kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml/HI-Small_Trans.csv

FINAL BALANCED:
/kaggle/working/AML_GNN_ONLY/data/HI-Small_FINAL_transactions_10146336.csv

================================================================================
FILE VALIDATION
================================================================================
Original file size : 453.63 MB
Final file size    : 1,409.24 MB

✅ Original file located
✅ Final balanced transaction file located

Now we can run the sample-size-adjusted amount audit.

In [44]:
# ============================================================
# CELL 26B — SAMPLE-SIZE-ADJUSTED LAUNDERING AMOUNT AUDIT
# ============================================================

import os
import numpy as np
import pandas as pd

from scipy.stats import ks_2samp, wasserstein_distance

# ------------------------------------------------------------
# PATHS
# ------------------------------------------------------------

ORIG_PATH = (
    "/kaggle/input/datasets/ealtman2019/"
    "ibm-transactions-for-anti-money-laundering-aml/"
    "HI-Small_Trans.csv"
)

SYN_PATH = (
    "/kaggle/working/AML_GNN_ONLY/data/"
    "HI-Small_SYNTH_FULL_transactions.csv"
)

print("Original :", ORIG_PATH)
print("Synthetic:", SYN_PATH)

assert os.path.exists(ORIG_PATH), "Original file not found"
assert os.path.exists(SYN_PATH), "Synthetic file not found"


# ------------------------------------------------------------
# 1. LOAD ORIGINAL LAUNDERING AMOUNTS ONLY
# ------------------------------------------------------------

print("\nLoading original laundering amounts...")

orig = pd.read_csv(
    ORIG_PATH,
    usecols=[5, 10],
    header=0
)

orig.columns = ["Amount", "Is_Laundering"]

orig["Amount"] = pd.to_numeric(
    orig["Amount"],
    errors="coerce"
)

orig["Is_Laundering"] = pd.to_numeric(
    orig["Is_Laundering"],
    errors="coerce"
)

orig_laundering = (
    orig.loc[
        orig["Is_Laundering"] == 1,
        "Amount"
    ]
    .dropna()
    .to_numpy(dtype=np.float64)
)

orig_laundering = orig_laundering[
    orig_laundering > 0
]

del orig

print(
    f"Original laundering transactions: "
    f"{len(orig_laundering):,}"
)


# ------------------------------------------------------------
# 2. LOAD SYNTHETIC LAUNDERING AMOUNTS
# ------------------------------------------------------------

print("\nLoading synthetic laundering amounts...")

# Synthetic file is large, so read only Amount column.
syn_chunks = []

for chunk in pd.read_csv(
    SYN_PATH,
    usecols=[5],
    header=0,
    chunksize=500_000
):
    chunk.columns = ["Amount"]

    vals = pd.to_numeric(
        chunk["Amount"],
        errors="coerce"
    ).dropna().to_numpy(dtype=np.float64)

    vals = vals[vals > 0]

    syn_chunks.append(vals)

    print(
        f"  Loaded {sum(len(x) for x in syn_chunks):,} "
        f"synthetic amounts",
        end="\r"
    )

synthetic_laundering = np.concatenate(
    syn_chunks
)

del syn_chunks

print(
    f"\nSynthetic laundering transactions: "
    f"{len(synthetic_laundering):,}"
)


# ------------------------------------------------------------
# 3. SANITY CHECK
# ------------------------------------------------------------

EXPECTED_ORIGINAL = 5_177
EXPECTED_SYNTHETIC = 5_067_991

if len(orig_laundering) != EXPECTED_ORIGINAL:
    print(
        f"⚠️ Original count differs from expected "
        f"{EXPECTED_ORIGINAL:,}"
    )
else:
    print("✅ Original laundering count exact")

if len(synthetic_laundering) != EXPECTED_SYNTHETIC:
    print(
        f"⚠️ Synthetic count differs from expected "
        f"{EXPECTED_SYNTHETIC:,}"
    )
else:
    print("✅ Synthetic laundering count exact")


# ------------------------------------------------------------
# 4. RAW-SCALE QUANTILES
# ------------------------------------------------------------

q_names = [
    "P01", "P05", "P10", "P25",
    "P50", "P75", "P90", "P95", "P99"
]

q_values = [1, 5, 10, 25, 50, 75, 90, 95, 99]

orig_q = np.percentile(
    orig_laundering,
    q_values
)

syn_q = np.percentile(
    synthetic_laundering,
    q_values
)

raw_rows = []

for name, oq, sq in zip(q_names, orig_q, syn_q):

    raw_rows.append({
        "Quantile": name,
        "Original": oq,
        "Synthetic": sq,
        "Synthetic_to_Original_Ratio":
            sq / oq if oq != 0 else np.nan
    })

raw_qdf = pd.DataFrame(raw_rows)

print("\n" + "=" * 90)
print("RAW AMOUNT DISTRIBUTION")
print("=" * 90)

print(
    raw_qdf.to_string(
        index=False,
        formatters={
            "Original": "{:,.4f}".format,
            "Synthetic": "{:,.4f}".format,
            "Synthetic_to_Original_Ratio":
                "{:.4f}".format
        }
    )
)


# ------------------------------------------------------------
# 5. SUMMARY STATISTICS
# ------------------------------------------------------------

summary_stats = pd.DataFrame({
    "Metric": [
        "Count",
        "Mean",
        "Median",
        "Std",
        "Minimum",
        "Maximum"
    ],
    "Original": [
        len(orig_laundering),
        np.mean(orig_laundering),
        np.median(orig_laundering),
        np.std(orig_laundering),
        np.min(orig_laundering),
        np.max(orig_laundering)
    ],
    "Synthetic": [
        len(synthetic_laundering),
        np.mean(synthetic_laundering),
        np.median(synthetic_laundering),
        np.std(synthetic_laundering),
        np.min(synthetic_laundering),
        np.max(synthetic_laundering)
    ]
})

print("\n" + "=" * 90)
print("SUMMARY STATISTICS")
print("=" * 90)

print(
    summary_stats.to_string(
        index=False,
        formatters={
            "Original": "{:,.6f}".format,
            "Synthetic": "{:,.6f}".format
        }
    )
)


# ------------------------------------------------------------
# 6. LOG-SPACE DISTRIBUTIONS
# ------------------------------------------------------------

orig_log = np.log10(orig_laundering)
syn_log = np.log10(synthetic_laundering)

full_ks = ks_2samp(
    orig_log,
    syn_log,
    alternative="two-sided"
).statistic

full_wd = wasserstein_distance(
    orig_log,
    syn_log
)

print("\n" + "=" * 90)
print("FULL DISTRIBUTION DISTANCE")
print("=" * 90)

print(f"KS statistic                     : {full_ks:.6f}")
print(f"Wasserstein distance (log10)     : {full_wd:.6f}")


# ------------------------------------------------------------
# 7. SAME-SIZE BOOTSTRAP
# ------------------------------------------------------------

N = len(orig_log)
N_BOOT = 200

rng = np.random.default_rng(42)

ks_orig_syn = []
wd_orig_syn = []

ks_syn_syn = []
wd_syn_syn = []

bootstrap_quantiles = {
    q: []
    for q in q_names
}

print("\nRunning same-size bootstrap...")

for b in range(N_BOOT):

    # Same number of synthetic transactions as
    # the original laundering population.
    syn_idx_1 = rng.choice(
        len(synthetic_laundering),
        size=N,
        replace=False
    )

    syn_sample_1 = synthetic_laundering[
        syn_idx_1
    ]

    syn_log_1 = np.log10(syn_sample_1)

    # Independent synthetic sample
    syn_idx_2 = rng.choice(
        len(synthetic_laundering),
        size=N,
        replace=False
    )

    syn_sample_2 = synthetic_laundering[
        syn_idx_2
    ]

    syn_log_2 = np.log10(syn_sample_2)

    # --------------------------------------------
    # Original vs Synthetic
    # --------------------------------------------

    ks_orig_syn.append(
        ks_2samp(
            orig_log,
            syn_log_1
        ).statistic
    )

    wd_orig_syn.append(
        wasserstein_distance(
            orig_log,
            syn_log_1
        )
    )

    # --------------------------------------------
    # Synthetic vs Synthetic
    # --------------------------------------------

    ks_syn_syn.append(
        ks_2samp(
            syn_log_1,
            syn_log_2
        ).statistic
    )

    wd_syn_syn.append(
        wasserstein_distance(
            syn_log_1,
            syn_log_2
        )
    )

    # --------------------------------------------
    # Synthetic quantiles
    # --------------------------------------------

    sample_q = np.percentile(
        syn_sample_1,
        q_values
    )

    for name, value in zip(
        q_names,
        sample_q
    ):
        bootstrap_quantiles[name].append(value)

    if (b + 1) % 25 == 0:
        print(
            f"  Bootstrap {b + 1}/{N_BOOT}"
        )


# ------------------------------------------------------------
# 8. DISTANCE COMPARISON
# ------------------------------------------------------------

ks_orig_median = np.median(ks_orig_syn)
ks_orig_low = np.percentile(
    ks_orig_syn,
    2.5
)
ks_orig_high = np.percentile(
    ks_orig_syn,
    97.5
)

wd_orig_median = np.median(wd_orig_syn)
wd_orig_low = np.percentile(
    wd_orig_syn,
    2.5
)
wd_orig_high = np.percentile(
    wd_orig_syn,
    97.5
)

ks_syn_median = np.median(ks_syn_syn)
ks_syn_p95 = np.percentile(
    ks_syn_syn,
    95
)

wd_syn_median = np.median(wd_syn_syn)
wd_syn_p95 = np.percentile(
    wd_syn_syn,
    95
)

print("\n" + "=" * 90)
print("SAME-SIZE SAMPLE EFFECT")
print("=" * 90)

print(
    f"Synthetic vs Synthetic KS median : "
    f"{ks_syn_median:.6f}"
)

print(
    f"Synthetic vs Synthetic KS P95    : "
    f"{ks_syn_p95:.6f}"
)

print(
    f"Original vs Synthetic KS median  : "
    f"{ks_orig_median:.6f}"
)

print(
    f"Original vs Synthetic KS 95% CI  : "
    f"[{ks_orig_low:.6f}, {ks_orig_high:.6f}]"
)

print()

print(
    f"Synthetic vs Synthetic WD median : "
    f"{wd_syn_median:.6f}"
)

print(
    f"Synthetic vs Synthetic WD P95    : "
    f"{wd_syn_p95:.6f}"
)

print(
    f"Original vs Synthetic WD median  : "
    f"{wd_orig_median:.6f}"
)

print(
    f"Original vs Synthetic WD 95% CI  : "
    f"[{wd_orig_low:.6f}, {wd_orig_high:.6f}]"
)


# ------------------------------------------------------------
# 9. SAME-SIZE QUANTILE INTERVALS
# ------------------------------------------------------------

rows = []

for name, oq in zip(
    q_names,
    orig_q
):

    vals = np.array(
        bootstrap_quantiles[name]
    )

    median_val = np.median(vals)
    low_val = np.percentile(
        vals,
        2.5
    )
    high_val = np.percentile(
        vals,
        97.5
    )

    rows.append({
        "Quantile": name,
        "Original": oq,
        "Synthetic_Median": median_val,
        "Synthetic_2.5pct": low_val,
        "Synthetic_97.5pct": high_val,
        "Synthetic_to_Original":
            median_val / oq
            if oq != 0 else np.nan,
        "Original_inside_95pct":
            low_val <= oq <= high_val
    })

boot_qdf = pd.DataFrame(rows)

print("\n" + "=" * 90)
print("SAME-SIZE QUANTILE BOOTSTRAP")
print("=" * 90)

print(
    boot_qdf.to_string(
        index=False,
        formatters={
            "Original": "{:,.4f}".format,
            "Synthetic_Median": "{:,.4f}".format,
            "Synthetic_2.5pct": "{:,.4f}".format,
            "Synthetic_97.5pct": "{:,.4f}".format,
            "Synthetic_to_Original":
                "{:.4f}".format
        }
    )
)


# ------------------------------------------------------------
# 10. COUNT HOW MANY QUANTILES ARE OUTSIDE
# ------------------------------------------------------------

outside_count = (
    ~boot_qdf["Original_inside_95pct"]
).sum()

print("\n" + "=" * 90)
print("QUANTILE OVERLAP RESULT")
print("=" * 90)

print(
    f"Original quantiles outside synthetic "
    f"95% intervals: "
    f"{outside_count}/{len(boot_qdf)}"
)


# ------------------------------------------------------------
# 11. FINAL AUTOMATIC DIAGNOSIS
# ------------------------------------------------------------

print("\n" + "=" * 90)
print("AUTOMATIC DIAGNOSIS")
print("=" * 90)

distance_ratio = (
    ks_orig_median / ks_syn_p95
    if ks_syn_p95 > 0 else np.inf
)

if outside_count <= 2 and distance_ratio <= 1.5:

    print(
        "🟢 AMOUNT DISTRIBUTION IS REASONABLY CONSISTENT."
    )
    print(
        "Most quantile differences are compatible with "
        "sample-size variation."
    )

elif outside_count <= 4:

    print(
        "🟡 MODERATE AMOUNT-DISTRIBUTION MISMATCH."
    )
    print(
        "Some differences appear systematic, but the "
        "distributions are not completely disconnected."
    )

else:

    print(
        "🔴 CLEAR AMOUNT-DISTRIBUTION MISMATCH."
    )
    print(
        "The synthetic amount distribution differs from "
        "the original laundering population beyond "
        "ordinary same-size sampling variation."
    )

print("\n✅ CELL 26B COMPLETE")


# ------------------------------------------------------------
# 12. SAVE RESULTS
# ------------------------------------------------------------

summary_stats.to_csv(
    "/kaggle/working/amount_distribution_summary.csv",
    index=False
)

raw_qdf.to_csv(
    "/kaggle/working/amount_distribution_raw_quantiles.csv",
    index=False
)

boot_qdf.to_csv(
    "/kaggle/working/amount_distribution_bootstrap_quantiles.csv",
    index=False
)

pd.DataFrame({
    "Metric": [
        "Full_KS",
        "Full_Wasserstein_log10",
        "SameSize_SYN_SYN_KS_Median",
        "SameSize_SYN_SYN_KS_P95",
        "ORIG_SYN_KS_Median",
        "ORIG_SYN_KS_95pct_Low",
        "ORIG_SYN_KS_95pct_High",
        "SameSize_SYN_SYN_WD_Median",
        "SameSize_SYN_SYN_WD_P95",
        "ORIG_SYN_WD_Median",
        "Original_Quantiles_Outside_95pct"
    ],
    "Value": [
        full_ks,
        full_wd,
        ks_syn_median,
        ks_syn_p95,
        ks_orig_median,
        ks_orig_low,
        ks_orig_high,
        wd_syn_median,
        wd_syn_p95,
        wd_orig_median,
        outside_count
    ]
}).to_csv(
    "/kaggle/working/amount_distribution_distance_summary.csv",
    index=False
)

print("\nSaved audit files:")
print("  amount_distribution_summary.csv")
print("  amount_distribution_raw_quantiles.csv")
print("  amount_distribution_bootstrap_quantiles.csv")
print("  amount_distribution_distance_summary.csv")

Original : /kaggle/input/datasets/ealtman2019/ibm-transactions-for-anti-money-laundering-aml/HI-Small_Trans.csv
Synthetic: /kaggle/working/AML_GNN_ONLY/data/HI-Small_SYNTH_FULL_transactions.csv

Loading original laundering amounts...
Original laundering transactions: 5,177

Loading synthetic laundering amounts...
  Loaded 468,825 synthetic amounts
Synthetic laundering transactions: 468,825
✅ Original laundering count exact
⚠️ Synthetic count differs from expected 5,067,991

==========================================================================================
RAW AMOUNT DISTRIBUTION
==========================================================================================
Quantile        Original                                                                                                                                                                                                                                                                Synthetic                                                                                                                                                                       Synthetic_to_Original_Ratio
     P01          1.0000                                                                                                                                                                                                                                                           8,001,037.0000                                                                                                                                                                                      8001020.0378
     P05        213.9700                                                                                                                                                                                                                                                           8,049,625.0000                                                                                                                                                                                        37620.3440
     P10        673.1480                                                                                                                                                                                                                                                         100,786,714.0000                                                                                                                                                                                       149724.4499
     P25      2,634.9700                                                                                                                                                                                                                                                         801,605,730.0000                                                                                                                                                                                       304218.1619
     P50      8,667.2100                                                                                                                                                                                                                                                         805,176,000.0000                                                                                                                                                                                        92899.0990
     P75     18,832.2700                                                                                                                                                                                                                                                         810,437,340.0000                                                                                                                                                                                        43034.5009
     P90    171,438.2920                                                                                                                                                                                                                                               8,010,910,000,000,000.0000                                                                                                                                                                                  46727658719.3249
     P95    943,718.0220                                                                                                                                                                             807,643,799,999,999,815,923,789,943,560,810,904,681,947,345,948,331,490,289,112,842,240.0000                                                                                                                                 855810508194367176201056036562304474938912463238550410756096.0000
     P99 23,420,046.8380 805,090,000,000,000,114,380,608,063,407,684,401,619,944,822,145,014,798,362,413,429,635,015,378,806,515,584,947,102,476,549,145,314,654,518,757,701,306,489,521,222,208,549,975,165,139,040,986,901,242,395,539,945,849,794,555,576,896,881,993,261,661,804,298,240.0000 34376105460801854321751956503488023953651018108002377311570921512776211144136186002998878019382273604547518315866319075308646192925680653923654328970840654017756634338992250075807941132288.0000

==========================================================================================
SUMMARY STATISTICS
==========================================================================================
 Metric              Original                                                                                                                                                                                                                                                                                                                                                                                                                     Synthetic
  Count          5,177.000000                                                                                                                                                                                                                                                                                                                                                                                                                468,825.000000
   Mean     36,135,310.412813     41,096,933,836,457,543,835,691,594,072,912,293,374,813,576,363,946,482,725,760,067,681,459,915,300,608,260,965,485,475,914,959,075,509,489,665,987,967,894,144,955,588,762,252,371,423,487,616,034,284,362,603,889,065,440,776,028,683,368,305,410,407,770,052,293,631,395,038,650,212,023,443,683,955,587,666,871,703,913,036,143,753,727,917,800,921,911,579,076,655,792,081,632,006,906,469,223,285,160,673,280.000000
 Median          8,667.210000                                                                                                                                                                                                                                                                                                                                                                                                            805,176,000.000000
    Std  1,527,771,094.710159                                                                                                                                                                                                                                                                                                                                                                                                                           inf
Minimum              0.003227                                                                                                                                                                                                                                                                                                                                                                                                                    810.000000
Maximum 84,853,144,179.580002 81,480,000,000,000,005,653,281,102,554,309,938,340,088,298,277,720,845,951,933,227,826,509,660,011,714,055,288,055,459,383,496,856,616,852,695,329,548,771,419,303,136,554,387,629,360,363,938,102,296,349,683,527,446,710,534,991,946,412,649,840,695,410,225,000,233,774,124,343,967,837,122,417,838,813,692,507,079,936,709,602,389,515,986,003,106,147,497,226,723,988,978,272,586,852,181,215,826,539,832,147,968.000000

==========================================================================================
FULL DISTRIBUTION DISTANCE
==========================================================================================
KS statistic                     : 0.971204
Wasserstein distance (log10)     : 12.487966

Running same-size bootstrap...

/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:188: RuntimeWarning: overflow encountered in multiply
  x = um.multiply(x, x, out=x)

  Bootstrap 25/200
  Bootstrap 50/200
  Bootstrap 75/200
  Bootstrap 100/200
  Bootstrap 125/200
  Bootstrap 150/200
  Bootstrap 175/200
  Bootstrap 200/200

==========================================================================================
SAME-SIZE SAMPLE EFFECT
==========================================================================================
Synthetic vs Synthetic KS median : 0.016805
Synthetic vs Synthetic KS P95    : 0.025546
Original vs Synthetic KS median  : 0.971122
Original vs Synthetic KS 95% CI  : [0.968515, 0.973735]

Synthetic vs Synthetic WD median : 0.555801
Synthetic vs Synthetic WD P95    : 1.073852
Original vs Synthetic WD median  : 12.463797
Original vs Synthetic WD 95% CI  : [11.713539, 13.420070]

==========================================================================================
SAME-SIZE QUANTILE BOOTSTRAP
==========================================================================================
Quantile        Original                                                                                                                                                                                                                                                         Synthetic_Median                                                                                                                                                                                                                 Synthetic_2.5pct                                                                                                                                                                                                                                                                                                Synthetic_97.5pct                                                                                                                                                                             Synthetic_to_Original  Original_inside_95pct
     P01          1.0000                                                                                                                                                                                                                                                           8,001,037.3200                                                                                                                                                                                                                     811,430.9030                                                                                                                                                                                                                                                                                                   8,003,187.0310                                                                                                                                                                                      8001020.3578                  False
     P05        213.9700                                                                                                                                                                                                                                                           8,049,915.1000                                                                                                                                                                                                                   8,040,824.9400                                                                                                                                                                                                                                                                                                   8,060,612.2550                                                                                                                                                                                        37621.6998                  False
     P10        673.1480                                                                                                                                                                                                                                                         100,824,863.0000                                                                                                                                                                                                                  81,366,644.6000                                                                                                                                                                                                                                                                                                 800,128,097.7000                                                                                                                                                                                       149781.1224                  False
     P25      2,634.9700                                                                                                                                                                                                                                                         801,607,730.0000                                                                                                                                                                                                                 801,465,242.0000                                                                                                                                                                                                                                                                                                 801,727,382.5000                                                                                                                                                                                       304218.9209                  False
     P50      8,667.2100                                                                                                                                                                                                                                                         805,181,465.0000                                                                                                                                                                                                                 804,964,620.0000                                                                                                                                                                                                                                                                                                 805,382,685.0000                                                                                                                                                                                        92899.7296                  False
     P75     18,832.2700                                                                                                                                                                                                                                                         810,462,255.0000                                                                                                                                                                                                                 810,169,572.2500                                                                                                                                                                                                                                                                                                 810,745,054.2500                                                                                                                                                                                        43035.8239                  False
     P90    171,438.2920                                                                                                                                                                                                                                               8,007,383,000,000,000.0000                                                                                                                                                                                                                 814,736,253.1050                                                                                                                                                                                                                                                                          80,097,880,000,000,003,986,685,952.0000                                                                                                                                                                                  46707085719.2159                  False
     P95    943,718.0220                                                                                                                                                                             806,791,599,999,999,935,324,364,098,166,845,570,981,542,495,001,490,279,100,250,587,136.0000                                                                                                                                     800,150,804,999,999,917,509,818,741,314,539,909,170,525,348,193,756,328,604,003,729,408.0000                                                                                                                                                                                                       8,012,347,400,000,000,591,631,633,952,645,153,711,522,354,375,606,685,389,066,850,496,325,196,185,600.0000                                                                                                                                 854907484218843370590650075405290771250206745665025968439296.0000                  False
     P99 23,420,046.8380 804,192,799,999,999,074,981,083,095,331,140,980,751,055,663,534,522,922,036,866,977,653,870,917,934,488,881,278,282,299,626,542,111,365,709,507,987,931,450,093,094,595,780,641,861,336,547,711,207,032,396,593,594,942,221,310,453,054,308,793,506,793,894,445,056.0000 806,956,949,999,999,854,191,926,760,025,895,974,508,361,641,017,059,174,699,199,982,298,194,218,910,782,796,678,003,963,093,309,971,642,756,769,053,615,834,976,129,699,214,271,233,100,036,704,556,189,278,507,427,168,256.0000 805,407,159,999,998,772,966,322,590,372,812,083,547,825,249,458,382,918,949,134,176,913,690,756,055,763,613,330,014,040,355,150,892,001,429,300,671,176,489,680,912,743,150,674,547,743,443,595,789,795,435,161,760,971,857,943,301,096,065,458,947,838,897,290,075,984,529,417,479,976,637,217,512,620,032.0000 34337796399927337361060277049106709061463254133347423046957498720629822398820827031823840310973892800188243593641560547829282554400275573818240466888199284902777695345327669592661730263040.0000                  False

==========================================================================================
QUANTILE OVERLAP RESULT
==========================================================================================
Original quantiles outside synthetic 95% intervals: 9/9

==========================================================================================
AUTOMATIC DIAGNOSIS
==========================================================================================
🔴 CLEAR AMOUNT-DISTRIBUTION MISMATCH.
The synthetic amount distribution differs from the original laundering population beyond ordinary same-size sampling variation.

✅ CELL 26B COMPLETE

Saved audit files:
  amount_distribution_summary.csv
  amount_distribution_raw_quantiles.csv
  amount_distribution_bootstrap_quantiles.csv
  amount_distribution_distance_summary.csv

In [46]:
# ============================================================
# CELL 26C — CORRECT AMOUNT DISTRIBUTION AUDIT
# Reads "Amount Received" by COLUMN NAME
# ============================================================

import numpy as np
import pandas as pd
from scipy.stats import ks_2samp, wasserstein_distance

ORIG_PATH = (
    "/kaggle/input/datasets/ealtman2019/"
    "ibm-transactions-for-anti-money-laundering-aml/"
    "HI-Small_Trans.csv"
)

SYN_PATH = (
    "/kaggle/working/AML_GNN_ONLY/data/"
    "HI-Small_SYNTH_FULL_transactions.csv"
)

# ------------------------------------------------------------
# 1. ORIGINAL — LAUNDERING ONLY
# ------------------------------------------------------------

print("=" * 90)
print("CELL 26C — CORRECT AMOUNT AUDIT")
print("=" * 90)

print("\nLoading original laundering transactions...")

orig_parts = []

for chunk in pd.read_csv(
    ORIG_PATH,
    usecols=["Amount Received", "Is Laundering"],
    chunksize=500_000,
    low_memory=False
):

    chunk["Amount Received"] = pd.to_numeric(
        chunk["Amount Received"],
        errors="coerce"
    )

    chunk["Is Laundering"] = pd.to_numeric(
        chunk["Is Laundering"],
        errors="coerce"
    )

    vals = chunk.loc[
        chunk["Is Laundering"] == 1,
        "Amount Received"
    ].dropna()

    vals = vals[vals > 0]

    orig_parts.append(
        vals.to_numpy(dtype=np.float64)
    )

orig_amounts = np.concatenate(orig_parts)

del orig_parts

print(
    f"Original laundering amounts: "
    f"{len(orig_amounts):,}"
)


# ------------------------------------------------------------
# 2. SYNTHETIC — AMOUNT RECEIVED
# ------------------------------------------------------------

print("\nLoading synthetic laundering amounts...")

syn_parts = []

for chunk_no, chunk in enumerate(
    pd.read_csv(
        SYN_PATH,
        usecols=["Amount Received"],
        chunksize=500_000,
        low_memory=False
    ),
    start=1
):

    vals = pd.to_numeric(
        chunk["Amount Received"],
        errors="coerce"
    ).dropna()

    vals = vals[vals > 0]

    syn_parts.append(
        vals.to_numpy(dtype=np.float64)
    )

    loaded = sum(
        len(x) for x in syn_parts
    )

    print(
        f"  Chunk {chunk_no:02d} | "
        f"loaded {loaded:,}",
        end="\r"
    )

synthetic_amounts = np.concatenate(
    syn_parts
)

del syn_parts

print(
    f"\nSynthetic amounts: "
    f"{len(synthetic_amounts):,}"
)


# ------------------------------------------------------------
# 3. EXPECTED COUNTS
# ------------------------------------------------------------

print("\n" + "=" * 90)
print("COUNT CHECK")
print("=" * 90)

print(f"Original expected : 5,177")
print(f"Original actual   : {len(orig_amounts):,}")

print(f"Synthetic expected: 5,067,991")
print(f"Synthetic actual  : {len(synthetic_amounts):,}")

assert len(orig_amounts) == 5_177, (
    f"Original laundering count mismatch: "
    f"{len(orig_amounts):,}"
)

assert len(synthetic_amounts) == 5_067_991, (
    f"Synthetic amount count mismatch: "
    f"{len(synthetic_amounts):,}"
)

print("\n✅ Counts exactly match expected values")


# ------------------------------------------------------------
# 4. BASIC STATISTICS
# ------------------------------------------------------------

def stats_array(x):

    return {
        "Count": len(x),
        "Mean": np.mean(x),
        "Median": np.median(x),
        "Std": np.std(x),
        "Min": np.min(x),
        "Max": np.max(x),
        "P01": np.percentile(x, 1),
        "P05": np.percentile(x, 5),
        "P10": np.percentile(x, 10),
        "P25": np.percentile(x, 25),
        "P50": np.percentile(x, 50),
        "P75": np.percentile(x, 75),
        "P90": np.percentile(x, 90),
        "P95": np.percentile(x, 95),
        "P99": np.percentile(x, 99),
    }


orig_stats = stats_array(orig_amounts)
syn_stats = stats_array(synthetic_amounts)

stat_df = pd.DataFrame({
    "Metric": list(orig_stats.keys()),
    "Original_Laundering": list(orig_stats.values()),
    "Synthetic_Laundering": [
        syn_stats[k]
        for k in orig_stats.keys()
    ]
})

print("\n" + "=" * 90)
print("CORRECT AMOUNT STATISTICS")
print("=" * 90)

print(
    stat_df.to_string(
        index=False,
        formatters={
            "Original_Laundering": "{:,.6f}".format,
            "Synthetic_Laundering": "{:,.6f}".format
        }
    )
)


# ------------------------------------------------------------
# 5. QUANTILE RATIOS
# ------------------------------------------------------------

quantiles = [
    1, 5, 10, 25, 50,
    75, 90, 95, 99
]

rows = []

for q in quantiles:

    oq = np.percentile(
        orig_amounts,
        q
    )

    sq = np.percentile(
        synthetic_amounts,
        q
    )

    rows.append({
        "Quantile": f"P{q:02d}",
        "Original": oq,
        "Synthetic": sq,
        "Synthetic_to_Original_Ratio":
            sq / oq if oq != 0 else np.nan
    })

quantile_df = pd.DataFrame(rows)

print("\n" + "=" * 90)
print("CORRECT QUANTILE COMPARISON")
print("=" * 90)

print(
    quantile_df.to_string(
        index=False,
        formatters={
            "Original": "{:,.4f}".format,
            "Synthetic": "{:,.4f}".format,
            "Synthetic_to_Original_Ratio":
                "{:.4f}".format
        }
    )
)


# ------------------------------------------------------------
# 6. LOG-SPACE FULL DISTRIBUTION TEST
# ------------------------------------------------------------

orig_log = np.log10(orig_amounts)
syn_log = np.log10(synthetic_amounts)

ks_full = ks_2samp(
    orig_log,
    syn_log
).statistic

wd_full = wasserstein_distance(
    orig_log,
    syn_log
)

print("\n" + "=" * 90)
print("FULL DISTRIBUTION DISTANCE")
print("=" * 90)

print(
    f"KS statistic                  : "
    f"{ks_full:.6f}"
)

print(
    f"Wasserstein distance (log10) : "
    f"{wd_full:.6f}"
)


# ------------------------------------------------------------
# 7. SAME-SIZE SAMPLING TEST
# ------------------------------------------------------------

N = len(orig_amounts)
BOOT = 200

rng = np.random.default_rng(42)

ks_orig_syn = []
wd_orig_syn = []

ks_syn_syn = []
wd_syn_syn = []

for i in range(BOOT):

    a = rng.choice(
        synthetic_amounts,
        size=N,
        replace=False
    )

    b = rng.choice(
        synthetic_amounts,
        size=N,
        replace=False
    )

    a_log = np.log10(a)
    b_log = np.log10(b)

    ks_orig_syn.append(
        ks_2samp(
            orig_log,
            a_log
        ).statistic
    )

    wd_orig_syn.append(
        wasserstein_distance(
            orig_log,
            a_log
        )
    )

    ks_syn_syn.append(
        ks_2samp(
            a_log,
            b_log
        ).statistic
    )

    wd_syn_syn.append(
        wasserstein_distance(
            a_log,
            b_log
        )
    )

    if (i + 1) % 25 == 0:
        print(
            f"Bootstrap {i + 1}/{BOOT}"
        )


# ------------------------------------------------------------
# 8. DISTANCE SUMMARY
# ------------------------------------------------------------

print("\n" + "=" * 90)
print("SAME-SIZE SAMPLE EFFECT")
print("=" * 90)

print(
    f"Synthetic vs Synthetic KS median : "
    f"{np.median(ks_syn_syn):.6f}"
)

print(
    f"Synthetic vs Synthetic KS P95    : "
    f"{np.percentile(ks_syn_syn, 95):.6f}"
)

print(
    f"Original vs Synthetic KS median  : "
    f"{np.median(ks_orig_syn):.6f}"
)

print(
    f"Original vs Synthetic KS 95% CI  : "
    f"[{np.percentile(ks_orig_syn, 2.5):.6f}, "
    f"{np.percentile(ks_orig_syn, 97.5):.6f}]"
)

print()

print(
    f"Synthetic vs Synthetic WD median : "
    f"{np.median(wd_syn_syn):.6f}"
)

print(
    f"Synthetic vs Synthetic WD P95    : "
    f"{np.percentile(wd_syn_syn, 95):.6f}"
)

print(
    f"Original vs Synthetic WD median  : "
    f"{np.median(wd_orig_syn):.6f}"
)

print(
    f"Original vs Synthetic WD 95% CI  : "
    f"[{np.percentile(wd_orig_syn, 2.5):.6f}, "
    f"{np.percentile(wd_orig_syn, 97.5):.6f}]"
)


# ------------------------------------------------------------
# 9. DIRECT SAME-SIZE QUANTILE BOOTSTRAP
# ------------------------------------------------------------

boot_rows = []

for q in quantiles:

    original_q = np.percentile(
        orig_amounts,
        q
    )

    values = []

    for _ in range(BOOT):

        sample = rng.choice(
            synthetic_amounts,
            size=N,
            replace=False
        )

        values.append(
            np.percentile(
                sample,
                q
            )
        )

    values = np.asarray(values)

    low = np.percentile(
        values,
        2.5
    )

    med = np.median(values)

    high = np.percentile(
        values,
        97.5
    )

    boot_rows.append({
        "Quantile": f"P{q:02d}",
        "Original": original_q,
        "Synthetic_Median": med,
        "Synthetic_2.5pct": low,
        "Synthetic_97.5pct": high,
        "Ratio": med / original_q
            if original_q != 0 else np.nan,
        "Original_inside_95pct":
            low <= original_q <= high
    })

boot_df = pd.DataFrame(
    boot_rows
)

print("\n" + "=" * 90)
print("SAME-SIZE QUANTILE BOOTSTRAP")
print("=" * 90)

print(
    boot_df.to_string(
        index=False,
        formatters={
            "Original": "{:,.4f}".format,
            "Synthetic_Median": "{:,.4f}".format,
            "Synthetic_2.5pct": "{:,.4f}".format,
            "Synthetic_97.5pct": "{:,.4f}".format,
            "Ratio": "{:.4f}".format
        }
    )
)


# ------------------------------------------------------------
# 10. FINAL INTERPRETATION
# ------------------------------------------------------------

outside = (
    ~boot_df["Original_inside_95pct"]
).sum()

print("\n" + "=" * 90)
print("FINAL DIAGNOSIS")
print("=" * 90)

print(
    f"Original quantiles outside synthetic "
    f"95% intervals: {outside}/9"
)

if outside <= 2:
    print(
        "🟢 AMOUNT DISTRIBUTION IS REASONABLY CLOSE."
    )
    print(
        "The remaining differences are largely "
        "compatible with sampling variation."
    )

elif outside <= 4:
    print(
        "🟡 MODERATE AMOUNT DISTRIBUTION DIFFERENCE."
    )
    print(
        "Some amount characteristics may need tuning."
    )

else:
    print(
        "🔴 GENUINE AMOUNT DISTRIBUTION MISMATCH."
    )
    print(
        "The synthetic generator's amount behavior should "
        "be improved before final model training."
    )


# ------------------------------------------------------------
# 11. SAVE
# ------------------------------------------------------------

stat_df.to_csv(
    "/kaggle/working/amount_audit_corrected_statistics.csv",
    index=False
)

quantile_df.to_csv(
    "/kaggle/working/amount_audit_corrected_quantiles.csv",
    index=False
)

boot_df.to_csv(
    "/kaggle/working/amount_audit_corrected_bootstrap.csv",
    index=False
)

print("\n✅ CELL 26C COMPLETE")

==========================================================================================
CELL 26C — CORRECT AMOUNT AUDIT
==========================================================================================

Loading original laundering transactions...
Original laundering amounts: 5,177

Loading synthetic laundering amounts...
  Chunk 11 | loaded 5,067,991
Synthetic amounts: 5,067,991

==========================================================================================
COUNT CHECK
==========================================================================================
Original expected : 5,177
Original actual   : 5,177
Synthetic expected: 5,067,991
Synthetic actual  : 5,067,991

✅ Counts exactly match expected values

==========================================================================================
CORRECT AMOUNT STATISTICS
==========================================================================================
Metric   Original_Laundering  Synthetic_Laundering
 Count          5,177.000000      5,067,991.000000
  Mean     36,135,310.412813     21,383,007.836351
Median          8,667.210000          1,465.920000
   Std  1,527,771,094.710159    584,454,802.649593
   Min              0.003227              0.000001
   Max 84,853,144,179.580002 25,747,762,666.419998
   P01              1.000002              0.014793
   P05            213.970000              3.413659
   P10            673.148000             17.142333
   P25          2,634.970000            150.798097
   P50          8,667.210000          1,465.920000
   P75         18,832.270000         17,584.730237
   P90        171,438.292000        276,577.693457
   P95        943,718.022000      1,575,623.564910
   P99     23,420,046.838000     59,921,433.366666

==========================================================================================
CORRECT QUANTILE COMPARISON
==========================================================================================
Quantile        Original       Synthetic Synthetic_to_Original_Ratio
     P01          1.0000          0.0148                      0.0148
     P05        213.9700          3.4137                      0.0160
     P10        673.1480         17.1423                      0.0255
     P25      2,634.9700        150.7981                      0.0572
     P50      8,667.2100      1,465.9200                      0.1691
     P75     18,832.2700     17,584.7302                      0.9338
     P90    171,438.2920    276,577.6935                      1.6133
     P95    943,718.0220  1,575,623.5649                      1.6696
     P99 23,420,046.8380 59,921,433.3667                      2.5586

==========================================================================================
FULL DISTRIBUTION DISTANCE
==========================================================================================
KS statistic                  : 0.336737
Wasserstein distance (log10) : 0.815273
Bootstrap 25/200
Bootstrap 50/200
Bootstrap 75/200
Bootstrap 100/200
Bootstrap 125/200
Bootstrap 150/200
Bootstrap 175/200
Bootstrap 200/200

==========================================================================================
SAME-SIZE SAMPLE EFFECT
==========================================================================================
Synthetic vs Synthetic KS median : 0.016226
Synthetic vs Synthetic KS P95    : 0.025720
Original vs Synthetic KS median  : 0.337068
Original vs Synthetic KS 95% CI  : [0.323928, 0.350985]

Synthetic vs Synthetic WD median : 0.045436
Synthetic vs Synthetic WD P95    : 0.076649
Original vs Synthetic WD median  : 0.817695
Original vs Synthetic WD 95% CI  : [0.784507, 0.847097]

==========================================================================================
SAME-SIZE QUANTILE BOOTSTRAP
==========================================================================================
Quantile        Original Synthetic_Median Synthetic_2.5pct Synthetic_97.5pct  Ratio  Original_inside_95pct
     P01          1.0000           0.0148           0.0088            0.0282 0.0148                  False
     P05        213.9700           3.4392           2.3593            4.6843 0.0161                  False
     P10        673.1480          17.1507          14.0777           20.6190 0.0255                  False
     P25      2,634.9700         151.7703         132.7783          170.9947 0.0576                  False
     P50      8,667.2100       1,460.8537       1,334.6584        1,672.0197 0.1685                  False
     P75     18,832.2700      17,550.5925      15,182.3884       20,045.2835 0.9319                   True
     P90    171,438.2920     275,259.8585     221,772.9014      339,558.5379 1.6056                  False
     P95    943,718.0220   1,555,306.6040   1,187,490.8180    2,014,302.5085 1.6481                  False
     P99 23,420,046.8380  56,904,858.8743  34,669,589.0928   94,537,261.9499 2.4298                  False

==========================================================================================
FINAL DIAGNOSIS
==========================================================================================
Original quantiles outside synthetic 95% intervals: 8/9
🔴 GENUINE AMOUNT DISTRIBUTION MISMATCH.
The synthetic generator's amount behavior should be improved before final model training.

✅ CELL 26C COMPLETE

In [47]:
# ============================================================
# CELL 28 — AMOUNT CALIBRATION OF SYNTHETIC LAUNDERING
# ============================================================
#
# Purpose:
#   Transform synthetic Amount Received/Amount Paid so that
#   their marginal monetary distribution follows the ORIGINAL
#   HI-Small laundering distribution.
#
# Important:
#   - NO graph changes
#   - NO account changes
#   - NO bank changes
#   - NO timestamp changes
#   - NO episode changes
#   - NO typology changes
#   - Only amount fields are calibrated
#
# Method:
#   Empirical quantile mapping in log10 space.
#
# ============================================================

import os
import csv
import numpy as np
import pandas as pd

# ------------------------------------------------------------
# PATHS
# ------------------------------------------------------------

ORIG_PATH = (
    "/kaggle/input/datasets/ealtman2019/"
    "ibm-transactions-for-anti-money-laundering-aml/"
    "HI-Small_Trans.csv"
)

SYN_PATH = (
    "/kaggle/working/AML_GNN_ONLY/data/"
    "HI-Small_SYNTH_FULL_transactions.csv"
)

OUT_PATH = (
    "/kaggle/working/AML_GNN_ONLY/data/"
    "HI-Small_SYNTH_FULL_V2_transactions.csv"
)

print("=" * 90)
print("CELL 28 — AMOUNT CALIBRATION")
print("=" * 90)


# ------------------------------------------------------------
# 1. LOAD ORIGINAL LAUNDERING AMOUNTS
# ------------------------------------------------------------

print("\n[1/6] Loading original laundering amounts...")

orig_parts = []

for chunk in pd.read_csv(
    ORIG_PATH,
    usecols=[5, 10],
    chunksize=500_000,
    low_memory=False
):

    chunk_amount = pd.to_numeric(
        chunk.iloc[:, 0],
        errors="coerce"
    )

    laundering = pd.to_numeric(
        chunk.iloc[:, 1],
        errors="coerce"
    )

    vals = chunk_amount[
        laundering == 1
    ].dropna()

    vals = vals[
        vals > 0
    ]

    orig_parts.append(
        vals.to_numpy(dtype=np.float64)
    )

original_laundering = np.concatenate(
    orig_parts
)

del orig_parts

assert len(original_laundering) == 5_177

original_laundering.sort()

original_log = np.log10(
    original_laundering
)

print(
    f"Original laundering amounts: "
    f"{len(original_laundering):,}"
)


# ------------------------------------------------------------
# 2. LOAD ALL SYNTHETIC AMOUNT RECEIVED VALUES
# ------------------------------------------------------------

print("\n[2/6] Loading synthetic Amount Received...")

synthetic_amount_parts = []

for chunk_id, chunk in enumerate(
    pd.read_csv(
        SYN_PATH,
        usecols=["Amount Received"],
        chunksize=500_000,
        low_memory=False
    ),
    start=1
):

    vals = pd.to_numeric(
        chunk["Amount Received"],
        errors="coerce"
    ).to_numpy(dtype=np.float64)

    synthetic_amount_parts.append(vals)

    loaded = sum(
        len(x) for x in synthetic_amount_parts
    )

    print(
        f"  chunk {chunk_id:02d} | "
        f"{loaded:,} rows",
        end="\r"
    )

synthetic_amounts = np.concatenate(
    synthetic_amount_parts
)

del synthetic_amount_parts

assert len(synthetic_amounts) == 5_067_991

print(
    f"\nSynthetic amounts: "
    f"{len(synthetic_amounts):,}"
)


# ------------------------------------------------------------
# 3. CLEAN + SORT SYNTHETIC AMOUNTS
# ------------------------------------------------------------

print("\n[3/6] Preparing empirical quantile mapping...")

if not np.all(np.isfinite(synthetic_amounts)):
    raise ValueError(
        "Synthetic Amount Received contains non-finite values."
    )

if np.any(synthetic_amounts <= 0):
    raise ValueError(
        "Synthetic Amount Received contains zero/negative values."
    )

synthetic_log_sorted = np.sort(
    np.log10(synthetic_amounts)
)

N_SYN = len(synthetic_log_sorted)
N_ORIG = len(original_log)

# Empirical probabilities associated with
# the original laundering distribution.
orig_u = (
    np.arange(N_ORIG) + 0.5
) / N_ORIG

# ------------------------------------------------------------
# 4. REPORT CURRENT VS TARGET
# ------------------------------------------------------------

print("\nCurrent synthetic amount distribution:")
print(
    f"  P01  : {np.percentile(synthetic_amounts, 1):,.4f}"
)
print(
    f"  P10  : {np.percentile(synthetic_amounts, 10):,.4f}"
)
print(
    f"  P50  : {np.percentile(synthetic_amounts, 50):,.4f}"
)
print(
    f"  P90  : {np.percentile(synthetic_amounts, 90):,.4f}"
)
print(
    f"  P99  : {np.percentile(synthetic_amounts, 99):,.4f}"
)

print("\nTarget original laundering distribution:")
print(
    f"  P01  : {np.percentile(original_laundering, 1):,.4f}"
)
print(
    f"  P10  : {np.percentile(original_laundering, 10):,.4f}"
)
print(
    f"  P50  : {np.percentile(original_laundering, 50):,.4f}"
)
print(
    f"  P90  : {np.percentile(original_laundering, 90):,.4f}"
)
print(
    f"  P99  : {np.percentile(original_laundering, 99):,.4f}"
)


# ------------------------------------------------------------
# 5. MAP EACH SYNTHETIC AMOUNT TO TARGET DISTRIBUTION
# ------------------------------------------------------------

def calibrate_amounts(
    values,
    sorted_log_values,
    target_log_values,
    target_u
):

    values = np.asarray(
        values,
        dtype=np.float64
    )

    log_values = np.log10(
        values
    )

    # Find empirical CDF position.
    left = np.searchsorted(
        sorted_log_values,
        log_values,
        side="left"
    )

    right = np.searchsorted(
        sorted_log_values,
        log_values,
        side="right"
    )

    # Mid-rank handles duplicate amounts more fairly.
    rank = (
        (left.astype(np.float64) +
         right.astype(np.float64))
        / 2.0
    )

    # Convert rank to probability.
    u = (
        (rank + 0.5)
        / len(sorted_log_values)
    )

    # Keep strictly within interpolation range.
    u = np.clip(
        u,
        target_u[0],
        target_u[-1]
    )

    # Piecewise-linear quantile mapping
    # performed in log10 space.
    mapped_log = np.interp(
        u,
        target_u,
        target_log_values
    )

    mapped = np.power(
        10.0,
        mapped_log
    )

    mapped = np.maximum(
        mapped,
        1e-6
    )

    return mapped


# Test the transformation on a small sample first.

test_sample = synthetic_amounts[:100_000]

test_mapped = calibrate_amounts(
    test_sample,
    synthetic_log_sorted,
    original_log,
    orig_u
)

if not np.all(
    np.isfinite(test_mapped)
):
    raise ValueError(
        "Calibration produced non-finite amounts."
    )

if np.any(test_mapped <= 0):
    raise ValueError(
        "Calibration produced non-positive amounts."
    )

print("\n✅ Calibration function passed sanity check")


# ------------------------------------------------------------
# 6. STREAM-REWRITE COMPLETE SYNTHETIC FILE
# ------------------------------------------------------------

print("\n[4/6] Rewriting calibrated synthetic file...")
print(f"Output: {OUT_PATH}")

# Remove previous partial output if present.
if os.path.exists(OUT_PATH):
    os.remove(OUT_PATH)

total_rows = 0

with open(
    SYN_PATH,
    "r",
    encoding="utf-8",
    errors="replace",
    newline=""
) as fin, open(
    OUT_PATH,
    "w",
    encoding="utf-8",
    newline=""
) as fout:

    reader = csv.reader(fin)
    writer = csv.writer(fout)

    header = next(reader)

    # Locate fields by name.
    try:
        received_idx = header.index(
            "Amount Received"
        )
    except ValueError:
        raise ValueError(
            "Amount Received column not found."
        )

    try:
        paid_idx = header.index(
            "Amount Paid"
        )
    except ValueError:
        raise ValueError(
            "Amount Paid column not found."
        )

    writer.writerow(header)

    # Process rows in Python batches so that the
    # calibration itself stays vectorized.

    BATCH_SIZE = 100_000

    rows_buffer = []
    received_buffer = []
    paid_buffer = []

    def flush_batch():

        nonlocal_dummy = None

    # Manual batch loop.
    for row in reader:

        rows_buffer.append(row)

        try:
            r = float(
                row[received_idx]
            )
        except Exception:
            raise ValueError(
                f"Invalid Amount Received: "
                f"{row[received_idx]}"
            )

        try:
            p = float(
                row[paid_idx]
            )
        except Exception:
            raise ValueError(
                f"Invalid Amount Paid: "
                f"{row[paid_idx]}"
            )

        received_buffer.append(r)
        paid_buffer.append(p)

        if len(rows_buffer) >= BATCH_SIZE:

            old_received = np.asarray(
                received_buffer,
                dtype=np.float64
            )

            old_paid = np.asarray(
                paid_buffer,
                dtype=np.float64
            )

            new_received = calibrate_amounts(
                old_received,
                synthetic_log_sorted,
                original_log,
                orig_u
            )

            # Preserve the transaction's existing
            # paid/received relationship.
            ratio = np.divide(
                old_paid,
                old_received,
                out=np.ones_like(old_paid),
                where=old_received != 0
            )

            new_paid = (
                new_received * ratio
            )

            # Protect against numerical overflow.
            new_paid = np.clip(
                new_paid,
                1e-6,
                np.finfo(np.float64).max
            )

            for j, row in enumerate(
                rows_buffer
            ):

                row[received_idx] = (
                    f"{new_received[j]:.6f}"
                )

                row[paid_idx] = (
                    f"{new_paid[j]:.6f}"
                )

                writer.writerow(row)

            total_rows += len(
                rows_buffer
            )

            rows_buffer.clear()
            received_buffer.clear()
            paid_buffer.clear()

            print(
                f"  rewritten {total_rows:,}"
                f"/5,067,991",
                end="\r"
            )

    # Flush final partial batch.
    if rows_buffer:

        old_received = np.asarray(
            received_buffer,
            dtype=np.float64
        )

        old_paid = np.asarray(
            paid_buffer,
            dtype=np.float64
        )

        new_received = calibrate_amounts(
            old_received,
            synthetic_log_sorted,
            original_log,
            orig_u
        )

        ratio = np.divide(
            old_paid,
            old_received,
            out=np.ones_like(old_paid),
            where=old_received != 0
        )

        new_paid = (
            new_received * ratio
        )

        new_paid = np.clip(
            new_paid,
            1e-6,
            np.finfo(np.float64).max
        )

        for j, row in enumerate(
            rows_buffer
        ):

            row[received_idx] = (
                f"{new_received[j]:.6f}"
            )

            row[paid_idx] = (
                f"{new_paid[j]:.6f}"
            )

            writer.writerow(row)

        total_rows += len(
            rows_buffer
        )

print(
    f"\n\nRows written: {total_rows:,}"
)

assert total_rows == 5_067_991

print("\n✅ Full calibrated synthetic file written")


# ------------------------------------------------------------
# 7. FILE SIZE
# ------------------------------------------------------------

size_gb = (
    os.path.getsize(OUT_PATH)
    / (1024 ** 3)
)

print(
    f"Output file size: "
    f"{size_gb:.2f} GB"
)

print("\n" + "=" * 90)
print("CELL 28 COMPLETE")
print("=" * 90)

print(
    "\nCreated:"
)
print(OUT_PATH)

print(
    "\nNext step will be a complete validation of:"
)
print(
    "  1. amount distribution"
)
print(
    "  2. row count"
)
print(
    "  3. graph/episode integrity"
)
print(
    "  4. timestamp preservation"
)
print(
    "  5. typology preservation"
)

==========================================================================================
CELL 28 — AMOUNT CALIBRATION
==========================================================================================

[1/6] Loading original laundering amounts...
Original laundering amounts: 5,177

[2/6] Loading synthetic Amount Received...
  chunk 11 | 5,067,991 rows
Synthetic amounts: 5,067,991

[3/6] Preparing empirical quantile mapping...

Current synthetic amount distribution:
  P01  : 0.0148
  P10  : 17.1423
  P50  : 1,465.9200
  P90  : 276,577.6935
  P99  : 59,921,433.3667

Target original laundering distribution:
  P01  : 1.0000
  P10  : 673.1480
  P50  : 8,667.2100
  P90  : 171,438.2920
  P99  : 23,420,046.8380

✅ Calibration function passed sanity check

[4/6] Rewriting calibrated synthetic file...
Output: /kaggle/working/AML_GNN_ONLY/data/HI-Small_SYNTH_FULL_V2_transactions.csv
  rewritten 5,000,000/5,067,991

Rows written: 5,067,991

✅ Full calibrated synthetic file written
Output file size: 0.83 GB

==========================================================================================
CELL 28 COMPLETE
==========================================================================================

Created:
/kaggle/working/AML_GNN_ONLY/data/HI-Small_SYNTH_FULL_V2_transactions.csv

Next step will be a complete validation of:
  1. amount distribution
  2. row count
  3. graph/episode integrity
  4. timestamp preservation
  5. typology preservation

In [45]:
# ============================================================
# CELL 27 — DIAGNOSE SYNTHETIC FILE CORRUPTION
# ============================================================

import os
import csv
import numpy as np
import pandas as pd

SYN_PATH = (
    "/kaggle/working/AML_GNN_ONLY/data/"
    "HI-Small_SYNTH_FULL_transactions.csv"
)

print("=" * 90)
print("SYNTHETIC FILE DIAGNOSTIC")
print("=" * 90)

# ------------------------------------------------------------
# 1. RAW PHYSICAL LINE COUNT
# ------------------------------------------------------------

with open(
    SYN_PATH,
    "r",
    encoding="utf-8",
    errors="replace"
) as f:

    raw_line_count = sum(1 for _ in f)

print(f"\nRaw physical lines : {raw_line_count:,}")
print("Expected data rows : 5,067,991")


# ------------------------------------------------------------
# 2. HEADER + FIRST 10 RAW ROWS
# ------------------------------------------------------------

print("\n" + "=" * 90)
print("HEADER + FIRST 10 ROWS")
print("=" * 90)

with open(
    SYN_PATH,
    "r",
    encoding="utf-8",
    errors="replace"
) as f:

    for i in range(11):
        line = f.readline()

        if not line:
            break

        print(f"{i:02d}: {line.rstrip()}")


# ------------------------------------------------------------
# 3. CSV STRUCTURE CHECK
# ------------------------------------------------------------

print("\n" + "=" * 90)
print("CSV STRUCTURE CHECK")
print("=" * 90)

with open(
    SYN_PATH,
    "r",
    encoding="utf-8",
    errors="replace",
    newline=""
) as f:

    reader = csv.reader(f)

    header = next(reader)

    print("Number of header fields:", len(header))

    for i, col in enumerate(header):
        print(f"[{i}] {col!r}")

    good = 0
    bad = 0
    first_bad = None

    for line_no, row in enumerate(reader, start=2):

        if len(row) == len(header):
            good += 1
        else:
            bad += 1

            if first_bad is None:
                first_bad = (line_no, len(row), row)

        # Enough to diagnose structural corruption
        if line_no >= 100_002:
            break

print("\nRows checked :", good + bad)
print("Good rows    :", good)
print("Bad rows     :", bad)

if first_bad is not None:
    print("\nFIRST BAD ROW:")
    print("Line number :", first_bad[0])
    print("Field count :", first_bad[1])
    print("Row        :", first_bad[2])


# ------------------------------------------------------------
# 4. READ ONLY AMOUNT COLUMN
# ------------------------------------------------------------

print("\n" + "=" * 90)
print("AMOUNT COLUMN DIAGNOSTIC")
print("=" * 90)

amount_parts = []

for chunk in pd.read_csv(
    SYN_PATH,
    usecols=[5],
    chunksize=100_000,
    low_memory=False
):

    vals = pd.to_numeric(
        chunk.iloc[:, 0],
        errors="coerce"
    )

    amount_parts.append(vals)

amounts = pd.concat(
    amount_parts,
    ignore_index=True
)

a = amounts.dropna().to_numpy(
    dtype=np.float64
)

print(f"Rows readable by pandas : {len(amounts):,}")
print(f"NaN amounts             : {amounts.isna().sum():,}")
print(f"Finite amounts          : {np.isfinite(a).sum():,}")

finite = a[np.isfinite(a)]

if len(finite) > 0:

    print("\nBasic statistics")
    print("----------------")
    print(f"Min    : {np.min(finite):,.10g}")
    print(f"Median : {np.median(finite):,.10g}")
    print(f"Mean   : {np.mean(finite):,.10g}")
    print(f"Max    : {np.max(finite):,.10g}")

    print("\nQuantiles")
    print("---------")

    for q in [0, 1, 5, 10, 25, 50, 75, 90, 95, 99, 99.9, 100]:

        value = np.percentile(
            finite,
            q
        )

        print(
            f"P{q:<5} : {value:,.10g}"
        )


# ------------------------------------------------------------
# 5. EXTREME VALUE COUNTS
# ------------------------------------------------------------

print("\n" + "=" * 90)
print("EXTREME AMOUNT COUNTS")
print("=" * 90)

thresholds = [
    1,
    10,
    100,
    1_000,
    10_000,
    100_000,
    1_000_000,
    10_000_000,
    100_000_000,
    1_000_000_000,
    1e12,
    1e15,
    1e20,
    1e50
]

for t in thresholds:

    count = np.sum(
        finite > t
    )

    print(
        f"> {t:>14,.0f} : {count:,}"
    )


# ------------------------------------------------------------
# 6. MOST FREQUENT AMOUNTS
# ------------------------------------------------------------

print("\n" + "=" * 90)
print("MOST COMMON EXACT AMOUNTS")
print("=" * 90)

rounded = pd.Series(
    finite
).round(8)

common = rounded.value_counts().head(20)

for value, count in common.items():

    print(
        f"{value:>30,.8f} : {count:,}"
    )


# ------------------------------------------------------------
# 7. CHECK WHETHER VALUES LOOK POWER/SCALING GENERATED
# ------------------------------------------------------------

print("\n" + "=" * 90)
print("REPRESENTATIVE LARGE VALUES")
print("=" * 90)

large = np.sort(
    finite[
        finite > 1_000_000
    ]
)

if len(large) > 0:

    sample_idx = np.linspace(
        0,
        len(large) - 1,
        min(20, len(large)),
        dtype=int
    )

    for x in large[sample_idx]:

        print(
            f"{x:.15e}"
        )

else:
    print("No amounts > 1,000,000")

print("\n✅ CELL 27 COMPLETE")

==========================================================================================
SYNTHETIC FILE DIAGNOSTIC
==========================================================================================

Raw physical lines : 5,067,992
Expected data rows : 5,067,991

==========================================================================================
HEADER + FIRST 10 ROWS
==========================================================================================
00: transaction_id,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering,is_synthetic,synthetic_episode_id,typology,source_template_id,template_source_order
01: BSX045L9N8UA3V3I,2022-09-10 23:26:00,001,800453EF0,018549,805E94300,134.510000,Rupee,134.510000,Rupee,Cash,1,1,SYN_BIPARTITE_0000000,BIPARTITE,BIPARTITE_0101,0
02: 9VSDBFX8R7GLGPK1,2022-09-02 15:14:00,001,8146E6E70,011405,807FCC2F0,470.645953,US Dollar,470.645953,US Dollar,Cheque,1,1,SYN_BIPARTITE_0000001,BIPARTITE,BIPARTITE_0233,0
03: D6L43N7BK70DUS7B,2022-09-02 00:35:00,01665,800710650,010,8001DDC50,216.758051,US Dollar,216.758051,US Dollar,ACH,1,1,SYN_BIPARTITE_0000001,BIPARTITE,BIPARTITE_0233,1
04: ELH5L6ICM5W8GDT3,2022-09-01 04:06:00,014650,807BAEB10,0113935,80576E930,9181.159823,Euro,9181.159823,Euro,Bitcoin,1,1,SYN_BIPARTITE_0000001,BIPARTITE,BIPARTITE_0233,2
05: DSSFFBDSDK94ZV8F,2022-09-01 00:01:00,002845,813CC4FF0,001244,809656C80,14238.152936,US Dollar,14238.152936,US Dollar,Cash,1,1,SYN_BIPARTITE_0000001,BIPARTITE,BIPARTITE_0233,3
06: Z9K5NQO856ZWPPNO,2022-09-01 23:00:00,022164,80A0F2850,002991,801B68FD0,18184.801389,US Dollar,18184.801389,US Dollar,Cheque,1,1,SYN_BIPARTITE_0000001,BIPARTITE,BIPARTITE_0233,4
07: CIWUXG0BAIB56W87,2022-09-02 20:26:00,025075,8097358D0,00220,81093B0E0,7869.855955,Swiss Franc,7869.855955,Swiss Franc,Cheque,1,1,SYN_BIPARTITE_0000001,BIPARTITE,BIPARTITE_0233,5
08: PG9618HEAZYIRE0V,2022-09-01 12:01:00,004523,8023A86F0,0015695,808BA8070,14075.841708,US Dollar,14075.841708,US Dollar,Cheque,1,1,SYN_BIPARTITE_0000001,BIPARTITE,BIPARTITE_0233,6
09: IAM9Z03SUP514PMO,2022-09-02 03:42:00,011974,8032A88C0,001047,8011BA5B0,8373.000177,Yen,8373.000177,Yen,Cash,1,1,SYN_BIPARTITE_0000001,BIPARTITE,BIPARTITE_0233,7
10: KTX2KVHWW96I6AES,2022-09-03 15:52:00,002385,80DBA78B0,025075,80D7FE3B0,1092927.450000,US Dollar,1092927.450000,US Dollar,Cheque,1,1,SYN_BIPARTITE_0000002,BIPARTITE,BIPARTITE_0058,0

==========================================================================================
CSV STRUCTURE CHECK
==========================================================================================
Number of header fields: 17
[0] 'transaction_id'
[1] 'Timestamp'
[2] 'From Bank'
[3] 'Account'
[4] 'To Bank'
[5] 'Account.1'
[6] 'Amount Received'
[7] 'Receiving Currency'
[8] 'Amount Paid'
[9] 'Payment Currency'
[10] 'Payment Format'
[11] 'Is Laundering'
[12] 'is_synthetic'
[13] 'synthetic_episode_id'
[14] 'typology'
[15] 'source_template_id'
[16] 'template_source_order'

Rows checked : 100001
Good rows    : 100001
Bad rows     : 0

==========================================================================================
AMOUNT COLUMN DIAGNOSTIC
==========================================================================================
Rows readable by pandas : 5,067,991
NaN amounts             : 4,599,166
Finite amounts          : 468,825

Basic statistics
----------------
Min    : 810
Median : 805,176,000
Mean   : 4.109693384e+301
Max    : 8.148e+304

Quantiles
---------
P0     : 810
P1     : 8,001,037
P5     : 8,049,625
P10    : 100,786,714
P25    : 801,605,730
P50    : 805,176,000
P75    : 810,437,340
P90    : 8.01091e+15
P95    : 8.076438e+65
P99    : 8.0509e+194
P99.9  : 8.061e+294
P100   : 8.148e+304

==========================================================================================
EXTREME AMOUNT COUNTS
==========================================================================================
>              1 : 468,825
>             10 : 468,825
>            100 : 468,825
>          1,000 : 468,822
>         10,000 : 468,822
>        100,000 : 468,548
>      1,000,000 : 464,807
>     10,000,000 : 426,058
>    100,000,000 : 425,251
>  1,000,000,000 : 47,633
> 1,000,000,000,000 : 47,633
> 1,000,000,000,000,000 : 47,394
> 100,000,000,000,000,000,000 : 43,925
> 100,000,000,000,000,007,629,769,841,091,887,003,294,964,970,946,560 : 31,095

==========================================================================================
MOST COMMON EXACT AMOUNTS
==========================================================================================
                           inf : 243
            8,138,154.00000000 : 91
          808,190,740.00000000 : 82
          811,713,330.00000000 : 80
          805,130,160.00000000 : 79
          804,946,650.00000000 : 73
          802,975,460.00000000 : 72
          805,155,520.00000000 : 71
          802,396,080.00000000 : 71
          802,523,190.00000000 : 70
          809,476,620.00000000 : 69
          800,081,920.00000000 : 69
          801,321,710.00000000 : 68
          804,020,360.00000000 : 68
          812,217,900.00000000 : 67
          809,782,890.00000000 : 66
          802,275,610.00000000 : 66
          804,846,200.00000000 : 66
          802,490,230.00000000 : 66
          806,465,520.00000000 : 66

==========================================================================================
REPRESENTATIVE LARGE VALUES
==========================================================================================
1.000061000000000e+06
8.070312000000000e+06
8.001750800000000e+08
8.007108500000000e+08
8.012554200000000e+08
8.018120200000000e+08
8.024105800000000e+08
8.030647900000000e+08
8.037310500000000e+08
8.048319400000000e+08
8.057521000000000e+08
8.067907200000000e+08
8.078206300000000e+08
8.088833700000000e+08
8.101632900000000e+08
8.116327100000000e+08
8.131316300000000e+08
8.148334900000000e+08
8.027379999999999e+65
8.148000000000001e+304

✅ CELL 27 COMPLETE

/usr/local/lib/python3.12/dist-packages/pandas/core/internals/blocks.py:1986: RuntimeWarning: overflow encountered in multiply
  values = self.values.round(decimals)  # type: ignore[union-attr]

In [48]:
# ============================================================
# CELL 29 — VALIDATE CALIBRATED SYNTHETIC V2
# ============================================================
#
# Checks:
#   1. Exact row count
#   2. Amount distribution vs original laundering
#   3. Same-size KS/Wasserstein
#   4. Quantile matching
#   5. Non-amount columns preserved
#   6. Timestamp preserved
#   7. Episode IDs preserved
#   8. Typologies preserved
#   9. Synthetic transaction IDs preserved
#  10. Graph endpoints preserved
# ============================================================

import os
import numpy as np
import pandas as pd

from scipy.stats import ks_2samp, wasserstein_distance

ORIG_PATH = (
    "/kaggle/input/datasets/ealtman2019/"
    "ibm-transactions-for-anti-money-laundering-aml/"
    "HI-Small_Trans.csv"
)

V1_PATH = (
    "/kaggle/working/AML_GNN_ONLY/data/"
    "HI-Small_SYNTH_FULL_transactions.csv"
)

V2_PATH = (
    "/kaggle/working/AML_GNN_ONLY/data/"
    "HI-Small_SYNTH_FULL_V2_transactions.csv"
)

EXPECTED_SYNTH = 5_067_991
EXPECTED_ORIG_LAUNDERING = 5_177

print("=" * 100)
print("CELL 29 — CALIBRATED SYNTHETIC VALIDATION")
print("=" * 100)


# ============================================================
# 1. ORIGINAL LAUNDERING AMOUNTS
# ============================================================

print("\n[1/8] Loading original laundering amounts...")

orig_parts = []

for chunk in pd.read_csv(
    ORIG_PATH,
    usecols=["Amount Received", "Is Laundering"],
    chunksize=500_000,
    low_memory=False
):

    chunk["Amount Received"] = pd.to_numeric(
        chunk["Amount Received"],
        errors="coerce"
    )

    chunk["Is Laundering"] = pd.to_numeric(
        chunk["Is Laundering"],
        errors="coerce"
    )

    vals = chunk.loc[
        chunk["Is Laundering"] == 1,
        "Amount Received"
    ].dropna()

    vals = vals[vals > 0]

    orig_parts.append(
        vals.to_numpy(dtype=np.float64)
    )

original_amounts = np.concatenate(orig_parts)

del orig_parts

assert len(original_amounts) == EXPECTED_ORIG_LAUNDERING

print(
    f"Original laundering amounts: "
    f"{len(original_amounts):,}"
)


# ============================================================
# 2. LOAD V1 + V2 AMOUNTS
# ============================================================

print("\n[2/8] Loading V1 and V2 amounts...")

v1_amounts = []
v2_amounts = []

for v1_chunk, v2_chunk in zip(
    pd.read_csv(
        V1_PATH,
        usecols=["Amount Received"],
        chunksize=500_000,
        low_memory=False
    ),
    pd.read_csv(
        V2_PATH,
        usecols=["Amount Received"],
        chunksize=500_000,
        low_memory=False
    )
):

    v1_amounts.append(
        pd.to_numeric(
            v1_chunk["Amount Received"],
            errors="coerce"
        ).to_numpy(dtype=np.float64)
    )

    v2_amounts.append(
        pd.to_numeric(
            v2_chunk["Amount Received"],
            errors="coerce"
        ).to_numpy(dtype=np.float64)
    )

v1_amounts = np.concatenate(v1_amounts)
v2_amounts = np.concatenate(v2_amounts)

assert len(v1_amounts) == EXPECTED_SYNTH
assert len(v2_amounts) == EXPECTED_SYNTH

print(
    f"V1 synthetic amounts: "
    f"{len(v1_amounts):,}"
)

print(
    f"V2 synthetic amounts: "
    f"{len(v2_amounts):,}"
)


# ============================================================
# 3. BASIC AMOUNT STATISTICS
# ============================================================

print("\n[3/8] Amount statistics...")

def make_stats(x):

    return {
        "Mean": np.mean(x),
        "Median": np.median(x),
        "P01": np.percentile(x, 1),
        "P05": np.percentile(x, 5),
        "P10": np.percentile(x, 10),
        "P25": np.percentile(x, 25),
        "P50": np.percentile(x, 50),
        "P75": np.percentile(x, 75),
        "P90": np.percentile(x, 90),
        "P95": np.percentile(x, 95),
        "P99": np.percentile(x, 99)
    }


orig_stats = make_stats(original_amounts)
v1_stats = make_stats(v1_amounts)
v2_stats = make_stats(v2_amounts)

stats_df = pd.DataFrame({
    "Metric": list(orig_stats.keys()),
    "Original_Laundering": list(orig_stats.values()),
    "V1_Synthetic": [
        v1_stats[k] for k in orig_stats.keys()
    ],
    "V2_Calibrated": [
        v2_stats[k] for k in orig_stats.keys()
    ]
})

print(
    stats_df.to_string(
        index=False,
        formatters={
            "Original_Laundering":
                "{:,.4f}".format,
            "V1_Synthetic":
                "{:,.4f}".format,
            "V2_Calibrated":
                "{:,.4f}".format
        }
    )
)


# ============================================================
# 4. QUANTILE RATIOS
# ============================================================

print("\n" + "=" * 100)
print("QUANTILE COMPARISON")
print("=" * 100)

quantiles = [1, 5, 10, 25, 50, 75, 90, 95, 99]

q_rows = []

for q in quantiles:

    oq = np.percentile(
        original_amounts,
        q
    )

    v1q = np.percentile(
        v1_amounts,
        q
    )

    v2q = np.percentile(
        v2_amounts,
        q
    )

    q_rows.append({
        "Quantile": f"P{q:02d}",
        "Original": oq,
        "V1": v1q,
        "V2": v2q,
        "V1_to_Original":
            v1q / oq if oq != 0 else np.nan,
        "V2_to_Original":
            v2q / oq if oq != 0 else np.nan
    })

qdf = pd.DataFrame(q_rows)

print(
    qdf.to_string(
        index=False,
        formatters={
            "Original":
                "{:,.4f}".format,
            "V1":
                "{:,.4f}".format,
            "V2":
                "{:,.4f}".format,
            "V1_to_Original":
                "{:.4f}".format,
            "V2_to_Original":
                "{:.4f}".format
        }
    )
)


# ============================================================
# 5. FULL DISTRIBUTION DISTANCES
# ============================================================

print("\n" + "=" * 100)
print("DISTRIBUTION DISTANCE")
print("=" * 100)

orig_log = np.log10(
    original_amounts
)

v1_log = np.log10(
    v1_amounts
)

v2_log = np.log10(
    v2_amounts
)

v1_ks = ks_2samp(
    orig_log,
    v1_log
).statistic

v2_ks = ks_2samp(
    orig_log,
    v2_log
).statistic

v1_wd = wasserstein_distance(
    orig_log,
    v1_log
)

v2_wd = wasserstein_distance(
    orig_log,
    v2_log
)

print(
    f"Original vs V1 KS               : "
    f"{v1_ks:.6f}"
)

print(
    f"Original vs V2 KS               : "
    f"{v2_ks:.6f}"
)

print(
    f"Original vs V1 Wasserstein      : "
    f"{v1_wd:.6f}"
)

print(
    f"Original vs V2 Wasserstein      : "
    f"{v2_wd:.6f}"
)


# ============================================================
# 6. CHECK NON-AMOUNT DATA PRESERVATION
# ============================================================

print("\n" + "=" * 100)
print("STRUCTURAL PRESERVATION CHECK")
print("=" * 100)

# Columns whose values MUST NOT change.
protected_columns = [
    "transaction_id",
    "Timestamp",
    "From Bank",
    "Account",
    "To Bank",
    "Account.1",
    "Receiving Currency",
    "Payment Currency",
    "Payment Format",
    "Is Laundering",
    "is_synthetic",
    "synthetic_episode_id",
    "typology",
    "source_template_id",
    "template_source_order"
]

comparison_columns = [
    "transaction_id",
    "Timestamp",
    "From Bank",
    "Account",
    "To Bank",
    "Account.1",
    "Amount Received",
    "Receiving Currency",
    "Amount Paid",
    "Payment Currency",
    "Payment Format",
    "Is Laundering",
    "is_synthetic",
    "synthetic_episode_id",
    "typology",
    "source_template_id",
    "template_source_order"
]

diff_counts = {
    col: 0
    for col in protected_columns
}

rows_checked = 0

for v1_chunk, v2_chunk in zip(
    pd.read_csv(
        V1_PATH,
        usecols=comparison_columns,
        chunksize=100_000,
        low_memory=False
    ),
    pd.read_csv(
        V2_PATH,
        usecols=comparison_columns,
        chunksize=100_000,
        low_memory=False
    )
):

    # Make sure rows remain aligned.
    assert len(v1_chunk) == len(v2_chunk)

    for col in protected_columns:

        a = v1_chunk[col].fillna("__NA__").astype(str)
        b = v2_chunk[col].fillna("__NA__").astype(str)

        diff_counts[col] += int(
            (a != b).sum()
        )

    rows_checked += len(v1_chunk)

    print(
        f"  Checked {rows_checked:,} rows",
        end="\r"
    )

print(
    f"\nRows checked: {rows_checked:,}"
)

print("\nProtected-column differences:")

for col, count in diff_counts.items():

    status = "✅" if count == 0 else "❌"

    print(
        f"{status} {col:24s}: "
        f"{count:,}"
    )


# ============================================================
# 7. EPISODE / TYPOLOGY / ENDPOINT COUNTS
# ============================================================

print("\n" + "=" * 100)
print("EPISODE / TYPOLOGY / GRAPH PRESERVATION")
print("=" * 100)

# Use only structural columns for this comparison.
struct_cols = [
    "synthetic_episode_id",
    "typology",
    "From Bank",
    "Account",
    "To Bank",
    "Account.1",
    "Timestamp"
]

v1_struct_parts = []
v2_struct_parts = []

for v1_chunk, v2_chunk in zip(
    pd.read_csv(
        V1_PATH,
        usecols=struct_cols,
        chunksize=500_000,
        low_memory=False
    ),
    pd.read_csv(
        V2_PATH,
        usecols=struct_cols,
        chunksize=500_000,
        low_memory=False
    )
):

    v1_struct_parts.append(v1_chunk)
    v2_struct_parts.append(v2_chunk)

v1_struct = pd.concat(
    v1_struct_parts,
    ignore_index=True
)

v2_struct = pd.concat(
    v2_struct_parts,
    ignore_index=True
)

del v1_struct_parts, v2_struct_parts


# Episode count
v1_episode_count = (
    v1_struct["synthetic_episode_id"]
    .nunique()
)

v2_episode_count = (
    v2_struct["synthetic_episode_id"]
    .nunique()
)

print(
    f"V1 episodes: {v1_episode_count:,}"
)

print(
    f"V2 episodes: {v2_episode_count:,}"
)

print(
    "✅ Episode count preserved"
    if v1_episode_count == v2_episode_count
    else "❌ Episode count changed"
)


# Typology counts
v1_typ = (
    v1_struct["typology"]
    .value_counts()
    .sort_index()
)

v2_typ = (
    v2_struct["typology"]
    .value_counts()
    .sort_index()
)

typology_compare = pd.DataFrame({
    "V1": v1_typ,
    "V2": v2_typ
}).fillna(0).astype(int)

typology_compare["Difference"] = (
    typology_compare["V2"]
    - typology_compare["V1"]
)

print("\nTypology transaction counts:")
print(typology_compare.to_string())

assert np.all(
    typology_compare["Difference"] == 0
)

print(
    "\n✅ Typology transaction counts preserved"
)


# Endpoint preservation
v1_endpoints = v1_struct[
    [
        "From Bank",
        "Account",
        "To Bank",
        "Account.1"
    ]
].astype(str)

v2_endpoints = v2_struct[
    [
        "From Bank",
        "Account",
        "To Bank",
        "Account.1"
    ]
].astype(str)

endpoint_diff = (
    v1_endpoints
    != v2_endpoints
).any(axis=1).sum()

print(
    f"\nEndpoint row differences: "
    f"{endpoint_diff:,}"
)

if endpoint_diff == 0:
    print(
        "✅ All graph endpoints preserved"
    )
else:
    print(
        "❌ Graph endpoints changed"
    )


# Timestamp preservation
v1_ts = (
    pd.to_datetime(
        v1_struct["Timestamp"]
    )
)

v2_ts = (
    pd.to_datetime(
        v2_struct["Timestamp"]
    )
)

timestamp_diff = (
    v1_ts != v2_ts
).sum()

print(
    f"Timestamp differences: "
    f"{timestamp_diff:,}"
)

if timestamp_diff == 0:
    print(
        "✅ All timestamps preserved"
    )
else:
    print(
        "❌ Timestamps changed"
    )


# ============================================================
# 8. FINAL DECISION
# ============================================================

print("\n" + "=" * 100)
print("FINAL V2 DECISION")
print("=" * 100)

q_v2_ratios = qdf[
    "V2_to_Original"
].to_numpy()

# Percentage closeness in log space.
log_ratio_error = np.mean(
    np.abs(
        np.log10(
            np.maximum(
                q_v2_ratios,
                1e-12
            )
        )
    )
)

protected_changes = sum(
    diff_counts.values()
)

structure_ok = (
    endpoint_diff == 0
    and timestamp_diff == 0
    and v1_episode_count == v2_episode_count
    and np.all(
        typology_compare["Difference"] == 0
    )
)

amount_improved = (
    v2_ks < v1_ks
    and v2_wd < v1_wd
)

print(
    f"V1 KS : {v1_ks:.6f}"
)

print(
    f"V2 KS : {v2_ks:.6f}"
)

print(
    f"V1 WD : {v1_wd:.6f}"
)

print(
    f"V2 WD : {v2_wd:.6f}"
)

print(
    f"Protected-column changes: "
    f"{protected_changes:,}"
)

print(
    f"Graph/episode structure OK: "
    f"{structure_ok}"
)

print(
    f"Amount distribution improved: "
    f"{amount_improved}"
)

if (
    amount_improved
    and protected_changes == 0
    and structure_ok
):

    print(
        "\n🟢 V2 PASSES CALIBRATION VALIDATION"
    )

    print(
        "The monetary distribution improved while "
        "the AML graph structure remained unchanged."
    )

elif (
    protected_changes == 0
    and structure_ok
):

    print(
        "\n🟡 STRUCTURE IS SAFE, BUT AMOUNT IMPROVEMENT "
        "NEEDS REVIEW"
    )

else:

    print(
        "\n🔴 V2 FAILED STRUCTURAL PRESERVATION"
    )

# ------------------------------------------------------------
# SAVE
# ------------------------------------------------------------

stats_df.to_csv(
    "/kaggle/working/"
    "amount_validation_v2_statistics.csv",
    index=False
)

qdf.to_csv(
    "/kaggle/working/"
    "amount_validation_v2_quantiles.csv",
    index=False
)

typology_compare.to_csv(
    "/kaggle/working/"
    "amount_validation_v2_typology.csv"
)

print(
    "\n✅ CELL 29 COMPLETE"
)

====================================================================================================
CELL 29 — CALIBRATED SYNTHETIC VALIDATION
====================================================================================================

[1/8] Loading original laundering amounts...
Original laundering amounts: 5,177

[2/8] Loading V1 and V2 amounts...
V1 synthetic amounts: 5,067,991
V2 synthetic amounts: 5,067,991

[3/8] Amount statistics...
Metric Original_Laundering    V1_Synthetic   V2_Calibrated
  Mean     36,135,310.4128 21,383,007.8364 35,540,072.6022
Median          8,667.2100      1,465.9200      8,667.2212
   P01              1.0000          0.0148          0.9970
   P05            213.9700          3.4137        213.9026
   P10            673.1480         17.1423        672.6370
   P25          2,634.9700        150.7981      2,634.6883
   P50          8,667.2100      1,465.9200      8,667.2212
   P75         18,832.2700     17,584.7302     18,834.5069
   P90        171,438.2920    276,577.6935    171,890.8613
   P95        943,718.0220  1,575,623.5649    953,049.3934
   P99     23,420,046.8380 59,921,433.3667 23,867,222.9808

====================================================================================================
QUANTILE COMPARISON
====================================================================================================
Quantile        Original              V1              V2 V1_to_Original V2_to_Original
     P01          1.0000          0.0148          0.9970         0.0148         0.9970
     P05        213.9700          3.4137        213.9026         0.0160         0.9997
     P10        673.1480         17.1423        672.6370         0.0255         0.9992
     P25      2,634.9700        150.7981      2,634.6883         0.0572         0.9999
     P50      8,667.2100      1,465.9200      8,667.2212         0.1691         1.0000
     P75     18,832.2700     17,584.7302     18,834.5069         0.9338         1.0001
     P90    171,438.2920    276,577.6935    171,890.8613         1.6133         1.0026
     P95    943,718.0220  1,575,623.5649    953,049.3934         1.6696         1.0099
     P99 23,420,046.8380 59,921,433.3667 23,867,222.9808         2.5586         1.0191

====================================================================================================
DISTRIBUTION DISTANCE
====================================================================================================
Original vs V1 KS               : 0.336737
Original vs V2 KS               : 0.000193
Original vs V1 Wasserstein      : 0.815273
Original vs V2 Wasserstein      : 0.000655

====================================================================================================
STRUCTURAL PRESERVATION CHECK
====================================================================================================
  Checked 5,067,991 rows
Rows checked: 5,067,991

Protected-column differences:
✅ transaction_id          : 0
✅ Timestamp               : 0
✅ From Bank               : 0
✅ Account                 : 0
✅ To Bank                 : 0
✅ Account.1               : 0
✅ Receiving Currency      : 0
✅ Payment Currency        : 0
✅ Payment Format          : 0
✅ Is Laundering           : 0
✅ is_synthetic            : 0
✅ synthetic_episode_id    : 0
✅ typology                : 0
✅ source_template_id      : 0
✅ template_source_order   : 0

====================================================================================================
EPISODE / TYPOLOGY / GRAPH PRESERVATION
====================================================================================================
V1 episodes: 584,706
V2 episodes: 584,706
✅ Episode count preserved

Typology transaction counts:
                     V1       V2  Difference
typology
BIPARTITE        415357   415357           0
CYCLE            453261   453261           0
FAN-IN           502219   502219           0
FAN-OUT          540123   540123           0
GATHER-SCATTER  1130782  1130782           0
RANDOM           301647   301647           0
SCATTER-GATHER   988646   988646           0
STACK            735956   735956           0

✅ Typology transaction counts preserved

Endpoint row differences: 0
✅ All graph endpoints preserved
Timestamp differences: 0
✅ All timestamps preserved

====================================================================================================
FINAL V2 DECISION
====================================================================================================
V1 KS : 0.336737
V2 KS : 0.000193
V1 WD : 0.815273
V2 WD : 0.000655
Protected-column changes: 0
Graph/episode structure OK: True
Amount distribution improved: True

🟢 V2 PASSES CALIBRATION VALIDATION
The monetary distribution improved while the AML graph structure remained unchanged.

✅ CELL 29 COMPLETE

In [49]:
# ============================================================
# CELL 30 — BUILD FINAL V2 BALANCED TRAINING DATASET
# ============================================================
#
# Existing final file:
#   Original HI-Small + V1 synthetic
#
# New final file:
#   Original HI-Small + V2 calibrated synthetic
#
# ONLY synthetic amount columns are replaced.
#
# Everything else is preserved:
#   transaction_id
#   Timestamp
#   From Bank
#   Account
#   To Bank
#   Account.1
#   currencies
#   payment format
#   Is Laundering
#   is_synthetic
#   synthetic_episode_id
#   typology
#   source_template_id
#   template_source_order
#
# ============================================================

import os
import csv
import shutil

import numpy as np
import pandas as pd


# ------------------------------------------------------------
# PATHS
# ------------------------------------------------------------

OLD_FINAL = (
    "/kaggle/working/AML_GNN_ONLY/data/"
    "HI-Small_FINAL_transactions_10146336.csv"
)

V1_PATH = (
    "/kaggle/working/AML_GNN_ONLY/data/"
    "HI-Small_SYNTH_FULL_transactions.csv"
)

V2_PATH = (
    "/kaggle/working/AML_GNN_ONLY/data/"
    "HI-Small_SYNTH_FULL_V2_transactions.csv"
)

FINAL_V2 = (
    "/kaggle/working/AML_GNN_ONLY/data/"
    "HI-Small_FINAL_V2_transactions_10146336.csv"
)


EXPECTED_ORIGINAL = 5_078_345
EXPECTED_SYNTH = 5_067_991
EXPECTED_FINAL = 10_146_336


print("=" * 100)
print("CELL 30 — FINAL V2 TRAINING DATASET")
print("=" * 100)


# ------------------------------------------------------------
# 1. VERIFY FILES
# ------------------------------------------------------------

for path in [
    OLD_FINAL,
    V1_PATH,
    V2_PATH
]:

    if not os.path.exists(path):
        raise FileNotFoundError(
            f"Missing file:\n{path}"
        )

    size_gb = (
        os.path.getsize(path)
        / (1024 ** 3)
    )

    print(
        f"✅ {os.path.basename(path)} "
        f"({size_gb:.2f} GB)"
    )


# ------------------------------------------------------------
# 2. VALIDATE V1/V2 ALIGNMENT
# ------------------------------------------------------------

print("\n[1/5] Validating V1 ↔ V2 transaction alignment...")

checked = 0

v1_reader = pd.read_csv(
    V1_PATH,
    usecols=[
        "transaction_id",
        "Timestamp",
        "From Bank",
        "Account",
        "To Bank",
        "Account.1",
        "synthetic_episode_id",
        "typology",
        "source_template_id",
        "template_source_order"
    ],
    chunksize=200_000,
    low_memory=False
)

v2_reader = pd.read_csv(
    V2_PATH,
    usecols=[
        "transaction_id",
        "Timestamp",
        "From Bank",
        "Account",
        "To Bank",
        "Account.1",
        "synthetic_episode_id",
        "typology",
        "source_template_id",
        "template_source_order"
    ],
    chunksize=200_000,
    low_memory=False
)

for chunk_no, (v1, v2) in enumerate(
    zip(v1_reader, v2_reader),
    start=1
):

    if len(v1) != len(v2):
        raise ValueError(
            f"V1/V2 chunk length mismatch "
            f"at chunk {chunk_no}"
        )

    for col in v1.columns:

        a = (
            v1[col]
            .fillna("__NA__")
            .astype(str)
        )

        b = (
            v2[col]
            .fillna("__NA__")
            .astype(str)
        )

        mismatches = (
            a != b
        ).sum()

        if mismatches:
            raise ValueError(
                f"V1/V2 mismatch in "
                f"{col}: {mismatches:,}"
            )

    checked += len(v1)

    print(
        f"  Checked {checked:,} V1/V2 rows",
        end="\r"
    )

print(
    f"\n✅ V1/V2 alignment verified: "
    f"{checked:,} rows"
)


# ------------------------------------------------------------
# 3. REWRITE OLD FINAL FILE
# ------------------------------------------------------------

print("\n[2/5] Creating final V2 merged file...")

if os.path.exists(FINAL_V2):
    os.remove(FINAL_V2)


# We need to consume V2 only as synthetic rows
v2_stream = pd.read_csv(
    V2_PATH,
    chunksize=100_000,
    low_memory=False
)

v2_buffer = pd.DataFrame()

v2_buffer_pos = 0

synthetic_rows_replaced = 0
total_rows_written = 0
original_rows_seen = 0


def get_next_v2_rows(n):

    global v2_buffer
    global v2_buffer_pos

    parts = []

    remaining = n

    while remaining > 0:

        available = (
            len(v2_buffer)
            - v2_buffer_pos
        )

        if available == 0:

            try:
                v2_buffer = next(
                    v2_stream
                )

                v2_buffer_pos = 0

                available = len(
                    v2_buffer
                )

            except StopIteration:

                raise ValueError(
                    "V2 file ended before "
                    "all synthetic rows were consumed."
                )

        take = min(
            remaining,
            available
        )

        parts.append(
            v2_buffer.iloc[
                v2_buffer_pos:
                v2_buffer_pos + take
            ].copy()
        )

        v2_buffer_pos += take
        remaining -= take

    return pd.concat(
        parts,
        ignore_index=True
    )


# ------------------------------------------------------------
# STREAM OLD FINAL
# ------------------------------------------------------------

first_write = True

for chunk_no, final_chunk in enumerate(
    pd.read_csv(
        OLD_FINAL,
        chunksize=100_000,
        low_memory=False
    ),
    start=1
):

    if "is_synthetic" not in final_chunk.columns:
        raise ValueError(
            "Old final file does not contain "
            "'is_synthetic' column."
        )

    synthetic_mask = (
        pd.to_numeric(
            final_chunk["is_synthetic"],
            errors="coerce"
        )
        .fillna(0)
        .astype(int)
        == 1
    )

    n_synthetic = int(
        synthetic_mask.sum()
    )

    n_original = (
        len(final_chunk)
        - n_synthetic
    )

    original_rows_seen += n_original

    # --------------------------------------------------------
    # Replace only synthetic rows
    # --------------------------------------------------------

    if n_synthetic > 0:

        v2_rows = get_next_v2_rows(
            n_synthetic
        )

        # Transaction IDs must align.
        final_ids = (
            final_chunk.loc[
                synthetic_mask,
                "transaction_id"
            ]
            .astype(str)
            .to_numpy()
        )

        v2_ids = (
            v2_rows[
                "transaction_id"
            ]
            .astype(str)
            .to_numpy()
        )

        if not np.array_equal(
            final_ids,
            v2_ids
        ):
            raise ValueError(
                "Synthetic transaction IDs "
                "do not align between old "
                "final file and V2."
            )

        # Replace calibrated amounts.
        final_chunk.loc[
            synthetic_mask,
            "Amount Received"
        ] = (
            v2_rows[
                "Amount Received"
            ]
            .to_numpy()
        )

        final_chunk.loc[
            synthetic_mask,
            "Amount Paid"
        ] = (
            v2_rows[
                "Amount Paid"
            ]
            .to_numpy()
        )

        synthetic_rows_replaced += (
            n_synthetic
        )

    # --------------------------------------------------------
    # Write chunk
    # --------------------------------------------------------

    final_chunk.to_csv(
        FINAL_V2,
        mode="w" if first_write else "a",
        header=first_write,
        index=False
    )

    first_write = False

    total_rows_written += len(
        final_chunk
    )

    print(
        f"  Chunk {chunk_no:03d} | "
        f"written {total_rows_written:,} | "
        f"synthetic replaced "
        f"{synthetic_rows_replaced:,}",
        end="\r"
    )


# ------------------------------------------------------------
# 4. FINAL COUNTS
# ------------------------------------------------------------

print("\n\n[3/5] Final row-count validation...")

print(
    f"Original rows retained  : "
    f"{original_rows_seen:,}"
)

print(
    f"Synthetic rows replaced : "
    f"{synthetic_rows_replaced:,}"
)

print(
    f"Total rows written      : "
    f"{total_rows_written:,}"
)

if original_rows_seen != EXPECTED_ORIGINAL:
    raise ValueError(
        f"Original row count incorrect: "
        f"{original_rows_seen:,}"
    )

if synthetic_rows_replaced != EXPECTED_SYNTH:
    raise ValueError(
        f"Synthetic row count incorrect: "
        f"{synthetic_rows_replaced:,}"
    )

if total_rows_written != EXPECTED_FINAL:
    raise ValueError(
        f"Final row count incorrect: "
        f"{total_rows_written:,}"
    )

print("✅ Final row count exact")


# ------------------------------------------------------------
# 5. CHECK FINAL FILE METADATA + SIZE
# ------------------------------------------------------------

print("\n[4/5] Checking final file...")

with open(
    FINAL_V2,
    "r",
    encoding="utf-8",
    errors="replace"
) as f:

    header = f.readline().strip()

print("\nFinal header:")
print(header)

size_gb = (
    os.path.getsize(FINAL_V2)
    / (1024 ** 3)
)

print(
    f"\nFinal V2 file size: "
    f"{size_gb:.2f} GB"
)


# ------------------------------------------------------------
# 6. QUICK FINAL DISTRIBUTION CHECK
# ------------------------------------------------------------

print("\n[5/5] Quick final laundering balance check...")

counts = {
    "legitimate": 0,
    "laundering": 0,
    "synthetic": 0
}

for chunk in pd.read_csv(
    FINAL_V2,
    usecols=[
        "Is Laundering",
        "is_synthetic"
    ],
    chunksize=500_000,
    low_memory=False
):

    laundering = pd.to_numeric(
        chunk["Is Laundering"],
        errors="coerce"
    ).fillna(0)

    synthetic = pd.to_numeric(
        chunk["is_synthetic"],
        errors="coerce"
    ).fillna(0)

    counts["laundering"] += int(
        (laundering == 1).sum()
    )

    counts["legitimate"] += int(
        (laundering == 0).sum()
    )

    counts["synthetic"] += int(
        (synthetic == 1).sum()
    )


print(
    f"Legitimate : {counts['legitimate']:,}"
)

print(
    f"Laundering : {counts['laundering']:,}"
)

print(
    f"Synthetic   : {counts['synthetic']:,}"
)

expected_balance = (
    counts["legitimate"]
    == counts["laundering"]
)

if not expected_balance:
    raise ValueError(
        "Final dataset is not exactly 50:50."
    )

if counts["synthetic"] != EXPECTED_SYNTH:
    raise ValueError(
        "Synthetic count in final file is incorrect."
    )

print(
    "\n✅ FINAL DATASET IS EXACTLY 50:50"
)

print("\n" + "=" * 100)
print("CELL 30 COMPLETE")
print("=" * 100)

print(
    "\nFINAL TRAINING FILE:"
)

print(FINAL_V2)

print(
    "\nNext stage:"
)

print(
    "FINAL V2 → feature engineering → "
    "Graph Transformer training → LI-Small external evaluation"
)

====================================================================================================
CELL 30 — FINAL V2 TRAINING DATASET
====================================================================================================
✅ HI-Small_FINAL_transactions_10146336.csv (1.38 GB)
✅ HI-Small_SYNTH_FULL_transactions.csv (0.82 GB)
✅ HI-Small_SYNTH_FULL_V2_transactions.csv (0.83 GB)

[1/5] Validating V1 ↔ V2 transaction alignment...
  Checked 5,067,991 V1/V2 rows
✅ V1/V2 alignment verified: 5,067,991 rows

[2/5] Creating final V2 merged file...
  Chunk 102 | written 10,146,336 | synthetic replaced 5,067,991

[3/5] Final row-count validation...
Original rows retained  : 5,078,345
Synthetic rows replaced : 5,067,991
Total rows written      : 10,146,336
✅ Final row count exact

[4/5] Checking final file...

Final header:
transaction_id,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering,is_synthetic,synthetic_episode_id,typology,source_template_id,template_source_order

Final V2 file size: 1.35 GB

[5/5] Quick final laundering balance check...
Legitimate : 5,073,168
Laundering : 5,073,168
Synthetic   : 5,067,991

✅ FINAL DATASET IS EXACTLY 50:50

====================================================================================================
CELL 30 COMPLETE
====================================================================================================

FINAL TRAINING FILE:
/kaggle/working/AML_GNN_ONLY/data/HI-Small_FINAL_V2_transactions_10146336.csv

Next stage:
FINAL V2 → feature engineering → Graph Transformer training → LI-Small external evaluation

In [51]:
# ============================================================
# CELL 32 — CREATE FINAL V2 PATTERNS.TXT
# ============================================================
#
# Original IBM pattern episodes:
#   unchanged
#
# Synthetic pattern episodes:
#   Amount Received -> V2 calibrated amount
#   Amount Paid     -> V2 calibrated amount
#
# Everything else remains unchanged.
#
# Output:
#   HI-Small_FINAL_V2_Patterns.txt
#
# ============================================================

import os
import csv
import re
import numpy as np
import pandas as pd


# ============================================================
# PATHS
# ============================================================

DATA_DIR = "/kaggle/working/AML_GNN_ONLY/data"

PATTERN_PATH = os.path.join(
    DATA_DIR,
    "HI-Small_FINAL_Patterns.txt"
)

V1_PATH = os.path.join(
    DATA_DIR,
    "HI-Small_SYNTH_FULL_transactions.csv"
)

V2_PATH = os.path.join(
    DATA_DIR,
    "HI-Small_SYNTH_FULL_V2_transactions.csv"
)

OUTPUT_PATH = os.path.join(
    DATA_DIR,
    "HI-Small_FINAL_V2_Patterns.txt"
)

EXPECTED_ORIGINAL_PATTERN_TX = 3_209
EXPECTED_SYNTH_PATTERN_TX = 5_067_991
EXPECTED_TOTAL_PATTERN_TX = (
    EXPECTED_ORIGINAL_PATTERN_TX
    + EXPECTED_SYNTH_PATTERN_TX
)

EXPECTED_BEGIN = 585_076
EXPECTED_END = 585_076
EXPECTED_ID_LINES = 584_706


print("=" * 100)
print("CELL 32 — FINAL V2 PATTERNS.TXT")
print("=" * 100)


# ============================================================
# 1. VERIFY INPUTS
# ============================================================

for path in [
    PATTERN_PATH,
    V1_PATH,
    V2_PATH
]:

    if not os.path.exists(path):

        raise FileNotFoundError(
            f"\nMissing file:\n{path}"
        )

    print(
        "✅",
        os.path.basename(path)
    )


# ============================================================
# 2. LOAD V1 SAMPLE FOR FIELD IDENTIFICATION
# ============================================================

print(
    "\n[1/8] Loading first 500 V1 synthetic amounts..."
)

V1_SAMPLE_N = 500

v1_sample_df = pd.read_csv(
    V1_PATH,
    usecols=[
        "Amount Received",
        "Amount Paid"
    ],
    nrows=V1_SAMPLE_N,
    low_memory=False
)

v1_received_sample = (
    v1_sample_df[
        "Amount Received"
    ]
    .to_numpy(dtype=np.float64)
)

v1_paid_sample = (
    v1_sample_df[
        "Amount Paid"
    ]
    .to_numpy(dtype=np.float64)
)

print(
    f"V1 sample rows: "
    f"{len(v1_received_sample):,}"
)


# ============================================================
# 3. LOAD ALL V2 AMOUNTS
# ============================================================

print(
    "\n[2/8] Loading all V2 calibrated amounts..."
)

v2_received_parts = []
v2_paid_parts = []

for chunk_no, chunk in enumerate(
    pd.read_csv(
        V2_PATH,
        usecols=[
            "Amount Received",
            "Amount Paid"
        ],
        chunksize=500_000,
        low_memory=False
    ),
    start=1
):

    v2_received_parts.append(
        chunk[
            "Amount Received"
        ].to_numpy(dtype=np.float64)
    )

    v2_paid_parts.append(
        chunk[
            "Amount Paid"
        ].to_numpy(dtype=np.float64)
    )

    loaded = sum(
        len(x)
        for x in v2_received_parts
    )

    print(
        f"  Chunk {chunk_no:02d} | "
        f"{loaded:,} rows",
        end="\r"
    )

v2_received = np.concatenate(
    v2_received_parts
)

v2_paid = np.concatenate(
    v2_paid_parts
)

del v2_received_parts
del v2_paid_parts

assert len(v2_received) == EXPECTED_SYNTH_PATTERN_TX
assert len(v2_paid) == EXPECTED_SYNTH_PATTERN_TX

print(
    f"\nV2 received amounts: "
    f"{len(v2_received):,}"
)

print(
    f"V2 paid amounts: "
    f"{len(v2_paid):,}"
)


# ============================================================
# 4. PATTERN LINE CLASSIFICATION
# ============================================================

print(
    "\n[3/8] Inspecting Patterns.txt..."
)


def is_control_line(line):

    s = line.strip()

    if not s:
        return True

    upper = s.upper()

    if (
        upper.startswith("BEGIN")
        or upper.startswith("END")
    ):
        return True

    if (
        s.startswith("id=")
        or s.startswith("ID=")
    ):
        return True

    return False


def detect_delimiter(line):

    candidates = [
        ",",
        "\t",
        "|",
        ";"
    ]

    scores = {
        d: line.count(d)
        for d in candidates
    }

    best = max(
        scores,
        key=scores.get
    )

    if scores[best] > 0:
        return best

    return None


def tokenize(line, delimiter):

    body = line.rstrip(
        "\r\n"
    )

    if delimiter is None:

        return re.split(
            r"\s+",
            body.strip()
        )

    return body.split(
        delimiter
    )


def join_tokens(tokens, delimiter):

    if delimiter is None:
        return " ".join(tokens)

    return delimiter.join(tokens)


# ------------------------------------------------------------
# First pass:
# Find the first 500 synthetic transaction lines.
# ------------------------------------------------------------

sample_pattern_lines = []

pattern_tx_count = 0
original_tx_count = 0

delimiter = None

with open(
    PATTERN_PATH,
    "r",
    encoding="utf-8",
    errors="replace"
) as f:

    for line in f:

        if is_control_line(line):
            continue

        pattern_tx_count += 1

        # First non-control line determines delimiter
        if delimiter is None:
            delimiter = detect_delimiter(line)

        # First 3,209 transaction lines are original IBM
        if pattern_tx_count <= EXPECTED_ORIGINAL_PATTERN_TX:

            original_tx_count += 1

            continue

        # Synthetic transaction lines
        synthetic_position = (
            pattern_tx_count
            - EXPECTED_ORIGINAL_PATTERN_TX
            - 1
        )

        if synthetic_position < V1_SAMPLE_N:

            sample_pattern_lines.append(
                line.rstrip("\r\n")
            )

        if len(sample_pattern_lines) >= V1_SAMPLE_N:

            break


print(
    f"Detected delimiter: "
    f"{delimiter!r}"
)

print(
    f"Original pattern tx encountered: "
    f"{original_tx_count:,}"
)

print(
    f"Synthetic sample lines: "
    f"{len(sample_pattern_lines):,}"
)

if len(sample_pattern_lines) != V1_SAMPLE_N:

    raise ValueError(
        "Could not collect enough synthetic "
        "pattern transaction lines."
    )


# ============================================================
# 5. INFER AMOUNT POSITIONS
# ============================================================

print(
    "\n[4/8] Identifying amount fields..."
)

tokenized_samples = [
    tokenize(
        line,
        delimiter
    )
    for line in sample_pattern_lines
]

max_tokens = max(
    len(tokens)
    for tokens in tokenized_samples
)

received_scores = {}
paid_scores = {}

for token_idx in range(max_tokens):

    received_matches = 0
    paid_matches = 0

    for i, tokens in enumerate(
        tokenized_samples
    ):

        if token_idx >= len(tokens):
            continue

        token = (
            tokens[token_idx]
            .strip()
            .strip('"')
            .strip("'")
        )

        try:
            value = float(token)

        except Exception:
            continue

        if np.isclose(
            value,
            v1_received_sample[i],
            rtol=1e-6,
            atol=1e-6
        ):
            received_matches += 1

        if np.isclose(
            value,
            v1_paid_sample[i],
            rtol=1e-6,
            atol=1e-6
        ):
            paid_matches += 1

    received_scores[
        token_idx
    ] = received_matches

    paid_scores[
        token_idx
    ] = paid_matches


print("\nAmount Received candidate positions:")

for idx, score in sorted(
    received_scores.items(),
    key=lambda x: x[1],
    reverse=True
)[:10]:

    print(
        f"  token {idx}: "
        f"{score}/{V1_SAMPLE_N}"
    )


print("\nAmount Paid candidate positions:")

for idx, score in sorted(
    paid_scores.items(),
    key=lambda x: x[1],
    reverse=True
)[:10]:

    print(
        f"  token {idx}: "
        f"{score}/{V1_SAMPLE_N}"
    )


# ------------------------------------------------------------
# Choose fields
# ------------------------------------------------------------

received_idx = max(
    received_scores,
    key=received_scores.get
)

received_score = received_scores[
    received_idx
]

paid_idx = max(
    paid_scores,
    key=paid_scores.get
)

paid_score = paid_scores[
    paid_idx
]

MIN_MATCH = int(
    V1_SAMPLE_N * 0.90
)

if received_score < MIN_MATCH:

    raise ValueError(
        f"Could not identify Amount Received. "
        f"Best score = "
        f"{received_score}/{V1_SAMPLE_N}"
    )


if paid_score < MIN_MATCH:

    paid_idx = None

    print(
        "\n⚠️ Could not confidently identify "
        "a separate Amount Paid field."
    )

else:

    print(
        f"\n✅ Amount Received token position: "
        f"{received_idx}"
    )

    print(
        f"   Match score: "
        f"{received_score}/{V1_SAMPLE_N}"
    )

    print(
        f"✅ Amount Paid token position: "
        f"{paid_idx}"
    )

    print(
        f"   Match score: "
        f"{paid_score}/{V1_SAMPLE_N}"
    )


# ============================================================
# 6. SHOW FIRST 5 BEFORE/AFTER VALUES
# ============================================================

print(
    "\n[5/8] Checking first five synthetic mappings..."
)

for i in range(5):

    tokens = tokenize(
        sample_pattern_lines[i],
        delimiter
    )

    old_received = float(
        tokens[received_idx]
        .strip()
        .strip('"')
        .strip("'")
    )

    print(
        f"\nSynthetic pattern {i}:"
    )

    print(
        f"  V1 pattern received : "
        f"{old_received:,.6f}"
    )

    print(
        f"  V1 CSV received     : "
        f"{v1_received_sample[i]:,.6f}"
    )

    print(
        f"  V2 CSV received     : "
        f"{v2_received[i]:,.6f}"
    )

    if paid_idx is not None:

        old_paid = float(
            tokens[paid_idx]
            .strip()
            .strip('"')
            .strip("'")
        )

        print(
            f"  V1 pattern paid     : "
            f"{old_paid:,.6f}"
        )

        print(
            f"  V1 CSV paid         : "
            f"{v1_paid_sample[i]:,.6f}"
        )

        print(
            f"  V2 CSV paid         : "
            f"{v2_paid[i]:,.6f}"
        )


# ============================================================
# 7. WRITE FINAL PATTERNS STREAMING
# ============================================================

print(
    "\n[6/8] Writing final V2 Patterns.txt..."
)

if os.path.exists(
    OUTPUT_PATH
):

    os.remove(
        OUTPUT_PATH
    )


tx_index = 0
synthetic_index = 0

begin_count = 0
end_count = 0
id_count = 0

original_tx_written = 0
synthetic_tx_written = 0

with open(
    PATTERN_PATH,
    "r",
    encoding="utf-8",
    errors="replace"
) as fin, open(
    OUTPUT_PATH,
    "w",
    encoding="utf-8",
    newline=""
) as fout:

    for line in fin:

        stripped = line.strip()

        # ----------------------------------------------------
        # CONTROL LINE
        # ----------------------------------------------------

        if is_control_line(line):

            fout.write(
                line
            )

            upper = stripped.upper()

            if upper.startswith("BEGIN"):
                begin_count += 1

            elif upper.startswith("END"):
                end_count += 1

            elif (
                stripped.startswith("id=")
                or stripped.startswith("ID=")
            ):
                id_count += 1

            continue

        # ----------------------------------------------------
        # TRANSACTION LINE
        # ----------------------------------------------------

        tx_index += 1

        # Original IBM pattern transaction
        if tx_index <= EXPECTED_ORIGINAL_PATTERN_TX:

            fout.write(
                line
            )

            original_tx_written += 1

            continue

        # Synthetic pattern transaction
        synthetic_index = (
            tx_index
            - EXPECTED_ORIGINAL_PATTERN_TX
            - 1
        )

        if synthetic_index >= EXPECTED_SYNTH_PATTERN_TX:

            raise ValueError(
                "More synthetic pattern transaction "
                "lines than expected."
            )

        tokens = tokenize(
            line,
            delimiter
        )

        # Replace Amount Received
        tokens[
            received_idx
        ] = f"{v2_received[synthetic_index]:.6f}"

        # Replace Amount Paid
        if paid_idx is not None:

            tokens[
                paid_idx
            ] = f"{v2_paid[synthetic_index]:.6f}"

        # Preserve newline style
        newline = (
            "\r\n"
            if line.endswith("\r\n")
            else "\n"
            if line.endswith("\n")
            else ""
        )

        fout.write(
            join_tokens(
                tokens,
                delimiter
            )
            + newline
        )

        synthetic_tx_written += 1

        if (
            synthetic_tx_written % 500_000
            == 0
        ):

            print(
                f"  Updated "
                f"{synthetic_tx_written:,}/"
                f"{EXPECTED_SYNTH_PATTERN_TX:,} "
                f"synthetic pattern transactions"
            )


# ============================================================
# 8. FINAL VALIDATION
# ============================================================

print(
    "\n[7/8] Final validation..."
)

total_tx_written = (
    original_tx_written
    + synthetic_tx_written
)

print(
    f"Original pattern tx : "
    f"{original_tx_written:,}"
)

print(
    f"Synthetic pattern tx: "
    f"{synthetic_tx_written:,}"
)

print(
    f"Total pattern tx    : "
    f"{total_tx_written:,}"
)

print(
    f"BEGIN lines         : "
    f"{begin_count:,}"
)

print(
    f"END lines           : "
    f"{end_count:,}"
)

print(
    f"ID lines            : "
    f"{id_count:,}"
)


assert (
    original_tx_written
    == EXPECTED_ORIGINAL_PATTERN_TX
)

assert (
    synthetic_tx_written
    == EXPECTED_SYNTH_PATTERN_TX
)

assert (
    total_tx_written
    == EXPECTED_TOTAL_PATTERN_TX
)

assert begin_count == EXPECTED_BEGIN
assert end_count == EXPECTED_END
assert id_count == EXPECTED_ID_LINES

print(
    "\n✅ Transaction counts correct"
)

print(
    "✅ BEGIN/END counts correct"
)

print(
    "✅ Synthetic ID-line count correct"
)


# ------------------------------------------------------------
# Verify file can be reopened
# ------------------------------------------------------------

print(
    "\nChecking output file readability..."
)

output_size_mb = (
    os.path.getsize(
        OUTPUT_PATH
    ) / (1024 ** 2)
)

print(
    f"Output size: "
    f"{output_size_mb:.2f} MB"
)


# ------------------------------------------------------------
# Verify synthetic amount samples
# ------------------------------------------------------------

print(
    "\nVerifying 10,000 synthetic V2 amounts..."
)

VERIFY_N = 10_000

verify_positions = np.linspace(
    0,
    EXPECTED_SYNTH_PATTERN_TX - 1,
    VERIFY_N,
    dtype=np.int64
)

verify_set = set(
    verify_positions.tolist()
)

synthetic_counter = 0
verified = 0

with open(
    OUTPUT_PATH,
    "r",
    encoding="utf-8",
    errors="replace"
) as f:

    for line in f:

        if is_control_line(line):
            continue

        if tx_index == 0:
            pass

        # We need synthetic transaction position
        # based on transaction-line order.
        #
        # This counter starts at zero for all pattern
        # transactions and skips original transactions.

        if synthetic_counter >= EXPECTED_SYNTH_PATTERN_TX:
            break

        # This pass tracks synthetic position differently.
        # Actual synthetic lines begin after 3,209 originals.
        break


# More robust targeted verification:
#
# Re-read transaction lines and verify selected positions.

tx_counter = 0
checks_done = 0

with open(
    OUTPUT_PATH,
    "r",
    encoding="utf-8",
    errors="replace"
) as f:

    for line in f:

        if is_control_line(line):
            continue

        if tx_counter < EXPECTED_ORIGINAL_PATTERN_TX:

            tx_counter += 1
            continue

        syn_pos = (
            tx_counter
            - EXPECTED_ORIGINAL_PATTERN_TX
        )

        if syn_pos in verify_set:

            tokens = tokenize(
                line,
                delimiter
            )

            actual_received = float(
                tokens[received_idx]
                .strip()
                .strip('"')
                .strip("'")
            )

            expected_received = (
                v2_received[syn_pos]
            )

            if not np.isclose(
                actual_received,
                expected_received,
                rtol=1e-6,
                atol=1e-5
            ):

                raise ValueError(
                    f"Amount Received mismatch "
                    f"at synthetic position "
                    f"{syn_pos}"
                )

            if paid_idx is not None:

                actual_paid = float(
                    tokens[paid_idx]
                    .strip()
                    .strip('"')
                    .strip("'")
                )

                expected_paid = (
                    v2_paid[syn_pos]
                )

                if not np.isclose(
                    actual_paid,
                    expected_paid,
                    rtol=1e-6,
                    atol=1e-5
                ):

                    raise ValueError(
                        f"Amount Paid mismatch "
                        f"at synthetic position "
                        f"{syn_pos}"
                    )

            checks_done += 1

        tx_counter += 1

        if (
            tx_counter
            >= EXPECTED_TOTAL_PATTERN_TX
        ):
            break


print(
    f"✅ Verified "
    f"{checks_done:,} synthetic V2 pattern amounts"
)


# ============================================================
# FINAL RESULT
# ============================================================

print("\n" + "=" * 100)
print("✅ CELL 32 COMPLETE")
print("=" * 100)

print(
    "\nFINAL PATTERNS FILE:"
)

print(
    OUTPUT_PATH
)

print(
    f"\nFile size: "
    f"{output_size_mb:.2f} MB"
)

print(
    "\nContents:"
)

print(
    f"  Original IBM pattern transactions : "
    f"{EXPECTED_ORIGINAL_PATTERN_TX:,}"
)

print(
    f"  Synthetic V2 pattern transactions: "
    f"{EXPECTED_SYNTH_PATTERN_TX:,}"
)

print(
    f"  Total pattern transactions        : "
    f"{EXPECTED_TOTAL_PATTERN_TX:,}"
)

print(
    "\n✅ Original pattern data preserved"
)

print(
    "✅ Synthetic pattern structure preserved"
)

print(
    "✅ Synthetic V2 amounts inserted"
)

print(
    "✅ Final Patterns.txt is ready"
)

====================================================================================================
CELL 32 — FINAL V2 PATTERNS.TXT
====================================================================================================
✅ HI-Small_FINAL_Patterns.txt
✅ HI-Small_SYNTH_FULL_transactions.csv
✅ HI-Small_SYNTH_FULL_V2_transactions.csv

[1/8] Loading first 500 V1 synthetic amounts...
V1 sample rows: 500

[2/8] Loading all V2 calibrated amounts...
  Chunk 11 | 5,067,991 rows
V2 received amounts: 5,067,991
V2 paid amounts: 5,067,991

[3/8] Inspecting Patterns.txt...
Detected delimiter: ','
Original pattern tx encountered: 3,209
Synthetic sample lines: 500

[4/8] Identifying amount fields...

Amount Received candidate positions:
  token 5: 500/500
  token 7: 500/500
  token 0: 0/500
  token 1: 0/500
  token 2: 0/500
  token 3: 0/500
  token 4: 0/500
  token 6: 0/500
  token 8: 0/500
  token 9: 0/500

Amount Paid candidate positions:
  token 5: 500/500
  token 7: 500/500
  token 0: 0/500
  token 1: 0/500
  token 2: 0/500
  token 3: 0/500
  token 4: 0/500
  token 6: 0/500
  token 8: 0/500
  token 9: 0/500

✅ Amount Received token position: 5
   Match score: 500/500
✅ Amount Paid token position: 5
   Match score: 500/500

[5/8] Checking first five synthetic mappings...

Synthetic pattern 0:
  V1 pattern received : 134.510000
  V1 CSV received     : 134.510000
  V2 CSV received     : 2,486.634036
  V1 pattern paid     : 134.510000
  V1 CSV paid         : 134.510000
  V2 CSV paid         : 2,486.634036

Synthetic pattern 1:
  V1 pattern received : 470.645953
  V1 CSV received     : 470.645953
  V2 CSV received     : 4,683.227657
  V1 pattern paid     : 470.645953
  V1 CSV paid         : 470.645953
  V2 CSV paid         : 4,683.227657

Synthetic pattern 2:
  V1 pattern received : 216.758051
  V1 CSV received     : 216.758051
  V2 CSV received     : 3,220.606684
  V1 pattern paid     : 216.758051
  V1 CSV paid         : 216.758051
  V2 CSV paid         : 3,220.606684

Synthetic pattern 3:
  V1 pattern received : 9,181.159823
  V1 CSV received     : 9,181.159823
  V2 CSV received     : 15,926.710654
  V1 pattern paid     : 9,181.159823
  V1 CSV paid         : 9,181.159823
  V2 CSV paid         : 15,926.710654

Synthetic pattern 4:
  V1 pattern received : 14,238.152936
  V1 CSV received     : 14,238.152936
  V2 CSV received     : 17,708.399934
  V1 pattern paid     : 14,238.152936
  V1 CSV paid         : 14,238.152936
  V2 CSV paid         : 17,708.399934

[6/8] Writing final V2 Patterns.txt...
  Updated 500,000/5,067,991 synthetic pattern transactions
  Updated 1,000,000/5,067,991 synthetic pattern transactions
  Updated 1,500,000/5,067,991 synthetic pattern transactions
  Updated 2,000,000/5,067,991 synthetic pattern transactions
  Updated 2,500,000/5,067,991 synthetic pattern transactions
  Updated 3,000,000/5,067,991 synthetic pattern transactions
  Updated 3,500,000/5,067,991 synthetic pattern transactions
  Updated 4,000,000/5,067,991 synthetic pattern transactions
  Updated 4,500,000/5,067,991 synthetic pattern transactions
  Updated 5,000,000/5,067,991 synthetic pattern transactions

[7/8] Final validation...
Original pattern tx : 3,209
Synthetic pattern tx: 5,067,991
Total pattern tx    : 5,071,200
BEGIN lines         : 585,076
END lines           : 585,076
ID lines            : 584,706

✅ Transaction counts correct
✅ BEGIN/END counts correct
✅ Synthetic ID-line count correct

Checking output file readability...
Output size: 574.45 MB

Verifying 10,000 synthetic V2 amounts...
✅ Verified 10,000 synthetic V2 pattern amounts

====================================================================================================
✅ CELL 32 COMPLETE
====================================================================================================

FINAL PATTERNS FILE:
/kaggle/working/AML_GNN_ONLY/data/HI-Small_FINAL_V2_Patterns.txt

File size: 574.45 MB

Contents:
  Original IBM pattern transactions : 3,209
  Synthetic V2 pattern transactions: 5,067,991
  Total pattern transactions        : 5,071,200

✅ Original pattern data preserved
✅ Synthetic pattern structure preserved
✅ Synthetic V2 amounts inserted
✅ Final Patterns.txt is ready